### ISSUE TITLE
Report whether a plugin can be ESL'ified (FO4, SSE)

### ISSUE THREAD

**Issue by Freso** [loot/loot#1002]
The ESL flag introduced for the Creation Club with FO4 and SSE has made small patches feasible again, without having worry about the dreaded 255 plugins limit. However, ESL is still not widely understood by the wider community, meaning some new plugins don't have it set even if it could without any issues, and there are also still a lot of older plugins around that could easily and without any issues have the ESL flag set on them. It would be great if LOOT could show these plugins, possibly as a toggle in the settings.

Conditions:
- Game should be Fallout 4 or Skyrim Special Edition (ESL flag isn't known to any older engines).
- ESL flag should not already be set (by flag or by `.esl` extension).
- Any records in a plugin should not have Form IDs outside of the $800–$FFF range.

**Comment by WrinklyNinja** [comment]
This can be done without too much effort, but is it really something we should be proactively informing users about? I'd have thought that anyone who cares would be fine speculatively opening TES5Edit and running a script or whatever there to identify such plugins. It seems a bit feature-creepy to me.

**Comment by Freso** [comment]
Having thought about this, I actually think this is kind of in the same realm as plugin cleaning. It's not something you have to do, but it's something you can do to make your load order a bit smoother if you care to put the work in. If we're informing about dirty plugins, I think we should also inform about ESL'able plugins—but maybe hiding it (together with `dirty` reporting?) behind a toggle?

@eFrysTon, do you have a take on this?

**Comment by eFrysTon** [comment]
well, I guess it's useful information. And if you are doing #1003 then you can just collect the information at the same time

**Comment by WrinklyNinja** [comment]
> If we're informing about dirty plugins, I think we should also inform about ESL'able plugins—but maybe hiding it (together with dirty reporting?) behind a toggle?

The difference I see is that cleaning can help avoid issues, this "just" helps you stuff more plugins into your load order. I'd generally recommend cleaning, but I'd probably say "don't bother unless you need to" about ESLification.

Getting the check to happen isn't much work once #1003 is implemented, but it's extra UI stuff to report on the outcome, and I'd rather not have a toggle because that's even more. I don't feel strongly enough about this to reject it outright, but it's not something I'm interested in implementing myself, unless anyone's got a convincing argument.

**Comment by Freso** [comment]
Let's wontfix this for now then. Anyone interested in ESL'ing their load order will need to fire of xEdit anyway, at which point they might as well use `-PseudoESL` or an xEdit script. If someone has a (more) compelling argument in the future, this can be reopened and reconsidered.
