### ISSUE TITLE
Report whether ESL plugins have new records with invalid Form IDs

### ISSUE THREAD

**Issue by Freso** [loot/loot#1003]
xEdit versions prior to it having ESL support didn't check whether a plugin was ESL'ifiable and would happily set the flag, even if the plugin had new records outside of the $800–$FFF range. It could be nice to have a LOOT-wide error message/condition for these plugins without having to rely on adding this per-plugin-per-CRC to the masterlist (which would still only catch ones that have made it to circulation, not ones users have managed to break on their own).

(While previous xEdit versions can be at fault, it's also always possible for people to hexedit or otherwise cause ESL-breakage, so it seems like a good check to have regardless.)

**Comment by WrinklyNinja** [comment]
Like #1002, this can be done, and unlike #1002 I think it makes sense to tell people about any such invalid plugins they've got.

**Comment by WrinklyNinja** [comment]
What's the severity of having an ESL with new records outside the valid range, does it cause problems in game, or do they get ignored or something else? Should LOOT treat one like other types of invalid plugin and refuse to load it (and show an error message saying so), or should it still accept it but show a warning?

**Comment by Freso** [comment]
I *think* it'll cause CTDs, but I'm not sure. I'll try and make a "bad" ESL and start FO4 with it.

**Comment by eFrysTon** [comment]
They simply overflow into the namespace of other light modules.

So suppose you got a file containing a record with object ID 001234 that's marked as ESL, and it gets mapped into FE002xxx, the record will end up at FE003234, possibly crashing into whatever record the light module that's supposed to load at FE003xxx contains.

**Comment by WrinklyNinja** [comment]
Ah, like how over 4096 ESLs used to overflow into your savegame's records... LOOT should then probably show an error/warning for that but still load the plugin.

**Comment by Ortham** [comment]
Anyone want to bikeshed over the error message text before I implement this? @CptMcSplody?

I'll start by suggesting

> Error: This plugin contains records that have FormIDs outside the valid range for an ESL plugin, and may break other ESL plugins.

**Comment by CptMcSplody** [comment]
> > Error: This plugin contains records that have FormIDs outside the valid range for an ESL plugin, and may break other ESL plugins.

You could lose the `and may break other ESL plugins.` as it leaves room for misinterpretation. 
Knowing it's an invalid flag should be enough, but you could ask @ElminsterAU what
could happen if an invalid flag is applied to be certain.

**Comment by CptMcSplody** [comment]
Yeah I having asked @ElminsterAU I would say to something like.

> Error: This plugin contains records that have FormIDs outside the valid range for an ESL plugin.
    Using this plugin will cause irreversible damage to your game saves.

**Comment by Ortham** [comment]
OK, added with your wording in 8335a77476ed380989378e564d60bfccadd8d84c.

**Comment by Ortham** [comment]
The commit is now ea27177a23a232bd88310c112728b87aeb9122bd, which has been merged into `dev`, so closing this.
