### ISSUE TITLE
LOOT shows "blank" window if "start in" is not LOOT folder

### ISSUE THREAD

**Issue by Freso** [loot/loot#1004]
If LOOT "starts in" anywhere other than where the LOOT executable is, it will show a "blank window": a white window with a very miniscule text that says "File not found." (though you'll have to copy/paste it to be able to actually read it).

This is also a relatively common error that MO users is getting, but which is not appearing for them outside of MO since their shortcuts will have been set up differently.

Steps to reproduce:
1) Create shortcut to `LOOT.exe`
2) Edit shortcut and change "Start in" to a directory other than where `LOOT.exe` lives
3) Run LOOT through this shortcut

Expected results:
That LOOT opens up just fine, or at the very least gives a meaningful error message.

**Comment by WrinklyNinja** [comment]
A fix for this would be to use the executable directory instead of the current working directory when loading resources. AFAIK there's no standard library way to obtain that, but hopefully there's a straightforward Windows API function for it.

**Comment by Freso** [comment]
I'm thinking it might be possible to get path of `LOOT.exe` and find things relative to that (using std or Win API library functions), essentially ignoring "Start in".

**Comment by WrinklyNinja** [comment]
That's what I meant by my comment above.

**Comment by WrinklyNinja** [comment]
Fixed in 495a3ca208474b9bba55e4b65b61c8e7fdc57581.
