### ISSUE TITLE
add a --auto-sort parameter to loot.exe

### ISSUE THREAD

**Issue by ElminsterAU** [loot/loot#1005]
If present, the parameter would automatically click the "sort" button on start.

And either have it automatically apply the result and close itself, or maybe have additional parameters for that:

--auto-apply (always automatically apply after sorting if no error occurred)
--auto-close (always automatically close LOOT after applying the sort order)

The 3 switches could actually be completely independent of each other.

**Comment by WrinklyNinja** [comment]
I don't see why not.

**Comment by ElminsterAU** [comment]
Sorry, only just noticed this. I'll give it a try later today. Thanks for implementing it!

**Comment by Ortham** [comment]
Done as of 24ae67b2018e58eb056e9310131ee1df44190578.
