### ISSUE TITLE
Cyclic interaction detected Need Help

### ISSUE THREAD

**Issue by Dragontailgaming** [loot/loot#1007]
I have this issue in loot and i need fixes pls 
Cyclic interaction detected between "Landscape Fixes For Grass Mods.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Open Cities Skyrim.esp, Verdant - A Skyrim Grass Plugin SSE Version.esp, Landscape Fixes For Grass Mods.esp

**Comment by CptMcSplody** [comment]
@Dragontailgaming Hi can you post a full debug log, if your not sure how to do that please see https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html

**Comment by Dragontailgaming** [comment]
is this correct
Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Failed to sort plugins. Details: Cyclic interaction detected between "Landscape Fixes For Grass Mods.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Open Cities Skyrim.esp, Verdant - A Skyrim Grass Plugin SSE Version.esp, Landscape Fixes For Grass Mods.esp
    at J.e.then.then.then.e (http://loot/ui/app.bundle.js:1:481687)

**Comment by CptMcSplody** [comment]
@Dragontailgaming No, please read the linked guide above.

**Comment by Dragontailgaming** [comment]
i got mostly the same thing with the debug log mode on:
Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Failed to sort plugins. Details: Cyclic interaction detected between "Landscape Fixes For Grass Mods.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Open Cities Skyrim.esp, Verdant - A Skyrim Grass Plugin SSE Version.esp, Landscape Fixes For Grass Mods.esp
    at J.e.then.then.then.e (http://loot/ui/app.bundle.js:1:481687)

**Comment by Dragontailgaming** [comment]
Fixed it! Thanks!
