### ISSUE TITLE
Check if plugin HEDR version is equal or greater than value corresponding to latest game update

### ISSUE THREAD

**Issue by SYNStack** [loot/loot#1009]
Hi, interested in LOOT checking plugins for their HEDR version and marking them "Obsolete" in the output if they are not equal or greater than the value corresponding to the latest update of the game.

Specifically the use-case for this would be weeding out unconverted Fallout 3 plugins from a Tale of Two Wastelands load order without manually adding every F3 plugin in existence to the masterlist.

For New Vegas (if I'm not mistaken), this value would be 1.32.

New Vegas plugin:
![FNV HEDR](https://i.imgur.com/ULapAz4.png)

Fallout 3 plugin:
![F3 HEDR](https://i.imgur.com/pTmyIJM.png)

**Comment by RoyBatty64** [comment]
The minimum valid Fallout NV HEDR version is indeed 1.32

**Comment by SYNStack** [comment]
Maybe this could have a metadata field added for a specifiable version value? "minversion: 1.34". Would be useful if we use 1.35 to validate TTW 3.x mods

**Comment by Ortham** [comment]
This is now implemented in the `warn-on-header-versions` branch, the message displayed is:

> - Warning: This plugin has a header version of X, which is less than the game's minimum supported header version of Y.

I didn't use "obsolete" as that suggests the plugin has been replaced with another version, which isn't necessarily the case. I'm open to changing the message though.

The minimum supported header version is configurable per game in LOOT's `settings.toml`, but not in the GUI as it's not a setting users should generally have to tweak. I've set the default values to:

| Game | Minimum Header Version |
|--------|-----------------------------|
| Oblivion | 0.8 |
| Skyrim | 0.94 |
| Skyrim SE | 1.7 |
| Skyrim VR | 1.7 |
| Fallout 3 | 0.94 |
| Fallout: New Vegas | 1.32 |
| Fallout 4 | 0.95 |
| Fallout 4 VR | 0.95 |

I don't know if these values are correct - other than the FO3 and FONV values, I got them by looking at header versions in the games' plugins, and for the VR games I guessed they'd be the same as their non-VR equivalents. It would be good to get feedback on whether the values above are correct.

**Comment by CptMcSplody** [comment]
###### Skyrim SE 1.7
https://user-images.githubusercontent.com/1944639/47952821-3ba68c00-df6d-11e8-8359-077c6cea759e.png

**Comment by Ortham** [comment]
@Arthmoor, @ElminsterEU, are you able to comment on accuracy of the above minimum header versions?

**Comment by ElminsterAU** [comment]
```pascal
  if wbGameMode = gmFNV then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '1.34'
  else if wbGameMode = gmFO3 then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '0.94'
  else if wbGameMode = gmTES3 then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '1.30'
  else if wbGameMode = gmTES4 then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '1.0'
  else if wbIsSkyrim then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '1.7'
  else if wbIsFallout4 then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '0.95'
  else if wbIsFallout76 then
    Header.RecordBySignature['HEDR'].Elements[0].EditValue := '68.0';
```
here is what xEdit currently uses when creating a new module

**Comment by Arthmoor** [comment]
So far as I know that list of minimum header versions is correct.

**Comment by Ortham** [comment]
Thanks, I'll keep the values as they are then.

**Comment by Ortham** [comment]
Done in c63fcee9770cca2374b09b8b0b5a4e6320811974.
