### ISSUE TITLE
Loot doesn't start no matter what

### ISSUE THREAD

**Issue by Wowzabunny** [loot/loot#1013]
Hello

My loot just started to randomly stop working. Bitdefender detected it as malware, I made an exception for it but nothing starts when I run it.

%localappdata% has a loot folder but I cant find settings.toml for me to edit either...

Ive tried reinstalling LOOT in different locations.
Ive tried to delete the LOOT folder in %localappdata&
Ive downloaded the newest version.

**Comment by pStyl3** [comment]
In case you installed LOOT 0.13.2, please uninstall that version, as we will release LOOT 0.13.3 shortly.

Regarding Bitdefender, it could be it's Firewall that is blocking LOOT. See here for more info:
https://github.com/loot/skyrimse/issues/322

**Comment by WrinklyNinja** [comment]
LOOT v0.13.3 is now [released](https://github.com/loot/loot/releases/tag/0.13.3), so try again with that.

**Comment by Wowzabunny** [comment]
Thank you for your responses, I installed LOOT 0.13.2

Turns out that Bitdefender's firewall was blocking LOOT, but even after I allowed it, it still won't start.

I managed to find some sort of dump files, not sure if they are right

[loot.exe.18648.zip](https://github.com/loot/loot/files/2372511/loot.exe.18648.zip)

**Comment by WrinklyNinja** [comment]
That dump isn't useful to me, sorry. If you delete your %LOCALAPPDATA%\LOOT folder and re-run LOOT, does it get created? If it does, try creating a settings.toml file there, and put `enableDebugLogging = true` in it, then re-run LOOT. If that creates a debug log, upload it.

**Comment by Wowzabunny** [comment]
Hi, sorry about that. I Uninstalled Bitdefender and it now works. Very strange as it worked with it installed for a long time and then suddenly wouldn't start one day. Thank you for the help.

**Comment by WrinklyNinja** [comment]
OK, closing this then.
