### ISSUE TITLE
Application Icon artifact with Windows 10 task bar setting `use small buttons`.

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1016]
Before
https://i.imgur.com/IAeOamS.png
![image](https://user-images.githubusercontent.com/1944639/45788577-5e0d7000-bc73-11e8-93b8-4b3094de5f27.png)

After
https://i.imgur.com/AsZ7vN7.png
![image](https://user-images.githubusercontent.com/1944639/45788580-62398d80-bc73-11e8-9fd6-f15dc0a5cbef.png)

**Comment by WrinklyNinja** [comment]
The larger icon also has a black bar on the left, it looks like the SVG isn't being rasterized correctly. I may need to make changes to [svg_to_ico](https://github.com/WrinklyNinja/svg_to_ico).

**Comment by WrinklyNinja** [comment]
Hmm, I can't actually see this myself, which makes it a bit hard to test... @CptMcSplody do you have a high DPI screen? If not, what's your graphics card/drivers?

**Comment by CptMcSplody** [comment]
40" 3,840 × 2,160. 
![image](https://user-images.githubusercontent.com/1944639/45922255-7624ff80-bebe-11e8-8479-4c8e34bdf677.png)

I changed scaling recently
![image](https://user-images.githubusercontent.com/1944639/45922257-a2d91700-bebe-11e8-9395-d422ee861e5b.png)
and 
![image](https://user-images.githubusercontent.com/1944639/45922264-dae05a00-bebe-11e8-979e-6ca8b84a8133.png)

But altering those setting doesn't cause it to happen straight away.
Shrugs, can't really nail it down. It only happens once and a while, but stays until I sign out.
I'll try and find some steps to replicate it.

**Comment by WrinklyNinja** [comment]
File a bug with Windows. 😛
