### ISSUE TITLE
Auto expand edit Meta-data screen on opening

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1019]
It can be quite difficult to navigate some parts of the edit Meta-data with the default height.
Can the edit Meta data screen auto expand on opening to cover the right panel.

For example the group selection with default size.
https://i.imgur.com/3QpSfca.png

And just over half way.
https://i.imgur.com/f8N1QrQ.png

**Comment by WrinklyNinja** [comment]
ArkianSoji [suggested](https://afkmods.iguanadons.net/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=174131) to extend the groups list up like this:

![515799615_lootsugestionexample thumb png 6b07cffbe2618014a25e5462dd248af7](https://user-images.githubusercontent.com/2430738/46194143-7119e300-c2f8-11e8-85fb-2cbce0ab863e.png)

**Comment by CptMcSplody** [comment]
Yeah that would work as well. The main thing was to just to be able to see more of the groups at once.

**Comment by CptMcSplody** [comment]
Fixed in commit https://github.com/loot/loot/commit/30f9fdb
