### ISSUE TITLE
Limit changes to Group editor layout on loading & Group addition.

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1020]
Currently the group editor will change its layout a lot between loads.
It will also change with the addition of new groups or removal.
<img src="https://i.imgur.com/JgGD0pM.png" height="150" width="175">
Which can be rather confusing if the groups start to get clumped or cross each other.
As the number of custom groups increases this becomes more of an issue.
If there was a way to limit these changes between loads/changes.
So that it would keep it's structure. I think it would remove some interference.
<img src="https://i.imgur.com/QUUzo0D.png" height="150" width="175">

**Comment by CptMcSplody** [comment]
If it's producing consistent layouts then yes I think it's definitely worth the trade off.

**Comment by CptMcSplody** [comment]
The flow from start to finish is a lot easier to see. One extra tweak would be to make the arrows between nodes slightly bigger.

**Comment by Ortham** [comment]
Like this?

![screenshot 61](https://user-images.githubusercontent.com/2430738/47615992-c6d7db80-daae-11e8-83a9-3541014151f8.png)

**Comment by CptMcSplody** [comment]
Yes, exactly like that.

**Comment by Ortham** [comment]
Done in f35161c3108d0777dc3fa614440ebcf31be6f0b9.

**Comment by CptMcSplody** [comment]
Thanks
