### ISSUE TITLE
Loot unable to detect plugins

### ISSUE THREAD

**Issue by Siren3484** [loot/loot#1028]
I currently have a total of 93 active plugins for Skyrim. Yet loot only detects a total of 83 while it states that only 72 are active. Again, I have 93 active. It's been an ongoing issue. I've reinstalled and regularly updated the program to no avail. Help?

**Comment by WrinklyNinja** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
