### ISSUE TITLE
'getElementsByClassName' message on startup & UI unresponsive upon entering settings menu.

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1032]
```json
] [error
]: Chromium console message from http: //loot/ui/app.bundle.js at line 5008: TypeError: Cannot read property 'getElementsByClassName' of null
    at Object.entries.forEach (http: //loot/ui/app.bundle.js:4893:2828)
    at Array.forEach (<anonymous>)
    at HTMLElement.addRow (http: //loot/ui/app.bundle.js:4893:2800)
    at Va.e.games.forEach.e (http: //loot/ui/app.bundle.js:5008:2271)
    at Array.forEach (<anonymous>)
    at Va (http: //loot/ui/app.bundle.js:5008:2228)
    at as.then.then.t (http: //loot/ui/app.bundle.js:5564:29079) 
```
![image](https://user-images.githubusercontent.com/1944639/46581810-77196d80-ca36-11e8-9870-6e2d39bd2558.png)

I then closed the message and opened settings to turn on debug logging.
The Settings entries were not displaying correctly.
The UI became unresponsive when I used cancelled setting changes and LOOT could only be closed.

I'm trying to find a way to replicate this to get some better information, no luck so far.

**Comment by WrinklyNinja** [comment]
I can see where this is happening, but I'm at a loss as to how, it's failing because it's got null instead of a reference to the table row it just added, but it should have just added the row...

**Comment by CptMcSplody** [comment]
I've only had it happen twice in nearly 100+ runs. No errors since opening this issue.

**Comment by CptMcSplody** [comment]
@Ortham I think this can be closed, I've can't replicate it, and have only seen reports of it happening while running LOOT through MO2.

**Comment by Ortham** [comment]
OK, closing this then.

**Comment by Ortham** [comment]
Re-opening this as it's been reported on the [official thread](https://afkmods.iguanadons.net/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=174530).

**Comment by neokio** [comment]
I just received this error for the first time after a dozen or so error-free launches.
Relaunching MO2 fixed the problem.

**Comment by cygarniczka** [comment]
![loot](https://user-images.githubusercontent.com/17316115/61080434-094e0800-a3f3-11e9-9e46-e17403f38750.jpg)
I get this each time I run LOOT out of MO2 first time. Running it second time does not give me this error.

**Comment by pStyl3** [comment]
@cygarniczka Do you still have this problem? If yes, could you do the following?
- Uninstall LOOT
- Delete your LOOT folder in `C:\%localappdata%\` in case it's still present
- Intall LOOT
- Goto `C:\%localappdata%\LOOT\` and create a file named `settings.toml`
- Open that file with Notepad or Notepad++ and enter the following line:
`enableDebugLogging = true`
- Save and close the file.
- Start LOOT

If the issue resurfaced once more, you now should have a file called `LOOTDebugLog.txt` inside of `C:\%localappdata%\LOOT\`. Please upload the log file here.

**Comment by rioadio** [comment]
This is my LOOTDebugLog after doing your instructions. Could you please help me?
Thanks!
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3800878/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Try running the game launcher, LOOT can't detect any installed games, which probably means its registry entry is missing.

**Comment by rioadio** [comment]
I did that. But it's not working.

**Comment by CptMcSplody** [comment]
Closing as I haven't experienced this since the change to add new row. It was a regular occurance before that change.

> The “Add New Row” icon button in editable tables has been replaced by text-only button, and its implementation tweaked to reduce the chance of breakage.
