### ISSUE TITLE
Loot cannot locate games

### ISSUE THREAD

**Issue by ThomasForthe** [loot/loot#1033]
Loot refuses to access any games even with manual path set. Latest version.

**Comment by WrinklyNinja** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Ortham** [comment]
Closing this as there have been a few releases since the original issue was reported.
