### ISSUE TITLE
[Linux] error setting game path

### ISSUE THREAD

**Issue by VaiN474** [loot/loot#1035]
I'm trying to get LOOT working in Ubuntu 18.04 LTS
Loot Version 0.13.1 (build 051e4dd) latest Linux binary from Bintray here: https://bintray.com/wrinklyninja/loot
(Thank you for that by the way)

I was able to run the binary after installing the following dependencies: libcurl4-openssl-dev libx11-dev libboost-log-dev libboost-date-time-dev libboost-thread-dev libboost-filesystem-dev libboost-locale-dev libboost-iostreams-dev libssl-dev libhttp-parser-dev

libhttp-parser.so.2.1 wasn't found, but fixed with:
sudo ln -s /usr/lib/x86_64-linux-gnu/libhttp_parser.so.2 /usr/lib/x86_64-linux-gnu/libhttp_parser.so.2.1

The app seems to be running fine.

When manually setting the path to Skyrim I recieve the following error message:
[error]: libloadorder failed to create a game handle. Details: A local data path must be supplied on non-Windows platforms

My Skyrim install path: /home/vain/.steam/steam/steamapps/common/Skyrim/

It's a local data path without any symlinks. I'm not sure how to resolve this on my end.

**Comment by Ortham** [comment]
You need to set the `local_path` for Skyrim in LOOT's `settings.toml` to point to whatever the equivalent to `%LOCALAPPDATA%\Skyrim` is on Linux. There's no GUI option to configure this. For example, this is what I've got on Windows:

```
enableDebugLogging = true
updateMasterlist = false
lastVersion = "0.13.4"
lastGame = "Skyrim Special Edition"
enableLootUpdateCheck = true
language = "en"
game = "auto"
[[games]]
	branch = "v0.13"
	folder = "Skyrim Special Edition"
	repo = "https://github.com/loot/skyrimse.git"
	type = "Skyrim Special Edition"
	registry = "Software\\Bethesda Softworks\\Skyrim Special Edition\\Installed Path"
	name = "TES V: Skyrim Special Edition"
	local_path = ""
	path = "C:\\Games\\Steam\\steamapps\\common\\Skyrim Special Edition\\"
	master = "Skyrim.esm"
```

`local_path` needs to be non-empty on Linux, because LOOT can't resolve `%LOCALAPPDATA%` to find it.

**Comment by VaiN474** [comment]
There was no `settings.toml` file, so I created one at `/home/vain/.config/LOOT/` as that's where the documentation suggests it would have been saved. I gave it the following content:

````
lastVersion = "0.13.1"
updateMasterlist = true
language = "en"
enableDebugLogging = true
enableLootUpdateCheck = true
game = "auto"
lastGame = "Skyrim"
[[games]]
	path = "/home/vain/.steam/steam/steamapps/common/Skyrim/"
	repo = "https://github.com/loot/skyrim.git"
	type = "Skyrim"
	local_path = "/home/vain/.config/LOOT/"
	folder = "Skyrim"
	name = "TES V: Skyrim"
	master = "Skyrim.esm"
	registry = "Software\\Bethesda Softworks\\Skyrim\\Installed Path"
	branch = "v0.13"
````
When I run the app it still auto-opens the settings and when hitting apply I get a new `std::bad_alloc` error now.
````
[17:51:53.436973] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[17:51:53.452743] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[17:51:54.448583] [error]: Exception while executing query: std::bad_alloc
[17:51:59.552819] [error]: Exception while executing query: std::bad_alloc
[17:51:59.554361] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
````

**Comment by Ortham** [comment]
`/home/vain/.config/LOOT/` isn't Skyrim's local app data directory, the path should be to the directory that has Skyrim's `plugins.txt` in it.

**Comment by Ortham** [comment]
The Linux builds are done on Ubuntu 14.04, so there's probably some incompatibility somewhere relating to that - I think I remember building and running LOOT on 18.04 earlier this year.

**Comment by 65b** [comment]
Building loot-api from 0.13.8 and linking loot HEAD against that seems to work on Arch. Had various linking issues with boost requiring disabling static libs. Had to hack the CMakeLIst.txt for loot to use the local loot-api package.

**Comment by Ortham** [comment]
@65b Can you share what you did to get it working, for the benefit of anyone else trying to do the same?

**Comment by TheRealDannyBoy** [comment]
@65b Could you share the steps you took?  I'm trying to compile on Arch as well.

**Comment by Ortham** [comment]
For any future readers, apocalyptech on Discord was able to get LOOT built and running on Arch, and wrote up their experience [here](http://apocalyptech.com/games/loot-linux/), maybe it'll help you.

Closing this as there have been several releases since the original issue was reported.
