### ISSUE TITLE
LOOT having an issue with multipul plugins.

### ISSUE THREAD

**Issue by captice** [loot/loot#1036]
My LOOT is having a panic attack when sorting the plugins for my Skyrim SE. 
This is the error i get:
Failed to sort plugins. Details: Cyclic interaction detected between "YOT - Sacrosanct.esp" and "Lock_Overhaul.esp". Back cycle: Lock_Overhaul.esp, YOT - Lock Overhaul.esp, Sacrosanct - Vampires of Skyrim.esp, YOT - Sacrosanct.esp

I don't know why its flipping out but i thought to bring it to your attention.

**Comment by CptMcSplody** [comment]
@captice I made a change which should resolve sorting errors for YOT. Can you try sorting again?

**Comment by captice** [comment]
@CptMcSplody That did the trick. no more weird recycling error message of two mods conflicting when there is no conflicts and i can now save my LOOT load order as it should be. thnx

**Comment by CptMcSplody** [comment]
@captice You're welcome. Thanks for confirming.
