### ISSUE TITLE
LOOT reporting false ITM errors?

### ISSUE THREAD

**Issue by DonQuixoteIII** [loot/loot#1038]
Loot is using SSEEdit ver. 3.2.4.  It is reporting ITM errors that SSEEdit ver. 3.2.1  does not clean.  (reports 0 ITM records removed)  I will also try to message the xEdit group.

**Comment by Ortham** [comment]
I don't see the problem, a newer version of SSEEdit can clean more than the version you're using, why not upgrade to it?

**Comment by Ortham** [comment]
Closing as invalid.
