### ISSUE TITLE
Failed to sort plugins. Details: Cyclic interaction detected between skyrim se

### ISSUE THREAD

**Issue by GounalakisOrestis** [loot/loot#1043]
Failed to sort plugins. Details: Cyclic interaction detected between "EBT - skyBirds Patch.esp" and "Cutting Room Floor.esp". Back cycle: Cutting Room Floor.esp, Landscape Fixes For Grass Mods.esp, skyBirds_SSE.esp, EBT - skyBirds Patch.esp

if I remove the EBT - skyBirds Patch.esp everything works
https://www.nexusmods.com/skyrimspecialedition/mods/2357

**Comment by Ortham** [comment]
@CptMcSplody can you help with this?

**Comment by CptMcSplody** [comment]
@Ortham Yeah I'll have a look.

**Comment by GounalakisOrestis** [comment]
nice everything works now
