### ISSUE TITLE
Failed to sort plugins. Details: Cyclic interaction detected between "DynDOLOD.esm" and "AcquisitiveSoulGemMultithreaded.esp". Back cycle: AcquisitiveSoulGemMultithreaded.esp, DynDOLOD.esm

### ISSUE THREAD

**Issue by WolfyJRB** [loot/loot#1046]
I have no idea how to fix this. need help fixing this 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2568962/LOOTDebugLog.txt)

**Comment by WolfyJRB** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2568965/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
Need more details.

Can you enable debug logging in LOOT's settings? see see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for details.

**Comment by WolfyJRB** [comment]
How do i upload a esm and esp file?

**Comment by CptMcSplody** [comment]
An archive such as a `.zip`,`.rar` or `.7z`. Try the test build I linked above first, I might not need the files if I can see the message from that version of LOOT.

**Comment by WolfyJRB** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2568973/LOOTDebugLog.txt)

**Comment by WolfyJRB** [comment]
also the loot version says it can't find skse64 even though i have it installed i may need to just replace the files

**Comment by CptMcSplody** [comment]
That one is expected, it's due to a change in conditional checking which isn't updated in the masterlist yet. Your SKSE is fine.

**Comment by CptMcSplody** [comment]
Is `AcquisitiveSoulGemMultithreaded.esp` listed as a master in `DynDOLOD.esm`?
Which version of DynDOLOD are you using?

**Comment by WolfyJRB** [comment]
version 2.47beta, from the S.T.E.P forum

**Comment by CptMcSplody** [comment]
If your using MO2 you can see a plugins masters if you hover over a plugin.
![image](https://user-images.githubusercontent.com/1944639/48308064-0264b200-e553-11e8-9233-55992c3f0345.png)
If AcquisitiveSoulGemMultithreaded.esp is listed as a master of DynDOLOD.esm then it not something LOOT can solve.

**Comment by WolfyJRB** [comment]
yep its listed as a master and if i use ssedit it tells me that DynDOLOD.esm must be loaded before AcquisitiveSoulGemMultithreaded.esp

**Comment by CptMcSplody** [comment]
Do you have `AcquisitiveSoulGemMultithreaded.esp` flagged as an `ESM` or `ESL`?

**Comment by WolfyJRB** [comment]
there is no flag on AcquisitiveSoulGemMultithreaded.esp in my load order.
Here is my load order
[loadorder.txt](https://github.com/loot/loot/files/2568981/loadorder.txt)

**Comment by CptMcSplody** [comment]
@WolfyJRB I going to run DynDOLOD with a basic stup and see if I have any issues after with sorting.
🤷‍♂️

**Comment by CptMcSplody** [comment]
![image](https://user-images.githubusercontent.com/1944639/48308296-71dda000-e559-11e8-8c53-10343c39c910.png)
Mine generated & sorts fine, no `AcquisitiveSoulGemMultithreaded.esp` in `DynDOLOD.esm` masters so I have no idea.

**Comment by WolfyJRB** [comment]
ok i even tried running the game without dyndolod and it CTD after i started a new game
