### ISSUE TITLE
Add command-line argument to temporarily override game folder

### ISSUE THREAD

**Issue by Karandra** [loot/loot#1049]
I suggest to add new command line parameter to override game folder detection. Something like: `--game-folder=<game folder full path>`.

I need that for [Kortex Mod Manager](https://www.nexusmods.com/skyrim/mods/90868) because it creates virtual folder which LOOT should use to be able to sort plugins. Otherwise LOOT will only see base game files. Currently, when LOOT is launched from Kortex for the first time, user need to choose that virtual folder in settings and restart LOOT. And the user needs to change that folder every time an instance is changed because virtual folder path is different for each instance.

Also I think when this new command line switch is used, LOOT should not save specified path to settings file because it's only for current session.

**Comment by Ortham** [comment]
It's fairly straightforward to implement a game path override, but preventing LOOT from writing out that path would involve keeping track of which if any game had its path overridden. Given that if the stored path is invalid, LOOT will fall back to looking the path up in the Registry, would it be a problem if LOOT stored the specified path?

**Comment by KerberX** [comment]
I see it like: I run LOOT with path override **and** game override (`--game=Skyrim` for example). If path and game is valid, continue, else terminate or show settings window or something like that.

It might be better to add separate cmd option that disables saving game path to settings file. But I see that could be quite complicated given how freely you can switch between games.

Anyway, not saving overridden path isn't so much important.

**Comment by Ortham** [comment]
Closing this as `--game-path` has been implemented in 70aca1de970adab68bc786ba1d6b326fa00daf13.
