### ISSUE TITLE
unnecessary warning (Sounds of Skyrim Complete SE and Vivid Weathers - Definitive Edition)

### ISSUE THREAD

**Issue by GounalakisOrestis** [loot/loot#1050]
sounds of skyrim and vivid weather both have compatibility patches for each other, but you can only use one of them  if I enable "vivid weathers SE SOS patch" I got this warning 

"A patch is included with the Sounds of Skyrim Complete SE installer, please make sure you have installed the Vivid Weathers - Definitive Edition patch and have it activated."

but if I enable this "SOS_VividWeather SE_Patch" I got this warning

"A patch is included with the Vivid Weathers Definitive Edition installer, please make sure you have installed the Sounds of Skyrim Complete SE patch and have it activated."

and finally, if I enable both I got this errors
This plugin is incompatible with "SoS_VividWeathers_Patch.esp", but both files are present.
This plugin is incompatible with "Vivid Weathers SE - SOS Patch.esp", but both files are present.

**Comment by CptMcSplody** [comment]
@GounalakisOrestis Thanks for the feedback, I've moved this issue to https://github.com/loot/skyrimse/issues, I'll fix this later today.
