### ISSUE TITLE
Exception while executing query - Invalid Reference Name

### ISSUE THREAD

**Issue by TheRealKraggy** [loot/loot#1060]
I'm getting this error every time I click SORT with Skyrim SE:

[11:46:50.496072] [error]: Exception while executing query: Git operation failed. Details: -12; the given reference name 'refs/heads/v0 (1).13' is not valid: libgit2 error
[11:46:50.496800] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5026: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5026:5818)

Working fine with Skyrim.  Running LOOT from MO 2.1.6, the built-in LOOT is also reporting the same error.  Started 2 or 3 days ago, my Masterlist is dated 22 Dec.

**Comment by TheRealKraggy** [comment]
Now happening on Skyrim too:

[13:42:24.581017] [error]: Exception while executing query: Git operation failed. Details: -12; the given reference name 'refs/heads/v0 (1).10' is not valid: libgit2 error
[13:42:24.585065] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5026: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5026:5818)

**Comment by CptMcSplody** [comment]
@TheRealKraggy can you open your `settings.toml`, any text editor will work. It's located at `C:\Users\%usrname%\AppData\Local\LOOT`.
And check these values
```
[[games]]
	branch = "v0.14"
	folder = "Skyrim"
	repo = "https://github.com/loot/skyrim.git"
	type = "Skyrim"
	registry = "Software\\Bethesda Softworks\\Skyrim\\Installed Path"
	name = "TES V: Skyrim"
	local_path = ""
	path = "Z:\\SteamLibrary\\steamapps\\common\\Skyrim\\"
	master = "Skyrim.esm"
[[games]]
	branch = "v0.14"
	folder = "Skyrim Special Edition"
	repo = "https://github.com/loot/skyrimse.git"
	type = "Skyrim Special Edition"
	registry = "Software\\Bethesda Softworks\\Skyrim Special Edition\\Installed Path"
	name = "TES V: Skyrim Special Edition"
	local_path = ""
	path = "Z:\\SteamLibrary\\steamapps\\common\\Skyrim Special Edition\\"
	master = "Skyrim.esm"
```

**Comment by TheRealKraggy** [comment]
The 'branch' values on both games was v0.13 .. I changed to v0.14 but the error persisted:

[19:12:00.908753] [error]: Exception while executing query: Git operation failed. Details: -12; the given reference name 'refs/heads/v0 (1).13' is not valid: libgit2 error

I presume the '.13' should be '.14', is there somewhere else I have to change the 13 to 14?

I have zipped up the settings.toml file along with the last FETCH_HEAD for Skyrim which was the last time it ran without error (in case it's of use)

[settings.zip](https://github.com/loot/loot/files/2715536/settings.zip)

**Comment by TheRealKraggy** [comment]
Yes, it happens when I run LOOT directly.

When I click "Sort Plugins", the message "Updating and Parsing masterlist..." appears followed immediately by the dialog with the "Oh no something went wrong" message.

Based on your comments I renamed AppData\Local\LOOT and ran LOOT manually to recreate it and then was able to run it from MO for both Skyrim and Skyrim SE and each worked fine, retrieving the masterlist for each without complaint.

LOOT is a blackbox to me so I've no idea what I'd do to try to discover what got broken and when but it's clearly that happened on my system recently; I've been switching between MO installations so maybe I changed something I didn't intend to, I don't really understand how MO exchanges info with LOOT.

I used not to have to manually tell LOOT what game it's being used for, it was always on auto-detect but nowadays I have to select the one I want if it isn't the one LOOT was run for last time, maybe whatever caused that glitched LOOT.

Anyhow, it seems the problem has 'gone away' so unless there's any more you'd like me to do to try to discover the cause it seems reasonable to leave it like that.

I appreciate the help and apologise if I wasted your time with an error of my own making, but like I say I have know understanding of LOOT's operation so I had no real idea where to begin.

Thanks.

**Comment by Ortham** [comment]
I don't think this is a bug in LOOT, it's more likely something to do with the interaction between MO and LOOT's git repositories leading to a corrupt state. I was going to suggest deleting the git repositories and allowing them to be re-created, but you've effectively done that and it worked, so I'll close this.
