### ISSUE TITLE
Assigning `default` in plugin group selector resets group

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1062]
LOOT version: loot_0.13.6-28-gb8badfc_dev, also seperately tested with libloot-0.14.1-0-gc8090fe_dev-win32. Works fine with last nexus release.

Steps:
Test module must be in a group besides `default`

Change modules group to `default`
![image](https://user-images.githubusercontent.com/1944639/50988071-624fe880-1503-11e9-9a67-6a35ee03765c.png)

And saved.
![image](https://user-images.githubusercontent.com/1944639/50988123-94f9e100-1503-11e9-89c9-360c6b957812.png)

Change does not save and the modules group is reset to match the masterlist.
![image](https://user-images.githubusercontent.com/1944639/50988129-9cb98580-1503-11e9-8841-e65ea9c69010.png)

Works fine when the group selected is not `default`.
![image](https://user-images.githubusercontent.com/1944639/50988156-b3f87300-1503-11e9-870b-725fe7341180.png)

Userlist icon & updated group showing in metadata editor.
![image](https://user-images.githubusercontent.com/1944639/50988292-1c475480-1504-11e9-8800-cdcf1e3b6955.png)

**Comment by Ortham** [comment]
OK, I can replicate this, not sure when it broke.

**Comment by Ortham** [comment]
OK, should be fixed in https://bintray.com/loot/snapshots/download_file?file_path=loot_0.13.6-31-gd2e2d0f_fix-czech-translation.7z.

**Comment by CptMcSplody** [comment]
Yeah it works fine now.

**Comment by Ortham** [comment]
OK, fixed as of a0fb5239e8098c5ed17ed10588fbd30eb7a73f90.
