### ISSUE TITLE
All translations from game.cpp are missing

### ISSUE THREAD

**Issue by DaCoolX** [loot/loot#1064]
Commit 09054d8 nuked all game.cpp items from the template.pot.

I guess someone forget to double-czech their commit. _\*BA DUMM TSS\*_

**Comment by Ortham** [comment]
Ah, this happened because the paths changed and I didn't update the pre-commit hook to reflect that.

**Comment by DaCoolX** [comment]
Yeah, I could and would have fixed it myself but it looked auto generated so I just bounced it back, because manually fixing comments referencing lines of code in other files is painstaking.

**Comment by DaCoolX** [comment]
Fixed in 463ae12
