### ISSUE TITLE
LOOT incorrectly detecting Requiem

### ISSUE THREAD

**Issue by HowellBP** [loot/loot#1068]
LOOT version is 0.13.6 (build e013793f)

There's a warning under `Book Covers Skyrim.esp`:
```
You seem to be using Requiem, but you have not enabled a compatibility patch for this mod. A third party patch is available here: Book Covers Skyrim - Compatibility Patch Collection
```
I do not have Requiem or any related mods installed.

**Comment by MacSplody** [comment]
@HowellBP Thanks, it should be corrected now.
