### ISSUE TITLE
Some Bug at LOOT startup after installing v0.14.0

### ISSUE THREAD

**Issue by BeerIsFood** [loot/loot#1071]
Hi

LOOT says in the General Information Frame (copy&paste):  

Failed to check for LOOT updates! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

Debug Log specific line is (2nd to last line in logfile): 

[16:43:25.305675] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5674: Failed to check for LOOT updates, details: TypeError: e.repos.getTags is not a function

The issue corrects itself after i hit the "Sort plugins" button. But after i restart LOOT it shows up again,

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2775706/LOOTDebugLog.txt)

**Comment by pStyl3** [comment]
Thanks for the info, we are already aware of the issue and fixed it already.

LOOT 0.14.1, which will include the fix, will be released shortly.
