### ISSUE TITLE
Unicode-Problem with new Version 0.14.1

### ISSUE THREAD

**Issue by Noctum28** [loot/loot#1073]
Hi, I downloaded the new version 0.14.1 today and ran into a problem when I executed it. 

In the attached log-file, I found the message "Für das Unicode-Zeichen ist kein zugeordnetes Zeichen in der Mehrbytecodepage vorhanden.", so apparently some Unicode-character could not be handled properly. I use a German version of Windows 7 64-bit and had the language of LOOT set to German as well. 

Changing the language of LOOT to English didn't help to resolve the issue. In fact, the logged error-message still remained German, so I assume the error originates from a third party software. Google brought me to some Microsoft website when I tried to investigate the problem myself.

Re-installing LOOT version 0.13.6 resolved the issue for me. Not sure if relevant for the problem, but I run LOOT through Mod Organizer 1.3.15.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2775979/LOOTDebugLog.txt)

**Comment by Noctum28** [comment]
No, I use English Skyrim LE with English mods only. I couldn't spot any special characters in the list of plugins either.

If at all, I could imagine that some text within a plugin might be in a different language as that happens every now and again when mod authors aren't carefull. I'm not sure if that could have any effect on LOOT.

PS: If you can create a debug version of LOOT that logs the query which is causing the problem, I would be willing to run it.

**Comment by Ortham** [comment]
I saw there's a filename mentioned in the log that looks suspicious: if the log is opened as Windows-1252, it's read as `â•‘Â»Ã�â”�â•—Ã¾ÃƒÃŽ.txt`, if opened as UTF-8, it's read as `║»Á┐╗þÃÎ.txt`, and the hex is `E2 95 91 C2 BB C3 81 E2 94 90 E2 95 97 C3 BE C3 83 C3 8E 2E 74 78 74`.

If I create a file in my Data directory called `║»Á┐╗þÃÎ.txt` and run LOOT, I get the same error as you (but in English: `No mapping for the Unicode character exists in the target multi-byte code page.`), so as a workaround try removing that file.

**Comment by Noctum28** [comment]
You are correct, that readme-file of a Japanese developer is the culprit here. Removing it fixes the problem.

**Comment by Ortham** [comment]
OK, this should be fixed now, can you try adding that file back into your Data directory and replacing your `loot.dll` with [this one](https://bintray.com/loot/snapshots/download_file?file_path=libloot-0.14.1-5-g2c9ea22_update-dependencies-win32.7z)?

**Comment by Noctum28** [comment]
That file fixed the issue, indeed. I can see "Checking to see if "║»Á┐╗þÃÎ.txt" is a valid plugin." in the debug-log, but no exception occurs.

**Comment by Ortham** [comment]
Fixed in 119aa27924632a19449126fd9aaeca4f9fc54886.

**Comment by sibir-ine** [comment]
@TheArel Are you using the [latest version of LOOT](https://github.com/loot/loot/releases/latest) (i.e., v0.17.0)? If so, can you please [provide a debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log)?
