### ISSUE TITLE
Opening metadata editor and immediately applying adds user metadata for plugins in the default group

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1075]
This regressed at some point, maybe due to a0fb5239e8098c5ed17ed10588fbd30eb7a73f90. It doesn't seem to happen if the plugin has a non-default group. I really need to add tests for this code, this isn't the first time it's broken like this.

**Comment by pStyl3** [comment]
It definitely occurs in 0.14.0 and not in 0.13.6, so you are probably right.

**Comment by Ortham** [comment]
This should be fixed as of 310269b0362b1bdb93f252c60cda2403bb82e227.
