### ISSUE TITLE
MorrowLoot Ultimate Message outdated (SSE)

### ISSUE THREAD

**Issue by sdpragequit** [loot/loot#1076]
![loot_2019-01-21_09-22-42](https://user-images.githubusercontent.com/24487483/51461428-50214600-1d5e-11e9-8bea-d4eec1265874.png)
The message links to UU's page which has no patches.
I am using the patch from MLU's page: https://www.nexusmods.com/skyrimspecialedition/mods/3058?tab=files

**Comment by Ortham** [comment]
Replying a bit late, but you've misinterpreted the message - it says

> A compatibility patch is provided on this plugin's mod page

"This plugin" is MLU.esp, it's the plugin the message is for.

**Comment by sdpragequit** [comment]
Well, I have that compatibility patch enabled - yet this message still shows.

**Comment by CptMcSplody** [comment]
@sdpragequit That should be resolved in https://github.com/loot/skyrimse/commit/c6582284477a1e4be51790b9478e3fc8801ca210
Make sure your master list is up to date.
