### ISSUE TITLE
Getting a warning for Rustic Soulgems Sorted without Requiem installed

### ISSUE THREAD

**Issue by HowellBP** [loot/loot#1077]
Should this only be displayed when Requiem is installed or is this a persistent warning as long as Rustic Soulgems is installed? Again, I'm not using Requiem in this load. (#1068 was fixed in the last update).
```
When using the Requiem patch for Rustic Soulgems, it's recommended that you deactivate or delete this plugin, but keep the assets (e.g. meshes, textures) installed with this mod as they're still required by the Requiem patch for Rustic Soulgems.
```

**Comment by Ortham** [comment]
This is fixed in the LOOT v0.14.3 release.
