### ISSUE TITLE
Problem with last LOOT and Wrye Bash

### ISSUE THREAD

**Issue by lex1975** [loot/loot#1078]
I wrote a bug report:
https://github.com/wrye-bash/wrye-bash/issues/431

I found what the problem with Wrye Bash. The last LOOT (0.14.0-0.14.2) during installation installed packet " MSVC 2017 x86 redistributable". When I uninstalled " MSVC 2017 x86 redistributable" everything worked fine.
On the previous versions of LOOT (0.13.6) such a problem was not observed.
All the latest updates to my system (Windows 7 x64 Professional SP1, 16Gb RAM, Intel Core I7) are installed.
I checked several times. After installing " MSVC 2017 x86 redistributable", program Wrye Bash.exe stops working.
Therefore I closed this issue Wrye Bash.

The LOOT at startup turns to DLL from packet " MSVC 2017 x86 redistributable"
For bug checks, I ask you to send me by mail a package of libraries (dll from " MSVC 2017 x86 redistributable") that your program uses.

I will remove from Windows packet " MSVC 2017 x86 redistributable". Then I copy your libraries directly to the folder with LOOT. That should work, right? After that, I will test the performance of both programs (Wrye Bash and LOOT).

I would be very grateful.
My E-mail: muravlov@mail.ru

**Comment by lex1975** [comment]
Some users have a similar problem.
https://forums.nexusmods.com/index.php?showtopic=5213770/#entry67047291
Comment #761 from other user:
Having the same problem after installing the new LOOT. I tried uninstalling both it and Visual C++ 2017, but my crashing has persisted. It's only affecting the Skyrim SE install for some reason. My Bash for Oblivion install is still working fine.

**Comment by Ortham** [comment]
LOOT v0.14.x requires the MSVC 2017 redistributable. If Wrye Bash has a problem with that being installed, the problem exists between Wrye Bash and Microsoft, independently of LOOT. As this isn't a LOOT issue, I'm closing this.

**Comment by Sharlikran** [comment]
From another use in the MO2 Discord

# Kurnn Said:

Installing MS Visual C 2017 on Win 10, will make  windows "Credit manager", "access manager" and .net, to update many "rights" to windows system only.
I had to check my .exe, MO2.exe, Loot.exe, and functions tools etc. The damn thing even put JAVA on highest security, if you had it on medium.
easy to fix, but no info from MS about it.
Similar how the October win 10 update, removed settings like "System restore" to off. You only needed to putit on again, but no info about it
MO2 uses pyton, which needs to call windows system processes sometimes. Credit manager has changed pyton. Once I simply manually "credit it" in credit manager", the issues where logs said "access problems". stopped
----I am no dev. I am a normal player. I am however, VERY experienced in Windows systems. Especially what they do and how to Fix/work around them-----

# In the end

And another message from him also clarified what credit manager is. It really means credential manager but I guess it is more commonly referred to as credit manager.

I post it not so much as a possible solution but to show that there can and always will be things that happen on Windows that we can't control.
