### ISSUE TITLE
Loot 14.2 crashes before load

### ISSUE THREAD

**Issue by NeoNate88** [loot/loot#1079]
Since installing 14.2 on Win 10, LOOT now crashes before loading (you can watch its process start and end immediately).

What I did:
-I installed the MSVC 2017 x86 redistributable as required. I restarted my computer as prompted by the installer.
-I ran the LOOT installer and installed it to a separate instance to avoid any potential upgrade issues.
-I ensured that there is an exception for LOOT in my antivirus software.
-After having this issue, I also downloaded the ZIP (which strangely is still marked "dev") and extracting it, running it from there. Same problem.

These steps resulted in this log file: [LOOTDebugLog.txt](https://github.com/loot/loot/files/2784912/LOOTDebugLog.txt)

Next I:
-Tried renaming the %LOCALAPPDATA%\LOOT folder to "LOOT_old".
-Ran LOOT again.

This time I experienced the same problem, but in the new %LOCALAPPDATA%\LOOT folder, there is simply a blank LOOTDebugLog.txt file. LOOT does not appear to generate any of the other local files or game folders. If I copy in the old settings.yaml into the local folder, it *does* generate a debug file that looks exactly the same as the one I've posted.

I tried 14.1 dev version as well, even though marked extremely unstable, just for kicks. Same results. For now reverting to 13.6

Thank you for your help!

**Comment by NeoNate88** [comment]
Thanks for the feedback. I did as you asked. Changed "game" to "Skyrim." I've attempted instances of LOOT off of both C: & I: after the change. Still no love from LOOT. 

Interestingly, though perhaps not useful, the task starts at using almost 2MB of memory, where it sits for a few seconds, drops to 20k for about 5-10s, then terminates. It's a real enigma.

13.6 continues to work fine.

**Comment by NeoNate88** [comment]
Here's something weird. I just noticed there is no loot_api.dll in the LOOT directory. What does this mean? Does this get unpacked after first load? Or is this the problem?

**Comment by Ortham** [comment]
> Here's something weird. I just noticed there is no loot_api.dll in the LOOT directory. What does this mean? Does this get unpacked after first load? Or is this the problem?

`loot_api.dll` was renamed `loot.dll` in v0.14.

**Comment by NeoNate88** [comment]
Ah. Got it. Oh well, back to the drawing board!

**Comment by NeoNate88** [comment]
It doesn't.

Thanks for the dedication. Moving Skyrim SE takes ages. I'd move it to C:, but I don't have room.

You are 100% correct. If I remove the drive, rendering SSE "uninstalled," LOOT starts up. Strange. I wonder what changed in 14.2 that rendered it unhappy? The path contains nothing unusual. I wish I could be more helpful.

**Comment by Ortham** [comment]
> I wonder what changed in 14.2 that rendered it unhappy?

I replaced the Boost filesystem library with the new-ish standard filesystem library, so I'd guess that the latter is complaining about something the former didn't. Try replacing your `loot.dll` with [this one](https://bintray.com/loot/snapshots/download_file?file_path=libloot-0.14.2-5-g2cbbc19_reduce-logging-win32.7z), it should log some more information.

**Comment by NeoNate88** [comment]
Rather than logging more information, LOOT simply just works now. Anything else I can do to help you troubleshoot this?

**Comment by Ortham** [comment]
Your log should have the necessary info: I just stopped the symlink handling causing the crash, but it needs a proper fix for people using symlinks.

**Comment by NeoNate88** [comment]
Thank you again for all your help! Closing.
