### ISSUE TITLE
[Linux] LOOT can't detect any games

### ISSUE THREAD

**Issue by TheRealDannyBoy** [loot/loot#1080]
Even after setting the game data path and local data path, LOOT can't find the game.  I do have a custom library location with custom ACL's, but I don't know why that would affect the application.
Debug log:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2788978/LOOTDebugLog.txt)

**Comment by TheRealDannyBoy** [comment]
I am using this build from Bintray [https://bintray.com/loot/snapshots/loot/0.14.2-0-g38ee4c2_0.14.2](url) on Arch Linux.

**Comment by Ortham** [comment]
A bit late, but apocalyptech on Discord was able to get LOOT built and running on Arch, and wrote up their experience [here](http://apocalyptech.com/games/loot-linux/), maybe it'll help you.

**Comment by qsniyg** [comment]
@TheRealDannyBoy Are you using movfs4l.py? If so, try renaming skyrim.esm to Skyrim.esp, and see if it works.

However, do note that any other esps/esms that you use must also be renamed properly, or else it will fail to work properly.

**Comment by TheRealDannyBoy** [comment]
I am indeed using that, although I believe I was having trouble without the VFS as well.  Did you mean Skyrim.esp, or should it still be .esm?

**Comment by TheRealDannyBoy** [comment]
As far as apocalyptech's instructions are concerned, I seemed to have my same problems plus LOOT not being able to download the masterlist.  I was going to ask for help on Discord when time allows.

**Comment by qsniyg** [comment]
>Did you mean Skyrim.esp, or should it still be .esm?

Sorry, yes, Skyrim.esm.

**Comment by pStyl3** [comment]
Closing this issue, since multiple libloot and LOOT versions have been released in the meantime.
