### ISSUE TITLE
Cyclic problem in 0.14.0, works fine in 0.13.6

### ISSUE THREAD

**Issue by cmeeren** [loot/loot#1085]
I can successfully sort my load order using 0.13.6, but I get a seemingly nonsense cyclic error in 0.14.0 (and 0.14.2):

```
Cyclic interaction detected between "Alternate Start - Live Another Life.esp" and "Apocalypse - Ordinator Compatibility Patch.esp":

Alternate Start - Live Another Life.esp
 [Master]
BetterQuestObjectives-AlternateStartPatch.esp
 [Group]
ELFXEnhancer.esp
 [Master]
elfx enhancer tweaks brighter.esp
 [Group]
MLU.esp
 [Masterlist Load After]
Ordinator - Perks of Skyrim.esp
 [Masterlist Load After]
Apocalypse - Magic of Skyrim.esp
 [Master]
Apocalypse - Ordinator Compatibility Patch.esp
 [Group]
Alternate Start - Live Another Life.esp
```

`Alternate Start - Live Another Life.esp` is in group `High Priority Overrides`, whereas `Apocalypse - Ordinator Compatibility Patch.esp` is in group `default`. I thought the groups were supposed to be ignored when contradicted by master relationships. And again, it works fine in 0.13.6.

**Comment by Ortham** [comment]
@CptMcSplody can you give any insight into this?

**Comment by CptMcSplody** [comment]
@Ortham Sorts fine in testing 
![image](https://user-images.githubusercontent.com/1944639/52458589-36527200-2b58-11e9-802c-b46878d3871c.png)

@cmeeren Can you supply a full debug log?

**Comment by cmeeren** [comment]
Sorry, unable to do that. I'm trying to get my saves to work after updating Skyrim and some mods, and LOOT messed up the whole load order pretty badly (perhaps because I went back and forth between 0.13.x and 0.14.x). I have spent a few hours adjusting the load order by hand to match the information in the savegame, and I'm not letting LOOT anywhere near it. I really just want to play the game. :)

Feel free to close if you can't get anywhere with this.

**Comment by Ortham** [comment]
In that case, closing this. Feel free to reopen this issue if it happens again.
