### ISSUE TITLE
LOOT no reaction

### ISSUE THREAD

**Issue by Memoso** [loot/loot#1086]
Hi Everybody,

I have a strange issue!

After moving my complete Skyrim Folder with Mod Organizer 2 and all utilities to another Hard Drive my Loot makes no reaction.  I already deleted everything incl the AppData Local Folder and reinstalled. But NO REACTION. If i double click the LOOT.exe there is the hourglass for half a second and that was it. I cant change the path because it wont open! Whats the matter here??

**Comment by Ortham** [comment]
Unfortunately this happens sometimes to some people and I've never been able to figure it out. Try the new [v0.14.3](https://github.com/loot/loot/releases/tag/0.14.3) release, you may have better luck with it.
