### ISSUE TITLE
Cyclic Interaction Between Audio Overhaul Skyrim - Immersive Sounds Patch.esp" and "Audio Overhaul Skyrim.esp"

### ISSUE THREAD

**Issue by AdamVezina** [loot/loot#1087]
Audio Overhaul Skyrim - Immersive Sounds Patch.esp
 [Group]
Cutting Room Floor.esp
 [Master]
Landscape Fixes For Grass Mods.esp
 [Group]
Audio Overhaul Skyrim.esp
 [Master]
Audio Overhaul Skyrim - Immersive Sounds Patch.esp

I haven't made any user edits to these files in loot. Seems to be the latest master list causing problems with it. Landscape Fixes has the CRF patch merged in which never caused problems before.

**Comment by CptMcSplody** [comment]
> Landscape Fixes has the CRF patch merged in which never caused problems before.

I wouldn't recommend merging a patch if it's going to add another mod as a master.

Landscape Fixes For Grass Mods.esp [Group]
You just need to move Landscape Fixes to a group higher than Audio Overhaul Skyrim.esp

**Comment by CptMcSplody** [comment]
@AdamVezina Can you test with the latest update?

**Comment by AdamVezina** [comment]
That fixed it. Thanks for the update!
