### ISSUE TITLE
Merged Plugins & Other plugins Keep Getting Thrown All Over The Place In Loot

### ISSUE THREAD

**Issue by NikaAlexandrov** [loot/loot#1088]
How do I make it so that my load order is correct? Everytime I try and add new mods, Loot always throws mods that I have merged together such as armor mods all over the place like a five year old toddler throwing his or her toys all over the place.  

It can be kind of annoying to have for example all of the vampire armors grouped together to avoid the plugin limit just thrown all over the place, or even worse the hunterborn mods in a mishmash when I have them put together in a super mod titled  
'Hunterborn Special Edition' only Loot would throw various parts of the merged patch all over the place constantly. 

As it would every other mod I happen to have. It's done that with all the others I've got worse in some that specifically have to be below alternate start live another life it will throw them above it.  Can someone help me with this please?:)

**Comment by CptMcSplody** [comment]
> for example (I have) all of the vampire armors grouped together

Are they grouped together in LOOT or just manually organized?

LOOT won't keep manual order, so you have to specify rules (Groups and/or afters) to achieve the sorting you want.

**Comment by NikaAlexandrov** [comment]
Manually organized together, how do I specify rules,  (groups and/or afters) to achieve the sorting I need?

**Comment by CptMcSplody** [comment]
All the information on using LOOT is provided in the Docs.
https://loot.readthedocs.io/en/latest/
https://loot.readthedocs.io/en/latest/app/usage/main.html

**Comment by NikaAlexandrov** [comment]
So for example what would Immersion style mods be considered as McSplody? Are they low priority, high priority or late fixes/changes?

**Comment by CptMcSplody** [comment]
It depends, what are these **Immersion style mods**?
Not all mods need to be grouped as well.

**Comment by NikaAlexandrov** [comment]
Just all the Hunterborn one's basically a test if you will. I merged them all down together into one group and want to keep them together. Instead of having them thrown all over the place.

**Comment by CptMcSplody** [comment]
Try that 
![image](https://user-images.githubusercontent.com/1944639/52953604-e6f21a00-337f-11e9-97b5-f2ca5a5da9c1.png)

**Comment by NikaAlexandrov** [comment]
Hmmm I'm not seeing an underrides like in yours. Do I need to create that?

**Comment by CptMcSplody** [comment]
Do you have the Latest version of LOOT? And have you updated your masterlist in LOOT?

**Comment by NikaAlexandrov** [comment]
I do and I'm updating it now

**Comment by NikaAlexandrov** [comment]
Okay that's fixed it now looks less wonky. How do I bind the one for Hunterborn Special Edition so that it will drag properly like you had it in the picture shown?:)

**Comment by NikaAlexandrov** [comment]
Hang on I got it now:
![image](https://user-images.githubusercontent.com/41357302/52955204-f140f380-3340-11e9-96e8-65be8f922fa1.jpg)

**Comment by NikaAlexandrov** [comment]
I think though need to switch that from blue to gray.

**Comment by CptMcSplody** [comment]
Arrow is going the wrong way `default` -> `Hunterborn` -> `Core`

**Comment by NikaAlexandrov** [comment]
![image](https://user-images.githubusercontent.com/41357302/52955608-ed61a100-3341-11e9-8826-8d325d73a2d3.jpg) this the way? :)

**Comment by CptMcSplody** [comment]
Then add only hunterborn to that group.

**Comment by NikaAlexandrov** [comment]
That's what I was told, to add hunterborn and it's related addon patches :) nothing else but:)

**Comment by CptMcSplody** [comment]
No just the main Hunterborn plug-in, you don't need to add the patches. 
If Hunterborn is a master for those plug-ins then they will sort after it without being in the same group.

**Comment by NikaAlexandrov** [comment]
*nods*

**Comment by CptMcSplody** [comment]
They just need to be in the group before it.

**Comment by CptMcSplody** [comment]
It will make sense when you sort.

**Comment by NikaAlexandrov** [comment]
So as long as I put them in group and say that's a master they will stay with it and won't be thrown all over my load order like I'm worried about in nmm? Because that happens all the time and it is annoying.

**Comment by CptMcSplody** [comment]
If the main plugin is in a group after `default` then anything that has it as a master will sort right after it.
You can also use the `Requires` in LOOT, which acts like adding as master.
![image](https://user-images.githubusercontent.com/1944639/52956484-325bf680-3387-11e9-902f-a62e01405528.png)

Generally patches will sort as low as possible after everything else in the same group.

If you leave the patches in `default` then they will sort after their highest master.
If the master is in a higher group, then they will sort straight after that master.
In your case `Hunterborn`,
Because those patches are not in their masters group, they can't sort after other modules in the masters group.

**Comment by NikaAlexandrov** [comment]
What's to prevent other files from immediately from loading right after them, do I need to set one right after the other in their order just in case? :)

**Comment by CptMcSplody** [comment]
There shouldn't be any need to generally, but I'd need to see an example of what you mean to be sure.

**Comment by NikaAlexandrov** [comment]
Well for example public executions.esp will for some unknown reason keeps being thrown in front of the animalpotions.esp part of the hunterborn.esp patch.

What that patch does of hunterborn does is it adds on allowing one to make nifty blood based potions for vampires. I still have to go through my entire load order just now to find the mcm for hunterborn because loot went and tossed that somewhere as well when I wanted to keep everything together nice and neat.

**Comment by CptMcSplody** [comment]
What is `public executions.esp`? And how does it relate to Hunterborn?
If you want it to sort after hunterborn and its patches then add `public executions.esp` to the hunterborn group.

`mcm for hunterborn` is it required to load after Hunterborn?
Does it have Hunterborn as a master? If not then you have either add an `after` or `requirement`.

**Comment by NikaAlexandrov** [comment]
It doesn't but loot just throwing down where I would manually would put all of the hunterborn ones and there's now an mcm for hunterborn.

**Comment by CptMcSplody** [comment]
You're going to have to provide a before and after of how you want it to sort verses how loot sorts them.
Because it's just guess work otherwise.

**Comment by NikaAlexandrov** [comment]
Ohh that's easy lol:
Hunterborn.esp
Hunterborn - Leather Tanning.esp
Hunterborn - Soups and Stews.esp
Hunterborn MCM SE
AnimalBloodPotionsSSE.esp
Hunterborn Special Edition.esp

Though all but Hunterborn SE's not checked lol

**Comment by CptMcSplody** [comment]
Right and how is LOOT sorting them?

**Comment by NikaAlexandrov** [comment]
What it kept doing is it would throw them every which way with hunterborn thrown up at the top of nmm, same with HB Special Edition, MCM SE in the middle between others, Soups and Stews towards the bottom where they should all be I'd have terrible time finding them all.

**Comment by CptMcSplody** [comment]
And you've added Hunterborn.esp to the hunterborn group?

**Comment by NikaAlexandrov** [comment]
Yep, looks like it worked :) *Bows to sensai CptMcSplody* :)
