### ISSUE TITLE
Links to AFK MOds need to be changed.

### ISSUE THREAD

**Issue by Arthmoor** [loot/loot#1089]
I am finalizing a switch over to a new domain for the AFK Mods site. I know there are some URLs within the LOOT files that refer to links at afkmods.iguanadons.net. These will all need to change to www.afkmods.com instead. Only the domain portion will need to change, the rest of the URL should still work fine.

**Comment by CptMcSplody** [comment]
I think it's just https://loot.github.io/latest-thread/ that is referenced by the master lists.

So only the below page should need updating.
https://github.com/loot/loot.github.io/blob/master/latest-thread.html

**Comment by Ortham** [comment]
The Fallout 4, Skyrim and Skyrim SE masterlists also contained links to afkmods.iguanadons.net, I've updated them too.
