### ISSUE TITLE
[Linux] Cyclic Interaction for DLCs (HearthFires.esm and Dragonborn.esm)

### ISSUE THREAD

**Issue by lkcv** [loot/loot#1090]
Hi,
I'm getting the error: Cyclic interaction detected between "Dragonborn.esm" and "HearthFires.esm".

Dragonborn.esm
    [Hardcoded]
HearthFires.esm
    [Masterlist Load After]
Dragonborn.esm

I went ahead and cleaned these files with SSEEdit to see if that would resolve the issue, but I'm still getting this error. The "Load After" metadata sections seem fine for both .esms (entries are set to stock and greyed-out). My workaround is to temporarily rename either Dragonborn.esm or HearthFires.esm and then run LOOT.

**Comment by pStyl3** [comment]
Which Linux Distribution do you use? Can you post your LOOTDebugLog.txt?

**Comment by lkcv** [comment]
I'm using Elementary OS (It's based on Ubuntu 18.04).
Here's my log
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2906527/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
I think this is a case sensitivity issue: the log contains references to `Hearthfires.esm`, e.g.

```
[22:50:36.149553] [trace]: Skipping adding hardcoded plugin edges for "Hearthfires.esm" as it is not installed.
```

but the plugin's filename is `HearthFires.esm`. Libloadorder has the former listed as a hardcoded plugin, so I'll need to update it to use the latter.

**Comment by Ortham** [comment]
The Skyrim and Skyrim SE masterlists also use `Hearthfires.esm` in places, they should probably also be updated.

**Comment by Ortham** [comment]
@lkcv Did you build LOOT yourself? If so, try rebuilding libloot from [this commit](https://github.com/loot/libloot/commit/22b7abc34823bbc9380a63b4082be3f48e052a29) and see if using that binary fixes your issue.

**Comment by lkcv** [comment]
@Ortham Yes, I did. Okay, I'll rebuild libloot and LOOT with the resulting libloot.so when I get home later today and let you know the result. Thanks for the update.

**Comment by Ortham** [comment]
You shouldn't need to rebuild LOOT, there shouldn't be any breaking ABI changes.

**Comment by lkcv** [comment]
That fixed it! Thank you.
