### ISSUE TITLE
Loot Failed (Exit Code Was 1)

### ISSUE THREAD

**Issue by ryan1431** [loot/loot#1091]
Error log:

14:08:25.124 [D] [loot] LOOT failed: yaml-cpp: error at line 1093, column 9: bad conversion: invalid condition syntax: Failed to parse condition "product_version("../SkyrimSE.exe", "1.5.62.0", <) and file("../SkyrimSE...
 [D]

**Comment by Ortham** [comment]
Is that all that was in the log? If not, please upload the file.

**Comment by ryan1431** [comment]
Issue resolved by reopening MO2
