### ISSUE TITLE
MorrowLoot Ultimate plugin fails to be detected (ESL - esp)

### ISSUE THREAD

**Issue by ubronan** [loot/loot#1093]
Hi since the release of the ESL like esp files for fixes i still have a problem that loot keeps reporting that the needed patch is not installed while it really is loaded and activated.
This is the message given on the main MLU.esp "You seem to be using Improved Daedric Artifacts, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
Gladly its only "Improved Daedric Artifacts" giving this issue. I am not sure if any of the other patches has similar issue.
I bet it can be quickly solved

**Comment by Ortham** [comment]
Sorry for the delay, but what's the filename of the MLU - Improved Daedric Artifacts patch you have that isn't being detected?

**Comment by CptMcSplody** [comment]
> 
> Hi since the release of the ESL like esp files for fixes i still have a problem that loot keeps reporting that the needed patch is not installed while it really is loaded and activated.
> This is the message given on the main MLU.esp "You seem to be using Improved Daedric Artifacts, but you have not enabled a compatibility patch for this mod. A compatibility patch is provided on this plugin's mod page."
> Gladly its only "Improved Daedric Artifacts" giving this issue. I am not sure if any of the other patches has similar issue.
> I bet it can be quickly solved

> 
> Sorry for the delay, but what's the filename of the MLU - Improved Daedric Artifacts patch you have that isn't being detected?
> 
> Also, is this a Skyrim or Skyrim SE issue?

Seems to be an Skyrim SE issue.
Plugin name was changed from `MLU - Improved Daedric Artifacts.esp` to `MLU - ImprovedDaedricArtifacts.esp`

**Comment by CptMcSplody** [comment]
@ubronan Thanks.
Resolved in https://github.com/loot/skyrimse/commit/959afbf191a5fd1df5f835454349f847d37b3ef6
