### ISSUE TITLE
Git operation failed. Details: -1; unsupported URL protocol: libgit2 error

### ISSUE THREAD

**Issue by klaidliadon** [loot/loot#1099]
I downloaded LOOT to use with Skyrim, but it get the following error:

```Git operation failed. Details: -1; unsupported URL protocol: libgit2 error```

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3010128/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
I don't know why you're seeing that error, the protocol is HTTPS. It could be due to GitHub requiring TLS 1.2, what operating system are you running?

**Comment by klaidliadon** [comment]
Windows 10 Pro x64 (1809)

**Comment by Ortham** [comment]
I can't figure out why this is happening for you, unless you've got the same Git config as described at the bottom of [this issue](https://github.com/JuliaLang/julia/issues/16009)...

**Comment by Ortham** [comment]
You could also try replacing your `loot.dll` with [this one](https://github.com/loot/libloot/releases/download/0.14.5/libloot-0.14.5-0-g68ecc02_dev-win32.7z), as that includes an updated libgit2.

**Comment by klaidliadon** [comment]
thank you so much!
It was the `.gitconfig` using ssh by default.
Sorry for the noise.

**Comment by Ortham** [comment]
OK, I'm glad that was it!

**Comment by MalcomeRoss1013** [comment]
> You could also try replacing your `loot.dll` with [this one](https://github.com/loot/libloot/releases/download/0.14.5/libloot-0.14.5-0-g68ecc02_dev-win32.7z), as that includes an updated libgit2.

i see how to replace the dll, but what about the rest in the include folder

**Comment by Ortham** [comment]
You can ignore the include folder, it's for developers.
