### ISSUE TITLE
Loot ran through MO2 loads faces as black

### ISSUE THREAD

**Issue by Talador12** [loot/loot#1102]
I know this is a standard load organizer issue, but I have run through a number of variations and finally found one that works. That said, running LOOT immediately breaks this order and I have to order it in the same way. I originally thought this was standard procedure in setting up Skyrim modding in oldrim or SE, but realized it was the key issue I had with the LOOT system. Almost all feedback online points to tracking down specific mod IDs from the console and last modified, but this is not an ideal experience and isn't clear for most.

**Comment by CptMcSplody** [comment]
@Talador12 You'll have to set up custom rules in LOOT.
LOOT won't be able to tell If you manually move plugins.

You can use afters to set the order.
Double click a plugin in the left panel.

![image](https://user-images.githubusercontent.com/1944639/55981648-1857d980-5c8f-11e9-89e4-eb37a7268d25.png)

Or select `Edit Meta Data` for the plugin menu in the right panel.

![image](https://user-images.githubusercontent.com/1944639/55981719-43dac400-5c8f-11e9-8320-7497926c66c5.png)

![image](https://user-images.githubusercontent.com/1944639/55981799-6cfb5480-5c8f-11e9-976f-178cb84bd6f0.png)

You can then add a new after rule.

![image](https://user-images.githubusercontent.com/1944639/55981945-c19ecf80-5c8f-11e9-8693-5b9360f28f9e.png)

![image](https://user-images.githubusercontent.com/1944639/55982002-db401700-5c8f-11e9-98af-ec630b71c022.png)
