### ISSUE TITLE
Cyclic Interactions with Groups and Users Defined Orders

### ISSUE THREAD

**Issue by AdamVezina** [loot/loot#1103]
Haven't sorted my load order in a day or two. But this was working prior. I have ELFX set to load after my weather mods. This is a recommended order by many ENB authors (I guess because it's not a hard requirement it hasn't made it to the master list yet?). 

When sorting I get the following Cyclic error:

Obsidian Weathers.esp
 [User Load After]
EnhancedLightsandFX.esp
 [Masterlist Load After]
Cutting Room Floor.esp
 [Masterlist Load After]
Book Covers Skyrim.esp
 [Master]
Qw_BookCoversSkyrim_CRF Patch.esp
 [Group]
Guard Dialogue Overhaul.esp
 [Group]
Weapons Armor Clothing & Clutter Fixes.esp
 [Master]
Qw_WACCF_AOS Patch.esp
 [Group]
Obsidian Weathers.esp

The issue is ELFX being set to load after Obsidian Weathers. Something due to Groups ordering is causing the cycle because it wants to load Obsidian after ELFX. This was not an issue before. I had submitted a similar issue to this a few months ago, I believe it was a similar problem where groups were interfering with user defined preferences.

**Comment by CptMcSplody** [comment]
@AdamVezina You'll need to change `Obsidian Weathers.esp` group to underrides inside LOOT.

![image](https://user-images.githubusercontent.com/1944639/57203795-e5adb200-6faa-11e9-8e6b-009e3a45d2fe.png)

**Comment by AdamVezina** [comment]
That did it. Thank you very much!
