### ISSUE TITLE
LOOT v0.14.4 Black Screen

### ISSUE THREAD

**Issue by Kaall** [loot/loot#1106]
Just as the Title says, Upon opening the last Version of Loot the only thing i have is a black Screen such as this one : https://i.imgur.com/W0GLbLN.png

I originally thought it was a Mod Organizer related issue, but even when lauching it by itself the black screen greets me.

I have switched back and forth between LOOT 0.14.3 (build 0cb2df71) and v0.14.4, and each and every time the black screen is there in the v0.14.4 and is never present in the v0.14.3.

**Comment by pStyl3** [comment]
Go to %localappdata%\LOOT and backup that folder, if it is present.
Then delete it and try starting LOOT by itself once more. Does it work now?

**Comment by Ortham** [comment]
I suspect this is more of a driver issue related to the CEF update in
0.14.4...

**Comment by Kaall** [comment]
> 
> 
> Go to %localappdata%\LOOT and backup that folder, if it is present.
> Then delete it and try starting LOOT by itself once more. Does it work now?

Did that and it did not change anything, still a Black Screen.

**Comment by pStyl3** [comment]
What is your operating system / graphics card / graphic card driver version?

**Comment by Kaall** [comment]
Windows  7 64bit Pro / Asus GTX970ti / Driver version : 378.92

**Comment by Ortham** [comment]
Try running LOOT with the `--disable-gpu` command line flag.

**Comment by Kaall** [comment]
The --disable-gpu Works, both by itself and using it in the argument in Mod Organizer...

Thank you.

**Comment by Ortham** [comment]
OK, unfortunately that may make the UI less responsive, but there's nothing I can do about it - you can try removing that flag next time you update LOOT, but otherwise you'll probably just have to run with that flag.

**Comment by bronzegauntlets** [comment]
I have the same problem and have no idea how to "run LOOT with the --disable-gpu command line flag"
can someone provide a more detailed explanation?

**Comment by FreezingFlame** [comment]
> 
> 
> I have the same problem and have no idea how to "run LOOT with the --disable-gpu command line flag"
> can someone provide a more detailed explanation?

1 - create a shortcut of LOOT
2 - Select its properties
3 - find the "target" of the shortcut
4 - put "--disable-gpu" at the end of the shortcut, preferably with a space between the arguments
