### ISSUE TITLE
Can't detect mutiple game install folders and no options in GUI to fix path issues

### ISSUE THREAD

**Issue by solarsootysmudge** [loot/loot#1109]
Loot is not detecting mutiple game install folders. It always points to the wrong game directory. It does not support finding the correct install directory. How do I force it to look at the correct drive path?

**Comment by Ortham** [comment]
You should be able to [set the install path for each game](https://loot.readthedocs.io/en/latest/app/usage/settings.html). What games is LOOT finding the wrong paths for, and what are they and the correct paths?

**Comment by solarsootysmudge** [comment]
Right the penny drops !!!

Now can detect more that one instance of the same game. Sometimes I want to build a new install from scatch without removing the old game directory. Deleting registry key completely. The pasting in correct directory path. A bit clunky but it gets the job done.

Many Thanks !!!
