### ISSUE TITLE
Have LOOT place The Tools of Kagrenac below Zim's Immersive Artifacts.

### ISSUE THREAD

**Issue by Zippomoon** [loot/loot#1110]
Since both mods edit Keening, ToK should be lower on the load order.

**Comment by CptMcSplody** [comment]
> Since both mods edit Keening,
> ToK should be lower on the load order.

@Zippomoon Could you provide some more detail on this?
What changes are being overwritten and why should Tools of Kagrenac have priority?

Also it would be useful to link the mods for reference.

**Comment by Zippomoon** [comment]
ToK
Oldrim: https://www.nexusmods.com/skyrim/mods/87590
SSE: https://www.nexusmods.com/skyrimspecialedition/mods/14168

Zim
Oldrim: https://www.nexusmods.com/skyrim/mods/81036
SSE: https://www.nexusmods.com/skyrimspecialedition/mods/9138

In ToK's FAQ section it it says that the mod conflic's with other mods that edit Keening while Zim's also state's it alters Keening in it's Ancient module/Complete Pack, since ToK's edit's are integrated into the mods story where as Zim merely change's the enchantment ToK should take priority.

**Comment by CptMcSplody** [comment]
@Zippomoon Perfect thanks.
