### ISSUE TITLE
Latest release shows as previous version once installed

### ISSUE THREAD

**Issue by yoyokenny** [loot/loot#1111]
Latest release (0.14.4 as of the time of submission) shows as the previous release (0.14.3) once it has been installed.

**Comment by Ortham** [comment]
I don't see this. Where are you seeing its version as 0.14.3?

**Comment by yoyokenny** [comment]
Nevermind, apparently I forgot to check where it was installing to. Recently reorganised my drives and didn't notice it installed to the old location. Oops.
