### ISSUE TITLE
infinite loop and creating hight temperature for CPU

### ISSUE THREAD

**Issue by xWhiteNinjax** [loot/loot#1112]
First, I love this program and use it a lot for sorting my mods in skyrim...
but there is a possible bug inside the first steps during merging/parsing the needed files (creating/checking masterfile)... sometimes there is an infinite loop causing the cpu jumping to 100 percent labor and heating the cpu into max stats... and since it is possible to run LOOT without looking carefully at the process (searching a website instead, for example), this process heating the cpu could go on for several minutes... in extremly unlucky possibilities this could cause computer-overhead and hardware-termininating-failures.... 

Even clausing the program with the taskmanager won't terminate the internal process for the cpu (still going like 100 percent and temperature going on to highest possible grades)... only solution is to start new (or just going out of the explorer, shutting down the user and starting windows-session again)...

This behaviour was visited from me since several versions, but occuring only randomly and seldom I missed to report this earlier... 

Since I am no programmer or technical experienced user I can only describe thie "bug" as I have seen the procedure running as described. Hope you are able to fix this easily

Have fun and thanks again for this program

**Comment by Ortham** [comment]
I can't do much about this without more data. If you could run LOOT with debug logging enabled and share the debug log the next time you see LOOT use system resources like this, that would help.

100% CPU utilisation for several minutes seems excessive, though LOOT does spread the load of parsing plugins across all available logical cores. As for closing LOOT not stopping the CPU load, LOOT runs multiple process, it sounds like you didn't close them all - I can't think how doing so would still leave stuff running.

As a general comment though, if your PC can't handle max load over a prolonged period of time without risk of hardware failure, your cooling is inadequate (but even then your CPU should thermally throttle itself), and that's something only you can fix.
