### ISSUE TITLE
Loot is stuck updating and parsing masterlist and cant be force closed

### ISSUE THREAD

**Issue by herbie47** [loot/loot#1113]
i have seen closed threads on this issue but cant fix it i have tryed running it in and out of MO, both with fresh installs and the same issue i will attach the log also. plz any advice would be much appreciated 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3263041/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Try replacing your `loot.dll` with [this one](https://bintray.com/loot/snapshots/download_file?file_path=libloot-0.14.6-8-g306c57e_dev-win32.7z).

**Comment by herbie47** [comment]
i replaced it and still the same and the log looks the same also

**Comment by Ortham** [comment]
Does it work if you manually download the [masterlist](https://raw.githubusercontent.com/loot/skyrim/v0.14/masterlist.yaml) and put it at `%LOCALAPPDATA%\Skyrim\masterlist.yaml`, and turn off masterlist updating in LOOT's settings?

**Comment by herbie47** [comment]
That seems to have worked thank u very much for your help it sorted my load order and my game doesn't ctd on load:)

**Comment by Ortham** [comment]
Well, you're not going to get any masterlist updates automatically, so it's a workaround but not a fix.

You could also try deleting the `%LOCALAPPDATA%\Skyrim\.git` folder (it may be hidden) and re-enabling masterlist updating, it may be that the Git repository got corrupted somehow.

**Comment by pStyl3** [comment]
Closing this issue since @herbie47's issue got fixed (albeit temporarily at the time) and new libloot and LOOT versions have been released in the meantime.
