### ISSUE TITLE
Application Error - 0xc0000022

### ISSUE THREAD

**Issue by AyronVaren** [loot/loot#1118]
Alright, now I'm pretty sure this is a common error for a lot of programs on Windows, but no matter what I do this error will not go away. I've searched it up and tried everything I could, but nothing worked for my Windows 7. I'm just flabbergasted because this happens every time I install a new update of LOOT and it magically gets fixed after a month or two, and I'd rather not wait that long.

(LOOT.exe Application Error
The Application was unable to start correctly (0xc0000022). Click OK to close the application)

**Comment by CptMcSplody** [comment]
Hi @AyronVaren,

This is more of a windows issue, but I'll point you to a possible solution.

0xc0000022 means access denied. Incorrect permissions to a particular file.

You'll have to troubleshoot following guidelines on this page.
http://tipsarea.com/2015/08/05/how-to-fix-the-application-was-unable-to-start-correctly-0xc0000022-error/
It uses outlook as an example but the steps will work for any application.

**Comment by AyronVaren** [comment]
Thanks for the reply @CptMcSplody 
I tried all the methods listed on the page, they didn't seem to work as the error still persists;
But the problem file seems to be Loot.dll. It's the only one being "denied".
Is there a reliable individual download of that dll file anywhere?

**Comment by CptMcSplody** [comment]
Can you open properties for that file and see if there is an unblock tickbox?
Downloads are [here](https://github.com/loot/loot/releases) or [Nexus](https://www.nexusmods.com/skyrimspecialedition/mods/1918?tab=files)

**Comment by AyronVaren** [comment]
![pic](https://user-images.githubusercontent.com/51891518/59570602-a4033300-904f-11e9-9e4c-354c1b348d0c.PNG)
Not one that I can find

**Comment by CptMcSplody** [comment]
Well I'd try using the installer and running it as admin when installing.

**Comment by AyronVaren** [comment]
Is there any specific location you'd think is best for the LOOT installation?
I've heard from some it doesn't matter but if there are any places that would potentially help, that would be great.

**Comment by CptMcSplody** [comment]
It shouldn't matter, but I usually put modding files outside the programs folder.
Something like.
> C:\Modding\tools\LOOT

**Comment by AyronVaren** [comment]
Alright, It seems I've tried almost everything now, but that error message still returns to no avail.
Everything has proper permissions, everything windows-related is installed, everything is where it's supposed to be; but it will seriously just not budge.
I'm most likely just going to wait for it magically work again, if it does like the last few times I used it. 
But if you have any other suggestions I'd be happy to try them

**Comment by CptMcSplody** [comment]
Not much, just standard things really.
Reboot windows and test.
Try testing using a different/new user account.
Make sure you're windows is updated fully.
Reinstall MSVC 2017 x86 redistributable.

**Comment by Ortham** [comment]
I'd guess that antivirus may be blocking the DLL from loading - if it magically starts to work after a month or so, that could be the DLL getting added to the antivirus's whitelist.

**Comment by CptMcSplody** [comment]
> 
> 
> I'd guess that antivirus may be blocking the DLL from loading - if it magically starts to work after a month or so, that could be the DLL getting added to the antivirus's whitelist.

@AyronVaren Have you tried this as @Ortham suggested?

**Comment by AyronVaren** [comment]
@CptMcSplody Yes, sadly enough it does not appear to work, Turned off all my anti-virus programs and the error still appears, even blocked it in the firewall but that also did not work

**Comment by AyronVaren** [comment]
Would there be a problem with the fact that I run a 64-bit system and LOOT potentially only works on 32-bit?

**Comment by Ortham** [comment]
No, if that was the reason, most people would have the same issue,
including me.

**Comment by pStyl3** [comment]
@AyronVaren Do you still have this issue and as such, need help in resolving it? We could close this issue otherwise.
