### ISSUE TITLE
Cyclic Interaction between X and Guard Dialogue Overhaul

### ISSUE THREAD

**Issue by rvazarkar** [loot/loot#1121]
I'm currently having an issue with trying to sort plugins, where it seems Guard Dialogue Overhaul is causing cycles with different ESPs. 

The initial error I got was: 
![image](https://user-images.githubusercontent.com/5720446/59967988-a1498780-9500-11e9-9e5f-65ec08968b09.png)

After moving 3DNPC1.esp into the underrides group, the error then became:
![image](https://user-images.githubusercontent.com/5720446/59967990-b3c3c100-9500-11e9-8c9f-2dd5122e7b6c.png)

I repeated the same process, and then the error moved to AHZBetterDGEntranceSE.esp

Masterlist revision is a62fbdc.

Let me know what other information I should provide.

**Comment by CptMcSplody** [comment]
Hi @rvazarkar 

Please post your full debug log with debug logging enabled, see How To Report Issues Helpfully.

**Comment by CptMcSplody** [comment]
Hi @rvazarkar 

Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by rvazarkar** [comment]
Here you go.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3317204/LOOTDebugLog.txt)

The game is SkyrimSE since I failed to put that in the initial post. Would this issue belong in the SkyrimSE LOOT issues?

**Comment by CptMcSplody** [comment]
> 
> 
> Here you go.
> 
> [LOOTDebugLog.txt](https://github.com/loot/loot/files/3317204/LOOTDebugLog.txt)
> 

Thanks.

> The game is SkyrimSE since I failed to put that in the initial post. Would this issue belong in the SkyrimSE LOOT issues?

No it's fine, I can open an issue there if needed.

**Comment by CptMcSplody** [comment]
@rvazarkar Okay just to test can you move `Guard Dialogue Overhaul.esp` to the `Default` group?

**Comment by rvazarkar** [comment]
After moving GDO to the Default group, I now get the following error:

![image](https://user-images.githubusercontent.com/5720446/59968209-24b8a800-9504-11e9-9953-9e942f01b728.png)

I did move 3DNPC1.esp back to default, instead of underrides to maintain a clean list. I can try moving it back

**Comment by CptMcSplody** [comment]
I think the issue is `Prom_No_Snow_Under_the_Roof.esp` and `EnhancedLightsandFX.esp`.
Can you move `Prom_No_Snow_Under_the_Roof.esp` to underrides and try sorting again?

**Comment by rvazarkar** [comment]
Looks like it sorted fine after making that change. Do you want me to try moving GDO back to the group it was in to see if it works without that change?

**Comment by CptMcSplody** [comment]
> Do you want me to try moving GDO back to the group it was in to see if it works without that change?

Yes.

Is that a merge or the original `Prometheus_No_snow_Under_the_roof.esp`?

**Comment by rvazarkar** [comment]
Its an original. The only change made was moving it to the Arthmoor's Villages group as per the Legacy of the Dragonborn SE guide by DarkLadyLexy. LOOT sorts fine after moving GDO back to Pre-Fixes, and leaving Prometheus_No_snow_Under_the_roof.esp to underrides.

**Comment by CptMcSplody** [comment]
Ah right, yeah that would cause issues, since there are mods set to load after it, like ELFX.
I can review those, to see if it can be avoided.

**Comment by rvazarkar** [comment]
Disregard my previous comment, it looks like I had incorrectly set a group. My mistake. I'll go ahead and close this

**Comment by rvazarkar** [comment]
Thanks for the quick reply and help, I appreciate it!
