### ISSUE TITLE
Updated to LOOT v0.14.4, now only opens to Black Screen - How to open with command line?

### ISSUE THREAD

**Issue by bronzegauntlets** [loot/loot#1123]
Hello,

I've updated to the newest version of LOOT v0.14.4, but it only opens to a black Screen. Kaall has  posted this issue previously and the solution was to "Try running LOOT with the --disable-gpu command line flag."

However I know nothing of coding, programming, or anything like it. Can someone please provide a detailed walkthrough of how to Run LOOT with a command line flag? I have no idea what this even means.

Thanks.

**Comment by Ortham** [comment]
If you don't already have a LOOT shortcut: Right-click LOOT.exe -> Create shortcut.

Then, right-click the shortcut -> Properties. Add `--disable-gpu` to the end of the Target text box, with a space between it and LOOT.exe, and click OK.

**Comment by bronzegauntlets** [comment]
Perfect, LOOT is now functioning normally.

Thanks!
