### ISSUE TITLE
Error reading version from DLL with no version fields

### ISSUE THREAD

**Issue by JesterSpearmann** [loot/loot#1124]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3341772/LOOTDebugLog.txt)

Loading up loot for the first time with a clean install for Skyrim SE I'm getting the generic "something went wrong check your debug log for further information" error

Attaching debug log for review

**Comment by Ortham** [comment]
```
[20:58:08.342941] [error]: Failed to evaluate condition "file("SKSE/Plugins/EnhancedNoPoisonDialog.dll") and file("../skse64_loader.exe") and ((version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", ==) and product_version("../SkyrimSE.exe", "1.5.73.0", !=)) or (version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", <) and product_version("../SkyrimSE.exe", "1.5.73.0", ==)))". Details: An error was encountered while reading the version fields of "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE/Plugins/EnhancedNoPoisonDialog.dll": entry not found
```

What version of LOOT are you using? Please also link to where you downloaded `EnhancedNoPoisonDialog.dll`.

**Comment by CptMcSplody** [comment]
> 
> 
> ```
> [20:58:08.342941] [error]: Failed to evaluate condition "file("SKSE/Plugins/EnhancedNoPoisonDialog.dll") and file("../skse64_loader.exe") and ((version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", ==) and product_version("../SkyrimSE.exe", "1.5.73.0", !=)) or (version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", <) and product_version("../SkyrimSE.exe", "1.5.73.0", ==)))". Details: An error was encountered while reading the version fields of "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE/Plugins/EnhancedNoPoisonDialog.dll": entry not found
> ```
> 
> What version of LOOT are you using? Please also link to where you downloaded `EnhancedNoPoisonDialog.dll`.

Seems to be the original version [Enhanced No Poison Dialog](https://www.nexusmods.com/skyrimspecialedition/mods/18497), it doesn't contain version information..

![image](https://user-images.githubusercontent.com/1944639/60385247-27c11480-9a7f-11e9-9275-a52b93cefb49.png)

```
Last updated
10 July 2018 11:47AM 

Requirements:
- Skyrim SE 1.5.39
- SKSE64 2.0.7
```

[Enhanced No Poison Dialogue - Updated](https://www.nexusmods.com/skyrimspecialedition/mods/19859)
[Enhanced No Poison Dialogue - Updated II - The Updatenning](https://www.nexusmods.com/skyrimspecialedition/mods/26798)

Both of those have version information included.

**Comment by Ortham** [comment]
This will probably need a code change to support trying to read versions from DLLs with no version fields - I assumed that if you're checking for a version, it will have a field, but that doesn't hold in this case...

**Comment by Ortham** [comment]
@CptMcSplody For now, I'd comment out the messages with that condition, with a note linking to this issue, and they can be uncommented once a fix is released.

**Comment by CptMcSplody** [comment]
> I'd comment out the messages with that condition,

All `.dll` messages using the version check or just the `EnhancedNoPoisonDialog.dll` one?

**Comment by Ortham** [comment]
Just the `EnhancedNoPoisonDialog.dll` ones.

**Comment by CptMcSplody** [comment]
@JesterSpearmann You'll need to disable/delete the `EnhancedNoPoisonDialog.dll` plugin.
Then update your masterlist in LOOT. You can reinstall/enable `EnhancedNoPoisonDialog.dll` after updating.

**Comment by JesterSpearmann** [comment]
> @JesterSpearmann You'll need to disable/delete the `EnhancedNoPoisonDialog.dll` plugin.
> Then update your masterlist in LOOT. You can reinstall/enable `EnhancedNoPoisonDialog.dll` after updating.

Thanks I'll fix it

> ```
> [20:58:08.342941] [error]: Failed to evaluate condition "file("SKSE/Plugins/EnhancedNoPoisonDialog.dll") and file("../skse64_loader.exe") and ((version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", ==) and product_version("../SkyrimSE.exe", "1.5.73.0", !=)) or (version("SKSE/Plugins/EnhancedNoPoisonDialog.dll", "1.2.2.0", <) and product_version("../SkyrimSE.exe", "1.5.73.0", ==)))". Details: An error was encountered while reading the version fields of "E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE/Plugins/EnhancedNoPoisonDialog.dll": entry not found
> ```
> 
> What version of LOOT are you using? Please also link to where you downloaded `EnhancedNoPoisonDialog.dll`.

Version 0.14.4 (build ec99692e)

**Comment by Ortham** [comment]
Reopened until I fix the version comparison to not error if there is no version.

**Comment by Ortham** [comment]
LOOT v0.14.5 is now released with the fix for this, so the conditional masterlist message can be added back in.
