### ISSUE TITLE
Can't load Fallout 3 GOTY (steam) from "non-default location"

### ISSUE THREAD

**Issue by Ryder17z** [loot/loot#1125]
I have steam set up so everything installs to E:\SteamLibrary and I can't get LOOT to detect my game even if i set the correct path;

E:\SteamLibrary\steamapps\common\Fallout 3 goty\

Why doesn't it work?

**Comment by CptMcSplody** [comment]
> I have steam set up so everything installs to E:\SteamLibrary

So FO3 was originally installed elsewhere?
If that's the case, it could be that the registry has not updated to mathc the new location.
You can try restarting you PC and launch the game, then try LOOT again.

**Comment by Ryder17z** [comment]
No, this is a global setting and FO3 was installed later

**Comment by Ryder17z** [comment]
Sorted by dreadful restart.
