### ISSUE TITLE
Failed to Spawn LOOT, SKSE, TES5Edit, Wrye Bash (Parameter Incorrect Error 87)

### ISSUE THREAD

**Issue by slick4hire** [loot/loot#1134]
I installed MO2 and was working fine for a week or so. 

Today, I tried to launch SKSE Loader and received the error

'failed to launch "skse_loader.exe":failed to start process (The parameter is incorrect. [87])

I then tried to launch all of the apps I have added in MO2 and all had the same error except FNIS. What I have tried so far with no change:

1. Reboot
2. Added exceptions to Avast and Malwarebytes for Modding & ModOrganizer folders, and rebooted.
3. Uninstalled Malwarebytes & rebooted.

Any help would be appreciated. Thanks in advance.

**Comment by slick4hire** [comment]
Sorry, I think this is in the wrong section.

**Comment by pStyl3** [comment]
Closing this in favor of https://github.com/ModOrganizer2/modorganizer/issues/801.
