### ISSUE TITLE
Font is weird in Japanese environment.

### ISSUE THREAD

**Issue by tktk11** [loot/loot#1135]
Font display is weird in Japanese environment.

The font assigned in "Typography.css" are as follows:
```font: 13 px/1.429 Roboto, Noto, 'Microsoft Yahei', 'Malgun Gothic', 'Meiryo', sans-serif;```

Chinese font is Microsoft Yahei
Korean font is Malgun Gothic.
Japanese font is Meiryo.

CSS applies a font in order from the beginning.
Microsoft Yahei and Malgun Gothic are also installed in Japanese environment, so it is displayed in Chinese or Korean font.
There is slightly difference between Chinese and Japanese for Kanji. It's hard to read.

I don't know CSS can be branched by language setting. However, if possible, I want you to change code the below.

If we set it to Japanese language, font is assigned 'Meiryo' without Microsoft Yahei and Malgun Gothic.

For example:
```font: 13 px/1.429 Roboto, Noto, 'Meiryo', sans-serif;```

You also need to change the assigned font in app.bundle.js.
It needs 'Meiryo' for menu and pop-up.

```--paper-font-common-base: {
font-family: 'Meiryo', 'Roboto', 'Noto', sans-serif;
-webkit-font-smoothing: antialiased;
};```

This problem can be fixed by install the Noto font. But LOOT is a  easy to use, essential tool, and I hope it's fine by default setting.

**Comment by Ortham** [comment]
This should be possible, though I haven't looked into it yet.

**Comment by Ortham** [comment]
I've added support for language-specific font families in [this build](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.14.5-7-g9d2ab0a_language-specific-fonts.7z), with Japanese set to use Meiryo by default and the ability to change it in LOOT's settings.toml.

**Comment by tktk11** [comment]
Thanks. Some of it is improved. However, the menu and filter items are still weird.

You need to give the priority to set the language-specific font over the the following parts in "app.bundle.js".

--paper-font-common-base: {
        font-family: 'Roboto', 'Noto', sans-serif;
        -webkit-font-smoothing: antialiased;
      };

![2019-07-31_17h15_20](https://user-images.githubusercontent.com/13784014/62210839-12217080-b3d8-11e9-9f34-9e711ae956f5.png)

**Comment by tktk11** [comment]
Perfect! Thank you for fixing. I want you to adopt this in the next version.

![2019-08-03_01h09_35](https://user-images.githubusercontent.com/13784014/62383865-d0392b80-b58b-11e9-83c8-b31180fa8571.png)

**Comment by Ortham** [comment]
OK, merged.
