### ISSUE TITLE
Skyrim is Windy EVT patch being loaded before EVT?

### ISSUE THREAD

**Issue by Soukmancer** [loot/loot#1136]
LOOT is sorting the skyrim is windy EVT patch before EVT... causing changes introduced by the patch to be reverted by EVT... the patch should load after EVT

EDIT: might be because the author updated EVT and changed the name of the plugin.

This plugin requires "SRG Enhanced Trees Activator.esp" to be installed, but it is missing.

It is now Enhanced Vanilla Trees SSE.esp ... donno why he would have done this.

**Comment by CptMcSplody** [comment]
@Soukmancer Fixed in https://github.com/loot/skyrimse/issues/734
