### ISSUE TITLE
Installer says "Download failed" and won't progress further

### ISSUE THREAD

**Issue by LittleKingJohn** [loot/loot#1137]
The installer fails with the error 

> Download failed. A connection to the server could not be established. Check your connection and click 'retry' to try downloading the files again.

When I press details, the file it could not download was vc_redist.x86.exe. It doesn't even seem to try though, with the error immediately appearing.

On Windows 10 64-bit Pro N. I have the latest version VC Redist 15/17/19 installed from Microsoft's site.

I think it's a bit silly I can't even skip this, or point it to a manually downloaded version.

**Comment by Ortham** [comment]
The installer checks to see if the redist is already installed and doesn't try to download it if it is.

Adding an option to skip would just mean people would do so thinking the redist is optional, and then find things don't work.

**Comment by LittleKingJohn** [comment]
> The installer checks to see if the redist is already installed and doesn't try to download it if it is.
> 
> Adding an option to skip would just mean people would do so thinking the redist is optional, and then find things don't work.

I have VC Redist 15, 17, and 19 installed. Which version is it looking for?

**Comment by pStyl3** [comment]
The following URL links the version that we advise people to download, that want to install LOOT using a preconfigured archive instead of the intaller:
[MSVC 2017 x86 redistributable](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe)

Does that link work for you?

**Comment by LittleKingJohn** [comment]
> The following URL links the version that we advise people to download, that want to install LOOT using a preconfigured archive instead of the intaller:
> [MSVC 2017 x86 redistributable](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe)
> 
> Does that link work for you?

That link is not accessible from any PC on my network, interestingly. The preconfigured 7z archive works fine, however. It seems that the installer is not checking that it is already installed. I'll mark it as closed since it's still primarily my fault.

**Comment by Ortham** [comment]
We can probably check for compatible newer versions, can you provide the version of the 2017 redist that you have installed?
