### ISSUE TITLE
LOOT Won't run

### ISSUE THREAD

**Issue by Pyromaniac99999** [loot/loot#1138]
I've seen similar questions being  asked in the past,  but mine is a little different. Ive recently upgraded from a WIndows 7 to 8.1. Naturally, I had to reinstall all the essentials like DirectX and MS  Redistributables, Etc. Ive downloaded the LOOT setups  time and again  but  the program wont run after installation. There is no probelm during installation. There is no LOOT  Folder in %LOCALAPPDATA%. It says  it needs  these .dlls to run:

api-ms-win-crt-heap-l1-1-0.dll  and
api-ms-win-crt-runtime-l1-1-0.dll.

Even after I put these in the loot folder,  it gives an  0xc0000007b  error. I have no idea  how to fix  this. I posted a thread on reddit, there a person  told me i had the wrong DirectX and I needed the DirectX  9 to run  it,  but I already have the latest version and its not doing anything. Please help.

**Comment by Ortham** [comment]
Those DLLs are supposed to be installed somewhere in C:\Windows by the MSVC redist installer, I'm not surprised that putting them in the LOOT folder didn't work. Have you installed the [redist](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe) that LOOT recommends?
