### ISSUE TITLE
Also have Mods needing to be cleaned listed at the top

### ISSUE THREAD

**Issue by WubTheGame** [loot/loot#1139]
Pretty self explanatory. Having a compact-ish list at the top just above the load order to show just the names of mods that need cleaning, what needs to be cleaned (if it's ITMs, display that, same with other things like deleted navmeshes), and the quantity of said thing needing to be cleaned.

This could be a huge help to people with absolutely massive load orders. And I'm sure you can see why with not too much trouble.

**Comment by CptMcSplody** [comment]
You can use the filters tabs to some degree.

![image](https://user-images.githubusercontent.com/1944639/63613867-97fc9a00-c5d9-11e9-8f88-2e056f54459c.png)

**Comment by Ortham** [comment]
@WubTheGame is using the filters tab good enough for you?

**Comment by WubTheGame** [comment]
Heheh, sorry, I hadn't even tried using that (I'm *that* kind of user, that mostly just does and uses what I can see, and if I don't find something somewhere immediately, I either look it up or something. Sometimes I'm not like that though, just another idiot on the internet not caring to use my brain for five seconds at a time). Thank you.

**Comment by Ortham** [comment]
Closing this as wontfix as what we've got seems to be good enough.
