### ISSUE TITLE
LOOT WONT DETECT SKYRIM SE

### ISSUE THREAD

**Issue by Wolfstorm321** [loot/loot#1143]
ALREADY STARTED SKYRIM LAUNCHER. 
ALREADY PUT "--game=Skyrim Special Edition" IN MO2. 
LOOT ONLY WORK WHEN INSTALLED **INSIDE** SKYRIM MAIN FOLDER, AND IT WILL NOT DETECT ANY MOD INSTALLED BY MO2, EVEN WITH THE COMMAND ABOVE.

**Comment by CptMcSplody** [comment]
[How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)

>Mod Organiser users who are experiencing a LOOT application issue should first try to replicate it while running LOOT independently of Mod Organiser. Running LOOT through Mod Organiser is unsupported.

Can you replicate the issue while running LOOT independently of Mod Organiser?

If you can't then you'll have to ask on the [MO2 github](https://github.com/ModOrganizer2/modorganizer) or their [Discord](https://discord.gg/6GKR9jZ).

**Comment by CptMcSplody** [comment]
https://github.com/ModOrganizer2/modorganizer/issues/820
