### ISSUE TITLE
First time Tips 

### ISSUE THREAD

**Issue by SALFATOR** [loot/loot#1150]
Hello!
The Dialog Box keeps appearing every time i lunch Loot Via MO2  after updating to the latest Version !

**Comment by CptMcSplody** [comment]
Hi @SALFATOR 

> Issues related to running LOOT through Mod Organizer will not be supported by the LOOT team.

Try replicating the issue while running LOOT independently of Mod Organiser.
If the issue persists, please read [How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)

**Comment by SALFATOR** [comment]
Sorry for the Delay .. !
I tried Running Loot separately and yet still persistent . 
and yes i'm Running loot via the usual instant . I've been using and updating LOOT in MO for a long time and never experienced that issue before .!

**Comment by Ortham** [comment]
Please provide a debug log. This suggests that LOOT is unable to write its settings file when it quits, as the settings file contains the version of LOOT that was last run, and that's checked before displaying the first time tips dialog.

**Comment by SALFATOR** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3705596/LOOTDebugLog.txt)

Hope that's what you asked for ..

**Comment by Ortham** [comment]
That doesn't log an errors writing the settings file, LOOT appears to be working correctly... What's in LOOT's settings.toml (in the same directory as LOOTDebugLog.txt)?

**Comment by SALFATOR** [comment]
Please Check below 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3709964/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
Closing as it just seems to be an LOOT with MO2 issue, no other reports since the time of opening.
