### ISSUE TITLE
Git repository missing help me plz

### ISSUE THREAD

**Issue by Hurricane-Rosevil** [loot/loot#1155]
I donno... a few hours before it still worked until I opened it again, and then I wanted to upgrade my list but it gave me an error, cannot find the game which I want to upgrade, so I reinstall it. After that it gave me another error which I have shown you at the title. There it is, I wonder is the server for LOOT is dead or what...? Oh btw I tried to use my MO2's LOOT to do the same thing but still it just CAN'T WORK geeze...

**Comment by Ortham** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by Hurricane-Rosevil** [comment]
Kay...Sorry this is the first time I use Git Hub...so uh this is the report:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3713732/LOOTDebugLog.txt)

**Comment by Hurricane-Rosevil** [comment]
Shoot, properly just my network's problem, I reinstall it again and it's working now, sorry wasting your time
