### ISSUE TITLE
ERROR: Cannot read property "status" of undefined when starting LOOT

### ISSUE THREAD

**Issue by Ozumayok** [loot/loot#1165]
Hey,

So I had some problems with  Skyrim SE not starting up after installing some recent mods. Last set of Mods that I installed were Ordinator, that disabled some previous mods (Royal Daedric Armor set). Also installed Mods for [Lady Death ](https://www.nexusmods.com/skyrimspecialedition/mods/30002?tab=files), now Skyrim doesn't load at all. Not even an instance is created on task manager, so I'm guessing it's crashing. 

Tried disabling some mods, but the issue still continued. Went ahead and Verified Integrity of Local Files on Steam. Reloading LOOT, got me the bug: 

> Error: Game-specific settings could not be initialised. Cannot set the current game: the game with folder "Skyrim Special Edition" is not installed

 error.

Already tried reinstalling LOOT, running it as administrator, resetting the Masterlist from Vortex, redeploying all mods and plugins

To launch Skyrim I followed the instructions from this [video ](https://www.youtube.com/watch?v=TTNy9Qr2sOc) on how to install SKSE64, and create your own desktop shortcut 

I'm attaching the LOOT Debug Log
[LOOTDebugLog.txt](https://github.com/loot/loot/files/3777325/LOOTDebugLog.txt)

FYT Loot still has the Skyrim SPecial Edition folder in it's directory, so not sure what's going on.

Thanks for the help

EDIT: LOOT got fixed, not sure how. I disabled some more MODs, and then deleted the SKSE64 loader from my desktop (planning on creating a new one from SKSE directory) and now LOOT loads. 

EDIT: Got game to Launch, disabled multiple mods, UIExtensions, daedric_2_7a... I guess this issue is more of a mod order issue now. 

EDIT: Updated LOOT Log, maybe someone can help me make better sense of this? What could be causing the issue?

[LOOTDebugLog.txt](https://github.com/loot/loot/files/3777361/LOOTDebugLog.txt)

EDIT: I think Daedric_2_7a standalone was causing my problem of the game not loading. This mod added a new set of Daedric craftable armors, and stopped working right after installing Ordinator (armor no longer craftable, but I still retained my previously crafted set)...

**Comment by CptMcSplody** [comment]
> EDIT: I think Daedric_2_7a standalone was causing my problem of the game not loading.

Is it `daedric_2_7a_standalone` from [Daedric Armor and weapon Improvement](https://www.nexusmods.com/skyrim/mods/3104)?

If you're using mods from Oldrim, they'll need to be converted first.
Oldrim `.bsa` files will crash the game on startup.
At any rate this isn't a LOOT issue, so I'll close this.
