### ISSUE TITLE
LOOT v0.15.1 UI visual glitch

### ISSUE THREAD

**Issue by Ne0niq** [loot/loot#1169]
Hello.
I am having strange visual issue. 
Here is a short video I recorded:
https://youtu.be/W83Eur046_Y

Hoever LOOT works as intended. It happens every time I run LOOT. 
I have all MSVC libraries installed (2013, 2015..2019). LOOT is the only program which acts this way among other programs relying on MSVC.
OS: Windows 10 1903 pro x64

**Comment by Ortham** [comment]
That looks very odd. Try running LOOT.exe with the `--disable-gpu` parameter.

**Comment by Ne0niq** [comment]
Running LOOT.exe with the --disable-gpu parameter helped. Program UI now looks fine! Thanks for you help, **Ortham**!
I suspected that it may be a "present" from lastest nVidia driver's and later I found that Whatsapp app has the same glitch.
