### ISSUE TITLE
RDO, Infinite Gold

### ISSUE THREAD

**Issue by ChaosOrdeal** [loot/loot#1178]
I have been running Relationship Dialogue Overhaul and Infinite Gold for Merchants together in SSE for some time.  LOOT does not note this as an issue, nor does it recommend the patch.  This is certainly not a bug, just recommending a possible feature addition.  LOOT is effing awesome, BTW.

**Comment by CptMcSplody** [comment]
> LOOT does not note this as an issue, nor does it recommend the patch.

[Infinite Gold For Merchants](https://www.nexusmods.com/skyrim/mods/52213)
[Relationship Dialogue Overhaul](https://www.nexusmods.com/skyrim/mods/74568)

[Infinite Gold For Merchants SE](https://www.nexusmods.com/skyrimspecialedition/mods/16162)
[Relationship Dialogue Overhaul SE](https://www.nexusmods.com/skyrimspecialedition/mods/1187)

Is there a patch available?

---

There are a few other rules that could be added for Infinite Gold for Merchants.

>###  Requirements, Load Order, and Compatibility Issues
> 
> Versions 2.1.0 and up are now compatible with [Vendor Sale Delay - GONE](https://www.nexusmods.com/skyrim/mods/34224) as long as you place IGFM AFTER Vendor Sale Delay - Gone in your load order.
> 
> It should be compatible with any mod that doesn't modify the Barter Dialogue branch.
> 
> Compatible with mods that add custom merchants, as long as they use the standard
> dialogue to barter with you (if they use custom dialogue, this mod will
> not work on them). Note that you may have to place IGFM AFTER those mods in the load order.
> 
> Known INCOMPATIBILITIES:
> - [Master Trader - Merchants Never Run Out Of Gold](https://www.nexusmods.com/skyrim/mods/50460)
> - [Master Trader SE - Merchants Never Run Out Of Gold](https://www.nexusmods.com/skyrimspecialedition/mods/1826)

**Comment by ChaosOrdeal** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/31271

I believe the same is true for LE.  I just used the three together in SkyrimVR.  It's not perfect but it works.  I suppose LOOT should at least mention that RDO generally conflicts with extra merchant gold mods.
[https://staticdelivery.nexusmods.com/mods/1704/images/thumbnails/31271/31271-1577395709-94842508.jpeg]<https://www.nexusmods.com/skyrimspecialedition/mods/31271>
RDO - Infinite Gold for Merchants Patch at Skyrim Special Edition Nexus - Mods and Community<https://www.nexusmods.com/skyrimspecialedition/mods/31271>
Credits and distribution permission. Other user's assets All the assets in this file belong to the author, or are from free-to-use modder's resources; Upload permission You are not allowed to upload this file to other sites under any circumstances; Modification permission You must get permission from me before you are allowed to modify my files to improve it
www.nexusmods.com


________________________________

**Comment by CptMcSplody** [comment]
@ChaosOrdeal Thanks,

> I suppose LOOT should at least mention that RDO generally conflicts with extra merchant gold mods.

It would be ideal to know which ones conflict or need afters for RDO. I'll have a look at any I come across against RDO.

**Comment by CptMcSplody** [comment]
I'll mark this as closed since the issues have been moved to the masterlists.
