### ISSUE TITLE
Exception while executing query: exists: 

### ISSUE THREAD

**Issue by dantomosoiu** [loot/loot#1181]
Hello, I'm using SkyrimVR with a bunch of manually installed mods and others through Vortex.

Skyrim works fine except the inventory UI takes a bit too much to load, which is why I tried LOOT.

On first run (and any subsequent runs) I get this error

**[04:02:32.268081] [error]: Exception while executing query: exists: The filename, directory name, or volume label syntax is incorrect.
https://github.com/loot/loot/issues[04:02:32.267507] [trace]: Checking if plugin "Dragonborn.esm" is active.
: "D:\Steam\steamapps\common\SkyrimVR\Data\Skyrim Radioactive -.*\.esp"**

[LOOTDebugLog.txt](https://github.com/loot/loot/files/4184057/LOOTDebugLog.txt)

I've seen this error popping about in similar threads but no obvious resolution, any ideas?

**Comment by CptMcSplody** [comment]
> : "D:\Steam\steamapps\common\SkyrimVR\Data\Skyrim Radioactive -.*.esp"

```yaml
      - 'Skyrim Radioactive -.*\.esp'
```

That metadata is only present in an older version v0.10 of the SSE\SVR masterlist.
_v0.15_ is the current and supported branch.
Make sure `AppData\Local\LOOT\settings.toml` has the right settings for branch.

```
[[games]]
[[games]]
	branch = "v0.15"
	folder = "Skyrim VR"
	repo = "https://github.com/loot/skyrimse.git"
	type = "Skyrim VR"
	name = "TES V: Skyrim VR"
```

If that's correct then try deleting the entire contents of `AppData\Local\LOOT`.
Then run LOOT outside your mod manager and update the masterlist.

**Comment by dantomosoiu** [comment]
Thank you, the version and **setting.toml** information were correct, so I deleted the **AppData\Local\LOOT** folder and it loaded successfully the next time I ran it.
