### ISSUE TITLE
The application was unable to start correctly 0xc00007b

### ISSUE THREAD

**Issue by rasellersjr** [loot/loot#1185]
It was running just fine yesterday. I switched from Nexus Mod Manager to MO2 and I get this error on startup. It happens running it from MO2 or just on its own. I've tried running it several different ways through the compatibility wizard, but nothing is getting it going again. I have also tried uninstalling and reinstalling all of Microsofts redistributables. When I try to start the app I'm still met with the message "loot the application was unable to start correctly 0xc00007b". I've also tried uninstalling and reinstalling the app.

**Comment by Ortham** [comment]
That error is apparently due to 32/64-bit mismatch and something going wrong in Windows. Does [this](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.14.4-9-g6be33f1_64-bit-win64.7z) (old) 64-bit LOOT work?

**Comment by rasellersjr** [comment]
Yes! Thank you! Been going nuts with this for hours. Doesn't even make any sense. Loot was working just fine 2 days ago. I have no new updates from Windows that might have screwed it up either. No idea what happened.
