### ISSUE TITLE
Loot going graphically nuts whenever doing any action.

### ISSUE THREAD

**Issue by Kapizor** [loot/loot#1192]
The function of the tools seems to be unaffected. This is only visual glitch.
Gif:
![ezgif-2-02b7dc8390d7](https://user-images.githubusercontent.com/17316115/77271072-1a3e6100-6c84-11ea-9154-eaf1e4f9f97f.gif)

Video: https://streamable.com/szn0u

**Comment by pStyl3** [comment]
Please go to LOOT's settings, enable debug logging and then provide us with your LOOTDebugLog.txt.

**Comment by Ortham** [comment]
Looks like some kind of graphics driver issue, what graphics card do you use, and what driver version are you running? If you run LOOT with `--disable-gpu`, do you still see the same issue?

**Comment by cygarniczka** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/4372167/LOOTDebugLog.txt)
I glanced quickly through the log and it list lots of plugins I don't use. I generated the log using no mods at all.

**Comment by Ortham** [comment]
I don't see anything wrong with that log, try using the [latest snapshot build](https://bintray.com/loot/snapshots/loot/0.15.1-8-g414b605_master): it includes a CEF update that jumps Chromium forward 10 versions, so maybe there were some relevant graphical fixes made in that.

**Comment by pStyl3** [comment]
Since there was nothing wrong within the log file, the issue occured with the old version 0.15.1 and no further feedback was provided on the post-0.15.1 / pre-0.16.0 build, I'm closing this issue. The issue could be reopened, in case the problem resurfaces in the latest version.
