### ISSUE TITLE
Regex to auto-group mods

### ISSUE THREAD

**Issue by erri120** [loot/loot#1193]
Let's say you have a group called `QUASIPC` and you want all patches from that mod in that group. You'd currently have to manually assign each plugin to the group. In this case all plugins start with `Qw_` which can be matched using a regex like

```Regex
^(Qw_)[^\.]+\.(esp|esl)$
``` 

Other examples include LotD Patches that start with `DBM_` but in this case you don't wanna include `DBM_RelicHunter.esp` because that is not a patch so you'd have a regex like 

```Regex
^(DBM_)(?!RelicHunter)[^\.]+\.(esp|esl)$
```

I could go on with more examples but the gist is that I wanna automate the group assignment. This can be achieved by adding a new field to to a group in the group manager called _Regex Matcher_ or _Regex Filter_ or however you wanna call it. Either have the matching and auto assigning done in the sort function or add a new button that will specifically execute this.

**Comment by Ortham** [comment]
This is already supported, but not through the UI. If you have a `userlist.yaml` like:

```
plugins:
  - name: .+\.esp
    group: Economy
```

Then that will add all plugins ending in `.esp` to the `Economy` group. I don't want to add UI for managing regex plugin metadata, as surfacing its existence would complicate things significantly.

**Comment by erri120** [comment]
Can you still manually remove plugins from that group even if they match the regex? Like if I use

```YAML
  - name: '^(Qw_)[^\.]+\.(esp|esl)$'
    group: 'QUASIPC'
```

Can I still manually assign eg `Qw_something.esp` to another group?

**Comment by Ortham** [comment]
No, because regex metadata entries are merged on top of a plugin's specific metadata entry, so the regex entry's group value would replace the specific entry's group value.

I think it would make sense to do smarter merging though, it's something I'll look into.

**Comment by Ortham** [comment]
I've filed loot/libloot#64 to change that behaviour.

**Comment by Ortham** [comment]
The improved merging behaviour was introduced in dcfb934cb1d68a3d582819dcfb13cf84ef720761, closing this.
