### ISSUE TITLE
Patch master not flagged as required

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1198]
LOOT Version 0.15.1 (build 82c756e1)

Tested directly in the data folder.
[LOOTDebugLog.zip](https://github.com/loot/loot/files/4468576/LOOTDebugLog.zip)

The patch `JSwords-ImmersiveWeaponsPatch.esp` for [Immersive Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/16788) is from [JaySuS Swords SE](https://www.nexusmods.com/skyrimspecialedition/mods/29415) All in one fomod.

![image](https://user-images.githubusercontent.com/1944639/79103598-d0b5d300-7d64-11ea-9bdd-525bdc443d79.png)

It doesn't show an error in LOOT if either master `JSwordsD.esm` `Immersive Weapons.esp` is missing.

![image](https://user-images.githubusercontent.com/1944639/79102418-9fd49e80-7d62-11ea-9e2d-907ce06b583a.png)

![image](https://user-images.githubusercontent.com/1944639/79102646-0bb70700-7d63-11ea-8736-b3b755be6e61.png)

It still sort it correctly.
![image](https://user-images.githubusercontent.com/1944639/79102808-68b2bd00-7d63-11ea-8155-ac46f50a54ec.png)

If I add one requirement, it will then show both requirements correctly.
Messages disapear when user rule is removed.

![image](https://user-images.githubusercontent.com/1944639/79102890-8f70f380-7d63-11ea-93a0-a7c30553a886.png)

**Comment by Ortham** [comment]
@CptMcSplody Try this build: https://bintray.com/loot/snapshots/loot/0.15.1-9-g9074951_fix-missing-messages

**Comment by CptMcSplody** [comment]
No, it's still not showing up.
![image](https://user-images.githubusercontent.com/1944639/83200177-ab293100-a13a-11ea-95c2-9515cf2eb909.png)

If I add any metadata such as a group change, it does work though.
![image](https://user-images.githubusercontent.com/1944639/83200249-d3189480-a13a-11ea-9ed1-dcd4867811a1.png)

**Comment by CptMcSplody** [comment]
@Ortham Here's the debug log, if it can help.
[LOOTDebugLog.zip](https://github.com/loot/loot/files/4698625/LOOTDebugLog.zip)
That is starting up LOOT with the group changed for the patch, and the errors showing. And then I removed the group assignment, and the errors disappear.

**Comment by Ortham** [comment]
@CptMcSplody That log gives the LOOT version as `0.15.1+d565efb6`, the build I linked is `0.15.1+90749517`

**Comment by CptMcSplody** [comment]
> That log gives the LOOT version as `0.15.1+d565efb6`, the build I linked is `0.15.1+90749517`

Yeah my mistake, I had an old zip from bintray that I unpacked instead. 🤦‍♂️ 

`0.15.1+90749517` is working as expected, no issues if I add or remove metadata.
And the errors only show when the plugin is enbled with the masters missing.

![image](https://user-images.githubusercontent.com/1944639/83286471-e3cb1800-a1d7-11ea-9303-1eac25b81fe8.png)

**Comment by Ortham** [comment]
OK, I've merged the fix.

**Comment by CptMcSplody** [comment]
@Ortham Thanks.
