### ISSUE TITLE
loot not working

### ISSUE THREAD

**Issue by kevininperu** [loot/loot#1201]
hi, i dont understand whats going on with LOOT... i downloaded fallout 4 & then loot.. it all worked fine... then i modded.. i then uninstalled all mods, reinstalled the game & added new mods, then I tried to use loot to do the load order but it didnt work.. i tried reinstalling loot.. it doesnt seem to find my fallout 4 game.. it doesnt do the search thing for the game.. it just has this message:

"error: game specific settings could not be initialised. none of the supported games were detected."

please help... thanks

**Comment by kevininperu** [comment]
sorry, just read another similar post with skyrim, someone put up thats closed & it stated i have to first run the game so it recognises it.. now my problem is already solved thanks

**Comment by CptMcSplody** [comment]
> sorry, just read another similar post with skyrim, someone put up thats closed & it stated i have to first run the game so it recognises it.. now my problem is already solved thanks

Okay, closing this since you've resolved it.
