### ISSUE TITLE
Feature request : condensing the lists

### ISSUE THREAD

**Issue by Shine753** [loot/loot#1204]
On a 27" monitor, in 2560x1440, the right list only display... 13 lines.
The left ist is better, but each line is still too large for the purpose.
Please do something to allow more... really more lines to be displayed, especially on the right panel.
It's really annoying when playing with many mods.

**Comment by Ortham** [comment]
Why do you think there aren't enough rows in the two lists? Or, to put it another way, enough for what? What numbers of rows would be enough?

**Comment by Shine753** [comment]
Enought would be... let's say something without extra useless space inside each row for so few displayed informations.

As an example, on the same screen, I can see a list of my last 46 emails, my first 59 installed mod in Mod Organizer 2, or my first 71 installed mod in Wrye Bash.

Opening LOOT and seing this 13 items list was like returning to a 640x480 monitor.

**Comment by Ortham** [comment]
That's not an actionable answer, it doesn't tell me what needs to be accomplished to resolve the issue you're having.

**Comment by Shine753** [comment]
Do what can be done to show more than  13 items in the right list.
If you don't see what I mean, just open Mod Organiser 2, load a bunch of mods using esp files, call LOOT, and look. I'm sure you can do something near this.

**Comment by Ortham** [comment]
I've added this to the 0.18.0 milestone as the Qt-based UI that's being developed in the `qt` branch and tracked by #1638 has a more compact UI. I think once that branch is merged this can be closed, as the lists will be more compact and no metric for measuring success was given.

**Comment by Ortham** [comment]
The new UI has landed as of 6daa98c0e45eddb4d5b37312302592ab4cf476c8, so closing this.
