### ISSUE TITLE
Building LOOT on Arch Linux fails by outdated library dependencies

### ISSUE THREAD

**Issue by Problembeloeser** [loot/loot#1217]
When trying to build loot following the commands from the travis yaml, the make fails due to outdated/missing library dependencies, namely libicuuc.so.55 and libhttp_parser.so.2.1, causing the following output:
```
[paul@pauldesktop build]$ make all
[  9%] Built target GTest
[ 19%] Built target spdlog
[ 28%] Built target cpptoml
[ 38%] Built target testing-plugins
[ 48%] Built target libloot
[ 61%] Built target loot_gui_tests
[ 71%] Built target cef
[ 80%] Built target json
[ 81%] Linking CXX executable LOOT
/usr/bin/ld: warning: libicuuc.so.55, needed by /home/paul/gits/loot/build/external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libhttp_parser.so.2.1, needed by /home/paul/gits/loot/build/external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UMemory::operator delete(void*)'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UnicodeString::foldCase(unsigned int)'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UnicodeString::~UnicodeString()'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::ByteSink::~ByteSink()'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `vtable for icu_55::ByteSink'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::ByteSink::GetAppendBuffer(int, int, char*, int, int*)'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UnicodeString::toUTF8(icu_55::ByteSink&) const'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UnicodeString::doCaseCompare(int, int, unsigned short const*, int, int, unsigned int) const'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `typeinfo for icu_55::ByteSink'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::UnicodeString::fromUTF8(icu_55::StringPiece const&)'
/usr/bin/ld: /home/paul/gits/loot/build/external/src/libloot/libloot.so: undefined reference to `icu_55::ByteSink::Flush()'
collect2: Fehler: ld gab 1 als Ende-Status zurück
make[2]: *** [CMakeFiles/LOOT.dir/build.make:321: LOOT] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:282: CMakeFiles/LOOT.dir/all] Fehler 2
make: *** [Makefile:104: all] Fehler 2
```

How could I get those dependencies up and running? Or could I get a linux build for it?

EDIT: I downloaded a linux build from bintray and when executing I still get notified about this missing dependencies with no guide on how to install them.

**Comment by Ortham** [comment]
Linux builds are provided pretty much as-is, with the assumption that if you're trying to run a modding utility for a Windows game on Linux, then you're comfortable going that far off the beaten track and are able to figure out how to get it working yourself. 

I've never used Arch Linux, so I can't tell you what you need to install. All I can tell you is that Linux builds on Travis CI work, and I've been able to build LOOT in Ubuntu VMs following the same process. However, I think Techwolf managed to get builds working at some point, though I can't recall if that was on Arch. He wrote a blog post about it, unfortunately I can't find a link to it, but maybe you'll have more luck with Google.

**Comment by C0rn3j** [comment]
I just compiled latest git just fine on Arch just like I did back in 2019.

https://github.com/loot/loot/pull/1162#issuecomment-545120145

_At the time of posting, the script has incorrect sed, you need to either fix the line manually or fix the sed command._

So I'd say this issue can be closed.

**Comment by Ortham** [comment]
@C0rn3j Thanks for the feedback, closing this since the build works for you.
