### ISSUE TITLE
Loot isn’t sorting

### ISSUE THREAD

**Issue by SeriousLunch** [loot/loot#1238]
When I try sorting with loot I get the messages

Could not check or read potential symlink path "D:/Modded Games/steamapps/common/Skyrim Special Edition": symlink_status: The parameter is incorrect.: "D:/Modded Games/steamapps/common/Skyrim Special Edition"

And

Could not check or read potential symlink path "D:/Modded Games/profiles/Default": symlink_status: The parameter is incorrect.: "D:/Modded Games/profiles/Default"

https://github.com/loot/loot/files/4731723/LOOTDebugLog.txt

**Comment by Ortham** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by SeriousLunch** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/4731723/LOOTDebugLog.txt)
is this right?

**Comment by Ortham** [comment]
It's the right file, but you haven't got debug logging enabled.

**Comment by SeriousLunch** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/4738882/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Do `"D:/Modded Games/steamapps/common/Skyrim Special Edition` or `D:/Modded Games/profiles/Default` contain symlinks, hardlinks or junction links? Are you running LOOT through a mod manager that uses a virtual filesystem like MO?

Those two path errors don't stop LOOT from starting up, and the other log entries show that LOOT is at least finding plugins. I don't see anything in the log about sorting, so I don't understand your issue.

**Comment by SeriousLunch** [comment]
Ok, I'll admit that i'm new to modding, so sorry if this entire thing has been annoying. My issues is that after i sort and apply the load order in loot, the mod list won't be sorted when i exit out of loot.

**Comment by LostDragonist** [comment]
I've seen a couple reports of this.  It appears to be traced back to running the game/mods on a storage drive formatted to exFAT instead of NTFS.  NTFS symlinks don't exist on exFAT drives so checking them is inevitably going to fail.

**Comment by SeriousLunch** [comment]
Thanks, this clarified that issue

**Comment by Ortham** [comment]
@LostDragonist thanks for that information, you'd have thought Microsoft could make `std::filesystem::is_symlink()` just return false when the filesystem doesn't support symlinks...

@SeriousLunch Could you try sorting with LOOT and uploading the debug log that creates?

**Comment by SeriousLunch** [comment]
I think I might have solved the issue actually. I’m not able to sort out the mods in loot, but I can sort the plugins through loot using the option in mod organizer’s menu

**Comment by Ortham** [comment]
Ah, were you launching LOOT through Mod Organiser? It will only be able to sort if launched that way.

**Comment by SeriousLunch** [comment]
Yeah, that was it, thanks for the help with this
