### ISSUE TITLE
loot for fallout new Vegas

### ISSUE THREAD

**Issue by TamaRha22** [loot/loot#1247]
for fallout new Vegas loot is not showing what dues and dues not need to be cleaned mod wise.

**Comment by CptMcSplody** [comment]
@TamaRha22 If you're not seeing any cleaning info, including the DLC. Then it's likely that you have not downloaded the masterlist in LOOT.

![image](https://user-images.githubusercontent.com/1944639/89837653-5144de80-db61-11ea-93f9-bb346e19da74.png)

![image](https://user-images.githubusercontent.com/1944639/89837674-5bff7380-db61-11ea-9adf-3627da8b8472.png)

![image](https://user-images.githubusercontent.com/1944639/89837697-69b4f900-db61-11ea-8a3e-3d0d6bd70082.png)

![image](https://user-images.githubusercontent.com/1944639/89837719-733e6100-db61-11ea-949c-d35b56eb9916.png)


If it's just a lack of info with the masterlist downloaded, then that requires contributors to submit the cleaning info to https://github.com/loot/falloutnv.
https://loot.github.io/docs/contributing/How-To-Contribute

**Comment by MacSplody** [comment]
Closing as it has been over a month without feedback.
