### ISSUE TITLE
User messages are lost when saving plugin metadata

### ISSUE THREAD

**Issue by alphaniner** [loot/loot#1255]
When user metadata for a plugin is saved, any preexisting user messages for the plugin are lost. It doesn't matter what changes are made to the metadata, or even if no changes are made at all. Presumably this is related to the fact that preexisting messages aren't seen on the messages tab in the first place.

In order to confirm it wasn't an issue with my existing userlist.yaml, I renamed it before opening LOOT. Then I added a message to a plugin's metadata, saved, and restarted LOOT. The message was present at this point. Finally I opened and saved the plugin's metadata and the message disappeared.

I use MO2 but the issue also occurs when LOOT is run normally. The attached log is from a normal run.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/4774039/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Thanks for reporting this, it should be fixed in [this snapshot build](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.15.1-110-ge100d7c_master.7z).

**Comment by alphaniner** [comment]
Thanks, that did the trick.
