### ISSUE TITLE
Cyclic interaction between a master .esp and a patch

### ISSUE THREAD

**Issue by nobiclown** [loot/loot#1258]
Cyclic interaction detected between "Complete Alchemy & Cooking Overhaul.esp" and "CACO_Milk Drinker.esp":

Complete Alchemy & Cooking Overhaul.esp
 [Master]
CACO_Milk Drinker.esp
 [User Load After]
Complete Alchemy & Cooking Overhaul.esp
I tried to load the master after the patch but it still gives me the same error

**Comment by CptMcSplody** [comment]
Without the user rule it works fine for me.

![image](https://user-images.githubusercontent.com/1944639/84980366-cda2de80-b129-11ea-974c-5bcc0e6bc4ab.png)

Can you remove that after? and then post any other sorting errors you may be having.

![image](https://user-images.githubusercontent.com/1944639/84980440-093da880-b12a-11ea-9a66-e862e333202c.png)

**Comment by CptMcSplody** [comment]
Closing as it worked fine in testing and lack of feedback.
