### ISSUE TITLE
Error launching LOOT

### ISSUE THREAD

**Issue by xMagne** [loot/loot#1324]
Whenever I try to start LOOT I just recieve this error box.
Help would be appreciated.
I am also using LOOT with Mod organizer 2, if that's valid information.
![error](https://user-images.githubusercontent.com/69201304/89294904-710b6c80-d660-11ea-874f-3b123d7dbac5.png)

**Comment by Ortham** [comment]
I don't know anything about that error, it looks specific to Mod Organiser.

**Comment by xMagne** [comment]
Anyone else who have encountered this issue?

**Comment by Papajack55** [comment]
Mine doesn't work and says error with a 000007b. Tells me to push ok, then the LOOT.exe stopped working-and I have to press close. It says the LOOT installer doesn't work and I tried the new one, and I don't have MO.

**Comment by CptMcSplody** [comment]
@Papajack55 Do you have the requirement [MSVC 2017 x86 redistributable](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe) installed?

**Comment by Papajack55** [comment]
Yes, I even tried to install it and it stated I already have it installed.   MSVC 2017 x86 redistributable

**Comment by Ortham** [comment]
@Papajack55 Try installing the [latest](https://aka.ms/vs/16/release/vc_redist.x86.exe) redistributable (it's newer than the one CptMcSplody linked to).

**Comment by Papajack55** [comment]
Already did, still not opening up. Is there a new version of LOOT out now?

**Comment by Ortham** [comment]
Yes, [0.16.0](https://github.com/loot/loot/releases/tag/0.16.0) was released earlier this week.

**Comment by MacSplody** [comment]
Same as #1340
