### ISSUE TITLE
Wrye Bash Tag Updates

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1326]
Opening here as it affects several masterlists.

###### Oblivion, Nehrim: At Fate's Edge, Fallout 3 & Fallout: New Vegas only.

`Npc.EyesOnly` replaced with `NPC.Eyes`.
`Npc.HairOnly` replaced with `NPC.Hair`.
`NpcFaces` split into `NPC.Eyes`, `NPC.Hair` and `NPC.FaceGen`.

###### For all games except Fallout 4
`Derel` replaced with `Relations.Remove`.
`Relations` split into `Relations.Add` and `Relations.Change`.
The behavior of the old `Relations` tag is equivalent to `Relations.Add` combined with `Relations.Change`.

###### For all games except Fallout 4
`EffectStats`
`EnchantmentStats`

- [x] Oblivion, Nehrim.
- [x] Fallout 3.
- [x] Fallout NV.
- [x] Skyrim LE.
- [x] Skyrim SE, VR.

**Comment by Infernio** [comment]
Was going to send them to you, but I see you're already on top of it :)
Skyrim (LE and SE) also gained `NPC.AIPackageOverrides`, `Outfits.Add` and `Outfits.Remove`.

**Comment by Infernio** [comment]
Went ahead and opened pull requests for all games updating the tag lists by generating them from the WB sources. These are up-to-date with [nightly](https://github.com/wrye-bash/wrye-bash/tree/nightly).

**Comment by CptMcSplody** [comment]
> Went ahead and opened pull requests for all games updating the tag lists by generating them from the WB sources. These are up-to-date with [nightly](https://github.com/wrye-bash/wrye-bash/tree/nightly).

Perfect I'll close this in that case, thanks.
