### ISSUE TITLE
Error -Oxc000007b

### ISSUE THREAD

**Issue by Papajack55** [loot/loot#1328]
Lately I have been recieving the error message that Oxc000007b comes up. I have taken my avast and included it in allowing to run through Avast. But now that error has come up and no matter what I do, I can't get it to run. 
Ant help please? I do not use MO, I use NMM. Never had a problem before until lately. 

It says LOOT.exe application error

**Comment by CptMcSplody** [comment]
@Papajack55 Can you turn on debug logging? And then supply a full debug log.
If you don't know how to do that, the steps are outlined here https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html.

**Comment by Ortham** [comment]
Try installing the [latest MSVC 2017 redistributable](https://aka.ms/vs/16/release/vc_redist.x86.exe).

**Comment by Papajack55** [comment]
I tried that already, but figured out how to fix it in case someone else wants to know-All I did was delete LOOT off my computer. Then I installed the  MSVC distributable, then I reinstalled the new version of LOOT. Worked perfectly..

**Comment by MacSplody** [comment]
Closing as the user has resolved the issue.
