### ISSUE TITLE
Latest version will not install 

### ISSUE THREAD

**Issue by Slayer0fKings** [loot/loot#1339]
Says archive is corrupt at every chance at downloading.  "The setup files are corrupted please obtain a new copy of the program is the message I get"

**Comment by Ortham** [comment]
I can't replicate the issue, [the archive](https://github.com/loot/loot/releases/download/0.16.0/loot_0.16.0-0-gb1094e6_0.16.0.7z) downloads and extracts fine for me.

**Comment by MacSplody** [comment]
@Slayer0fKings Did you resolve this issue?

**Comment by MacSplody** [comment]
Closing due to lack of feedback.
