### ISSUE TITLE
LOOT not running through MO2

### ISSUE THREAD

**Issue by Ballhammed** [loot/loot#1340]
LOOT is not running through mod organizer 2 but it will if I run it by it's self
I have excluded both the LOOT and the Mod Organizer 2 installer from my antivirus and reinstalled and the LOOT shortcut in MO2 is correct
This is the details it gave me after the error:

Error 87 ERROR_INVALID_PARAMETER: The parameter is incorrect. (0x57)
 . binary: 'C:\Modding\LOOT\LOOT.exe'
 . owner: BUILTIN\Administrators
 . rights: (normal rights)
 . arguments: '--game="Skyrim Special Edition"'
 . cwd: 'C:\Modding\LOOT'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: yes
 . usvfs x86:ok x64:ok proxy_x86:not found proxy_x64:ok

I am a computer retard so I don't understand this
Please help, if you do thank you

**Comment by Ballhammed** [comment]
I forgot to mention I have the required redist as well

**Comment by MacSplody** [comment]
> LOOT is not running through mod organizer 2 but it will if I run it by it's self
> I have excluded both the LOOT and the Mod Organizer 2 installer from my antivirus and reinstalled and the LOOT shortcut in MO2 is correct

@Ballhammed We don't provide support for running LOOT through MO2.
If you want help with MO2 then you can ask on the MO2 [Discord server](https://discord.gg/6GKR9jZ]https://discord.gg/6GKR9jZ) or [github page](https://github.com/ModOrganizer2/modorganizer/issues).
