### ISSUE TITLE
game is not installed

### ISSUE THREAD

**Issue by mr2meowsYT** [loot/loot#1342]
Error: Game-specific settings could not be initialised. Cannot set the current game: the game with folder "Skyrim VR" is not installed.

**Comment by MacSplody** [comment]
https://loot.github.io/docs/help/LOOT-FAQs

> #### A game is installed, but LOOT cannot detect it. How do I fix this?
>
> Steam removes the game's Registry entry when the game is updated or its cache is verified. Run the game's launcher to add the Registry entry back again. LOOT will then be able to detect the game.
> 
> Another cause may be that the game is installed in a location where you does not have read permissions, in which case LOOT cannot read your plugins, and so treats the game as undetected. Try checking the game path's permissions, and ensuring you have read access.

You can also manually set the path to the game in LOOTs settings.
![image](https://user-images.githubusercontent.com/1944639/93136560-083df800-f6d4-11ea-99ea-e1eee6273d3d.png)

**Comment by MacSplody** [comment]
Closing due to lack of feedback. It's also a common issue that can usually be solved by following the [FAQs](https://loot.github.io/docs/help/LOOT-FAQs) advice.
