### ISSUE TITLE
Valid ESL flagged plugin showing error message

### ISSUE THREAD

**Issue by MacSplody** [loot/loot#1345]
LOOT Version 0.16.0 (build b1094e67), it does not occur in Version 0.15.1 (build 82c756e1).

[Lanterns Of Skyrim II](https://www.nexusmods.com/skyrimspecialedition/mods/30817)
[Enhanced Solitude](https://www.nexusmods.com/skyrimspecialedition/mods/27816)

![image](https://user-images.githubusercontent.com/1944639/94588041-524dde80-027b-11eb-8568-32f8c3034504.png)

Patch `LoS II - Enhanced Solitude SSE patch.esp` for `Lanterns Of Skyrim II.esm` and `Enhanced Solitude SSE.esp`.
The patch is included in the Lanterns Of Skyrim II fomod.

Tested in xEdit and the file did not require compacting after removing the ESL flag.
I also had no error after re-adding the ESL flag and saving.

Wrye Bash also flagged the file as ESL capable.
![image](https://user-images.githubusercontent.com/1944639/94594612-93e18800-0281-11eb-8023-0a5e131bd99c.png)

**Comment by Ortham** [comment]
I'll try to look into this at the weekend.

**Comment by Ortham** [comment]
`LoS II - Enhanced Solitude SSE patch.esp` contains new records with object IDs ranging from 0x111 to 0x130, but as far as I'm aware the valid range for ESLs in Skyrim SE is 0x800 to 0xFFF, and that's why the warning is shown.

**Comment by MacSplody** [comment]
> `LoS II - Enhanced Solitude SSE patch.esp` contains new records with object IDs ranging from 0x111 to 0x130, but as far as I'm aware the valid range for ESLs in Skyrim SE is 0x800 to 0xFFF, and that's why the error is shown.

Yeah it's listed that way on the AFK guide.
https://www.afkmods.com/index.php?/topic/5079-plugin-files-and-you-esmeslesp/

> FE000800 - FE000FFF ModFile1
> FE001800 - FE001FFF ModFile2
> FE002800 - FE002FFF ModFile3

I've never noticed it starting from `FE000800` before tbh.
I always assumed everywhere listed it as starting from `FE000000` like below.

> FE000000 - FE000FFF ModFile1
> FE001000 - FE001FFF ModFile2
> FE002000 - FE002FFF ModFile3

---

Okay I  did some more testing.
xEdit only prevents changing the formid to anything over and including `FE001`.
Everything from `FE000001` to `FE000FFF` is accepted for ESL flagged plugins.
So anything in the `FE000` slot seems fine?

![image](https://user-images.githubusercontent.com/1944639/94966131-a3b4d280-04f4-11eb-9a1e-6a41c68afc18.png)

Having a record at or above `xx001000` will allow for compacting of all records.
That's disabled if the records are already inside the valid range.

![image](https://user-images.githubusercontent.com/1944639/94964924-7404cb00-04f2-11eb-9789-c9ec5f3f3589.png)

**Comment by Ortham** [comment]
I [asked](https://discordapp.com/channels/471930020454072348/486317996344868864/761884447225282560) in the xEdit Discord if the valid range has changed, and ElminsterAU replied to say it hasn't, so xEdit may be bugged - maybe it's not distinguishing between Skyrim SE and Fallout 4 correctly?

**Comment by MacSplody** [comment]
Okay, so there's nothing to fix in LOOT in that case.
Close this?

**Comment by Ortham** [comment]
Yes, I think so.
