### ISSUE TITLE
Feature request: Suggest to run the game before touch it

### ISSUE THREAD

**Issue by lexfrei** [loot/loot#1356]
Just stack at similar issue: https://steamcommunity.com/app/489830/discussions/0/1649918058738142446/

In our ages, we want to install mods before lounching the game and it's not clear why the Loot can't find a Skyrim.esm in the dir.

Please, add the suggestion or check for never lounched game

**Comment by pStyl3** [comment]
We have this point in our FAQs under Common Issues:
https://loot.github.io/docs/help/LOOT-FAQs.html#game-not-detected

@Ortham How about adding a bullet point to the FIrst-Time Tips dialogue, that informs the users that running the game launcher is necessary so that LOOT can find the game?

**Comment by Ortham** [comment]
That's an idea, but I don't really want to preempt issues like that. How about adding something like "try running the game launcher" to the error message that is displayed when LOOT can't find a game?

**Comment by pStyl3** [comment]
That should be sufficient. I like the idea.

**Comment by Ortham** [comment]
Done in a064348bfffb5407ee46fc3d9153bf14583a1edc.
