### ISSUE TITLE
Skyrim Special Edition Loot failed. Exit code was: 0xc0000135. How to fix that? 

### ISSUE THREAD

**Issue by LetziFetzi** [loot/loot#1368]
This happen when I want to sort my mods in MO2. I can run Loot without any problem but if I want to sort the mods this error appears. Loot failed. Exit code was: 0xc0000135.

**Comment by pStyl3** [comment]
If LOOT runs fine on it's own and the issue only occurs, if LOOT is run through MO, it's a problem on MO's side. If your problem still exists, please ask the developers of MO.
