### ISSUE TITLE
Ran into an error

### ISSUE THREAD

**Issue by parsafaramarzi** [loot/loot#1369]
ran into this error while sorting idk what it means but im sharing it with you just in case
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/5238295/LOOTDebugLog.txt)

**Comment by MacSplody** [comment]
> [14:44:32.509755] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out
> : libgit2 error

It seems like something is blocking LOOT from connecting to Github.
You may need to add an exception for LOOT to your firewall. @parsafaramarzi

**Comment by parsafaramarzi** [comment]
hi i dont remember what the problem was back when i registered it here but
now im good :) thank you forthe reply

**Comment by MacSplody** [comment]
> hi i dont remember what the problem was back when i registered it here but
> now im good :) thank you forthe reply

Okay, thanks for letting us know, I'll close this since you've resolved the issue.
