### ISSUE TITLE
Linux installation guide

### ISSUE THREAD

**Issue by BrightCrow** [loot/loot#1371]
Hello everyone,

Sorry, but I do not understand the installation guide of LOOT for Linux. Can someone explain to me with more details what to do?

I have read the Building section for Linux. I have the listed applications installed. But I don't understand how to "Refer to .travis.yml for the build process". I have never encountered .yml files, and don't know what to do with it. 

I searched and found that you can use it with docker-compose and use the docker-compose up command, but I doubt it is what you need to do here.
I don't know how to run the file, if this is what we should do, or maybe we need to run each command by hand.

Thank you for your help

EDIT: Found a fix. I downloaded the LOOT installer for the 0.15.1, directly run it with Wine, installed it, added the exe to MO2, launched it, and it works. I had also another problem, LOOT was not recognizing Skyrim Special Edition, as if it was not installed, so I launched SkyrimSE.exe and SkyrimSELauncher.exe with MO2, and that fixed this. Problem solved, maybe it can help another Linux user.

**Comment by Ortham** [comment]
> I have read the Building section for Linux. I have the listed applications installed. But I don't understand how to "Refer to .travis.yml for the build process". I have never encountered .yml files, and don't know what to do with it.

For future reference, what is meant by that is to look in [.travis.yml](https://github.com/loot/loot/blob/master/.travis.yml) to see the commands that Travis runs, and run those commands yourself (adjusting any paths and other details as necessary).
