### ISSUE TITLE
loot and DynDOLOD v3.0a14

### ISSUE THREAD

**Issue by hercules6969** [loot/loot#1391]
Hi

I've been using loot since I started moding Skyrim so thank you for this help in sorting numerous plugins for us... I have encountered a cyclic interraction between the latest version of Dyndolod and better dynamic snow. 
The last version of dyndolod 3.0a14 added (didn't in the past) "Better Dynamic Snow.esp" as a master for my load order but since Better Dynamic Snow isn't an esm, it should load after DynDOLOD.esm, hence the cyclic interraction.
Cyclic interaction detected between "Better Dynamic Snow.esp" and "DynDOLOD.esm":
Better Dynamic Snow.esp
[Master]
DynDOLOD.esm
[Master Flag]
Better Dynamic Snow.esp

I tried adding an "esm" flag to Better Dynamic snow.esp with wrye Bash but that lead to another cyclic interraction:

Cyclic interaction detected between "SMIM-SE-Merged-All.esp" and "Better Dynamic Snow.esp":
SMIM-SE-Merged-All.esp
[Masterlist Load After]
Better Dynamic Snow.esp
[Master Flag]
SMIM-SE-Merged-All.esp
any idea on how to solve this except adding the esm flag to all the cascading esps that will need it?

**Comment by InkjetFire** [comment]
Hi,

I assume DynDOLOD added unused master files (Better Dynamic Snow.esp) when it generated DynDOLOD.esm. It should not need to be loaded after any plugin. This appears to cause the cyclic interaction flagged by loot.

**Proposed Solution/Workaround:**
I suggest you use SSEEdit (xEdit) to clean masters of the generated DynDOLOD.esm file. 

Run SSEEdit with the following arguments to enable esm editing:

_-IKnowWhatImDoing -SSE -AllowMasterFilesEdit_

After the Module Selection window populates, double-click DynDOLOD.esm. When the loader finishes, find DynDOLOD.esm in the left panel (it should be listed last). Right-click it and select the option to Clean Masters. This process should take a few seconds at most.

When the process is done, close SSEEdit and choose to save the edited DynDOLOD.esm. Then run loot again. Hopefully this will resolve the cyclic interaction, as it did for me.

**Comment by Ortham** [comment]
Yes, this looks like the list of masters in `DynDOLOD.esm` being outdated - since it's a dynamically generated plugin and the cycle doesn't involve any metadata, regenerating the plugin should fix the issue.

**Comment by hercules6969** [comment]
Hi InkjetFire
Thanks for the tip, I tried the xEdit solution but even after cleaning, I guess there are still references to better Dynamic Snow because the cleaning process did not removed the master.
I'll try Ortham's suggestion of re-generating the plugin (but it takes me a few hours to do so...) and let you know
