### ISSUE TITLE
Invalid ESM's

### ISSUE THREAD

**Issue by Cristi80** [loot/loot#1402]
Just reinstalled Skyrim SE updated to v1.5.97 updated LOOT to v0.16.0 cleaned everything etc and every time i restart LOOT i get some chicky messages like: LOOT has detected that x ESM is invalid and is now ignoring it. The problem seems to persist when the game is clean after i installed few mods is gone. For future reference any idea?

**Comment by Ortham** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).
