### ISSUE TITLE
LOOT always shows 'Light Master File' for ESL-flagged plugins

### ISSUE THREAD

**Issue by Infernio** [loot/loot#1406]
A light master file would only be a file with ESL and ESM flags (which implicitly includes all `.esl` flags, of course).
LOOT currently shows it for all ESL-flagged files, e.g. this patch I created:

![image](https://user-images.githubusercontent.com/2845240/106324977-5ebe6400-627a-11eb-975f-aa54a9460a49.png)

But that one's clearly only an ESL-flagged ESP. It does not have the master flag:

![image](https://user-images.githubusercontent.com/2845240/106325074-81507d00-627a-11eb-8e74-fae6f862729a.png)

**Comment by Ortham** [comment]
This is a terminology thing: I call anything with the ESL flag a light master, is there a better / more widely used term?

**Comment by Infernio** [comment]
Light plugin is what I call them in WB.

**Comment by MacSplody** [comment]
> This is a terminology thing: I call anything with the ESL flag a light master, is there a better / more widely used term?

Light Plugin or ESP-FE are the only two I know of.

**Comment by Infernio** [comment]
For a regular ESP with ESL flag I show `Light plugin.`, for an ESL with ESM flag I show `Light plugin. Master plugin.`

**Comment by Infernio** [comment]
So since there's already the crown icon for masters, I think `Master Plugin` and `Light Plugin` for those two would be good terminology.

**Comment by Ortham** [comment]
Fair enough, `Light Plugin` works for me.

**Comment by Ortham** [comment]
I think this is done in 1694710091ac72277605838c1a355a6d538e96e0, though the underlying libraries still use "light master" as a synonym for "light plugin".

**Comment by Infernio** [comment]
Yup, looks good 👍
