### ISSUE TITLE
Update credits.rst

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1422]
https://github.com/loot/loot/blob/master/docs/app/credits.rst

`LOOT's masterlists were largely converted from BOSS's masterlists, and so credit is due to the very large number of sources and people who have contributed to them.`

While I do not want to downplay the contribution of the people that created the old masterlists for BOSS - we continue to thank everyone who contributed in any way - by now only half of the masterlists the LOOT project provides originated from the BOSS era.

These were started during the BOSS era:
```
Oblivion
Fallout 3
Fallout NV
Skyrim
```
And these were created after the transition to LOOT:
```
Skyrim Special Edition
Fallout 4
Morrowind
Enderal
```
As such, I think that `LOOT's masterlists were largely converted from BOSS's masterlists` doesn't accurately describes the situation anymore (not to mention the massive updates and continuous development of the masterlists) and we should change that sentence so that it fits more to the current situation.

I would suggest something like this:
`LOOT's masterlists were created by many people over the course of the years, and so credit is due to the very large number of sources and people who have contributed to them.`

---
Additionally, we probably should check the list of translators mentioned in this file, I think there are missing a few. For example, @DaCoolX  helped with the german translation of the LOOT application itself, but isn't mentioned.

Should we also list people here, that helped translating the masterlists?

**Comment by DaCoolX** [comment]
I wasn't particularly aware these credits even existed, thanks for the mention.

I propose `LOOT's masterlists, have gotten many additions, improvements, refinements and translations over the years, and so credit is due to the very large number of people and sources (particularly BOSS's masterlists) who have contributed to them.`

Regarding the masterlist translators, does it make sense to separate them from other kind of masterlist contributors or should we include them just under the big "contributor" umbrella term. I lean towards the latter.

**Comment by Ortham** [comment]
I think it makes sense to reflect the passage of time and the wide range of sources for and types of contribution to the masterlists, I'd be happy with either of your proposals.

This just reminded me that https://loot.github.io/credits/ exists, but it looks like it broke at some point...

**Comment by pStyl3** [comment]
> Hmm, it works intermittently.

That's also my observation. Reloading the page sometimes helps.

> LOOT's masterlists have gotten many additions, improvements, refinements and translations over the years, and so credit is due to the very large number of people and sources (particularly BOSS's masterlists) who have contributed to them.

I also like your variation DaCoolX, maybe without the first comma.

> Regarding the masterlist translators, does it make sense to separate them from other kind of masterlist contributors or should we include them just under the big "contributor" umbrella term. I lean towards the latter.

I think we should just name everyone who has provided translations in one place, and this file could be this place. So if language A has been added, then the translator for that language get's named first in the credit list for that specific language. Every other person that provides translations for that language after that, may it be for the application itself or for the masterlist, just get's added to that list one after the other. This way every translator get's credited and we keep an overview over this specific group of people. I will compile a list of people that I think should be added soon.

**Comment by DaCoolX** [comment]
> maybe without the first comma.

That was an oversight, thanks for fixing that and thanks for finding my proposal adequate.

> I think we should just name everyone who has provided translations in one place, and this file could be this place. So if language A has been added, then the translator for that language get's named first in the credit list for that specific language. Every other person that provides translations for that language after that, may it be for the application itself or for the masterlist, just get's added to that list one after the other. This way every translator get's credited and we keep an overview over this specific group of people. I will compile a list of people that I think should be added soon.

Sounds like a very good approach of organizing the crediting of the translators.

**Comment by pStyl3** [comment]
These people have contributed to translating the masterlists or the application, and **haven't** been mentioned in credits.rst so far:
```
Brazilian Portuguese: zDasF1xer
Chinese: silentdark
Czech: 
Danish: 
Finnish: 
French: cpasmoi
German: DaCoolX, pStyl3
Japanese: tktk11
Korean: sean-kang
Polish: Yoosk
Russian: 
Spanish: 
Swedish: simoneddeland, ddbb07

Portuguese: ironmagician
```

The list above could be incomplete, I'm not sure if I got everyone yet.
In any case, I've got a few questions.

Are `Kaos` and `cpasmoi` perhaps the same person that provided the french translation? There are a couple of pull requests in the loot repo, that were commited by a deleted GitHub user "Ghost", but if I look at the commit in question I see the name `cpasmoi`. An example would be [PR number 447](https://github.com/loot/loot/pull/447).

Also .. it appears to me that LOOT only offers `Brazilian Portuguese` and not standard `Portuguese` as language (and that is reflected by current credits.rst not mentioning Portuguese), yet we differentiate between the two in the masterlists (`pt_BR` and `pt`). How does that work?

**Comment by Ortham** [comment]
> Are `Kaos` and `cpasmoi` perhaps the same person that provided the french translation?

I don't know.

> There are a couple of pull requests in the loot repo, that were commited by a deleted GitHub user "Ghost", but if I look at the commit in question I see the name cpasmoi. 

I'd attribute those ghost commits to cpasmoi.

> Also .. it appears to me that LOOT only offers Brazilian Portuguese and not standard Portuguese as language (and that is reflected by current credits.rst not mentioning Portuguese), yet we differentiate between the two in the masterlists (pt_BR and pt). How does that work?

We always differentiate between Portuguese and Brazilian Portuguese to be accurate, though I'm told that someone who can read one can generally make sense of the other. The reason we don't list Portuguese as a language is that the LOOT application itself doesn't have a Portuguese translation, and I wasn't aware that any of the masterlist messages do.

**Comment by pStyl3** [comment]
I've added `Infernio` and `Deka-O` to the list, both of them provided german translations in the skyrimse masterlist.

I'd also say, that `Kaos` and `cpasmoi` are different persons. `Kaos` is mentioned [here](https://github.com/loot/loot/commit/b95b33e8bb764d1f0730e835addd3a860ff175dd), which was over a year before `cpasmoi` updated the french localization.
We probably also should add `Sita` to the list of french translators, as he helped out [here](https://github.com/loot/loot/commit/e75a45bd7209aaf7f1c0814acf5d9d6f20a7ea8d).

Regarding `pt_BR`, it's support to LOOT was added by `Kassane` [here](https://github.com/loot/loot/pull/315).
Then we sought out to translate more masterlist messages through [sse issue 646](https://github.com/loot/skyrimse/issues/646). That's why sse PR [651](https://github.com/loot/skyrimse/pull/651) came to be, so since then we have `pt` translations.
After that, zDasF1xer added `pt_BR` translations through sse PR [744](https://github.com/loot/skyrimse/pull/744).

**Comment by Deka-O** [comment]
No need to credit me twice, I'm DaCoolX, just keep me credited as that.

**Comment by DaCoolX** [comment]
Ya, I know, personal accounts and all that.

**Comment by RacerBG** [comment]
> 
> 
> These people have contributed to translating the masterlists or the application, and **haven't** been mentioned in credits.rst so far:
> 
> ```
> Brazilian Portuguese: zDasF1xer
> Chinese: silentdark
> Czech: 
> Danish: 
> Finnish: 
> French: cpasmoi
> German: DaCoolX, Infernio, pStyl3
> Japanese: tktk11
> Korean: sean-kang
> Polish: Yoosk
> Russian: 
> Spanish: 
> Swedish: simoneddeland, ddbb07
> 
> Portuguese: ironmagician
> ```
> 
> The list above could be incomplete, I'm not sure if I got everyone yet.
> In any case, I've got a few questions.
> 
> Are `Kaos` and `cpasmoi` perhaps the same person that provided the french translation? There are a couple of pull requests in the loot repo, that were commited by a deleted GitHub user "Ghost", but if I look at the commit in question I see the name `cpasmoi`. An example would be [PR number 447](https://github.com/loot/loot/pull/447).
> 
> Also .. it appears to me that LOOT only offers `Brazilian Portuguese` and not standard `Portuguese` as language (and that is reflected by current credits.rst not mentioning Portuguese), yet we differentiate between the two in the masterlists (`pt_BR` and `pt`). How does that work?

I would like to include myself here for the Bulgarian translation I made. :smiley: 

Bulgarian: Georgi Georgiev (RacerBG)

**Comment by pStyl3** [comment]
> I would like to include myself here for the Bulgarian translation I made. 😃
> 
> Bulgarian: Georgi Georgiev (RacerBG)

Your PR was [this](https://github.com/loot/loot/pull/1343) one and the next official LOOT version will feature Bulgarian as a new language. I've added you to the list, thanks!

**Comment by pStyl3** [comment]
Regarding the standard Portuguese `pt` translations within our masterlists by @ironmagician, while the LOOT application "only" supports Brazilian Portuguese (pt_BR) - this is a very unfortunate situation. Because LOOT itself doesn't support standard Portuguese as of now, there is no way that these `pt` masterlist translations will show up. This is clearly a mistake on our part, somehow we got that mixed up and didn't realize that sooner. We shouldn't have asked for masterlist translations when LOOT doesn't support the language yet, so we can only appolize to @ironmagician! It wasn't out intention to let someone work on translations, when the application itself wasn't ready for them.

Two questions arise out of this situation, with the latter one also being the reason why I'm writing this post in this particular issue.

What needs to be done, so that the `pt` masterlist translations could be displayed?
How do we handle `ironmagician` within our `credits.rst` file?

The first question is relatively easy to answer: LOOT itself needs to be updated to support standard Portuguese (pt).
I'm not gonna ask here, if anyone feels up for the task, but that's the answer.

The second question is quite a problematic one. The problem is, on the one hand `ironmagician` clearly invested some time in these translations so in general he should be credited, without a question, as everybody else providing translations for LOOT as well. But on the other hand, it doesn't make sense to credit someone for a language in credits.rst, if the language itself is not supported by LOOT - because anybody reading credits.rst from that point onwards would be confused, once he or she tries to switch to standard Portuguese. _"LOOT supports standard Portuguese? I'm not seeing it in the options!"_

So I propose the following. For now, and strictly in order to avoid potential confusion, we will continue to not list standard Portuguese as a supported language within credits.rst, because in fact, it isn't supported as of now. With this comes unfortunately, that - for now - `ironmagician` can't be listed as well. However, the moment someone provides a standard Portuguese translation for the LOOT application itself, `ironmagician` will be added aswell. Sorry once again about that, ironmagician!

**Comment by ironmagician** [comment]
I don't have any issue with my name not appearing on the credits, and I totally agree with @pStyl3. `pt-PT` appearing on the credits while not supported will confuse the users.

I think I am able to prepare a translation file for LOOT if you guys are interested. I believe I have the time to have a look at it during this weekend. Just give me a sign. 😃  Already had a glance over the `pt_BR` translations.

> We always differentiate between Portuguese and Brazilian Portuguese to be accurate, though I'm told that someone who can read one can generally make sense of the other.

I would say more than simply make sense, they are the same language. Yet, some differences do exist. 
It is comparable to differences between `en_GB` and `en_US`, which I believe LOOT doesn't distinguish.

**Comment by pStyl3** [comment]
@ironmagician Thank you for understanding. If you would like to translate LOOT itself as well, we of course would appreciate that, but only if you want and time permits. In that case, the best course of action would be to follow the instructions in our [contributing file](https://github.com/loot/loot/blob/master/CONTRIBUTING.md). If you look at the `pt_BR` translation as a reference, please note that this PR was quite a few years ago and as such, a few things might have changed.

**Comment by pStyl3** [comment]
I think that we got everyone, or at least most of the people currently not listed in credits.rst. I've gone through the commit history of the different masterlist and while I am not 100% sure that I didn't miss anyone, I've done what I wanted. As such, the updated credits.rst would look like this:

```
* Translations:
  * Brazilian Portuguese: Kassane, zDasF1xer
  * Bulgarian: Georgi Georgiev
  * Chinese: bluesky404, silentdark
  * Czech: ThePotatoChronicler
  * Danish: Freso
  * Finnish: 3ventic
  * French: Kaos, cpasmoi, Sita
  * German: lpradel, DaCoolX, Infernio, pStyl3
  * Japanese: kuroko, tktk11
  * Korean: SteamB23, sean-kang
  * Polish: Łukasz Niemczyk, Yoosk
  * Russian: Tokc.D.K.
  * Spanish: Sharlikran
  * Swedish: Mikael Hiort af Ornäs, simoneddeland, ddbb07
```
`ironmagician` will also be credited for `Portuguese` once he submits his translation for the LOOT application itself.

That plus the proposed change of
> LOOT's masterlists were largely converted from BOSS's masterlists, and so credit is due to the very large number of sources and people who have contributed to them.

to
> LOOT's masterlists have gotten many additions, improvements, refinements and translations over the years, and so credit is due to the very large number of people and sources (particularly BOSS's masterlists) who have contributed to them.

will resolve this issue.

**Comment by sibir-ine** [comment]
@pStyl3 Maybe we should also write "Brazilian Portuguese" as "Portuguese (Brazilian)" as we did with "Chinese (Simplified)".

**Comment by pStyl3** [comment]
According to @zDasF1xer:
`it seems most places use Portuguese (Brazil)`

So we should change it to that one.

**Comment by sibir-ine** [comment]
@pStyl3 I happened to find loot/fallout3#5. We should add KerberX to Russian & Artaios & Mr. Robo to (?) to Spanish.

**Comment by pStyl3** [comment]
Looks like I overlooked that particular issue after all. Yes, we should add them, though `KerberX` likely would like to be mentioned as `Kerber`, since that is his current name in Discord.

**Comment by pStyl3** [comment]
Done, also added the entry for Italian.

**Comment by DaCoolX** [comment]
Good work!
