### ISSUE TITLE
Update Simplified Chinese (zh_CN) localization

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1437]
I'll be assisting a few friends in updating the localization for Simplified Chinese, so they may need context for a few strings. I'll be asking questions here when I can't provide an answer myself.

For one, does "N/A" stand for "Not applicable" or "Not available"?

**Comment by Ortham** [comment]
LOOT uses N/A as an abbreviation of "Not applicable".

**Comment by sibir-ine** [comment]
Closing this as if I have more questions, I'll ask in loot/loot.github.io#77.
