### ISSUE TITLE
Submitting data to LOOT

### ISSUE THREAD

**Issue by cecell** [loot/loot#1450]
Looking at things from a user's perspective I see two amazing programs: xEdit and LOOT that when used together are even greater still.  LOOT wants xEdit data and Nexus data (link to mod, mod name, etc) but the problem is that the CRC data for the esp/m/l isn't available for query via the Nexus API and after a protracted discussion with Pickysaurus that data/method is unlikely to be implemented because of not only how game specific it is but because on the whole it often represents such a small portion of the mod archive itself.  The alternative that was proposed was a Vortex extension.  I don't know so much about MO2 so I won't bring it up here.  After talking to ElminsterAU, infernio and Pickysaurus here's the picture I assembled in my peon inexperienced brain: 
a Vortex extension adds a right click function to use quickautoclean on a plugin.  xEdit, maybe with a command line switch, spits out the pertinent cleaning data into a text file in a folder in \data\.  Then a right click function could allow the user to submit said cleaning data including the mod's nexus link, mod name, and anything else Vortex has there on hand.  The extension could even verify the file's integrity against the mod archive (to make sure the user hasn't jimmied with it since it was deployed).
I stumbled across the functionality for extracting the CRC32 from any archive supported by 7zip via command line [using 7zip.exe portable so it could be bundled if necessary] functionality via 7zip.exe L -sLt archive.rar -ir!fileyourelookingfor.esm. 
Naturally the data could be formatted however the LOOT team preferred.  

I'm only pitching ideas out, no one has committed to doing anything and I absolutely do not have sufficient experience to do even one thing suggested here.

Thank you for your time.

**Comment by Ortham** [comment]
That sounds similar to features that have existed in Wrye Bash and xEdit, but it's not clear to me why you're posting this here: if you want to write a Vortex extension, that doesn't really involve LOOT.

**Comment by cecell** [comment]
Was suggested to do so by pStyl3 in Discord.  My part is done.

**Comment by pStyl3** [comment]
I wrote the following in the `General` channel of the Nexus discord:

> @Cecell It would probably be in everyone's best interest if you would open a new issue regarding your idea here:
https://github.com/loot/loot/issues/new
>
> Please describe in a detailed but concise way, what it is that you are thinking off. What would the benefits be, for LOOT as well as Nexus? How should it work? What would the LOOT team need to do, and the Nexus team? Are there drawbacks? Infernio linked a good example of what can happen if an automatic submission system / in-app report system goes wrong or stops being looked after.
>
> That should be a base for a discussion, and then WrinklyNinja (Ortham on GitHub) can likely give a response to the request. There are several aspects to think through, so it's best discussed on GitHub, before either side can start on this, if we even reach the conclusion to work on this.

My reason for writing that post was, that I thought that the situation at hand was unclear. You started in our LOOT discord in the `loot-discussions` channel to formulate what you had in mind, like this:

> @MacSplody may I fall down on my knees and beg for something?
> I wish I may I wish I might just be able to submit xEdit cleaning reports
> I beg...of...you... (as the life force drains from my body and I fall over)
> If you would only say yes I would become the community's pack mule and work myself to death
> and we would all be merry

And after MacSplody answered, that `Anyone is free to submit changes https://loot.github.io/docs/contributing/How-To-Contribute`, you're answer was:

> I get shut down...
> URL requested, patches requested
> I'm not going to generate a ton of cleaning data if I'm just gonna have to turn around and add all that data.  That data isn't needed by the mod manager of course, but, well I'm getting spoiled since Vortex handles all that for me
> It can bring the light and the dark side together aka Nexus mod data on the mod tab and then LOOT info on the plugins tab
> I'm literally talking about this only:
```yaml
  - name: '3BBB.esp'
    dirty:
      - <<: *quickClean
        crc: 0x7E8AF9A5
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 2
    clean:
      - crc: 0xF76D8CCD
        util: 'SSEEdit v4.0.3'
```
That did go on for a bit and than the discussion shifted to Nexus' discord. Reading through that I had the same expression, that it still wasn't clearly described, from beginning to end, what the system you are thinking off looks like exactly, and what it would entail for Nexus as well as the LOOT application / team. Hence the request for a detailed but concise description, as at the time it wasn't clear if we need to direcly change something within the LOOT application or not. So it does no harm to start a discussion here, at least until we know that we don't need to do anything for this idea to work.

And that being said, even if we don't need to do something directly, it would still be good to know if at some point we can expect to potentially get a significant amount of cleaning reports more than now and if so, in which form that will be and which information these reports contain.

From reading the first post I already would have two questions, namely
- Can you provide an example what the submitted cleaning data could look like?
- Which information are meant with `anything else Vortex has there on hand` ?

That's my current take on the situation. It would be great if further details could be provided how and if this pans out. And if questiosn arise, they surely can be answered.

**Comment by cecell** [comment]
@pStyl3  Dang dude, you brought it all together thanks! 
Here are the best answers I can think of at the moment to the questions you posed:
1. The cleaning data block you posted above that I had posted before is what xEdit outputs to its log at the end of the its quickautoclean function.  Its format is structured to be the body of a LOOT masterlist entry. However that isn't all that is needed but 2 has the answer to the rest of the data:
2. What data does Vortex have that is needed here? 
First, the name of the mod, not the filename, the name.  So "Immersive Armors" instead of "hothtrooper44_armorcollection.esp".  Most esp, esm, esl don't even properly use the name field within the file itself and even when they do it's halfhearted so that is very unreliable.  
Second, the link to the mod itself on the nexus's site which is a important bit of data required by the LOOT team.
And then finally, pretty much any data that could be desired at some point.  Further speculation about other data that might be needed is an internal discussion for the LOOT team to have.

**Comment by pStyl3** [comment]
@cecell @Pickysaurus
Currently it looks like as if we don't need to do anything on LOOT's side for this to work. So if someone wants to further proceed with it, I would suggest to open a new issue in the Vortex repository.

As such I will close this issue for now, but it could be reopened in case changes to LOOT would become necessary after all.
