### ISSUE TITLE
Opps something went wrong error... Debuglog attached. Still Won't refresh masterlist, after fresh install?

### ISSUE THREAD

**Issue by TiggiTheWillful** [loot/loot#1451]
[error.txt](https://github.com/loot/loot/files/6213962/error.txt)

So I got the age old debuglog error. So, did a fresh install of loot I'm still getting the error. I've attached the log. My only big update has been windows 10 (two days ago)

Any fixes anyone can suggest?

**Comment by sibir-ine** [comment]
@TiggiTheWillful https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors

**Comment by TiggiTheWillful** [comment]
Thank you, that worked!
