### ISSUE TITLE
Add group metadata to the main plugin list view

### ISSUE THREAD

**Issue by rad-aghast** [loot/loot#1476]
This is a (hopefully) simple feature request, to display the group that a plugin has been assigned to in the main plugin list (i.e. the default view when opening LOOT). This might encourage use of groups by making them more visible and easier to manage. As it is, it takes 2-3 clicks just to see which group a plugin has been placed in, which makes it hard to find mods I haven't assigned to a group. As a result, I tend to assign groups only when I'm having problems with my default load order.

That leads to an observation, I'm not quite sure exactly how group metadata is created and managed on the dev end. But as it is, it seems only a handful of mods have group metadata out of the box, based on my personal mod list. Assuming group metadata is based on user feedback, I'd hope that increasing the visibility and ease of using groups would lead to more input on where plugins should be grouped and a better default than just, default.

I'll add that instead of merely showing the current group, a dropdown menu to change groups right from the master plugin list would make the process even smoother, but maybe for design reasons it's best to keep metadata edits to the "edit metadata" menu.

Thanks for supporting a great modding tool.

**Comment by Ortham** [comment]
> This might encourage use of groups

I'm not sure I want this, given how fiddly groups can get, especially when the masterlist changes...

> As a result, I tend to assign groups only when I'm having problems with my default load order.

That sounds like a good thing though? If it ain't broke, don't fix it, right?

As it is, it takes two clicks to see the groups for all your plugins: pick any plugin, click the dropdown menu button on its card, and click the Edit Metadata menu item. That opens the metadata editor, and displays plugin groups under plugin names in the sidebar.

I'm going to close this as wontfix as I can't see myself wanting to implement this. It can be reopened if there's more interest and someone can provide more motivation for why it would be a significant improvement over the status quo.
