### ISSUE TITLE
About section does not list all supported games

### ISSUE THREAD

**Issue by C0rn3j** [loot/loot#1477]
![image](https://user-images.githubusercontent.com/1641362/113491636-9fcd3180-94d2-11eb-8a29-9a0df0a343b8.png)

Namely Morrowind and Nehrim.

It seems this string is present in 15~ files and I do not know how to correctly fix this.

Seems like the same string is present in https://loot.github.io/

**Comment by sibir-ine** [comment]
@C0rn3j The 15 or so files your finding are mostly localization files. It really just needed to be updated in [`src/gui/html/js/translateStaticText.ts`](https://github.com/loot/loot/blob/master/src/gui/html/js/translateStaticText.ts), & then [`resources/l10n/template.pot`](https://github.com/loot/loot/blob/master/resources/l10n/template.pot) needed to be regenerated accordingly. The remaining localization files at [`resources/l10n`](https://github.com/loot/loot/tree/master/resources/l10n) will have to be updated when individual translators update them.

The docs need to be updated separately in quite a few places.
