### ISSUE TITLE
Consider simplifying masterlist update process

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1490]
The current masterlist update process is fairly complicated, and though it works it may be worth simplifying it. Each masterlist is kept in a separate Git repository, and LOOT clones/pulls the online repository for fetch/update the masterlists. This has the following advantages over just downloading the latest files:

* Fetching Git repo updates generally transfers less data than the whole file content
* Git repos provide built in version tracking (commit hash and date)
* Git repos allow LOOT to roll back to a working version of the masterlist if it cannot load the latest without additional downloads

However, it also has the following disadvantages:

* The initial download is larger, as it fetches the entire masterlist history, not just the latest version: the Git repository ranges from 3x larger than the masterlist for the less active repositories to 13x larger for the skyrim repository. Summed up, the repositories are ~10x larger than the masterlists (30 MB vs. 3.4 MB).
* The implementation is more complex.

Rolling back masterlist versions hasn't really been relevant for a while now: I don't think we've pushed a masterlist update that's been broken in years, thanks to better CI on the masterlist repositories that uses LOOT's own metadata loader to check validity. As such, having the whole history available is probably irrelevant, but unfortunately libgit2 does not support shallow clones, so we can't clone just the latest commit (for example). Given that, perhaps it's not even useful to track the masterlist version: perhaps a simple "updated" / "already up to date" message is enough.

If we don't need to track or roll back commits, then it becomes a more direct trade-off between implementation complexity and up-front data transfer vs. ongoing data transfer for updates.

---

Masterlists are kept in separate repositories so that updating a masterlist only fetches updates that are relevant for the current game. However, if diffs are small the cost of irrelevant updates is small, and reporting the relevant commit hash and date could be done by getting the details of the last commit in which a particular masterlist changed, rather than just getting the details of `HEAD`. 

If we don't use Git, a masterlist could be hosted anywhere and the updater would just fetch the file at a given HTTPS or file URL. It then doesn't matter if we store them in separate repositories or not.

---

I need to do more data gathering and thinking about this. There's probably enough going for the current approach that the status quo isn't worth changing, but it'll be good to have done some analysis after 8 years of the current approach.

**Comment by Ortham** [comment]
Update on this: as of libloot v0.17.0, masterlist update no longer supports rolling back to earlier masterlist revisions, so the Git history is useless to libloot (and therefore LOOT): only the current commit is used.

I'll try to profile masterlist update at some point. 

For now, I've got a Skyrim SE LOOT game folder that was created on 2021-12-31. Its `.git` folder is 6.96 MB and contains 25 files. The repository's v0.17 branch currently contains 2937 commits. `masterlist.yaml` is 903 KB.

The Skyrim masterlist is slightly larger, but has ~ 1300 fewer commits.

**Comment by Ortham** [comment]
I did some profiling:

## Raw file download

Opening the raw Skyrim masterlist.yaml in Firefox with the dev tools open, I see that the file size is 894.26 KB but only 161.37 KB was transferred due to gzip compression. The request took 58 ms to complete.

    GET https://raw.githubusercontent.com/loot/skyrim/v0.17/masterlist.yaml
    Transferred 161.37 kB (894.26 kB size)
    Took 58 ms

Raw file download also works if given a specific commit hash:

    GET https://raw.githubusercontent.com/loot/skyrim/08f6d910df2d939b9438736fa221e5f6ca42e314/masterlist.yaml
    Transferred 161.37 kB (894.26 kB size)
    Took 70 ms

## GitHub APIs

Using GitHub API calls is not ideal because GitHub limit unauthenticated requests to 60 per hour. It also locks LOOT into updating from a particular platform, where current support allows from any Git repo (even locally).

### Get repository content API

It's possible to get a file from a repository on GitHub using the [get repository content API](https://docs.github.com/en/rest/reference/repos#get-repository-content), but that only supports files up to 1 MB in size, which a couple of the masterlists are close to. The response includes the file SHA and the base64-encoded content.

    GET https://api.github.com/repos/loot/skyrim/contents/masterlist.yaml?ref=v0.17
    Transferred 365 KB (1.20 MB size)
    Took 278 ms

It's worth noting that the SHA of the file returned by the content API is *not* the commit hash.

### Git Data APIs

It's also possible to get a file using the [Git data APIs](https://docs.github.com/en/rest/reference/git). This involves multiple steps:

1. First get the commit SHA for the relevant masterlist branch:

    GET https://api.github.com/repos/loot/skyrim/git/refs/head/v0.17
    Transferred 1.51 kB (370 B size)
    Took 199 ms

2. Get the tree SHA for the commit:

    GET https://api.github.com/repos/loot/skyrim/git/commits/08f6d910df2d939b9438736fa221e5f6ca42e314
    Transferred 2.30 kB (2.27 kB size)
    Took 194 ms

3. Get the blob SHA for the masterlist in that tree:

    GET https://api.github.com/repos/loot/skyrim/git/trees/bff15575d084fcf6c8ab3318bd8081731f4f1463
    Transferred 1.83 kB (2.03 kB size)
    Took 179 ms

4. Get the blob content for the masterlist.yaml:

    GET https://api.github.com/repos/loot/skyrim/git/blobs/2ef6fe59f7d78e853a523fd36feb4e38f2b31674
    Transferred 364.39 kB (1.20 MB size)
    Took 231 ms

    This supports files up to 100 MB in size and responds with the contents encoded in base64.

### Commits API + Git Data API

Another approach would be to use the [commits API](https://docs.github.com/en/rest/reference/commits#get-a-commit):

    GET https://api.github.com/repos/loot/skyrim/commits/v0.17
    Transferred 3.26 kB (6.87 kB size)
    Took 313 ms

    The response includes the commit tree, so you can then go to step 3 using the Git data APIs above.

## libgit2

Profiling masterlist update in LOOT for Skyrim SE, using MSVS's profiling tools.

### Starting from no Git repository or masterlist.yaml

Took 6381 ms to do the non-UI bits:

- 5694 ms in loot::UpdateFile
    - 5642 ms in git_clone()
      - 5621 ms in git_remote_fetch()
        - 5589 ms in git_remote_download()
          - 5585 ms in git_smart__download_pack()
            - 5349 ms in git_indexer_commit()
              - 5341 ms in resolve_deltas()
                - 4529 ms in git_odb__hashobj()
                  - 4524 ms in SHA1DCUpdate()
    - 37 ms in std::filesystem::copy()
    - 11 ms in std::filesystem::remove_all()
- 429 ms in loot::gui::Game::LoadMetadata()
- 258 ms in loot::MetadataQuery<>::generateDerivedMetadata<>()

It seems that libgit2 is much slower than git when cloning repositories, and
it's mostly due to the hash calculations...

### Update existing masterlist with all remote history fetched

I ran `git checkout HEAD^` in `%LOCALAPPDATA%\LOOT\Skyrim Special Edition` then
ran masterlist update in LOOT.

Took 826 ms to do the non-UI bits:

- 414 ms in loot::gui::Game::LoadMetadata()
- 255 ms in loot::MetadataQuery<>::generateDerivedMetadata<>()
- 79 ms in loot::UpdateFile()
  - 35 ms in loot::GitHelper::CheckoutNewBranch()
  - 15 ms in loot::GitHelper::Fetch()
  - 15 ms in loot::GitHelper::DeleteBranch()

### No update necessary

Took 60 ms to do the non-UI bits:

- 60 ms in loot::UpdateFile()
  - 25 ms in loot::GitHelper::Fetch()
  - 19 ms in loot::GitHelper::IsFileDifferent()
  - 12 ms in loot::GitHelper::IsBranchCheckedOut()

**Comment by Ortham** [comment]
The profiling results above suggest that just downloading the latest masterlist file over HTTPS would give much faster first-time updates and probably not noticeably slow down subsequent updates. Updating from a local Git repository could be done by just copying the file.

The problem with always getting the current file is that it doesn't convey any versioning information, and we currently:

* display the file's commit hash and date
* display if the file matches what's in the commit (i.e. if it's been edited)
* skip updating the UI if running masterlist update doesn't change the latest commit

What we can do is calculate the blob hash for the file we download (which isn't just the content hash but is still doable without libgit2). LOOT could use the blob hash in the same way that it currently uses the commit hash (to display, check for modifications, and skip UI updates). The commit date could be replaced with a "last updated" date that is updated whenever masterlist update changes the blob hash. The last updated date and blob hash could be written to a file that LOOT reads on launch in order to preserve the date and to allow modification checks to work.

One way in which the blob hash would fall short is that it's currently easy to take the commit hash and find the relevant commit in the source repository. A combination of `git log`, `git ls-tree` and `grep` (or a script that handles those details) can be used to find the commit(s) that a blob hash appears in, but that needs a local copy of the masterlist repository to run those commands against, so it's not as useful. I don't know how important that is though. @sibir-ine @MacSplody as masterlist maintainers, how important is being able to easily go from a user's masterlist version to a commit in the relevant Git repo?

**Comment by sibir-ine** [comment]
I find it pretty useful. It makes testing my own changes in real time fast & easy, & I can test a contributor's changes quickly as well.

**Comment by sibir-ine** [comment]
Ah, I see what you mean. Yeah, for testing stuff, pointing to the repo URL & branch is enough; I've never needed to point to a specific commit.

> I was more thinking that if a user reports an issue with some masterlist metadata, if it's ever useful for them to give what commit they're using to help you track down the issue?

I've never needed to ask what commit a user is on. I just assume they're up-to-date with our repos or ask them to update first if they aren't. As long as there's some indication that your masterlist is up-to-date with the branch it's pointed to, I don't personally think it needs to be in the form of the specific commit.

**Comment by MacSplody** [comment]
> how important is being able to easily go from a user's masterlist version to a commit in the relevant Git repo?

Not really important for maintenance, only for making sure users have the latest masterlist or haven't edited the local copy.

**Comment by Ortham** [comment]
OK, sounds like it's worth trying out Git-less masterlist update to see how it is in practice.

**Comment by Ortham** [comment]
Here are some timings to compare with what I measured for libgit2 above. Because Git-less masterlist update is non-blocking, these numbers don't include the time taken to actually perform the HTTP request and get a response, but as far as I can tell that only takes ~ 40 ms, which seems about right given the numbers above.

Updating from nothing is *much* faster, and the other two cases are a little faster, but not really significantly so.

## No masterlist or metadata file

- 694 ms in loot::UpdateMasterlistTask::onMasterlistReplyFinished()
  - 689 ms in loot::UpdateMasterlistTask::finish()
    - 436 ms in loot::gui::Game::LoadMetadata()
    - 251 ms in loot::PluginItem::PluginItem()
  - 4 ms in loot::updateFileWithData()
- 3 ms in loot::UpdateMasterlistTask::onPreludeReplyFinished()
- 2 ms in loot::UpdateMasterlistTask::execute()

## Existing masterlist that does not match latest version

- 704 ms in loot::UpdateMasterlistTask::onMasterlistReplyFinished()
  - 689 ms in loot::UpdateMasterlistTask::finish()
    - 437 ms in loot::gui::Game::LoadMetadata()
    - 251 ms in loot::PluginItem::PluginItem()
  - 5 ms in loot::updateFileWithData()
- 3 ms in loot::UpdateMasterlistTask::onPreludeReplyFinished()
- 3 ms in loot::UpdateMasterlistTask::execute()

## No update necessary

- 5 ms in loot::UpdateMasterlistTask::onMasterlistReplyFinished()
- 2 ms in loot::UpdateMasterlistTask::onPreludeReplyFinished()
- 5 ms in loot::UpdateMasterlistTask::execute()

**Comment by pStyl3** [comment]
Testing with `loot_0.17.0-98-g2a9f03b_gitless-file-update-win64.7z` and prior deleted LOOT folder in `localappdata`, LOOT will immediately tell me on startup that something went wrong. This is included in LOOTDebugLog.txt:
> [23:19:49.980821] [error]: Failed to add path C:\Users\Alpha\AppData\Local\LOOT\backups\LOOT-backup-20220123T231949 to zip file, got error code -111
[23:19:49.980878] [error]: Caught an exception: Failed to add path to zip file

After closing and opening LOOT once more the above issue will not occur. With enabled debug logging, updating the masterlist produced these logs:
> [23:25:17.356548] [info]: No LOOT update is available.
[23:25:21.801094] [trace]: Sending a prelude update request to GET https://raw.githubusercontent.com/loot/prelude/v0.17/prelude.yaml
[23:25:22.059540] [trace]: Finished receiving a response for prelude update
[23:25:22.059969] [error]: Caught exception when getting file revision, assuming file is not up to date: C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml is not a regular file
[23:25:22.062074] [info]: Updated file at C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml, new blob hash is 6d040e7006ce76275cf7d6fc26b0c2b33e559f63
[23:25:22.062114] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml.metadata.toml with ID 6d040e7006ce76275cf7d6fc26b0c2b33e559f63 and date 2022-01-23
[23:25:22.063310] [trace]: Sending a masterlist update request to GET https://raw.githubusercontent.com/loot/oblivion/v0.17/masterlist.yaml
[23:25:22.294338] [trace]: Finished receiving a response for masterlist update
[23:25:22.296180] [error]: Caught exception when getting file revision, assuming file is not up to date: C:\Users\Alpha\AppData\Local\LOOT\games\Oblivion\masterlist.yaml is not a regular file
[23:25:22.298711] [info]: Updated file at C:\Users\Alpha\AppData\Local\LOOT\games\Oblivion\masterlist.yaml, new blob hash is 5cc2b931270201ac5316d48b679e902f2d6c979d
[23:25:22.298743] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\games\Oblivion\masterlist.yaml.metadata.toml with ID 5cc2b931270201ac5316d48b679e902f2d6c979d and date 2022-01-23
[23:25:22.299910] [debug]: Preparing to parse masterlist prelude.
[23:25:22.299978] [debug]: Preparing to parse masterlist.
[23:25:22.300028] [debug]: Parsing metadata list(s).

This is with LOOT being utilised on a SSD and an i9-9900K CPU.

**Comment by Ortham** [comment]
> Testing with `loot_0.17.0-98-g2a9f03b_gitless-file-update-win64.7z` and prior deleted LOOT folder in `localappdata`, LOOT will immediately tell me on startup that something went wrong.

Hmm, that's an error with auto-backup on loading a new version, it should be ignoring `backups/`...

It looks like masterlist update works though.

**Comment by sibir-ine** [comment]
Migration of default settings works as expected. However, migration of non-default settings pointing to other repos isn't ideal. If the repo is local & the branch exists upstream, it migrates as much as possible considering the branch can't be preserved AFAIK (i.e., repo `C:/Users/ph/Documents/GitHub/skyrimse` migrates to source `C:/Users/ph/Documents/GitHub/skyrimse/masterlist.yaml`). However, if the branch doesn't exist upstream, it just overwrites it with our repos. Ideally, it'd still migrate to the given local repo. Forks always get overwritten, though I imagine they'd be fairly simple to migrate (i.e., repo `https://github.com/sibir-ine/oblivion.git` & branch `sib-cleaning-updates` could migrate to source `https://raw.githubusercontent.com/sibir-ine/oblivion/sib-cleaning-updates/masterlist.yaml`).

For updates, they seem to be working properly. They update faster, & the IDs match the latest blob hashes for each masterlist & the prelude.

**Comment by sibir-ine** [comment]
> It only does this migration if you've got the configured branch currently checked out, so in a sense the branch is preserved. Is that the behaviour you want?

Ah, that makes sense. I just observed a migration that didn't quite conform to that scenario, so I wasn't quite sure what the logic was (should've read the commit log 😛).

> If it doesn't exist or if it's not currently checked out, yep. My thinking was that you wouldn't want LOOT to suddenly start using a different branch of the masterlist without you realising.

That makes sense too. However, I feel like it's a bit more disorientating to switch over not only to a different branch but a different repo as well due to migration failing. Would it be possible to do a partial migration in those cases & log a warning that only the repo could be preserved during migration & that the branch will have to be checked out?

If the above isn't possible or you don't think it's appropriate or worth it, as I said earlier, I found a case for local repos where the configured branch doesn't match the checked out branch, but LOOT migrates anyway: when the configured branch is an older branch. If that's intentional (i.e., updating the branch & then migrating), it might be worth noting that in the log in the rare case that someone intentionally had an older branch configured in a custom game profile.

**Comment by Ortham** [comment]
> Would it be possible to do a partial migration in those cases & log a warning that only the repo could be preserved during migration & that the branch will have to be checked out?

Yes, that should be possible.

> I found a case for local repos where the configured branch doesn't match the checked out branch, but LOOT migrates anyway: when the configured branch is an older branch. If that's intentional (i.e., updating the branch & then migrating), it might be worth noting that in the log in the rare case that someone intentionally had an older branch configured in a custom game profile.

Yes, that's intentional, it carries over the previous behaviour of updating old LOOT branches. I can log it so that it's more obvious that there's a two-step migration happening.

**Comment by Ortham** [comment]
> Testing with `loot_0.17.0-98-g2a9f03b_gitless-file-update-win64.7z` and prior deleted LOOT folder in `localappdata`, LOOT will immediately tell me on startup that something went wrong.

This is now fixed.

> Forks always get overwritten, though I imagine they'd be fairly simple to migrate

Any GitHub repo can now be migrated.

> Would it be possible to do a partial migration in those cases & log a warning that only the repo could be preserved during migration & that the branch will have to be checked out?

This is now implemented.

> I found a case for local repos where the configured branch doesn't match the checked out branch, but LOOT migrates anyway: when the configured branch is an older branch. If that's intentional (i.e., updating the branch & then migrating), it might be worth noting that in the log in the rare case that someone intentionally had an older branch configured in a custom game profile.

I've added the extra logging.

**Comment by pStyl3** [comment]
> This is now fixed.

It works now, thanks.

Another excerption from the debug log:

> [19:26:17.560199] [trace]: Sending a prelude update request to GET https://raw.githubusercontent.com/loot/prelude/v0.17/prelude.yaml
[19:26:17.628127] [trace]: Finished receiving a response for prelude update
[19:26:17.628758] [info]: Calculated blob hash for file at C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml: 6d040e7006ce76275cf7d6fc26b0c2b33e559f63
[19:26:17.628779] [info]: C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml is already up to date with blob hash 6d040e7006ce76275cf7d6fc26b0c2b33e559f63
[19:26:17.628800] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml.metadata.toml with ID 6d040e7006ce76275cf7d6fc26b0c2b33e559f63 and date 2022-01-24
[19:26:17.630041] [trace]: Sending a masterlist update request to GET https://raw.githubusercontent.com/loot/fallout4/v0.17/masterlist.yaml
[19:26:17.836586] [trace]: Finished receiving a response for masterlist update
[19:26:17.837250] [error]: Caught exception when getting file revision, assuming file is not up to date: C:\Users\Alpha\AppData\Local\LOOT\games\Fallout4\masterlist.yaml is not a regular file
[19:26:17.839550] [info]: Updated file at C:\Users\Alpha\AppData\Local\LOOT\games\Fallout4\masterlist.yaml, new blob hash is d5ef21427f4a7006517ff2c9f6c3e98a185fd8e2
[19:26:17.839582] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\games\Fallout4\masterlist.yaml.metadata.toml with ID d5ef21427f4a7006517ff2c9f6c3e98a185fd8e2 and date 2022-01-24
[19:26:17.840719] [debug]: Preparing to parse masterlist prelude.
[19:26:17.840786] [debug]: Preparing to parse masterlist.
[19:26:17.840836] [debug]: Parsing metadata list(s).

And:
> [19:31:57.527254] [trace]: Sending a prelude update request to GET https://raw.githubusercontent.com/loot/prelude/v0.17/prelude.yaml
[19:31:57.596416] [trace]: Finished receiving a response for prelude update
[19:31:57.597041] [info]: Calculated blob hash for file at C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml: 6d040e7006ce76275cf7d6fc26b0c2b33e559f63
[19:31:57.597061] [info]: C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml is already up to date with blob hash 6d040e7006ce76275cf7d6fc26b0c2b33e559f63
[19:31:57.597091] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\prelude\prelude.yaml.metadata.toml with ID 6d040e7006ce76275cf7d6fc26b0c2b33e559f63 and date 2022-01-24
[19:31:57.598421] [trace]: Sending a masterlist update request to GET https://raw.githubusercontent.com/loot/skyrimse/v0.17/masterlist.yaml
[19:31:57.662657] [trace]: Finished receiving a response for masterlist update
[19:31:57.666176] [info]: Calculated blob hash for file at C:\Users\Alpha\AppData\Local\LOOT\games\Skyrim Special Edition\masterlist.yaml: cbccbafbf02a500e98817e90b18eb15b7ce95fdc
[19:31:57.666200] [info]: C:\Users\Alpha\AppData\Local\LOOT\games\Skyrim Special Edition\masterlist.yaml is already up to date with blob hash cbccbafbf02a500e98817e90b18eb15b7ce95fdc
[19:31:57.666222] [info]: Writing file revision info for C:\Users\Alpha\AppData\Local\LOOT\games\Skyrim Special Edition\masterlist.yaml.metadata.toml with ID cbccbafbf02a500e98817e90b18eb15b7ce95fdc and date 2022-01-24

The update process is really fast now. 👍

**Comment by sibir-ine** [comment]
Migrating forks, partially migrating local repos, & the extra logging all work great, thanks! Everything looks great AFAICT.

**Comment by Ortham** [comment]
Closing this as it's done and merged as of b76d29e01cf7e45e6791156d1ed3ef0fbbe67f6c.
