### ISSUE TITLE
Sorting Fails If Any Plugin Errors Are Listed

### ISSUE THREAD

**Issue by LordNyriox** [loot/loot#1508]
**Version:**  `0.16.0` 

**Game:**  Oblivion 

**Problem:**  If there are any plugin errors currently detected by LOOT (such as having ZOO and one of its contributing mods installed simultaneously), sorting will fail upon pressing the <kbd>Apply</kbd> button. 

The error message in the debug log is `libloadorder failed to set the load order. Details: Access is denied. (os error 5)`. 

While this particular error message is documented to occur when `plugins.txt` is read-only or otherwise inaccessible, under the previously-described conditions this LOOT-specific error will trigger even if all file permissions are correct. 

Manually removing the error-flagged plugin file (then restarting LOOT) appears to restore LOOT sorting functionality.

**Comment by sibir-ine** [comment]
LordNyriox's [debug log](https://github.com/loot/loot/files/6488245/LOOTDebugLog.txt) from when the issue was first reported in Discord.

Also, I can't reproduce the issue.

**Comment by MacSplody** [comment]
https://discord.com/channels/473542112974077963/473542230095822848/843244969548709898

> Lord Nyriox
>  — 
> Today at 22:54
> Sorting does still error-out the same way in the nightly build you linked. 
> 
> Thankfully, the log messages look more helpful now. 
> 
> Log File Download:  [https://mega.nz/file/OIFhFCYY#FtNHrAiv_L1mW6uHbJCqar_RsIY8LP1-8g8G_7ow9Jw]


[LOOTDebugLog.txt](https://github.com/loot/loot/files/6488332/LOOTDebugLog.txt)

**Comment by LordNyriox** [comment]
> Also, I can't reproduce the issue. 

I believe this whole issue might be a corner case, exposed by my bad habit of cutting down Windows system functionality on my machine.

**Comment by Ortham** [comment]
Hmm, I can't replicate this either - I tried creating copies of `Oblivion.esm` named `Oblivion_1.1.esm`, `Oblivion_GBR SI.esm`, `Oblivion_GOTY non-SI.esm` and then launched LOOT. The error message `This plugin is a modding resource and should not be used in-game.` is displayed, and when I sort and apply the sorted load order, it works. 

Because they're only copies Wrye Bash doesn't recognise the additional master files as valid for swapping, so maybe there's an interaction there that I'm not triggering.

**Comment by LordNyriox** [comment]
@Ortham: 

> Because they're only copies Wrye Bash doesn't recognise the additional master files as valid for swapping 

To create at least one valid ESM variant, you can use GBRPlus's [Main File Patcher](https://www.nexusmods.com/oblivion/mods/49349?tab=description).  Rename the resulting patched ESM to `Oblivion_GBR SI.esm`, and rename the `.bak` file back to `Oblivion.esm`.

**Comment by sibir-ine** [comment]
@LordNyriox FWIW, I tried with a proper version of the GBRPluss-patched ESM, but I couldn't replicate the issue. Can you replicate it with just that file? Also, can you please test with v0.16.1 in case it's been miraculously fixed?

**Comment by Ortham** [comment]
I thought I posted a comment saying the same thing, but apparently not...

**Comment by LordNyriox** [comment]
@sibir-ine: 

> Can you replicate it with just that file? Also, can you please test with v0.16.1 in case it's been miraculously fixed? 

Tested with just `Oblivion_GBR SI.esm`, using LOOT `v0.16.1` (which by the way does not handle High Contrast themes all that well).  The problem is still present. 

I will go ahead and close this Issue, since it seems to be specific to my own sabotaged OS configuration.
