### ISSUE TITLE
Loot failure to update plugin list

### ISSUE THREAD

**Issue by Giantjay** [loot/loot#1509]
I came across this message when trying to sort plugins (loot will not update the plugins) [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)
Any ideas?

**Comment by sibir-ine** [comment]
@Giantjay Please see [this article](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) on how to provide a debug log for your issue.

**Comment by Giantjay** [comment]
thanks I'll try and see if i can do this, ive managed to enable debug logging and its quite the long list

**Comment by sibir-ine** [comment]
@Giantjay You can just drag the file into a comment & post it.

**Comment by Giantjay** [comment]
thank you do i post it in the same location? I was directed to here by the mod authors link on the posts page on nexus

**Comment by sibir-ine** [comment]
@Giantjay Yes, please post it here.

**Comment by Giantjay** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/6489084/LOOTDebugLog.txt)

**Comment by Giantjay** [comment]
is this correct ?

**Comment by sibir-ine** [comment]
Yes, thank you. I'll take a look.

**Comment by Giantjay** [comment]
ok thank you

**Comment by sibir-ine** [comment]
@Giantjay Try the solutions discussed in [this section](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors) of the FAQ.

**Comment by Giantjay** [comment]
ok will look now

**Comment by Giantjay** [comment]
I looked at the page but I solved it my own way,  by de activating Bug Fixes SSE v3 as I was having a problem installing Dll Plugin Loader https://www.nexusmods.com/skyrimspecialedition/mods/10546
thank you for your help it got me to read up on things I'd forgotten about years ago

**Comment by sibir-ine** [comment]
You're welcome. That shouldn't have any impact on the issue, but, since the issue's solved, I'll close this. Feel free to reopen it if it comes back.
