### ISSUE TITLE
IDP.generic reported with Avast for 16.1

### ISSUE THREAD

**Issue by seddonac** [loot/loot#1510]
False positive or corrupt file?

**Comment by pStyl3** [comment]
It's a false positive result from Avast. See [here](https://www.virustotal.com/gui/file/60f8ece14fcb015fa7b4fa24fa8be275372864e3efb158762ce6dd9b3334072b/detection/f-60f8ece14fcb015fa7b4fa24fa8be275372864e3efb158762ce6dd9b3334072b-1621776253).
