### ISSUE TITLE
Executable deleted

### ISSUE THREAD

**Issue by Kubbejoager** [loot/loot#1511]
This new version opens for a couple of seconds, closes and deletes the LOOT.exe file. And after that I can't reinstall the previous or new version. It says access is denied!

**Comment by pStyl3** [comment]
Uninstall LOOT completely, including deleting the `LOOT` folder in `C:\%localappdata%` (you also could simply rename it to `_LOOT` for example). Then install the new version.

**Comment by Ortham** [comment]
This sounds like antivirus quarantining the new executable, I can't think how LOOT would delete itself.

**Comment by RacerBG** [comment]
> This sounds like antivirus quarantining the new executable, I can't think how LOOT would delete itself.

That's correct. Avast always do this to me when I install a new version of anything which is not yet in their databases.

**Comment by sibir-ine** [comment]
@Kubbejoager Please try making an exception for LOOT in your AV & let us know whether it works.

**Comment by Kubbejoager** [comment]
I had to make an exception for a file called IDP.Generic, I looked it up and that usually is a false positive with Avast. It works now so I guess this is closed.
