### ISSUE TITLE
Support for offline?

### ISSUE THREAD

**Issue by snekandsnoot** [loot/loot#1538]
My internet is cut off for the time being. Right now, I plan to use this tool because I'm afraid my manual sorted load order for Fallout 4 isn't correct. When I tried installing LOOT, it needs to download additional files but it fails because it needs some kind of connection to a server. Is there any possibility for offline support?

**Comment by sibir-ine** [comment]
@snekandsnoot If you're able to, you can download & install the archive & MSVC x86 redistributable separately to get around this issue. However, if LOOT also isn't able to connect to the internet, you'll need to download the masterlist manually as well. Instructions on doing so are in the FAQ on our [website](https://loot.github.io/), but I'm also having internet issues right now & can't link to the specific section. It's in the section about getting git-related errors.

**Comment by snekandsnoot** [comment]
> @snekandsnoot oh ok I'll try that out. Thanks

**Comment by sibir-ine** [comment]
@snekandsnoot Were you able to install LOOT?

**Comment by sibir-ine** [comment]
@snekandsnoot I'll assume it worked out for you, but please feel free to let us know if you have any more questions.

@Ortham Unless you think it's worth making it so that the installer can proceed if there are connectivity issues (i.e., skipping installing the MSVC redist.), this issue can be closed.

**Comment by Ortham** [comment]
The installer should already skip downloading the MSVC redist if it is already installed (though detecting the appropriate versions is complicated so it may download and install unnecessarily). I don't have any plans to make changes to the installer in response to this issue.
