### ISSUE TITLE
error when downloading additional files

### ISSUE THREAD

**Issue by LuaNoob** [loot/loot#1540]
![Screenshot_13](https://user-images.githubusercontent.com/85694952/121553002-1d656e80-ca3b-11eb-8a03-61c3030b0c3d.png)

this keeps happening when i'm trying to install LOOT, tried finding a fix but can't find any

**Comment by sibir-ine** [comment]
@LuaNoob It's timing out when trying to download the MSVC redist. Make sure your firewall &/or antivirus aren't preventing the installer from proceeding. If that doesn't work, you can install the [redist.](https://download.visualstudio.microsoft.com/download/pr/749aa419-f9e4-4578-a417-a43786af205e/d59197078cc425377be301faba7dd87a/vc_redist.x86.exe) & [archive](https://github.com/loot/loot/releases/download/0.16.1/loot_0.16.1-0-g18e28e9_0.16.1.7z) separately to get around it.

**Comment by LuaNoob** [comment]
@sibir-ine thanks! it works!
