### ISSUE TITLE
Feature Request: Export/Import UserMetaData

### ISSUE THREAD

**Issue by MachMX** [loot/loot#1543]
I find being able to make your UserMetaData rules very good and sometimes critical tool for some mods which require very specific overrides between them and other mods which are not resolved on the masterlist, or just happen to be needed for user created patches.

But making this UserMetaData changes in LOOT is very time consuming. And currently there is no way to export/import any UserMetaData when starting on a new install on a new machine (at least from within the GUI, if there is a way to just backup a UserMetaData file, it would be welcome to know).

**Comment by Ortham** [comment]
Your user metadata is stored at `%LOCALAPPDATA%\LOOT\<game>\userlist.yaml`, just take a copy of that.

**Comment by MachMX** [comment]
Okay this solves a lot of issues I had, thanks! Wish it was on the docs *facepalm*
