### ISSUE TITLE
LOOT Issue cropping up from time to time.

### ISSUE THREAD

**Issue by Panther1232** [loot/loot#1544]
I'm getting this.

Error: Game-specific settings could not be initialized. Cannot set the current game: the game with folder "Fallout4" cannot be found. If it is installed, try running the game's launcher to register its location.

My issue is, I'm not trying to sort Fallout 4, I'm trying to sort Fallout New Vegas. It won't show me any other game option. I will admit that the last game I sorted was 4 and I've since uninstalled it. But that's not what I am needing to sort now. The game list at the top is blank. I don't have the greatest internet connection, so installing Fallout 4 just to use LOOT is not an ideal solution.

This is also showing up when I start it:
![LOOT Issue](https://user-images.githubusercontent.com/85956693/122093493-093abc00-ce03-11eb-9afe-6e4569335887.png)

**Comment by sibir-ine** [comment]
@Panther1232 Please set `Default Game` to `Fallout: New Vegas`, or set it to `Autodetect` & choose Fallout: New Vegas from the Games drop-down menu at the top. You can also use the [`--game` command-line parameter](https://loot.readthedocs.io/en/latest/app/usage/initialisation.html). If it's also having trouble detecting FNV, please run its launcher to regenerate its registry key or manually input it's directory path in its settings entry.

**Comment by Panther1232** [comment]
> @Panther1232 Please set `Default Game` to `Fallout: New Vegas`, or set it to `Autodetect` & choose Fallout: New Vegas from the Games drop-down menu at the top. You can also use the [`--game` command-line parameter](https://loot.readthedocs.io/en/latest/app/usage/initialisation.html). If it's also having trouble detecting FNV, please run its launcher to regenerate its registry key or manually input it's directory path in its settings entry.

The first one worked. The one at the top
