### ISSUE TITLE
Adding a new mode to find sorting issues more quickly

### ISSUE THREAD

**Issue by primem0ver** [loot/loot#1545]
I had a lengthy discussion in the help channel of discord regarding issues that me and others are having with the cycle detection.  In that discussion I mentioned the issue of having multiple cyclic errors in large load orders taking a long time to discover and wanted an option to disable/ignore group rules for those errors.  I was told that this was counter to the purpose of Loot.  I understand that dilemma but I want to proposed a suggestion that will satisfy this need without compromising the purpose of Loot.  Here it is:

I am sure by now you understand that I am not the only person with a very large load order.  Our subset realizes that we may not get a working load order the first time we try.  I don't believe you need to make a subset of cyclic interaction rules (this objection to my proposal was brought up in the Discord Conversation).  The solution that will keep the purpose of Loot and satisfy our needs is to simply add a "diagnostic mode" or mode with some such title.  Let people know that this mode doesn't guarantee a working load order.  Its purpose is to find problems quickly.  

This mode would attempt to follow all rules but it would be flexible and ignore any conflicting rules except master rules ONLY for specific mods affected by a cycle (NOT other mods in the group which aren't part of the problem).  It would report that rule violation and affected mods to the user so the user knows what to fix.  It doesn't interrupt the sorting session to ask anything from the user.  For these mods only, it uses only their masters as hard rules in order to resolve the cyclic problem; it outputs the problem to let the user know there is a significant problem worth attending to; and then moves on. The point here is to find where we need to make fixes as quickly as possible.  Then the user goes back, fixes all the problems and sets LOOT to "normal" mode where groups (and other user-made rules) are enforced in order to get a working load order.

**Comment by Ortham** [comment]
First of all, LOOT's sorting performance scaling very poorly with load order size is a known issue, tracked by #1370. It's a difficult problem to solve and unfortunately one that I'm not currently enthusiastic/motivated/excited to solve. However, from the logs shared in the linked issue, a 1,200 plugin load order takes ~ 20 seconds without a userlist to get to the point of adding overlap edges, which isn't fast but is a lot less than the nearly 7 minutes it takes to complete sorting. 

Once LOOT starts adding overlap edges, it only adds edges that will not cause cycles (and checking that is why it takes so much longer past that point). This means that we could move the cycle check earlier in the sorting process, so you'd get feedback much faster. Can you share a debug log of a sorting run so I can understand the timings involved in your case and see how much of a difference that change would make?

As for your proposal, there are a couple of problems with the approach you've described:

1. Once you've got a cycle, there's often no way for the application to know which bit of metadata caused the cycle. To put it another way, removing any one of the links in the chain would break it and resolve the problem, but the application doesn't know which link *should* be removed. As such, depending on your starting point, all the rules involved are conflicting.
2. Ignoring rules has knock-on effects for the rest of the load order, and the order in which plugins' rules are evaluated affects the result. This means that ignoring some rules may have a wider impact on the resulting load order than intended, so the result may not be a workable load order, but more importantly it means that the existence of other cycles may be affected, so a run wouldn't necessarily ever find more than one cycle at a time.

**Comment by Ortham** [comment]
LOOT v0.17.0 introduced a check for cycles before adding overlap edges, so fails before the slowest bit of sorting: using the same example as above, it's the difference between failing after 20 seconds instead of after 7 minutes, and that difference will only be more pronounced with even larger load orders.

Given that, I don't think a separate mode is needed, so I'm going to close this as resolved.
