### ISSUE TITLE
LOOT finds game, but no mods

### ISSUE THREAD

**Issue by jacovny** [loot/loot#1557]
I had LOOT installed and ran it through NMM flawlessly for several years. After a computer issue that wiped out some of my apps, I reinstalled everything. LOOT recognizes that the game is installed and displays all of the DLCs, but no mods, although I have around 200 installed and working via NMM. I suspect it's something to do with the location in which I've installed it (as I run all my games through my D: drive, which is also where NMM and LOOT are), but I've been researching the problem for 2 days and have come up with nothing. I'd be grateful for any advice. Thank you.

**Comment by Ortham** [comment]
Are you running LOOT through NMM? If not, you won't see any of the mods that NMM has installed, because they're not actually in the game's Data folder.

**Comment by jacovny** [comment]
> Are you running LOOT through NMM? If not, you won't see any of the mods that NMM has installed, because they're not actually in the game's Data folder.

Yes sir, I'm running it through NMM. Previously I couldn't get NMM or the game to recognize the mods I was trying to reintegrate after the reinstall, so I was advised to move them into the game's Data folder. Now both the game and NMM recognizes them and runs them, but LOOT doesn't acknowledge them. It always did before, when I just allowed everything to install on my C: drive by default. Should I move them somewhere else? Install LOOT somewhere else?

**Comment by Ortham** [comment]
You shouldn't need to move anything. Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by jacovny** [comment]
> You shouldn't need to move anything. Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

Thank you for your help. I have attempted to attach the log; hopefully I did it correctly...
[LOOTDebugLog.txt](https://github.com/loot/loot/files/6842009/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Yes, that's correct. It's saying you've got Skyrim SE installed at `D:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data` - just to double-check, if you open that folder, do you see the plugins you've installed? The log shows LOOT isn't finding anything other than the official plugins.

**Comment by jacovny** [comment]
Ooooh boy... it looks like I've had the game double-installed this whole time without realizing it. I've had it installed at D:\Fallout4\steamapps\common\Skyrim Special Edition, and that pathway is also where my mods are. Meanwhile, LOOT has been searching the alternate "SteamLibrary" pathway and not finding anything. I feel like a fool. Well, what would you suggest for fixing it? Will deleting the alternate installation fix the problem?

**Comment by Ortham** [comment]
Deleting the alternate installation will stop LOOT from using it, but if LOOT got the path from the game's Registry entry it may not be able to find the correct path. Try also running the game's launcher through Steam to get it to update the Registry entry, then run LOOT.

**Comment by jacovny** [comment]
You were correct. After deleting the alternate installation, LOOT was unable to find it, so I tried launching through Steam. A window popped up telling me that the game was updating. When it finished, the game had reinstalled in the "SteamLibrary" pathway, same as before. Since that's where Steam is determined that it should be located, should I just move all of my folders over from the other installation to here?

**Comment by Ortham** [comment]
Probably, if only to keep Steam happy.

**Comment by jacovny** [comment]
A can't thank you enough. That seems to be what Steam was after; I just ran loot, and it recognized and sorted all my plug-ins. They're no longer listed under the "mods" tab anymore strangely, but they're all present under the "plug-ins" tab, and they're functioning perfectly in game. Thanks again for your patience in working through the issue.

**Comment by Ortham** [comment]
OK, problem solved, so I'll close this.
