### ISSUE TITLE
Won't run due to 0xc00007b

### ISSUE THREAD

**Issue by Papajack55** [loot/loot#1559]
Every time I bring up LOOT, it shows the above message and says press to stop message. How do I fix this?

**Comment by MacSplody** [comment]
> Every time I bring up LOOT, it shows the above message and says press to stop message. How do I fix this?
> Won't run due to 0xc00007b

Google search points to it being an issue with your OS or a corrupt Visual C++ Redistributable Runtime and not LOOT specifically.
Fixing issues like that is outside of LOOT support, but there's a possible solution listed [here](https://www.reddit.com/r/windows/comments/df4b78/how_to_solve_error_0xc00007b_windows_10_64bit/f34s28l?utm_source=share&utm_medium=web2x&context=3).
