### ISSUE TITLE
Error sending data: (12007) The server name or address could not be resolved

### ISSUE THREAD

**Issue by PiestoGo** [loot/loot#1575]
I get this when I try to install LOOT. Just a little bit of background. I reformatted the laptop few months ago and it had LOOT on it then. Perhaps this error is related to that?

**Comment by pStyl3** [comment]
Which version of LOOT do you try to install, the latest one v0.16.1? Also, do you use the installer `LOOT.Installer.exe` or the preconfigured archive `loot_0.16.1-0-g18e28e9_0.16.1.7z` to install LOOT, and which Operating System do you use?

**Comment by PiestoGo** [comment]
I chose LOOT.Installer.exe Win10 64x

**Comment by sibir-ine** [comment]
@PiestoGo Sorry that this issue went unresolved for so long. Are you still experiencing this issue? If so, are you able to successfully install LOOT through the archive?
