### ISSUE TITLE
No longer notices if esp/esm has ITMs or such

### ISSUE THREAD

**Issue by Dreifels** [loot/loot#1578]
for longer time already LOOT does not show anymore if an esp/esm has ITMs or such. It takes all as if they  would be fine.
No error in log
[LOOTDebugLog.txt](https://github.com/loot/loot/files/7018052/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
@Dreifels What are the names of the plugins in question & what are their checksums? You can see their checksums in their plugin cards in LOOT after sorting (you don't have to apply the sort).
![image](https://user-images.githubusercontent.com/69141501/130170500-fc0da86a-e41a-482a-84d7-e39a06026bb1.png)

**Comment by Dreifels** [comment]
before autoclean:
Jehanna.esp
C4A17F1D

autocelan reports:
Removing: GRUP Cell Temporary Children of [CELL:0347AE77] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -1,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347AE63] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -4,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347AE0D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -16,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347AD6F] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-8)
Removing: GRUP Cell Temporary Children of [CELL:0347AD67] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-7)
Removing: GRUP Cell Temporary Children of [CELL:0347AD61] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-6)
Removing: GRUP Cell Temporary Children of [CELL:0347AD53] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-3)
Removing: GRUP Cell Temporary Children of [CELL:0347AD4D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-2)
Removing: GRUP Cell Temporary Children of [CELL:0347AD47] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-1)
Removing: GRUP Cell Temporary Children of [CELL:0347ADAD] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-16)
Removing: GRUP Cell Temporary Children of [CELL:0347ADA3] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-14)
Removing: GRUP Cell Temporary Children of [CELL:0347ADA1] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-15)
Removing: GRUP Cell Temporary Children of [CELL:0347AD97] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-13)
Removing: GRUP Cell Temporary Children of [CELL:0347AD91] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-12)
Removing: GRUP Cell Temporary Children of [CELL:0347AD7F] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-11)
Removing: GRUP Cell Temporary Children of [CELL:0347AD75] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-9)
Removing: GRUP Cell Temporary Children of [CELL:0347ADEF] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-24)
Removing: GRUP Cell Temporary Children of [CELL:0347ADE9] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-23)
Removing: GRUP Cell Temporary Children of [CELL:0347ADDF] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-22)
Removing: GRUP Cell Temporary Children of [CELL:0347ADB7] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-17)
Removing: GRUP Cell Temporary Children of [CELL:0347AE13] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347820E] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -1,22)
Removing: GRUP Cell Temporary Children of [CELL:0347820A] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -2,22)
Removing: GRUP Cell Temporary Children of [CELL:03478206] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -3,22)
Removing: GRUP Cell Temporary Children of [CELL:0347AD29] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -14,22)
Removing: GRUP Cell Temporary Children of [CELL:0347AD15] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -13,22)
Removing: GRUP Cell Temporary Children of [CELL:0347AD1D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,21)
Removing: GRUP Cell Temporary Children of [CELL:0347AD41] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,0)
Removing: GRUP Cell Temporary Children of [CELL:0347AD3D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,1)
Removing: GRUP Cell Temporary Children of [CELL:0347AD39] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,2)
Removing: GRUP Cell Temporary Children of [CELL:0347AD35] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at -17,3)
Removing: GRUP Cell Temporary Children of [CELL:0347066A] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 20,-1)
Removing: GRUP Cell Temporary Children of [CELL:0347AF15] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-24)
Removing: GRUP Cell Temporary Children of [CELL:0347AB6D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-23)
Removing: GRUP Cell Temporary Children of [CELL:0347AB5B] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-22)
Removing: GRUP Cell Temporary Children of [CELL:0347AB57] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-21)
Removing: GRUP Cell Temporary Children of [CELL:0347AFA5] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347AF3B] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-27)
Removing: GRUP Cell Temporary Children of [CELL:0347AF29] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-26)
Removing: GRUP Cell Temporary Children of [CELL:0347AF1F] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,-25)
Removing: GRUP Cell Temporary Children of [CELL:0347AEB7] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 4,-26)
Removing: GRUP Cell Temporary Children of [CELL:0347AE81] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 0,-28)
Removing: GRUP Cell Temporary Children of [CELL:0347AC3D] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 19,22)
Removing: GRUP Cell Temporary Children of [CELL:0347AC3B] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 18,22)
Removing: GRUP Cell Temporary Children of [CELL:0347827E] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 16,22)
Removing: GRUP Cell Temporary Children of [CELL:0347ABD9] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 21,11)
Removing: GRUP Cell Temporary Children of [CELL:0347ABD5] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 21,10)
Removing: GRUP Cell Temporary Children of [CELL:03470660] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 21,3)
Removing: GRUP Cell Temporary Children of [CELL:03470658] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 21,5)
Removing: GRUP Cell Temporary Children of [CELL:03470656] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 21,4)
Removing: GRUP Cell Temporary Children of [CELL:0347826E] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 15,22)
Removing: GRUP Cell Temporary Children of [CELL:03478254] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 13,22)
Removing: GRUP Cell Temporary Children of [CELL:0347824E] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 12,22)
Removing: GRUP Cell Temporary Children of [CELL:03478248] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 11,22)
Removing: GRUP Cell Temporary Children of [CELL:03478242] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 10,22)
Removing: GRUP Cell Temporary Children of [CELL:0347823C] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 9,22)
Removing: GRUP Cell Temporary Children of [CELL:03478236] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 8,22)
Removing: GRUP Cell Temporary Children of [CELL:03478230] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 7,22)
Removing: GRUP Cell Temporary Children of [CELL:0347822A] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 6,22)
Removing: GRUP Cell Temporary Children of [CELL:03478226] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 5,22)
Removing: GRUP Cell Temporary Children of [CELL:03478222] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 4,22)
Removing: GRUP Cell Temporary Children of [CELL:0347821E] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 3,22)
Removing: GRUP Cell Temporary Children of [CELL:0347821A] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 2,22)
Removing: GRUP Cell Temporary Children of [CELL:03478216] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 1,22)
Removing: GRUP Cell Temporary Children of [CELL:03478212] (in Kirkmore "Kirkmore" [WRLD:031D31E6] at 0,22)
Removing: [LAND:00002972]
Removing: GRUP Cell Temporary Children of [CELL:00001972] (in Tamriel "Skyrim" [WRLD:0000003C] at -50,33)
Removing: [CELL:00001972] (in Tamriel "Skyrim" [WRLD:0000003C] at -50,33)
Removing: [LAND:00002941]
Removing: GRUP Cell Temporary Children of [CELL:00001941] (in Tamriel "Skyrim" [WRLD:0000003C] at -49,34)
Removing: [CELL:00001941] (in Tamriel "Skyrim" [WRLD:0000003C] at -49,34)
Removing: [NAVM:0010365A] (in GRUP Cell Temporary Children of [CELL:00006EAE] (in Tamriel "Skyrim" [WRLD:0000003C] at -39,24))
Removing: [NAVM:0010314E] (in GRUP Cell Temporary Children of [CELL:00006E71] (in Tamriel "Skyrim" [WRLD:0000003C] at -40,26))
Removing: [NAVM:00103668] (in GRUP Cell Temporary Children of [CELL:00006EB2] (in Tamriel "Skyrim" [WRLD:0000003C] at -43,24))
Removing: [NAVM:0010316B] (in GRUP Cell Temporary Children of [CELL:00006EB1] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,24))
Removing: [NAVM:0010317C] (in GRUP Cell Temporary Children of [CELL:00006EB1] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,24))
Removing: [NAVM:00103149] (in GRUP Cell Temporary Children of [CELL:00006E54] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,27))
Removing: [NAVM:00103148] (in GRUP Cell Temporary Children of [CELL:00006E53] (in Tamriel "Skyrim" [WRLD:0000003C] at -41,27))
Removing: GRUP Cell Temporary Children of [CELL:00006E53] (in Tamriel "Skyrim" [WRLD:0000003C] at -41,27)
Removing: [NAVM:0010315D] (in GRUP Cell Temporary Children of [CELL:00006E36] (in Tamriel "Skyrim" [WRLD:0000003C] at -43,28))
Removing: [NAVM:0010313D] (in GRUP Cell Temporary Children of [CELL:00006E35] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,28))
Removing: [NAVM:0200C3EE] (in GRUP Cell Temporary Children of [CELL:00006E1A] (in Tamriel "Skyrim" [WRLD:0000003C] at -46,29))
Removing: [NAVM:0010313F] (in GRUP Cell Temporary Children of [CELL:00006E16] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,29))
Removing: [NAVM:0010312A] (in GRUP Cell Temporary Children of [CELL:00006DF7] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,30))
Removing: [NAVM:00108998] (in GRUP Cell Temporary Children of [CELL:00006DF7] (in Tamriel "Skyrim" [WRLD:0000003C] at -42,30))
Removing: [LAND:00007E95]
Removing: GRUP Cell Temporary Children of [CELL:00006E81] (in Tamriel "Skyrim" [WRLD:0000003C] at -56,26)
Removing: [CELL:00006E81] (in Tamriel "Skyrim" [WRLD:0000003C] at -56,26)
Removing: [LAND:00007E94]
Removing: GRUP Cell Temporary Children of [CELL:00006E80] (in Tamriel "Skyrim" [WRLD:0000003C] at -55,26)
Removing: [CELL:00006E80] (in Tamriel "Skyrim" [WRLD:0000003C] at -55,26)
Removing: [LAND:00007E75]
Removing: GRUP Cell Temporary Children of [CELL:00006E61] (in Tamriel "Skyrim" [WRLD:0000003C] at -55,27)
Removing: [CELL:00006E61] (in Tamriel "Skyrim" [WRLD:0000003C] at -55,27)
Removing: [LAND:00007E96]
Removing: GRUP Cell Temporary Children of [CELL:00006E82] (in Tamriel "Skyrim" [WRLD:0000003C] at -57,26)
Removing: [CELL:00006E82] (in Tamriel "Skyrim" [WRLD:0000003C] at -57,26)
Removing: GRUP Cell Temporary Children of [CELL:0316102C] (in Tamriel "Skyrim" [WRLD:0000003C] at -58,14)
[Removing "Identical to Master" records done]  Processed Records: 55699, Removed Records: 98, Elapsed Time: 00:00
[00:00] Saving: Jehanna.esp.save.2021_08_20_13_29_04
[00:00] Queued renaming of save "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Jehanna.esp.save.2021_08_20_13_29_04" to "D:\Steam\steamapps\common\Skyrim Special Edition\Data\Jehanna.esp" on shutdown.
[00:00] Done saving.
[00:00] Start: Applying Filter
[00:10] still applying Filter
[00:16] Done: Applying Filter, [Pass 1] Processed Records: 58309, [Pass 2] Processed Records: 55602, Remaining unfiltered nodes: 55602, Elapsed Time: 00:15
[Undeleting and Disabling References done]  Processed Records: 55601, Undeleted Records: 0, Elapsed Time: 00:00
[Removing "Identical to Master" records done]  Processed Records: 55601, Removed Records: 0, Elapsed Time: 00:00

LOOT Masterlist Entries

  - name: 'Jehanna.esp'
    dirty:
      - <<: *quickClean
        crc: 0xC4A17F1D
        util: '[SSEEdit v4.0.3](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 98
    clean:
      - crc: 0x0BB98D51
        util: 'SSEEdit v4.0.3'
[00:00] Quick Clean mode finished.
[00:37] Background Loader: finished

**Comment by sibir-ine** [comment]
LOOT only displays cleaning data manually added to the masterlists. There isn't an entry for **Jehanna.esp** in the SSE masterlist at the moment, so it won't show any cleaning data for it. If you have a link to the mod in question, we can add an entry for it.

**Comment by Dreifels** [comment]
I remember, in hostory (past year) LOOT also did work for new mods well (in this point). So as LOOT works now, user always believes all is fine.
Also, some weeks ago I uploaded lot of links and crcs but none of them LOOT realised. None is shown as clean This I made because translation of a mod (and new cleaning) changes crc, but all 186 translations I made, cleaned, uploaded crcs, but not shown as clean in LOOT.
In so far, in between LOOT is worthless for this, the only use is sort of load order. 

unfortunately, because typing mistake of pw when I enter AFKMods last time, I'm blocked there, can't log in anymore. Mail to them gives no response.
This also is a suboptimal thing, that crc need to get posted there. Very unhandy.

**Comment by sibir-ine** [comment]
> I remember, in hostory (past year) LOOT also did work for new mods well (in this point).

It's possible cleaning reports for some newly released mods were provided soon after they were released, but LOOT hasn't, to my knowledge, ever had the ability to automatically detect dirty edits (@Ortham, please correct me on this if this isn't the case). Wrye Bash can detect deleted references & navmeshes, so that might be what you're thinking of too.

> So as LOOT works now, user always believes all is fine.

We have a separate indicator for when files are verified to be clean, so, if a plugin has neither a dirty edits message nor a verified clean badge, that means we don't have cleaning data for that checksum of the plugin, the plugin was dirty & we opted not to include a checksum for the cleaned version of the plugin as it's often volatile, or the author of the mod states that the mod has intentional ITMs. I think the badge is preferable to a message indicating the plugin is clean as that would clutter up the UI with messages a user really only needs to see once.

![image](https://user-images.githubusercontent.com/69141501/130231268-3e0fb218-d037-4833-9a91-a73c5edd1e76.png)

> Also, some weeks ago I uploaded lot of links and crcs but none of them LOOT realised.

In order to add cleaning data for a mod to one of the masterlists, we require a link to the mod. @pStyl3 & I have explained before that this is to make maintenance of the masterlists more reasonable for us. Recording the location of a plugin makes it easier to access the plugin later in case we want to update information for it or remove the entry if the plugin no longer exists. Take a look at the [Skyrim](https://github.com/loot/skyrim/blob/v0.15/masterlist.yaml), [Fallout: New Vegas](https://github.com/loot/falloutnv/blob/v0.15/masterlist.yaml), [Fallout 3](https://github.com/loot/fallout3/blob/v0.15/masterlist.yaml), & [Oblivion](https://github.com/loot/oblivion/blob/v0.15/masterlist.yaml) masterlists to see why this is so important. There are thousands of entries without any links, so we have to scour Nexus & the internet whenever we want to update any of them. That makes issues like https://github.com/loot/skyrim/issues/196 & https://github.com/loot/fallout3/issues/81 a logistical nightmare. It's because of issues like these that we request links for plugins before we add them to the masterlists & why it's nonnegotiable. That's also why your previous reports weren't added. Even if we tried to find all the links ourselves, there's no guarantee they're for the exact plugin or version of the plugin the reports pertain to. All of this logic also applies to why we don't add reports for mods that aren't publicly available or behind a paywall as we can't easily access them for maintenance as well.

> This also is a suboptimal thing, that crc need to get posted there.

You can also post them in our [Discord](https://loot.github.io/discord/) or file an issue in the repository of the relevant masterlist (i.e., [Skyrim Special Edition](https://github.com/loot/skyrimse/issues) in your case).

**Comment by Dreifels** [comment]
I uploaded new some, will see if it works.

**Comment by sibir-ine** [comment]
Considering the issue initially brought up has been addressed, I'll close this issue. We'll add your new reports when we get the chance, thanks.

**Comment by Ortham** [comment]
> It's possible cleaning reports for some newly released mods were provided soon after they were released, but LOOT hasn't, to my knowledge, ever had the ability to automatically detect dirty edits (@Ortham, please correct me on this if this isn't the case).

Just to confirm, this is correct.
