### ISSUE TITLE
Update contributing.rst (xEdit's QAC, URL Requirement and acceptable URLs)

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1579]
[contributing.rst](https://github.com/loot/loot/blob/master/docs/app/contributing.rst)

> LOOT is very much a community project, and contributions from its users are very welcome, whether they be metadata, translations, code or anything else. The best way to contribute is to make changes yourself at GitHub! It's the fastest way to get changes you want applied, and you'll get your name automatically immortalised in our credits.
> 
> If you encounter an issue with LOOT, check the Frequently Asked Questions page in case a solution is available there. Otherwise, general discussion and support takes place in LOOT's official forum thread, which is linked to on LOOT's homepage.
> 
> If you want to submit metadata, the easiest way to do so is to add the metadata to your own LOOT install, then use the Copy Metadata feature to easily get it in a form that you can then edit into a masterlist on GitHub or post in the official forum threads.
> 
> Information on dirty plugins is very welcome, but for such information to be useful we require at least the filename and the CRC of the dirty plugin. The CRC may be calculated using Wrye Bash or 7-Zip, with other sources being unverified as correct. In the case of 7-Zip, the "CRC checksum for data" is the one required. Any other information, such as the ITM record and deleted reference counts, is very welcome.

- [x] Rename `forum threads` to `forum thread` and link to our thread on AFKmods
- [x] Mention our Discord server
- [x] Rewrite the last paragraph to ask users to submit a QAC report, "that includes the filename, CRC and a link to the mod" and that ideally the user should check if the masterlist already includes information on the plugin in question
- [x] Mention that providing URLs to the plugins in question is a requirement. We need to be able to verify the legitimy of the plugin's source as well as the legitimy of the plugin itself, sometimes months or years later we must be able to reevaluate the plugin once more .. so the best way for that is to require links to the plugins.
- [x] Provide information on what we define "Acceptable URLs"

Regarding "Acceptable URLs", it would be best to define some rules for them. These should be good start:
- The LOOT Team reserves the right to reject URLs to websites that contain illegal content
- Whenever possible, the url should use `https` instead of `http`
- The plugin in question mustn't be behind a paywall of any sort
- ~~No non-virtual nudity allowed (including ads running on the website we shall link to)~~
- The link should refer to an official/canonical/supported source, as opposed to just any old re-upload

**Comment by Ortham** [comment]
This all sounds good, apart from the point about nudity: it seems like a strange detail to pick on.

If the intent is to ensure that links to go pages that are safe-for-work, there's plenty of virtual nudity and other content that's not SFW. However, there are also plenty of NSFW mods, and I don't think we should refuse links to them - that'll only end up making masterlist maintenance more difficult. Labelling such links could be useful though, e.g. with a `(NSFW)` in the link text.

**Comment by pStyl3** [comment]
Labeling such links as NSFW is a good idea and for `subs`, `display` and `text` keys could be done like so:
`[Nameofthemod (NSFW)](URL)`

If we have
```yaml
  - name: 'Example.esp'
    url: [ 'https://www.example.com/' ]
```
and would like to specify the NSFW nature of the link, we can write the entry like this:
```yaml
  - name: 'Example.esp'
    url:
      - link: 'https://www.example.com/'
        name: 'Example (NFSW)'
```
There are actually two reasons why I've added that point. The first one is to simply create a clear line as to what we want to link to and what not. Nudity itself is not the probem, not to mention that multiple (if not all) of the games LOOT supports are also targeted for a mature audience. But the question is, if we *want* to link to sites that feature non-virtual nudity, or potentially even **explicit**, potentially animated, non-virtual nudity. Take a look at LL's ads without any adblockers and you see what I mean (**warning: NSFW**), though this is not only about LL. We also must think about our masterlist maintainers (female or male alike) that might get exposed to this kind of stuff, even though they potentially wouldn't access such sites normally.

The second reason is that I am quite suspicious about any site that mixes virtual and non-virtual NFSW content. In a world where, for example, so-called Deepfakes become more of a problem each day (another example would be highly detailed 3D models of RL persons), it is my opinion that we need to perform any steps possible to prevent these worlds from further mixing, especially if it's about NSFW content. And while of course we cannot stop these things from happening, obviously, we could prevent LOOT from linking to sites with such content, and even sites that haven't grasp the seriousness of their situation yet.

That being said. Stating that `The LOOT Team reserves the right to reject URLs to websites that contain illegal content` and `NSFW` warnings are a good improvement and should make it clear that we do not accept any URL just like that.

**Comment by Ortham** [comment]
>  But the question is, if we _want_ to link to sites that feature non-virtual nudity, or potentially even **explicit**, potentially animated, non-virtual nudity.

Welll, if that's the/a canonical host for the mod in question, I personally think the answer to that is yes. The links are in the masterlist for two audiences:

1. Masterlist maintainers - I think we'd rather have a NSFW link to the mod's host rather than no link at all, it makes our lives easier. Additionally, most sites hide 'adult' content behind an age 'verification' dialog and/or require you to log in and/or opt in to seeing such content, so I think the likelihood of "oh I'll just check if the mod page has any info -> aargh my eyes!" is pretty low. Labelling such links should be enough mitigation.
2. Users who have already downloaded the mod - in the vast majority of cases (where a mod only has a single official host), the user will already have gotten the mod from the NSFW site in question, so are clearly OK with visiting such sites.

---

Now that I've mentioned it, I think another bullet point should be that the link should be one that is to an official/canonical/supported source, as opposed to just any old re-upload.

**Comment by pStyl3** [comment]
Done in https://github.com/loot/loot/commit/f624d3241c0106b619b1ae5f7a7b6aba22043f5b.
