### ISSUE TITLE
 White screen error.

### ISSUE THREAD

**Issue by Jarweis** [loot/loot#1594]
When I open Loot the screen turns white and nothing is done. I deleted all the files and reinstalled but it didn't work. I reset my computer but that didn't work either. I've never had this problem with my previous installs. I'm not the only one having this problem. Many community groups have the same problem.
![image](https://user-images.githubusercontent.com/78624183/131974308-ba3b1e7b-b37f-476f-af73-cfedf4f277e9.png)

**Comment by sibir-ine** [comment]
@Jarweis https://loot.github.io/docs/help/LOOT-FAQs.html#blank-window

**Comment by Jarweis** [comment]
@sibir-ine Thanks for the help
