### ISSUE TITLE
LOOT Failure to launch in Skyrim SE & Fallout 4

### ISSUE THREAD

**Issue by Ray5868** [loot/loot#1595]
LOOT failure to Launch. Log as requested
[LOOTDebugLog.txt](https://github.com/loot/loot/files/7199864/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
LOOT seems to be detecting Skyrim SE, but the issue in the log is Git-related. Please take a look at this [section of the FAQ](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors) to resolve the issue. Keep in the mind that the `.git` folder is hidden by default, so make sure you can [see hidden folders](https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5).

**Comment by Ray5868** [comment]
Deleting the .git file fixed the problem. Thank You for your help.

**Comment by sibir-ine** [comment]
Great, you're welcome! I'll close this issue then.
