### ISSUE TITLE
White Screen & New Vegas

### ISSUE THREAD

**Issue by abysskeeper** [loot/loot#1599]
I've been trying to fix this for a few days now, I've tried pretty much every solution I could've found online but none of them worked!
Whenever I'm trying to run LOOT, either through MO2 or alone, I only get this white screen and inside the debug file it reads that it can't detect the game.
[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/7213368/LOOTDebugLog.txt)

Thanks in advance.

**Comment by Ortham** [comment]
I think this will also be fixed in the next release, as I added GOG registry entries in b567e48f73f1a3debd64a5c3f6eed0d758f1ef38.
