### ISSUE TITLE
Linux crash

### ISSUE THREAD

**Issue by alexzk1** [loot/loot#1615]
Installed LOOT 0.16 from arch repos, using this
https://github.com/loot/loot/issues/1035
figured to make config to access wine 1 hour later

> [[games]]
> 	registry = ""
> 	local_path = "/home/alex/Games/SkyrimWholeThings/PoL/Skyrim32/drive_c/users/steamuser/Local Settings/Application Data/Skyrim"
> 	path = "/home/alex/Games/Skyrim/"
> 	branch = "0.15"
> 	master = "/home/alex/Games/Skyrim/TESV.exe"
> 	folder = "/home/alex/.config/LOOT/Skyrim"
> 	repo = "https://github.com/loot/skyrim.git"
> 	minimumHeaderVersion = 0.93999999761581421
> 	name = "SkyrimLE"
> 	type = "Skyrim"
> 
> 

Those options are additional to speak about errors if manually edited (so confusing if does not match [[games]] values):
```
lastGame = "SkyrimLE"
game = "/home/alex/.config/LOOT/Skyrim"

```

Starting with debug log (couple lines):

> 
> [23:47:15.687770] [info]: LOOT Version: 0.16.1+
> [23:47:15.687796] [info]: LOOT API Version: 0.16.3+
> [23:47:15.687798] [debug]: Detecting installed games.
> [23:47:15.687804] [trace]: Checking if game "SkyrimLE" is installed.
> .....
> [23:47:15.687852] [debug]: New game is: SkyrimLE
> [23:47:15.687854] [info]: Initialising filesystem-related data for game: SkyrimLE
> [23:47:15.687862] [info]: Attempting to create a game handle with game path "/home/alex/Games/Skyrim/" and local path "/home/alex/Games/SkyrimWholeThings/PoL/Skyrim32/drive_c/users/steamuser/Local Settings/Application Data/Skyrim"
> [23:47:15.687878] [info]: Initialising load order data for game of type 1 at: /home/alex/Games/Skyrim/
> [23:47:15.687957] [debug]: Game selected is SkyrimLE
> [23:47:15.696127] [info]: Attempting to open link: http://loot/ui/index.html
> [23:47:15.696151] [trace]: Link is to LOOT page, allowing CEF's default handling.
> [23:47:15.726318] [info]: Handling request to URL: http://loot/ui/index.html
> [23:47:15.732316] [info]: Handling request to URL: http://loot/ui/css/typography.css
> [23:47:15.732479] [info]: Handling request to URL: http://loot/ui/css/style.css
> [23:47:15.732633] [info]: Handling request to URL: http://data.loot/theme.css
> [23:47:15.732646] [trace]: File /home/alex/.config/LOOT/theme.css not found, sending 404.
> [23:47:15.732741] [info]: Handling request to URL: http://loot/ui/app.bundle.js
> [23:47:15.737162] [info]: Handling request to URL: http://loot/ui/fonts/Roboto-Regular.ttf
> [23:47:15.737525] [info]: Handling request to URL: http://loot/ui/fonts/Roboto-Bold.ttf
> [23:47:15.816043] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> [23:47:15.834167] [info]: Handling request to URL: http://loot/ui/fonts/Roboto-Medium.ttf
> [23:47:16.017830] [info]: Getting LOOT's version.
> [23:47:16.017868] [info]: Getting LOOT's detected games.
> 
> ....
> [23:47:16.062203] [info]: Loading 196 plugins using 12 threads, with up to 17 plugins per thread.
> [23:47:16.062529] [trace]: Starting plugin loading.

And finally in console:

> [alex@newsuper ~]$ /opt/loot/LOOT
> /usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = plugin_crc; _Alloc = std::allocator<plugin_crc>; std::vector<_Tp, _Alloc>::reference = plugin_crc&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
> Aborted (core dumped)

Additional thanks for 250+ mb ...of what, html pages? :D and 500+ of building tools. So 3/4 of GB is spent and it is not working and confusing yet.

Frustrating of how modern software is done.

**Comment by Ortham** [comment]
The fix is included in v0.17.0, so I'm closing this.
