### ISSUE TITLE
Name of the file cannot be resolved by the system error

### ISSUE THREAD

**Issue by iwo123** [loot/loot#1635]
LOOT was working perfectly yesterday but when I try and use it now all I get is error messages. I already tried a complete uninstall and reinstall but that didn't work. How would I fix this?

[LOOTDebugLog.txt](https://github.com/loot/loot/files/7535871/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
```
[22:28:00.896212] [error]: Exception while executing query: directory_entry::status: The name of the file cannot be resolved by the system.
: "M:\Steam Games\steamapps\common\Skyrim Special Edition\Data\.gitignore"
```

It's having trouble reading your data folder, does that `.gitignore` file exist? If so, try deleting it.
