### ISSUE TITLE
Latest version doesn't recognizes Skyrim Legendary Edition.

### ISSUE THREAD

**Issue by nakano15** [loot/loot#1637]
Any other game I install, like TES Oblivion, it is able to find it installed and manage mods.
As for Skyrim Legendary Edition, it simply don't work, even though it's listed on loot, but isn't recognized at all.

**Comment by sibir-ine** [comment]
Take a look at [this section](https://loot.github.io/docs/help/LOOT-FAQs.html#game-not-detected) of the FAQ. If that doesn't resolve the issue, try deleting (& backing up) LOOT's settings file, located at `%LOCALAPPDATA%\LOOT\settings.toml`. If that still doesn't help, you can manually set Skyrim LE's install path in LOOT's settings. Just select **TES V: Skyrim** in the settings menu & enter your path in the **Install Path** field.

**Comment by nakano15** [comment]
Deletting the settings file solved the issue.
Thank you. :3
