### ISSUE TITLE
Add ability to back up LOOT data folder on first launch of new version & on demand

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1655]
To guard against bugs when updating to a new version of LOOT.

- Should this backup happen automatically, or be a prompted option?

Suggested by [sibir on Discord](https://discord.com/channels/473542112974077963/496196499890241546/921908426236375060).

**Comment by sibir-ine** [comment]
I think whether we make the backups automatic or optional depends on what we plan to backup. If we backup the entire folder, we'll probably want to make it optional as it can get fairly big due to the `.git` folders (IIRC, mine was a few gigs until I deleted & regenerated most of them, though maybe this will be less of an issue without rollbacks?). However, if we just backup the text files (which I lean towards), it probably wouldn't be very costly or intrusive to just automatically back them up on first launch & give a popup notification informing the user their LOOT data was backed up & where it is.

**Comment by Ortham** [comment]
Backing up the whole of `%LOCALAPPDATA%\LOOT` is sufficient, but not necessary - I agree that we can skip the `.git` folders because they will just be copies of Git repos, and are the largest items in LOOT's data folder.

**Comment by IllusiveMan196** [comment]
Why not both? Automatic backup on new version install and manual whenever user wants to. Backing up text files like settings, current masterlist and user load rules would be enough.

**Comment by sibir-ine** [comment]
I think the question Ortham is asking is whether when backing up at first launch, should it just do it automatically or ask the user first. I was also thinking about on-demand backups & restoration, but then I realized it's not that much simpler than just going to the LOOT appdata folder (we already have a menu option for that) & physically backing up what you need. However, if it's trivial to implement, maybe it'd still be worth it.

**Comment by Ortham** [comment]
Thinking about how this would work:

1. User clicks "Backup data" (or similar) menu option, or LOOT launches with a last version in the settings file that's not equal to the current version.
2. LOOT creates a folder for the backup at `%LOCALAPPDATA%\LOOT\backups\LOOT-backup-<ISO 8601 timestamp>`.
2. LOOT recursively iterates over the `%LOCALAPPDATA%\LOOT` directory, skipping the root `backups` folder, `.git` folders and `LOOTDebugLog.txt`. It copies each file into the destination backup folder, preserving the relative directory structure.
3. LOOT creates a zip file of the backup directory, at %LOCALAPPDATA%\LOOT\backups\LOOT-backup-<ISO 8601 timestamp>.zip`.
4. LOOT deletes the backup directory.
5. LOOT displays an informational dialog box to the user that includes the path to the new backup zip file. If backup happened because LOOT's version has changed, the backup file path should probably be included in the First Time Tips dialog instead of having two dialogs pop up.

Probably the easiest way to create the zip file is to add [minizip-ng](https://github.com/zlib-ng/minizip-ng) as a dependency. A quick manual test of the process with my own LOOT folder showed it would go from 2.61 MB to 443 KB, so zipping seems worth it.

There are a couple of other changes that would make sense along with this:

- Move all LOOT's game directories into a `games` subdirectory, so that there can't be any clashes with the other files and folders in `%LOCALAPPDATA%\LOOT`. For backwards compatibility, LOOT would have to have a migration step on startup where it loops over the games defined in its settings and moves any matching folders in `%LOCALAPPDATA%\LOOT` to `%LOCALAPPDATA%\LOOT\games`.
- Rename the "Open Debug Log Location" menu action to something like "Open LOOT data folder".

**Comment by Ortham** [comment]
This is now implemented in the `backup-data` branch, though the Linux build is failing because I need to fix some library names. @sibir-ine could you try it out and let me know what you think?

**Comment by sibir-ine** [comment]
It works perfectly! 👍 Both the manual & first-time backups back up my settings & all of my LOOT game folders sans the `.git` folders. The links in the post-backup dialogs open that backup in another window, & the backups are all stored in the `backups` folder in my LOOT data folder (which I redirected using the `--loot-data-path` argument). Subsequent backups also don't include the backups folder. The size of the backups seems reasonable too (1.16 MB archive vs. 7.1 MB without `.git` folders & 649 MB with).

The only suggestion I can come up with is maybe seeing if the icon library LOOT uses has an icon that looks like an archive for the `Backup LOOT Data` option.

**Comment by Ortham** [comment]
Done as of 522feb7bdd668f9648d065c6b208bf4445ebbb90.

**Comment by sibir-ine** [comment]
Something I just noticed with the first-time backup that's potentially undesirable: it moves the currently opened game profile to `games/` before executing the backup. Ideally, it'd execute the first-time backup before making any changes to the LOOT data folder.

**Comment by Ortham** [comment]
> Something I just noticed with the first-time backup that's potentially undesirable: it moves the currently opened game profile to `games/` before executing the backup. Ideally, it'd execute the first-time backup before making any changes to the LOOT data folder.

I've flipped the order of game init and displaying the first time tips dialog so that the latter happens first, before game init moves the directory. That's currently in the `gitless-file-update` branch.

**Comment by sibir-ine** [comment]
The backup now happens before migrating profiles 👍 However, an unintended side effect of it seems to be that the first-time dialog isn't centered on the main window.

![image](https://user-images.githubusercontent.com/69141501/150910474-1bf72e66-7a76-4cdc-89b4-a1ea108877f6.png)

**Comment by Ortham** [comment]
I can replicate that, but only when the LOOT window is maximised. It looks like the dialog gets displayed too quickly after the window is initialised so the dialog is positioning itself based on the unmaximised window position... Adding a 2 millisecond delay after opening the LOOT window is enough to get the dialog to center correctly for me.

@sibir-ine Do you see it only when maximised, or when LOOT isn't maximised too?

**Comment by Ortham** [comment]
I've pushed a workaround for that dialog positioning bug in the `better-auto-backup` branch.

**Comment by sibir-ine** [comment]
> Do you see it only when maximised, or when LOOT isn't maximised too?

Yeah, it's just when it starts maximized. I tried distorting the window as much as I could minimized, but it's always centered.

> I've pushed a workaround for that dialog positioning bug in the `better-auto-backup` branch.

Yup, the dialog is centered when maximized now 👍 Thanks!

**Comment by Ortham** [comment]
Closing this again as the new changes are now merged as of f9e4d655aa12e9824117424018c11d4736fe4ea3.
