### ISSUE TITLE
Bitdefender flagged LOOT as a Trojan

### ISSUE THREAD

**Issue by DannyBoi08** [loot/loot#1656]
I've been using LOOT for a long time now but this didn't happen until now. The latest update somehow got flagged as a Trojan by Bitdefender. Kindly fix.

**Comment by Ortham** [comment]
This tends to happen with every new release, as various antivirus systems' heuristics trip up over LOOT. I don't know if it's possible in Bitdefender, but some AVs allow you to report false positives.

**Comment by RacerBG** [comment]
> This tends to happen with every new release, as various antivirus systems' heuristics trip up over LOOT. I don't know if it's possible in Bitdefender, but some AVs allow you to report false positives.

This happens with Avast as well but it does not deserve a "bug report" at all. I will send the file to Avast for analysis though.

**Comment by DannyBoi08** [comment]
![AV](https://user-images.githubusercontent.com/96395169/146718744-071f7773-c5bd-4b19-8940-9b9c2eca8358.jpg)
This is what I get when trying to install LOOT's latest build.

**Comment by pStyl3** [comment]
@DannyBoi08 
You could report the false positive on [this](https://www.bitdefender.com/consumer/support/answer/29358/) Bitdefender website. In the meantime you could create an exception rule for LOOT.exe within Bitdender, so that you can actually use it.

**Comment by DannyBoi08** [comment]
Will do.
