### ISSUE TITLE
LOOT 0.17.0 - Exception while executing query: Git operation failed.

### ISSUE THREAD

**Issue by HylianSteel** [loot/loot#1668]
I've loaded up LOOT today to sort my mods and encountered an issue that has prevented LOOT from functioning.
I've attached the entire debug log, these are what sticks out to me:

[13:40:50.854491] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic

[13:40:51.583449] [error]: Exception while executing query: Git operation failed. Details: -1; the git_object of id '8f184403bbf3eb35bcdc76aaecf2d7a9b956e1b0' can not be successfully peeled into a tree (git_object_t=2).: libgit2 error

[LOOTDebugLog.txt](https://github.com/loot/loot/files/7841223/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
Please try the advice in the [FAQ](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors).

**Comment by HylianSteel** [comment]
Tried the FAQs advice. I think this is a server issue.

https://raw.githubusercontent.com/loot/skyrim/v0.17/masterlist.yaml is showing this for me.

Error 503 first byte timeout
first byte timeout

Guru Mediation:
Details: cache-iad-kcgs7200033-IAD 1641861981 1825558297

Varnish cache server

**Comment by sibir-ine** [comment]
Yeah, it's likely a connection issue. Has it been resolved, or are you still having issues updating your masterlist &/or accessing the file?

**Comment by HylianSteel** [comment]
I just checked the masterlist.yaml and i'm able to access it now. Vortex is also running perfectly fine again as well. Pretty odd, but at least it's fine again.
