### ISSUE TITLE
Been working fine for weeks, now fails immediately after launch.

### ISSUE THREAD

**Issue by Javic36** [loot/loot#1669]
Problem occurs on 64-bit Windows 7 SP1.

Same old story. Worked fine an hour ago. Now it doesn't work at all. As soon as I launch loot.exe, it presents an error message.

I'm using it for Oblivion. At first it reported that it couldn't find the game even though it found it fine earlier. So I set the Oblivion installation path manually via Settings, but it still said it couldn't find the game. So I reinstalled Oblivion and that got past this error. But it still fails now on launch.

Tried deleting LOOT completely (including stuff under %LOCALAPPDATA%) and reinstalling but that had no effect. Also tried rebooting; no change.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/7842389/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
Please try the advice in the FAQ for [git errors](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors).

**Comment by Javic36** [comment]
I tried all that. None of those suggestions had any effect. FWIW there is no ".git" folder under %LOCALAPPDATA%\LOOT\Oblivion\. The only file there is "masterlist.yaml".

**Comment by sibir-ine** [comment]
It's hidden by default, so make sure you have the option to view hidden files & folders selected.

**Comment by Javic36** [comment]
OK. Yep, there it is. (One mystery solved. :-) Is there anything I can look at there (or post here) that would help diagnose the problem?

**Comment by sibir-ine** [comment]
Not really, the git files just get corrupted on rare occasion & need to be manually deleted so that they can be properly regenerated.

**Comment by Javic36** [comment]
Fortunately, I had a system image from a few days ago when LOOT was working fine. I just restored that image, and now LOOT is working again. Apparently either my OS or LOOT got corrupted in some way recently, and going back in time fixed it.
