### ISSUE TITLE
Czech language produces error

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1677]
If one tries to start LOOT using Czech as set language, LOOT will produce an error and won't show any plugins in it's UI. This message is logged in LOOTDebugLog.txt:

> [23:54:15.846110] [error]: Exception while executing query in worker thread: boost::too_few_args: format-string referred to more arguments than were passed

I've reproduced this using both `v0.17.0` and `loot_0.17.0-55-gf776e07_qt5-win64.7z`, as well as `loot_0.17.0-98-g2a9f03b_gitless-file-update-win64.7z`.

**Comment by sibir-ine** [comment]
It's due to a typo in a placeholder.

https://github.com/loot/loot/blob/5048737b1a19932933281f1608bacc036ecd7e02/resources/l10n/cs/LC_MESSAGES/loot.po#L881-L886
