### ISSUE TITLE
Well Excuse me

### ISSUE THREAD

**Issue by 5uck7ou** [loot/loot#1693]
...for daring to criticize your awfully designed, unusable software, ya snide piece of S***. Have a nice life, ***hole, but I won't be talked down to like that without getting the last word in. I won't be reading another one of your snide responses.

**Comment by pStyl3** [comment]
Have a nice day.

**Comment by Ortham** [comment]
I guess this relates to #1692. At least this clarifies any uncertainty about whether or not blocking the OP is appropriate...
