### ISSUE TITLE
Please elaborate on command line option --game=<game folder name>

### ISSUE THREAD

**Issue by noabody** [loot/loot#1694]
The documentation is a bit vague on this point of "[folder name](https://loot.readthedocs.io/en/latest/app/usage/initialisation.html)" vs "path name".

Since a Folder Name is presumed to be a subset of the path, e.g. "D:\Morrowind", where ```D:\``` is the installation drive and ```Morrowind``` is the Folder Name.  This doesn't seem to be an option that helps to _find_ the game so much as to _define_ which game we're searching for.

Is there similarly a command line option to specify the exact path to the game, to _find_ it?  Such an option exists in the file ```%LOCALAPPDATA%\LOOT\settings.toml``` as ```path = ""```.

A great example of how confusing this can be is the default Steam installation folder for "Fallout New Vegas" which is literally as I've quoted it.  Yet the "Game folder name" referenced in the link above suggests I should use ```--game="FalloutNV"``` rather than ```--game="Fallout New Vegas"```.  This dismisses the notion that ```--game=<game folder name>``` should reflect the actual game folder name but, instead, the identifiers noted.

As such, a more apt description would be ```--game=<game identifier>```.  If this is indeed the case, I'd like to make a feature request to add something like ```--path=<path to game>``` as a command line option to supplement that found in "settings_toml".
```
[[games]]
	branch = "v0.17"
	folder = "Morrowind"
	repo = "https://github.com/loot/morrowind.git"
	type = "Morrowind"
	name = "TES III: Morrowind"
	local_path = ""
	path = ""
	master = "Morrowind.esm"
	minimumHeaderVersion = 1.2000000476837158
	registry = ["Software\\Bethesda Softworks\\Morrowind\\Installed Path", "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Steam App 22320\\InstallLocation", "Software\\GOG.com\\Games\\1440163901\\path", "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\1440163901_is1\\InstallLocation", "Software\\GOG.com\\Games\\1435828767\\path", "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\1435828767_is1\\InstallLocation"]
```
Specifically, I'm using Loot as a tool for ModOrganizer2 with Steam Proton on Linux.  I cannot use command ```--game="D:\Morrowind"``` to allow Loot to find the game.  Instead I have to create a registry entry that conforms to https://github.com/loot/loot/commit/b567e48f73f1a3debd64a5c3f6eed0d758f1ef38, manually add a game that adds a ```path = "D:\\Morrowind"``` entry to "settings_toml", or directly amend that file for the game heading and ```path = "D:\\Morrowind"```.

**Comment by Ortham** [comment]
The "game folder name" (`folder` in `settings.toml`) is used in a few ways:

* It uniquely identifies the game within LOOT.
* The default value for each game type is used as that game type's serialised value (the `type` setting in `settings.toml`).
* As it's a unique identifier, it's used as the name of the game's directory within LOOT's app data folder (`%LOCALAPPDATA%\LOOT` on Windows, `$XDG_CONFIG_HOME/LOOT` or `$HOME/.config/LOOT` when running natively on Linux) - in the latest snapshot builds these game directories have moved into a `games` subdirectory.
* Interestingly, when checking this I noticed that it's also used by `Game::PluginsTxtPath()`, which is used to provide a path in a sorting error message, and doesn't respect `local_path` or `local_folder`... That's a bug, I'll fix that.

So you're correct that "game identifier" would be a better description.

If set, `local_path` is used to override libloadorder's derivation of the path to the game's directory in `%LOCALAPPDATA%` (on Windows) (i.e. the folder that contains `plugins.txt`). `local_folder` is similar, but names a folder inside `%LOCALAPPDATA%` (on Windows) or `$XDG_CONFIG_HOME` or `$HOME/.config` (when running natively on Linux).

None of those relate to where the game was installed to though: you're right that setting `path` in `settings.toml` is one way to provide that. If you specify `path`, do you find that you also need to specify `local_path`? I.e. would you need `--game-local-path=<path to game local directory>` as well as `--game-path=<game install path>`?

I'm surprised that you have to manually create one of the registry entries that LOOT searches for though, do they not get created by Steam or the game's launcher when it runs under Proton?

**Comment by noabody** [comment]
Thank you for the very detailed reply.  I only need to specify ```path = ""``` i.e. ```path = "D:\\Morrowind"```.  

I have developed a method to run Nirsoft RegScanner.exe ([wstart](https://noabody.wordpress.com/2021/10/04/wstart)) within the Steam Proton Wine prefix for Morrowind, Oblivion, Fallout New Vegas and Skyrim Special Edition.  There is no match on a search for Morrowind.  These are the search results for the others (which LOOT has no problem detecting):
```
HKLM\Software\Wow6432Node\Bethesda Softworks\Skyrim Special Edition
HKLM\Software\Wow6432Node\bethesda softworks\falloutnv
HKLM\Software\Wow6432Node\Bethesda Softworks\Oblivion
```
My understanding is that the Game Launcher, itself, may populate the registry entries on those that have a match.  I'm not at all certain Steam pushes that information when the game prefix is created.  A registry import such as this "loot.reg" solves my issue for Morrowind:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Bethesda Softworks\Morrowind]
"Installed Path"="D:\\Morrowind"
```
This is clearly an _edge_ case related to Steam Proton.  Unfortunately, manipulating Steam Proton prefixes is not a trivial task.  Simple things like running Windows Explorer or the Registry Editor are difficult.

It would be much easier to have a command line option.

**Comment by sibir-ine** [comment]
LOOT only uses your registry to automatically find your games; it isn't necessary to use LOOT. If you manually set the `path` field (_Install Path_ in the settings dialog) to your Morrowind installation, you don't need to worry about editing your registry. Does manually setting the path not work for you? If not, as Ortham said, try setting the `local_path` field (_Local Data Path_ in the settings dialog in v0.17.0, _Local AppData Path_ in the latest source code) to the same path for Morrowind since, as you said, `Morrowind.ini` stores your active plugins list. If you've already set it to something, try leaving it blank as well. Also, make sure this is in the game profile for Morrowind (i.e., `folder = "Morrowind"`, _LOOT Folder_ in the settings dialog).

As for a command line switch for defining your game's install path, if defining the path in your settings isn't working, that won't help. However, I suppose it could be beneficial for people with multiple installations.

**Comment by sibir-ine** [comment]
Also of note: a game path switch was originally requested in #1049.

**Comment by Ortham** [comment]
> Morrowind doesn't employ `%LOCALAPPDATA%\Morrowind\plugins.txt`. Its settings appear to be contained in the game folder within "Morrowind.ini"

Yep, Morrowind's a special case so now that I think about it setting `local_path` or `local_folder` wouldn't do anything.

I've added `--game-path` in the `game-path-cli-parameter` branch, please try the snapshot build [here](https://loot.jfrog.io/ui/native/loot/game-path-cli-parameter/) and let me know if it works as you expect or not.

**Comment by noabody** [comment]
The build you specified works perfectly. :)

My MO2 command line is ```--game-path="D:\Morrowind" --game="Morrowind" --loot-data-path="D:\mwmo2\mwloot"```.  The game is detected and "settings.toml" automagically picks up the ```path = "D:\\Morrowind"```.  

Personally, I keep LOOT installed outside of ModOrganizer2 but prefer to have it save its settings within my portable MO2 profile since it is easier to manipulate than having it within the Proton prefix path.

Thank you so much!

**Comment by Ortham** [comment]
No problem, closing this as it's done in 70aca1de970adab68bc786ba1d6b326fa00daf13.
