### ISSUE TITLE
Use bigger font size for plugin names in plugin cards

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1695]
With snapshot `loot_0.17.0-158-ge0565f1_locations-display-win64.7z` the UI currently looks like this:
![grafik](https://user-images.githubusercontent.com/10406657/154818180-0fa9ca70-be0d-48f7-90b4-c73bad1cfebc.png)

I think it could be beneficial if we would use a slightly bigger font size for the plugin names (e.g. `RaceMenu.esp`) in the plugin cards (LOOTs right pane). As of now they sort of lack something that is highlighting them, with the result, that it's harder to spot the plugin name in each plugin card.

As a reference, here's what it looks like in v0.17.0:
![grafik](https://user-images.githubusercontent.com/10406657/154818482-8d07b010-e46f-42df-aa7d-92513581e7dd.png)

**Comment by Ortham** [comment]
Here's a screenshot with the same 1.143 multiplier as used by the v0.17.0 UI:

![image](https://user-images.githubusercontent.com/2430738/154838903-708b75f6-6356-4c7e-8688-11f65a32ae67.png)

**Comment by pStyl3** [comment]
That looks better, and it should help when looking over the different plugin cards to find a specific plugin.

**Comment by Ortham** [comment]
OK, I've adde the change to the `game-path-cli-parameter` branch, can you give it a go to see what you think of using it?

**Comment by pStyl3** [comment]
Tested it and I still like it. When scrolling up & down the plugin cards, it is now easier to concentrate on the (now bigger) plugin names. 👍

**Comment by Ortham** [comment]
OK, done in c1d38e0e3d6b751d94ebe1babaf77ba99b25f06e.
