### ISSUE TITLE
Add header for different columns in sidebar

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1696]
Since https://github.com/loot/loot/issues/1189 we now have more than one column in the sidebar, that displays an index / a number - plus the one column for the plugin names.

Current UI:
![grafik](https://user-images.githubusercontent.com/10406657/154853653-7c6e13ab-3607-4432-a65b-7a189c5bafc9.png)

It would be great if we could add a header for these columns, so that it's easier to communicate their meaning.

Here are a few possibilities:
1. Decimal Index | Hexadecimal Index | Light Index | Plugin Name
    This variant would entail splitting up the column for the Hex Index and the Light Index into two seperate columns.
    Writing these headers out might very likely waste to much horizontal space, so abbreviations might help here:

    DI | HI | LI | Plugin Name
    If these abbreviations would be used, perhabs we also could add tool-tips to reveal their full name.

2. Number | Index | Light Index | Filename
    This variant would also entail utilising 4 columns instead of 3.

3. @sibir-ine made the following suggestion on Discord (which I also like):
    LO | MI | Plugin Name
    with LO = Load Order and MI = Mod Index

**Comment by Ortham** [comment]
I don't think having abbreviations or initialisms as header text is all that useful - the purpose of the header text is to communicate meaning, and if you don't already know what `LO` or `MI` stand for they're not really obvious, and if you do know then the header text isn't necessary.

Unfortunately, using more meaningful header text also means sacrificing horizontal space:

![image](https://user-images.githubusercontent.com/2430738/155025411-fd5c399b-c118-431f-88e7-178df2ffd775.png)

"Order" is not really correct, "Position" is better but uses more space:

![image](https://user-images.githubusercontent.com/2430738/155025446-8912af8e-4380-413b-a4ef-f16a592f03dc.png)

**Comment by pStyl3** [comment]
"Position" is indeed better than "Order", as such I would prefer the variant depicted in the 2nd image (including writing "Plugin Name" instead of "Name"). The increased horizontal space is around ~5mm, so considering the options not to bad.

We *could* center the numbers in the Position and Index columns, so that the white space between the columns doesn't feel as wide, here's a mockup I've just created:
![test](https://user-images.githubusercontent.com/10406657/155028354-e90bc608-4617-48ba-b8a8-39db699486fb.png)

That being said, I don't really mind if it's left aligned or centered.

**Comment by Ortham** [comment]
I prefer left-aligned text, so I've kept it like that, but I've implemented option 2 otherwise. I've also made the first two columns resizable so you can get rid of the extra horizontal space introduced by "Position" if you want. This is available in the `sidebar-column-headers` branch if you want to try it out.

**Comment by pStyl3** [comment]
Looks good to me, and the ability to resize the columns is great.

**Comment by Ortham** [comment]
Done and merged in aff442dc93afa1a5d3b66ec6d5b12eaa830ee5ce.
