### ISSUE TITLE
Limit the width of the left-hand list in the settings dialog

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1700]
Requested by pStyl3. As the width of the settings dialog is increased, the list width scales with it, which is pretty quickly pointless.

**Comment by Ortham** [comment]
@pStyl3 I've made a change in the `fixed-settings-sidebar` branch, please let me know what you think of it.

**Comment by pStyl3** [comment]
Looks great! Thanks. 👍

**Comment by Ortham** [comment]
Done in c915f72adf09804eea343018daeb82a4bae47403.
