### ISSUE TITLE
Save node positions in groups editor

### ISSUE THREAD

**Issue by NukelordPvP** [loot/loot#1708]
Add an option to disable the auto formatting of the Groups tree after saving. I have some really long chains and its making it hard to read with auto formatting on.
![automatic](https://user-images.githubusercontent.com/63741267/157740423-cb5a5eff-c17c-4620-b70b-4bad2796fe2d.PNG)
after manual formatting
![manual formatting](https://user-images.githubusercontent.com/63741267/157740723-cbf1389d-c1b7-4821-836e-225c1694e1c4.PNG)
zoomed out
![zoomed out](https://user-images.githubusercontent.com/63741267/157740527-46aba72c-d9f4-43a4-8937-94cb46992140.PNG)

**Comment by Ortham** [comment]
Can you upload your `userlist.yaml`? (File -> Open LOOT Data Folder, then the file is at `games/<game>/userlist.yaml`)

The layout isn't saved, it's recalculated each time the graph is populated. Saving the layout would bring its own problems (e.g. what happens if you open the groups editor and there are groups with no saved positions, how do you lay them out, especially if there are groups that do have saved positions?), so I'm more inclined to try to improve the layout algorithm., which is currently very simplistic.

**Comment by NukelordPvP** [comment]
[userlist.zip](https://github.com/loot/loot/files/8227661/userlist.zip)
for long chains instead of trying to go down and then connect via a super long line couldn't you make it go horizontally
![zoomed out2](https://user-images.githubusercontent.com/63741267/157769125-3acb34d8-474f-476d-b5ab-94d53a68c532.png)

**Comment by Ortham** [comment]
@NukelordPvP Can you try [this snapshot build](https://loot.jfrog.io/artifactory/loot/master/loot_0.18.2-17-g431589f_master-win64.7z) out? It improves the layout of the groups graph - is it good enough for you (without saving node positions)?

**Comment by NukelordPvP** [comment]
![111](https://user-images.githubusercontent.com/63741267/164306072-17ded4e8-3e70-4da4-84c9-7e6abd82abe4.PNG)
It's better but only issue I see now is really long chains wouldn't it be better to coil them in empty space then connect to the end node so the main node chain doesn't become extremely long.

**Comment by Ortham** [comment]
Yes and no: it would be a more efficient use of the space, but even in the ideal case of a single linear sequence of groups it's not as obvious to read (the arrows in the current layout will usually all point to the right). When you've got more complex relationships between groups I think it would also get a lot more complicated to arrange everything clearly (if it's possible at all).

Most of all, graph layout is already complicated enough that I pulled in a library to avoid having to implement the new layout algorithm myself. I could have implemented it - the algorithm LOOT now uses is well-known, is described in a CS paper, and has multiple implementations - but it would have been a lot more effort for relatively little gain. I really don't want to go to the trouble of inventing and then implementing my own more complicated algorithm, just so LOOT can have a groups editor that looks better in some cases.

**Comment by Ortham** [comment]
Node positions are now saved and saved positions used as of ec57678be1169ab983aecb4ed0456c579a7b2114. Saved positions are ignored if there is any group that does not have a saved position, so group changes in the masterlist will effectively reset node positioning.
