### ISSUE TITLE
Reintroduce search button in toolbar

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1709]
This has been a surprisingly common complaint with the new v0.18.0 release - I removed it because I didn't think it was significant enough of an action to sit alongside selecting the game, sorting and updating the masterlist, but apparently people are finding it difficult to discover how to search in the new UI. It's hard to tell how much of this is existing users having to re-learn the UI and how much of it is a usability regression that would also affect new users, but given the frequency of the complaint it's probably worth making the update easier for existing users to adjust to.

See #1706 and the following comments on Discord:

- https://discord.com/channels/473542112974077963/473721823071043585/950871456353497178
- https://discord.com/channels/473542112974077963/496196499890241546/951235266713104434
- https://discord.com/channels/473542112974077963/496196499890241546/951591369208655932
- https://discord.com/channels/473542112974077963/473721823071043585/950867953262419988

**Comment by Ortham** [comment]
This is done in the `ui-enhancements` branch.

**Comment by pStyl3** [comment]
The new button next to the `Update Masterlist` button works as intended.

Though I'll have a semi-related question. When searching with enabled `Use regular expression` and an empty textfield, is it normal that LOOT finds x from x results (e.g. 54/54)? In any case, closing the search window with enabled regular expressions doesn't clear the search and as such, plugin cards will continue to be highlighted.

**Comment by Ortham** [comment]
> Though I'll have a semi-related question.

That's a bug, there's a check to ignore empty strings but not empty regexes.

**Comment by Ortham** [comment]
That bug should now be fixed.

**Comment by Ortham** [comment]
Done in a60929ccbfbea60cceb04eb84688837b2c0d98f9 and 60bb4303091bfaa4fa30f9c5b964396fd7931d4d.
