### ISSUE TITLE
Add plugin-specific actions to right-click context menu on plugin cards

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1710]
Suggested by Skinjack [on Discord](https://discord.com/channels/473542112974077963/473721823071043585/951595234977001472).

This would be in addition to the actions in the Plugin menu bar menu. I'm not sure how or if this affects the virtual list item rendering.

**Comment by Ortham** [comment]
This is done in the `ui-enhancements` branch. Right-clicking on a plugin card or a sidebar item selects that plugin in the sidebar (right-clicking in the sidebar table already did this) and opens the Plugin menu as a context menu under at cursor's position.

**Comment by pStyl3** [comment]
Works great, there's only a small issue. If you open the plugin editor through LOOTs right pane, while the plugin in question isn't visible (scrolled out of view), the `Editor Is Open` icon will not be displayed for the plugin. The icon will only get displayed, once the plugin is clicked on in the sidebar.

**Comment by Ortham** [comment]
Done in fff99e5683fef5643fa2e52705a93df14270cfd7.

> Works great, there's only a small issue. If you open the plugin editor through LOOTs right pane, while the plugin in question isn't visible in the sidebar (scrolled out of view), the `Editor Is Open` icon will not be displayed for the plugin. The icon will only get displayed, once the plugin is clicked on in the sidebar.

I can't replicate this, right-clicking a card in the right pane scrolls the list in the sidebar to that plugin, and the editor is open icon gets displayed when I open the editor. If after right-clicking a card I scroll the sidebar so the plugin is out of view and then right-click again it won't scroll to the plugin in the sidebar because the plugin is already selected there, but if I open the editor and then manually scroll to the plugin, it will have the editor is open icon displayed. It also works as expected if I have the Filters panel open when I right-click a plugin card and open the editor, then switch back to the Plugins panel.
