### ISSUE TITLE
Try adding horizontal padding to the main window

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1711]
Suggested by hrjw89 [on Discord](https://discord.com/channels/473542112974077963/496196499890241546/951596401895305236). A small amount of padding may look better.

**Comment by Ortham** [comment]
This is done in the `ui-enhancements` branch.

**Comment by pStyl3** [comment]
To quote hrjw89:
> Better, definitely. Thank you.

**Comment by Ortham** [comment]
Done in 4879847a2ad8627fa7b670ac2df22ac05528a4a3.
