### ISSUE TITLE
User metadata flag not applied consistently

### ISSUE THREAD

**Issue by Prepubescent-Blastoise** [loot/loot#1716]
When a loadafter rule is applied to  plugin, the user metadata symbol is attached to the Load After tab of the metadata rules. If the group is changed from default though, a symbol is not applied to the Groups tab. If only the group is changed, the symbol does appear correctly in the left pane, but once you open metadata, you cannot tell what has been changed. This appears to be the only tab affected.

**Comment by Ortham** [comment]
This is now fixed in the `ui-enhancements` branch.

**Comment by Ortham** [comment]
Done in d834b0e40a015ec7e0028be4e026cafe9c891ac0.
