### ISSUE TITLE
No message telling user sort order didn't change

### ISSUE THREAD

**Issue by Glanzer-modder** [loot/loot#1724]
Version 0.18.1 provides no informative message to the user when sorting made no changes to the sort order. It just ends and brings you back to the interface.

**Comment by pStyl3** [comment]
This information get's displayed in the status bar in the bottom left corner.

![grafik](https://user-images.githubusercontent.com/10406657/158489787-1c28b6da-b0f6-4a19-902a-249444ee0d98.png)

**Comment by pStyl3** [comment]
And in case LOOT made changes to the load order you are then presented with the option to `Apply` or `Discard` these changes (next to the game selection dropdown).

![grafik](https://user-images.githubusercontent.com/10406657/158490118-e2ba7f6f-1d2d-4fc0-8e6f-59c30c6efc5c.png)

**Comment by Glanzer-modder** [comment]
Ok, then I guess I didn't look hard enough. It's a lot more subtle than previous versions!
