### ISSUE TITLE
Using Enter to Add a new group closes the Groups Editor

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1727]
![grafik](https://user-images.githubusercontent.com/10406657/158885469-2fd29398-6807-4995-b66f-b49cddd8a474.png)
Clicking on `Save` will add the group like it should.

![grafik](https://user-images.githubusercontent.com/10406657/158885567-69bd5d61-bc84-4087-8e59-0af111b2d6a5.png)

However, if you try to use the `Enter` button to add `Test`, it will close the Groups Editor instead of adding the group.

Discovered by @DarkladyLexy

**Comment by Ortham** [comment]
Fixed in 0464ec6020661bebf563f4e42c7af6b534218b0c.
