### ISSUE TITLE
Groups Editor enhancements: resize buttons and landscape display

### ISSUE THREAD

**Issue by Prepubescent-Blastoise** [loot/loot#1731]
The Groups Editor screen does not have minimize or maximize buttons, and defaults to a narrow perspective making navigation challenging. You can manually resize, but when you close the window, the next time you reopen it it returns to the default size.

Also, it would be great to either return to landscape display of loot groups, or have an option to display them that way since monitors are primarily landscape oriented. Since the switch to vertical there is lots of unused space that requires scrolling up and down as opposed to seeing all groups at once.

**Comment by Ortham** [comment]
Maximise/minimise buttons were added in d60c6d6cd61f17936b6c07900127fb1712b992de, and the groups graph has a landscape orientation as of a2cad21e6a7b0a826d5db7f941f6ebc24ccbd1fb, so I'm closing this.

**Comment by pStyl3** [comment]
Is there are snapshot build in which the Maximise/minimise buttons are already usable? I'm not seeing them in `loot_0.18.2-17-g431589f_master-win64.7z`.

**Comment by Ortham** [comment]
I see them:

![image](https://user-images.githubusercontent.com/2430738/164769525-2c8a1257-435d-49ea-9657-ea9677e72f5f.png)

**Comment by pStyl3** [comment]
Sorry, I'm not getting it. Even after 5 minutes of switching forth and back between LOOT itself and your screenshot (and adjusting monitor settings just in case) .. I don't see it.

**Comment by pStyl3** [comment]
Alright, now I know where the confusion stems from. You mean these ones:
![grafik](https://user-images.githubusercontent.com/10406657/164776679-01f3ab0d-eac2-4d72-a4fc-a15a0a1dbac3.png)

I thought, that the goal here was the add buttons that would change the zoom in the area where the groups are getting displayed, so to get from this
![grafik](https://user-images.githubusercontent.com/10406657/164776985-bf32eae7-707b-4c71-bfb5-ec3a8f609bcb.png)

to this
![grafik](https://user-images.githubusercontent.com/10406657/164777019-7b076a05-4d98-4981-b86e-e1ce39fabfb7.png).
