### ISSUE TITLE
LOOT won't detect additional mods added to New Vegas

### ISSUE THREAD

**Issue by Weatherbee9** [loot/loot#1734]
Ran LOOT 18.2 after installing New Vegas and adding mods to total 16 plugins. LOOT continues to only list 16 plugins; yet I have 29 plugins in total. Deleted the LOOT folder from Appdata and reinstalled LOOT 4x.

Is there a way to force LOOT to rescan for games and would this help? New Vegas is the only game installed. 

If you have any suggestions to solve this problem, please let me know.

Thank you in advance for your help.

**Comment by Ortham** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by sibir-ine** [comment]
They posted their debug log in https://github.com/loot/loot/issues/1735#issue-1185697491.

@Weatherbee9, you said your install path for FNV is `C:\!GAMES\STEAM\steamapps\common\Fallout New Vegas\`, but your registry still points to `G:\SteamLibrary\steamapps\common\Fallout New Vegas\` & LOOT is finding a valid installation there. Make sure that you've properly [moved](https://help.steampowered.com/en/faqs/view/4BD4-4528-6B2E-8327#move) your installation & haven't left anything behind, then run FNV's launcher at least once through Steam.

**Comment by Weatherbee9** [comment]
Thank you so much for your help. Really thought STEAM had moved that game. I deleted FNV from :G and LOOT worked.
Sorry to have bothered you. Your help was great.
