### ISSUE TITLE
Add plugin type filter

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/loot#1746]
Suggestion to add filter showing only certain mod types like eslified esp for example. Would be really useful to quickly check what is and isn't eslified or esmified in the case of esp plugins, same for other flag combinations perhaps.

**Comment by Ortham** [comment]
I've got some questions that lead into each other:

- What plugin types would you like covered? 
- Are any of the types you want covered mutually exclusive, or do they overlap at all?
- Would this be a single filter with e.g. a dropdown to select which plugin type to show (this may be best if all types are mutually exclusive), or as a set of independent filters?

**Comment by IllusiveMan196** [comment]
Ideally all of them. This would probably need multiple additive filters, but gives better control over what is filtered out. There are only 6 possible combination with 3 filters overlapping each other.
This would work fine as multiple-choice checkmark thing for esl, esm flags and regular esp.

ESL overlapping with error filter would aslo serve to show incorrectly eslified plugins (think over valid record range).

**Comment by Ortham** [comment]
Coming back to this, I'm not really sure about what's wanted, as plugin behaviour isn't just about what flags are set, file extensions can also matter, so you've got 12 possible combinations:

| | *.esp | *.esm | *.esl
|---|-|-|-|
| Unflagged |
| Light flagged |
| Master flagged |
| Light + master flagged |

Which of these matter?

Also, it seems like this could significantly expand LOOT's set of filters, so I'd like to see some justification for why this functionality is something that LOOT should provide as opposed to a more general mod manager, i.e. how does this interact with and enhance LOOT's existing features?

**Comment by IllusiveMan196** [comment]
Shouldn't .esl force both light and master plugin flags?If so, then we have
just esp, esp(master), esp(light master), esp(light), esm, esm(light), esl.

Idea behind this quickly typed request was to use LOOT as a filtering tool
for already eslified plugins (forgot why exactly, but I was remaking my mod
setup and had an awful lot of plugins to sift through and mark or group
appropriately right at that time). Maybe I wanted LOOT to do that in case
something happened to mod manager program?

Probably can be closed, if I'll remember why I wanted that included in LOOT
(besides soft replacement for mod managers or filtering tool to quickly
list plugins of each type and check if flag was actually applied correctly
or at all) I'll reopen this thread.

**Comment by Ortham** [comment]
> Shouldn't .esl force both light and master plugin flags?

Yes, in game it will behave as those flags were set, but I wasn't sure if you wanted to lump them together like that - you could be using the filters to see what's actually flagged in case you want to change the file extension.

As it is, I'll close this because I'm not sure LOOT's the right place for this functionality.
