### ISSUE TITLE
Suggestion: Published masterlist md5s

### ISSUE THREAD

**Issue by Silarn** [loot/loot#1749]
Right now, when doing a masterlist update, you download the masterlist and then run an md5 comparison. The only thing this really accomplishes is telling you that the file you downloaded already is a new version. It doesn't avoid the initial download.

If we can parse a published md5 hash of the masterlist, we can run this check first and then download the updated full masterlist file once we confirm the md5 is different.

**Comment by Ortham** [comment]
Nitpick: it's not an MD5 of a file, it's a SHA1 of the Git blob.

Based on the profiling I did in #1490, I don't think it's worth trying to avoid downloading the masterlist, it's much less than 200 kB for even the largest masterlist, which should take a fraction of a second on most Internet connections and is not a significant amount of data for most people (a Google search results page is about 4 times larger).

Checking published hashes means we'd need to publish those hashes somewhere, which means having the infrastructure host the published hashes, and extending the CI jobs to do the publishing. The masterlist source URL can be any URL, and adding hash checking would mean that anyone else wanting to have their own copy of the masterlist (which could be useful when testing changes in a fork before submitting a PR, for example) would need to have similar infrastructure. On top of that, the source URL can point to a fixed version of a masterlist (e.g. a specific commit) or a moving target (e.g. the head of a Git branch), so you'd need to publish hashes for all available versions of a masterlist to not break using any of them as a source: that's over 3000 commits (and so 3000 hashes) for the Skyrim SE masterlist alone.

You could sidestep that complexity by using GitHub's APIs to get the hash, but then that ties LOOT to GitHub for masterlist updates (it's tied to GitHub for application update checks, but for various reasons that lock-in is less of an issue), and means that masterlist updates are then subject to GitHub's API rate limits, which are low enough for unauthenticated requests that they can get in the way.

**Comment by Silarn** [comment]
I guess I just don't see the point of running the comparison, aside from informing users that it was updated, which I suppose is valid. Since we've never displayed this in MO2 I'd probably just validate that it's a functional masterlist and assume what I've downloaded is the newest version.

**Comment by Ortham** [comment]
Yes, it's to inform of changes to the local copy, and also to detect edits to the local copy since the last time the masterlist was updated (which is useful for maintainers making quick edits to their local copy).

> Since we've never displayed this in MO2 I'd probably just validate that it's a functional masterlist and assume what I've downloaded is the newest version.

I think that's reasonable.

**Comment by Ortham** [comment]
Closing this as wontfix for the reasons given above.
