### ISSUE TITLE
Add more hotkeys to interface

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1760]
For the metadata editor, @IllusiveMan196 suggested using the Enter key as a hotkey for the Save button. We could also add the Escape key as a hotkey for Cancel, maybe with a confirmation dialog if there are unsaved changes just in case a user accidentally presses the Escape key.

For the menu bar, [GalmarisP](https://forums.nexusmods.com/index.php?showtopic=5002060/#entry112386833) requested adding hotkeys utilizing the Alt key for all the of the menus, e.g., Alt + F for File, Alt + G for Game.

**Comment by Ortham** [comment]
I don't think Enter/Esc for the metadata editor is appropriate, as it's not a dialog, it's just part of the main LOOT window, and the editor doesn't necessarily have focus when pressing those keys.

The Alt hotkeys for the menus are a good idea though.

**Comment by Ortham** [comment]
I've added Alt keyboard shortcuts to all the menus and their actions in the `misc` branch.

**Comment by sibir-ine** [comment]
The shortcuts work well 👍 However, one concern I have is with translations of these items. Are translators able to use the same `&` syntax to specify what character in their language can be combined with Alt to produce a shortcut? If so, we should note that in the readme for contributing translations. If not, & there doesn't appear to be a suitable workaround, we should probably make note of that somewhere to avoid confusion (we should also note the existence of these shortcuts in the docs).

Another thing I noticed while testing this is that the _Search Cards_ toolbar button doesn't appear to get translated even though that string exists in the template, though the dialog window title does.

**Comment by IllusiveMan196** [comment]
Re: about translations. Many keyboards have dual character rows when/where
appropriate, some have English only. Double key designation should not
be an issue, unless it's some very specific writing system. Tooltip
construction is mostly the same anyway more or less (I choose shortest
fully understandable form, this usually involves switching words around).
Alt+something is usually written as Alt+something in manuals, localized
tooltips, coursebooks, notes, anywhere and everywhere.

**Comment by Ortham** [comment]
Good catch with the translations - the ampersand is syntax for creating a mnemonic (which is what those Alt + character shortcuts are called) on the next character, but it does interfere with the translatable text. That's probably a good thing, as "&File" having the mnemonic F makes sense, but if there's no F in the translation then it doesn't make sense for the mnemonic to still be F. I'll update the translation docs to mention this - we don't currently have any ampersands in translatable text, which means translators don't need to guess if it's a mnemonic or a literal ampersand.

> Another thing I noticed while testing this is that the _Search Cards_ toolbar button doesn't appear to get translated even though that string exists in the template, though the dialog window title does.

I think this is because there's two different strings: "Search Cards" and "Search cards".

**Comment by sibir-ine** [comment]
> I think this is because there's two different strings: "Search Cards" and "Search cards".

If you test with, e.g., Bulgarian, it has translations for both varieties of the string, & their translations both show up as expected in the window title & text field, respectively. However, the toolbar button remains untranslated.

**Comment by Ortham** [comment]
Oh, it looks like that's because that button is the same action as the Search Cards... menu item, it's used for both. So the addition of the ampersand is making that not get translated either.

I've updated the translation guide, the changes are now in the `alt-shortcuts` branch.

**Comment by sibir-ine** [comment]
Ah, that makes sense looking at the source code, I was just thrown off by the fact that the ellipsis is truncated in the button. Translating that string does in fact translate the button too, & the guide changes look good to me 👍

**Comment by Ortham** [comment]
OK, done in 27b4d36dde58c93a9e8327484f6641a676b70934.
