### ISSUE TITLE
Using unconnected groups for mod management

### ISSUE THREAD

**Issue by IllusiveMan196** [loot/loot#1761]
Idea about mod groups: toggle to let LOOT sort unconnected groups of mods wherever it thinks would be best. Example of intended use case: 5-15 small fixes / content restoration / bsa loader mods with no real conflict with other mods and between themselves.
Lets say "lore and continuity" series from Nexus or Enhanced Vanilla Experience mods, Quest Award Perk Points patches, various non-interfering empty bsa-loader plugins.

In other words - better and somewhat easier way to manage multiple similar mods using LOOT groups, while having QoL improvement of not having to deal with figuring exact load order for them.

P.S. On this note such groups would also benefir from having "load before" or "load after" text input fields to speed up group load chain building. Perhaps use it as one-parameter field to specify plugin to load before (like I want all my retextures to load before Bashed Patch or Atlas Map Markers but exact place doesn't matter. Now LOOT would just chuck empty plugins wherever, even after dynamic patches, Bashed Patch, DynDOLOD and the like, which is not that good obviously).

**Comment by Ortham** [comment]
> Idea about mod groups: toggle to let LOOT sort unconnected groups of mods wherever it thinks would be best. Example of intended use case: 5-15 small fixes / content restoration / bsa loader mods with no real conflict with other mods and between themselves.

It should already do this, though there's other data and metadata that's taken into account when sorting the plugins in those unconnected groups.

**Comment by Ortham** [comment]
Closing this - it's not invalid but I think it's asking for something that already exists.
