### ISSUE TITLE
.exe installers can break game installations on Linux

### ISSUE THREAD

**Issue by JohannesGaessler** [loot/loot#1763]
I am using Linux with Steam Proton/WINE to run Mod Oranizer 2 for Skyrim Special Edition.
I downloaded the LOOT .exe installer for 64 bit Windows and installed it to the WINE prefix for Skyrim SE.
Afterwards my game installation was broken.
I assume this is because the LOOT .exe installer installed the incorrect version of the MSVC 2019 redistributable to my WINE prefix (64 bit MSVC to 32 bit WINE prefix).
The 32 bit .7z LOOT archive worked for me.
The 64 bit .7z LOOT archive did not.

I suggest the following two changes to LOOT release texts:

* Recommend Linux users use the .7z archives since the incorrect .exe installer can break WINE prefixes, and therefore an entire game installation.
* Mention that Linux users need the 32 bit or 64 bit version depending on their WINE prefix.

**Comment by Ortham** [comment]
I don't intend to do anything about this, I think it's reasonable to expect Linux users to know if they need the 32 or 64 bit version, same as Windows users. I'm surprised that installing the wrong build will break things in that Wine prefix more generally, but I don't know enough about Wine to comment further.
