### ISSUE TITLE
Move snapshot builds from JFrog Artifactory

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1766]
Artifactory has a bug where it redirects users to a login page that's actually a modal dialog with an almost-invisible close button, even if the repository is configured to allow anonymous access, and trying to close the dialog displays a flash of the UI you're trying to get to before the dialog is opened again. In the past I've been able to get around this by using a private browsing window but that doesn't seem to work any more.

Given that almost the whole point we use Artifactory is to allow anonymous access to our build artifacts, this issue is quite debilitating, so it looks like we need to migrate away from Artifactory. Our options depend on how much data we're storing, so here's a summary of that.

Artifactory says that we're currently storing a total of 17 artifacts, taking up 156.26 MB of space. Broken down by repository, that's:

| Repository | Size / MB | Files | Folders (i.e. branches)
|------------|-----------|------|----------------------
| loot | 109.22 | 8 | 2
| libloot | 21.80 | 3 | 1
| libloot-python | 8.57 | 2 | 1
| metadata-validator | 5.46 | 2 | 1

I'd like to be able to publish 10 branches at a time, which would be 930 MB.

Our current individual artifact sizes are:

| Repository | Artifact type | Size / MB
|------------|--------------|----------
| loot | win32 archive | 12.4
| loot | win64 archive | 13.1
| loot | win32 installer | 14.3
| loot | win64 archive | 14.8
| libloot | win32 | 7.5
| libloot | win64 | 7.7
| libloot | linux | 6.6
| libloot-python | python 3.7 win32 | 4.0
| libloot-python | python 3.7 win64 | 4.6
| metadata-validator | win32 | 1.6
| metadata-validator | linux | 3.9

Our CI jobs run a cleanup script that removes all artifacts for branches that no longer exist, and also removes all previous artifacts for the current branch, so we only store the artifacts for the latest release of every existing branch. That's less than what we used to store before moving to artifactory, but it hasn't gotten in the way so I'm inclined to keep that pruning in place.

My JFrog account page shows storage high water marks and data transfer amounts:

![image](https://user-images.githubusercontent.com/2430738/177008017-f5a41b24-c88a-4936-8b07-be29cf4c9fc5.png)

LOOT v0.18.0's changes meant a large reduction in artifact size and also meant that Dependabot would no longer open 10 PRs per month. It was released on the 8th of March, which is why there's such a big drop to and after March. Development did also slow down after that, which means fewer branches being opened and fewer snapshots being downloaded, but as I tend to only actively work on one or two branches at a time I think the impact of that is relatively insignificant.

**Comment by Ortham** [comment]
With very little development happening in June and July, my JFrog account graphs now look like this:

![image](https://user-images.githubusercontent.com/2430738/183158497-968f5f93-ce13-4d66-b762-d24a2233694d.png)

The login page issue mentioned above is still a problem, but I haven't looked into alternatives to Artifactory yet.

**Comment by Ortham** [comment]
I just tried Azure Artifacts, but while it gives 2 GB of free storage and allows anonymous access, the only supported way to download artifacts is using the Azure CLI tool.

I also had a look at packagecloud, but while they claim to support storing arbitrary file types, their CLI client (the only documented way to publish such files) only whitelists *.asc files.

**Comment by sibir-ine** [comment]
Is there a way to report the login page bug to JFrog? I tried doing it myself, but they weren't really responsive to my attempts to reach out, & support may only be available to people who actually use the service to host repos (& possibly only to paid users, not sure).

**Comment by Ortham** [comment]
> Is there a way to report the login page bug to JFrog? I tried doing it myself, but they weren't really responsive to my attempts to reach out, & support may only be available to people who actually use the service to host repos (& possibly only to paid users, not sure).

Technical support seems to be done through an issue tracker that is only available to paid users, unfortunately.

**Comment by sibir-ine** [comment]
I may be speaking too soon, but it looks like they've removed the login screen.

**Comment by Ortham** [comment]
😮 It looks like you're right!

In that case, I'm going to close this as that was the issue and I haven't found any real suitable alternative since opening this issue.
