### ISSUE TITLE
Adding edges to Groups is hindered by graph movement feature

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1767]
Following a discussion with @FelesNoctis in Discord [here](https://discord.com/channels/473542112974077963/496196499890241546/997636548675768421), I've found that connecting groups can be harder than it should be.

![LOOT](https://user-images.githubusercontent.com/10406657/180047481-73b17634-ea60-4703-8809-50c13d684aa9.gif)

If you are on the edge of a group and do the first left click (of the required double left click to create a connection between two groups), this can get registered as "grabbing the pane" in order to move the entire graph around.

Would it be possible that moving the entire graph around would only be allowed, if a node isn't around, perhaps even that a node must be a few pixels away?

**Comment by Ortham** [comment]
> Would it be possible that moving the entire graph around would only be allowed, if a node isn't around, perhaps even that a node must be a few pixels away?

Yes, or I can adjust the collision box of the nodes - right now I think it exactly fits the circle and has a rectangle covering the text, but I can add some padding around the circle.

**Comment by Ortham** [comment]
I've added half-radius padding around the circles to make them easier to grab, @pStyl3 can you check and see how it feels for you?

**Comment by pStyl3** [comment]
The added padding feels great, I like it.

**Comment by Ortham** [comment]
Done in 6798ffa8be2eec89aef90878ac0136d956e39dc7.
