### ISSUE TITLE
Toggle between ascending & descending order in Plugins list columns

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1768]
[Requested](https://forums.nexusmods.com/index.php?showtopic=5002060/#entry112386833) in the Nexus forum

The request is to add the ability to toggle between ascending & descending order when clicking on the column titles (i.e., Position, Index, & Plugin Name). Adding this feature to Index & Plugin Name would also require adding the ability to sort by them. Hopefully with the Position column for comparison, this wouldn't introduce too much confusion when the order doesn't match the actual sorted load order, but perhaps this could be further mitigated by forcing it to sort by Position in ascending order when load order sorting produces changes.

**Comment by Ortham** [comment]
I don't see the point of this, why is being able to sort by the different columns an improvement? There's only one order that matters, and that's the load order. If you want to find a plugin by name, there's search.

**Comment by selsie** [comment]
If you want to find several plugins by name, e.g. lux* the search doesn't work well.

**Comment by sibir-ine** [comment]
> If you want to find several plugins by name, e.g. lux* the search doesn't work well (I have 128 files with that string in it.

If you're trying to use `*` as a wild card, you can do the same with regexes with `.*`. You can therefore search for `lux.*` with regex checkbox checked.
> Besides, the search box text resets when I save Metadata, which makes me write the same search term over and over.

I can reproduce this, I'll file a separate issue for it.

**Comment by sibir-ine** [comment]
You probably want to use the text filter rather than the search dialog for your purposes. That doesn't clear when saving metadata & also supports regexes.
