### ISSUE TITLE
Make interface fully navigable with keyboard

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1770]
[Requested](https://forums.nexusmods.com/index.php?showtopic=5002060/#entry112386833) in the Nexus forum

The request is to make the interface completely navigable with a keyboard. This would probably mostly involve adding more shortcuts (#1760) to access parts like the menu bar & changing the behavior of some keys (e.g., Tab) within the interface to better navigate between & within components.

**Comment by Ortham** [comment]
This is the sort of thing I'd have hoped Qt would provide for "free". 

The groups editor can't be keyboard-navigable because it's a drag-and-drop based interface, but it looks like most other bits work - the issues I spotted are:

* when the plugins sidebar panel is visible, it captures tab navigation and I can't figure out how to escape it (that might just be because I don't do much keyboard navigation between different window elements)
* sometimes when tabbing around the dotted-line box that indicates the focussed element just disappears until you tab again, like it's selected an invisible element, which makes navigation uncertain
* sometimes the order in which tab moves through elements is not obvious to me (e.g. in the sidebar you get to the text filter and then have to tab through all the checkbox filters until it reaches the "use regular expression" checkbox).

**Comment by Ortham** [comment]
I've improved tab navigation in the `better-keyboard-navigation` branch, a few things are still outstanding:

- it's not possible to switch between the plugins and filters panels in the sidebar
- it's not possible to navigate between toolbar buttons, only the game combo box is navigable
- it's not possible to navigate the message content editor dialog, trying to just closes the dialog

**Comment by sibir-ine** [comment]
> it's not possible to switch between the plugins and filters panels in the sidebar

Is it not possible to use hotkeys to select them or toggle between them?

> it's not possible to navigate the message content editor dialog, trying to just closes the dialog

If you select an element within the dialog, you can navigate it, but pressing tab two more times after it focuses on the __Cancel__ button closes it. Is there no way to override this behavior for that type of Qt dialog? If not, can it be converted to the same type of window as the groups editor?

**Comment by Ortham** [comment]
I think the problem with the dialog is that it's the editor for a table cell - it looks like once you open an editor in the table, the table stops ignoring tab keypresses and still has keyboard focus, so pressing tab switches to the next cell.

**Comment by sibir-ine** [comment]
> I think the problem with the dialog is that it's the editor for a table cell - it looks like once you open an editor in the table, the table stops ignoring tab keypresses and still has keyboard focus, so pressing tab switches to the next cell.

Yeah, that's what it looks like. The same thing happens when you manually focus on the dialog, the table eventually steals focus again. Is there a way to completely lock focus on the dialog while it's open?

As for the new actions, the __Apply__ & __Discard__ buttons will need ones as well.

I also noticed that in the metadata editor, when one of the tabs are in focus, a box is displayed around the text to indicate it's highlighted, but the box doesn't properly fit the text:

![image](https://user-images.githubusercontent.com/69141501/184280266-52fcb751-29a4-45ca-ad8c-51ec2f8e701e.png)

**Comment by Ortham** [comment]
> Is there a way to completely lock focus on the dialog while it's open?

That's what I've been trying to find.

> As for the new actions, the **Apply** & **Discard** buttons will need ones as well.

I forgot about them, thanks.

> I also noticed that in the metadata editor, when one of the tabs are in focus, a box is displayed around the text to indicate it's highlighted, but the box doesn't properly fit the text:

I don't know why, that's something Qt handles. I don't intend to look into it, it's minor and there's probably nothing I can feasibly do about it.

**Comment by Ortham** [comment]
@sibir-ine The message content editor dialog should now handle tabs correctly, can you try it out?

**Comment by sibir-ine** [comment]
Yup, it appears to lock focus on the dialog now, & the new actions & mnemonics work as intended 👍 One last thing I noticed is that in the Settings menu, when navigating through the settings for a game profile, `Tab` navigates to the __Save__ & __Cancel__ buttons before any of the profile settings. Other than that, I'm pretty sure that's everything covered.

**Comment by Ortham** [comment]
OK, closing this as done as of 2441638d7f4fdec69cb9510b2b78b46b5b06ce75.

> One last thing I noticed is that in the Settings menu, when navigating through the settings for a game profile, `Tab` navigates to the **Save** & **Cancel** buttons before any of the profile settings.

That seems to just be the way tab ordering works for all dialogs, I'm leaving that as it is.
