### ISSUE TITLE
Censor usernames in debug log

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1771]
Windows usernames can contain personally identifiable information as it's not uncommon for people to use their first or even full name within it. The debug log doesn't appear to contain this information often, but both versions of Enderal provide local AppData path overrides by default that contain the user's username. MO2 implemented this in ModOrganizer2/modorganizer#1621, as did Wrye Bash in wrye-bash/wrye-bash@477575f5223fccdc6ff36ef809b769ca6a7a93a7, so they could be used as inspiration.

**Comment by pStyl3** [comment]
This is a great idea, though there's one aspect I'd like to point out and that is the circumstance, that user names sometimes include non standard letters, which was an issue for LOOT in one case a couple of years ago. I'm not sure where that discussion took place, as I would have liked to link it here.

Perhaps we could add a check, if the user name include a non-[ASCII](https://www.rapidtables.com/code/text/ascii-table.html) character? And if yes, print that as a message to the debug log.

That way we would censor the user names, but still know if the name includes special characters that might be part of the users issue.

**Comment by Ortham** [comment]
Yeah, that's worth pointing out: Wrye Bash only made the change once they were in a position that non-ASCII characters would no longer cause issues, and LOOT being largely in C++ that is more difficult to ensure (though the test suite does cover testing non-ASCII paths in many cases). We can add some initialisation checks that log if any of the directories that LOOT uses contain non-ASCII paths, but at this point I'm fairly confident in the test coverage, and if we're adding the checks for each of those directories, why not just fix their handling? You've already identified what could be problematic, it would "just" then need to be traced through to where it's used.

Also, the approach of just replacing all instances of the user's username like MO2 does can also leak information, e.g. if the name appears within another string such that it can be guessed - if your username is sam then it'll be obvious when the log contains text like `255 normal plugins and at least one light plugin are active at the *****e time.`. I imagine that'll be relatively rare, but I can also imagine that there'll be users who don't have their user directory paths logged but who do fall foul of this substitution leaking their names, making the problem strictly worse for them. It's like a twist on the scunthorpe problem.

For that reason, I prefer Wrye Bash's approach of replacing the whole user directory path substring. I think replacing `%USERPROFILE%` should be good enough, though there are probably weird edge cases where `%LOCALAPPDATA%` isn't in `%USERPROFILE%` or the user's put their game or LOOT in another path that contains their name.

**Comment by sibir-ine** [comment]
Yeah, I remembered hearing about LOOT having issues with non-ASCII characters in paths at some point, but I was under the impression that the issue was resolved & therefore didn't mention it. I haven't seen any issues recently, so I assume we can depend on LOOT's test suite & just keep it in the back of our heads in case someone reports an issue with no obvious solution.

Re the approach, I also prefer WB's for the reason you laid out. I feel like the probability of a false negative is probably significantly less than a false positive in this case. Besides, there's also the issue that if your username is a common string (or, god forbid, a single letter as I think was the case with an MO2 user) within the log, regardless of it containing PII, it could potentially make the log difficult to read.

**Comment by Ortham** [comment]
@pStyl3 @sibir-ine This has been implemented in the `censor-userprofile` branch, give it a spin and let me know what you think?

**Comment by sibir-ine** [comment]
Seems to be working really well, not a single instance missed so far out of ~80. Replacing the path with `%USERPROFILE%` is also a really nice touch 👍

**Comment by pStyl3** [comment]
Seems to be working for me as well. 👍

**Comment by Ortham** [comment]
Done in df567d56f08c7cba303af48705c38f18913ce810.
