### ISSUE TITLE
User groups not set to load after any other groups aren't saved to userlist

### ISSUE THREAD

**Issue by monax3** [loot/loot#1772]
To reproduce:

1. Open the group editor
2. Create a new group
3. Drag an arrow from the group to any built-in group
4. Click Save
5. Click Sort Plugins

The result is the message "The group does not exist" until the group is deleted in the group editor

**Comment by sibir-ine** [comment]
I can reproduce this in v0.18.3.

**Comment by Ortham** [comment]
Yeah, this looks like the other half of the bug I fixed in 51d48aca3d233037dee0e5f61a50e1cfcafa54aa...

**Comment by Ortham** [comment]
I think this is now fixed in the `misc` branch, @sibir-ine can you confirm?

**Comment by sibir-ine** [comment]
Yup, that appears to have fixed it 👍

**Comment by Ortham** [comment]
Fixed in 11d82bb4831477df958fd73f5033a3f3fb21cc56.
