### ISSUE TITLE
Improve text scaling in Plugins sidebar section

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1773]
When using system-wide text scaling (e.g., text scaling in the Windows Ease of Access settings) to increase the size of text, most of LOOT scales relatively well (at the very least, it doesn't fare much worse than most applications). However, the Plugins section of the sidebar becomes unreadable very quickly. Here's an example with 150% text scaling:

![image](https://user-images.githubusercontent.com/69141501/182596888-66c4626d-7426-4c96-9ccc-f0f5e3ea8297.png)
As you can see, the cards, menu bar, & toolbar are all still readable (as are the UI elements not shown), but the sidebar text is cut off & difficult to read. At higher scales, it becomes completely unreadable, & the positions & indices begin to get cut off as well.

**Comment by Ortham** [comment]
I don't see this, at 200% scaling I see the height of the rows scales correctly (150% is the same):

![image](https://user-images.githubusercontent.com/2430738/183146485-e9ab56d8-6717-4c95-9999-f50fba3fffee.png)

**Comment by sibir-ine** [comment]
What setting are you using? I'm referring to this one:

![image](https://user-images.githubusercontent.com/69141501/183230673-7f3d94c6-71ca-4350-ad8e-7c1ae2e79ba5.png)
Settings like _Make everything bigger_ seem to work without issue, it's just when scaling text alone that the issue occurs.

**Comment by Ortham** [comment]
Ah, I didn't read your post properly: I've been using the System -> Display scaling option, I see what you mean now.

I think this is now fixed in the `fix-scaling` branch, can you confirm?

**Comment by sibir-ine** [comment]
Yes, it scales properly now. However, at some scales (including default, i.e., 100%), letters like `g` get a tiny bit cut off, so would it be possible to add a little extra padding as well?

![image](https://user-images.githubusercontent.com/69141501/183242406-e1864d15-39cc-43cc-a656-310628364792.png)

**Comment by Ortham** [comment]
Yes, that should now be fixed.

**Comment by sibir-ine** [comment]
Looks good now 👍

**Comment by Ortham** [comment]
OK, done in b9cae0c60d556f0e740caa1d194a187521a44dd8.
