### ISSUE TITLE
Add missing files to uninstaller

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1774]
Here's a list of files & folders that I noticed the uninstaller doesn't uninstall that it should as well as some suggestions:

In the AppData folder:

- The Prelude folder
- The `masterlist.yaml.metadata.toml` files

Install folder:

- The empty install folder itself

User data:

- Hasn't been updated for the move to the `games` folder
- Missing userlists for SSE, Nehrim, both Enderals, & both VR games

Suggestions:

- Delete load order backups (not AppData folder backups in case a user accidentally accepts the delete user data dialog) as user data
- Delete group node position files as user data
- Don't treat debug log as user data (i.e., always uninstall since it's not particularly useful for users to keep around)

**Comment by Ortham** [comment]
All these are done in the `rename-groups` branch.

**Comment by sibir-ine** [comment]
Everything cleans up neatly now 👍

**Comment by Ortham** [comment]
Done in e70188b93182eeeadc98e89f38220734232be2c1.
