### ISSUE TITLE
Text filter sometimes causes Plugin menu to be grayed out for last unfiltered plugin

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1775]
Steps to reproduce:
1. Open LOOT & select SSE
2. Switch to the _Filters_ list
3. Type `dawn` into the text filter
4. Switch back to the _Plugins_ list
5. Select `Dawnguard.esm` & attempt to open its _Plugin_ menu

Selecting another plugin seems to fix it, but this obviously isn't possible with only one unfiltered result. It also doesn't always seem to occur depending on, from what I can tell, some combination of the filter string used, the plugin selected prior to filtering, & the LO position of the plugin (i.e., it seems to happen less consistently with the first few plugins in the LO). However, it seems to happen consistently enough regardless of these factors.

**Comment by Ortham** [comment]
This should be fixed in the `rename-groups` branch, @sibir-ine can you confirm?

**Comment by sibir-ine** [comment]
Yup, that appears to have fixed it 👍

**Comment by Ortham** [comment]
OK, fixed in 1939fbcd331e869e6c4b248f702b69e92977e9ae.
