### ISSUE TITLE
Drop support for some versions of Windows

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1776]
LOOT currently offers two builds: 

- a 32-bit build that supports 32-bit and 64-bit Windows 7, 8.1, 10 and 11 (which doesn't have a 32-bit version), using Qt 5.15
- a 64-bit build that supports 64-bit Windows 10 (1809+) and 11, using Qt 6.2

Windows 7 and 8.1 will reach full end of life on 2023-01-10. Qt only provides updates to open-source users for 6 months, so Qt 5.15 has been effectively EOL for about 2 years, and Qt 6.x doesn't support Windows 7 or 8.1 or 32-bit Windows.

Given all that, I'm thinking to drop support for Windows 7, 8.1 and the 32-bit version of Windows 10 after 2023-01-10, i.e. releases after 2023-01-10 will support only 64-bit Windows 10 (1809+) and 11.

The Steam hardware survey (looking at Windows only) says:

| Windows version | July / % | August / % | September / % | October / % |  November / % | December / % |
|------------------|--------------|--------------|--------------|--------------|------|----|
| 10 64 bit | 75.41 | 71.76 | 71.04 | 71.41 | 68.25 | 68.04
| 11 64 bit | 21.77 | 24.71 | 25.76 | 24.22 | 29.11 | 29.56
| 7 64 bit | 2.10 | 2.70 | 2.49 | 3.72 | 1.96 | 1.73
| 8.1 64-bit | 0.52 | 0.53 | 0.46 | 0.42 | 0.43 | 0.43
| 7 | 0.1 | 0.15 | 0.12 | 0.11 | 0.11 | 0.11
| 10 | | 0.06 | | | |
| Other | 0.1 | 0.08 | 0.12 | 0.12 | 0.13 | 0.13

The OSes included in "Other" that LOOT currently supports are Windows 8.1 32-bit and Windows 10 32-bit (apart from in August).

Assuming the Steam stats accurately reflect our users' stats, if we dropped support in July it would have affected up to 2.82% of users. I expect that the percentage of LOOT users affected will go down over time - while Windows 7 Steam usage has increased, that'll be down to the Steam userbase growing (adding new users on old hardware/software) rather than people downgrading to Windows 7, and those new users are unlikely to experience LOOT dropping support for them (because they probably weren't already using LOOT).

This is still over 5 months away, but I figure it's better to get it written down sooner rather than later, in case anyone's got any comments.

**Comment by pStyl3** [comment]
Sooner or later we should make the switch, and personally I will fully support the decision then. We explicitly provide two different versions of LOOT since a couple of months and that alone should communicate the notion, that the end of support for older Windows versions is in sight. It may not be what some people want, but it's important that we stay efficient and not support software that's EOL no matter what.

I'd say, if version 0.18.4 would be the last version to support older Windows versions, that would be okay. We probably should make it clear and announce the fact, that going forward we then would update Qt and what that entails.

**Comment by RacerBG** [comment]
This decision is understandable but I would like to see 0.18.4 as the last version which support these OS's as well. Then the version after it should probably be 0.19.0.

**Comment by sibir-ine** [comment]
Yeah, I also think we should give it at least one more release due to the bug fixes & QoL changes that will be in it. Other than that, yeah, we probably shouldn't be stuck on obsolescent technology for too long if we can help it.

**Comment by Ortham** [comment]
To be clear:

* I won't change LOOT's requirements in a patch (0.18.x) release
* I don't intend to change any requirements before December this year - I might decide to drop Windows 7 and 8.1 in December or delay increasing the minimum required version of Windows 10 until January, I don't think the month difference will really matter either way but if there's a practical reason to upgrade Qt in December (e.g. there's a bug that impacts LOOT that's fixed) then I could do that.
* I do intend to get another release out before then, as there have already been a few fixes and improvements since 0.18.3

Also, I got the Qt lifecycle info wrong above, so I've updated the OP to reflect that.

**Comment by Ortham** [comment]
Qt 6.4.0 has been released and it unexpectedly changed the Windows requirement to read "Windows 10 (1809 or later)", making no mention of 21H2. 

However, the [Qt downloads](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_640/qt.qt6.640.win64_msvc2019_64/) do include 21H2 in their names, but looking back at previous releases that was introduced in [Qt 6.2.3](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt6_623/qt.qt6.623.win64_msvc2019_64/), (which was released in January 2022) and LOOT uses 6.2.4. 

Qt 6.2's requirement reads "Windows 10 21H2 (1809 or later)", which doesn't make any sense because 21H2 and 1809 are both versions (21H2 > 1809). I think the mentions of 21H2 are essentially typos - as far as I can tell there were no backwards-incompatible Windows SDK changes introduced in 21H2, and the latest SDK still downlevels to 1809.

I'm interpreting all this as meaning that the minimum supported Windows 10 version is 1809, that this hasn't changed, so it's safe to update to Qt 6.4.0 without dropping support for anyone. I've updated the OP to reflect that.

**Comment by Ortham** [comment]
Done as of bef195433c3b8125eb60f2210095b0eacffdb659.

**Comment by sibir-ine** [comment]
It's worth noting that Steam will be [dropping support for Windows 7/8/8.1](https://help.steampowered.com/en/faqs/view/4784-4F2B-1321-800A) at the beginning of next year.

**Comment by RacerBG** [comment]
As a last-ditch effort here is an unofficial way to run LOOT 0.20.0 and probably higher versions of the program if you are still on Windows 7 but be aware that this is do it at your own risk task:

1. Download the patched Qt 6.5.1 DLL's. **The patched DLL's must match exactly the Qt version of LOOT!**
2. Copy & Paste them in to your LOOT directory.

You must manually update your masterlists from now on. Download the raw .yaml files from GitHub and paste them in to your respective folders in _C:\Users\Your_User\AppData\Local\LOOT_.

PS: At the time of writing this, LOOT 0.19.1 is still a good solution if you are on Windows 7.

[Qt 6.5.1 DLLs.zip](https://github.com/loot/loot/files/11714425/Qt.6.5.1.DLLs.zip)
