### ISSUE TITLE
LOOT does not seem to sort with modified userdata (Skyrim SE)

### ISSUE THREAD

**Issue by Foroneus** [loot/loot#1777]
For the record, I _am_ using it with MO2, but I'm not so sure that it's the cause of this problem.
When I've been running LOOT these past few weeks, the sorting would not take; it would change, I would tell it to apply, and I would close it but the load order remained the same as before.
But lately, I've decided to run a backup and then reset all user metadata to see if that was the problem; sure enough, it was and when I run LOOT, it actually changes the load order in MO2. Is this an actual bug or is something broken in my user metadata settings that stop LOOT from working right.

EDIT: in case it helps narrow down I've also used the builtin "Sort" button in MO2, which was indeed able to change my load order.

**Comment by sibir-ine** [comment]
Can you please upload your userlist as well as a [full debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log) attempting to sort with it?

**Comment by Foroneus** [comment]
> Can you please upload your userlist as well as a [full debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log) attempting to sort with it?
Userlist and debug log where I turned on debug logging, attempted sorting, cleared user metadata, and then sorted again:
[userlist.zip](https://github.com/loot/loot/files/9313619/userlist.zip)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/9313621/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
Is that the userlist that caused the issue? It's empty, & I can't replicate the issue with an empty userlist while using Wrye Bash. Also, please try to upload a debug log where you can confirm that you've reproduced the issue. From your description, it doesn't sound like you confirmed  that your load order didn't update outside LOOT with the problematic userlist before clearing it.

**Comment by Foroneus** [comment]
> Is that the userlist that caused the issue? It's empty, & I can't replicate the issue with an empty userlist while using Wrye Bash. Also, please try to upload a debug log where you can confirm that you've reproduced the issue. From your description, it doesn't sound like you confirmed that your load order didn't update outside LOOT with the problematic userlist before clearing it.

Whatever the issue seems to have been, I seem to be able to fix it by just extracting an old backup and running LOOT again; even when disabling and re-enabling "Lock GUI when running executable" in MO2, something that I'm still sure is related to this, is now no longer affecting plugin order like it did before; even the userlist is now populated with mods again, something that I didn't even know was an issue.

I'm simply confused at this point, but since the problem seems to be resolved, I might just close this issue anyway.

**Comment by sibir-ine** [comment]
I'm pretty sure disabling the GUI lock for programs like LOOT that depend on the data MO2's virtualization system is deploying is generally a bad idea, so I'd avoid doing that. If you make any changes to your load order within MO2, I don't think the virtualized data that's already deployed will dynamically update so that LOOT can see the changes. You'd need to close LOOT, make the changes, then open LOOT through MO2 again.
