### ISSUE TITLE
Can't update sorted load order

### ISSUE THREAD

**Issue by L-dong** [loot/loot#1784]
After click 'apply sorted load order',the load order had't change as it in the LOOT.
My loot and skse  are the latest vesion.
Anyone who can help me ,thank you!

**Comment by sibir-ine** [comment]
What mod manager do you use?

**Comment by sibir-ine** [comment]
Closing as stale. If you're still having problems, feel free to ask at our [Discord server](https://loot.github.io/discord/) or [forum thread](https://loot.github.io/latest-thread/). You can also continue the discussion in this issue if you think it's the same problem.
