### ISSUE TITLE
The procedure entry point (CreateDXGIFactory2) could not be located in the DLL (dxgi.dll)

### ISSUE THREAD

**Issue by 468hnj** [loot/loot#1793]
Every time i try to start up LOOT i get this error:

The procedure entry point (CreateDXGIFactory2) could not be located in the DLL (dxgi.dll)

I havent done anything yet, just installed the app. Tried restarting, tried from the zip and the exe installation too.

**Comment by sibir-ine** [comment]
What's your OS & architecture (i.e., 32-bit or 64-bit)? Which version of LOOT did you download?

**Comment by 468hnj** [comment]
After 3 hours i figured out that im just blind and downloaded the wrong version repeatedly.
