### ISSUE TITLE
Visually differentiate between user & non-user metadata within metadata editor

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1799]
The icon is currently displayed in the plugins list in a separate column, so this column could presumably be added to each table within the metadata editor as well. Currently, the icon is only used there to identify if any of the tabs contain user metadata, so you actually have to check whether a row can be deleted to tell if it's user metadata.

**Comment by Ortham** [comment]
I've tried to implement this today and it's a bit awkward. In the old UI the non-user metadata was distinguished by having it greyed out, and I can do that instead. Here's a screenshot with the icon and with the greyed-out text, what do you think?

![image](https://user-images.githubusercontent.com/2430738/199024530-b0c506a5-4248-42a8-a979-7fb72dda50cd.png)

**Comment by sibir-ine** [comment]
Yeah, I think that works better since it also communicates at a glance that non-user metadata can't be edited 👍

**Comment by Ortham** [comment]
Done in 173dfd907f3c59ff25609a5f0ad5764627af1cf0.
