### ISSUE TITLE
Qt v6.2 bug that affects users with multiple monitors

### ISSUE THREAD

**Issue by theloser** [loot/loot#1800]
LOOT v0.18.4 always opens the main window on my right-most monitor (3-monitor setup), although the center monitor is set as default/main. There are two issues with multiple monitors:

- when closing and re-opening LOOT it does remember the window size, but not the window position. It will open again on my right-most monitor
- if moving LOOT to any other than the right-most monitor, all sub-menus (when clicking on "File", "Game" etc) will open on the right-most monitor

Versions up to and including v0.18.3 do not have this issue (tested: 0.16.1, 0.17.0, 0.18.0, 0.18.1, 0.18.2 and 0.18.3).

**Comment by sibir-ine** [comment]
This is a bug with the version of Qt v6.2 that LOOT v0.18.4 uses. It's been fixed in Qt v6.3, but updating would've required bumping the version requirement for the 64-bit builds which @Ortham wanted to avoid for that release.

**Comment by Ortham** [comment]
@theloser You can try [this Qt 6.3 build](https://github.com/loot/loot/actions/runs/2920773958) to see if it fixes the issues for you.

**Comment by Ortham** [comment]
It turns out that Qt v6.4.0 doesn't actually bump the version requirement, so the master branch has been updated to that, and this issue should now be fixed.

**Comment by theloser** [comment]
Can confirm, 0.18.5 doesn't have this issue anymore! Thanks!
