### ISSUE TITLE
Big ISSUE

### ISSUE THREAD

**Issue by DjDarthyGamer** [loot/loot#1810]
ENG 
Hi, I noticed that when LOOT prepares the loading order of some mods for Skyrim AE, if more than 500 or in any case more or less them in total, some mods are skipped or not read and therefore missing in the order and NNM excludes them and makes the game unplayable, this thing only happens with NMM, for example with MO2 it doesn't happen and it works well or at least it seems ...

(however this bug, should be present even with less mods, I have given example 500 but sometimes it also happens with 20)

ITA
Salve, ho notato che quando LOOT, prepara l'ordine di caricamento di alcune mods per Skyrim AE, se più di 500 o comunque più o meno li di totale, alcune mods vengono saltate o non lette e quindi mancanti dentro l'ordinamento e NNM le esclude e rende il gioco ingiocabile, questa cosa succede solo con NMM, esempio con MO2 non succede e funziona bene od almeno pare...
Salve, ho notato che quando LOOT, prepara l'ordine di caricamento di alcune mods per Skyrim AE, se più di 500 o comunque più o meno li di totale, alcune mods vengono saltate o non lette e quindi mancanti dentro l'ordinamento e NNM le esclude e rende il gioco ingiocabile, questa cosa succede solo con NMM, esempio con MO2 non succede e funziona bene od almeno pare...

(comunque questo bug, dovrebbe essere presente anche con meno mods, io ho fatto esempio 500 ma avvolte succede anche con 20)

**Comment by Ortham** [comment]
If this only happens with NMM then it's probably not an issue with LOOT itself. Can you replicate the issue using the LOOT application on its own?

**Comment by sibir-ine** [comment]
Closing since there hasn't been any response in over a week & it appears to be an issue with NMM, not LOOT.
