### ISSUE TITLE
Add support for the Epic distribution of Fallout 3

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1812]
As mentioned by sibir in #1809, Fallout 3 is [coming](https://store.epicgames.com/en-US/p/fallout-3-game-of-the-year-edition) to the Epic Games Store, so add support for it once it arrives there.

**Comment by Ortham** [comment]
I've just downloaded Fallout 3 from EGS: it uses `%LOCALAPPDATA%\Fallout3\plugins.txt`, and doesn't write its install path to the Registry. I've uploaded its [EGS manifest file](https://github.com/loot/loot/files/9832252/7D528F2141909752BCF0768BAD5279BB.zip) (packaged in a zip so that GitHub will accept it): the `AppName` is `adeae8bbfc94427db57c7dfecce3f1d4`.

**Comment by Ortham** [comment]
Detection of the game's install path is complicated by the fact that each localisation ships as a separate copy of the game within the directory given by `InstallLocation` in the EGS manifest file, like Oblivion in the MS Store. The directories are shown in this screenshot:

![image](https://user-images.githubusercontent.com/2430738/197012983-fe6a857a-f215-4970-bd22-cf05dc291019.png)

Each one of the "Fallout 3 GOTY <language>" directories contains `Fallout3.exe` and all the other files and the `Data` directory, e.g:

![image](https://user-images.githubusercontent.com/2430738/197013221-f58e4946-8a01-4da2-bae3-60f18c17d550.png)

**Comment by Ortham** [comment]
This is now done in the `egs-fallout3` branch.

**Comment by Ortham** [comment]
I'm going to try to improve the logic for what localisation gets launched by the Epic launcher - it seems to be tied to the Windows display language, so I'll try adding logic to check what that is and check what the behaviour is when the display language doesn't have a game localisation.

**Comment by sibir-ine** [comment]
Just to confirm, the title of my `.item` file is `E45D17924A2F4666942FA8BE8DFE728C`, so they don't seem to be named in a consistent way that we could take advantage of.

**Comment by Ortham** [comment]
This is done as of d368438b16cbb863e147e8a85455620af875347e - I've also improved the localised game handling so that LOOT will try localisations in the order of the user's preferred UI languages as reported by Windows, which seems to be how the EGS and MS Store launchers pick a localisation.
