### ISSUE TITLE
Add option to default to last assigned group in group dropdown menu in metadata editor

### ISSUE THREAD

**Issue by selsie** [loot/loot#1814]
When editing metadata -> Group, the standard selection is default. 

Clicking on the dropdown, I'm at the very end of my group list.

**It would be cool if it could automatically jump to the last assigned group, because it is very likely that one adds multiple files at once to a group.**

**Comment by Ortham** [comment]
@selsie When you say the "last assigned group", do you mean that if I edit plugin A to put it in group X and save that edited metadata, when I then edit plugin B, clicking on the group select box should highlight group X in the dropdown?

**Comment by selsie** [comment]
Yes, exactly.

Oliver Hamlet - ***@***.***
***@***.***> schrieb
am Di., 25. Okt. 2022, 18:09:

**Comment by Ortham** [comment]
Closing this because I had a look but can't figure out how to implement this. Hopefully #1790 is a more feasible alternative for efficiently adding multiple plugins to the same group more easily than you can at the moment.
