### ISSUE TITLE
Update search results instead of resetting search after updating plugin metadata

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1816]
This doesn't happen when closing via the cancel button.

**Comment by Ortham** [comment]
This is intentional, it happens whenever plugin data changes and when conflict filtering (because that can also change plugin data, that might be a redundant call). However, I can see that it would be better to re-run the current search instead.

**Comment by Ortham** [comment]
Done in 25933754c0287d72e1d18b44929e8782a719e850.
