### ISSUE TITLE
LOOT throwing floppy drive errors on startup

### ISSUE THREAD

**Issue by Ham62** [loot/loot#1827]
When starting LOOT, it attempts to access the floppy drive completely unprompted before starting.

If a diskette is present in the drive, it makes 2 separate reads from the disk. One that completes before the window opens, then another (much) longer one which completes after the main screen is populated in the program.

If no diskette is present, LOOT throws a critical error complaining no disk is present in the drive and asks that one is inserted. Whether a disk is inserted or not, LOOT's startup continues as normal after this point. I've included a screenshot of the error below.
https://i.imgur.com/TeGwb1u.png

It should be noted that LOOT does not attempt to access either of the optical drives on start that I could notice, and does not throw any errors about having a disc present or not. It appears to only do this for diskette drives hooked up on the system.

This was tested launching LOOT 1.18.6.

**Comment by sibir-ine** [comment]
Could you please [upload a debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log) after replicating the issue?

**Comment by Ham62** [comment]
Sorry, here's the startup log.

https://pastebin.com/r8GeRPrw

As it turns out from the log, it looks like LOOT actually was pinging (and failing to read) all 3 of the optical drives on startup the same as the floppy drive. For some reason only the floppy threw the blocking error dialog though.

**Comment by Ortham** [comment]
This is due to LOOT checking all drives to see if they hold any Microsoft Store games. I've changed that to only check what Windows reports as fixed or RAM disk drives.

@Ham62 Can you try out [this build](https://loot.jfrog.io/ui/native/loot/restrict-drive-scanning/) and let us know if that works for you?

**Comment by Ham62** [comment]
This build seems to work without error! 
Thanks guys!
