### ISSUE TITLE
Add filter to hide cleaning data for official plugins

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1828]
Cleaning official plugins appears to carry some risks due to peculiarities that apply only to them. xEdit has addressed all that we know of, but there's no guarantee that there aren't more (see this [wiki article](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-OFST) from Wrye Bash for a history of them). I don't think we should go as far as removing them outright as these issues can always be addressed by the xEdit team as they come up, & there's the slight possibility of UDRs causing issues for older mods IIUC (I don't believe ITMs are an issue as official plugins tend to load before mods & rarely revert changes from other official plugins AFAIK). However, it'd be a good idea to allow users who would rather avoid the risk the option to hide them. The Wrye Bash team has even done so in v311 (see wrye-bash/wrye-bash@f01a417). The Oblivion GotY add-ons & CC content might not be as risky to clean, but they could be added too for good measure (as WB did).

**Comment by Ortham** [comment]
Does this apply to only official masters, or all official plugins? I.e. can the filter logic be `IsOfficial(plugin)` or `IsOfficial(plugin) && IsMaster(plugin)`?

**Comment by sibir-ine** [comment]
Probably `IsOfficial(plugin)`. I doubt there are many users who are skeptical of cleaning official masters but not official non-masters. IIRC, the only plugins in that category are the Oblivion DLCs & the [official Morrowind plugins](https://en.uesp.net/wiki/Morrowind:Plugins) (not the expansions). The SSE CC plugins are all masters, & I'm not sure about the FO4 CC plugins.

**Comment by Ortham** [comment]
@sibir-ine I'm a little unclear on what should be filtered: is it the cleaning messages, or the dirty info itself? I.e. would this affect other things like the dirty plugin count and the metadata displayed in the metadata editor when an affected plugin's metadata is being edited.

I'd expect the message to get hidden and the dirty plugin count to decrease by one but the metadata to still be visible in the metadata editor when the filter is active and there's an official plugin with dirty info, but I wanted to check.

**Comment by sibir-ine** [comment]
Just the messages. IIRC, the filter for hiding notes doesn't hide them in the metadata editor as well, same with tags & locations. As for the count, WB's Plugin Checker still informs you that you have dirty vanilla plugins that are being ignored due to a setting, so maybe we can still count them but put something like "some hidden due to filter" in parentheses next to the count? Otherwise, just subtracting them from the count would work.

**Comment by Ortham** [comment]
Done in 042920812462e7d42cd63d9aa654f4c5d7666c67, though this has to be one of the most lines changed for smallest impact I've done in this repo: nearly 2400 lines of changes to support adding a single checkbox.

**Comment by sibir-ine** [comment]
Looks like it works, thanks!
