### ISSUE TITLE
64-bit v0.19.0 exe seems to download v18.6 installer

### ISSUE THREAD

**Issue by olavinto** [loot/loot#1831]
Simple: The 64-bit Windows .exe v0.19.0 seems to link to v18.6 installer. Or at least that is what the installer and app say after installation.

**Comment by mehmetkursataydin** [comment]
Indeed

**Comment by Ortham** [comment]
It's the right installer/application, they've just got the wrong version number. I'll be releasing 0.19.1 shortly to fix this.

**Comment by Ortham** [comment]
Fixed by the 0.19.1 release.
