### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by 1uniqueBeast** [loot/loot#1832]
Hello. I've been using Loot for years. I opened it and saw that there was a new update. I closed Loot, uninstalled it, and then tried to install the new one. I'm 99% certain that this is the process I've done with previous updates. But this time I got a windows message saying "0x 80070666 - Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel." But I already did that. I figure there's a file somewhere that didn't get deleted, but I have no idea where. The pop up also gave me a copy of the log file. I can provide those upon request. The only thing I did that might be different from last time is when I uninstalled it, it asked me if I wanted to delete my preferences, and I said yes. Would someone please lend a hand? Thank you.

**Comment by sibir-ine** [comment]
Have you tried rebooting your computer & running the installer again? It shouldn't have an issue with installing when there's an existing installation.

**Comment by Ortham** [comment]
Google suggests that 0x80070666 happens when you've got a newer version of the MSVC redist installed, but the installer should be able to handle this.

Can you check what you've got in your Registry under `SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`, particularly the `Installed`, `Major`, `Minor` and `Bld` values?

Can you also try re-running the installer with its logging enabled, and upload the log file? To enable logging, run it with the `/LOG=<file>` command line parameter. The easiest way to do that is to:

1. Right-click the installer
2. Click "Create shortcut"
3. Right-click the new shortcut
4. Click Properties
5. In the Target input text box, add ` /LOG=setup.log` after the executable path that's already there, e.g. `C:\Users\foo\Downloads\loot_0.19.1-win64.exe /LOG=setup.log`
6. Click OK
7. Double-click the shortcut to run it.

**Comment by 1uniqueBeast** [comment]
Hello. Thanks so much for helping me.
I did the create shortcut thing as you said and got the same result.

This is everything in that registry folder. The column
[dd_vcredist_amd64_20230115210315.log](https://github.com/loot/loot/files/10431793/dd_vcredist_amd64_20230115210315.log)
![Registry Editor clip](https://user-images.githubusercontent.com/122765984/212819771-7f6e4731-7e75-44fe-a238-7507922fdaf7.jpg)
![Loot error](https://user-images.githubusercontent.com/122765984/212819772-6064e9bb-c732-426d-b6f8-1d9974f50083.jpg)
s are Name, Type, and Data.

(Default).......REG_SZ..........(value not set)
Bid.............REG_DWORD.......0x0007cbb (31931)
Installed.......REG_DWORD.......0x00000001 (1)
Major...........REG_DWORD.......0x0000000e (14)
Minor...........REG_DWORD.......0x00000022 (34)
Rbld............REG_DWORD.......0x0000000 (0)
Version.........REG_SZ..........v14.34.31931.00

**Comment by sibir-ine** [comment]
Do you get this error when you run the actual LOOT installer, or just the separate MSVC installer we link to? If the former, can you please also post the `setup.log` file that should be in the same folder as the LOOT installer assuming you followed Ortham's instructions? If the latter, have you tried just running the LOOT installer? It should install the MSVC redistributable for you or just skip it if it or a newer version is already installed as appears to be the case.

**Comment by Ortham** [comment]
@1uniqueBeast I thought you were reporting an issue with the LOOT installer, which is why I gave the path to the LOOT installer executable in my example. The error screenshot you've shared of the MSVC redistributable installer is expected.

**Comment by RacerBG** [comment]
You should be able to install MSVC 2015-2022 (this still works for Windows 7 too). For good measure install both the x86 and x64 versions:

https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by 1uniqueBeast** [comment]
Yeah. I also thought I was reporting an issue with the Loot installer. I didn't understand what I was looking at on the Loot page. I just clicked on the thing that looked like an installation file. I found the correct installation file, installed it, and it works fine. Sorry to waste your time. If it's any consolation, I learned not to make the same mistake again. Thank you.
