### ISSUE TITLE
Updating LOOT deleted all the groups??

### ISSUE THREAD

**Issue by PeachVsEggplant** [loot/loot#1833]
I just updated to the newest version of LOOT - the 64bit.exe - and all the groups that come installed with LOOT are now gone except for "default" help :(
![Screenshot 2023-01-18 082443](https://user-images.githubusercontent.com/122992832/213196683-4adca2fe-cb6c-4fbb-b020-eaa9bec716ae.jpg)

**Comment by sibir-ine** [comment]
After you restore your user metadata from a backup, make sure to restart LOOT & update your masterlist. It gets deleted after an update (hence the `N/A: No masterlist present` in the second screenshot & the lack of masterlist groups), so it just needs to be redownloaded. Sorting does this by default as well unless you disabled updating before sorting in settings.

**Comment by PeachVsEggplant** [comment]
I downloaded v0.19.1 from v0.19.0

**Comment by PeachVsEggplant** [comment]
Will that be affected by the second time when I redid it and selected "erase all user settings and metadata" ?

**Comment by PeachVsEggplant** [comment]
And it erased all the groups that came installed on LOOT, the first time I still had MY created ones, but not any of the preinstalled groups. The second time it was all wiped out.

**Comment by sibir-ine** [comment]
> Will that be affected by the second time when I redid it and selected "erase all user settings and metadata" ?

Backups aren't deleted as part of that option, so you should still have them as long as you didn't manually delete them.

> And it erased all the groups that came installed on LOOT, the first time I still had MY created ones, but not any of the preinstalled groups. The second time it was all wiped out.

This is expected. The installer deletes masterlists when updating but not userlists, so you should've only seen your groups until you updated your masterlist again. The second time, you chose the option to delete all of your user metadata, which includes userlists, so all of your custom groups & rules were deleted on top of your masterlist.

As previously stated, you should just need to restore the latest backup from the location Ortham posted, restart LOOT if it's still open, & update your masterlist with the **Update Masterlist** button (or just sort by default).

**Comment by PeachVsEggplant** [comment]
> As previously stated, you should just need to restore the latest backup from the location Ortham posted, restart LOOT if it's still open, & update your masterlist with the **Update Masterlist** button (or just sort by default).

This worked and brought everything back! Thank you!
