### ISSUE TITLE
Improve handling of masterlists when updating using installer

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1834]
IllusiveMan raised this on Discord. When you run LOOT's installer, it will first check if LOOT has previously been installed using the installer (the version doesn't matter) and run the corresponding uninstaller if so. The installer will remove all non-user-generated files (and the debug log), which means that there will be no masterlist when LOOT is next run. This isn't a problem for a fresh install, but if there is existing user metadata, especially any that relies on masterlist groups, the user may see errors due to undefined metadata.

There are three ways I can think of to improve this:

1. Change the uninstaller to not delete the masterlists if a flag is set, and set the flag when running the uninstaller during install. This would only solve the issue for people upgrading from future releases, and if the masterlist syntax supported has changed it'll still cause errors to be displayed.
2. Bundle masterlist files with the installer and install them too. This would mean that users would get working but outdated masterlists, and those masterlists might not be compatible with the user's metadata (e.g. if the old and new LOOT versions used the same masterlist version but the user metadata relied on a masterlist group added since the new LOOT version's release). This also raises the question of which masterlists to install - it would probably be best just to install them all.
3. Download and install the masterlist files as part of running the installer, like how the MSVC redist is handled. This would require an internet connection when installing, unless it was made an optional part of the install, and the installer would have to be able to calculate and write the update metadata files too (which should be possible, given the available scripting functions). It's got the same question as the second option about which masterlists should be installed.

1 is the easiest to implement, but offers the least improvement, and doesn't improve the UX for fresh installs. I think 3 gives the best UX, but I don't want to break offline installs, so it would have to be optional. Combining it with 2, using the bundled masterlists as a fallback, might be worth the added complexity.

**Comment by sibir-ine** [comment]
Maybe instead of installing every masterlist, we could look at what game folders they have in their LOOT data folder & only install masterlists for them.

**Comment by Ortham** [comment]
> Maybe instead of installing every masterlist, we could look at what game folders they have in their LOOT data folder & only install masterlists for them.

Good idea, but it's easier to just install them all, and I don't think there's much reason not to.

I've done this in the `install-masterlists` branch, installer build is [here](https://loot.jfrog.io/artifactory/loot/install-masterlists/loot_0.19.1-8-g2f0783b_install-masterlists-win64.exe). Dealing with string encodings in PowerShell was a pain but aside from that it was pretty straightforward to bundle and optionally download the masterlists.

**Comment by Ortham** [comment]
Done as of 2f0783b017f958c62bf0562893ce79918d7183fd.
