### ISSUE TITLE
Struggling with custom groups and cyclic interactions

### ISSUE THREAD

**Issue by Runel2** [loot/loot#1835]
Hi! 
In order to have a cleaner load order i made custom groups and placed my 550-ish plugins in said groups because most were in "default". Problem is I don't quite get how this system works since it seems to always give me a cyclic rule between plugins that have nothing to do with each other. I tried to move some of them in "early loaders", and redo the "tree" but nonetheless another cyclic interaction is always found. Can someone explain where i went wrong ?
![image](https://user-images.githubusercontent.com/123494017/214365586-8d97aa65-f06b-4176-a468-8db7867f14b2.png)
![image](https://user-images.githubusercontent.com/123494017/214365688-f44b2384-f213-4213-804a-5ca73bf05f22.png)
![image](https://user-images.githubusercontent.com/123494017/214365728-1f99c490-1255-4c26-b6bc-c266a74a0610.png)

EDIT:
For anyone with the same issue as mine, best way is to unlink everything, link one or two, sort, and if there's no issue, continue. When you have issue check the ones in cyclic rule, most likely a superior plugin is in a lower group than the rest, i suggest having screenshots of previous tree and taking your time :) .

**Comment by Ortham** [comment]
LOOT's current group handling is unable to avoid many cycles even when it's obvious to a human how that would best be done. I'm trying to improve on that, but it's tricky.

I can't give specific advice without any idea of the plugins in the groups, but my general advice is to avoid using groups, especially if it's just to make things look cleaner. They're really more for positioning a plugin relative to an set of unknown other plugins, but if you're defining them for your own load order, you know what plugins you've got installed so could get similar results with load after metadata.

**Comment by sibir-ine** [comment]
If you really do need to use group rules, I'd highly recommend setting custom groups (or chains of custom groups) to load between two directly adjacent masterlist groups to help avoid cyclic interactions. For interactions between plugins in the same group, MacSplody has a good explanation of how to solve these pinned in the `#app-help` channel in our [Discord](https://loot.github.io/discord/). Also, regarding your `flat maps` group specifically, I'm assuming this is for FWMF? If so, this group is unnecessary as we already place it in the `Paper Maps` group, which is late enough (nothing after it will conflict with it). Just let LOOT sort it how it does by default & regenerate your dynamic patches (e.g., Bashed Patch, DynDOLOD) with that order. They will then properly import their changes as necessary like with any other mod. No mod should really need to load after most dynamic patches, including any of the patches we have load rules for.

**Comment by Runel2** [comment]
Sibir yes I noticed the "paper map" group but for some reason it doesn't work if loaded after LODs so i had to make that change. 
Ortham it seems that i'm on the right track, i'm slowly rebuilding the order and so far so good.

**Comment by Runel2** [comment]
I confirm, i managed to make it work. The most triggering was that cycles had like 5 plugins but only two were linked.
This issue is closed
