### ISSUE TITLE
Issues errors when using Sorts plugins and when performing Update masterlist.

### ISSUE THREAD

**Issue by Trendasti** [loot/loot#1839]
![image](https://user-images.githubusercontent.com/124440691/216768763-25282f79-01a6-469d-8513-675ab383e6b3.png)

**Comment by sibir-ine** [comment]
Please see [this section](https://loot.github.io/docs/help/LOOT-FAQs.html#update-masterlist-errors) of the FAQ.

**Comment by sibir-ine** [comment]
Closing due to no response in over a week. Feel free to continue the discussion if you're still experiencing the issue.
