### ISSUE TITLE
I am trying to Download masterlist manually but cant access the srver

### ISSUE THREAD

**Issue by Ragerex** [loot/loot#1841]
I am trying to download Masterfile for Skyrim manually since it is not working. But I can not reach the desirable website. Is there any problem?  
![Capture](https://user-images.githubusercontent.com/124502502/216817540-f2970db6-d495-49ac-9a82-c7283097af1d.JPG)

**Comment by pStyl3** [comment]
@Ragerex is your Internet Service Provider (ISP) by chance [Jio](https://www.jio.com/)? Apparently that ISP has blocked access to `raw.githubusercontent.com`, see [here](https://www.reddit.com/r/india/comments/zd7ykr/jio_has_blocked_rawgithubusercontentcom_again/) or [here](https://github.com/community/community/discussions/42655).

**Comment by Ragerex** [comment]
Yes, it is Jio. Ok, I'll contact my ISP soon. Thank you for the quick
response.

**Comment by sibir-ine** [comment]
@Ragerex, as an alternative, you can download the masterlist & prelude from the main pages for their respective repositories. [Here](https://github.com/loot/skyrimse)'s SSE's, & [here](https://github.com/loot/prelude)'s the prelude's. Click the green **Code** button & select **Download ZIP**. Then, just grab the `masterlist.yaml` & `prelude.yaml` file from each ZIP file, respectively, & proceed with the instructions from the FAQ you were presumably following.

**Comment by sibir-ine** [comment]
There's nothing we can do about ISPs blocking whatever site we use to host the masterlists, so I'll close this.
