### ISSUE TITLE
Loot wont update

### ISSUE THREAD

**Issue by SuppaPanda** [loot/loot#1847]
The error says 'Prelude update response errored'
[LOOTDebugLog.txt](https://github.com/loot/loot.github.io/files/10872571/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
Looks like a connection error that we can't do anything about. Can you access [this link](https://raw.githubusercontent.com/loot/prelude/v0.18/prelude.yaml) via a browser?

**Comment by sibir-ine** [comment]
Closing due to lack of response in over a week. Feel free to continue the discussion if you're still experiencing the issue.
