### ISSUE TITLE
Add ability to copy all plugin filenames in a group in Groups Editor

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1855]
[Requested](https://discord.com/channels/473542112974077963/496196499890241546/1088744599813636126) by DarkladyLexy on Discord. I imagine this could be done via an action in a context menu in the **Plugins in <group>** panel. You're already able to copy the filename of a plugin there if focused with `CTRL + C`, so an action for that could be exposed in the menu as well.

**Comment by Ortham** [comment]
Done in ae4b9d87058db8324f85e31f9dff0ed369cc7392.

**Comment by pStyl3** [comment]
The string `&Copy Plugin Names` has an ampersand `&` in front of the `C`, so it's a mnemonic shortcut. Am I right, that this string is within the same group of strings as other menu titles, e.g. `&File`, `&Game`, `&Plugin` etc?

**Comment by Ortham** [comment]
It's not in a group, as it only appears in the groups editor plugin list context menu and there are no other entries yet. I'll add a note for translators to explain this though.

**Comment by Ortham** [comment]
Done in 1447592eeb8027586ed06697bb2acd701933d8be.
