### ISSUE TITLE
My loot keeps crashing, please help.

### ISSUE THREAD

**Issue by InsaneVRGamer** [loot/loot#1859]
[LOOTDebugLog.txt](https://github.com/loot/falloutnv/files/11152689/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
For some reason, LOOT is having trouble reading `FalloutNV.exe`'s product version file metadata, though it due to lack of access:

```
[error]: Failed to evaluate condition "readable("../FalloutNV.exe") and product_version("../FalloutNV.exe", "1.4.0.525", <)". Details: An error was encountered while reading the version fields of "L:\SteamLibrary\steamapps\common\Fallout New Vegas\Data\../FalloutNV.exe": unknown magic number
[error]: Caught an exception: Failed to evaluate condition "readable("../FalloutNV.exe") and product_version("../FalloutNV.exe", "1.4.0.525", <)". Details: An error was encountered while reading the version fields of "L:\SteamLibrary\steamapps\common\Fallout New Vegas\Data\../FalloutNV.exe": unknown magic number
```

Try reinstalling Fallout: New Vegas (or verifying game file integrity through Steam) in case your installation is broken in some way.

**Comment by InsaneVRGamer** [comment]
> For some reason, LOOT is having trouble reading `FalloutNV.exe`'s product version file metadata, though it due to lack of access:
> 
> ```
> [error]: Failed to evaluate condition "readable("../FalloutNV.exe") and product_version("../FalloutNV.exe", "1.4.0.525", <)". Details: An error was encountered while reading the version fields of "L:\SteamLibrary\steamapps\common\Fallout New Vegas\Data\../FalloutNV.exe": unknown magic number
> [error]: Caught an exception: Failed to evaluate condition "readable("../FalloutNV.exe") and product_version("../FalloutNV.exe", "1.4.0.525", <)". Details: An error was encountered while reading the version fields of "L:\SteamLibrary\steamapps\common\Fallout New Vegas\Data\../FalloutNV.exe": unknown magic number
> ```
> 
> Try reinstalling Fallout: New Vegas (or verifying game file integrity through Steam) in case your installation is broken in some way.


That worked, thanks, verify did bugger all, so i deleted a few things from the new vegas folder, and basically reinstalled a bunch of its files, and it worked!

**Comment by sibir-ine** [comment]
You're welcome!
