### ISSUE TITLE
Please add support for Darkest Dungeon and Divinity Original Sin 2 Definitive Edition

### ISSUE THREAD

**Issue by ExLuck6** [loot/loot#1862]

**Comment by pStyl3** [comment]
The request to support non-Bethesda games has come up a few times in the past, as such we have been asked at different occasions to add support for Mount & Blade II: Bannerlord, Stellaris, Space Engineers & Starbound.

The answer to the question if we want to add support for Darkest Dungeon and Divinity Original Sin 2 will be the same, with the short answer being: We won't add support for them.

LOOT has been specifically designed with Bethesda games in mind, so adding support for a non-Bethesda game would entail a great commitment to the case as well as a significant amount of time to develop and test things, with no clear outline if the work succeeds or not. There's also other things to consider, like that it's not done with `adding` support .. the support will need to be maintained for ideally years to come. Who will do that? Do the different LOOT team members even own these games? And there are other implications we could think about.

Here's @Ortham's answer to one of these requests:
> My personal opinion is that it would be far more worthwhile to create a new utility for managing any non-Fallout/TES game than to try to make LOOT more general - LOOT's multi-game support works because all the games it does support are very similar (using iterations of the same engine helps), and LOOT simply isn't designed in a way that allows it to support games generically.

As such, thanks for the inquiry, but it won't happen from our side and you probably should ask in those games' communities for such modding tools.
