### ISSUE TITLE
Loot crash on start after the first time tips windows is closed 

### ISSUE THREAD

**Issue by Erynies** [loot/loot#1863]
Hello everyone ! i've quite the issue and after hours of searching i didn't find any solution. Each time that i open loot the application crashes after i close the ''First-Time Tips''. I've tried to launch with administration right, same for the installation. Tried to uninstall and delete the folder in AppData no changes too. Firewall isn't the problem too i've made an exception for the application.

I'm on windows 11, maybe the problem comes from here ? 

Anyway i attach the DebugLog here thanks in advance for your help, and sorry for the probably bad english it's not my native language 

[LOOTDebugLog.txt](https://github.com/loot/loot/files/11428110/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
Please [enable debug logging](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log) & post a full debug log.

**Comment by sibir-ine** [comment]
Try creating a `settings.toml` file there with the line `enableDebugLogging = true`.

**Comment by Erynies** [comment]
Thanks it worked :) and here you go 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/11428527/LOOTDebugLog.txt)

**Comment by Erynies** [comment]
I have never install Morrowind sadly haha (Or at least not since 15 years on my last computer XD) 

I've got GamingRoot but how can i share it ? :)

**Comment by Ortham** [comment]
> And nope no microsoft store installed on my D

In that case I think you can just delete your `D:\.GamingRoot` and see if LOOT works then.

**Comment by Erynies** [comment]
it worked !!! thanks a lot ! =D

**Comment by Erynies** [comment]
Good idea ! but it was really strange that he was persuaded that morrowind was installed haha 

Anyway, thanks a lot again :) have a great day !

**Comment by sibir-ine** [comment]
Fixed in 884cc0c58a253f79c20b5e256aabd03d493558d0.
