### ISSUE TITLE
Prevent user from entering invalid characters in LOOT Folder

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1865]
When creating a new settings profile, users can freely enter characters in `LOOT Folder` that are invalid for a path in Windows (i.e., `\/<>:"*?|`). Since the path is created when the profile is first opened in LOOT, it only causes an error then. Therefore, it'd be better to just prevent users from doing so in the first place. The only exceptions are `\` & `/` which produce profiles in nested folders instead that appear to work fine, so we may want to continue to allow them.

**Comment by Ortham** [comment]
Done in 86d05b9d157cf234a36bc0f950e0d870947dce64.

**Comment by sibir-ine** [comment]
Would it also be possible to prevent the other illegal characters? Or would it cause issues for Linux users or not be worth it in some other way?

**Comment by Ortham** [comment]
Yes, done in 315cbc6620560f58550b9082ce30d303af34f353.
