### ISSUE TITLE
Add support for the Epic distribution of Fallout New Vegas

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1867]
[FNV Ultimate Edition](https://store.epicgames.com/en-US/p/fallout-new-vegas--ultimate-edition) has been released on Epic (apparently, [FNV](https://store.epicgames.com/en-US/p/fallout-new-vegas) will be released on 6/1 on it's own) & will be free for the week. Here's the relevant info for adding support:

- EGS app name: `5daeb974a22a435988892319b3a4f476`
- AppData folder name: `FalloutNV_Epic`
- File that can be used to identify it as EGS: `EOSSDK-Win32-Shipping.dll`
- It has the same five localized folders (same names as well) as the MS version (e.g., `Fallout New Vegas English`)

**Comment by Ortham** [comment]
I've added support for the Ultimate Edition in the `fonv-egs-support` branch, I'll keep the branch open until the non-Ultimate edition is released (though I don't know why they're releasing it, it seems needlessly confusing to buyers, considering how old the game is...).

**Comment by sibir-ine** [comment]
Yeah, no clue why either. However, I noticed when checking the manifest that there are separate manifests for the base game (which is what we're using for UE) & each DLC, so I assume the non-Ultimate edition will just be the same base game.

**Comment by Ortham** [comment]
Now that the non-Ultimate edition is out, I can confirm that I see it already in my library as installed, i.e. the app name above is valid for both editions.

**Comment by Ortham** [comment]
Done as of ebe6e3b8fbe75dff8a885fcb5f572cd2c3d1e96a.
