### ISSUE TITLE
Add "Update All Masterlists" action

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1869]
@IllusiveMan196 requested the ability to update the masterlists of all of your settings profiles at once.

**Comment by Ortham** [comment]
It's not obvious to me how the results should be communicated to the user. If the user updates a single masterlist, they get a notification dialog saying if the masterlist was updated or not: what should the user see if they update multiple masterlists at the same time (if none update, if some update and if all update)?

**Comment by sibir-ine** [comment]
Maybe a summary dialog that lists each profile & the results of attempting to update its masterlist? I can't think of a good way to implement this with the status bar notifications, & displaying each notification dialog individually would probably be overwhelming to users with many games & therefore many profiles. A summary dialog seems like the best implementation.

**Comment by IllusiveMan196** [comment]
"Masterlist updated for: [insert game name depending on what games had masterlist updates]" would be sufficient. Version info is not required I think, as for what games had no updates you can use "No updates for [game names]" or not show anything at all. Should cover most games and their instances as masterlists are universal. might ned to shorten game names a bit though.

TES 3, TES 4, TES 5, TES 5 SE, TES 5 VR, FO3, FNV, FO4, FO4 VR, Nehrim, Enderal, Enderal (SE).

Lets see if this looks good:
Masterlist updated for: TES 3, TES 4, TES 5, TES 5 SE, TES 5 VR, FO3, FNV, FO4, FO4 VR, Nehrim, Enderal, Enderal (SE)

On my screen and window size it takes up 80% of window width. Manageable.

**Comment by Ortham** [comment]
I've implemented this in the `update-all-masterlists` branch, @IllusiveMan196 can you try out [this build](https://github.com/loot/loot/actions/runs/5231510756) and see what you think?

**Comment by IllusiveMan196** [comment]
> I've implemented this in the `update-all-masterlists` branch, @IllusiveMan196 can you try out [this build](https://github.com/loot/loot/actions/runs/5231510756) and see what you think?

That works and there is even space to list masterlist versions if you want to. Message is static, yes? Seeing as I don't have Enderal and Nehrim but they were listed as updated (although having them just in case doesn't really hurt).

**Comment by sibir-ine** [comment]
> If message isn't static, which it may be, as I don't have Enderal and Nehrim but their masterlists were listed as updated (having them just in case is fine).

If you navigate to LOOT's settings, do you see them there? My understanding is that it updates all settings profiles present, & I believe those are created whether you have the games or not as their masterlists are also installed via the installer.

**Comment by Ortham** [comment]
> That works as imagined and there is even space to list masterlist versions if you want to. If message isn't static, which it may be, as I don't have Enderal and Nehrim but their masterlists were listed as updated (having them just in case is fine).

> If you navigate to LOOT's settings, do you see them there? My understanding is that it updates all settings profiles present, & I believe those are created whether you have the games or not as their masterlists are also installed via the installer.

Yep, updating all masterlists updates the masterlists for all the games you have settings for.

**Comment by Ortham** [comment]
Done as of b324355a3afcb8b08374334ed68a1412f618411e.
