### ISSUE TITLE
Broken cyclic Interaction message

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1877]
I've tried to load `ccgrcfo4001-pipgreytort.esl` after `ccgrcfo4002-pipgreenvim.esl`, which results in a cyclic interaction. The displayed message in the General Information card however is getting displayed like this:

![grafik](https://github.com/loot/loot/assets/10406657/b7f6b31e-60af-4533-afca-71eed1428cb4)

Tested with `loot_0.20.0-15-g5604f5f_master-win64.7z`.

**Comment by Ortham** [comment]
Ah, I replaced the message with an escaped message by accident. Fixed in c2c2500d071ff7570cb69d2dcd8fa6363a02e0df.
