### ISSUE TITLE
Add support for Starfield

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1882]
After [Starfield](https://bethesda.net/en/game/starfield) was first announced during E3 2018, it is now scheduled to be released on the 6th of September 2023.

**Platforms:**
- Windows - [Standard Edition](https://www.xbox.com/en-US/games/store/starfield-standard-edition/9ntfm8rxljf9) | [Premium Edition](https://www.xbox.com/en-US/games/store/starfield-premium-edition/9NLGBHLSWXM8/0017)
- [Steam](https://store.steampowered.com/agecheck/app/1716740/)
- [Game Pass](https://www.xbox.com/en-US/xbox-game-pass)
- Xbox Series X|S

There might be GOG/EGS releases planned at some point, but as far as I know this hasn't been officially talked about yet.

**Minimum System Requirements:**
- OS: Windows 10 version 22H2 (10.0.19045)
- Processor: AMD Ryzen 5 2600X, Intel Core i7-6800K
- Memory: 16 GB RAM
- Graphics: AMD Radeon RX 5700, NVIDIA GeForce 1070 Ti
- DirectX: Version 12
- Storage: 125 GB available space
- Additional Notes: SSD Required

It probably might be a good idea to calculate with more than 125 GB storage space, official DLCs and mods will come on top of that.

**Videos:**
- [Announcement Teaser](https://www.youtube.com/watch?v=JUobbpHERh8)
- [Teaser Trailer](https://www.youtube.com/watch?v=pYqyVpCV-3c)
- [Gameplay Reveal](https://www.youtube.com/watch?v=zmb2FJGvnAw)
- [Starfield Direct – Gameplay Deep Dive](https://www.youtube.com/watch?v=uMOPoAq5vIA)
- [AMD is Starfield’s Exclusive PC Partner](https://www.youtube.com/watch?v=9ABnU6Zo0uA)
- [Starfield's Secret to 1000 Planets! From Lex Fridman Podcast](https://www.youtube.com/shorts/6ddI_Kt8cUg)
- [Starfield: The Settled Systems - Supra Et Ultra](https://www.youtube.com/watch?v=8Kj6wulHMsA)
- [Starfield: The Settled Systems - Where Hope is Built](https://www.youtube.com/watch?v=9trjxvaWP_0)
- [Starfield: The Settled Systems - The Hand that Feeds](https://www.youtube.com/watch?v=2mX2iDI00FM)

**Creation Engine 2**

https://twitter.com/BethesdaStudios/status/1404124165658009601
> Starfield will be our first game to use Creation Engine 2. We've spent years developing it to power the next generation of immersion and exploration.

Starfield is build using the CE 2, which is said to be vastly improved compared to it's predecessors. There are [some snippets of information](https://www.starfielddb.com/creation-engine-2/) floating around, but not much is known until now. We should very carefully observe everything around the CE 2, since it might mean that there are substantial differences in regards to load order as well.

Of course, besides updating the LOOT application itself, a new masterlist will need to be created, too.

**Closing Thoughts:**
I bought the *Digital Premium Edition* from Steam, as such I will have early access to it 5 days prior to the official release, and I will also get the first planned story expansion, aka DLC "Shattered Space". For testing purposes, it might be good to have a few people owning the game through the Microsoft Store, any help on this front will be welcome!

Let's see how the game will perform and get received, I'm looking forward to it.

**Comment by pStyl3** [comment]
[Starfield has gone gold](https://twitter.com/BethesdaStudios/status/1691827163299754093)

> Starfield has gone gold! Preloads begin tomorrow for [@Xbox](https://twitter.com/Xbox)
 X|S and Windows PC and August 30 for Steam.

People have started preloading the game now, and while the files are still encrypted, the files within Starfield's `game` folder (within this "preloaded state") are:
> \Config
\D3D12
\Data
\media
appxmanifest.xml
bink2w64.dll
CreationKitTooltips.ini
DefaultGlobalGraphicsSettings.json
gamelaunchhelper.exe
High.ini
layout_ff5f9afb-a689-44d8-85cd-06cf9139122e.xml
Low.ini
Medium.ini
MicrosoftGame.Config
resources.pri
ssce5564.dll
Starfield.exe
Starfield.ini
Starfield_it.ini
Starfield_pl.ini
Starfield_ptbr.ini
Starfield_zhhans.ini
Ultra.ini
XCurl.dll

The files within the `Data` folder are also known, though in order to avoid potential spoilers, I'm only listing the files that are relevant for us:
> Starfield.esm
BlueprintShips-Starfield.esm
BlueprintShips-Starfield - Localization.ba2
Constellation.esm
Constellation - Localization.ba2
Constellation - Textures.ba2
OldMars.esm
OldMars - Localization.ba2
OldMars - Textures.ba2

A such the `.esm` plugin format as well as the `.ba2` archive format will continue to be used.
It remains to be seen, if they have been updated for Starfield in any way, shape or form.

**Comment by Ortham** [comment]
I've taken a look through the code to see what questions need to be answered for Starfield support:

- [ ] Is plugin load order even relevant to Starfield? (probably)
- [ ] What is Starfield's minimum plugin header version?
- [ ] What (if any) generic Registry key install path value gets created by Starfield?
- [ ] Does the Steam install path contain an `installscript.vdf` file?
- [ ] What is Starfield's app name on the Microsoft Store?
- [ ] What local app data folder name does the Steam version of Starfield use?
- [ ] Does Starfield support light plugins?
  - [ ] If Starfield supports light plugins, what is their valid object index range?
- [ ] Does Starfield support .esl plugins?
- [ ] What are the rules for what plugins load what BA2 archives?
- [ ] How is load order stored in Starfield?
- [ ] How does Starfield keep track of which plugins are active?
- [ ] Which plugins are hardcoded to load?
- [ ] What is the structure of Starfield's plugin file format? (Judging by file extensions it'll be similar to the other games)
  - [ ] Are records and groups arranged like in all games after Morrowind?
  - [ ] Is the plugin header record still TES4?
  - [ ] Does the plugin header record still have an SNAM subrecord that holds the plugin description?
  - [ ] Does the plugin header record still have a record and group count subdrecord, and if so which is it?
  - [ ] How long is the record header, and what is its structure?
  - [ ] How are large subrecords handled in Starfield?

Thanks to Pickysaurus from Nexus Mods I now have a copy of Starfield on Steam and a copy from the Microsoft Store through a 3-month Game Pass subscription, so I'll be able to get answers to these questions myself. I expect that most will be fairly straightforward to answer, the plugin file format questions will probably need a little trial-and-error parsing to check assumptions. It may be tricky to work out the ins and outs of how load order works, but the basics should be obvious with a little testing.

**Comment by pStyl3** [comment]
**Steam version**

![grafik](https://github.com/loot/loot/assets/10406657/8673a6b0-8695-4481-9d81-c07d5dbe3992)
Version of Starfield.exe: `1.7.23.0`

> Does the Steam install path contain an `installscript.vdf` file?

It doesn't seem so.

**Comment by pStyl3** [comment]
`C:\Users\USER\AppData\Local\<game>` usually includes `plugins.txt`.

For Starfield - `C:\Users\USER\AppData\Local\Starfield` - contains only a single file for me:
`Pipeline.cache`

It's size is around 62 MB and it can't be opened with a simple text editor.

**Comment by pStyl3** [comment]
Viewing `Starfield.esm` with a hex editor suggests, that both `TES4` as well as `SNAM` continue to be there.

**Comment by pStyl3** [comment]
While viewing `Starfield.exe` with a hex editor and searching for `.esm` will find these entries:
> .ESM
TestData.esm
Starfield.esm
BlueprintShips-Starfield.esm
Constellation.esm
OldMars.esm

Searching for `.esp` will find:
> .ESP
.esp

Searching for `.esl` will find:
> .ESL

**Comment by pStyl3** [comment]
I've playing a bit with console commands. In `C:\Users\USER\Documents\My Games\Starfield` there is a `StarfieldConsoleHistory.log` file that logs every console command input.

In FO4, you could use
```
ShowGlobalVars
GetGlobalValue <var>
```
where `<var>` was one of the listed variables of `ShowGlobalVars` and it would return the correct value.

I'm currently unable to replicate this behaviour in Starfield. While `ShowGlobalVars` works, using `GetGlobalValue <var>` afterwards results in the following message:
```
Item '<var>' not found in parameter Global.
Compiled script not saved!
```

On the other hand
```
player.getvalue luck
player.setvalue Luck 2
```
worked, and using another `player.getvalue luck` afterwards returned `2` as the result, while before it was `1`.

**Comment by Geeknasty** [comment]
> In FO4, you could use
> 
> ```
> ShowGlobalVars
> GetGlobalValue <var>
> ```
> 
> where `<var>` was one of the listed variables of `ShowGlobalVars` and it would return the correct value.
> 
> I'm currently unable to replicate this behaviour in Starfield. While `ShowGlobalVars` works, using `GetGlobalValue <var>` afterwards results in the following message:
> 
> ```
> Item '<var>' not found in parameter Global.
> Compiled script not saved!
> ```


I was able to use `GetGlobalValue <var>` to work by using the FormID value of the global variables instead of the EditorID.

So instead of `GetGlobalValue Locklevel_Novice` I would use `GetGlobalValue AEF4F`

**Comment by pStyl3** [comment]
[Starfield Default Values for All Known Valid INI Settings](https://stepmodifications.org/forum/topic/19019-starfield-default-values-for-all-known-valid-ini-settings/) compiled by @DoubleYouC
In case we want to make use of some of these settings.

**Comment by Ortham** [comment]
In Process Monitor it looks like Starfield also looks for some files (including plugins and BA2 files) under `%USERPROFILE%\Documents\My Games\Starfield`, e.g.

```
%USERPROFILE%\Documents\My Games\Starfield\Data\Starfield.esm
%USERPROFILE%\Documents\My Games\Starfield\DATA\DATA\Starfield.esm
%USERPROFILE%\Documents\My Games\Starfield\Data\Starfield.ccc
%USERPROFILE%\Documents\My Games\Starfield\Starfield.ccc

%USERPROFILE%\Documents\My Games\Starfield\DATA\Data\Constellation - Localization.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\Constellation - Localization.ba2
%USERPROFILE%\Documents\My Games\Starfield\DATA\Data\Constellation - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\Constellation - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\Constellation - Voices_en.ba2
%USERPROFILE%\Documents\My Games\Starfield\Constellation - Voices_en.ba2

%USERPROFILE%\Documents\My Games\Starfield\DATA\Data\OldMars - Localization.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\OldMars - Localization.ba2
%USERPROFILE%\Documents\My Games\Starfield\DATA\Data\OldMars - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\OldMars - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\OldMars - Voices_en.ba2
%USERPROFILE%\Documents\My Games\Starfield\OldMars - Voices_en.ba2

%USERPROFILE%\Documents\My Games\Starfield\DATA\DATA\test.esm
%USERPROFILE%\Documents\My Games\Starfield\Data\test.esm

%USERPROFILE%\Documents\My Games\Starfield\Data\BlueprintShips-Starfield - Main.ba2
%USERPROFILE%\Documents\My Games\Starfield\BlueprintShips-Starfield - Main.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\BlueprintShips-Starfield - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\BlueprintShips-Starfield - Textures.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\BlueprintShips-Starfield - Voices_en.ba2
%USERPROFILE%\Documents\My Games\Starfield\BlueprintShips-Starfield - Voices_en.ba2
%USERPROFILE%\Documents\My Games\Starfield\Data\BlueprintShips-Starfield - Localization.ba2
```

It's hopefully not using %USERPROFILE% to resolve the path, IIRC there's a folder ID for getting the My Games path, but I can't remember what it's called. I imagine it's using that, so it's not necessarily at `%USERPROFILE%\Documents\My Games`, but I'm not going to mess with my user account to find out.

Other observations from Process Monitor:

- It looks like the game looks for each BA2 in My Games before the install path. E.g. `My Games\Starfield\DATA\Data\OldMars - Textures.ba2`, then `steamapps\common\Starfield\DATA\Data\OldMars - Textures.ba2`, then `My Games\Starfield\Data\OldMars - Textures.ba2`, then `steamapps\common\Starfield\Data\OldMars - Textures.ba2`.
- `Starfield.ccc` is searched for at `My Games\Starfield\Data\Starfield.ccc`, then `steamapps\common\Starfield\Data\Starfield.ccc`, then `My Games\Starfield\Starfield.ccc`, then `steamapps\common\Starfield\Starfield.ccc`.
- `OldMars.esm` (and other plugins) is searched for at `My Games\Starfield\DATA\DATA\OldMars.esm` then `steamapps\common\Starfield\DATA\DATA\OldMars.esm`, then `My Games\Starfield\Data\OldMars.esm`, then `steamapps\common\Starfield\Data\OldMars.esm`.
- `test.esm` is a plugin I've created to test loading from plugins.txt. It's in the game install's Data folder, and even without it listed in plugins.txt the game still looks for it in the same folders as the other plugins.
- `BlueprintShips-Starfield - Main.ba2` is the only `Main`-suffixed BA2 that's searched for. There's a block in Starfield.exe that is: `Textures.ba2� - Main.ba2�.ba2�������� - Voices_��` (all the question marks are nulls). `Main.ba2` also appears later in the executable in `Starfield - Animations.ba2������Main.ba2�`. `Localization` appears in the block `- Localization��%s*.ba2�- Main.�- Textures.�` 
- The `Voices_<language>` language value comes from the `Starfield.ini` (and language-specific ini files)'s `sLanguage` property. It's not set in `Starfield.ini`, `sLanguage=en` is the implied default, but e.g. in the German ini file it's `sLanguage=de`, and if I add it to `Starfield.ini` I see the in-game language changes and the relevant BA2 files are opened.

**Comment by Ortham** [comment]
I've been able to handmake a plugin that changes the name of the "Eon" pistol: it's FormID `000476C4`, and the name is the first `FULL` subrecord in the record. It's a localised string by default, so I set the TES4 header's flags so that `0x80` was not set and then edited the field to a 3-letter name (as its original value is a 4-byte localised string index, and I didn't want to mess with offsets/sizes).

However, I'm only able to see the change in-game when I replace one of the hardcoded plugins (e.g. `OldMars.esm` with my plugin. Enabling the `TestData.esm` plugin might also work, but I don't think that approach would really tell me anything new.

I also haven't been able to create a new record (not one that just overrides one in Starfield.esm) and have that show up in game, and none of the records added by `OldMars.esm` or `Constellation.esm` seem to be inventory items (which are easy to spawn in using `player.additem`), so I've so far been unable to check what the hardcoded load order is.

**Comment by Ortham** [comment]
Interesting... I created a copy of the Eon pistol's record and gave it a different EDID value (ZVP - again I only had 3 bytes to play with) and a FormID of `01FFFFFF`, and then used `FindForm` in-game, and it said the FormID was `FE001FFF`. The plugin's TES4 flags were `0x101`. When I change the flags to `0x0` or `0x1` the in-game FormID is `01FFFFFF`, and when the flag is `0x100` it's `FE001FFF` again. If I keep the flag at `0x100` and change the FormID to `01000000`, it shows in-game as `FE001000`.

So it looks like:

- the light plugin flag is `0x100` in this game, not `0x200`
- the valid object ID range for light plugin records is `0x0` to `0xFFF`.

I then changed the first instance of `OldMars.esm` in `Starfield.exe` to `OldMars.esl` and renamed by test plugin to match, clearing its TES4 flags, and when loading my save game Starfield prompted about mods being loaded causing achievements to be disabled, but FindForm did not find my new record. I then changed its FormID back to `01FFFFFF`, but it still wasn't found. I then also changed the second instance of `OldMars.esm` in `Starfield.exe`, but that made no difference. 

I'm not sure what to draw from this, as despite changing both strings the game recognised that the plugins it was trying to load weren't the usual official plugin names, but then loading seems to have failed as the changes weren't visible in-game (not just my new pistol, but also the edit to the Eon didn't show up). I'm not sure this says much about plugin loading in general either, as the official plugins may well go through a different path to the rest.

**Comment by Ortham** [comment]
I renamed `Starfield - Meshes01.ba2` to test out what happened when I tried loading a save with it using different filenames, and:

- `OldMars - Meshes01.ba2`: crash
- `OldMars - Main.ba2`: crash
- `OldMarsTextures.ba2`: crash
- `OldMars - Voices_fr.ba2`: crash (with language set to English)
- `OldMars.ba2`: crash
- `OldMars - Textures.ba2`: success
- `OldMars - Localization.ba2`: success
- `OldMars - Voices_en.ba2`: success (with language set to English)

That's pretty much what I was expecting, except `OldMars.ba2` not getting loaded.

**Comment by Infernio** [comment]
aers on the RE discord confirmed that `.esl` still forces the master flag.

**Comment by Ortham** [comment]
aers on the SkyrimSE RE discord has also found that the 0x200 TES4 flag (which was previously the light plugin flag) now suppresses the light plugin flag being set for plugins with a .esl extension (but doesn't do anything if that flag is already set in the file). [Here](https://discord.com/channels/535508975626747927/1144803661034299443/1148092887536517200) is where most of the discussion starts.

The logic (as written by Elminster) boils down to:

```
if the 0x200 flag is set then begin
  if there is no master list, or the 0x100 flag is set then
    remove the 0x200 flag
end else
  if the extension is .esl then
    force 0x100 flag
```

I should update esplugin to account for this behaviour, so that plugins don't get treated as light when the flag is suppressed.

**Comment by aers** [comment]
> It's hopefully not using %USERPROFILE% to resolve the path, IIRC there's a folder ID for getting the My Games path, but I can't remember what it's called. I imagine it's using that, so it's not necessarily at `%USERPROFILE%\Documents\My Games`, but I'm not going to mess with my user account to find out.

It uses ShGetFolderPathA to resolve the user's personal Documents folder, so yes it will work no matter where it is located.

**Comment by Ortham** [comment]
> It uses ShGetFolderPathA to resolve the user's personal Documents folder, so yes it will work no matter where it is located.

Thanks, I was thinking of `SHGetKnownFolderPath`, and I thought there was a FOLDERID for My Games but it looks like I was wrong, there's only `FOLDERID_SavedGames`.

**Comment by Ortham** [comment]
@aers I ran those tests you suggested:

```

One plugin:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

In-game:
- the Eon (000476C4) is renamed ESM.
- FindForm ZVM returns 02FFFFFF

---

One plugin:

test.esm
Flags: 0x200
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

In-game:
- the Eon (000476C4) is renamed ESM.
- FindForm ZVM returns 00FFFFFF

---


One plugin:

test.esl
Flags: 0x200
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

In-game:
- the Eon (000476C4) is renamed ESM.
- FindForm ZVM returns 00FFFFFF

---

Two plugins:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test.esl
Flags: 0x200
Master: test.esm

Records:
- FormID: 00FFFFFF, EDID: ZVL, FULL: ESL
- FormID: 01FFFFFF, EDID: YVL, FULL: ZVL

Loaded sTestFile1=test.esm, sTestFile2=test.esl

In-game:
- the Eon (000476C4) is renamed ESM.
- FindForm ZVM returns nothing
- FindForm ZVL returns nothing
- FindForm YVL returns 02FFFFFF

---


Two plugins:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test2.esm
Flags: 0x200
Master: Starfield.esm

Records:
- FormID: 000476C4, EDID: Eon, FULL: ES2
- FormID: 01FFFFFF, EDID: ZV2, FULL: ZV2

Loaded sTestFile1=test2.esm, sTestFile2=test.esm

In-game:
- the Eon (000476C4) is renamed ES2.
- FindForm ZVM returns 02FFFFFF
- FindForm ZV2 returns 00FFFFFF
```

**Comment by Ortham** [comment]
Doing some more testing to understand the game's behaviour with the 0x200 flag:

```
Two plugins:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test_starfield_dependent.esm
Flags: 0x200
Masters: Starfield.esm, test.esm

Records:
- FormID: 01FFFFFF, EDID: ZVL, FULL: ESL
- FormID: 02FFFFFF, EDID: YVL, FULL: YVL

Loaded sTestFile1=test.esm, sTestFile2=test_starfield_dependent.esm

In-game:
- the Eon (000476C4) is renamed ESM
- FindForm ZVM returns nothing
- FindForm ZVL returns 02FFFFFF
- FindForm YVL returns 00FFFFFF
```

That makes sense to me: ZVL overrides ZVM, so doesn't use up a new mod index, while YVL is a new record that gets squashed down to Starfield.esm's mod index. Is it squashing down to Starfield.esm's mod index though, or the mod index of the first master listed?

```
Two plugins:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test_starfield_dependent.esm
Flags: 0x200
Masters: test.esm, Starfield.esm

Records:
- FormID: 00FFFFFF, EDID: ZVL, FULL: ESL
- FormID: 02FFFFFF, EDID: YVL, FULL: YVL

Loaded sTestFile1=test.esm, sTestFile2=test_starfield_dependent.esm

In-game:
- the Eon (000476C4) is renamed ESM
- FindForm ZVM returns nothing
- FindForm ZVL returns nothing
- FindForm YVL returns 02FFFFFF
```

This gets the same result as the last test case in my previous comment, and what's common between them is that the first master is not `Starfield.esm`. I was expecting ZVL to be 02

ZVM should have mod index 02, but it and ZVL have vanished and YVL has mod index 02. I think what's happened is that ZVM was overridden by ZVL, but they were both overwritten by YVL, because all three have the same FormID.

```
test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test_starfield_dependent.esm
Flags: 0x200
Masters: test.esm, Starfield.esm

Records:
- FormID: 02FFFFFE, EDID: ZVL, FULL: ESL
- FormID: 02FFFFFF, EDID: YVL, FULL: YVL

Loaded sTestFile1=test.esm, sTestFile2=test_starfield_dependent.esm

In-game:
- the Eon (000476C4) is renamed ESM
- FindForm ZVM returns nothing
- FindForm ZVL returns 02FEFFFF
- FindForm YVL returns 02FFFFFF
```

Here ZVL and YVL are both new records that have been squashed down into test.esm's mod index, and ZVM no longer exists because it's been overwritten (not overridden) by YVL.

```
Two plugins:

test.esm
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

test_starfield_dependent.esm
Flags: 0x200
Masters: test.esm, Starfield.esm

Records:
- FormID: 00FFFFFF, EDID: ZVL, FULL: ESL
- FormID: 02FFFFFE, EDID: YVL, FULL: YVL

Loaded sTestFile1=test.esm, sTestFile2=test_starfield_dependent.esm

In-game:
- the Eon (000476C4) is renamed ESM
- FindForm ZVM returns nothing
- FindForm ZVL returns 02FFFFFF
- FindForm YVL returns 02FFFFFE
```

Here YVL uses a different object index from ZVM/ZVL, so ZVL overrides ZVM as expected, and YVL squashes into test.esm as expected.

**Comment by Ortham** [comment]
I think I've got everything I need to add support for Starfield to esplugin and loot-condition-interpreter, and to libloot itself. However, as I've been so far unable to figure out how to get the game to load non-hardcoded plugins without using ini settings, I can't complete support in libloadorder.

It looks like adding support for Starfield will involve a couple of breaking changes to libloot's API, so I might just assume that Starfield uses the same load order system as Skyrim SE and Fallout 4 so that I can include the breaking changes in the next libloot release - I don't have any reason to expect figuring out the load order system to involve breaking API changes in libloot or libloadorder, so it would be easier to patch in any corrections later.

Aside from basic functionality, it would be good to support:

- [ ] Loading plugins and archives from My Games before looking in the install path (but I think it would be premature to add support for reading Starfield.ccc from there, as it may end up elsewhere).
- [ ] Displaying an error message for invalid override plugins (i.e. plugins that set the 0x200 flag but contain new records).

**Comment by TechAngel85** [comment]
> I think I've got everything I need to add support for Starfield to esplugin and loot-condition-interpreter, and to libloot itself. However, as I've been so far unable to figure out how to get the game to load non-hardcoded plugins without using ini settings, I can't complete support in libloadorder.

I don't know if this will be helpful, but Elminster mentioned in the Starfield Discord that it's likely Bethesda has blocked or commented out the code for loading plugins.txt. It looks like it's still present, just block off; likely until an official update for "mod support".

**Comment by Ortham** [comment]
> I don't know if this will be helpful, but Elminster (xEdit dev) mentioned in the Starfield Discord that it's likely Bethesda has blocked or commented out the code for loading plugins.txt. It looks like it's still present, just block off; likely until an official update for "mod support".

I'm already aware, I've been talking to him saying the same sort of thing, though what you've said isn't quite correct: the game does read plugins.txt, but we don't yet know what it does with the contents. I've got the code open in in a disassembler, but I've been avoiding it (I don't enjoy reading assembly).

**Comment by pStyl3** [comment]
[Starfield Repository](https://github.com/loot/starfield)
The first few commits have been made and Starfield's `masterlist.yaml` has been created.
@MacSplody @sibir-ine @Sabre142 I'd appreciate it, if you could take a look. 😄

**Comment by Ortham** [comment]
Correction about BA2 loading: if I've got `sTestFile1=test.esm` in my ini file, the game will attempt to load `test - Main.ba2`. Using the same test setup as [earlier](https://github.com/loot/loot/issues/1882#issuecomment-1704358534) I've verified that this does load assets successfully. I went back and tested `OldMars - Main.ba2` and that actually works, so I've updated that test result above (I must have had a typo in the BA2 name or something like that).

**Comment by Ortham** [comment]
Another test case checking if the 0x200 flag affects the master flag getting set for a .esm plugin:
```
Two plugins:

test.esp
Flags: 0x0
Master: Starfield.esm

Records
- FormID: 000476C4, EDID: Eon, FULL: ESP
- FormID: 01FFFFFF, EDID: ZVP, FULL: ZVP

test.esm
Flags: 0x200
Masters: Starfield.esm

Records:
- FormID: 000476C4, EDID: Eon, FULL: ESM
- FormID: 01FFFFFF, EDID: ZVM, FULL: ZVM

Loaded sTestFile1=test.esp, sTestFile2=test.esm

In-game:
- the Eon (000476C4) is renamed ESP
- FindForm ZVM returns 00FFFFFF
- FindForm ZVP returns 03FFFFFF
```

So the master flag is still applied. I renamed test.esm to test.esl and got the same results.

**Comment by Ortham** [comment]
I've been slowly making my way through the disassembly for some of the `Starfield.exe` code that uses the `%sPlugins.txt` string that's hardcoded in `Starfield.exe`, and I'm pretty confident that it's using the same format of `plugin.txt` as in Skyrim SE and Fallout 4: lines beginning with `#` are skipped, and lines beginning with `*` are treated differently. I've identified one function that cuts off any leading `*` before doing something with the rest of the line, and another function that only does stuff for lines that begin with `*`. I haven't figured out what is done in either case, but it seems likely that the `*` is still used to indicate an active plugin. I haven't yet spotted anything that would explain why listing plugins in `plugins.txt` doesn't seem to have any impact in-game.

**Comment by Ortham** [comment]
Now that my Game Pass copy of Starfield has unlocked, I've started it up and gotten past character creation then made a save, and taken a look at what files were accessed where:

- `My Games/Starfield` was used for loading plugins and BA2s and `Starfield.ccc` as in the Steam version
- `%LOCALAPPDATA%\Starfield\Plugins.txt` was opened

Weirdly, although I made a save and loaded it, I can't find it anywhere, and ProcMon doesn't show any .sfs file accesses.

**Comment by pStyl3** [comment]
[BGS Discord](https://discord.com/channels/784542837596225567/1149031917111492608/1149031943699169372)

> **Cartogriffi**
Hi folks, with Starfield launched we’re opening a dedicated channel for discussing Starfield Mods. 
Official mod support is planned for the future, and we look forward to sharing more details. There is no ETA on when this will be, but keep an eye on this channel and `#⁠modding-news`!

And according to the following [japanese news article](https://www.famitsu.com/news/202309/06315728.html) - the section that includes `Mod` within the question:
> Will we be able to place new creatures and other things on the planet with the mod?
> 
> Todd:
When we can do mods, we'll be able to do almost anything we've done in the past, and the mods will be supported next year, but we'll do it in a big way because we love it too.

(DeepL translation)

**Comment by pStyl3** [comment]
Starfield has received it's first post-launch patch - [Link](https://steamdb.info/patchnotes/12128396/)
The version of `Starfield.exe` has been bumped from `1.7.23.0` to `1.7.29.0`.

**Comment by 3ventic** [comment]
>  What local app data folder name does the Microsoft Store version of Starfield use?

Microsoft Store version of the game also uses `%LocalAppData%\Starfield`

**Comment by Ortham** [comment]
> > What local app data folder name does the Microsoft Store version of Starfield use?
> 
> Microsoft Store version of the game also uses `%LocalAppData%\Starfield`

Thanks, I'd already got an answer for this one (I've got Game Pass), but forgot to tick it off, sorry!

**Comment by pStyl3** [comment]
A new Patch is available - [Notes](https://store.steampowered.com/news/app/1716740/view/3741984674874067188?l=english)
The new version of `Starfield.exe` is `1.7.33.0`.

**Comment by Ortham** [comment]
While Starfield.exe looks for Starfield.ccc, plugins listed in it aren't currently loaded, same as plugins.txt.

I've just finished adding support for reading sTestFile<N> ini properties to libloadorder, which is used by other games and is also currently the only way to load plugins for Starfield, but I don't intend to support changing those ini property values (they're also only used to activate plugins, not set load order).

**Comment by pStyl3** [comment]
Considering that
* the normal way to load a plugin in Starfield is currently "disabled"
* we don't know how to enable or disable plugin loading via `plugins.txt` yet
* that it could take potentially months until Bethesda enables it

How about adding a basic ("view only") support for Starfield to LOOT? As in, you can select the game, see plugins that are found in the `Data` folder, you can even try to sort your load, but the sorting result get's either dismissed automatically, or the load order is written to some sort of temporary file e.g. `order.txt` (so that it doesn't get confused with `plugins.txt`)? Or diable the ability to sort the Starfield load order to begin with.

And ss soon as loading plugins via `plugins.txt` works, we can also activate it in LOOT.

Just some ideas ..

**Comment by Ortham** [comment]
> How about adding a basic ("view only") support for Starfield to LOOT?

Yeah, that's the direction I'm heading in, I've got it so that libloadorder will error if you try to save changes, so I was going to disable the apply changes button in LOOT, but thinking about it again, disabling sorting entirely makes more sense since you can't do anything with the results.

**Comment by pStyl3** [comment]
This is what LOOT using `loot_0.20.0-99-gb743ba8_starfield-win64.7z` looks like after starting LOOT with the plugins mentioned [here](https://github.com/loot/starfield/issues/8), so no sorting until now.

![snip1](https://github.com/loot/loot/assets/10406657/e9f49148-ca9a-4281-91ed-3e55e3253fa4)

I think it's great that LOOT immediately informs the users about things like header versions being lower than the game's minimum header version.

The ability to sort currently enables me to see the CRC32 values of all the different plugins, as well as if LOOT detects plugins to be invalid:

![snip2](https://github.com/loot/loot/assets/10406657/6d72f950-8607-44e1-94be-cae5578c9446)

These information are nice to have and we would miss out on them for Starfield, as long as sorting would be disabled. But I think it would be okay, given the circumstances. Starfield being recognized by LOOT and the ability to see the plugins (and potential messages for them) seems like a good first step.

**Comment by Ortham** [comment]
@pStyl3 It's not obvious, but you get CRC calculation and full plugin parsing if you use the conflict filter.

**Comment by pStyl3** [comment]
True. Seems like I haven't used the conflict filter for quite some time. 😄 Well, then all the more reason to disable sorting for Starfield, until loading plugins via `plugins.txt` is working.

**Comment by Ortham** [comment]
I've disabled sorting and checking for ambiguous load orders when the current game is Starfield, as in both cases there's nothing the user can do with the result, and I've updated the warning message displayed for Starfield to reflect this.

In other news, I've hit an issue with implementing support for the `sTestFile1` through `sTestFile10` ini properties: Starfield supports them being defined in the `Starfield_<language>.ini` (e.g. `Starfield_en.ini`) file for the current language, but figuring out which is the current language is not straightforward:

- For Steam installs, the language is set in Steam's game properties, and is stored in the game's appmanifest ACF file, so libloadorder needs to parse that and map it to the appropriate language code (I think the game gets it through the Steam API DLL). I've gotten that working thanks to a parser library for the file format, though it doesn't seem particularly high quality or well maintained, so I'm not sure I want to go ahead with depending on it.
- For Microsoft Store installs, the language is taken from your Windows system configuration. Unfortunately, it's not clear what config is relevant or what OS languages/locales are supported, in part because I've found that [Bethesda's instructions for setting the language](https://help.bethesda.net/#en/answer/62401) don't actually work...

The `Starfield_<language>.ini` is one of three ini files you can use to set `sTestFile<N>`, and is not a likely choice (if Bethesda are going to set `sTestFile<N>` in a future update, it'll probably be in `Starfield.ini`, and a user would probably use `StarfieldCustom.ini`), so I might just ship without support for it and leave it as a todo for some other time.

**Comment by Ortham** [comment]
Also, I've intentionally limited support in libloadorder so that it will ignore plugins.txt and Starfield.ccc since the game doesn't currently activate plugins listed in those files if they exist.

**Comment by Infernio** [comment]
Nukem has posted an SFSE plugin that enables `plugins.txt` support: https://www.nexusmods.com/starfield/mods/4157

**Comment by Ortham** [comment]
@Infernio Do you know where (if anywhere) the source code is available for that?

**Comment by Ortham** [comment]
Done as of 9dbc06f26e707d23600511feba13d2fd83243761.
