### ISSUE TITLE
Display message if no supported games have been found

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1887]
If LOOT can't find any of it's supported games on startup, LOOT will look like this:

![grafik](https://github.com/loot/loot/assets/10406657/aad68780-d540-41c0-8620-1ebd4df9c05a)

This can be confusing, because we currently do not convey to the user, what the underlying problem might be.

Therefore it would be great, if we could introduce a dedicated error message for this, that explains the situation. Perhaps the message could also include some generalised advise on how to fix the problem.

**Comment by sibir-ine** [comment]
The messages display in v0.19.1, so this appears to be a bug.

**Comment by pStyl3** [comment]
You are talking about these messages, right?

![grafik](https://github.com/loot/loot/assets/10406657/b44d2dca-b7bd-4460-b2c3-e2ae0899af29)

That's not my screenshot, it's from Discord ([Link](https://discord.com/channels/473542112974077963/473542230095822848/1076637948407185548)). You are right that these should get displayed. I still think, that adding a notice on how the problem could be fixed would be nice to have here. Something along the lines of

*For the game you want to use LOOT for, start it's game launcher (e.g. press "Play" from within Steam) in order for the game to add it's entry to the registry.*

Or something similiar.

**Comment by sibir-ine** [comment]
> You are talking about these messages, right?

Yes, I've edited my comment for clarification. I thought you were just reporting the fact that the errors no longer render correctly, I didn't realize you were also suggesting improvements to them.

**Comment by Ortham** [comment]
The blank messages were fixed as of 5fd95062087535b4df48c1bf46034f222ba40c49.

@sibir-ine @pStyl3 how's this for improving the error message?

![image](https://github.com/loot/loot/assets/2430738/fc1c59f5-992f-43ed-a36c-06f3e9911cb6)

**Comment by sibir-ine** [comment]
> The blank messages were fixed as of [5fd9506](https://github.com/loot/loot/commit/5fd95062087535b4df48c1bf46034f222ba40c49).

My bad, forgot to check the latest snapshot with the device I was testing on.

> how's this for improving the error message?

Looks good to me. The only suggestion I have is to say restarting instead of re-running.

**Comment by pStyl3** [comment]
I agree with sibir's viewpoint & suggestion. Would this message replace the old messages, or be shown in addition?

**Comment by Ortham** [comment]
> I agree with sibir's viewpoint & suggestion. Would this message replace the old messages, or be shown in addition?

It replaces the old messages.

**Comment by pStyl3** [comment]
Alright, seems good to me then. The new message is definitely more user friendly.

**Comment by Ortham** [comment]
OK, done in 368e07b819995b3dfb1a3d55fc24fe33669f544e.
