### ISSUE TITLE
Add support for detecting GOG's distribution of Fallout 4

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1894]
Store page [here](https://www.gog.com/en/game/fallout_4_game_of_the_year_edition), DB page [here](https://www.gogdb.org/product/1998527297). There are two relevant IDs: 1998527297 for the game and 1408237434 for the high-res texture pack.

As well as adding the IDs to game detection, this might need a libloadorder update if the game's local app data folder name is different from the Steam name (which is true for Skyrim SE).

I've bought the game, it's currently downloading.

**Comment by sibir-ine** [comment]
I read on the xSE Discord that the executable wasn't recompiled, so the current version of F4SE should work with GOG FO4. If someone could confirm, I'd appreciate it.

**Comment by pStyl3** [comment]
I've also bought the game and have it installed via the offline installer files (so not through GOG Galaxy).

Here's the `game` folder:
![grafik](https://github.com/loot/loot/assets/10406657/621a9ab5-8e34-4d74-a18e-2279ef8708bf)

**Comment by Ortham** [comment]
@pStyl3 can you confirm that this build works with your GOG FO4? https://github.com/loot/loot/actions/runs/5900030076

**Comment by pStyl3** [comment]
Installed `loot_0.20.0-37-g1a424d7_fo4-gog-win64.7z` and deleted `%localappdata%\LOOT`, then started LOOT successfully.

Opening the games dropdown menu shows all 3 instances of FO4 that I have installed.
![grafik](https://github.com/loot/loot/assets/10406657/91d865cc-0f7f-4a5a-926d-6df68bc789bd)

After switching to the Steam installation and updating the masterlist, I've got the following error:
> [10:14:02.172386] [trace]: Sending a prelude update request to GET https://raw.githubusercontent.com/loot/prelude/v0.18/prelude.yaml
[10:14:02.210038] [error]: Network error code 2, description is: Connection closed
[10:14:02.210118] [trace]: Finished receiving a response for prelude update
[10:14:02.210147] [error]: Error while checking for LOOT updates: unexpected HTTP response status code: 0. Response body is: 
[10:14:02.245601] [error]: Caught an exception: invalid vector subscript

The first time I get the prelude error. And I don't think that I have seen the `exception: invalid vector subscript` line before.

**Comment by pStyl3** [comment]
Switching to FO4's GOG installation & then updating the masterlist worked.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/12377172/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
> The first time I get the prelude error. And I don't think that I have seen the `exception: invalid vector subscript` line before.

The good news is you got an exception instead of undefined behaviour, but the bad news is that it's hard to tell where exactly it was thrown from. It's probably something like some code assuming that the prelude update succeeded and trying to access the result.

**Comment by pStyl3** [comment]
I've installed a bunch of mods directly in the `Data` folder, and refreshed LOOTs content afterwards (I've had it open beforehand). The plugins showed up in LOOT & sorting & appling the new load order worked.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/12385861/LOOTDebugLog.txt)

![grafik](https://github.com/loot/loot/assets/10406657/d4ff1e3d-754d-4470-8e46-b0e1ce7c81f9)

**Comment by Ortham** [comment]
Done in 489ab57b6af9e0bbead52683ddcb72b8c9b7b761.
