### ISSUE TITLE
LOOT not detecting Fallout NV

### ISSUE THREAD

**Issue by CallousCourier** [loot/loot#1906]
LOOT only detects Fallout 4 and I can't delete Fallout 4 from LOOT or get it to detect Fallout NV. I tried to get it to identify manually but I don't know what to put for install path or appdata path.

**Comment by sibir-ine** [comment]
See the [FAQ](https://loot.github.io/docs/help/LOOT-FAQs.html#game-not-detected) to get LOOT to automatically or manually detect it. The install path is just the file path to the game, specifically, the folder containing the game's executable & `Data` folder (e.g., `C:\Steam\steamapps\common\Fallout New Vegas\`, it may be different for you).
