### ISSUE TITLE
feature req: manual install of masterlist

### ISSUE THREAD

**Issue by nutpantz** [loot/loot#1909]
my gaming machine is quite old and somewhat outdated, so its not on the internet
which is not needed for fallout 3,nv 4, or skyrim oblivion etc  
 
so it would be nice to have an offline updating procedure for the master list

**Comment by sibir-ine** [comment]
There already is in the [FAQ](https://loot.github.io/docs/help/LOOT-FAQs.html#update-masterlist-errors). You obviously still need a connection at some point to download any masterlists, it just doesn't need to be done through LOOT. Feel free to ask if you still have questions.

**Comment by nutpantz** [comment]
the faq needs the addition to uncheck  "update masterlist before sorting" and "check for loot updates on startup"

**Comment by sibir-ine** [comment]
From the FAQ:
> Finally, disable the "Update masterlist before sorting" option in LOOT's settings until your connectivity issues have been resolved.

When LOOT fails to check for updates, it just displays an error message that doesn't disrupt any functionality, so that setting isn't relevant to manually updating masterlists.

**Comment by nutpantz** [comment]
That night be the case, but it sure looked like it was not working to a first time user. After i un checked those it sorted everything. And i got the sort button a lot before i found those settings
