### ISSUE TITLE
Index column is not wide enough

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1911]
While testing `loot_0.20.0-92-gbcb7806_starfield-win64.7z` I've noticed that the Index column does not properly increases it's width if needed.

![Index](https://github.com/loot/loot/assets/10406657/ccf51473-09cd-4f3e-8271-d1bd59080a5f)

For SSE it still works using the same LOOT build.

![Index_SSE](https://github.com/loot/loot/assets/10406657/1b0e00e8-51c9-4671-b940-9e3f20fd1d91)

This issue was [first noticed](https://github.com/loot/loot/issues/1638#issuecomment-1001077837) when we worked on implementing Qt for the new GUI.

**Comment by Ortham** [comment]
I missed a couple of game checks in the starfield branch, closing this.
