### ISSUE TITLE
Program stuck to wrong screen

### ISSUE THREAD

**Issue by rdelvax** [loot/loot#1923]
Apparently the latest version of LOOT ALWAYS opens in the same screen in a multi monitor setup
I'm using windows 10 home on a laptop. The laptop screen is just for monitoring resources.
LOOT seems top ALWAYS open on the laptop screen, not on the main screen. And even when I move it to
my main, all the menu pulldowns open on the laptop screen.

**Comment by Ortham** [comment]
Did it work correctly in v0.20.0? If not, what was the last LOOT version that worked correctly?
