### ISSUE TITLE
Unable to provide commandline parameter 'game'  for starfield.

### ISSUE THREAD

**Issue by luctius** [loot/loot#1934]
I believe detection for starfield is missing from 'loot_settings.cpp::getGameId', is that correct?

**Comment by Ortham** [comment]
> I believe detection for starfield is missing from 'loot_settings.cpp::getGameId', is that correct?

No, and that's unrelated anyway.

I've just tested it out, and it works fine. Make sure you're passing the correct LOOT folder as the parameter value.
