### ISSUE TITLE
Don't resort empty plugins alphabetically

### ISSUE THREAD

**Issue by Silarn** [loot/loot#1935]
After packing some loose file mods and creating empty light plugins to load the archives, I've discovered that running the sorter seems to reorder these plugins alphabetically.

I think it makes more sense to preserve the existing load order of such ambiguously sorted plugins so that it doesn't potentially break what might be an intentional archive load order.

**Comment by Ortham** [comment]
LOOT [already](https://github.com/loot/libloot/blob/master/src/api/sorting/plugin_graph.cpp#L529) uses existing load order, but if they were new plugins then they might not have had load order positions yet.

**Comment by Ortham** [comment]
Sorting Starfield load orders is effectively broken unless Bethesda make changes, and disabled in the latest snapshot builds, so I don't think there's any point debugging the issue at this time.

**Comment by Ortham** [comment]
@Silarn could you check if you still get this issue with the latest snapshot builds?

**Comment by Silarn** [comment]
I did incorporate the latest libloot and it doesn't look like I'm seeing that anymore, so I believe this is resolved.

**Comment by Silarn** [comment]
Just to note, MO2 was previously generating ESL files rather than light-flagged ESMs. No idea if this was somehow contributing.
