### ISSUE TITLE
Nothing seems to be a "valid Windows folder name"

### ISSUE THREAD

**Issue by MurdoMaclachlan** [loot/loot#1937]
I see from previous issues that LOOT enforces Windows folder structure even on Linux for portability reasons. However, I'm unable to add a new game at all, with any characters. I've tried:

```
\home\murdo\Games\Mods\Oblivion\LOOT\
\home\murdo\Games\Mods\Oblivion\LOOT
Z:\home\murdo\Games\Mods\Oblivion\LOOT\
Z:\home\murdo\Games\Mods\Oblivion\LOOT
```

All come back with the same "This is not a valid Windows folder name" error.

(Which, as a side note, is unreadable on dark mode:)
![image](https://github.com/loot/loot/assets/47920497/1575f5a2-7a78-4b49-b26c-0bdfa893a6b3)

**Comment by Ortham** [comment]
You're not the first person to be confused by this:

- a folder name is a single path component, e.g. `Oblivion` or `LOOT`
- LOOT is asking you what name to give the folder that it'll create in its own data folder (e.g. `%LOCALAPPDATA%\LOOT\games\<folder name>` on Windows), not the name of the LOOT install folder.

Perhaps it would be better if LOOT picked a folder name itself though.

The tooltips not getting themed correctly is surprising, and I'm not sure if there's anything I can do about that - though displaying validation errors as tooltips is a bit of a hack and that could do with improvement.

**Comment by MurdoMaclachlan** [comment]
Oh, I see, that makes more sense. It let me add the game now, but I'm not sure if I've done something wrong, as it still won't let me select Oblivion, even when I have the default game set to it (still shows "No supported games were detected" as well).

I have the install path set to, `/home/murdo/SSD/STEAM_INSTALL_3/steamapps/common/Oblivion/`, and the Local AppData path set to `/home/murdo/SSD/STEAM_INSTALL_3/steamapps/compatdata/22330/pfx/drive_c/users/steamuser/AppData/Local/Oblivion/`.

![image](https://github.com/loot/loot/assets/47920497/4a5a2a92-28a7-48e4-9795-8a5e331dbc84)

Regarding the tooltips, I think this is just one of those bugs with detecting system theme -- in LOOT's settings, the theme was actually set to "default". When I set it to force "dark" the colour scheme changes very slightly and the tooltip becomes readable.

**Comment by Ortham** [comment]
Can you [share your debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log)?

**Comment by MurdoMaclachlan** [comment]
Here it is: [LOOTDebugLog.txt](https://github.com/loot/loot/files/13261023/LOOTDebugLog.txt)

**Comment by MurdoMaclachlan** [comment]
If the warning about being unable to open `$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/config/libraryfolders.vdf` is relevant, that's because that file doesn't exist as Steam isn't isntalled via Flatpak.

**Comment by Ortham** [comment]
Could you turn on debug logging and try again?

That warning isn't significant, LOOT just tries that path in case Steam was installed as a Flatpak application.

**Comment by MurdoMaclachlan** [comment]
Ah, sorry, here it is with debug logging: [LOOTDebugLog.txt](https://github.com/loot/loot/files/13261030/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
Does `/home/murdo/SSD/STEAM_INSTALL_3/steamapps/common/Oblivion/Data/Oblivion.esm` exist, and do the filesystem permissions allow LOOT to see it? That's the only reason I can think that the Oblivion install isn't getting seen.

**Comment by MurdoMaclachlan** [comment]
It exists and LOOT has full permissions to read & write there.

**Comment by MurdoMaclachlan** [comment]
Scratch that, I'm apparently blind and glossed over the part of the docs that mentioned Flatpak-specific permissions, thought you meant the read/write permissions of the folder itself. Added permissions for that path and it works now. Thanks for the help, and sorry for wasting your time!
