### ISSUE TITLE
Not being installed

### ISSUE THREAD

**Issue by Wrawller117** [loot/loot#1939]
I am using Windows 22H2 (OS 19045.3570). Neither it is working in Vortex. I don't have vortex installed in C drive.
It simply isn't able to connect to the internet or it's servers are non responsive. I have already set my firewalls to default, reset my network, several restarts, installed an older version of LOOT and yet the same result. Connect timed out.

![image](https://github.com/loot/loot/assets/63629630/f6589830-21d0-4587-aa89-f76d3606d6dd)

![Loot_error](https://github.com/loot/loot/assets/63629630/98a7b2ae-245f-4805-a577-e7949055ae1b)
![image](https://github.com/loot/loot/assets/63629630/0b2e8dd2-afa0-44de-97fa-22efcc339bc4)

Here are the log files for the above image. 

ENOENT: no such file or directory, stat 'C:\Users\p\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml'
ENOENT: no such file or directory, stat 'C:\Users\p\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml'
Error: ENOENT: no such file or directory, stat 'C:\Users\p\AppData\Roaming\Vortex\skyrimse\masterlist\masterlist.yaml'
Prior Context:
    at Object.statAsync (E:\Installed\Vortex\resources\app.asar\renderer.js:9456:27)
    at t.default.<anonymous> (E:\Installed\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:633615)
Prior Context:
    at Object.statAsync (E:\Installed\Vortex\resources\app.asar\renderer.js:9456:27)
    at t.default.<anonymous> (E:\Installed\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:2:633615)

**Comment by pStyl3** [comment]
I've **removed** your duplicate comment from issue 197. Posting your issue one time is enough - plus issue 197 was from 2014, so that was entirely unnecessary Wrawller117.

[GitHub Status](https://www.githubstatus.com/) is not reporting anything unusual, as such everything should be working as intended. You may want to read [this](https://loot.github.io/docs/help/LOOT-FAQs.html#update-masterlist-errors) article from our FAQ.

**Comment by Ortham** [comment]
Could this be similar to the Jio issue?

**Comment by pStyl3** [comment]
That could be the case, yes.
