### ISSUE TITLE
Loot sorting for Starfield greyed out

### ISSUE THREAD

**Issue by ximtek** [loot/loot#1941]
I have taken care of any Loot errors for my Starfield install but I cannot get the sort button to be enabled, it's stays greyed out.  Loot tells me I have not sorted it yet.  I'm using Vortex and have been managing my plugins.txt myself.  I have not ordered it them yet, just adding new mods to the bottom of the list.  Are there any prerequisites or perhaps any plugins.txt formatting issues that could cause this?

**Comment by Ortham** [comment]
No, sorting is intentionally disabled for Starfield.

**Comment by pStyl3** [comment]
[Changelog](https://loot.readthedocs.io/en/latest/app/changelog.html#id2)

> Sorting has been disabled for Starfield. Due to the way that Starfield plugins make changes to existing data, LOOT cannot reliable detect when two plugins change the same record, so sorting may not function as intended.

Also interesting: [Starfield - An update on plugin mods](https://www.nexusmods.com/starfield/news/14888)

As such, when it comes to Starfield LOOT is currently in "view only" mode. Bethesda needs to release official modding and fix the issues the community has found since release, then we can see about reenabling sorting for Starfield.

**Comment by ximtek** [comment]
Thank you for the quick response, that saves me time trying to troubleshoot something that can't be fixed.  Should have noticed that in the changelog.  

I'm going to take a look at this problem to see if I can offer some suggestions (I do these sorts of data oriented problem solving for a living).  At the very least I might be able to make a Loot copy that works for my local install.

Is this considered a bug by Bethesda or "by design", perhaps due to a slightly different plug-in paradigm?  Is that known or stringly inferred?

I still don't completely understand the issue but plan to figure it out.  The article that @pStyl3 gave a link for is a nice primer and shows an easy to read diagram, however it does not label anything on the diagram as a "subrecord", the thing is spends the article discussing.  I still don't get how a mod's masters requirements are different from the master's requirement of the individual records the mod contains (aka "subrecords") as the article seems to imply.
