### ISSUE TITLE
False error message for Skyrim SSE max ESL records (update from 2048 to 4096)

### ISSUE THREAD

**Issue by FedericoSteidl** [loot/loot#1942]
Please update this or turn it into a _message_ that says: "...will cause irreversible damage to your game saves on versions prior to 1.6.1130"

![image](https://github.com/loot/loot/assets/115730623/88b6313a-4fbf-4bbb-bf06-42dd238e9048)
![image](https://github.com/loot/loot/assets/115730623/5dd822f9-3aa4-4296-8dfc-433f30149d6d)

**Comment by sibir-ine** [comment]
We're aware, the issue is being tracked in one of LOOT's dependencies at Ortham/esplugin#40.

**Comment by Ortham** [comment]
This should be fixed in [this build](https://github.com/loot/loot/actions/runs/7119308323).

**Comment by pStyl3** [comment]
Seems to be working as intended, I no longer get the above error message.

**Comment by Ortham** [comment]
Fixed by 35be07e8e599816dd6c7ae12ed4dddbb832fdae7.
