### ISSUE TITLE
Norton 360 Reports 22.3 as a virus

### ISSUE THREAD

**Issue by N0lla** [loot/loot#1943]
It seems the file in \docs\_images\groups_editor.windows.png is a problem

There is no issue installing 22.2.

**Comment by sibir-ine** [comment]
It's a [false positive](https://loot.github.io/docs/help/LOOT-FAQs.html#antivirus), there's nothing we can do about it. Either make an exclusion for LOOT or report it as a false positive to your AV if possible.
