### ISSUE TITLE
Add plugin card icons to docs

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1944]
In [the docs](https://loot.readthedocs.io/en/stable/app/usage/main.html#plugin-cards-sidebar-items), LOOT lists the icons that appear in a plugin card, but it doesn't include the icons themselves. This makes it difficult to decipher which icon label applies to which icon.

**Comment by Ortham** [comment]
Done in 367fbde4d77e82b6a6e6d4a470b64bb6bf21c108.
