### ISSUE TITLE
LOOT INSTALLATION PROBLEM

### ISSUE THREAD

**Issue by SRUSTON** [loot/loot#1945]
When attempting to install Loot on Windows 10, I receive the error message shown in the attached file.
![ScreenHunter 06](https://github.com/loot/loot/assets/25768363/7be7f446-1af7-477f-9ed6-4abfb7717b04)

It has worked fine previously, please help as I am desperate to reslove a Skyrim problem.

**Comment by Ortham** [comment]
Are you running an old version of Windows 10? Apparently that function was [added](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfofordpi#requirements) in Windows 10, version 1607.

**Comment by sibir-ine** [comment]
User is indeed running a version of Windows 10 LOOT doesn't support, see https://github.com/loot/loot/issues/1953#issuecomment-1868539113.
