### ISSUE TITLE
Installation is blocked on arm64, despite compatibility layer

### ISSUE THREAD

**Issue by Weldawadyathink** [loot/loot#1947]
Windows 11 on arm64 has a compatibility layer to run x86 and x86_64 code. When you try to install LOOT on arm64, the installer fails with a message that it only supports x64. If you bypass the installer by copying /Program Files/LOOT from a x64 installation to an arm64 computer, everything works correctly. 

I recommend allowing the installer to run on arm64, or allow a bypass to force the installation despite "incompatible" architecture.

**Comment by Ortham** [comment]
Does the installer from [this build](https://github.com/loot/loot/actions/runs/7158184046) work?

**Comment by Weldawadyathink** [comment]
Hey all, sorry for letting this report languish. I can't remember if that installer worked. I ran into so many issues with other modding software that I ended up abandoning the attempt.

**Comment by Ortham** [comment]
Fair enough. Since that CI build's artifacts have expired I'll mark this as a bug but not awaiting feedback. If Windows on ARM ever leaves its perpetual beta I might try running it in a qemu VM, and if anyone else using Windows on ARM wants to try it out in the future I can always rebuild the change I made.

**Comment by Ortham** [comment]
I've changed my mind on calling this a bug because although blocking the install isn't intentional, we don't claim to support ARM.

**Comment by Ortham** [comment]
Inno Setup 6.3.0 introduced better support for ARM64, and I enabled that in b2b96f8c2a7a6af2a9c45ee15263d880c46553ba, so I'm closing this as done.
