### ISSUE TITLE
Loot will not run

### ISSUE THREAD

**Issue by SRUSTON** [loot/loot#1953]
When I attempt to run LOOT, I receive the attached error message. This is dispite Qt6Gui.dll being in the same directory.
![ScreenHunter 01](https://github.com/loot/loot/assets/25768363/dd64af8b-c45d-4647-9fd7-05a8d1b82eee)

**Comment by Ortham** [comment]
[SystemParametersInfoForDpi](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfofordpi#requirements) has been around since Windows 10 version 1607, what version of Windows are you running?

**Comment by SRUSTON** [comment]
Hi Oliver,
Thanks for replying so quickly. I'm running Windows 10 Build 1511. It keeps
updating to the next build, but it disables my Audigy Fx Sound Card.
Kind regards,
Shane Ruston

**Comment by pStyl3** [comment]
You'll need to update Windows 10 at least to build 1809, as that is a minimum requirement for LOOT.
