### ISSUE TITLE
Loot Error while Sorting, then crashes

### ISSUE THREAD

**Issue by MrSpaceCosmos** [loot/loot#1954]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/13764978/LOOTDebugLog.txt)

I have added my Debug Log File, I have installed Nolvus Modlist and then added a few of my own mods, been trying to sort the load order, but when I press sort plugins, it loads for a minute or 2, then shows error (just error) and then Loot crashes. Please, need help to sort this out, I have not crossed my esp limit, I have 254 esp, In the beginning, Loot could not detect Nolvus load order, because nolvus installs completely different stock game in it's own file, but then I changed the path so Loot could detect Nolvus alongside with my Mods. Now I am having this new problem.

**Comment by Ortham** [comment]
Can you enable debug logging and try again?
