### ISSUE TITLE
Game-specific settings could not be initialised: libloadorder failed to create a game handle. Details: Failed to parse ini file

### ISSUE THREAD

**Issue by Faye0121** [loot/loot#1964]
I'm using MO2 to edit my ini file. When I run Loot with MO2. It occur this error:
Game-specific settings could not be initialised: libloadorder failed to create a game handle. Details: Failed to parse ini file, error at line 9, column 1: expecting "[Some('='), Some(':')]" but found EOF.: Libloadorder error

**Comment by Ortham** [comment]
You've probably pasted nonsense from Nexus Mods (its anti-script-injection code mangles some ini recommendations that some mod authors include in their mods' descriptions) into an ini file (for Fallout 4, maybe?). If you've got a line in the ini that contains "javascript-event-stripped" then it's mangled.

**Comment by Faye0121** [comment]
@Ortham Yeah I found that line in my fallout4custom.ini, it was inserted between a line I added to reduce the rim light. The "javascript-event-stripped" replaced some letters in that line. Loot works fine once I delete it and rewrite that line. Thanks a lot!
