### ISSUE TITLE
Sort anyway if masterlist update takes too long or fails

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1969]
Requested by [Psymon](https://discord.com/channels/473542112974077963/473542230095822848/1236875477931524126) & [IllusiveMan](https://discord.com/channels/473542112974077963/473542230095822848/1236878398027202654) on Discord.

They are requesting that if **Update masterlist before sorting** is enabled & the masterlist update procedure hangs or fails, LOOT notifies the user & proceeds to sorting anyway. In the case that it hangs, this would require setting a max time after which the masterlist update procedure is canceled.

At present, when the masterlist update procedure fails (e.g., when there's no internet connection) before sorting, LOOT appears to crash. This doesn't occur when just the **Update Masterlist** button is pressed, it just returns an error. This might be a separate bug.

**Comment by Ortham** [comment]
- I'd need to change up the tasks code to support more complicated chaining, as masterlist update is prelude then masterlist, and if prelude fails we'd want to skip masterlist and go to sort, and if masterlist fails we'd want to go to sort. That's fine, it's just not trivial.
- Yeah, there's no default timeout, I can add one easily enough. Qt's default (if you set a timeout without specifying a value) is 30 seconds, which seems reasonable.
- I see why LOOT is crashing, the handler doesn't account for the possibility that the process might have completely failed, it always expects at least one task to finish. That's easy enough to fix.

**Comment by Ortham** [comment]
The crash is fixed in 67c7fd5feb15148f67a2be55cfc466f1773acaa2 and the network timeouts have been added in bc5a440a3d58425e27787f2a34f0fc6dab762d85.

**Comment by Ortham** [comment]
As of a4c5de593f45efb219f80a97965fcfe240f5b6a4 the update-and-sort process will handle any masterlist update errors before starting to sort the load order.
