### ISSUE TITLE
LOOT can't detect an existing internet connection

### ISSUE THREAD

**Issue by tommy61157** [loot/loot#197]
LOOT has been working pretty well for me up to this point, I'm just having 2 main issues with it now.
1. LOOT says that either I don't have an internet connection to update the masterlist or the server is down.
2. (this may be a result of the above) It claims I have dirty edits on plugins that TESVEdit says are clean.

**Comment by Wrawller117** [comment]
> I'm going to close this as there's nothing I can really do about it, besides keeping LOOT's dependencies updated. LOOT just lets libgit2 handle all the networking, and libgit2 uses Windows' API. There's no way LOOT can get in the middle either.

Did you find anything ? I am having this same issue years later. It simply isn't able to connect to the internet or it's servers are non responsive. I have already set my firewalls to default, reset my network, several restarts, installed an older version of LOOT and yet the same result. Connect timed out.

This here, is  the message I get when I am trying to use in Vortex

![image](https://github.com/loot/loot/assets/63629630/a7e5b485-72bb-4aaa-882e-1de46fe87c6f)
