### ISSUE TITLE
Quick Auto Clean/xEdit documentation for Flatpak version?

### ISSUE THREAD

**Issue by WMan22** [loot/loot#1981]
I decided to test load order sorting, which resulted in this. 
![QAC](https://github.com/loot/loot/assets/48204719/728ce1b1-e7ec-451c-8714-8bc36571a671)

When following the link [to the website that is meant to explain how it works,](https://tes5edit.github.io/docs/7-mod-cleaning-and-error-checking.html#ThreeEasyStepstocleanMods) it shows the use of an extra .exe file for quick auto clean, but scrolling across the instructions I couldn't figure out what a linux equivalent of this would be.

Is there any utility within the flatpak itself that can be used? Am I missing something obvious?

**Comment by sibir-ine** [comment]
It's a separate program from LOOT, so we can't guarantee it'll work with your OS (especially since xEdit only officially supports Windows). If it doesn't work with your OS, you'll just have to ignore cleaning messages as xEdit is the only program you can clean plugins with.

**Comment by WMan22** [comment]
Ah, I understand now. I suppose I'll try to use that through SteamTinkerLaunch's One Time Run function later then, I made the issue tracker here with the assumption that it was part of LOOT, my bad. Closing now.
