### ISSUE TITLE
Error: Game-specific settings could not be initialized. libloadorder failed to create a game handle...error at line 2287, column 1:expecting "[Some('='), Some(':')] but found EOF.: libloadorder error

### ISSUE THREAD

**Issue by zolticq** [loot/loot#1987]
I stumbled across is when launching LOOT through MO2 I used past solutions of deleting the LOOT folder in appdata/local and uninstalling and reinstalling via the exe. Just need help figuring this out. Any help is appreciated!

edit: this is for fo4

**Comment by sibir-ine** [comment]
What version of LOOT are you using?

**Comment by zolticq** [comment]
0.22.4

**Comment by sibir-ine** [comment]
Please upload your debug log. You can find it by going to File -> Open LOOT Data Folder.

**Comment by zolticq** [comment]
[LOOTDebugLog.txt](https://github.com/user-attachments/files/15526537/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
In your `Fallout4Custom.ini`, post what's at line 2287, including a few of the surrounding lines.

**Comment by zolticq** [comment]
uWorkshopSnapTargetOnlyThreshold=75 (2284)
(2285)
END_OF_TEXT (2286)
(here is 2287)

**Comment by sibir-ine** [comment]
> END_OF_TEXT

As in `END_OF_TEXT` is written out? Try removing that line (2286).

**Comment by zolticq** [comment]
Yeah END_OF_TEXT is line 2286 for the txt file and there is nothing for 2287

**Comment by sibir-ine** [comment]
This can be closed as I've instructed you on how to fix your INI. If you're still experiencing issues, feel free to ask for clarification.
