### ISSUE TITLE
LOOT unticking/disables ESL flagged plugins (patches made in SSedit)

### ISSUE THREAD

**Issue by d0verenny** [loot/loot#1988]
Every time I launch LOOT, it's unticking my patches I made in SSedit that are flagged as ESL in MO2. I know LOOT does that to ESPs when they exceed 255 limit, but I only have overall 133 plugins (including the main Bethesda's files), and my patches are ESL-flagged. I never had this problem before.

MO2 ver. 2.5.0
LOOT ver. 0.22.4

Update: I'm not sure now if it's LOOT related. When I close SSedit, MO2 unchekcs the plugins too.

**Comment by sibir-ine** [comment]
LOOT hasn't disabled plugins for several versions, so it's almost certainly something else.

**Comment by d0verenny** [comment]
Update: I noticed the "Plugin not found" error and that it showed the question mark instead of the "—" symbol: 

`Plugin not found: xEdit ? RDO + Lydia mod patch.esp`

![ModOrganizer_mKqCUMqApZ](https://github.com/ModOrganizer2/modorganizer/assets/28781690/6acc6884-8a72-413e-90f8-997e74dd9721)

All I had to do is just rename the em dash to "-" (minus) — now MO2 doesn't disable the mod.

So the problem wasn't related to LOOT.
