### ISSUE TITLE
Compile error with 0.22.4 but not 0.22.3

### ISSUE THREAD

**Issue by C0rn3j** [loot/loot#1990]
This is the build function of mine (in [AUR/loot](https://aur.archlinux.org/packages/loot)), which works with 0.22.3: 

```bash

build() {
	# libloot
	cd "$srcdir/lib$pkgname-$_pkglibver"
	mkdir -p build
	cd build
	cmake .. -DCMAKE_SKIP_RPATH=TRUE
	make loot

	mkdir -p pkg
	cp lib$pkgname.so ./pkg/
	cp -r ../include/ ./pkg/
	tar -zcf lib$pkgname-$_pkglibver.tar.gz ./pkg/

	# loot
	cd "$srcdir/$pkgname-$pkgver"

	mkdir -p build
	cd build
	cmake .. -DLIBLOOT_URL="$srcdir/lib$pkgname-$_pkglibver/build/lib$pkgname-$_pkglibver.tar.gz" \
		-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE -DCMAKE_INSTALL_RPATH="/opt/$pkgname"
	make LOOT
}
```

Did something change in the build process with this minor release?

I think what I am getting stuck on in 0.22.4 is this:

`make[3]: *** No rule to make target 'external/src/libloot/lib/libloot.so', needed by 'LOOT'.  Stop.`

Full build log including some logs around pacman - [loot-0.22.4-1-x86_64-build.zip](https://github.com/user-attachments/files/15905761/loot-0.22.4-1-x86_64-build.zip)

**Comment by Ortham** [comment]
The libloot archive file structure changed, compare https://github.com/loot/libloot/releases/download/0.22.4/libloot-0.22.4-Linux.tar.xz and https://github.com/loot/libloot/releases/download/0.22.3/libloot-0.22.3-Linux.tar.xz

**Comment by C0rn3j** [comment]
![image](https://github.com/loot/loot/assets/1641362/e847b9a8-7b95-429b-9c12-eb42445bb8e5)

Thanks! Got it.
