### ISSUE TITLE
Linux version only accepts Windows folder structure

### ISSUE THREAD

**Issue by Thijxx** [loot/loot#2006]
Hi there, I see an other issue that went a bit crazy and got locked, this may be about the same issue.
The Flatpak version of Loot let's you add a game in settings but it is impossible because it only accepts Windows style paths.

"This is not a valid Windows folder name" is a correct message :) so maybe this is not a bug but it's unclear how to use it then.

**Comment by Ortham** [comment]
Can you give an example of what you're trying to enter?

**Comment by Thijxx** [comment]
for example `/mnt/steam/SteamLibrary/steamapps/common/Skyrim Special Edition/`

**Comment by Ortham** [comment]
That's not a folder name, that's a folder path.

**Comment by Ortham** [comment]
You're getting the error because you're trying to enter an invalid value. This is for the "LOOT Folder" field, right? That's just the name of a folder for LOOT to store its game-specific data in its own folder, not the path to the game - that's what the "Install Path" field is for.

**Comment by Thijxx** [comment]
> That's not a folder name, that's a folder path.

OMG, sry about that, I was expecting it to ask for the Game folder there :D in my defense it just says LOOT Folder next to the text box

It works with the paths at the right places
![image](https://github.com/user-attachments/assets/c0c51ea8-54e4-4d48-a854-9758ec6bb6d8)
