### ISSUE TITLE
Error code: 12; Failed to update masterlist. Details: Error when trying to clone a remote masterlist storage.

### ISSUE THREAD

**Issue by FRTD19** [loot/loot#2007]
When I tried to update the masterlist, the error "Error code: 12; Failed to update the masterlist. Details: Error when trying to clone a remote masterlist storage." All the discussions on this topic that I could find were quite old and most of the links to solutions to the problem did not work.

**Comment by Ortham** [comment]
What version of LOOT are you using? It hasn't cloned the masterlists for years.
