### ISSUE TITLE
BlueprintShips-Starfield.esm doesn't load as expected

### ISSUE THREAD

**Issue by Ortham** [loot/loot#2009]
Silarn brought this up [in Discord](https://discord.com/channels/473542112974077963/496196499890241546/1265012541894164510). I've tested having `BlueprintShips-Starfield.esm` in `Starfield.ccc` and explicitly the first active plugin in `Plugins.txt`, together with a master-flagged plugin that adds new records, and the new records showed up in the 01 slot, so `BlueprintShips-Starfield.esm` is not loading before the other plugin.

I also tested with a non-master-flagged plugin that adds new records, and they still showed up in the 01 slot, so even though `BlueprintShips-Starfield.esm` is master-flagged, it doesn't load as the last master.

I then renamed `BlueprintShips-Starfield.esm` and renamed a second master-flagged test plugin that adds new records to `BlueprintShips-Starfield.esm`, and in-game I saw those new records appear in the 01 slot, before the records from my first master-flagged test plugin.

I then noticed that the Creation Kit doesn't list the original `BlueprintShips-Starfield.esm` in its Data dialog, even when it's renamed, but if another plugin is renamed to `BlueprintShips-Starfield.esm`, that plugin *does* show up in the list. That behaviour is controlled by the plugin's `0x800` flag: if it's set then the plugin isn't listed.

I went back to the test plugin that I'd renamed to `BlueprintShips-Starfield.esm` and set its 0x800 flag, and this time I saw its records appear in the 03 slot, after the records from my first master-flagged test plugin and my non-master-flagged test plugin.

It appears that the 0x800 flag hides the plugin from the Creation Kit and also makes `BlueprintShips-Starfield.esm` load after all active full plugins (master-flagged or otherwise).

This means that LOOT (via libloot and libloadorder) don't handle plugins with that flag set correctly.

Things I didn't test:

- [x] What happens if the flag is present on a small or medium plugin
  - Hopefully it causes the plugin to load last in the FE or FD slot respectively
- [x] What happens if more than one plugin has the 0x800 flag set
  - Hopefully their relative load order is preserved at the end of the load order

**Comment by Silarn** [comment]
Might be worth testing what happens with this flag when applied to a different plugin. Do they always load at the end or is that somehow unique to BlueprintShips?

**Comment by Silarn** [comment]
Some information from Lord Nyriox in the Starfield Modding discord: 

> If I had to guess, the flag you mentioned indicates a ‘blueprint master’. 
>
> IIRC, it is because of the idiosyncrasies of ‘blueprint master’ handling that SF1Edit hoists `BlueprintShips-Starfield.esm` with every plugin it creates. 
>
> You can enable loading such plugins in the CK by [enabling a hidden CreationKit.ini option](<https://discord.com/channels/916686954421157930/1254924936980467812>): 
>```[General]
>bShowBluePrintMastersInDataFiles=1

**Comment by Ortham** [comment]
With `BlueprintShips-Starfield.esm` in `Starfield.ccc` and the following in `Plugins.txt`:

```
*test.1.esm
*test.2.esm
*test.1.esp
```

where `test.1.esm` is master-flagged and has the 0x800 flag set, `test.2.esm` is master-flagged and `test.1.esp` is unflagged, I saw that `test.2.esm` was loaded into the 01 slot, `test.1.esp` was loaded into the 02 slot, and `test.1.esm` was loaded into the 04 slot (so by process of elimination `BlueprintShips-Starfield.esm` was in the 03 slot.

I set the 0x800 flag in `test.2.esm` and verified that plugins with that flag retain their relative load order, just after all other full plugins.

I also set the small and medium flags on the test plugins and when the 0x800 flag is also set it causes the plugin to load after other plugins of the same scale that don't have that flag set.

All my test plugins override the same Starfield.esm record with different values, so I also checked which won the conflict, and it was always the 0x800-flagged plugin that loaded last, so the load order slot that new records appear in is also the same that's used for conflict resolution (unlike for small and medium masters).

I've also noticed that once the game is loaded `test.1.esm` was removed from `Plugins.txt`, so it's got 3 effects that I know of:

1. Plugins with the 0x800 flag set are not visible in the Creation Kit's Data dialog or in Starfield's load order UI (accessed from the Creations UI).
2. Plugins with the 0x800 flag set are removed from `Plugins.txt` when a save is loaded (and the flag doesn't make them implicitly active, `BlueprintShips-Starfield.esm` is implicitly active because it's hardcoded to be).
3. Plugins with the 0x800 flag set load after all plugins of the same scale (full/medium/small) that do not have the flag set, but retain their load order positions relative to other plugins of the same scale that have the 0x800 flag set.

Setting `bShowBluePrintMastersInDataFiles=1` in `CreationKit.ini` (under the `[General]` heading) does cause plugins with the 0x800 flag to show up, so I'll refer to it as the blueprint flag from now on (not blueprint master flag, to avoid confusion with the master flag and since non-masters can also have the flag).

**Comment by Silarn** [comment]
So basically this also breaks setting blueprint plugins as masters, right? A standard plugin can never override records from a blueprint plugin as the blueprint plugin will always be placed last in the load order. Which is interesting because many xEdit-created plugins automatically included `BlueprintShips-Starfield.esm` as a master. So it's a bit unclear to me how that's going to affect plugin loading.

Since blueprint plugins get removed from plugins.txt, I think we don't need to worry about it too much. AFAIK you can't create one in the CK and would have to manually edit the plugin flags to do so. But I suppose we should at least recognize when they exist and perhaps warn about if not outright disable them. IMO only the core plugin should be allowed, and it's not clear to me that using it as a master is a good idea even though xEdit was doing it for a while.

**Comment by Ortham** [comment]
> So basically this also breaks setting blueprint plugins as masters, right? A standard plugin can never override records from a blueprint plugin as the blueprint plugin will always be placed last in the load order. Which is interesting because many xEdit-created plugins automatically included `BlueprintShips-Starfield.esm` as a master. So it's a bit unclear to me how that's going to affect plugin loading.

Having a blueprint plugin as a master might cause it to get hoisted above the dependent plugin. I did try quickly testing that but got weird results, so I'm going to retry later.

**Comment by Silarn** [comment]
A large number of xEdit-based plugins have it set as master. An example load order that was posted in the MO2 Discord seemed to show that it was still loading in the last memory position even though other dependent plugins were loaded.

Yet apparently the game can still run this way. But I have no idea if this still somehow changes the load order of the actual records or if it still technically overrides everything else.

**Comment by Ortham** [comment]
I retested with `Plugins.txt` containing:

```
*blueprint.esm
*override.esm
```

where `blueprint.esm` adds a few new records and `override.esm` overrides one of them and adds a new record. In game I saw the record added by `override.esm` at slot 01 and the records added by `blueprint.esm` at slot 03 (with `BlueprintShips-Starfield.esm` presumably in slot 02). However, the overridden data in `override.esm` wasn't visible, instead I saw the original record from `blueprint.esm`.

If I also make `override.esm` a blueprint plugin, then `blueprint.esm` loads at slot 02 and `override.esm` loads at slot 03, and the changes it makes to the record it overrides are visible in-game.

So the behaviour is weird, but it should be fine to have `BlueprintShips-Starfield.esm` as a master, but you won't be able to actually make any changes to the records it adds unless your dependent plugin is also a blueprint plugin.

**Comment by Silarn** [comment]
Some authors have told me they're able to edit the ship data in BS. I asked them to give examples here but apparently that hasn't happened. I'll see if I can dig something up. This was apparently before the creation update so who knows if it's still valid.

**Comment by Ortham** [comment]
I just retested and saw the same behaviour as before.

**Comment by Ortham** [comment]
I've found more unexpected behaviour.

With `BlueprintShips-Starfield.esm` in `Starfield.ccc` and `Plugins.txt` containing:

```
*blueprint.esp
*test.esp
*blueprint.esm
```

where the plugins all add a single record, the blueprint plugins are blueprint-flagged and the .esm file is master-flagged, in-game `blueprint.esp` is loaded at slot 01, `test.esp` is loaded at slot 02 and `blueprint.esm` is loaded at slot 04. So it looks like the blueprint flag has no effect on load order for non-masters (though they're still hidden in the CK's Data dialog).

I need to re-test the behaviour when the medium or light flags are present, in case I misunderstood what was happening with them... Having 4 dimensions of plugin type (master/non-master, update/non-update, blueprint/non-blueprint, full/medium/small) makes it so much more work to cover all their interactions. 😢

**Comment by Ortham** [comment]
Yet another test, this time about whether blueprint plugins can hoist other blueprint plugins: the answer is yes.

With BlueprintShips-Starfield.esm in Starfield.ccc and Plugins.txt containing:

```
*blueprint - override.esm
*blueprint.esm
```

where `blueprint.esm` adds a record and `blueprint - override.esm` overrides that record, the record was seen in game in slot 02 with the changes made by `blueprint - override.esm`.

**Comment by Ortham** [comment]
I think I've finished wrapping my head around the behaviour of blueprint plugins, and have summarised my understanding in [a blog post](https://blog.ortham.net/posts/2024-07-30-blueprint-plugins/).

**Comment by Ortham** [comment]
Note to self: add a validation check to LOOT that shows an error message if a non-blueprint-master has a blueprint master as a master, requirement or load after, as that will always cause a cyclic interaction error, and in the case of a master any overridden records won't actually be overridden in-game.

**Comment by Ortham** [comment]
Closing this as done as of 27786d584ae9b32ce97597ef8a8cf41967594593.
