### ISSUE TITLE
Details missing in General Information section

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#2011]
If LOOT is used to sort a Starfield load order, while at least one master of a plugin is missing, e.g.

![image](https://github.com/user-attachments/assets/9846e1d2-a223-45e6-8c19-3cb0dd2d75d9)

sorting will fail with the following message:

![image](https://github.com/user-attachments/assets/6aa63fb9-419d-49c7-8cd9-89b4332f78c2)

Corresponding entry in LOOTDebugLog.txt:
```
[20:29:23.376872] [error]: esplugin failed to resolve the record IDs of "no_quest_sal-6830.esm". Error code: 14. Details: Plugin metadata for "sfbgs00a_a.esm" not found
[20:29:23.376962] [error]: Failed to sort plugins. Details: esplugin failed to resolve the record IDs of "no_quest_sal-6830.esm". Error code: 14. Details: Plugin metadata for "sfbgs00a_a.esm" not found
```

The issue however is, that the General Information card does not contain any information regarding this error, so it's not obvious to the user what the issue is.

[Unlock SAL-6830 Engine - Quest Requirement Begone](https://www.nexusmods.com/starfield/mods/9802/)
[Archived 1.0 version](https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=37472&game_id=4187)

This can be reproduced using the archived version `1.0` of `no_quest_sal-6830.esm`, which has `sfbgs00a_a.esm` (Blackout Drumbeat Skin) as a master. The latest version `1.1` only has `Starfield.esm` as a master, so isn't suited to test this issue.

**Comment by Ortham** [comment]
This is happening because the esplugin error just gets thrown as a generic file error, so there's no way to distinguish it from other error causes and provide a localised error message for it. I can update libloot to expose the error codes though, and update LOOT to check for the specific code for this scenario.

@pStyl3 How's this?

![image](https://github.com/user-attachments/assets/f9ababc1-628f-4ccc-9a63-9e5896d233f9)

**Comment by pStyl3** [comment]
> @pStyl3 How's this message, displayed when sorting fails?

I like it. 👍

**Comment by Ortham** [comment]
Done as of b82f1af34e783e90426a77c5033246ac8313a444.
