### ISSUE TITLE
Help Skyrim SE, USSEP & LOOT

### ISSUE THREAD

**Issue by bobbeurke** [loot/loot#2012]
About Skyrim SE - vers 1.6.659 (Gog), it seem that USSEP  v4.2.9A would be the right version.
Can anyone confirm, please ?

For use in conjunction with LOOT, it seems that v0.19.1 would be the right version.
Can anyone confirm, please ?

Would Loot v0.23.0 (last) work with USSEP 4.2.9A?

Many thanks in advance !

**Comment by Ortham** [comment]
I don't know of any reason why you shouldn't be using the latest version of LOOT - it can't really be incompatible with specific mods.

**Comment by pStyl3** [comment]
It's recommended to always use the [latest version](https://github.com/loot/loot/releases/latest) of LOOT.

LOOT v0.19.1 has been released in January 2023, so not only is it outdated in general by now, it also uses an outdated masterlist syntax - which means you wouldn't receive masterlist updates, if you were to use this version of LOOT.

[Unofficial Skyrim Special Edition Patch - USSEP](https://www.nexusmods.com/skyrimspecialedition/mods/266/) only offers a `v4.3.2`, as such in my opinion there's nothing else to discuss here.
