### ISSUE TITLE
Starfield: SFBGS004.esm not getting set enabled automatically

### ISSUE THREAD

**Issue by Silarn** [loot/loot#2018]
I guess just adding it to the masterlist doesn't update LOOT's internal 'automatically loaded' list, so LOOT is complaining about ambiguous load orders with the latest Starfield update and the SFBGS004.esm plugin.

It may be worth having Starfield set to autoload maingroup plugins since they seem to be regularly adding new core plugins to Starfield.

**Comment by Ortham** [comment]
This is resolved by 46f4f3b5f80120fffbc56eccd5c183cc0ecefc84 or 98a4ae8859668fa4eff70e557e28c2e0887d8057 (both would resolve it in different ways), I'll get a new release out with those changes.
