### ISSUE TITLE
ITMs on official DLC masters shouldn't be fatal errors 

### ISSUE THREAD

**Issue by obewan** [loot/loot#2021]
There's ITMs on official Skyrim SSE dlc (Dawnguard.esm (842), Update.esm (386), HearthFires.esm (221)...), it's duplicate records from Skyrim.esm. Now the latest DynDOLOD check this as a fatal error and ask us to clean those masters. I don't think it should be safe to modify the masters, even those ITM could be some safeguards for their content. 
I already ask Seldon but he say I should ask xEdit team for that, though it's more a Loot issue then.
Do you think it's safe to modify those masters? Does it worth it? If not could you just remove this errors messages from the masters, as they are not plugins but masters ?
See https://stepmodifications.org/forum/topic/19808-im-told-to-clean-updateesm-dawnguardesm-hearthfiresesm-is-it-really-safe-to-do-so/

**Comment by obewan** [comment]
Thanks pStyl3. I pass the autoclean on those then, even if I think it's temporary and a bit unsafe.
Best regards.

**Comment by sibir-ine** [comment]
Also, just to clarify, we're not the ones saying dirty official plugins are "fatal errors", that's DynDOLOD as you said. As pStyl3 pointed out, we just throw a warning that can be hidden & ignored.
