### ISSUE TITLE
Failed to check for LOOT updates

### ISSUE THREAD

**Issue by EternityEngine** [loot/loot#2025]
Running 64-bit version 0.23.1 on Windows 10, and I had this issue with version 0.23 as well. On first starting LOOT, I get a red message stating the following:

`Failed to check for LOOT updates! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.`

If I close and reopen LOOT, I do not get the message again and it completes the check. It will work fine for a while, and then I will get the error again.

I've attached LOOTDebugLog.txt from the error run and from the non-error run. The only difference is these two lines existing when the error occurs:

```
[18:38:21.219497] [error]: Network error code 5, description is: Operation canceled
[18:38:21.236829] [error]: Error while checking for LOOT updates: unexpected HTTP response status code: 0. Response body is: 
```

There's nothing that looks relevant in the Windows Event Viewer, unfortunately.

[LOOTDebugLog_1_error.txt](https://github.com/user-attachments/files/16859778/LOOTDebugLog_1_error.txt)
[LOOTDebugLog_2_noerror.txt](https://github.com/user-attachments/files/16859777/LOOTDebugLog_2_noerror.txt)

**Comment by pStyl3** [comment]
Sorry for the late reply @EternityEngine.

In the meantime [LOOT v0.24.1](https://github.com/loot/loot/releases/tag/0.24.1) has been released, so please update to this version, if you haven't already.

If you continue to experience the same error, please have a look at [this FAQ entry](https://loot.github.io/docs/help/LOOT-FAQs.html#update-masterlist-errors).

**Comment by EternityEngine** [comment]
The issue actually stopped happening before I updated to 24.0 (and still doesn't happen for 24.1), so I assume it was some sort of network hiccup or GitHub issue. Thank you for your reply.

**Comment by Thijxx** [comment]
I run 0.24.1 on Arch Linux and have the issue with the update error, could you make this a warning so it does not block auto-sort? I checked the FAQ but have no connection issues.

**Comment by Ortham** [comment]
> I run 0.24.1 on Arch Linux and have the issue with the update error, could you make this a warning so it does not block auto-sort? I checked the FAQ but have no connection issues.

You can disable the auto-update before sort in LOOT's settings, is that not enough to solve your issue?

**Comment by Thijxx** [comment]
> > I run 0.24.1 on Arch Linux and have the issue with the update error, could you make this a warning so it does not block auto-sort? I checked the FAQ but have no connection issues.
> 
> You can disable the auto-update before sort in LOOT's settings, is that not enough to solve your issue?

I try to run LOOT without user interaction so for my use case it is not a great solution.

**Comment by Ortham** [comment]
> I try to run LOOT without user interaction so for my use case it is not a great solution.

It's a setting that you only need to configure once, and if you really want to avoid the GUI you could update the setting in LOOT's `settings.toml` file.

**Comment by Thijxx** [comment]
> > I try to run LOOT without user interaction so for my use case it is not a great solution.
> 
> It's a setting that you only need to configure once, and if you really want to avoid the GUI you could update the setting in LOOT's `settings.toml` file.

Great, I'll do that, thanks
