### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by Freakygamer17** [loot/loot#2036]
LOOT doesn't download when I click on the download link. 
Can someone help me with this?

**Comment by pStyl3** [comment]
Both [GitHub](https://github.com/loot/loot/releases/tag/0.24.0) and [Nexus](https://www.nexusmods.com/site/mods/439/) work for me, and [GitHub Status](https://www.githubstatus.com/) also doesn't report anything going wrong. Please make sure that you've tried both sources linked above. If it still doesn't work, try to restart your PC, or simply wait for a bit until you try again.

**Comment by Freakygamer17** [comment]
Okay..
Thanks Man.
