### ISSUE TITLE
Make bash tags a list or auto-completion

### ISSUE THREAD

**Issue by Freso** [loot/loot#254]
There's a finite number of bash tags for each supported game, most of these tags (e.g., `Relev`, `Delev`) being shared among the games.

It would be neat if LOOT would either 1) have a drop-down instead of the free-text input field, or 2) have an auto-completion function to aid with tag entry (see also #253).

The tag lists could be implemented by either having all valid tags across all games in a list, or having separate lists for each game with LOOT being aware of which game is currently active and thus using the relevant list.

![Screenshot](https://i.imgur.com/sIKFZzb.png)

**Comment by WrinklyNinja** [comment]
I've begun work on this. Bash Tag suggestions are hardcoded for each game, but need changing because Mator Smash supports using all the tags that exist for Oblivion with Skyrim, and Wrye Bash also supports the following new tags for Skyrim: `C.Acoustic C.ImageSpace C.Location C.SkyLighting C.Regions`.

**Comment by WrinklyNinja** [comment]
Done in 5c5670d52f9de103bc576ef9c7210e28fa0245db

**Comment by Freso** [comment]
I thought part of the idea was to have the "hardcoded" list part of the games' masterlist, so updates/changes to it wouldn't be dependent on releasing a new version of LOOT, but could be pushed by a simple masterlist update…?

**Comment by WrinklyNinja** [comment]
Eh, I was being lazy. :stuck_out_tongue: If you think sourcing suggestions from the masterlist is worth it, open a new issue for it (since this one's not a breaking change, but that would be), and I'll get it done.

**Comment by Freso** [comment]
Would it really be a breaking change? Wouldn't the masterlist parser just ignore the unknown top-level tree, like it ignores `common:`? It's 2 AM though, so I guess I'll sleep on it and decide if I care enough to make a new issue for it one of the coming days. ;)

**Comment by WrinklyNinja** [comment]
You're right, it's not a breaking change. You're an hour ahead of me, but still more awake than I am. :tired_face:

**Comment by WrinklyNinja** [comment]
Reopening this until I've had a go at implementing the masterlist integration.

**Comment by WrinklyNinja** [comment]
Done in ab5bdd26f9197217d39e3cd8de8e10e356477dc3

**Comment by Freso** [comment]
Do you want to do the work of moving the bash tags to the masterlists, or should I do it?

**Comment by WrinklyNinja** [comment]
If you're happy to, go ahead.

**Comment by Freso** [comment]
- [ ] Fallout 3: https://github.com/loot/fallout3/commit/cd79277542bcc1feca27a9a072f48fd02b258622
- [ ] Fallout NV: 
- [ ] Fallout 4 apparently doesn't have any yet.
- [ ] TES3:
- [ ] TES4:
- [ ] TES5:

**Comment by Freso** [comment]
All masterlists except for FO4's have `bash_tags` lists now. Will LOOT just ignore if no `bash_tags` list is present, or should I add an empty list to FO4's? (I'm thinking it ignoring it if there's no `bash_tags` would be preferable.)

**Comment by WrinklyNinja** [comment]
If `bash_tags` is not present, LOOT just provides no autocomplete
suggestions.
