### ISSUE TITLE
LOOT crashes when hitting "Sort Plugins"

### ISSUE THREAD

**Issue by zer0fr0st** [loot/loot#294]
After I get blue screen while running LOOT, now it stop working while hitting "Sort Plugins". When I hit Edit metadata it shows me this: "An unhandled exception occured. Press "Abort" to terminate the program, "Retry" to exit the program normally and "Ignore" to try to continue".

**Comment by LordOfLA** [comment]
I am seeing an intermittent crash on LOOT 0.8 when hitting sort plugins. I've just read the "how to report wiki" and have enabled debug logging. Next time I see it crash I'll see about posting the log somewhere and updating.

It doesn't always crash, I can re-run LOOT through Mod Organiser and sort plugins without an issue all the times I've had it crash first time so far.

This is with Mod Organiser 1.3.8 sorting Skyrim mods following Neovalen's guide over at http://wiki.step-project.com/index.php?title=User:Neovalen/Skyrim_Revisited_-_Legendary_Edition

If you need details beyond debug log once I'm able to get one let me know. It may be some time before I update.

**Comment by WrinklyNinja** [comment]
Also [reported](http://forums.bethsoft.com/topic/1519842-rel-loot-thread-19/?p=24203916) by Baern.

> If you need details beyond debug log once I'm able to get one let me know. It may be some time before I update.

If you do manage to reproduce the crash, a debug log would be helpful.

**Comment by LordOfLA** [comment]
Okay here we go. Crash log for loot 0.8.0 after hitting sort plugins. Ran fine without issue on immediate second attempt 

http://pastebin.com/Fa74D81q

**Comment by WrinklyNinja** [comment]
Hmm, I suspect a multithreading issue here, as multiple plugin loading threads may attempt to access the same CRC cache, and cause a crash. I thought I had mutex locking to prevent this, but it seems not. Maybe I accidentally removed it when overhauling the loader...

**Comment by WrinklyNinja** [comment]
@LordOfLA: I have uploaded a new build with mutex locking in the `thread-safety` folder [here](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0). Could you try it and let me know if the issue still occurs?

**Comment by LordOfLA** [comment]
Have downloaded and installed it. Will let you know how it goes. Could be a while again, given how random the issue was to begin with.

**Comment by LordOfLA** [comment]
I've not had any crashes when sorting over the last 2 weeks. I've been using it pretty extensively as I've been tweaking mods I'm using. In order to add extra demand to loot (and because I prefer a full re-sort each time I use loot) I've been deleting the loadorder.txt and lockedorder.txt text files from my Mod Organiser profile each time before running loot.

If I encounter any more crashes after this post I'll update.
