### ISSUE TITLE
"Several fixes for bugs inside Vault 106" => version:106

### ISSUE THREAD

**Issue by Freso** [loot/loot#298]
The `SNAM` for `Vault 106 Fixes.esp` reads
> Several fixes for bugs inside Vault 106

This gets translated by LOOT as the mod having a version of "106".

![Screenshot, LOOT](https://i.imgur.com/IBjffgl.png) ![Screenshot, FO3Edit](https://i.imgur.com/ywvZlpo.png)

**Comment by WrinklyNinja** [comment]
This is fixed in a48b3df76b2c09c76344f32153555ac35c78e10c by disabling the regex responsible. It shouldn't affect very many true positives, as it's a last-ditch attempt at version extraction.
