### ISSUE TITLE
Force LOOT to run with admin privileges

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#370]
Suggested by @freesimpleryan, to catch users who don't realise that UAC causes issues when modding. Granting admin access to LOOT as a workaround is the easiest solution.

Forcing LOOT to run as an admin would help it "just work" for users, but I don't like the idea of granting unnecessary system access, and I suspect that users would just run into the same issue when they started using more utilities, so there's a sense that it's better to gain the understanding of why admin access is required at an early stage.

It's also worth noting that LOOT (at least v0.7) does give a permissions error message when trying to apply a sorted load order to a directory protected by UAC, and that Skyrim isn't affected at all.

**Comment by WrinklyNinja** [comment]
Alternatives suggested by others include:

* Noting UAC and admin permissions in the first-time tips dialog.
* Prominently displaying the information in the readme.

**Comment by Arthmoor** [comment]
I'd go with the tooltip and readme prompting. Granting automatic admin access would be bad from a security standpoint. That's something the user should always need to affirm themselves.

**Comment by steamb23** [comment]
Maybe, would not you add to the compilation options?
```
SET_TARGET_PROPERTIES(your-target-name PROPERTIES LINK_FLAGS /MANIFESTUAC:"level='highestAvailable'")
```

**Comment by WrinklyNinja** [comment]
> Maybe, would not you add to the compilation options? (I don't know about the CMake.)

I could, but I don't think I should.

**Comment by Freso** [comment]
I'm with @Arthmoor. Enabling this behaviour is an ugly road to begin walking down. Let's raise user awareness instead.

**Comment by WrinklyNinja** [comment]
With the two of you validating my opinion, I'll close this. :P
