### ISSUE TITLE
Better Chinese and Korean font support

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#384]
LOOT uses the Roboto font for Latin, Greek, and Cyrillic scripts, but falls back to the system font for others. This looks ugly, and Google suggest using their Noto fonts to cover all other scripts.

However, there are quite a few Noto fonts, and they are together quite large. The web-hosted fonts only support a very limited number of scripts (only two not covered by Roboto), so they're of no use, and that means two things:

1. LOOT needs to include `@font-face` CSS rules for each Noto font it supports.
2. Each Noto font needs to be on the user's computer.

Since the full set of Noto fonts is large in both number and file size, LOOT needs to choose what to support, and given that it has translations for them, Chinese and Korean are the obvious choices. Their font files are still 83 MB compressed though, so they can't be bundled with LOOT.

As a workaround, what could be done is to add `@font-face` CSS rules for those font files to LOOT, then post a note somewhere (the wiki?) detailing how to download and install the fonts for LOOT to use. Some Korean and Chinese speakers may not be able to find this information, but it only takes someone to translate it then share it for it to be useful.

**Comment by WrinklyNinja** [comment]
I have added some information on using the Noto fonts to the [wiki](https://github.com/loot/loot.github.io/wiki/Using-Noto-fonts-for-Chinese-and-Korean-in-LOOT). I'll need to update the page and add it to the sidebar once the next beta is released.

**Comment by steamb23** [comment]
Probably be like this change. (Recommended Font order)

font:11pt/1.429 Roboto, Noto, sans-serif;
to
font:11pt/1.429 Roboto, Noto, 'segoe UI', 'Microsoft Yahei', 'Microsoft Jhenghei', meiryo, 'malgun gothic', sans-serif;

segoe UI: English(Maybe you do not need.)
Microsoft Yahei: Simplified Chinese
Microsoft Jhenghei: Traditional Chinese
meiryo: Japanese
malgun gothic: Korean

**Comment by WrinklyNinja** [comment]
Thanks for the suggestions, I've added the Simplified Chinese and Korean fallbacks in 71ca53855badd1adfd0f7a89676968535f1c1f6c.
