### ISSUE TITLE
LOOT 0.6.1 is ignoring the user added BASH tags

### ISSUE THREAD

**Issue by clampi** [loot/loot#394]
Bash tags from userlist.yaml are ignored. They don't get reported into the sorting summary. I am not sure, but they also may be ignored when queried by Wrye Flash.

![result](https://cloud.githubusercontent.com/assets/10470629/5725066/918bbd64-9b58-11e4-88a7-8563dae26ee3.png)
![usersettings](https://cloud.githubusercontent.com/assets/10470629/5725065/918af050-9b58-11e4-97e1-3b9d45497acd.png)

**Comment by WrinklyNinja** [comment]
Can you test whether this happens with the 0.7 beta?

**Comment by clampi** [comment]
it does, but does not seems to be able to edit the ones from userlist.yaml. It shows them in the report window, but when I try to edit the metadata, only the ones from masterlist show.
![0 7 0b3](https://cloud.githubusercontent.com/assets/10470629/5725458/9f78d922-9b5b-11e4-8881-983d58f57958.png)

**Comment by WrinklyNinja** [comment]
Hmm, you're right.
