### ISSUE TITLE
Cannot edit LOOT's metadata from the UI

### ISSUE THREAD

**Issue by Thallassa** [loot/loot#413]
I am speaking of the built-in metadata, not user-added data.

It is not possible to remove or edit these rules in the UI. 

Sometimes these rules are incorrect. For example, one user reported "The load order should be Moon and Star -> Undeath -> Moon and Star Undeath Patch. LOOT insists that MAS's Undeath patch should load before Undeath."

Another example: "AOS.esp should should after Realistic Water Two.esp"

In the latter example it is actually up to user discretion which order they should load. Realistic Water Two.esp can load second if the patch is used, or AOS.esp can load second and then no patch is needed. 

Because it is only a minor conflict and is up to user discretion, this should not be hard-coded into the UI. At the very least this rule should be removed in future updates of the masterlist, but since it is impossible to ensure that the masterlist is always 100% correct, it would be best to make it possible to edit these data. If one is concerned about under-educated users editing metadata that they should not, there is always the option of adding a big warning box when one elects to edit the masterlist from the UI.

**Comment by WrinklyNinja** [comment]
This is intentional, because users could fix any incorrect metadata themselves, they would probably not bother or forget to report it to the masterlist maintainers, so the actual problem wouldn't get fixed.

I have removed the MAS - Undeath patch from Undeath.esp's after metadata.

I looked at the AOS - RWT patch, and I could add a condition so that AOS loads second only if no patch exists, but don't see why you'd want to use the patch, given that you don't need to...

**Comment by Thallassa** [comment]
Thank you for the response!

As far as AOS-RWT, conflict resolution for other mods becomes much more
simple when AOS early and RWT loads late.  However, for most users this
probably won't be an issue.

**Comment by WrinklyNinja** [comment]
I have now added the condition I mentioned to AOS.esp's load after metadata, so it won't force RWT to load first if the patch is present. Does that resolve your issue?

**Comment by Thallassa** [comment]
Yes, it works as I want it to now. Thank you!

**Comment by afonik** [comment]
I usually merge the compatibility patches and that includes AOS - RWT patch. This way I cannot force AOS.esp to load before RWT.esp.
Does LOOT have an OVERRIDE rule as BUM had?
Thanks. 
PS: I see the thread is close but as I reached here googling I don't really know were to post.

**Comment by WrinklyNinja** [comment]
> I usually merge the compatibility patches and that includes AOS - RWT patch. This way I cannot force AOS.esp to load before RWT.esp.
> Does LOOT have an OVERRIDE rule as BUM had?

No, it doesn't, but if you want AOS to load before RWT, just add AOS to RWT's "load after" metadata in LOOT.

**Comment by afonik** [comment]
I'm getting 
ERROR
Error code: 14; Failed to sort plugins. Details: Cyclic interaction detected between plugins "RealisticWaterTwo.esp" and "AOS.esp". Back cycle: AOS.esp, RealisticWaterTwo.esp

**Comment by afonik** [comment]
It's done
The only thing I have to do is put AOS2_RealisticWaterTwo Patch.esp) in the load order and then disabled it. This way loot sorts it as I want by default.
I used an empty .esp so Mod Organizer warns me of it and I remember what I've done.
Thanks for taking your time answering me

**Comment by WrinklyNinja** [comment]
> I'm getting 
> ERROR
> Error code: 14; Failed to sort plugins. Details: Cyclic interaction detected between plugins "RealisticWaterTwo.esp" and "AOS.esp". Back cycle: AOS.esp, RealisticWaterTwo.esp

Oh, yeah, silly me. That'll happen if you don't have the patch (or as you've done, a blank plugin of the same name).

**Comment by wolfgarr15** [comment]
having to load an empty plugin is not a valid solution in my book. Users should be able to delete default load order rules. Otherwise, it makes LOOT more of a burden than a helpful tool for users who merge mods.

**Comment by WrinklyNinja** [comment]
> having to load an empty plugin is not a valid solution in my book. Users should be able to delete default load order rules. Otherwise, it makes LOOT more of a burden than a helpful tool for users who merge mods.

You could also give the merged plugin a different filename. That way LOOT won't match it against any metadata and it's clearer to you that it is a merged plugin. That seems like an equally valid solution, and one that doesn't have the potential pitfalls that allowing deletion of masterlist metadata would have.

**Comment by swarnadeep** [comment]
Hi, I really didn't want to necro a closed issue like this, but I wanted to point out that the default load order in loot for Relationship Dialogue Overhaul (RDO), Cutting Room Floor (CRF), Guard Dialogue Overhaul (GDO), Weapons Armor Clothing and Clutter Fixes (WACCF) and Alternate Start, Live another life (ASLAL) have the wrong load order. The correct order is 
-RDO
-CRF
-GDO
.
.
-WACCF
.
.
-ASLAL
