### ISSUE TITLE
Blank Screen - Mod Organizer

### ISSUE THREAD

**Issue by vontrocken** [loot/loot#415]
Version 6 

Through mod organizer - blank screen, and then window which says " Navigation cancelled"

Version 7 - i cant even start it through mod organizer, so i cant provide any debug log for it ;/

Through mod organizer 
"Failed to load URL file:///D:/Steam/SteamApps/common/Skyrim/resources/report/index.html with error (-6)."
Through explorer - seems working 

IE version 11. Java updated. Thing in IE which allows another programs sth - checked

Any ideas how to fix this ? Will that help ? 
http://support.microsoft.com/en-us/kb/967941 

+ 
Debug from Version 6 
gist:311952d3fd556d519a43

+ 

Fix for WinSock doesnt work for me

I think its most important thing cause like in this video : https://www.youtube.com/watch?v=Rz6xR1Q1zuE 

It worked here as intended

**Comment by WrinklyNinja** [comment]
I don't know about getting v0.6 to work, but it looks like you have v0.7's launch settings in MO set up wrong, unless you've installed LOOT into your Skyrim folder. Make sure the `Start in` field is empty in MO's launcher settings.

**Comment by vontrocken** [comment]
I installed Loot in Skyrim folder. However after i cleaned start in field LOOT is working correctly with Mod Organizer. Thanks !
