### ISSUE TITLE
Caught Unhandled Unknown Exception

### ISSUE THREAD

**Issue by RoobBarrett** [loot/loot#416]
Everytime I try to run LOOT through Mod Organizer, I get a message box saying "*** Caught unhandled unknown exception; terminating" and loot closes. I have no idea why. 
![image](https://cloud.githubusercontent.com/assets/11923469/7114498/cf5a9476-e1d5-11e4-91af-73b35ed6f91a.png)

**Comment by WrinklyNinja** [comment]
What version of LOOT are you using, and does it happen with the latest v0.7 beta?

**Comment by RoobBarrett** [comment]
I'm in work right now I'll check when I get home and let you know.
Thanks for the speedy reply.

**Comment by RoobBarrett** [comment]
![image](https://cloud.githubusercontent.com/assets/11923469/7136380/40ce12fe-e2a8-11e4-93e9-04abb81b328d.png)
I was using 6.1.0, downloaded the beta version, and everytime I try to run that it crashes instantly. 
![image](https://cloud.githubusercontent.com/assets/11923469/7136410/7a230528-e2a8-11e4-8d72-4771ac23fba4.png)

**Comment by WrinklyNinja** [comment]
OK, weird. Please [provide a debug log](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully).

**Comment by RoobBarrett** [comment]
I'll do so first thing in the morning.

**Comment by RoobBarrett** [comment]
Thanks

**Comment by RoobBarrett** [comment]
Sorry I haven't been home yet, my friend got evicted from their house I
wentbdown there to help them pack up and stuff

**Comment by RoobBarrett** [comment]
http://pastebin.com/rBejuGWi

Hey sorry this took so long, here's the debug log.

**Comment by WrinklyNinja** [comment]
It seems to be crashing either when it's trying to get the Registry entry for Fallout 3, or just after. Does LOOT crash if you run it without going through MO? Try running Fallout 3's launcher, then see if LOOT still crashes.

**Comment by RoobBarrett** [comment]
I shall try that in the morning and let you know, thank you.

**Comment by RoobBarrett** [comment]
Hey sorry I still haven't been home, have exams on now so I've been staying
with a mate in college to study. Will try that in the next few days and let
you know.

**Comment by RoobBarrett** [comment]
Hey I tried that, fallout three doesn't exist on my computer, I don't have
it installed, only fallout new vegas.

**Comment by WrinklyNinja** [comment]
OK, can you try [this snapshot build](https://www.dropbox.com/s/m74ddyqlcwospcf/LOOT%20v0.7.0-beta.4-50-g27edd15.7z?dl=0) and see if it works?

**Comment by RoobBarrett** [comment]
Will do.

**Comment by RoobBarrett** [comment]
Nope, same thing as usual. 
![image](https://cloud.githubusercontent.com/assets/11923469/7433090/ce44fcf8-f025-11e4-8ec9-9b579697d494.png)

**Comment by WrinklyNinja** [comment]
Have the debug log contents changed?

**Comment by RoobBarrett** [comment]
http://pastebin.com/sz3W1ucY

**Comment by RoobBarrett** [comment]
I could install a fallout three and run the launcher to see if that does
anything?

**Comment by WrinklyNinja** [comment]
If you've got FO3, and it's not too much to download just to debug this issue, sure. That would help narrow down whether it's an issue with Registry check for FO3, or if it's failing on something after. I think FONV should be checked for next though, and I don't have any reason to suspect that would cause the issue...

Before you do download FO3, try deleting your `%LOCALAPPDATA%\LOOT\settings.yaml` file and running LOOT again. Maybe there are some corrupted settings.

**Comment by RoobBarrett** [comment]
Tried deleting that file, didn't work, tried installing fallout three and
running it, that didn't work either.

**Comment by RoobBarrett** [comment]
Debug log didn't change after either of them.

**Comment by WrinklyNinja** [comment]
OK, new [snapshot build](https://www.dropbox.com/s/uczc2tv1v97q2a1/LOOT%20v0.7.0-beta.4-52-gf0b95b9.7z?dl=0). This should provide an error message instead of crashing: let me know what the message says if so.

**Comment by RoobBarrett** [comment]
Okay, this one isn't crashing or showing an error, but it isn't reading any of the mods. 
![image](https://cloud.githubusercontent.com/assets/11923469/7445035/2c74a430-f199-11e4-911d-0f0cdb46cbc2.png)

**Comment by WrinklyNinja** [comment]
What about your debug log?

**Comment by RoobBarrett** [comment]
This time it actually gave a filepath for the fallout 3 resources it
couldn't access, which were leading through my brothers user account. I
gave myself access to them through the securities in their properties, ran
the loot snapshot build 2, and it ran perfectly.
So that seems to have been the problem.

**Comment by WrinklyNinja** [comment]
Could I get the actual log, so that I can at least stop LOOT from crashing in such cases in the future?

**Comment by RoobBarrett** [comment]
Yeah of course.

**Comment by RoobBarrett** [comment]
Okay it's changed again since I've run it and it worked sorry.
This is what it says now http://pastebin.com/2yh2hKBS

**Comment by WrinklyNinja** [comment]
Removed this from the v0.7.0 milestone because I can't fix it without debug information.

**Comment by RoobBarrett** [comment]
Thanks for all your help.

**Comment by Talyna23** [comment]
Same problem here.
Running LOOT through NMM (Nexus ModManager).
My debuglog reads:

[12:30:45] [info]: LOOT Version: 0.6.1
[12:30:45] [debug]: Initialising language settings.
[12:30:45] [debug]: Selected language: Deutsch
[12:30:45] [debug]: Detecting installed games.
[12:30:45] [info]: Setting new details for game: TES IV: Oblivion
[12:30:45] [info]: Setting new details for game: TES V: Skyrim
[12:30:45] [info]: Setting new details for game: Fallout 3
[12:30:45] [info]: Setting new details for game: Fallout: New Vegas
[12:30:45] [info]: Setting new details for game: TES IV: Oblivion
[12:30:45] [debug]: Selecting game.

Read in another forum, this message (topic) shows when not heaving the newest directx version.
Should be no problem here, 'cause mine is actual...
But maybe the hint helps...?

**Comment by WrinklyNinja** [comment]
> Read in another forum, this message (topic) shows when not heaving the newest directx version.
> Should be no problem here, 'cause mine is actual...
> But maybe the hint helps...?

If it's the same problem, it's got nothing to do with DirectX. Does the crash happen when you use the latest v0.7.0 [snapshot build](https://www.dropbox.com/s/rpzafd2phborpfc/LOOT%20v0.7.0-beta.4-65-g7a48820.7z?dl=0)?

**Comment by Talyna23** [comment]
Does't start either...
Here's what Win7 says (sorry, it's in German):

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	LOOT.exe
  Anwendungsversion:	0.7.0.0
  Anwendungszeitstempel:	554d1dfe
  Fehlermodulname:	LOOT.exe
  Fehlermodulversion:	0.7.0.0
  Fehlermodulzeitstempel:	554d1dfe
  Ausnahmecode:	40000015
  Ausnahmeoffset:	001fee80
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	022f
  Zusatzinformation 2:	022f0cdc748df82dd9b65585ae6e54c2
  Zusatzinformation 3:	e471
  Zusatzinformation 4:	e471bba2eda9208293edc8f78750dc1c

**Comment by WrinklyNinja** [comment]
> Does't start either...

Whenever you report a crash or any other issue, please also post the debug log. For now though, try the snapshot build [here](https://www.dropbox.com/sh/03pfrksk8hkmheh/AABCh0IBGhKxGIwYTzVkEuqka?dl=0).

**Comment by Talyna23** [comment]
Ok...
Maybe I'm doing something wrong, with the installation?
Downing the ZIP-unpacking to "any" location-starting loot.exe-->win7 telling me, that loot.exe isn't working anymore. So, there isn't a debug log at all... :(
To be precise...even the small window, with the message mentioned as topic doesn't flash up...

**Comment by WrinklyNinja** [comment]
The debug log should be created in `%LOCALAPPDATA%\LOOT\LOOTDebugLog.txt` even if LOOT crashes immediately, unless the crash happens before logging is set up (which is almost the first thing LOOT does).

If you're not seeing a debug log there, please double-check that you've followed the instructions [here](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully). Installation is just a  matter of unpacking the archive to any location, so you're doing that correctly.

**Comment by Talyna23** [comment]
Ok, think it's not my fault...^^
Tried now, to install the stable version (same result) and copied the snapshot build into the same folder, overwriting the stable one. no success...
And at %LOCALAPPDATA%\LOOT\ there is only an empty folder named Skyrim...
could this all be an anti-virus issue?

**Comment by Talyna23** [comment]
Aaah, wait a minute..got a settings.yaml this time
I try to upload...

**Comment by WrinklyNinja** [comment]
> Aaah, wait a minute..got a settings.yaml this time
> I try to upload...
> 
> Here we go:
> http://pastebin.com/mjbHKCai
> and for the second build:
> http://pastebin.com/CLGSbu8f

Interesting. I've uploaded a new build (68) to the [same folder as before](https://www.dropbox.com/sh/03pfrksk8hkmheh/AABCh0IBGhKxGIwYTzVkEuqka?dl=0). Can you try again with that? It should stop LOOT crashing at that point, and provide some more info in the debug log, though it'll probably crash at some point after.

**Comment by Talyna23** [comment]
Ok, fixed it and running!
Problem was "Oblivion".
LOOT couldn't find the installation path. I recently installed a SSD, which changed my drive-names. Oblivion was suposed on drive F:, but this is actually my blueray-drive...tried to change the insallation path ind some dll or ini...couldn't remember where, put in the Oblivion-CD in drive F:, started LOOT aaaaaaaand IT WORKED FLAWLESSLY!! :D 

Thanks for all the help!

Now I just have to find the installpath entry...

Here the last debuglog AFTER puttind CD into F:
http://pastebin.com/YA4LW6n4
Sorry that I can't provide the first debuglog after trying build 68...I was so exited by it's Oblivion-Enty, I instantly tried to fix it, an forgot to save it...
If, this time, I could provide any help or Info in return, I gladly try! 

Cheers,
Talyna

**Comment by WrinklyNinja** [comment]
OK, that gave me enough clues to replicate the issue and fix it, thank you.

**Comment by Talyna23** [comment]
Glad it helped! :)
Besides, my Skyrim seems much more stable with the new loadorder!
