### ISSUE TITLE
Provide feature for exporting load order with dec and hex indices.

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#437]
Wrye Bash is apparently the only mod manager that exports a load order with hex indices, which are useful for looking up mod objects in game, and it doesn't provide the decimal indices too, which has also been requested.

Since it seems that such a feature would be unique to LOOT, and useful to users, it's a good candidate for addition. It should be pretty easy too, and just requires a main menu entry to access it.

**Comment by InsanePlumber** [comment]
This is really great news.
