### ISSUE TITLE
LOOT not detecting Fallout 3 GOTY Version

### ISSUE THREAD

**Issue by Yijare** [loot/loot#448]
When launching LOOT Fallout 3 does not appear to be installed.
It detectes it when the folder within the SteamApps\Common\ folder is renamed to "Fallout 3" instead of "Fallout 3 goty"

**Comment by WrinklyNinja** [comment]
Have you tried running Fallout 3's launcher? Sounds like you have an old Registry entry for the non-GOTY version that needs updating.

**Comment by Yijare** [comment]
i did, i have to rename the folder for LOOt to detect it either way

**Comment by WrinklyNinja** [comment]
Could you send me your [debug log](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully) then?

**Comment by Yijare** [comment]
LOOT-debug
http://pastebin.com/9i47GSAt
CEF-debug
http://pastebin.com/bM4h2mMr

**Comment by WrinklyNinja** [comment]
Can you try the latest build (at the bottom) [here](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0)? If it still doesn't work, please post your LOOT debug log again.

**Comment by Yijare** [comment]
works now. thank you

**Comment by WrinklyNinja** [comment]
OK, closing this then.
