### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by MyHouseATL** [loot/loot#453]
Just installed new Loot.  However, when I start loot, I get a blank page.  How can I fix this.  (Use with Skyrim and Mod Manager in Windows 8.1 X64.)

**Comment by WrinklyNinja** [comment]
Which mod manager are you using? If it is Mod Organiser, try the suggestion in the [FAQs](https://github.com/loot/loot.github.io/wiki/LOOT-FAQs#loots-window-is-blank-when-im-starting-it-through-mod-organizer-whats-up).

**Comment by RorikC** [comment]
I have the same problem but I am opening it by the shortcut on the desktop

**Comment by WrinklyNinja** [comment]
Please post your [debug logs](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully).

**Comment by RorikC** [comment]
ok, I went to the link above about how to post your debug files. when I
opened settings.yaml , there was no "enableDebugLogging: false". I attached
that file also to look at. The only debug file in the loot folder is the
one I attached. Thank you for your help.

On Mon, Jun 29, 2015 at 3:07 AM, Oliver Hamlet <notifications@github.com>
wrote:

> Please post your debug logs
> <https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/loot/loot/issues/453#issuecomment-116514486>.
>

[0628/203516:WARNING:resource_bundle.cc(286)] locale_file_path.empty()
[0628/203516:ERROR:main_delegate.cc(550)] Could not load locale pak for en-US
[0628/203517:WARNING:resource_bundle.cc(286)] locale_file_path.empty()
[0628/203517:ERROR:main_delegate.cc(550)] Could not load locale pak for en-US

**Comment by WrinklyNinja** [comment]
> ok, I went to the link above about how to post your debug files. when I
> opened settings.yaml , there was no "enableDebugLogging: false". I attached
> that file also to look at. The only debug file in the loot folder is the
> one I attached. Thank you for your help.

Attaching files to email replies doesn't make them available on GitHub.

**Comment by RorikC** [comment]
The files are posted at http://pastebin.com/u/Rorik
I did find the spot to enable the debugging. The way notepad opens it, its hard to read and I just overlooked it. Thanx

**Comment by WrinklyNinja** [comment]
Try using v0.7.1, IIRC it fixed a blank screen bug.

**Comment by RorikC** [comment]
thank you. will give it a shot

**Comment by RorikC** [comment]
still the same blank screen. files are posted at http://pastebin.com/u/Rorik

**Comment by WrinklyNinja** [comment]
Looks like browser creation is failing for some reason. Try running LOOT with the `--single-process` argument.

If that doesn't fix it, I'll have to pause further investigation for a week, as I'm going to be "out of the office".

**Comment by RorikC** [comment]
That fixed it

**Comment by RorikC** [comment]
it works great now. is there any downside to running it like this?

**Comment by WrinklyNinja** [comment]
UI performance might be a bit slower, I've seen font rendering be a little worse, but nothing really significant AFAIK.

**Comment by RorikC** [comment]
awesome, thanx for all your help
