### ISSUE TITLE
Add `name`, remove `ver` for location metadata structure.

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#457]
Following feedback from loot/loot.github.io#38, I will remove the `ver` key from the location metadata structure, and add a `name` key. 

The `name` key will be used as the link text when constructing hyperlinks, and so could describe the mod (eg. `Russian translation`) or the site (eg. `Nexus`). It will be an optional key: if not specified then something else will be used as the link text, depending on context (as there are no current uses of the location metadata, this is a bit hard to pin down).

**Comment by Freso** [comment]
So this isn't "live" as per 0.7.1 so we'll need a new masterlist branch for 0.8.0?

**Comment by WrinklyNinja** [comment]
Yes, that's correct. v0.7.1 was only a minor release. The `ver` key is now
deprecated, ready for removal in v0.8.0.

**Comment by WrinklyNinja** [comment]
> So this isn't "live" as per 0.7.1 so we'll need a new masterlist branch for 0.8.0?

Though I should probably note that you *can* use the `name` key immediately, it'll just get ignored by current versions of LOOT. Useful if you want to start naming URLs right away.
