### ISSUE TITLE
Error Code 1; Game ID incorrect

### ISSUE THREAD

**Issue by The4ndx** [loot/loot#459]
![eror](https://cloud.githubusercontent.com/assets/13056402/8367301/64b4fc4e-1b62-11e5-99cc-ee0b4fadd1ff.jpg)

This is what appears me on LOOT. Is the first time installing and i don't know what to do.

**Comment by WrinklyNinja** [comment]
It looks like LOOT can't detect any supported games: try running the
game(s) launchers to add the required Registry entries.

**Comment by The4ndx** [comment]
Wow!! It worked!! Thanks :)
