### ISSUE TITLE
Convert installer to Inno Setup

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#467]
I can't download NSIS because SourceForge is currently down, and I don't particularly like NSIS anyway because:

* It has a weird scripting / declarative language.
* Protons decay in less time than its development cycle, the official Unicode version has been in beta for ages.
* Updating the script is a bit involved.

Given that, I thought I'd give Inno Setup a go, since it's the main competitor, and see how far I get before Sourceforge comes back up.

**Comment by WrinklyNinja** [comment]
Searching through the Registry after running the Inno installer shows that a key is created at `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{BF634210-A0D4-443F-A657-0DCE38040374}_is1`. This holds a whole bunch of subkeys, and is removed by the uninstaller.

For compatibility with other programs that detect LOOT installs, the Inno script should also create a key at `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\LOOT` as the NSIS script does.

**Comment by WrinklyNinja** [comment]
OK, so first impressions are that the basics are easier with Inno, and I particularly like how it automatically creates an uninstaller that by default removes all the files it installs.

However, there's no simple way to:

1. run any previously-installed LOOT's uninstaller before beginning the new installation
2. Set LOOT's language
3. Optionally uninstall user files

The first two aren't surprising, since I had to script that in NSIS too, but the third is a bit of a disappointment. At least the scripting is done in a proper language (Pascal), so I'll see how that goes.

**Comment by WrinklyNinja** [comment]
Another thing to note is that there aren't any official Simplified Chinese or Korean translations, but unofficial translations are [available separately](http://www.jrsoftware.org/files/istrans/).

**Comment by WrinklyNinja** [comment]
@loot/translators: I've machine-translated [some messages](https://github.com/loot/loot/blob/b9217d7a703d69155044bf1e2d4e7260b409f5bd/src/installer.iss#L169-L179), but it would be great if you could check your language's message and post a better translation (if there is one).

**Comment by WrinklyNinja** [comment]
The Inno installer can now set LOOT's language, and the implementation involves 98% less witchcraft than NSIS's. The Inno script is less than half the length of the NSIS script too, with only the uninstall-before-install left to do.

I think I can remove that question mark from the title now.

**Comment by WrinklyNinja** [comment]
Closing this, as I've squashed and merged my commits, so the switch has now been completed.

**Comment by lpradel** [comment]
The [German translation](https://github.com/loot/loot/blob/dev/src/installer.iss#L187) is fine as is.
