### ISSUE TITLE
An option to disable animations

### ISSUE THREAD

**Issue by Dol-phin** [loot/loot#475]
Can you add on option to disable animations in LOOT?

**Comment by WrinklyNinja** [comment]
I don't think it's technically feasible aside from a small subset of them
(dialogs, basically). Why would you want this?

**Comment by Translator5** [comment]
I thing its because of the "Program don't react" message" or the animation problem when you use more than 200 mods.
For me it's  so If I want to edit a File or I apply a Filter it is very laggy. (242esp's)

**Comment by WrinklyNinja** [comment]
> I thing its because of the "Program don't react" message" or the animation problem when you use more than 200 mods.
> For me it's so If I want to edit a File or I apply a Filter it is very laggy. (242esp's)

I'm not aware of any "program not responding" or animation problems with large mod sets, though I don't have many mods installed myself owing to switching machines recently.

Applying filters is known to be slow, but that's not because of animations.

**Comment by WrinklyNinja** [comment]
Closing this because disabling animations isn't feasible, and #434 and related JavaScript changes should resolve the performance issues.
