### ISSUE TITLE
Left Hand Rings and Dirty Plugins report

### ISSUE THREAD

**Issue by BlairInKW** [loot/loot#478]
Using the most recent masterlist, Loot is reporting that "LeftHandRings.esp" and "LeftHandRings - Dawnguard.eps" each contain 3 I'M records an recommends cleaning. The thing is I tried and TES5Edit reports them as clean and can find no ITMs.

**Comment by pStyl3** [comment]
[Left Hand Rings](http://www.nexusmods.com/skyrim/mods/21720)

LOOT reports the following:

LeftHandRings.esp
EDCE6FEB
3 ITMs

LeftHandRings - Dawnguard.esp
0665945A
3 ITMs

These itm values came from the recent commit of @shadowslasher410 [here](https://github.com/loot/skyrim/commit/f2d637a24a193521d30b0f8ed52e7bdf5e840d41). As it seems, these two reports of ITMs are unfortunately false aswell, both plugins are clean as of the latest version of xEdit, so they should be removed.

Seeing as more and more numbers seem to be incorrect, it would probably best to remove the whole batch of those reported 'dirty' plugins (aside Purity.esp, which is as said a legit case).

**Comment by WrinklyNinja** [comment]
OK, I'll revert the commit later today and then add the Purity.esp metadata back in.

**Comment by WrinklyNinja** [comment]
[Done](https://github.com/loot/skyrim/commit/9daec19544048cb18e4b0a25bc7e9c4f19e75700). Also, this isn't the proper place for this issue to be reported, this is the code issue tracker. In future please use the Skyrim masterlist [issue tracker](https://github.com/loot/skyrim/issues) instead.
