### ISSUE TITLE
error code 12

### ISSUE THREAD

**Issue by mrchaos500** [loot/loot#484]
every time i try to sort the plugins i get Error code: 12; Failed to update the masterlist. Details: An error occurred while trying to clone the remote masterlist repository.
any solutions? i have the current .80 build. running windows vista 32bit. LOOT has admin privileges. i really hope you can help since BOSS is no longer a valid organizer

**Comment by WrinklyNinja** [comment]
Are you on Windows Vista?

**Comment by mrchaos500** [comment]
yes

**Comment by WrinklyNinja** [comment]
Then this is a duplicate of #477. The latest snapshot build contains a fix.
