### ISSUE TITLE
Global priority sorting issue

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#486]
Global priorities seem to be ignored in certain circumstances, see [this bug report](http://forums.bethsoft.com/topic/1531778-rel-loot-thread-20/?p=24322400). I can't replicate this exact behaviour, but I do see Falskaar and Wyrmstooth loading before the High Resolution Texture Pack and its Unofficial Patch, even though the latter have a lower global priority, so the same issue is present.

**Comment by WrinklyNinja** [comment]
My replication is actually a false positive: the unofficial high res pack plugins are non-master plugins, so they must load after Falskaar and Wyrmstooth.

**Comment by PinkysBrain** [comment]
I have the same issue, the priority of ELE_Legendary_Fs_Wt_Lite.esp is 990100 and EnhancedLightsandFX.esp is 990050, yet the latter is sorted lower. If I remove my conflict resolution esps (which are forced into an order using load-after) they are sorted correctly.

This might be related to the bug, if I double click the an ESP to check out the priority I have set for it and then apply it subsequently shows it in the plugin list as having no user metadata. If I double click it again it still has the priority set, but it won't show the user metadata icon until I restart loot.

**Comment by WrinklyNinja** [comment]
Thanks for the log, I'll look into it when I have time. I edited your post to upload the log directly to GitHub (which is a new feature, just drag the file into the text box to do so), so that it can't get lost.

Could you also provide me with the link to whatever mod `ELE_Legendary_Fs_Wt_Lite.esp` is from?

**Comment by PinkysBrain** [comment]
It's from ELE - lite. In case the plugin list didn't look familiar, the mods are mostly Skyrim Revisited & REGS.

http://www.nexusmods.com/skyrim/mods/59733/?

**Comment by WrinklyNinja** [comment]
> If I remove my conflict resolution esps (which are forced into an order using load-after) they are sorted correctly.

I've figured out what's happening. 

Your three conflict resolution plugins are `SR Conflict Resolution.esp`, `REGS - SRLE conflict resolution.esp` and `conflict resolution personal.esp`. The first two both have `ELE_Legendary_Fs_Wt_Lite.esp` as a master, so inherit its priority of `990100`. The latter two are both set to load after the first.

`BetterQuestObjectives-Patches.esp` inherits a priority of `1990000` from something, and so loads before `EnhancedLightsandFX.esp` due to priority difference.

The problem is that `conflict resolution personal.esp` is not inheriting the inherited priority values of `SR Conflict Resolution.esp` and `REGS - SRLE conflict resolution.esp`, because priority inheritance is evaluated in alphabetical order, so the latter two plugins haven't yet inherited their priorities when the former is evaluated.

It therefore retains its priority of 0, so `BetterQuestObjectives-Patches.esp` loads after it, thus making `EnhancedLightsandFX.esp` load after `ELE_Legendary_Fs_Wt_Lite.esp`.

Now that I know why it's misbehaving, I need to think how best to fix it...

---

... I really need to output better debugging for sorting issues, a DOT file containing the constructed graph would be good. That's part of #377 though.
