### ISSUE TITLE
Node native module + Electron

### ISSUE THREAD

**Issue by noahlange** [loot/loot#492]
Love the work you're doing on LOOT. I've been putzing around in the repository and attempting a build on MacOS with the Linux build instructions... it's been an adventure, to say the least. :)

While attempting to build, the notion of a [native Node.js module](https://nodejs.org/api/addons.html) for LOOT came to mind. I don't know enough about C++ or the LOOT internals to know how much of a pain it would be to rewrite LOOT as a native module, but the process would have a few pretty great side effects.

1. CLI/programmatic usage of LOOT in JS. Being able to call something like `loot.query()` from JS code would be really neat and would open up a lot of doors in terms of node-based mod/load-order managers.
2. And more importantly, a native module would allow it to be wrapped into an Electron/nw.js app. Few benefits there:
  - would simplify a lot of the complications that exist re: maintaining a GUI application
  - would have cross-platform support baked in
  - would be a lot less intimidating to contribute to for front-end developers than it is right now, myself included

Anyway, feel free to disregard or ignore. As a node dev who loves LOOT and would be thrilled to work with it programmatically / contribute, thought I'd offer the suggestion.

**Comment by WrinklyNinja** [comment]
You're talking about making the backend a native Node.js module, right? In which case:

1. A wrapper around the API would be sufficient, and likely far less complex to implement. I'm not interested in doing it, because it provides LOOT itself with no benefit, and the third sentence of that Node.js page you linked is `The API (at the moment) is rather complex, involving knowledge of several libraries`. Anyone else is free to do it though.
2. I don't see any benefit to using Electron over CEF. The only functional difference is probably that you call native code like any other JS function, rather than sending queries, but that's hardly a pain, and not worth adding a Node.js runtime dependency for.
  * I'm not sure what complications would be simplified, could you give examples?
  * LOOT already has pretty good cross-platform support. There's very little OS-specific code, probably only 5 or so bits of functionality, and it's all clearly marked out. It took a couple of hours to add the ability to build and package a native Linux GUI this weekend.
  * How? The frontend is the same HTML/JS/CSS that you'd be working with if LOOT were Electron-based. I mean, I know my JS is a mess, but using Node doesn't enforce good design.

**Comment by noahlange** [comment]
> You're talking about making the backend a native Node.js module, right? In which case:

> A wrapper around the API would be sufficient, and likely far less complex to implement. I'm not interested in doing it, because it provides LOOT itself with no benefit, and the third sentence of that Node.js page you linked is The API (at the moment) is rather complex, involving knowledge of several libraries. Anyone else is free to do it though.

You're right - it doesn't provide LOOT, as it stands, with any benefit. Best case scenario, there would be no difference to 90% of the end-users. And I understand that that might be a deal-breaker. But it would (and in this case, yeah, would probably be a wrapper around the API) provide developers the ability to use LOOT's functions from an arbitrary JS context.

That could be mod sites that use LOOT to evaluate load orders before a user download them. That could give CLI or GUI package managers that resolve dependencies (like YAMM) the ability to resolve load order issues automagically when users download new mods, or warn users before downloading that they might face compatibility issues. Either of those would be huge, game-changing features for the modding community.

> I don't see any benefit to using Electron over CEF. The only functional difference is probably that you call native code like any other JS function, rather than sending queries, but that's hardly a pain, and not worth adding a Node.js runtime dependency for.

Mmhmm. You're right - as stated above, there wouldn't be much of a functional difference. It wouldn't add anything to the LOOT library / app as it stands, it would simply make its capabilities available outside of the LOOT app.

> I'm not sure what complications would be simplified, could you give examples?

Autoupdating, crash reporting, packaging, installers. Just boilerplate stuff that you could foist upon front-end devs and the Electron maintainers instead of dealing with yourself. ;)

> How? The frontend is the same HTML/JS/CSS that you'd be working with if LOOT were Electron-based. I mean, I know my JS is a mess, but using Node doesn't enforce good design.

You're right - switching to Node does not enforce good design, and the Lord knows Node's enabled more than its fair share of bad design in the last five years. But I would argue that separating into a two repos, one a C++ library and the other an HTML5 app would be good design. Separate concerns - keep the GUI with the GUI and keep the library self-contained. That way you lower the barrier of from "able to do a smattering of both C++ and JS" - which to be honest, is pretty rare - to "only does C++" or "only does JS."

Please know I'm not trying to insult you guys or your work - as noted above, I love LOOT, and y'all have saved my load order countless times. So, lest I forget, thank you so much! And BTW, your JS is really not bad at all. :)

**Comment by WrinklyNinja** [comment]
> Autoupdating, crash reporting, packaging, installers. Just boilerplate stuff that you could foist upon front-end devs and the Electron maintainers instead of dealing with yourself. ;)

Well, I already have scripts for the latter two, I don't have the confidence to use autoupdating (eg. the UI has no tests) and I'm not too bothered by crash reporting... A quick look at the docs does show that it's a more well-rounded framework for building cross-platform apps off than CEF, but LOOT is already invested, and cross-platform is hardly a priority given everything it works for are Windows games.

> But I would argue that separating into a two repos, one a C++ library and the other an HTML5 app would be good design.

Right, but the operations that the API allows are less than what the GUI's C++ code uses, so I'd have to greatly extend the API, write a wrapper for Node.js, and end up with a codebase that's much larger, just to implement functionality I have currently.

I don't want to be developing LOOT for the rest of my life. I've already got a long list of significant issues to work on, and the Polymer update is providing to be incredibly difficult to perform. Switching to Electron wouldn't help with any of those issues, just give me more work to do.

**Comment by noahlange** [comment]
> I don't want to be developing LOOT for the rest of my life. I've already got a long list of significant issues to work on, and the Polymer update is providing to be incredibly difficult to perform. Switching to Electron wouldn't help with any of those issues, just give me more work to do.

I don't blame you - and you're right that it wouldn't help with any of the outstanding issues, In fact, the only way it would alleviate those at all would be to lower the barrier of entry for other folks to contribute on the front end.

> Also, I'm a bit disenfranchised about building web UIs. There's a lot of freedom, but there's also a startling number of things that just don't have APIs, or which have bizarre (in the desktop world) limitations, thanks to the web's origins and nature making some things a Bad Idea. It's also incredibly difficult to get a UI that's performant, it's a constant struggle.

What sorts of APIs don't you have access to / have excessive limitations? I don't know exactly what chromium embedded gets you, but if it's not anything more than a browser window, then I imagine it'd be a pain in the ass.

**Comment by WrinklyNinja** [comment]
> I don't blame you - and you're right that it wouldn't help with any of the outstanding issues, In fact, the only way it would alleviate those at all would be to lower the barrier of entry for other folks to contribute on the front end.

Perhaps, but contributing on the front end only needs C++ skills if you want to get/set data from the backend, or call functions, that aren't already available. Admittedly, this might stop people from adding many new features, but purely modifying the UI doesn't require any of that.

> What sorts of APIs don't you have access to / have excessive limitations? I don't know exactly what chromium embedded gets you, but if it's not anything more than a browser window, then I imagine it'd be a pain in the ass.

CEF gives me a Chromium window, plus the ability to call C++ from JS and vice-versa, redirect URLs, etc. It's pretty good, there's nothing CEF-specific that I've run up against. (I did type out a reply to your actual question, but it turned into a rant...)

**Comment by WrinklyNinja** [comment]
Anyway, closing this as I'm not going to do it.
