### ISSUE TITLE
Blank UI when launched directly or through NMM

### ISSUE THREAD

**Issue by ghost** [loot/loot#493]
I have a blank UI whenever I open LOOT by double-clicking on the executable or running it through NMM. Mod Organizer is not installed on my computer. LOOT was originally installed to Program Files, I reinstalled it to C:\Games and it still has a blank UI. I am running Windows 10 and have tried compatibility mode for Windows 8.

NMM is v0.60.14
LOOT is v0.8.1, installed with Loot.Installer.exe
Skyrim v1.9.32.0, Steam version
SKSE v1.7.3

**Comment by WrinklyNinja** [comment]
Please [provide](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully) your debug logs.

**Comment by avuong2962** [comment]
Debug logs:
http://pastebin.com/vqBk61C9

**Comment by WrinklyNinja** [comment]
Odd, I expected to see some errors (ignoring the extensions error, that's unimportant) in the CEF debug log. Instead that looks fine but the LOOT debug log looks incomplete, it gets to evaluating the general messages then stops...

LOOT isn't crashing then, is it?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
