### ISSUE TITLE
Store LOOT configuration in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by Freso** [loot/loot#494]
Rather than saving configuration in a subfolder to the binary, save configuration in the standard location for configuration files as per the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

I would suggest something like:
```
if ($XDG_CONFIG_HOME): save_to($XDG_CONFIG_HOME/loot)
else: save_to($HOME/.config/loot)
```

**Comment by Freso** [comment]
Maybe it would make sense to additionally allow for a local settings file/directory, to allow for "portable" LOOTs (ie., like it currently does)?

**Comment by WrinklyNinja** [comment]
I don't see the benefit of having a portable LOOT, I don't think the games
are portable. It's probably just needless complication.

**Comment by Freso** [comment]
Possibly. :) I guess it won't be *that* hard to bring it back if it turns out it's needed?

**Comment by WrinklyNinja** [comment]
No, it should be straightforward, but it's still not a feature I'd want to
keep speculatively, since we'd have to add a CLI switch to control whether
LOOT ran portably or not.
