### ISSUE TITLE
Copying to clipboard is unimplemented

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#497]
Using LOOT's "Copy Load Order", "Copy Content" or "Copy Metadata" functionality will have no effect on a Linux build, as copying to the clipboard isn't implemented. The Windows implementation uses the Win32 APIs to interact with its clipboard.

In #491, @Freso suggested using xclip:

> There's [xclip](http://xclip.sourceforge.net/), which is a neat little command-line utility I often resort to in shell scripts etc. It can either be interfaced with directly, or you can poke through the code (it's GPL v2-or-later, so it can be copied willy-nilly into LOOT) and see how they deal with clipboards under X/Linux.

However, I wonder about stuff like Wayland replacing X in the near future (for example in Fedora 24, which is apparently early next year). From what I can tell, Chromium supports either backend and at the moment is generally built on X, so maybe it's not something to worry about until when/if it switches.

There's also the possibility that there's some API in CEF that I've overlooked that can abstract away the details without requiring an external utility to be called (which I'd probably prefer over including X-specific code).

**Comment by Freso** [comment]
I wouldn't worry too much about Wayland before it's actually here. It's been coming "in the near future" for years. Yes, that "near future" is more near now than it was a year ago, but I'm not holding my breath. X has been around for years and years and years and years and years and years, it's not going to just disappear within one.
