### ISSUE TITLE
Search not working conistently

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#499]
Moved from loot/loot.github.io#47, which was filed by @koumdros:

>I've been having this issue since level 8,0 and it is the same with 8.1
>
>Usually if i try to search for a term ( usually a word contained within an eps's name ) it sometimes finds the first instance of that word, and doesnt find anything else, or doenst actually seem to do anything.
>
>Sometimes the right hand panel ( with the esp modules) seemingly refreshes, but the reults dont actually have the word I;m searching for, in fact it seems all the esps are there ..
>Othertimes everything works normally..
>
>is there a way to increase loging verbocity to get more visibility?

**Comment by WrinklyNinja** [comment]
Can you give me a specific example where the search behaves unexpectedly? 

The right-hand panel does not refresh when you search, only the cards list scrolls to the first/next match.

There's no way to increase logging verbosity: the UI JavaScript code currently only logs when it encounters an error.

**Comment by koumdros** [comment]
sorry for the delay, been working allnighters around the clock...
when you say example, should I try for a screen shot, or would the info of search item and results be enough? 
I was probably a bit blurry when I wrote the original post, so lets clarify: 
the right hand pane didnt scrol to the next match or it did scrol lto one containing something irelevant. I'll try to duplicate the effect as tonight everything works normally. 

btw I'm runing LOOT from inside M.O. while doing all this.

**Comment by WrinklyNinja** [comment]
Info on the what to search and what happens should be enough, I just need to be able to replicate the issue.

**Comment by WrinklyNinja** [comment]
Given that the search functionality has been reimplemented since this issue was filed, I'm closing it as most likely fixed - if it's not, the issue can be re-opened.
