### ISSUE TITLE
game finding issue

### ISSUE THREAD

**Issue by Ironbloodclaw** [loot/loot#501]
it seems if you mess with certain games enough it can never find them again i moved my skyrim game from my external drive to an internal one and then just stop trying to find it after i had to delete it's old route to the other drive i even tried to delete loot then reinstall or redownload didn't work might be an error in the code that gets left over but not sure since i'm not a deep programmer and know only so little of how to mess with mods and certain files on my computer so can i get some help on this or maybe suggest an update to fix this maybe some way to input where the game is through another way besides putting in it's file path name which is really hit and miss

**Comment by WrinklyNinja** [comment]
I'm having an issue finding any punctuation in there...

**Comment by Ironbloodclaw** [comment]
sorry not really used to using it for alot of reasons

**Comment by EpicBurrito** [comment]
Have you run Skyrim through Steam since you moved it, or exclusively
through a Mod Manager? Make sure you've run the launcher at least once.

**Comment by WrinklyNinja** [comment]
> sorry not really used to using it for alot of reasons

I can't help you if you can't effectively communicate your problem.
