### ISSUE TITLE
Fallout 4 Support

### ISSUE THREAD

**Issue by audjack99aus8** [loot/loot#504]
How do we get loot to work with fallout 4 please?

**Comment by WrinklyNinja** [comment]
Fallout 4 support will be added in due course. Until official modding tools
are created, using any mod plugins is very inadvisable anyway.

**Comment by WrinklyNinja** [comment]
Fallout 4 support requires updates to:

- [x] libespm
- [ ] libloadorder
- [ ] `GameSettings`
- [ ] `Game`
- [ ] `LoadOrderHandler::Init()`
- [ ] `Plugin::Plugin()`
- [ ] `PluginLoader::Load()`
- [ ] `Handler::GetGameTypes()`
- [ ] The API needs a new game constant added and `loot_create_db()` to be updated

Most changes required are trivial, but LOOT needs to be updated to use libespm v2 as part of them, and I'm in the middle of a libloadorder rewrite.

**Comment by Freso** [comment]
Milestone: 0.8.x? (Ie., would you consider this a blocker for the next release increment?)

**Comment by WrinklyNinja** [comment]
> Milestone: 0.8.x? (Ie., would you consider this a blocker for the next release increment?)

Let me get my tea leaves out.

In all seriousness, I've lost track of almost all prioritisation, the milestone is essentially just for those things which I can work on right away and which I definitely want to do. So yes, this could be milestone v0.8.x, but it's not a blocker (I don't think anything in the milestone is).

**Comment by Freso** [comment]
Well, they are blockers until you move them out of the milestone again. :)

**Comment by WrinklyNinja** [comment]
Since the changes involve adding a new API constant, that breaks the ABI, so this means the next release will be v0.9.

**Comment by WrinklyNinja** [comment]
OK, Fallout 4 support has been added in the (no surprises) `fallout4-support` branch (which may be subject to rebases).

The update to libespm v2 incurred a significant (x2) performance hit, which I plan to address before merging this into `dev`.

**Comment by Freso** [comment]
I'm looking forward to make my computer explode when testing the pre-release. :+1:

**Comment by pStyl3** [comment]
Just to double check, has the 'Loads BSA' icon been renamed to 'Loads BA2' ?

**Comment by WrinklyNinja** [comment]
> Just to double check, has the 'Loads BSA' icon been renamed to 'Loads BA2' ?

No, I'll have to change it to "Loads Resources" or something.

**Comment by Freso** [comment]
I renamed the "v0.8.x" milestone to "v0.9.0". I figured there won't be any more 0.8.x releases. :)

**Comment by pStyl3** [comment]
In case that those bsa/ba2 references/tooltips can't be "switched", depending on which game is selected in the settings .. 'Loads Resources' could be an alternative. To mention is though, that this term is pretty universal, and thus doesn't necessarily makes it clear, that loose files are not included by this.

'Loads Bethesda Archive' could be another alternative. That term is longer though.

**Comment by Freso** [comment]
"Loads BSA/BA2" could also be an option, until TES6 and the introduction of the next type of resource archive. :p

**Comment by LuthienKess** [comment]
"Loads Archives", would be pretty clear, if we're taking suggestions.
<sup><sup><sup>Then that's my suggestion.</sup></sup></sup>

**Comment by WrinklyNinja** [comment]
> "Loads Archives", would be pretty clear, if we're taking suggestions.

I've gone with "Loads Archive", as plugins typically only load the one (though pre-Skyrim they could load more than one), and it is clearer that it means packaged vs. loose files.

**Comment by WrinklyNinja** [comment]
A snapshot build is now available in the `fallout4-support` subfolder in the snapshot builds folder on Dropbox.

**Comment by Freso** [comment]
🙌 Of course, I'll be busy for the next many hours so I won't be able to poke at it until much later. Ah well. Any chance for a link to the Dropbox in here for the lazy? 😇

**Comment by pStyl3** [comment]
Awesome job wrinklyninja. :)

Already downloaded it and did a first few things on the Skyrim side, to see if the non-FO4 related changes resulted in any quirks. Everything looks fine, with the exception of one thing happening, that is that suddenly LOOT's interprets ".esp.mohidden" files (plugins that are hidden within MO) as well as "esp.bak" files (DynDOLOD) as "plugins".

http://abload.de/img/untitled1oip5u.jpg
http://abload.de/img/untitled2iqqmf.jpg
http://abload.de/img/untitled3wisvt.jpg

LOOTDebugLog.txt (split into 3 parts):
http://pastebin.com/9XaVg5MN
http://pastebin.com/j3m8SJVD
http://pastebin.com/qeV8KJrM

CEFDebugLog.txt:
[1128/142329:ERROR:main_delegate.cc(738)] Could not load cef_extensions.pak

Also, Fallout 4 is not yet mentioned within the "About LOOT" window.
http://abload.de/img/untitled4unsvi.jpg

**Comment by pStyl3** [comment]
Started LOOT normally, attempted to switch to Fallout 4, this error message appeared:
http://abload.de/img/untitled1vcaxa.jpg

**Comment by WrinklyNinja** [comment]
> Any chance for a link to the Dropbox in here for the lazy? 😇

Added one to my previous comment.

> Everything looks fine, with the exception of one thing happening, that is that suddenly LOOT's interprets ".esp.mohidden" files (plugins that are hidden within MO) as well as "esp.bak" files (DynDOLOD) as "plugins".

Well, they are valid plugins, though I guess I should reinstate the condition that `.ghost` extensions are the only non-standard extensions allowed.

> Started LOOT normally, attempted to switch from Skyrim to Fallout 4, this error message appeared:
> http://abload.de/img/untitled1vcaxa.jpg

I thought I removed the code that does that, but I must have discarded that edit...

**Comment by WrinklyNinja** [comment]
Right, new snapshot build is up, should fix those issues.

**Comment by pStyl3** [comment]
The issues seem indeed to be fixed. :+1:
http://abload.de/img/loot1g9ktq.jpg

Downloaded a few plugins from Nexus and I don't recognize anything going wrong.
F4SE is correctly detected aswell.

> Also, Fallout 4 is not yet mentioned within the "About LOOT" window.
> http://abload.de/img/untitled4unsvi.jpg
That is still the case.

One thing wrinklyninja .. could you upload an up-2-date API package? I tried to run LOOT from within MO 2.0.0 Alpha 2, and it is failing.
http://abload.de/img/loot2efkds.jpg

I just want to see if I can get it to work (switching the loot32.dll in MO's `loot` folder .. or possibly now the loot64.dll ?) and if not I'll let Tannin know.

Last but not least .. with the previous 4 games we had the following commands:
> --game=FalloutNV
> --game=Fallout3
> --game=Skyrim
> --game=Oblivion

Am I right to assume that `--game=Fallout4` works aswell?

**Comment by WrinklyNinja** [comment]
> That is still the case.

I forgot that one, fixed now.

> I just want to see if I can get it to work (switching the loot32.dll in MO's loot folder .. or possibly now the loot64.dll ?) and if not I'll let Tannin know.

Which is it, 32-bit or 64-bit?

> Am I right to assume that --game=Fallout4 works aswell?

It should do, yes.

**Comment by pStyl3** [comment]
> Which is it, 32-bit or 64-bit?

Well, until now Tannin always used loot32.dll, and it's also shipped along with Alpha 2 of version 2.0.0. But since version 2 is all about 64 bit support, I would guess that loot64.dll could be a necessity now aswell.

The last API package I have is `LOOT API v0.8.1-5-g0ba3dae.7z`, so a few sub-versions old (around 2 months).

**Comment by Freso** [comment]
I’m pretty sure https://github.com/TanninOne/modorganizer v2 and forwards is entirely a 64‐bit application, so it would make sense for it to be using the 64‐bit LOOT DLL now.

**Comment by WrinklyNinja** [comment]
OK, new LOOT app and API builds are up, for 32-bit and 64-bit.

This is the first time I've built a 64-bit LOOT.exe. The Steam hardware survey puts 32-bit OS's at 12%, which is still a bit high for me to switch over, and I don't think there's much point in regularly providing builds for both architectures, unless there's a necessity for interoperability with other tools. 

@TanninOne: Will MOv2 be able to launch other utilities that are 32-bit, or does everything that runs on top of its filesystem hackery have to share the same architecture?

**Comment by WrinklyNinja** [comment]
Also @pStyl3, just dropping the API DLL into MO probably won't get it working with Fallout 4, because MO will need updating to know to use the new game constant for FO4. Depending on how the DLL is loaded, it may also be broken for existing games, because adding the constant changed the binary interface.

**Comment by WrinklyNinja** [comment]
I have now merged `fallout4-support` into `dev`, and uploaded new snapshot build archives accordingly.

**Comment by TanninOne** [comment]
@WrinklyNinja MOv2 will support running both 32-bit and 64-bit applications but in the current alpha the "bridge" to the other architecture is broken. If making the 64-bit builds is a bother for you I can bundle a 32-bit lootcli in the future.

The supported games should not break in lootcli if you update the loot-dlls. All variables and functions from the loot-dll are resolved at runtime with GetProcAddress, I don't link against a stub-library.
But yeah, fallout 4 support will not magically appear as the list of supported games is static inside lootcli.

**Comment by WrinklyNinja** [comment]
> If making the 64-bit builds is a bother for you I can bundle a 32-bit lootcli in the future.

If it's no extra work for you, then doing so would be better. 64-bit builds require me to swap a couple of folders around, so it's not much of a bother, but offering 32-bit and 64-bit downloads would confuse some users, plus there's more to go wrong, and I'd rather avoid that.

**Comment by TanninOne** [comment]
That's fine. I have to create complete 32-bit and 64-bit builds of everything anyway, doesn't matter which of the lootcli builds i pick for the releases.

**Comment by pStyl3** [comment]
Thanks to both of you for your efforts!

If using `LOOT v0.8.1-38-g7c4fe9f (64 bit).7z` MOv2 Alpha 2 no longer throws the mentioned error message. What happens is that MO tries to normally start LOOT, the window "MO is locked while the executable is running." pops up, and after a few seconds that window disappears again without LOOT being started. If I read Tannin's sentence correctly, `lootcli.exe` within MO's `loot` folder needs to be updated to account for FO4 support, so this result seems to be reasonalbe. This should therefore be resolved once Tannin comes around to do that.

In any case @WrinklyNinja do you expect any significant differences between the 32 and 64 bit builds of LOOT? Like performance gain/loss? Is there anything specific you would like me to test wth the 64 bit version (with or without regards to FO4)?

**Comment by Techwolf** [comment]
Just for info only, there is no MS .NET for wine 64-bit, but I _just_ discovered there is wine-mono for 64-bit .NET apps. While LOOT does not use .NET (Thank ${DEITY}), some games and utilities may not run in a 64-bit environment. I will be testing this in the future on my Skyrim on wine install. Skyrim has one .NET program, FNIS that is used by many mods.

To sum up, one vote for both 32-bit and 64-bit  program, even if you have to 'hide' one of them to prevent confusing some of those gamers.

**Comment by WrinklyNinja** [comment]
> In any case @WrinklyNinja do you expect any significant differences between the 32 and 64 bit builds of LOOT? Like performance gain/loss? Is there anything specific you would like me to test wth the 64 bit version (with or without regards to FO4)?

No, I don't expect any differences.

> To sum up, one vote for both 32-bit and 64-bit program, even if you have to 'hide' one of them to prevent confusing some of those gamers.

LOOT doesn't work through Wine though, I thought that was what started getting a native Linux build. Since native builds are possible, it makes little sense for me to provide a 64-bit build just for Wine users, that won't work anyway...

**Comment by Freso** [comment]
@Techwolf But Fallout 4 is 64‐bit only, so whenever the Wine project catches up on DirectX compatibility, you will need a 64‐bit Wine prefix for running Fallout 4 anyway.

**Comment by Techwolf** [comment]
LOOT does work with wine. I've added a comment to that issue. What was needed was "wine LOOT.exe --no-sandbox" and it worked, even with MO.

**Comment by WrinklyNinja** [comment]
@Techwolf: I'm still confused as to why you want 64-bit LOOT on Linux.

**Comment by pStyl3** [comment]
New Fallout 4 Patch is now released, 218.8 MB through Steam.

**Comment by Techwolf** [comment]
@WrinklyNinja I though that was a fallout 4 requirement...or was that MO now I think about it. If so, forget my thoughts about 64-bit LOOT from this old senile werewolf. :-D

**Comment by WrinklyNinja** [comment]
Fallout 4 and MO v2 require a 64 bit OS, but they don't need LOOT to also
be 64 bit.

**Comment by WrinklyNinja** [comment]
Closing this since as of 9e28bfa31d7dfa113ea8b181fd97d64a860581fa Fallout 4 support seems to be working correctly.
