### ISSUE TITLE
Can't Read Push Undefined TESV

### ISSUE THREAD

**Issue by GrapeShifter** [loot/loot#506]
[CEFDebugLog.txt](https://github.com/loot/loot/files/41094/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/41095/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
It doesn't look like you're running v0.8.1, as there are lines missing from the start of the LOOT debug log. Try upgrading and see if that fixes your issue.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
