### ISSUE TITLE
Crash when sorting

### ISSUE THREAD

**Issue by coldfiret** [loot/loot#507]
Hey, i'm hoping someone will know how to fix this issue, but whenever I launch loot through mod organizer, and I click sort plugins loot crashes saying "LOOT.exe has stopped working."

**Comment by Freso** [comment]
What version of Mod Organizer? What version of LOOT? What button are you pressing to sort plugins in MO via LOOT? What game are you working on? What do [your logs](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully) say?

**Comment by coldfiret** [comment]
MO-v1.3.11 LOOT-v0.8.1 I launch the loot executable through the MO exe manager. Once loot loads up, I click the three lined button that when I hover over it says sort plugins.

**Comment by Freso** [comment]
There are still two questions you didn't answer.

**Comment by coldfiret** [comment]
Amazingly it just worked, all I did was disable about half of the mods for skyrim I was using, then tried sorting through loot and it was successful. Maybe I just had too many mods enabled and my PC couldn't handle it.

**Comment by Freso** [comment]
A log would still be nice. Maybe @WrinklyNinja would be able to make LOOT error out sanely instead of straight out crashing. Of course, if it's an [OOM](https://en.wikipedia.org/wiki/Out_of_memory) issue, maybe it requires too deep OS level integration to catch, I don't know.
