### ISSUE TITLE
Regenerate .pot file

### ISSUE THREAD

**Issue by Freso** [loot/loot#509]
Hey @WrinklyNinja. Please regenerate the `resources/l10n/template.pot` in the `dev` branch. :)

Hm. I could probably regenerate this myself. Are you doing anything special, or will running `xgettext` work fine?

**Comment by WrinklyNinja** [comment]
Running `xgettext` should just work, though the existing path in the `.pot` file for JS sources hadn't been updated to account for refactoring.

I've updated the file in 794e955b6a9ccd6d914b378ea9c9e3a7e3c210a2 on the `fallout4-support` branch, as that should be ready to merge soon.
