### ISSUE TITLE
Improve quality of plugin version extraction

### ISSUE THREAD

**Issue by Freso** [loot/loot#510]
`Version 0.2.` in `SNAM` should translate to `0.2`, but is currently being interpreted as `0.2.`.

See http://www.nexusmods.com/fallout4/mods/2955

**Comment by WrinklyNinja** [comment]
OK, I'll need to take a look at the regexes for version extraction. It may be worth going through the masterlists to see what plugins have version checks, and working back from there, rather than having an unnecessarily broad range of regexes that leak.

**Comment by Freso** [comment]
I was actually looking a bit at the tests, and it seems like they're all functional tests. Maybe some unit tests would be good for the version parsing function? So it'd be easy to make a list of strings and what they should result in (e.g., `EXPECT_EQ(version_parser("Version 0.2."), "0.2")`).

**Comment by WrinklyNinja** [comment]
> I was actually looking a bit at the tests, and it seems like they're all functional tests. Maybe some unit tests would be good for the version parsing function? So it'd be easy to make a list of strings and what they should result in (e.g., EXPECT_EQ(version_parser("Version 0.2."), "0.2")).

Yes, that's what I was thinking of doing. I'll need to move parsing out of the `Plugin` class, into a helper function probably, so that such tests could see the function.

**Comment by WrinklyNinja** [comment]
Now `Version(const std::string& str)` will try parsing the string for a version number and trim it to that version number if it finds one. This isn't exactly the same behaviour as previously, as it keeps the whole string if nothing is found, while the old behaviour would keep an empty string, but that's done to keep the existing tests passing with minimal code changes.

Now to write some more and better tests for that parsing, that force the old behaviour back in and fix the reported issue...

**Comment by WrinklyNinja** [comment]
Now I need to gather up the plugins that the masterlists currently contain version conditions for, and create tests using the contents of their description fields.

##### Oblivion

- [ ] `Unofficial Oblivion Patch.esp`
- [ ] `Ayleid Loot EXtension.esp`
- [ ] `Oblivion WarCry EV.esp`
- [ ] `Sneaking Detection Recalibrated.esp`
- [ ] `SDR_Core.esp`

##### Fallout 3

- [ ] `Unofficial Fallout 3 Patch.esm`

##### Skyrim

- [ ] `Unofficial Skyrim Patch.esp`
- [ ] `Unofficial Dawnguard Patch.esp`
- [ ] `Unofficial Hearthfire Patch.esp`
- [ ] `hideout.esm`
- [ ] `retreat.esm`
- [ ] `JSwords.esm`
- [ ] `BabettesFeastBalanced.esp`
- [ ] `BabettesFeastOverpowered.esp`
- [ ] `BabettesFeastWeakerEffects.esp`
- [ ] `cao_goldbrand_WT.esp`
- [ ] `AMatterOfTime.esp`
- [ ] `SkyUI.esp`
- [ ] `Fhaarkas Font Mod - SkyUI.esp`
- [ ] `DPArmor.esp`
- [ ] `hothtrooper44_ArmorCompilation.esp`
- [ ] `JSwordsDistributionBalancePlugin.esp`
- [ ] `Redguard Shield.esp`
- [ ] `Skimpy Plate Armor.esp`
- [ ] `TrissArmorRetextured.esp`
- [ ] `FM - UNP Merchants.esp`
- [ ] `hideout.esp`
- [ ] `retreat.esp`
- [ ] `WARZONES - Civil Unrest.esp`
- [ ] `Headbomb's Better Sorting - Ammo.esp`
- [ ] `Headbomb's Better Sorting - Books.esp`
- [ ] `Headbomb's Better Sorting - Food (Light Weight).esp`
- [ ] `Headbomb's Better Sorting - Food (Normal Weight).esp`
- [ ] `Headbomb's Better Sorting - Food (Reduced Weight).esp`
- [ ] `Headbomb's Better Sorting - Food (Weightless).esp`
- [ ] `Headbomb's Better Sorting - Ingredients.esp`
- [ ] `Headbomb's Better Sorting - Miscellaneous.esp`
- [ ] `Headbomb's Better Sorting - Potions (Half Weight).esp`
- [ ] `Headbomb's Better Sorting - Potions (Light Weight).esp`
- [ ] `Headbomb's Better Sorting - Potions (Normal Weight).esp`
- [ ] `Headbomb's Better Sorting - Potions (Weightless).esp`
- [ ] `Headbomb's Better Sorting - Soul Gems (PseudoVanilla).esp`
- [ ] `Headbomb's Better Sorting - Soul Gems (Ranked).esp`
- [ ] `Headbomb's Better Sorting - Spells.esp`
- [ ] `BabettesFeast - IMCN.esp`

I expect that once all these are done, the minimal regex to match their versions will leak more false positives than the existing regexes. The best way to reduce them would be to upload a snapshot build and have testers report any false positives they encounter, covering a larger range of mods than I could on my own.

**Comment by WrinklyNinja** [comment]
Closing this now that the reported issue is fixed and the fix merged into `dev` (in f6924d0e5ea210d421cb7785f222c48a8c8820d1). 

It's likely there are still false positives to fix, as there's a lot less to the new regex than the old regexes, but I'll handle that by uploading a snapshot build and getting feedback from testers.
