### ISSUE TITLE
LOOT can not find boost lib

### ISSUE THREAD

**Issue by Myppomeu** [loot/loot#511]
Debian 8.2 x64
I have builded boost v1.59.0 with [this](http://www.boost.org/build/doc/html/bbv2/installation.html) manual and install it into system.
When running LOOT 0.8.1 (prebuilded from Dropbox), this error appears:

```
error while loading shared libraries: libboost_log.so.1.55.0: cannot open shared object file: No such file or directory
```

Tried to fix this with this:

```
ln -s /usr/local/lib/libboost_log.so /usr/local/lib/libboost_log.so.1.55.0
```

Also tried put this lib into LOOT directory (and make ln -s) with same result.

Maybe, there is fully ready to work prebuilded version of LOOT, wich does not require to compile and manually install all dependencies?

P.S. LOOT crashes in wine.

**Comment by WrinklyNinja** [comment]
> Maybe, there is fully ready to work prebuilded version of LOOT, wich does not require to compile and manually install all dependencies?

You don't need to compile Boost yourself if you happen to use Ubuntu and/or have the `boost-latest` PPA added to your APT sources list.

Running LOOT on Linux is unsupported: I have documented one specific way of getting it to work, beyond that you're on your own, because there are a million and one different flavours and I don't have the time or inclination to help people through getting it to work on their favourite.

**Comment by Myppomeu** [comment]
Does not matter if I install boost from this repo or compile it from source, result is the same.
[This](https://github.com/loot/loot/blob/dev/docs/BUILD.LINUX.md) manual is out of date: npm would not be installed (wrong dependencies) and libstdc++6 in 14.04 is too old for LOOT 0.8.1.
Tried to install boost on Ubuntu 15.10 and run LOOT. If boost is x32, LOOT will say that ELF class in libboost_log.so.1.55.0 is wrong. If boost is x64, LOOT will say that cannot open libboost_log.so.1.55.0: No such file or directory.
In fact, LOOT can not be run in Linux at the moment.

**Comment by WrinklyNinja** [comment]
> In fact, LOOT can not be run in Linux at the moment.

If it didn't run, I wouldn't have uploaded the snapshot build. There's clearly just some step or configuration that you missed (or possibly I didn't document).

I haven't tried 32 bit builds in Linux though, so I wouldn't be surprised if that doesn't work.

**Comment by Myppomeu** [comment]
Linux was x64.
Maybe I miss something.
For now solved it with virtual machine with windows and connected share with skyrim folder.

**Comment by Translator5** [comment]
Linux Run ->Wine 1.9.10 Staging
Settings: WinXP and under Staging; Wine7 won't work and DONT ENABLE GTK3 Theming, than Loot should start.

**Comment by WrinklyNinja** [comment]
Closing this as it references an older version of Boost, and I've been able to build and run LOOT on Travis and on a Linux install of my own.
