### ISSUE TITLE
LOOT not sorting with Mod Organizer?

### ISSUE THREAD

**Issue by Naddyice** [loot/loot#512]
Hey folks. As the title suggests, I'm having an issue with LOOT working with Mod Organizer. I have LOOT installed in my Skyrim folder, and I do run the executable through mod organizer. All are always run as administrator. However, I noticed while getting some mods ready that despite running loot and allowing it to sort plugins, and even using the sort button built into MO, none of my mods were actually being sorted. To test this, I intentionally dragged a few important mods (unofficial patches, SKSE and what not) out of place and pressed sort, and they remained where they were. So..if anyone could help me trouble shoot on what might be the issue, I'd greatly appreciate it. Both my MO and LOOT are currently up to date (MO is 1.3.11, and LOOT is 8.1).

I've modded before, and I've never had this such issue. I'm not really sure what to do.

**Comment by WrinklyNinja** [comment]
Please [provide a debug log](https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully).

**Comment by Naddyice** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/57205/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/57204/CEFDebugLog.txt)


Alright, there you go. There were two. I hope these help!

**Comment by WrinklyNinja** [comment]
It looks like the debug log you've provided was generated from after you enabled debug logging in the settings panel, could you give me one generated from when LOOT is opened?

**Comment by Fusion-tech** [comment]
I'm having a similar issue... Maybe this log will help? I hope I have the right one.
[CEFDebugLog.txt](https://github.com/loot/loot/files/60301/CEFDebugLog.txt)

**Comment by FletcherVK** [comment]
If I open LOOT (8.1) from Windows 7 Ultimate (64 bit), it is apparently not playing well with Mod Manager either. It comes up with whatever is in ...\Skyrim\Data.  (I checked by modifying and re-running.  Additionally, if I try to open the exe from Mod Manager (1.3.11)  I get a LOOT window that is empty, even after 10 minutes. 
Thanks for doing this, LOOT is awesome. :D

My CEFDebugLog.txt for opening LOOT is just this:
[1216/000759:ERROR:main_delegate.cc(730)] Could not load cef_extensions.pak

**Comment by geraintwd** [comment]
I am having a similar problem. I am running LOOT Version 0.8.1 (build b97f7849) and using Wrye Bash (Smash) to install / manage mods for Skyrim. 

I'm running Windows 7 Ultimate 64-bit. The OS and Skyrim (and all my other software for that matter) are all legally purchased and fully up to date.

Skyrim is installed in E:\Steam\steamapps\common\Skyrim
Bash is installed in E:\Steam\steamapps\common\Skyrim\Mopy
LOOT is installed in E:\Games\LOOT
My Games (where Skyrim.ini, etc. are saved) is E:\My Documents\My Games
(E:\ is not a network drive, it is a local hard drive.)

Most of my mods have been installed through BAIN (Bash Installers), however there are a handful that were subscribed via Steam Workshop (not available on Nexus).

LOOT recognises the mods I have installed and gives no errors when I use it to sort them and I click "Apply". However, the order of the mods in Wrye does not change. I have also checked both plugins.txt and loadorder.txt (both stored in the My Games folder mentioned above) - the order has not changed in those either, i.e. the changes suggested by LOOT have not been written to those files. Also, the last modified date for both files is the last time I ran the game (2 days ago). If LOOT was updating them, their date stamps would change.

Interestingly enough, I have an identical problem with BOSS - it doesn't make any changes to the load order for Skyrim (though it works fine for Oblivion, whether invoked standalone or via Wrye Bash).

CEFDebugLog.txt for LOOT is the same as FletcherVK (file attached)
[CEFDebugLog.txt](https://github.com/loot/loot/files/64459/CEFDebugLog.txt)

Also attached screenshot of my LOOT window.
![loot screenshot 1](https://cloud.githubusercontent.com/assets/16326425/11851991/7d0e264a-a42d-11e5-9e32-02913ed65dd1.jpg)

I would appreciate any help or suggestions, as I'm currently having to reorder my mods manually in Bash according to LOOT's suggestions.

Thanks
Geraint

**Comment by WrinklyNinja** [comment]
> I'm having a similar issue... Maybe this log will help? I hope I have the right one.

If LOOT isn't sorting, then the LOOTDebugLog.txt may be helpful.

> If I open LOOT (8.1) from Windows 7 Ultimate (64 bit), it is apparently not playing well with Mod Manager either. It comes up with whatever is in ...\Skyrim\Data. (I checked by modifying and re-running.) Additionally, if I try to open the exe from Mod Manager (1.3.11) I get a LOOT window that is empty, even after 10 minutes.

That's #482, not this issue.


> LOOT recognises the mods I have installed and gives no errors when I use it to sort them and I click "Apply". However, the order of the mods in Wrye does not change. I have also checked both plugins.txt and loadorder.txt (both stored in the My Games folder mentioned above) - the order has not changed in those either, i.e. the changes suggested by LOOT have not been written to those files. Also, the last modified date for both files is the last time I ran the game (2 days ago). If LOOT was updating them, their date stamps would change.

`plugins.txt` and `loadorder.txt` are not stored in My Games - if there are such files there, they will be copies made by Wrye Bash.

**Comment by dwelsh99** [comment]
I was able to get LOOT to work with Mod Organizer for Skyrim, but not for Mod Organizer 2 for Fallout 4.

I had to run LOOT from Mod Organizer for Skyrim and add the Argument '--single-process '. Pic included...

![mo_loot](https://cloud.githubusercontent.com/assets/15525582/12209936/0097e26c-b61c-11e5-86d0-69dbd41b6515.jpg)

But this does not work for Mod Organizer 2 for Fallout 4. But also using the Alpha version of Mod Organizer 2. Perhaps it will work after a newer version of Mod Organizer 2 comes out.

**Comment by OneSubtractOne** [comment]
I grabbed the 64 bit loot from dropbox, (LOOT v0.8.1-38-g7c4fe9f (64 bit).7z) to try with the new Mod Organizer Alpha. It detects the plugins, but still does some weird things.
It doesn't appear to be sorting anything at all, and each plugin doesn't seem to recognize any of the plugins that went before it. See screenshot for an example. This is happening with any mod that requires another mod. It throws up an error that this mod requires that mod, but that mod is not installed, despite the fact that it's obviously in the load order.
I don't know if this needs something done in Loot or ModOrganizer though.

![loot](https://cloud.githubusercontent.com/assets/16618377/12213841/4ddc03f0-b64e-11e5-883a-1e61bcc304b8.jpg)

**Comment by WrinklyNinja** [comment]
> I don't know if this needs something done in Loot or ModOrganizer though.

Does it work without MO involved? If yes, then it's not something for LOOT to change. If no, then it's probably a bug, so try with the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (0.8.1-121).

**Comment by dwelsh99** [comment]
@OneSubtractOne 

the missing plug-ins is an issue with MO2, they are not showing up in MO2. You can read more in this link.

http://forum.step-project.com/topic/9377-mod-organizer-2-discussion-and-feedback/

@WrinklyNinja 

Thanks for the link for the 64-bit version

**Comment by OneSubtractOne** [comment]
https://github.com/TanninOne/modorganizer/issues/443
For those of you in the same boat as myself, and a few others, I looked a little harder. It is an MO issue, and there's a work around at the link above. Works fine once you perform those actions.

**Comment by belowzeros** [comment]
I've come across this problem myself.  I've been using MO & LOOT quite extensively the past 7-10 days with no problems.  For some reason LOOT just stopped sorting via MO.  I've tried cold and soft resets with new installs of MO, LOOT 8131 and the snapshot build with no luck.  The above possible solution from TanninOne does not work either.

[CEFDebugLog.txt](https://github.com/loot/loot/files/97109/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/97110/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
> I originally realized I had this problem because my modpack from Skyrim Mod Combiner that adds multiple .esps was frozen at the end of the load order.

What does "frozen" mean?

> because LOOT maybe doesn't recognize them? 

LOOT doesn't have a concept of "recognising" plugins, it's meaningless.

There are no significant errors in your logs, the order LOOT sorts your plugins into just matches their existing order. How is this wrong?

**Comment by belowzeros** [comment]
"frozen" meaning they will stay at the bottom of my load order.  The mods that start at 83Willows_101BUGS_V4_LowRes.esp are all from my texture pack.  They have been mixed into my load order before this problem started for me.  

They just won't sort anymore, nothing will.   If I manually move something and run LOOT it doesn't move anything I put out of place, it just stays where I put it.

**Comment by WrinklyNinja** [comment]
Could you give me a specific example of a plugin in your load order, that is present in the load order you posted the debug log for above, that LOOT is not positioning correctly, and give me some detail about why the position it's in is not correct.

"It doesn't move my plugins around" doesn't necessarily mean anything is wrong, and it's very difficult to spot LOOT making a mistake from just reading the log.

**Comment by belowzeros** [comment]
sure, thanks for the help.  to test i disabled my entire load order and have been reloading everything.  once I get a bit farther I will compare some mods against the masterlist and update.

**Comment by Dyscrasite** [comment]
I thought that it was just me having this issue so I've been using MO & LOOT the past week with no changes in my mods being organized. For example LOOT would run and yet my plugins and mods would be in priority that they normally wouldn't be in so I just manually would move them around in MO. I've uninstalled and did a reinstall of Skyrim, MO and LOOT 8.1. and now I am reinstalling the mods in my list back in order of their respective priorities... no CRS as of yet doing it this way

**Comment by Nitrogue1** [comment]
If the load order doesn't keep changes with the newer versions of LOOT, open LOOT and end the mod organizer process in task manager. Then sort and close.

**Comment by inkwhiz** [comment]
Having same or similar problem, loot v9 runs on its own but starting run i try launch it from mod organizer it crashes every time, so here is a copy of the details, I hope it helps to find a solution.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	LOOT.exe
  Application Version:	0.9.0.0
  Application Timestamp:	57409a1b
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.23418
  Fault Module Timestamp:	5708a73e
  Exception Code:	c0000005
  Exception Offset:	0004e6df
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	3081
  Additional Information 1:	a877
  Additional Information 2:	a87751724e225ffcdd7aaed29770c8da
  Additional Information 3:	92c6
  Additional Information 4:	92c64138029af891e783db3b4ad59838

Is this dll File part of LOOT V.9?

**Comment by Freso** [comment]
@inkwhiz If LOOT runs and works fine on its own, you should report it with Mod Organizer as it isn't a LOOT issue then.

**Comment by inkwhiz** [comment]
understood

**Comment by WrinklyNinja** [comment]
Closing this as it's YAMOI (Yet Another Mod Organiser Issue). As Freso says, issues that occur only when using Mod Organiser should really be redirected towards its issue tracker.
