### ISSUE TITLE
Cyclic interaction and bad allocation on Skyrim.esm

### ISSUE THREAD

**Issue by l1qu1d101** [loot/loot#514]
Whenever I try to sort my mods using loot launched from mod organizer I get told Error code: 14; Failed to sort plugins. Details: Cyclic interaction detected between plugins "Skyrim.esm" and "ApachiiHair.esm". Back cycle: ApachiiHair.esm, Skyrim.esm yet if I disable apachii, another plugin will have bad cyclic interaction. When I try to edit the metadata I am told Cannot read "Skyrim.esm". Details: bad allocation. 

I have verified the game cache using steam then copied the verified files into my mod for MO "Skyrim Legendary + Update + SKSE scripts" and in MO I have verified that skyrim.esm is definitely from MY mod, not another one of my 300 or so mods overwriting my skyrim master.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/60032/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/60033/CEFDebugLog.txt)

The strange thing is this is not game breaking, I can play after using MO internal sort button (fully updated using LOOTAPI0.81) yet I would much prefer being able to set user rules and use the full LOOT.

**Comment by pStyl3** [comment]
By looking at your LOOTDebugLog.txt file I can see, that you are using the latest official release of LOOT, so version `0.8.1 revision  b97f784`. Please retry to sort your load order with the latest pre-release version `LOOT v0.8.1-53-gaac5583 (32 bit).7z` that you can download [here](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0).

I'm using that version and I just successfully sorted my load order with `ApachiiHair.esm` from [ApachiiSkyHair on Nexus](http://www.nexusmods.com/skyrim/mods/10168) being present.

**Comment by WrinklyNinja** [comment]
> Whenever I try to sort my mods using loot launched from mod organizer I get told Error code: 14; Failed to sort plugins. Details: Cyclic interaction detected between plugins "Skyrim.esm" and "ApachiiHair.esm". Back cycle: ApachiiHair.esm, Skyrim.esm yet if I disable apachii, another plugin will have bad cyclic interaction.

What's the other plugin, and does another plugin have the same issue if you deactivate it, and so on?

Supplying any user metadata you have may also help, please paste in the contents of your `Skyrim\userlist.yaml` file in LOOT's folder (where you found the debug logs).

> When I try to edit the metadata I am told Cannot read "Skyrim.esm". Details: bad allocation.

That sounds like a separate issue entirely, which the lastest pre-release version @pStyl3 mentioned may help with. Bad allocation happens if not enough memory can be allocated to load the plugin, which is highly unusual.

Also what do you mean "skyrim.esm is definitely from MY mod"? Did you replace the vanilla Skyrim.esm with an edited version?

**Comment by l1qu1d101** [comment]
Yes so if I disable apachii then apparently dawnguard becomes the cyclic interaction, but that is the behaviour i intended, if i disable the "problem" plugin then another plugin becomes the issue and so on. And what i intended to say about my plugin is just that its a straight copy from the data dir to a MO mod so I have nothing in my data dir apart from MO's hook.dll, so i def have not and would not edit my skyrim.esm :). I'll post bk in a mo with the results from the pre release loot and cheers for bearing with me.

Userlist.yaml->

!<!> enableDebugLogging: true
!<!> game: !<!> auto
!<!> games:
  - type: Oblivion
    name: "TES IV: Oblivion"
    folder: Oblivion
    master: Oblivion.esm
    repo: https://github.com/loot/oblivion.git
    branch: v0.8
    path: ~
    registry: Software\Bethesda Softworks\Oblivion\Installed Path
  - type: Skyrim
    name: "TES V: Skyrim"
    folder: Skyrim
    master: Skyrim.esm
    repo: https://github.com/loot/skyrim.git
    branch: v0.8
    path: C:\Program Files\Steam\steamapps\common\Skyrim\
    registry: Software\Bethesda Softworks\Skyrim\Installed Path
  - type: Fallout3
    name: Fallout 3
    folder: Fallout3
    master: Fallout3.esm
    repo: https://github.com/loot/fallout3.git
    branch: v0.8
    path: ~
    registry: Software\Bethesda Softworks\Fallout3\Installed Path
  - type: FalloutNV
    name: "Fallout: New Vegas"
    folder: FalloutNV
    master: FalloutNV.esm
    repo: https://github.com/loot/falloutnv.git
    branch: v0.8
    path: ~
    registry: Software\Bethesda Softworks\FalloutNV\Installed Path
  - type: Oblivion
    name: Nehrim - At Fate's Edge
    folder: Nehrim
    master: Nehrim.esm
    repo: https://github.com/loot/oblivion.git
    branch: v0.8
    path: ~
    registry: Software\Microsoft\Windows\CurrentVersion\Uninstall\Nehrim - At Fate's Edge_is1\InstallLocation
!<!> language: !<!> en
!<!> lastGame: !<!> Skyrim
!<!> updateMasterlist: false
lastVersion: 0.8.1
window:
  left: 154
  right: 1595
  top: 154
  bottom: 914

**Comment by l1qu1d101** [comment]
ok so first run with the pre release it worked perfectly, sorted my mod list just like it should. I tried it again as i always do and now my skyrim.esm has vanished in loot yet is ticked and active @ top of the mod list as it should be in MO before i execute loot.

**Comment by WrinklyNinja** [comment]
> ok so first run with the pre release it worked perfectly, sorted my mod list just like it should. I tried it again as i always do and now my skyrim.esm has vanished in loot yet is ticked and active @ top of the mod list as it should be in MO before i execute loot.

It sounds like it doesn't think your Skyrim.esm is a valid plugin, could you post your LOOTDebugLog.txt generated by the snapshot build?

**Comment by l1qu1d101** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/60308/LOOTDebugLog.txt)
Yes it seems so but I did just do a straight copy into a MO folder after verifying the game content in steam. Bit of a slowish connection here but i'll verify my data again to be on safe side. I'll also try leaving the skyrim.esm, dawnguard.esm etc in the data folder and run loot , so it isn't using the MO hook.dll for the system files just in case that produces different results.

**Comment by l1qu1d101** [comment]
After verifying then leaving the esm files in the data dir and running loot without starting MO I have no issues at all using loot. When I run loot from MO with files unmanaged it will not show skyrim.esm in loot. Since the problem only appears using MO would that mean this is an issue with MO and not loot?

**Comment by WrinklyNinja** [comment]
> Since the problem only appears using MO would that mean this is an issue with MO and not loot?

Whatever the cause, LOOT thinks that your Skyrim.esm is not a valid plugin (ie. it can't parse it), and that obviously doesn't happen without MO involved, but it also doesn't happen when I use LOOT through MO, so its either another of those tricky bugs to solve or something specific to your setup. 

Either way, I don't think there's anything I can do on LOOT's end, since it seems to be specific to the MO interaction.
