### ISSUE TITLE
Error when sorting Plugins.txt 'iostream stream error' - Fallout 4

### ISSUE THREAD

**Issue by resooner** [loot/loot#518]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/64437/LOOTDebugLog.txt)
Error code: 1; libloadorder failed to set the load order. Details: "C:\Users\Me\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error

I have made sure the plugins.txt file is not set to read-only and the issue is still happening.

Edit:
I am running Windows 7 SP1 64bit using LOOT Version 0.8.1 (build e34c867) for the Steam version of Fallout 4.

**Comment by WrinklyNinja** [comment]
Does running LOOT as an admin work? It shouldn't be necessary, but it's worth a shot.

**Comment by resooner** [comment]
Just tried, got the exact same error.

**Comment by Ibbanez** [comment]
I believe Nexus Mod Manager has permanently set plugins.txt to read-only, or possibly Windows.  Even if you change it, once you press OK, and then reopen it, its back to read-only.

**Comment by Freso** [comment]
If you exit NMM you can unset `plugins.txt`'s read-only flag and it'll stay unset until you launch NMM again. There isn't a way to *permanently* set a file to read-only. (I've successfully managed to launch LOOT via NMM, sort in LOOT, unset `plugins.txt`'s read-only flag, apply LOOT's sort order, and exit LOOT back to NMM.)

Also, as @WrinklyNinja stated [elsewhere](https://github.com/loot/loot/issues/517#issuecomment-164816138), Bethesda will likely revert this either in the next update or in the update following/accompanying the release of the FO4 GECK, by which time NMM's work around will likely be undone too.

> It had to be their most recent update to v0.61.4

It was part of [0.61.3](http://www.nexusmods.com/fallout4/news/12680/)… You do read the update notes when you update NMM and other software, right?

**Comment by Ibbanez** [comment]
The one thing I want to point out is even though you get the error, if you press apply again for a second time, there is no error, and if you look at the mods on Nexus Mod Manager, they do in fact change their location, so it does work, but it throws an error.  Just press apply again and all should be good.

**Comment by unforbidable** [comment]
There is not error the second time because the changes got applied the first time you clicked Apply.

**Comment by sjguy1962** [comment]
I have Win10 and my plugins.txt are not read only. it was so that hitting apply a second time cleared the error but now it no longer does so. this error renders LOOT pretty much useless can we get this fixed soon please.

**Comment by Ibbanez** [comment]
I have Win 10, and even with the error and the read only plugins.txt file, Loot makes the changes just fine, even with the error, so I'm not sure what issues you are having.  Also, to test it out and make sure that your plugins.txt file just has nothing to move.  Try moving things in a completely inproper order, so that LOOT will actually have something to move and reorder.  Either way, even with the error, it still works for me perfectly and changes the order up when needed.

**Comment by sjguy1962** [comment]
No I just tried that and positions did NOT change for manual manipulation
required. I even tried a refresh and masterlist update. its like its not
pulling anything except changes I make outside of the program. I like this
tool and have used it since Oblivion i hope you can fix this.

**Comment by WrinklyNinja** [comment]
This is no longer an issue with Fallout 4 1.5's mod support and the Creation Kit beta, so closing this.

**Comment by luckydonald** [comment]
But it is still happening, Fallout and NMM is on the newest version, Loot [aswell](https://github.com/loot/loot/releases/tag/0.9.0).
- Windows `8.1`
- Loot `0.9.0`
- NMM `0.61.23`

**Comment by WrinklyNinja** [comment]
Have you ensured that your plugins.txt is not read-only?

**Comment by luckydonald** [comment]
It later did work when running while NMM was also running.

I understand NMM sets it as readonly when closing?
Maybe a more verbose (englisch) error message clearly stating it is readonly could be helpful?
Also can't it just remove the readonly flag?

**Comment by WrinklyNinja** [comment]
The error message doesn't say it's read-only because that's only one possible reason for the error. 

LOOT doesn't remove the read-only flag because the game never makes `plugins.txt` read-only, and it's not LOOT's responsibility to work around whatever changes other utilities are making - the onus is on such utilities to not make changes that require workarounds.

**Comment by luckydonald** [comment]
But an error message you have to google is not a good error message. It is good for a log file, bot not for a user.
> because that's only one possible reason for the error

Especially now I see no reason for a cryptic `ios_base::badbit set: iostream stream error`
instead of *"your file is readonly"*

**Comment by WrinklyNinja** [comment]
No, it's not a good error message. Neither is "your file is readonly", because being inaccurate is just as bad as being imprecise.

**Comment by luckydonald** [comment]
Can we find an error message which would be better?
I don't want to offend, but try to find a way to improve it.
Why is it inaccurate? Because we should also mention the file path?

**Comment by WrinklyNinja** [comment]
Sure, if you can come up with something better, go for it. Perhaps just "there was an error writing the load order"?

"your file is readonly" is inaccurate because it might not be read-only. That error occurs if anything goes wrong while reading the file - another process might delete it half way through, for example.

**Comment by ntblood** [comment]
I have this same error sorting Oblivion mods with LOOT with TMM (OBMM's new version).
"ios_base::badbit set: iostream stream error"  I've looked for a long time and this is the only discussion I've found. My plugins.txt in Local AppData is not read-only so I don't understand how to fix this error. 

 Thanks

**Comment by Freso** [comment]
@ntblood Have you tried using the latest [snapshot build of LOOT](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0)? ("LOOT 0.9.1-17-gab5bdd2 (32 bit).7z" as of this writing.)

**Comment by Kiufie** [comment]
I don't know if this will help anyone else but I was able to fix my exact same issue by following the path that was given in the error and changing the plugins.txt to a non read only. I'm using the latest LOOT version and Fallout 4 update on windows 7 Pro 64-bit.

**Comment by Hyrakzo** [comment]
luckydonalds tips on having NMM open at the same time as LOOT seems to be working for me.

Now the second time im opening LOOT without having NMM running seems to have fixed problem 👍
