### ISSUE TITLE
LOOT not recognizing masters MO and Fallout 4

### ISSUE THREAD

**Issue by cfs3rd** [loot/loot#519]
When using LOOT through MO for Fallout 4 it is giving an error that some esp's are missing masters even though the masters are present. Here is the debug log.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/64798/LOOTDebugLog.txt)
If this is due to the mod authors mistakes then please delete this post. Thank you for your time and the work you all do.
Windows 10 64 bit Home latest build
MO v 2.0.0a
LOOT API v0.8.1-38-g7c4fe9f (64 bit)

**Comment by WrinklyNinja** [comment]
Does it work without MO in the mix?

**Comment by cfs3rd** [comment]
Yes, it works with manual install and with NMM. It seems to only happen with MO. I did merge the updates into the original files when installing. Will try reinstalling as separate mods.

**Comment by WrinklyNinja** [comment]
If it only happens with MO, it's hardly an issue with LOOT.

**Comment by cfs3rd** [comment]
I agree and I thank you for your time. :-)
