### ISSUE TITLE
I don't even...

### ISSUE THREAD

**Issue by DubstepNinja88** [loot/loot#521]
I need LOOT in order to organize my mods. So I looked it up and found this site. However, there is a problem. There are no instructions anywhere for installing LOOT properly, and no less than six different downloads. How am I supposed to know which one to get? Do I get them all? Once I do, where do I put them? What do I do with all these separate files. If I need them all, why aren't they zipped? If I don't, why isn't there some kind of indication as to what I'm supposed to be doing. I literally can't find a single clue. I've been trying to fix my mods for twelve hours. Now this... I don't intend to come off as rude or anything, but I think these questions are ones that need to be asked and considered. I can't be the only person who arrives to the page and sees six separate downloads and no indication anywhere what to do with whatever unknown number of them I'm supposed to be using... I don't know how quickly I can expect responses here, but regardless, I hope this is addressed so that no one else has to deal with this in the future.

**Comment by EpicBurrito** [comment]
Dude, if 6 separate, clearly labeled downloads are too much I don't know how you expect to deal with the nonsense you'll see on the nexus.

On top of this, LOOT is available on the Nexus for every game it works for.

The .exe one is clearly labeled "INSTALLER", and it is for people that want an installer.

The .7z one is a zip (7z is required for modding, you should get it and recognize it), and is for people that prefer loose files.

The rest are pretty self-explanatory.

I also don't intend to come off as rude or anything either, but dude, this isn't rocket surgery.

**Comment by Freso** [comment]
I'm not sure I even want to know what rocket surgery is like. :laughing:

But yeah, as @EpicBurrito says, I don't really see the issue. So closing.
