### ISSUE TITLE
New condition function: many_active()

### ISSUE THREAD

**Issue by Freso** [loot/loot#522]
We're currently able to distinguish between active and inactive plugins by using `active()` vs `file()`, but there's no way to do a regex to check for multiple active plugins, as `many()` behaves the same as `file()` (or, well, as `regex()`, but the point is it doesn't distinguish between active plugins and other files/non-active plugins).

This would be useful for e.g. the [`*useOnlyOneX`](https://github.com/loot/fallout4/blob/78343bb065aa20560edf5c51f91333438dcdd5b2/masterlist.yaml#L21-L33) messages. There's no point in showing an error (though perhaps a warning) if all the other X plugins aren't activated.

**Note:** This would break current v0.8 masterlist format compatibility, so maybe it should be held back until we have more format changes we want?

**Comment by Freso** [comment]
Perhaps an `regex_active()` as well? (Or switched around so they're `active_regex()` and `active_many()`?)

**Comment by WrinklyNinja** [comment]
`active_many()` seems like a sensible addition. Could you give an example use-case for `active_regex()`?

And yep, they would be added in v0.10, not v0.9.

**Comment by Freso** [comment]
I can't think of any case for `active_regex()` right now, I just know that I wish I had `active_many()` available for my latest addition to the FO4 masterlist. :)

**Comment by WrinklyNinja** [comment]
@Freso: Is this still a useful feature you'd like?

**Comment by Freso** [comment]
Yes.

**Comment by WrinklyNinja** [comment]
This is now done in the `masterlist-syntax-changes` branch, but I'll leave the issue open until the branch is merged.
