### ISSUE TITLE
Don't ask for apply/discard after sort if post-sort order is same as before

### ISSUE THREAD

**Issue by Freso** [loot/loot#523]
Currently LOOT will always ask for a sort order to be applied or discarded following a sort, even if the "new" calculated load order is identical to the previous one. It would be nice if it just gave a message that the load order wasn't changed/didn't need changing.

I'm assuming this will also potentially save some disk writes (don't know how FAT/NTFS handles writing an identical file to disk, but it'll at least need to write the "last updated" bit somewhere) and in particular now with NMM/FO4 launcher racing to read-only/reset `plugins.txt` it would be great to know that one doesn't need to de-read only-fy the file to get a non-changed load order applied. :)

**Comment by WrinklyNinja** [comment]
Good idea, should be simple enough to do.
