### ISSUE TITLE
Plugin card content is blank on filter then scroll

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#538]
Reported by pStyl3 [here](http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/?p=24864932) with more information [here](http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/?p=24867840).

If the "Hide messageless plugins" then "Hide Bash Tags" filters are applied, then removed in the same order, then the plugin card list scrolled, the first recycled card's title content (name, version, CRC) will be blank (the menu button is still displayed, as are status icons).

Inspecting this shows that this seems to be a purely rendering issue, as no unexpected styling is applied, and the content strings are present, just not displayed. Most UI interactions (switching sidebar tabs, viewing a tooltip, opening menus) then cause the text to be displayed correctly.

This bug is present in the v0.8.1 release and the latest `dev` code. I'm unsure if I can actually fix it, as it may be a Chromium bug, but a workaround could be to add a 'silent' UI interaction after a card's content is created or in a scroll event handler.

**Comment by pStyl3** [comment]
As it turns out, using the filter "Hide messageless plugins" isn't needed to reproduce this bug. I can now reproduce it with only "Hide Bash Tags".

**Comment by pStyl3** [comment]
As of snapshot 0.8.1-212, this issue seems to be fixed. I couldn't replicate it, although trying to do so multiple times.

**Comment by WrinklyNinja** [comment]
Fixed as of 543158b395374848fdb0e6aec42fa03178d1013f.
