### ISSUE TITLE
libcef.dll missing

### ISSUE THREAD

**Issue by Sneaks911** [loot/loot#541]
Loot wortked perfectly of Friday, Sat the computer was unused, and Sunday, I clicked on LOOT and recieved 
LOOT.exe - System Error
The program can't start because libcef.dll is missing from your 
computer.  Try reinstalling the program to fix this problem.

I reinstalled LOOT API v0.8.1-146-gb199982 (32 bit).7z, tried LOOT v0.8.1-38-g7c4fe9f (64 bit).7z since I run a 64bit, coppied libcef.dll to the Steam/bin folder.  Non of these have worked.  I don't know what else to do.

**Comment by Freso** [comment]
Try again using the latest 32-bit snapshot, and if it still doesn't work, please provide us more extensive information as per https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully

**Comment by Sneaks911** [comment]
That worked.  Thank you.

RHONDA

“When fascism comes to America it will be wrapped in the flag and carrying a cross.”

 Sinclair Lewis  (American Writer, 1885-1951)





Date: Sun, 31 Jan 2016 16:34:09 -0800
