### ISSUE TITLE
LOOT refuses to close.

### ISSUE THREAD

**Issue by kyotra** [loot/loot#542]
Go into menu>quit, doesn't close. Click window x, doesn't close. Alt+F4, doesn't close. Have to kill process with task manager. Using 0.8.1 snapshot from the Fallout 4 Nexus. On Windows 7.

**Comment by WrinklyNinja** [comment]
Does this happen every time you open LOOT? If not, what actions cause it to occur?

**Comment by kyotra** [comment]
It happened about 4 times in a row, however it has stopped acting up for now. I'll try and replicate the issue.

**Comment by kyotra** [comment]
Okay, finally happened again. I believe it may be triggered by changing and applying a new load order after receiving the "cannot write to plugin.txt" error.

**Comment by WrinklyNinja** [comment]
Try with the [latest snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (in the polymer-1.2 folder).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
