### ISSUE TITLE
"Invalid instantiation of non-const reference of type 'YAML::Node' from an rvalue of type 'YAML::Node'" when compiling LOOT

### ISSUE THREAD

**Issue by Insidious611** [loot/loot#545]
[  5%] Building CXX object CMakeFiles/LOOT.dir/src/gui/handler.cpp.o
/home/dmorrison/Downloads/loot-dev/src/gui/handler.cpp: In member function ‘bool loot::Handler::HandleComplexQuery(CefRefPtr<CefBrowser>, CefRefPtr<CefFrame>, YAML::Node&, CefRefPtr<CefMessageRouterBrowserSide::Callback>)’:
/home/dmorrison/Downloads/loot-dev/src/gui/handler.cpp:285:51: error: invalid initialization of non-const reference of type ‘YAML::Node&’ from an rvalue of type ‘YAML::Node’
                 _lootState.load(request["args"][0]);
                                                   ^
In file included from /home/dmorrison/Downloads/loot-dev/src/gui/handler.h:28:0,
                 from /home/dmorrison/Downloads/loot-dev/src/gui/handler.cpp:25:
/home/dmorrison/Downloads/loot-dev/src/gui/loot_state.h:36:14: note:   initializing argument 1 of ‘void loot::LootState::load(YAML::Node&)’
         void load(YAML::Node& settings);
              ^
CMakeFiles/LOOT.dir/build.make:590: recipe for target 'CMakeFiles/LOOT.dir/src/gui/handler.cpp.o' failed
make[2]: *** [CMakeFiles/LOOT.dir/src/gui/handler.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/LOOT.dir/all' failed
make[1]: *** [CMakeFiles/LOOT.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

The above happens when trying to compile LOOT.

**Comment by WrinklyNinja** [comment]
Which branch/platform/compiler?

**Comment by WrinklyNinja** [comment]
Also, please provide the revision that is failing.

**Comment by Insidious611** [comment]
Commit abf0cc5 of branch dev, Linux (Debian stretch), gcc 5.3.1

**Comment by Insidious611** [comment]
Also, since it's probably relevant to the bug, for yaml I'm using yaml-cpp patched-for-loot e377ae1 https://github.com/loot/yaml-cpp/commit/e377ae191ddbe565b9d584f30729806cf0a1f117
