### ISSUE TITLE
Cannot define a game, error code -1

### ISSUE THREAD

**Issue by miere43** [loot/loot#548]
When I launch LOOT I see first time launching note and list of games to manage in LOOT. When I click apply, this error pops out:
```Error code: -1; Invalid game ID supplied.```
I set up everything right, even deleted all rows and did other naughty things but this crap anyway shows this error. I tried to install 0.7.1/0.7.0, error is still present.

Also, when hitting apply button with 1 or more games without specifiyng Install Path UI remains unresponsible with darker background.

I have tried to enable debug log, but there's nothing, just this:
```[0308/170603:ERROR:main_delegate.cc(730)] Could not load cef_extensions.pak```

OS: Windows 10 x64
Loot: 0.8.1

**Comment by WrinklyNinja** [comment]
The Settings dialog is displayed on launch when LOOT can't find any of the supported games, there should be an error message highlighted in red: `None of the supported games were detected.`. 

How to resolve this is covered in the [FAQs](https://github.com/loot/loot.github.io/wiki/LOOT-FAQs#a-game-is-installed-but-loot-cannot-detect-it-how-do-i-fix-this).

**Comment by miere43** [comment]
Well, I didn't saw this message, so it was kinda weird that even I specified path myself it didn't work anyway. Thanks, it's working now, sorry for false report.
