### ISSUE TITLE
LOOT refuses to close/no load order change

### ISSUE THREAD

**Issue by Barracuda4Surf** [loot/loot#551]
PLEEEEASE help! -.- 

I reinstalled FA4 and spent hours and hours (and hours) to select and install my favorite mods and did rely on LOOT to secure my load order.

But something went horribly wrong: 
First, after pressing "sort load order" I got a message that "C:\Users\***\AppData\Local\Fallout4\plugins.txt" was read-only. Okay, fixed that.

After that LOOT hang up after "sort load order" and "apply", had to close it via task manager. After a new try it didn't hang up, but the complete load order is sorted alphabetically now! [Edit: and that doesn't change ("Sorting made no changes to load order")]

I am using the newest NMM, Windows 8.1 x64, Java x64, latest LOOT from Nexus.

Help is really, really appreciated! Thanks! 

[EDIT: logfiles attached]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/164875/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/164876/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Try with the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0).

**Comment by Barracuda4Surf** [comment]
LOOT v0.8.1-231-g543158b (32 bit).7z 21hrs ago?
Or
LOOT v0.8.1-38-g7c4fe9f (64 bit).7z 3 months ago?
Because I thought I would need a 32bit one.

**Comment by WrinklyNinja** [comment]
The 32-bit one, it's the latest. The 64-bit build was an unsupported experiment.

**Comment by Barracuda4Surf** [comment]
Ok, thx - will give feedback

**Comment by Barracuda4Surf** [comment]
Hmmm... still no luck. Load order still alphabetical.

**Comment by Barracuda4Surf** [comment]
Ok, my bad. plugins.txt was read-only again... Do I have to switch it everytime I use LOOT aftzer I used NMM?
Anyway, it worked now, thanks!

**Comment by WrinklyNinja** [comment]
Yes, you'll need to make sure plugins.txt is not read-only until Bethesda release official mod support for Fallout 4 and NMM gets updated for that.
