### ISSUE TITLE
Check if Fallout 4's plugin.ini is set to read only

### ISSUE THREAD

**Issue by fluteamahoot** [loot/loot#553]
Hello! I've been having a continuing issue with LOOT not checking if plugins.ini is flagged as read only before it writes to the file. Not a biggy, but it is annoying. Thanks for a great tool!

Fallout 4 on Windows 10 x64 using LOOT v0.8.1

**Comment by WrinklyNinja** [comment]
I assume you mean `plugins.txt`, rather than `plugins.ini`. This is by design, and will remain so until official mod support lands.
