### ISSUE TITLE
Add hex load order indices to sidebar plugins

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#555]
This was brought up as useful in the forum thread, as other utilities use the indices to show the load order. This may be a little complex though, as the load order position would only be displayed for active plugins, so it's a compound-property state.

**Comment by WrinklyNinja** [comment]
@pStyl3: You were one of the people wanting this, right? How is the UI mockup below?

![screenshot 56](https://cloud.githubusercontent.com/assets/2430738/16896343/a70bcbc0-4b88-11e6-822b-eb58c48efbb9.png)

In this, Update.esm is inactive (for the sake of this mockup, forget that can't happen), so it has no index displayed.

**Comment by pStyl3** [comment]
That's right, I was [one of them](http://forums.bethsoft.com/topic/1588424-rel-loot-thread-22/page-4#entry25078128). I agree on the fact that the hex numbers should ideally be highlighted in some way or another, if the grey circle background will do the job .. maybe. I don't have anything against it yet, but seeing it in action will definitely help to form a fleshed out opinion.

**Comment by Freso** [comment]
I like it. :+1:

**Comment by WrinklyNinja** [comment]
> That's right, I was one of them. I agree on the fact that the hex numbers should ideally be highlighted in some way or another, if the grey circle background will do the job .. maybe. I don't have anything against it yet, but seeing it in action would definitely help to form a fleshed out opinion.

A new snapshot build is up in the `load-order-indices` subfolder, let me know what your fleshed-out opinion is.

**Comment by pStyl3** [comment]
I think it would be good if abcdef in the hex numbers would be written out capitalized, so ABCDEF. I've checked and Wrye Bash, NMM, MO as well as xEdit all use the capitalized letters, so it would be great if LOOT would do so aswell. And since one of the great aspects of showing load order indices is that we create a connection to the actual IDs ingame, it would also make sense to write 00 instead of 0, 01 instead of 1, and so on.

Changing this would likely mean that the export load order function should also be adjusted.

The grey circle background itself isn't bad per se, but with the current colors / contrast, it makes it unnecessarily hard to read the hex numbers (not to speak of the dark theme .. given how it is done right now, the numbers should probably be written in black so that they can be read). Changing the grey color of the circle background to be a bit brighter would help I think.

Last but not least, for whatever reason it seems that with snapshot "LOOT 0.9.1-42-gc66c289 (32 bit).7z" it takes both processes "Parsing, merging and evaluating metadata..." and "Sorting load order..." noticeable longer to finish than in previous snapshots.

**Comment by WrinklyNinja** [comment]
> I think it would be good if abcdef in the hex numbers would be written out capitalized, so ABCDEF.

Whoops, I didn't spot that.

> it would also make sense to write 00 instead of 0, 01 instead of 1, and so on.

OK.

> The grey circle background itself isn't bad per se, but with the current colors / contrast, it makes it unnecessarily hard to read the hex numbers (not to speak of the dark theme .. given how it is done right now, the numbers should probably be written in black so that they can be read). Changing the grey color of the circle background to be a bit brighter would help I think.

I'll increase the contrast. I haven't tested it with the dark theme, but I'll do that too.

> Last but not least, for whatever reason it seems that with snapshot "LOOT 0.9.1-42-gc66c289 (32 bit).7z" it takes both processes "Parsing, merging and evaluating metadata..." and "Sorting load order..." noticeable longer to finish than in previous snapshots.

I didn't spot the lowercase lettering because running LOOT through MO stopped working for me, it just started to get stuck on "Parsing, merging and evaluating metadata..." forever, and quitting would leave a LOOT.exe process open. Nothing significant changed, so I don't know why it's broken now, but maybe you're seeing a similar thing? From what I see, running LOOT independently doesn't take any longer than it did before.

**Comment by pStyl3** [comment]
Are we talking about MO1 or MO2? If seen similar with Alpha versions of MO2, but not with MO1 or later versions of MO2 (that being said, MO2 still has a few kinks to iron out).

For me, under MO1, LOOT 0.9.1-42 needs just longer than before, and under MO2 it takes _even_ longer, but it finishes nevertheless.

When it comes to running LOOT independelty, that seems to work just normal for me, but that is only with the vanilla files. I will need to copy&paste some files into \Data\ to test that on a larger load order, and that I will do tomorrow.

**Comment by WrinklyNinja** [comment]
> Are we talking about MO1 or MO2?

MO1.

**Comment by pStyl3** [comment]
That's quite strange, MO1 normally works just fine in my experience. In that case I would suggest to reinstall MO. Just delete everything in your MO folder BUT the "downloads", "mods" and "profiles" folder, and install a fresh MO1 installation over it.

**Comment by WrinklyNinja** [comment]
Ah, that got it working (but slowly, as you see) again! It looks like the load order index lookup needs optimising after all...

**Comment by WrinklyNinja** [comment]
It's tricky to have secondary text on a light grey background with good contrast, so how about a circle outline instead?

![screenshot 58](https://cloud.githubusercontent.com/assets/2430738/16906634/ede95226-4cb2-11e6-9388-f73bd7cba1a1.png)
![screenshot 57](https://cloud.githubusercontent.com/assets/2430738/16906636/ef845bb2-4cb2-11e6-96ac-c08d216229b4.png)

**Comment by Freso** [comment]
Circle outline looks good to me. :+1:

**Comment by pStyl3** [comment]
That looks great! Dark theme is perfect, within the light theme the circle outline could've be a tiny bit darker even.

**Comment by WrinklyNinja** [comment]
Is this better?

![screenshot 59](https://cloud.githubusercontent.com/assets/2430738/16923543/a6ed8922-4d12-11e6-9c20-bdb634a2e360.png)

I've exposed the colour as a CSS custom property so it will be themeable.

**Comment by pStyl3** [comment]
I like it. :+1:
