### ISSUE TITLE
Loot 0.8.1 Not detecting dirty edits?

### ISSUE THREAD

**Issue by NexusKnight** [loot/loot#557]
Just d'led the latest Loot version and at the same time re-installed Skyrim again. Only this time, Loot 0.8.1 didn't detect any dirty edits from Bethesda's DLC's! Namely Dragonborn, Dawnstar, Hearthfire and Babette. Just thought I should let someone know, as these have always been 'dirty' with the previous versions of Loot (on a fresh install). I should know, I've had to re-install this game several times lately, because of instability issues. Hope this helps and thanks for all your support.

NVM... I've figured it out... gotta select the parse button and the dirty edits are shown now - thanks

**Comment by WrinklyNinja** [comment]
Does it work with the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0)?

**Comment by NexusKnight** [comment]
I installed the 1.8.10 version, I'll have to try this new one for you and let you know...

**Comment by WrinklyNinja** [comment]
You don't need the API, you just needed what's in the non-API archive, but since it's working for you now, I'll close this.
