### ISSUE TITLE
LOOT error- cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Wanderer-Jiyuren** [loot/loot#563]
While attempting to set up a new skyrim profile, I encountered this issue with reordering my plugins. 
I am fairly new to modding, and did not see any relevant thread addressing this issue after considerable time searching. 

Any information regarding locating the source of an error with plugin reordering would also be greatly appreciated.

[CEFDebugLog.txt](https://github.com/loot/loot/files/215748/CEFDebugLog.txt)

**Comment by Freso** [comment]
This sounds like it's an error with the masterlist. Can you please provide the actual debug log as per https://github.com/loot/loot.github.io/wiki/How-To-Report-Issues-Helpfully

**Comment by Wanderer-Jiyuren** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/215777/LOOTDebugLog.txt)

**Comment by Freso** [comment]
I don't see the error message in that log. Is the log from the same run that you got the error in?

**Comment by Wanderer-Jiyuren** [comment]
yes. And regarding the masterlist version request, would that simply be the revision number listed at the top? If not, where would I find that?

**Comment by WrinklyNinja** [comment]
It looks like a JavaScript error message to me, so I'd expect it to be in the CEFDebugLog.txt. In any case, all error messages that reach the UI are supposed to be logged there, so it looks like the CEFDebugLog.txt you posted isn't for the run of LOOT that you encountered the error...

If it were a masterlist error, the error message would have a different structure, and Travis CI should have caught it.

**Comment by Freso** [comment]
Yes, that would be that revision "number". :)

@WrinklyNinja Latest loot/skyrim update was done by me, but that very same update parses fine by LOOT for Fallout 4, so…

**Comment by WrinklyNinja** [comment]
Try the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (not the archive with "API" in its filename) and see if it works with that.

@Freso: the syntax isn't game specific, so that makes sense.

**Comment by Wanderer-Jiyuren** [comment]
um... so I restarted the LOOT application, and it suddenly worked. o.o Thank you for your help guys.

**Comment by WrinklyNinja** [comment]
We didn't do anything... Can you try with the latest snapshot build anyway? You'll need to delete your `%LOCALAPPDATA%\LOOT\settings.yaml` file afterwards if you want to roll back to v0.8.1 afterwards, but testing the latest build may help.
