### ISSUE TITLE
LOOT Failed to Launch

### ISSUE THREAD

**Issue by stinky1678** [loot/loot#566]
Hey guys. I'm installing the STEP: Extended guide right now and I've ran into some problems with LOOT that I had never encountered before. Whenever I launch loot, be it from MO or stand-alone, nothing happens. The process will appear in task manager for a second and then disappear. Anyone else have this problem?

**Comment by dmcclccam** [comment]
I have the same problem here. :(

**Comment by Ghostwalker71** [comment]
if you have an anti-virus that scans for virus-like activity in unknown files it can false flag loot causing the behavior you describe. Flagging the loot exec as trusted is a way past this, just be certain that the file you have is valid( IE downloaded from a known source)
