### ISSUE TITLE
LOOT crashing on start

### ISSUE THREAD

**Issue by alexisalex** [loot/loot#567]
As per title
[0420/205726:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0420/205726:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0420/205727:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak

**Comment by WrinklyNinja** [comment]
Could I get the other (probably more useful) log too?

**Comment by alexisalex** [comment]
Other log? This is the one from appdata/local/loot where is the other one?

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by alexisalex** [comment]
There is no LOOTDebugLog.txt i can't reach the settings dialog so I did the enableDebugLogging: false > enableDebugLogging: true and that was the only file

**Comment by WrinklyNinja** [comment]
It must be failing before logging begins then... 

* Are you running LOOT through Mod Organiser?
* If you delete the `settings.yaml` file (in the same folder as the logs), does running LOOT recreate it?
* What about if you delete the whole `%LOCALAPPDATA%\LOOT` folder?

**Comment by alexisalex** [comment]
I've deleted the whole folder and its working now, thanks for your help..
