### ISSUE TITLE
Increase visibility time for "sorting made no changes" toast

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#569]
Suggested so as to give users more time to read and understand the message. It's currently at the default of 3 seconds, maybe increase to 5 and see if that helps?

**Comment by Freso** [comment]
I tried poking at this as it seems like a fairly easy thing to do ("change a variable"), but I can't seem to figure out where to do this. My initial reaction was to look out where the message was set (line 127 in `src/gui/html/js/events.js`) which calls `loot.Dialog.showNotification()` defined in `src/gui/html/js/dialog.js`. The thing causing the message to appear seems to be a `.show()` method, which I'm guessing is this one: https://api.jquery.com/show/ - but this doesn't seem to be what's hiding the element again, and I couldn't find that.

**Comment by WrinklyNinja** [comment]
It's a [`<paper-toast>`](https://elements.polymer-project.org/elements/paper-toast#property-duration) element:

**Comment by Freso** [comment]
Yes, I did figure that much out as well, but I didn't realise that that meant something specific. :)

**Comment by WrinklyNinja** [comment]
I've found that if the duration is increased so that one toast is already displayed when another needs to be displayed, the same toast will be re-used, with only the text changing, and the timer does not reset, so the second message is not visible for the full duration time.

Toasts are only supposed to be shown one-at-a-time, so the handling should probably be updated to close an existing toast and open a new one (maybe the same element can be re-used, I'm not sure).

**Comment by WrinklyNinja** [comment]
Done in 34711be54808243aa9b68e8ecc794592435d55b6
