### ISSUE TITLE
Loot crashing immediately on start, no signs of any error log

### ISSUE THREAD

**Issue by sketchslayer** [loot/loot#571]
So I have suspicions as to mods causing it and am in the process of disabling (taking a while due to them being pretty big), is there some way to force it to create some form of error log so I can have some sorta idea what exactly makes it decide it doesn't feel like opening?

Update: disable just finished and yeah, it wasn't the mods I suspected causing it to fail to load meaning I'm not even 100% on which game is causing it to not want to boot so I could really do with some way of forcing it to log the exact cause of crash.

**Comment by WrinklyNinja** [comment]
See [How To Report Issues Helpfully](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Note that if you used a snapshot build then try to run the v0.8.1 release, you need to delete your settings.yaml file, otherwise v0.8.1 will not launch.

**Comment by sketchslayer** [comment]
Ahh thanks, it was the settings.yami thing... now I feel dumb.
Thanks dude, trying to debug the mod list for TTW without this would be a nightmare.
