### ISSUE TITLE
First-time tips dialog is no longer displayed

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#572]
If settings.yaml is deleted, the first-time tips dialog should be shown on LOOT's next launch, but it isn't. I need to figure out why not.

**Comment by pStyl3** [comment]
FWIW, it was snapshot "LOOT v0.8.1-131-g4aff5a2 (32 bit).7z" that introduced the bug. Snapshot "LOOT v0.8.1-121-g7ddb9d4 (32 bit).7z" still seems to work regarding this issue.

**Comment by pStyl3** [comment]
Relevant forum link:
http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/page-5

**Comment by WrinklyNinja** [comment]
Fixed in 0d6c0c70bee4a82b4e78a09e030a9751acd61943
