### ISSUE TITLE
Weird Issue with loot

### ISSUE THREAD

**Issue by Snakestone91** [loot/loot#573]
Awhile back I got back into modding Skyrim, when I got back into it I was still running v6.1, eventually I found out LOOT had massivly update since then so I installed the newer version of LOOT. For awhile I had no issues then well...I have the latest version installed but it seems whenever I run LOOT it doesnt update my mods list. Any new mod I add is always stuck between Your Own Thoughts.esp and my Bash Patch at the bottom, it can be any mod. Even USLEEP can get put there if I unactive and reactivate the mod. I have to uninstall LOOT and run it twice for it to update my mods list. I say twice cause first it sorts all my mods, but it puts USLEEP under Wyrmstooth and Falskaar so I have to run it again to get it to place above those. Can someone help me out here? Its getting annoying. It doesnt move anything, nor modify my load order. If I uninstall LOOT and reinstall it, it seems to modify and move my load order. It says no masterlist update necessary and then nothing. No mods are moved and are under YOT and above Bash Patch. I had to set USLEEPs priority above Falskaar and Wyrmstooth cause LOOT kept putting them under it.

It also says that the High Res esps and the Unoffical Patch for it are empty plugins. Aswell eachtime I run LOOT it randomly throws plugins all over. I high doubt Unique Dogs or Solitude Public Bathhouse need to load after my Bash Patch. Someone please help, its gotten to the point im scared to run LOOT.

I did find a semi-fix. I installed LOOT v6.1 on another hard drive, I run that and hit apply and then run the newest version of LOOT and it sorts the plguins as it should (though USLEEP still loads after Wyrmstooth so I have to set priority manually), but I doubt this is an ideal fix.

**Comment by Sharlikran** [comment]
Both versions use different syntax for the settings.yaml files.  LOOT v6.1 is using an older masterlist and USLEEP isn't listed in it.  Go to C:\Users\<<your username>>\AppData\Local\LOOT and rename (to make a backup) settings.yaml to settings.bak.  Then _**only**_ run the latest version of LOOT.

**Comment by Snakestone91** [comment]
Hmm, seems iv ran into another issue I dont seem to have an AppData folder with Local or LOOT. I do have C:\Program Files (x86)\LOOT but I dont see a setting.yaml or setting.bak. I run the exe installer and it points to Program Files (x86), any help? Also, is the reason the newest version of LOOT not re-moving plugins from the bottom due to it reading settings from v6.1?

**Comment by WrinklyNinja** [comment]
> Hmm, seems iv ran into another issue I dont seem to have an AppData folder with Local

You definitely have `%LOCALAPPDATA%`. It's a hidden folder, if you can't find it, google how to.

**Comment by Snakestone91** [comment]
Okay, found it. USLEEP still loads after Wyrmstooth and Falskaar though.

**Comment by Snakestone91** [comment]
Update, issue is still happening, new esps are set between YOT and Dyndolod

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
