### ISSUE TITLE
New masterlist rule: CACO must load after CCOR

### ISSUE THREAD

**Issue by Thallassa** [loot/loot#574]
I hope that posting these as issues is ok. 

I sorted the other day with the current version of the masterlist and noticed this was not sorted correctly. 

Complete Alchemy & Cooking Overhaul.esp must sort _after_ Complete  Crafting Overhaul_Remade.esp

(it must also sort after disparity.esp)

This is on the mod description page for CACO and I've confirmed it in TES5edit.

**Comment by WrinklyNinja** [comment]
Could you please re-file this issue in the relevant masterlist's issue tracker? I'm guessing this is for Skyrim, so that would be [here](https://github.com/loot/skyrim/issues).

**Comment by Thallassa** [comment]
Ok, thanks!
