### ISSUE TITLE
None of my games are dected.

### ISSUE THREAD

**Issue by Azhara1** [loot/loot#578]
Hello, Just like..2-3 days ago my Loot was working fine for Skyrim and now I restarted my computer and now it won't detect any of my games. Skyrim,Oblivion,Fallout 3 or Fallout 4. And everytime I try to get it to detect I just get the error saying (Error code:-1;Invalid game ID supplied ) I'd really like some help with this problem.

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Also, did you change anything else other than restarting your computer? Which version of LOOT are you using?

**Comment by Azhara1** [comment]
I'll read that in just a second. I just really want this problem fixed lol. I haven't changed anything I'm on version 0.9.0. I reinstalled it to attempt to fix this. When I start up Loot ( https://gyazo.com/2961ccb3db8bcae9dc0f9668ef648af7 ) That comes up. So I hit apply then ( https://gyazo.com/e95024c043ee995423287361b7ecfd0c ) That. I'm really not sure on what to do so I came here in hope to fix this because I don't like Mod Organizer it's to..Complicated xD Which is why I love Loot more.

**Comment by WrinklyNinja** [comment]
The settings panel is displayed because LOOT can't detect any games. Try running the games' launchers to add their Registry entries, or you can put the paths to their folders in LOOT's settings panel.

**Comment by Azhara1** [comment]
Ah Thank you Ninja. I'm really sorry that this simple problem was a bother haha. Though I got it to work finally by opening the launcher for Skyrim.

**Comment by WrinklyNinja** [comment]
OK, closing this since it's fixed.
