### ISSUE TITLE
Reorganise Settings UI layout

### ISSUE THREAD

**Issue by Ortham** [loot/loot#581]
The Settings dialog's games table is pretty cramped, so it would be good if it could be made more readable. 

I'm thinking of giving the dialog two tabs: General and Games. The four non-game settings would be listed vertically in the General tab, while the Games tab would be split in half. On the left would be a list of game names, with an "Add game" input and button at the bottom of the list, while on the right would be the game settings fields, but listed vertically instead of as a table row. This layout makes better use of the available space.

Selecting a game on the left would initialise the fields on the right with its values. The user would be unable to select another game while a field has an invalid value, and adding a game would automatically select it (so adding would also fail with existing invalid values).

This will require temporary storage of game settings values while the dialog is open, as there is only one set of fields and it should still be possible to discard the values.

**Comment by Ryder17z** [comment]
I'll just chuck something in here: there should be a "Browse" option to set the path manually to a supported game.

**Comment by Ortham** [comment]
Here's the direction I'm going with this at the moment:

![Screenshot 2021-03-16 184556](https://user-images.githubusercontent.com/2430738/111363436-f12e9180-8687-11eb-9c6d-29e277273d99.png)

![Screenshot 2021-03-16 185944](https://user-images.githubusercontent.com/2430738/111364947-ca715a80-8689-11eb-9891-710f64ff671c.png)

The Games tab still needs a lot of work on styling and also all of the interactivity.

**Comment by Ortham** [comment]
I've now pushed my changes in the `settings-ui-overhaul` branch, I've changed the design from above as having tabs and a sidebar made navigating the dialog messy. Screenshots of the new layout are below.

![Screenshot 2021-03-24 213651](https://user-images.githubusercontent.com/2430738/112387290-7b5ea180-8ce9-11eb-93db-4214da735a54.png)

![Screenshot 2021-03-24 213633](https://user-images.githubusercontent.com/2430738/112387286-7a2d7480-8ce9-11eb-8f9a-f5574b4755e7.png)

**Comment by MacSplody** [comment]
> I've now pushed my changes in the `settings-ui-overhaul` branch, I've changed the design from above as having tabs and a sidebar made navigating the dialog messy. Screenshots of the new layout are below.

That is much better, it looked a bit cramped before.

**Comment by pStyl3** [comment]
I agree with MacSplody, it looks great and much cleaner. Just an idea though, would it be feasible to list the games that LOOT supports categorized by the franchise they belong to? So for example:

The Elder Scrolls
- TES III: Morrowind
- TES IV: Oblivion
- TES V: Skyrim
- TES V: Skyrim Special Edition
- TES V: Skyrim VR
- Enderal: Forgotten Stories (Special Edition)

Fallout
- Fallout 3
- Fallout: New Vegas
- Fallout 4
- Fallout 4 VR

The question would be how this could be done within the left pane in the new settings menu. Would collapsable entries for `The Elder Scrolls` and `Fallout` be possible?

> General
> 
> [+] The Elder Scrolls
> [+] Fallout

Or simply by inserting a bit of empty space inbetween the different entries (possibly bolding them)?

> General
> 
> **The Elder Scrolls**
> a
> b
> 
> **Fallout**
> c
> d

**Comment by sibir-ine** [comment]
Yeah, the new settings menu looks amazing! Great work, Ortham! I also like pStyl3's idea of collapsable entries.

**Comment by Ortham** [comment]
I can add stuff like section / catagory separators between list items no problem and I was thinking of having a "Games" heading to separate general settings from games' settings, but I can't find a good way to style the headings unambiguously without taking up loads of space.

Collapsable entries would be a bit tricky, since only direct children of the list element are selectable. It could be done with some scripting like "when this section title is clicked, hide all following sibling elements until the next section title".

**Comment by RacerBG** [comment]
@Ortham Your latest concept looks good to me. In my opinion collapsible entries are not needed of they are hard to implement.

**Comment by pStyl3** [comment]
Hmm, I don't really think, that formatting `General`, `The Elder Scrolls` and `Fallout` differently would be the way to go.

What if instead of writing `Settings` at the top of the window, we use `Settings` as a header in the left pane? So Like this:

> ### Settings
> General
> 
> ### The Elder Scrolls
> Oblivion
> Skyrim
> 
> ### Fallout
> Fallout 3
> Fallout 4

The header doesn't necessarily need to use bigger font size, but they likely should be formatted in the same way. Sort of like the Discord options menu.

**Comment by MacSplody** [comment]
I still like the one without the extra headers, I don't think they add anything that warrants their inclusion.

**Comment by Ortham** [comment]
Since opinion is divided and I don't feel strongly about any particular direction, I'm just going to merge the changes as they are. We can always tweak it more in the future.

**Comment by RacerBG** [comment]
@Ortham Could you update the translation files too if any new strings are added to the template file? I did not pay attention if your commit added new strings though...

**Comment by Ortham** [comment]
@RacerBG There are a few new strings in the template file. I don't know what you mean by updating the translation files, I can't translate the strings myself.

**Comment by Ortham** [comment]
Done as of f97feaeec4007e7e0bae2c370a0a169f9f88e9af.

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG There are a few new strings in the template file. I don't know what you mean by updating the translation files, I can't translate the strings myself.

I mean to just add the new strings in to the translation files not just the template. I know that you can not translate them in every existing language for LOOT.

**Comment by sibir-ine** [comment]
> I mean to just add the new strings in to the translation files not just the template. I know that you can not translate them in every existing language for LOOT.

@RacerBG I'm not 100% sure, but I believe that strings missing translations will default to English anyway. The translation files only need to be updated by a translator when they provide new translations or update old ones.

**Comment by Ortham** [comment]
> I mean to just add the new strings in to the translation files not just the template. I know that you can not translate them in every existing language for LOOT.

> @RacerBG I'm not 100% sure, but I believe that strings missing translations will default to English anyway. The translation files only need to be updated by a translator when they provide new translations or update old ones.

What sibir said, there's no point in me updating the `*.po` files as that won't have any effect until the strings can actually be translated.
