### ISSUE TITLE
Fallout 4

### ISSUE THREAD

**Issue by kcoun** [loot/loot#582]
I'm using 0.9.0  ... NMM 61.23 and the latest Fallout 4.  Once loaded LOOT runs a sort, but doesnt sort / change anything.  (Plugins are listed in the order I've added them and I seriously doubt that's the best sort order)   Skyrim works just fine as did previous versions of LOOT.   Any ideas ?   I'm sorta stumped here ... Is there a problem sorting Fallout 4 ?   Thx

**Comment by WrinklyNinja** [comment]
If LOOT doesn't change anything, it's because it doesn't think anything needs changing. You think otherwise: why? If there's a reason, then that reason can be turned into metadata and possibly added to the Fallout 4 masterlist.

**Comment by kcoun** [comment]
Thanks for the response. You asked why I think otherwise -  Because the load order it keeps approving is purely chronological - that is to say based on the order that the mods were installed.   That seems a bit odd .. am I wrong ?

**Comment by WrinklyNinja** [comment]
LOOT doesn't move anything it doesn't think needs moving, and if you have mods that didn't have load order positions before, the order it uses is the order plugins are found in when your data folder is scanned. This order is undefined, but may be timestamp-based.

**Comment by kcoun** [comment]
ok ... just seemed odd that it didnt want to move any of 100 plugins off of the order in which they were installed, but then you know more about this than I do.   thanks.

**Comment by WrinklyNinja** [comment]
If you shuffle them around in the load order using a mod manager, you should then see LOOT keep that order when you sort with it. Closing this though, since it doesn't seem to be an issue.
