### ISSUE TITLE
Can't get Loot to show plugins as activated

### ISSUE THREAD

**Issue by brazenvoid** [loot/loot#583]
I am using 0.9.3 with latest NMM. I have had this issue since forever with loot for Fallout 4. Only the official master files show up as activated while all else as inactive. This happens when I install a plugin through NMM. Previously (Fallout 4 1.3) it got corrected when I had to do the frustrating reinstall of all plugins. Now with 1.5, it stays stubborn.

There is file CEFDebugLog or something, containing;
[0606/081756:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0606/081756:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0606/081756:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak

Please help, I can't play without it!

**Comment by WrinklyNinja** [comment]
There is no v0.9.3... Are the plugins you activate in NMM being prefixed with an `*` in your `%LOCALAPPDATA%\Fallout4\plugins.txt`?

**Comment by brazenvoid** [comment]
no * before any of the plugin names

**Comment by WrinklyNinja** [comment]
Then NMM isn't activating them, and LOOT is working fine.

**Comment by brazenvoid** [comment]
thanks for your time, found the issue to be in NMM also.
