### ISSUE TITLE
Only Fallout 4 is showing up

### ISSUE THREAD

**Issue by SixOfSpades** [loot/loot#584]
I'm new to LOOT so I don't know if this is a problem that's already been fixed or if it's even a real problem at all but when I open LOOT the only game I can select is Fallout 4 but I DO have a legal copy of Skyrim but it's just grayed out and I can't click on it.
I would very much appreciate any help
Thank you
Also I don't know if this affects anything but I'm launching LOOT with the Skyrim NMM
I just noticed that Fallout:NV and Fallout:3 also aren't working despite me also having them
I fixed my Skyrim problem by moving the LOOT folder into my Skyrim folder

**Comment by WrinklyNinja** [comment]
Have you run Skyrim's launcher?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
