### ISSUE TITLE
LOOT will no longer open through MO.

### ISSUE THREAD

**Issue by SilentAegis** [loot/loot#585]
First time being here. So I haven't played Skyrim for a few months and recently, I've decided to play it again. However, through MO, ( Mod Organizer ) it will not open. I make it run, it says LOOT is running, and then nothing. I haven't updated MO to MO2 or anything, nothing's changed. I've tried the following:

Reinstalling LOOT to the latest install.
Using the latest "snapshot" install.
Using the installer.
Using the 7z file.
Deleting the LOOT file in Local.
Putting LOOT in different directories.
Using the -single-process command.
Restarting my computer.
Watching install videos to ensure I installed it correctly.

It runs perfectly by itself, but once put through MO, it refuses to launch. I'm running out of ideas, so I'm hoping anyone here has a few. All other programs and tools launch fine. FNIS, Tes5Edit, etc. Any ideas are appreciated.

**Comment by Freso** [comment]
> It runs perfectly by itself, but once put through MO, it refuses to launch.

This means that it's a problem with MO and not with LOOT. Please file an issue at MO's issue tracker: https://github.com/TanninOne/modorganizer/issues
