### ISSUE TITLE
Global Priority user metadata is behaving inconsistently

### ISSUE THREAD

**Issue by iaz3** [loot/loot#586]
Global Priority user metadata is behaving extremely odd.

[Plugins uploaded to modwatch for readability.](http://www.modwat.ch/u/iaz3) with relevant sections starting at 152 and below

I've given Requiem.esp a global priority of 99, so it should load at the end of the load order. This works fine.

I'm attempting to get `Requiem - Legendary Bugsmasher Edition.esp` to load directly under `Requiem.esp`, and various attempts were tried and failed.

Attempting to give `Requiem - Legendary Bugsmasher Edition.esp` a global priority of -99 causes the plugin to be placed at the 11th space after `Requiem.esp`(Directly after `Requiem - Guard Dialogue & Open Helmets.esp`), for no discernible reason.

This is unexpected since it doesnt depend on anything except requiem, so it's not a masters issue, and it goes against what the docs say for Global Priority(0 is higher than -99, so why is it being put _after_ a bunch of others when they have a 0 non global priority?)

Changing the Global Priority to any of 99, -100, -98, or 98 has no effect on placement.

Increasing the Global Priority by 1, such that it is 100, causes it to be moved much lower in the LO, only 5 spots up from the bottom and directly above Alternate Start. This doesnt really make any sense or have an obvious cause.

Giving `COR-CraftingOverhaulReqtified.esp` a Load After rule for `Requiem - Legendary Bugsmasher Edition.esp` causes `Requiem - Legendary Bugsmasher Edition.esp` to be loaded directly after `Requiem.esp` as i want(COR remains in the same place as before, oddly enough), **BUT**, _ONLY_ if `Requiem - Legendary Bugsmasher Edition.esp` has a Global Priority less than 100, a negative value, or 0.

Values of 100 and up have the same effect as before.

All in all, this is extremely confusing, inconsistent, counter-intuitive, illogical, nonsensical, and just downright annoying.

Testing consisted of repeatedly clicking the sort button.

I didnt look for or test other plugins, mostly because i dont have any other plugins with a similar master situation(IE, ones that need tons of patches/have enough patches for me to actually test this behaviour)

[LOOTDebugLog.txt](https://github.com/loot/loot/files/310575/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/310576/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
That does sounds wrong...

Unfortunately that LOOT debug log doesn't seem to be from when you ran the sort, could you upload one taken from when you sort with LOOT?

**Comment by iaz3** [comment]
Under which situation?

Since i describe various different situations and circumstances that i sorted under, should i just get a separate log for each, or just do one and hope that can point you to the problem, or what?

**Comment by WrinklyNinja** [comment]
Under the original situation in which you discovered the issue, ie. giving `Requiem.esp` a global priority of 99 and `Requiem - Legendary Bugsmasher Edition.esp` a global priority of -99.

**Comment by iaz3** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/310675/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/310676/CEFDebugLog.txt)

**Comment by iaz3** [comment]
Possibly worth noting that while the mods that are being placed above it have no master list metadata referencing the bugsmasher, they do have load afters for the Requiem - Hearthfires.esp, but that itself has no metadata provided by the masterlist.

Possibly relevant due to how the issue seems to resolve when a load after is added to either the KFR or COR patches for the bugsmasher.

(According to the editor)

**Comment by WrinklyNinja** [comment]
Oh wait, this is happening due to priority inheritance: because `Requiem - Legendary Bugsmasher Edition.esp` has `Requiem.esp` as a master, the former inherits the latter's (higher) priority value, so -99 gets replaced with 99.

It's intended behaviour because otherwise it causes sorting inconsistency depending on how the plugins are iterated over.

**Comment by iaz3** [comment]
Thats a little inconsistent and unexpected(and not mentioned in the docs)

~~And, if so, how does that explain the huge difference in sorting between it having a value of 99 and 100? Shouldent it be 99 in both cases and have no difference?~~ Higher you say? So since all dependencies inherit a priority of 99, and 100 is higher, it overrides and it loads at the bottom?

In addition, how come adding a load after containing `Requiem - Legendary Bugsmasher.esp` to either the KFR or COR patch causes `Requiem - Legendary Bugsmasher.esp` to be where i want?

In theory it shouldent do anything except move them down, not move `Requiem - Legendary Bugsmasher.esp`(But only if it's priority is any value less than 100) right?

**Comment by iaz3** [comment]
Perhaps some sort of warning should be displayed when a master overwrites metadata, which the user may not expect to happen?

Or some other way introduced to load plugins in a certain order relative to their master? I imagine it may be useful, patches being in the right order can make the manual patching soo much easier

**Comment by WrinklyNinja** [comment]
> Thats a little inconsistent and unexpected

If A must load after B, A having a lower priority doesn't make any sense, A will always load as if it had a priority value at least equal to B's. I thought I'd documented it, I'll correct that.

> In addition, how come adding a load after containing Requiem - Legendary Bugsmasher.esp to either the KFR or COR patch causes Requiem - Legendary Bugsmasher.esp to be where i want?

> In theory it shouldent do anything except move them down, not move Requiem - Legendary Bugsmasher.esp up(But only if it's priority is any value less than 100) right?

I haven't looked into it, but moving the Bugsmasher plugin up is equivalent to moving the other two down, it's all relative.

> Perhaps some sort of warning should be displayed when a master overwrites metadata, which the user may not expect to happen?

It's standard behaviour, that would be like warning whenever you copy something to your clipboard that it's overwritten what was there before... If you're getting caught by it, then it needs to be more obvious / better explained, but I don't have any ideas on how to that (besides mentioning it in the readme).

> Or some other way introduced to load plugins in a certain order relative to their master? I imagine it may be useful, patches being in the right order can make the manual patching soo much easier

Plugins already load in a certain order relative to their master: *after*. If you want specific relative load orders between plugins otherwise, use requirement or load after metadata.

**Comment by iaz3** [comment]
> If A must load after B, A having a lower priority doesn't make any sense, A will always load as if it had a priority value at least equal to B's. I thought I'd documented it, I'll correct that.

My thinking was that it would go as high as it could, and since it cant go above it's master, it would go directly under it. 

> Plugins already load in a certain order relative to their master: after. If you want specific relative load orders between plugins otherwise, use requirement or load after metadata.

I dont get what you mean. Wont those just put it _somewhere_ after the master, not in whatever order you want/that all the patches **need** to be in to correctly override everything and each other?

**Comment by WrinklyNinja** [comment]
> My thinking was that it would go as high as it could, and since it cant go above it's master, it would go directly under it.

Not necessarily, see below.

> Wont those just put it *somewhere* after the master

Yes, that's how LOOT works - it doesn't do specific positioning, because it's a) not important and b) inflexible. A lot of people thinking exact positions are important: they aren't, it's all relative.

For example, say you have three plugins that must load A, B, C. You may think the rules are that C must load after A and B must load directly after A, but it's really C must load after B and B must load after A.

**Comment by iaz3** [comment]
If you say so..

I guess this isnt an issue, then.
