### ISSUE TITLE
Skyrim Scarcity plugin metadata cannot be saved

### ISSUE THREAD

**Issue by Triquetra** [loot/loot#587]
When attempting to edit the metadata for "Scarcity - Less Loot Mod.esp" from the [Scarcity Skyrim plugin](http://www.nexusmods.com/skyrim/mods/49496/?), I cannot save any changes made (such as load after, or global priority).  Any other plugins are fine, even the other plugins from this same mod.  But Loot refuses to save metadata changes for this plugin.  Pressing the save icon simply does nothing.  No errors, no complaints, and no save.  Does anyone know why this might be?

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). In particular, is there anything in your CEFDebugLog.txt?

**Comment by Triquetra** [comment]
[0616/094520:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0616/094523:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak
[0616/094524:ERROR:main_delegate.cc(766)] Could not load cef_extensions.pak

One line for each time I tried to push the "save" button when editing metadata for this plugin.

**Comment by WrinklyNinja** [comment]
Hmm, that's a harmless error though, and unrelated.

I just downloaded Scarcity and tried for myself though, and I'm experiencing the same issue, so I'll look into it.

**Comment by WrinklyNinja** [comment]
Ah, when you open it in the metadata, does the Bash Tags tab have an Add row with no Bash Tag name given?

For some reason LOOT thinks there's a bash tag with an empty name for the Scarcity plugin in the masterlist, but there isn't...

**Comment by WrinklyNinja** [comment]
Well, it's not coming from the masterlist, the Scarcity plugin has `{{BASH:}}` in its description field, which is the format used for Bash Tags, but it should have Bash tags after the colon, eg. `{{BASH:C.Climate,Names}}`. As it is, LOOT is reading the description and extracting a Bash Tag with a zero-length name.

I'll fix LOOT so that it doesn't accept empty names, but it's probably also a good idea if you let the mod author know.

**Comment by WrinklyNinja** [comment]
OK, I've uploaded new [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) that fixes the issue.

**Comment by Triquetra** [comment]
I tried the most recent upload at the link given, but It had no executable in it.  Was that intentional?  Anyway, I simply overwrote the existing Loot 0.9 directory with the new archive, and tried it, but I still have the same problem.  Though I am using the standard 0.9 executable...

**Comment by Triquetra** [comment]
Oops.  I downloaded the API instead of the program archive.  My bad.  Ok, now after trying the program archive, it does not work either.  I still can't save edits to metadata.  I noticed that when I first opened the metadata in Loot, the Bash tags tab does not show the empty entry.  But if I try to save the metadata, even if I don't change anything, the empty bash tag entry re-appears, and presumably prevents the saving of the metadata.

**Comment by WrinklyNinja** [comment]
Does an error message get displayed under the blank bash tag input when you try to save the metadata? Are you able to delete the table row it's in?

**Comment by Triquetra** [comment]
Yes, there is a message in red that says "A name is required".  No, I cannot delete the row.  The delete icon appears to be ghosted, and clicking on it does nothing.

**Comment by WrinklyNinja** [comment]
I don't get that, I wonder where it's picking that data up from now... Try deleting your `%LOCALAPPDATA%\LOOT` folder?

**Comment by Triquetra** [comment]
I had a little time to do some more testing today, and discovered my MO shortcut was pointing to the old executable because I had created a custom folder for Loot.  Now using the new executable, it won't start from within MO.  When I attempt to start it, MO "locks" like it does every time a program is run, but then it eventually goes back to MO without doing anything (after about 5 seconds).  The old executable (and all my others, XEdit, etc.) still work fine, so I don't think its an MO problem.

**Comment by WrinklyNinja** [comment]
Does the new executable work if you run it outside of MO?

**Comment by Triquetra** [comment]
It opens and looks like Loot normally does when run outside of MO, except that there are no mods because all the mods are in MO.

**Comment by WrinklyNinja** [comment]
In that case it's not a problem with LOOT. Can you temporarily copy the Scarcity plugin to your data folder to test without MO involved?

**Comment by Triquetra** [comment]
I can confirm that the new version you posted successfully alters the metadata of Scarcity - Less Loot Mod.esp when run outside of MO.  I'm still not sure why it doesn't work inside MO when the release version does...  Oh, well.  Thanks for the help, WrinklyNinja!
