### ISSUE TITLE
Loot will not recognize mods loaded by Mod Organizer fallout 4

### ISSUE THREAD

**Issue by djhoerauf** [loot/loot#588]
Hello, 
Sorry if this is a duplicate, i cant imagine i am the first to have this issue but i could not find a solution.
I am using loot .9.0.0, i am playing fallout 4 loaded by mod organizer 2.0.7.
I have loaded up a few dozen mods into mod organizer.(MO).  I click the drop down box for loot after providing the correct path in setup for MO, when loot loads it only shows up with the main game of fallout 4 and the 3 dlc's. I tried to find any place in loot setup to correct the path to my MO but everything is grayed out. under settings. any help would be great as the game will not play with the mods i have and being unorganized.
Thank you!

**Comment by WrinklyNinja** [comment]
Are you running LOOT through MO? It's not clear from your post if you are.

**Comment by djhoerauf** [comment]
i am running loot through MO, that is correct

**Comment by WrinklyNinja** [comment]
Does it work if you copy some mod plugins into the Data folder and run LOOT independently of MO?

**Comment by djhoerauf** [comment]
Loot does work if i copy in files directly to the date folder in fallout 4. I think my error is that loot can not find the mods from MO, even though i am running with my profile loaded from MO. Is there a way to direct LOOT to MO (even though i start Loot through MO) and to my profile if needed?

**Comment by WrinklyNinja** [comment]
If LOOT works independently of MO, then it should work through MO, and if it doesn't, there's not much LOOT can do about that.
