### ISSUE TITLE
Error on sorting Fallout 4 mods.

### ISSUE THREAD

**Issue by PirateToshio** [loot/loot#590]
_[Posted this on the ModOrganizer git as well because I'm not sure who's causing the error.](https://github.com/TanninOne/modorganizer/issues/827)_

I am running LOOT through Mod Organizer and whenever LOOT is launched I've had 2 different types of errors. 

First both the "Masterlist Revision" and the "Masterlist Date" both read:
`Git operation failed. Error: -1; Failed to open directory 'C:/Users/pirat/AppData/Local/LOOT/Fallout4/.git/objects/pack/':`

Also when I run the sort they both change to:
`An error occurred while trying to read the local masterlist's version. If this error happens again, try deleting the ".git" folder in C:\Users\pirat\AppData\Local\LOOT\Fallout4.`

Secondly, at launch both the "Masterlist Revision" and the "Masterlist Date" will both read:
`An error occurred while trying to read the local masterlist's version. If this error happens again, try deleting the ".git" folder in C:\Users\pirat\AppData\Local\LOOT\Fallout4.`
before the sort. 

After sorting 2 error messages will come up:
`Error code: 12; Failed to update the masterlist. Details: An error occurred while trying to update the masterlist. This could be due to a server-side error. Try again in a few minutes.`
and
`Error code: 1; Failed to sort plugins. Details: libloadorder failed to set the load order. Details: Zero-length plugin array passed.`

The first error set happens more often than the second.

**Comment by WrinklyNinja** [comment]
An easy way to determine if this is a LOOT or MO bug is to run LOOT independently of MO and see if the error still occurs.

**Comment by PirateToshio** [comment]
Thank's for the tip, confirmed it's an issue with MO, sorry to bother
