### ISSUE TITLE
Fallout4 dirty plugins

### ISSUE THREAD

**Issue by RestedWicked** [loot/loot#592]
Hi!
Is there any special reason fallout 4 plugins don't have dirty plugins warnings? Like cleaning the plugins isn't recommended yet at this stage of fo4edit or something? Or it's just not implemented yet?
Also a thumbs up on the suggestion to create a tag for cleaned plugins. A small icon like the ones used to show empty plugins or plugins with inis attached would be simplistic and clean-looking.
Congrats on the awesome work!

**Comment by pStyl3** [comment]
The automated cleaning process of FO4Edit is not yet ready to be used. Once that changes it most likely will not take long until LOOT's FO4 masterlist will start to feature metadata about dirty plugins.

**Comment by WrinklyNinja** [comment]
Closing this since the question has been answered.

**Comment by RestedWicked** [comment]
cool. thanks for clarifying. rolling back on the dlc esms that I cleaned :P
