### ISSUE TITLE
Loot will not start through MO

### ISSUE THREAD

**Issue by ThurkearGix** [loot/loot#593]
Ever since I downloaded Mod Organizer and using it for Skyrim, I've been running Loot with no problem. Updating whenever possible (version 0.9.1), keeping everything proper, etc. Then, 2 days ago, it just stopped working, for no apparent reason. Every time I try launch it through MO, it gives me the program running lock screen, and then that goes away and nothing happens. Outside of MO, it works perfectly, but does not have any of my mods from MO.

I've tried uninstalled and reinstalled both Loot and MO, and no joy.
I placed Loot in the MO folder, Skyrim folder, on my C drive (MO and Steam are on D drive), and no joy.
I took full control of Loot, and told it to require admin privileges, and no joy.
I installed version 0.9.0, and no joy.
I tried every possible combination of the above, and no joy.

It's been two days of trying every solution I can find on the web. pls halp meh

**Comment by RestedWicked** [comment]
I can run loot 0.9.1 both in mo2 and mo 1.3.11.
try reinstalling vcredist

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported, because as you've found out, it can break for who knows what reason, and there's pretty much nothing I can do about it.
