### ISSUE TITLE
loot_get_plugin_tags returns the same set of tags irrespective of mod

### ISSUE THREAD

**Issue by Utumno** [loot/loot#595]
Test driving LOOT.API.0.9.1-0-gdc24e10.32.bit.7z - from a point onward calls to `loot_get_plugin_tags` return me a fixed set of tags that changes every few iterations. Here are those tags tags for Oblivion:

[bashbugdump.txt](https://github.com/loot/loot/files/349904/bashbugdump.txt)

As seen till one point it returns correct (mostly empty) tags - then it suddenly starts returning the same set of tags - which changes every some iterations.

Same goes for Skyrim:

[bashbugdump - skyrim.txt](https://github.com/loot/loot/files/349913/bashbugdump.-.skyrim.txt)

Here is the debugger view:

![tags on empty mod](https://cloud.githubusercontent.com/assets/1365079/16620298/92bf5eac-439a-11e6-906e-34c843407291.jpg)

That's right when Bash starts - [_getTagCache](https://github.com/wrye-bash/wrye-bash/blob/114c83729aa50045cac4f381912007826d8048bf/Mopy/bash/bosh/mods_metadata.py#L290) calls lootDb.GetModBashTags(modName) which essentially [calls](https://github.com/wrye-bash/wrye-bash/blob/114c83729aa50045cac4f381912007826d8048bf/Mopy/bash/loot.py#L368) loot_get_plugin_tags.

**Comment by WrinklyNinja** [comment]
Ah, I didn't have a test for consecutive calls, and sure enough, it's broken...

**Comment by WrinklyNinja** [comment]
Sure, API bugfixes have priority over enhancements, and I can always release a v0.9.2.

**Comment by WrinklyNinja** [comment]
@Utumno: If you don't know, you can get snapshot builds [here](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0). Build 6 includes the fix for this issue.

**Comment by Utumno** [comment]
>  If you don't already know, you can get snapshot builds here. Build 6 includes the fix for this issue.

Didn't know - thanks - will test this ASAP.
