### ISSUE TITLE
Version comparison condition issue

### ISSUE THREAD

**Issue by MageKing17** [loot/loot#599]
UFO4P 1.0.4b shows as "outdated" compared to 1.0.2, according to the condition on its note in the masterlist, which is `version("Unofficial Fallout 4 Patch.esp", "1.0.2", <)`; a quick check of the source says psuedosem sees "4b" as not containing all digits and decides that means it's a "prerelease" version identifier, and therefore treating it as more like "1.0 beta 4" than "1.0.4.2"; not sure if the solution is to change psuedosem or to change how LOOT uses psuedosem (because appending letters to version numbers to indicate hotfixes is not a particularly uncommon scheme that should probably be supported).

**Comment by WrinklyNinja** [comment]
It's probably best to tweak pseudosem.

**Comment by WrinklyNinja** [comment]
This should be fixed in the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0) (9), can you confirm?

**Comment by MageKing17** [comment]
Confirmed; the snapshot build doesn't display the "outdated" message, and the condition in the metadata is the same.

**Comment by WrinklyNinja** [comment]
Great!

**Comment by Freso** [comment]
@MageKing17, does the latest version of the UFO4P report as "1.0.4b" in LOOT for you? I got the latest one off the Nexus which *should* be .4b, but LOOT shows it as 1.0.4a. So my question now is whether it's not fully updated on Nexus, or if @Arthmoor et al forgot to bump the version for .4b… or if LOOT is simply being silly for whatever reason. :)

(Sorry about the somewhat unrelated noise, Wrinkly!)

**Comment by MageKing17** [comment]
@Freso I downloaded it from bethesda.net so I can't speak as to the state of the Nexus version.

**Comment by Freso** [comment]
@MageKing17 But you can verify that your version says "1.0.4b" in LOOT? (It seems like "1.0.4b" has been uploaded twice to Beth.net, so maybe that forgot to update it the first time around, fixed it, and re-uploaded, but didn't reupload Nexus version?)

**Comment by MageKing17** [comment]
@Freso Yes, it shows as 1.0.4b in LOOT; otherwise I wouldn't have reported a problem with how it compared the string "1.0.4b", I would've reported a problem with how it compared the string "1.0.4a".
