### ISSUE TITLE
Loot Crash Error: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by KriticalKatIsTaken** [loot/loot#600]
After reloading Skyrim I noticed that some NPCs had missing textures that turned a light purple, so when I went to run LOOT I got the error: Unexpected token C in JSON at position 0
http://image.prntscr.com/image/bfb83e85c5e74eda9a61dad6c8ad0cdd.png

**Comment by WrinklyNinja** [comment]
Please provide your debug logs: see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by fireundubh** [comment]
I'm getting this error on Windows 10. Running Version 0.9.2 (build 6b58f92) through Mod Organizer 2.0.7.

- [CEFDebugLog.txt](https://github.com/loot/loot/files/546653/CEFDebugLog.txt)
- [LOOTDebugLog.txt](https://github.com/loot/loot/files/546654/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
I'll try to replicate it, though your LOOT debug log shows that the underlying issue is that your Data folder can't be found, which suggests MO is messing something up (if the path does actually exist).
