### ISSUE TITLE
Error when sorting for Oblivion

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#602]
Reported [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25184702), with more information [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25186104), [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25186106) and [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25186154) and [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25186166).

After sorting, some plugins have the error message `Cannot read "[insert mod name]". Details: ios_base::failbit set: iostream stream error`. Plugins affected include the DLC plugins:

```
DLCBattlehornCastle.esp
DLCMehrunesRazor.esp
DLCVileLair.esp
DLCFrostcrag.esp
Knights.esp
```

The last working build of LOOT was 4cb6576, and a9d1793 is the first build which exhibits the issue.

I'm not sure if it's related or not, but some plugins are reported as empty when they aren't, and inactive when they're active.

**Comment by WrinklyNinja** [comment]
Looking at the diff between the two commits given, there weren't any relevant changes between them that could have caused the issue...

**Comment by Freso** [comment]
> The last working build of LOOT was a9d1793, and 4cb6576 is the first build which exhibits the issue.

Time to hit the [`git bisect`](https://duckduckgo.com/?q=git+bisect)! :D (One of my favourite `git` commands that I get to use far too rarely. Too bad I don't actually have an environment here that I can build LOOT with to bisect it myself. :))

**Comment by WrinklyNinja** [comment]
> Time to hit the git bisect! :D (One of my favourite git commands that I get to use far too rarely. Too bad I don't actually have an environment here that I can build LOOT with to bisect it myself. :))

Unfortunately it looks like the cause is something outside of the version control, if I build 4cb6576 now, it has the same issue... It could be due to a Boost or CEF update, I'll just have to investigate manually.

**Comment by WrinklyNinja** [comment]
Well, I'm not sure what's going on. Libespm's test fail for Oblivion plugins, but they didn't when I last updated libespm, and passed on Travis. Since then there has been an MSVC update (30th March) and a Boost update (13th May), so I thought they may have changed something. 

I rolled back to Boost 1.60.0, but still experienced the same issue. I was on MSVC update 2, but a third update was released a couple of weeks ago, so I updated to that instead, but still no luck, so if a regression is the cause it still exists (I think that's unlikely though).

If I build and run the libespm tests on a local Linux VM, they still pass there too, I'm not sure what's going on...

**Comment by WrinklyNinja** [comment]
*Deleted my last comment because it turned out to be issues with my dev env, not the code.*

OK, I tracked it down to the wrong size of groups being calculated, but I'm not sure why it caused an error, it wasn't causing issues in the test plugins with groups and Knights.esp is too big to pinpoint the issue (I spent most of the day stepping through for loops trying to do so...).

**Comment by Zyntheos** [comment]
Used Snapshot Build: LOOT 0.9.1-10-g72934e4 (32 bit) can confirm it resolved "cannot read "[insert mod name]". Details: ios_base::failbit set: iostream stream error".
 Thank you for kepping my load order in order as always LOOT team.

**Comment by Nova25** [comment]
*Windows 7 - 64bit
*LOOT.0.9.1-0-gdc24e10.32.bit
*Oblivion : 5th Anniversary Edition

After adding all of the other DLCs (their .esp and .bsa), from 'other sources'.
I then install the 3 Unofficial patches, downloaded on the Nexus website : 
-Unofficial Oblivion Patch-5296-3-5-4b
-Unofficial Shivering Isles Patch-10739-1-5-8
-Unofficial Oblivion DLC Patches-9969-23

Once I click to 'Sort Plugins', I get an immense amount of red messages on the patches and the official DLCs(but not all), like such : 
**Cannot read "Unofficial Oblivion Patch.esp". Details: ios_base::failbit set: iostream stream error**
**This plugin requires "Unofficial Oblivion Patch.esp" to be active, but it is inactive.**
**Cannot read "DLCBattlehornCastle.esp". Details: ios_base::failbit set: iostream stream error**
**This plugin requires "DLCThievesDen.esp" to be active, but it is inactive.**
**This plugin requires "DLCThievesDen - Unofficial Patch.esp" to be active, but it is inactive.**

**Comment by WrinklyNinja** [comment]
> *LOOT.0.9.1-0-gdc24e10.32.bit

You're not using a snapshot build that includes the fix.
