### ISSUE TITLE
Test masterlist syntax's version check when the plugin exists but has no version

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#604]
This isn't currently tested. It should evaluate sensibly. Related to WrinklyNinja/pseudosem#2 and the conversation in [this commit](https://github.com/loot/fallout4/commit/c52fdb8a2c19a8e22b3af1629883e700286e2890).

**Comment by WrinklyNinja** [comment]
> Why should it always fail?

Ah, you're right, it shouldn't.

> Perhaps the logic should be changed so that if no version string can be found, assume it's version "0"?

I suspect that's what it does at the moment (but of course I should add tests). So for a missing version and a non-empty given version, do the following seem reasonable?

Comparison | Result
-------------|-------
`"" == "1"` | false
`"" != "1"` | true
`"" < "1"` | true
`"" > "1"` | false
`"" <= "1"` | true
`"" >= "1"` | false

**Comment by Freso** [comment]
That table is pretty much what I would expect to happen, yes.

**Comment by Freso** [comment]
And perhaps add a note to the documentation that an empty/missing version string would be treated as a 0 for the purpose of comparison, if this is what happens?

**Comment by WrinklyNinja** [comment]
Yes 👍

**Comment by WrinklyNinja** [comment]
LOOT behaves as expected in the table above, so no changes are necessary. :smile:

**Comment by Freso** [comment]
🙌
