### ISSUE TITLE
LOOT not loading under profile with over 100 mods.

### ISSUE THREAD

**Issue by DanBolivar** [loot/loot#606]
Hi, I've tried EVERYTHING before coming here for help... 
Loot is running fine as a stand alone, and under Mod Organizer profiles which run few mods.
But it seems to not want to kick with my primary playthrough profile that contains a lot of mods.

Is there something I may be doing wrong? Is this a known issue?
Please help. Much appreciated.

**Comment by DanBolivar** [comment]
UPDATE... Well, it seems that when one looks for help, the universe brings it. Even before those one asked for help even have time to type up a reply. :) Happily, it occurred to me that it could be my antivirus kicking in... and PRESTO! That was the issue. I shut down my antivirus, and LOOT ran perfectly loading everything and working fine. :)

ADMIN, please close this post of mine. Life is good!

**Comment by WrinklyNinja** [comment]
Glad you figured it out!
