### ISSUE TITLE
New condition function: regex_active()

### ISSUE THREAD

**Issue by Freso** [loot/loot#613]
@WrinklyNinja asked [elsewhere](https://github.com/loot/loot/issues/522#issuecomment-168379903):
> Could you give an example use-case for `active_regex()`?

I'm currently going through [Valdacil's Item Sorting](http://www.nexusmods.com/fallout4/mods/3877) and there are some plugins where I want to show a message if one of the "Val's Picks" combined plugins are active. It is unlikely that there would ever be more than one of those active (so not a usecase for `active_many()`), but with 4(+?) versions of the "base" plugin, it also quickly becomes cumbersome to do `active(…) or active(…) or active(…) or …`.

**Comment by Freso** [comment]
Or `regex_active()`. If `active_regex()` is used, perhaps rename `many_active()` to `active_many()`.

**Comment by Freso** [comment]
Alternatively: make it so `active()` takes a filepath *or* a regular expression, like the `name` plugin key (if it doesn't create too much overhead/complexity).

**Comment by WrinklyNinja** [comment]
> Alternatively: make it so active() takes a filepath or a regular expression, like the name plugin key (if it doesn't create too much overhead/complexity).

I could do that: for simplicity the string would be treated as regex only if it contains any of the characters `:\*?|`, like how `name` keys are decided. Would it also be useful to turn the `file()` condition function into something that accepts regex, and remove `regex()`?

**Comment by Freso** [comment]
I'd say so, yeah. That would give us `file()` for a single file, active or not; `active()` for a single file, active; `many()` for multiple files, active or not; `many_active()` for multiple files, active. Seems like that would cover all bases.

**Comment by WrinklyNinja** [comment]
Done in ec5e24f972dc18bd78227282a77795bf652a717e, but keeping this open until the branch is merged.

**Comment by WrinklyNinja** [comment]
Merged in bdd1cabb727731c223cc512914195e33947e027b
