### ISSUE TITLE
Can't use LOOT on Mod Organizer 1.3.11

### ISSUE THREAD

**Issue by vsoco** [loot/loot#614]
Set the aplications correctly, in accord with S.T.E.P.S guidelines, but as I try to run the aplications a quick dialoue box opens – as if it will run normally – and then simply shuts, without LOOT running at all.

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported.

**Comment by WrinklyNinja** [comment]
However, your issue does sound like #575, so maybe something in that issue will work for you.

**Comment by vsoco** [comment]
Thanks! Very fast answer!
