### ISSUE TITLE
Automate deployment of release docs to LOOT's website

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#620]
When LOOT is released, we manually add its docs to LOOT's website, but this can be automated. We can add a script to AppVeyor to commit LOOT's docs to the LOOT website repo when a tagged build passes. This would involve:

- Checking that the build is a tagged build
- Cloning the loot.github.io repo
- Editing the `docs/index.html` file to insert a new `<option>` for the new docs
- Adding the docs to a subfolder in `docs`
- Committing and pushing the changes

This would benefit from a minor change to the site's docs index, to initialise the links on load rather than hardcoding their defaults. I'm not sure how the `docs/index.html` file would be edited, I assume PowerShell has something like `sed` though.

I've got a robot account @WrinklyRobot that can be used to perform the commit (I could use a personal access token from my own account, but being able to clearly see it's done by an automated process has its advantages).

**Comment by Freso** [comment]
https://duckduckgo.com/?q=sed+for+powershell has a couple of hits that looks viable at least.

**Comment by WrinklyNinja** [comment]
Well I did this, but my robot is [committing](https://github.com/loot/loot.github.io/commits/master) on untagged commits for some reason...

**Comment by WrinklyNinja** [comment]
It's also appending an extra trailing newline with every commit, which I need to fix too.

**Comment by WrinklyNinja** [comment]
OK, done as of 1ef0af0bd60bfd747591a18832a338325ad5646c.
