### ISSUE TITLE
Automating .pot generation

### ISSUE THREAD

**Issue by Freso** [loot/loot#622]
Seeing how we're automating more and more of the trivial things related to LOOT (🙌), maybe it'd be possible to automate generating a new .pot file whenever a string has been changed (or maybe even whenever a string is moved to a new line)?

`xgettext --add-comments -k"translate:1,1t" -k"translate:1c,2,t" --add-location=full --from-code=utf-8 --package-name=LOOT --package-version=0.9.2 --copyright-holder="WrinklyNinja" --msgid-bugs-address="https://github.com/loot/loot/issues" -o resources/l10n/template.pot src/{gui,backend}/**.*`
or
`xgettext --add-comments -k"translate:1,1t" -k"translate:1c,2,t" --add-location=full --from-code=utf-8 --package-name=LOOT --package-version=0.9.2 --copyright-holder="WrinklyNinja" --msgid-bugs-address="https://github.com/loot/loot/issues" --join-existing -o resources/l10n/template.pot src/{gui,backend}/**.*`
run from the root of the repository seems to work well. Possibly with an `sed -i 's|charset=CHARSET|charset=UTF-8|' resources/l10n/template.pot` tossed in there.

I don't know how to notice that a string has been added/changed/removed though. Maybe it's possible to just run the command for each commit and disregard if `POT-Creation-Date` is the only thing that's changed?

**Comment by WrinklyNinja** [comment]
You could just run the command for every commit, but `POT-Creation-Date` probably won't be the only thing that changes, since the POT file also includes the source line numbers for messages, and that generates a lot of noise. Though it may be possible to diff ignoring comment lines...

Generating a POT file on changes to `dev` is a good idea though, and it could even be coupled to  notifications (email, IRC, whatever). However, I'd rather it weren't implemented as part of a CI build, because then you'd have most builds generating a new commit which generates its own build , effectively generating nearly twice the load. A Git `pre-commit`, `pre-push` hook would be better in that respect, though it obviously requires the user to "install" it first.

**Comment by Freso** [comment]
Yeah, I agree a `pre-commit` hook would probably be the best approach to this - this would ensure that every commit has a .pot relevant for that commit. I think as long as you and I have the hook set up, I think we should be good. (And really, by "you and I", I really only mean you. :stuck_out_tongue_closed_eyes: Though I'd probably set it up as well, just because.)

It doesn't look like `git diff` ships with an option to ignore comment lines, but it is possible to make `git diff` only look in specific paths - and I'm sure this can be hacked somehow to look at all paths except `resources/l10n` (or perhaps even specifically `resources/l10n/template.pot`).

I did an `xgettext` .pot update in https://github.com/loot/loot/pull/623/commits/9f59413d5fa553258830cbdc252ec2761fe8494b for https://github.com/loot/loot/pull/623 btw, using the more "invasive" approach of not using the `--join-existing` option.

**Comment by Freso** [comment]
Is there somewhere the current "dev" version is stored that can be used for the `--package-version` flag? (E.g., current `dev` would be `0.10.0` or `0.9.2`.)

**Comment by WrinklyNinja** [comment]
No,  I just tend to update the current version shortly before release, since I've always handled non-release stuff as being relative to the last release.

**Comment by WrinklyNinja** [comment]
35f8a84268ca3f334de54f41feb97a8e931682a2 adds a pre-commit hook script, I had to make a couple of changes from your command, because the `**.*` syntax wasn't working (probably a Git-on-Windows thing).

**Comment by Freso** [comment]
Yeah, I think `**.*` only works in a few shells, like [Zsh](http://www.zsh.org/) and [fish](https://fishshell.com/). (I use fish.) I'm not even sure it works in bash - but it definitely isn't POSIX compliant. Sorry about that! :)

**Comment by WrinklyNinja** [comment]
I fixed a comment in the script to be more accurate, the new commit ID is f202ae5c208c7c523968a84633686dbac08b5fb2.

**Comment by Freso** [comment]
* e3b39b72336ac07724afa8ef659ba4301df12d21 :)

**Comment by WrinklyNinja** [comment]
Yeah, I commented too soon. Anyway, this is done, so closing.

**Comment by Freso** [comment]
FWIW, in my local `loot/loot` clone, I've added
```
# Update .pot file if needed
/bin/dash ./scripts/git/pre-commit
```
to a copy of the default `.git/hooks/pre-commit.sample` so it also does all the trailing whitespace etc. checking.
