### ISSUE TITLE
Error when sorting for Oblivion - again

### ISSUE THREAD

**Issue by Nova25** [loot/loot#624]
Previous issue ( https://github.com/loot/loot/issues/602 ) was marked as closed, but it reappeared...

*Windows 7 - 64bit
*LOOT.0.9.1-0-gdc24e10.32.bit
*Oblivion : 5th Anniversary Edition

After adding all of the other DLCs (their .esp and .bsa), from 'other sources'.
I then install the 3 Unofficial patches, downloaded on the Nexus website :
-Unofficial Oblivion Patch-5296-3-5-4b
-Unofficial Shivering Isles Patch-10739-1-5-8
-Unofficial Oblivion DLC Patches-9969-23

Once I click to 'Sort Plugins', I get an immense amount of red messages on the patches and the official DLCs(but not all), like such :
Cannot read "Unofficial Oblivion Patch.esp". Details: ios_base::failbit set: iostream stream error
This plugin requires "Unofficial Oblivion Patch.esp" to be active, but it is inactive.
Cannot read "DLCBattlehornCastle.esp". Details: ios_base::failbit set: iostream stream error
This plugin requires "DLCThievesDen.esp" to be active, but it is inactive.
This plugin requires "DLCThievesDen - Unofficial Patch.esp" to be active, but it is inactive.

**Comment by WrinklyNinja** [comment]
Closing this as a duplicate, it's the same issue, you don't need to file it again.
