### ISSUE TITLE
Switch to using CEF's minimal distribution

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#626]
At the moment LOOT's CMake config downloads and builds using CEF's standard distribution, but a minimal distribution is also available. The minimal distribution is far smaller (94 MB vs. 224 MB on Windows) and contains the files LOOT depends on, so would be a better choice. For reference, all CEF downloads can be browsed [here](http://opensource.spotify.com/cefbuilds/index.html).

However, the minimal and standard distributions require different integration, with the minimal distro intended for tighter integration than how LOOT currently handles its dependencies. I looked into this before and thought it was a bug at first, but after discussion [here](https://bitbucket.org/chromiumembedded/cef/issues/1921/cmake-error-building-minimal-binary) it's by design. Since I want to update CEF to be Chromium 52-based, now is a good time to revisit the issue and try to get the dependency working.

**Comment by Freso** [comment]
Maybe get the 0.9.2 out and do this for 0.10.0? I think it'd be good to get the Oblivion fix out in a "real" release. Already plenty enough things in `dev` to justify a release.

**Comment by WrinklyNinja** [comment]
Yeah, I agree.

**Comment by WrinklyNinja** [comment]
Done in da4245925691cdeb191aad9b0bb4b49c4afbd600.
