### ISSUE TITLE
Plugins not showing

### ISSUE THREAD

**Issue by Pumpkin17** [loot/loot#628]
Sorry for putting this here, but I've asked multiple other threads about this, and none of them have answered my issue..

I'm using both latest Loot Version and the Latest Fallout Version...1.6.9

Loot isn't showing any plugins other than Fallout.esm...

It's not sorting any of the plugins, and I receive an Error Message...."You haven't sorted your plugins this session"

Using Mod Organiser...I hit the sort button, I ran it as an .exe...I manually moved mods about, nothing..

Ran it independently of Mod Organiser...and same Problem..

**Comment by Freso** [comment]
Do the mods actually reside in the Date/ folder outside of Mod Organizer?

**Comment by Pumpkin17** [comment]
No, the Mods are just in the Mod Organiser folder, which was always fine when I modded Skyrim a year or so ago..

And yes, 0.92

**Comment by Freso** [comment]
If run outside of MO, LOOT can only see whatever mods are in the Data/ folder. LOOT has no way of accessing MO's virtual environment if run outside of MO. And issues with LOOT run inside of MO should be reported to MO, as we can't fix whatever issues come up in MO.

**Comment by Freso** [comment]
http://wiki.step-project.com/Guide:Mod_Organizer_Advanced#The_virtual_filing_system for more information about MO's virtualisation.
