### ISSUE TITLE
Reimplement LOOT API as a C++ API

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#632]
For #597. To do:

- [x] Remove the various constants that are just casts of enums in favour of using the enums directly.
- [x] Always return outputs, never pass output parameters and modify pointers/references.
- [x] Replace the C types (ie. pointer arrays, C strings) with C++ equivalents.
- [x] Return Bash Tag strings directly when getting a plugin's tags: performance isn't significantly different from using an integer map, and it's simpler to use.
- [x] Make all the functions that take a `loot_db *` into member functions of an interface (`Database` above) that `loot_db` implements.
- [x] Conform to LOOT's C++ style, using CamelCase for types and underscore_names for variables, and namespacing everything in `loot` instead of using it as a name prefix.
- [x] Remove error code returns, just let the exceptions propagate.
- [x] Remove obsolete functions (`loot_get_tag_map()`, `loot_get_version()`, `loot_get_build_id()`)
- [x] Update documentation for functions/types and more general explanatory text.
- [x] Reimplement the C API as a wrapper of the C++ API, in a separate repository.
- [x] Modify SortPlugins to take a vector of plugin filename strings that are the plugins to sort.
- [x] Set empty strings as the default values for `CreateDatabase` and `LoadLists`'s optional path parameters.
- [x] Remove `DatabaseInterface::ApplyLoadOrder()`

**Comment by WrinklyNinja** [comment]
I've run into an issue where functions that returned standard string or container types would crash, and it turned out to be because statically-linked C++ runtimes have their own heaps, so the DLL had a different heap from the calling executable, and when the returned data went out of scope in the test case, the executable would try to free it, but it wasn't allocated in the executable's heap.

The solutions to this are:

1. Dynamically link the C++ runtime.
2. Manually manage memory that is returned by the API.

The former is what's recommended everywhere I've read (statically linking the runtime in DLLs seems to be strongly discouraged...), though I don't like adding a runtime dependency, and the latter is what the C API did.

**Comment by WrinklyNinja** [comment]
I've managed to get the C++ runtime dynamically linked, and it does indeed fix the issue crashing. However, while the API is now converted (on the `c++-api` branch), its documentation comments need to be updated, I forgot to do that while making all the changes.

**Comment by Utumno** [comment]
Just to suggest an addition (pardon my C++):

```
struct Database {
...
  vector<string> order_plugins(const std::set& plugins) = 0;
}

```

When I was a happy Bash user I would use several times per session the BOSS sorting menu item. 
order_plugins should just extract what info is to be found in the masterlist - Bash (or other clients) should take care of the rest (esm before esps etc)

**Comment by WrinklyNinja** [comment]
> order_plugins should just extract what info is to be found in the masterlist

How should that data be serialised? (I'm assuming you want one string in the output per plugin in the input.) Also, `SortPlugins()` will give you a LOOT-sorted load order, but not apply it, isn't that more helpful if you want to implement something like the BOSS sorting menu item?

**Comment by Utumno** [comment]
> How should that data be serialised? (I'm assuming you want one string in the output per plugin in the input.)

Correct

> Also, SortPlugins() will give you a LOOT-sorted load order, but not apply it, isn't that more helpful if you want to implement something like the BOSS sorting menu item?

Oops there was a code listing here - did not see that method (apparently it was in the "rest of methods"). Then this is all I need - no, applying load order is left to Bash - I just need the load order info contained in the masterlist.

**Comment by WrinklyNinja** [comment]
For the documentation, I've managed to get doxygen + Breathe + Sphinx working, now I "just" need to figure out how to write in reStructuredText for Sphinx, and bring it all together, then tie it into LOOT's CI system.

I've decided to do it this way because doxygen produces some pretty horrible documentation, but is the only practical way to document stuff in source code. I can use it to extract the reference documentation from the code, then use Breathe to make it accessible to Sphinx, which can then combine it with non-reference, out-of-source docs, and output something that's a lot more pleasant to read.

For distributing the documentation, I plan to hook into Read The Docs, and just package a readme that points to the online documentation. While that's not as good as providing some offline documentation too, the three main offline options have significant flaws:

* HTML documentation consists of multiple files, has things like multi-page search to deal with them, and is just too complicated for a relative simple library's local/offline docs.
* EPUB documentation would solve the HTML docs' issue, but Windows doesn't ship a reader and they aren't commonly installed, it's a bit esoteric for docs.
* PDF provides a single file, but requires LaTeX to be installed, which isn't feasible for LOOT's CI.

On the other hand, Read The Docs hosts HTML documentation on its website, hiding that complexity, and provides PDF downloads if you do want an offline file.

**Comment by WrinklyNinja** [comment]
The LOOT API documentation is now available on [Read The Docs](http://loot.readthedocs.org/)! It could do with more explanatory content, but it's now got everything the old reference documentation had, so I'm going to switch to moving the C API into a new wrapper repository. Once that's done, I'll add similar documentation for it and the Python wrapper, then everything will be at the same level.

**Comment by Utumno** [comment]
Re: SortMods (http://loot.readthedocs.io/en/c---api/reference.html#_CPPv211SortPluginsv ). I'd rather be able to pass it a set of mods to sort - any imaginable client should have at all times a set of load order mods (_excluding corrupted_ which is an issue). So have the client pass only those mods (or possibly a subset) would simplify the internals and practically make the API more powerful.

Coming to speak of which, if the API allows to extract load order info then the maketaglist scripts should be reworked to allow for having this info in the taglist.yaml files ( WriteMinimalList http://loot.readthedocs.io/en/c---api/reference.html#_CPPv216WriteMinimalListRKNSt6stringEKb should get a boost)

Finally the ApplyLoadOrder call should maybe be dropped - that's libloadorder's job - does the API include libloadorder internally ?

That's just from the top of my head - I should use the API to provide better feedback but as I said in 597 I am rather pressed at the mo.

**Comment by WrinklyNinja** [comment]
> Re: SortMods (http://loot.readthedocs.io/en/c---api/reference.html#_CPPv211SortPluginsv ). I'd rather be able to pass it a set of mods to sort - any imaginable client should have at all times a set of load order mods (excluding corrupted which is an issue). So have the client pass only those mods (or possibly a subset) would simplify the internals and practically make the API more powerful.

I can rework stuff to make SortMods() take a vector of plugin filenames, sure.

> Coming to speak of which, if the API allows to extract load order info

It doesn't :wink:, and I'd like to get what currently exists in the API settled before I start adding anything else. But if it did, I agree that WriteMinimalList should write that data.

> Finally the ApplyLoadOrder call should maybe be dropped - that's libloadorder's job - does the API include libloadorder internally ?

Yes, it's a straight passthrough to libloadorder, I provided it for convenience, but as you say there's not really any point, so I'll drop it.

**Comment by Utumno** [comment]
Thanks :)

> It doesn't 

Strange - I would think that ~~SortMods~~ SortPlugins uses that info (?)

**Comment by WrinklyNinja** [comment]
Ah, I misunderstood - yes, it uses that info. However, looking at the metadata stored, if WriteMinimalList() was modified to include metadata used for sorting, it stops being *minimal*, because most of the data is retained!

Having said that, I did quickly modify the validator to strip out incompatibility, message and location info, and it cut around 25% of the Skyrim masterlist out, so it's still significant (messages are the largest data structures, after all).

**Comment by Utumno** [comment]
Well - this goes towards a masterlist parser API slowly and efficiently - which is not a bad idea at all.
We could device a way to reduce size (by using for instance tag ids in the taglists bundled with Bash) but for once I would agree that size of those lists is not a big issue. On the other hand if this becomes a full time masterlist parser API, we could dispose of the taglists and bundle the masterlists theyselves (and/or use the API to update them).

One other possible way of going (which was the BOSS way and it is actually more elegant) would be to have loot.exe accept cli switches to do all those operations - so use user's loot and only fallback to the dll if loot is not present. This is of course for a later iteration (11+) - after the API is fleshed out and operational. But it has the huge advantage of using the user's install which should be more up to date than the dll bundled.

Re: docs: please focus your efforts on the database docs ( http://loot.readthedocs.io/en/c---api/reference.html#_CPPv2N4loot14CreateDatabaseEK8GameTypeRKNSt6stringERKNSt6stringE ) - what exactly is "load", what is "evaluate" what is cached, which operations are costly. The more detail the merrier.

----

Meanwhile - I intend to bundle 9.2 in my nightlies - which masterlist revision should I build the taglists with ?

**Comment by WrinklyNinja** [comment]
> On the other hand if this becomes a full time masterlist parser API, we could dispose of the taglists and bundle the masterlists theyselves (and/or use the API to update them).

What's stopping you from using the masterlists themselves right now? The taglists only contain tags and dirty info, both of which the API can parse.

> One other possible way of going (which was the BOSS way and it is actually more elegant) would be to have loot.exe accept cli switches to do all those operations

The reason I decided against this is because LOOT's sorted load orders are calculated, so it's more important that a human has a look at what it's done before agreeing to the changes (which is also why the LOOT UI gives the user the chance to apply or cancel a sort's result). With BOSS, humans put the plugins in that order, so there's a stronger implication of correctness there (however valid or not that is).

> Re: docs: please focus your efforts on the database docs ( http://loot.readthedocs.io/en/c---api/reference.html#_CPPv2N4loot14CreateDatabaseEK8GameTypeRKNSt6stringERKNSt6stringE ) - what exactly is "load", what is "evaluate" what is cached, which operations are costly. The more detail the merrier.

Thanks - because I know everything about how it works, it's hard to see what is most helpful to document.

> Meanwhile - I intend to bundle 9.2 in my nightlies - which masterlist revision should I build the taglists with ?

Whatever the latest v0.8 branch (0.9.2 uses the 0.8 syntax) commits are.

**Comment by Utumno** [comment]
> What's stopping you from using the masterlists themselves right now? The taglists only contain tags and dirty info, both of which the API can parse.

Well - didn't know that (plus the size). Will consider it though,  as it takes one more task off my plate - I am really full time and counting.

> Whatever the latest v0.8 branch (0.9.2 uses the 0.8 syntax) commits are.

Ok,  this one https://github.com/loot/oblivion/commit/2c8da7b6c45e1edb53d00cb1698d69321c415521

> The reason I decided against this is because LOOT's sorted load orders are calculated

Not only the load order but also the tags, clean state etc. For load order in particular, now that Bash features a pretty operational undo/redo load order this is not much of an issue ;)

> it's hard to see what is most helpful to document.

Also now we talk about it - more info on LOOT's load order calculation algorithm is much appreciated.

**Comment by WrinklyNinja** [comment]
> Ok, this one loot/oblivion@2c8da7b

Yes

**Comment by Utumno** [comment]
Sorry to hijack this - I dropped the mastrerlists instead of the taglists and replaced the loot_lang_any - I am getting this:
```

Wrye Bash starting
Using Wrye Bash Version 307
Python version: 2.7.10
wxPython version: 2.8.12.1 (msw-unicode)
input encoding: UTF8; output encoding: utf-8; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs 
Searching for game to manage:
bush.py   71 _supportedGames: Detected the following supported games via Windows Registry:
bush.py   73 _supportedGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   73 _supportedGames:  skyrim: C:\GAMES\Skyrim
bush.py  131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  137 _detectGames: Set game mode to oblivion based on sOblivionPath setting in bash.ini:  C:\GAMES\TESIV\Oblivion
bush.py  172 setGame: No preferred game specified.
bush.py  152 __setGame:  Using oblivion game: C:\GAMES\TESIV\Oblivion
testing UAC
__init__.py 7498 initDirs: Using libbsa API version: 2.0.0
mods_metadata.py  219 __init__: Using LOOT API version: 0.9.2
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 365, in main
    bosh.initBosh(opts.personalPath, opts.localAppDataPath, bashIni)
  File "bash\bosh\__init__.py", line 7700, in initBosh
    initDirs(bashIni, personal, localAppData)
  File "bash\bosh\__init__.py", line 7500, in initDirs
    configHelpers = ConfigHelpers()
  File "bash\bosh\mods_metadata.py", line 223, in __init__
    lootDb = loot.LootDb(bass.dirs['app'].s, bush.game.fsName)
  File "bash\loot.py", line 330, in __init__
    _CCreateLootDb(byref(self._DB),game,_enc(gamePath))
  File "bash\loot.py", line 234, in LootErrorCheck
    raise LootError(result)
bash.loot.LootError: LootError: LOOT_ERROR_INVALID_ARGS:Given local data path "" is not a valid directory.

```

The exception reads in the debugger:

    <type 'tuple'>: (<class 'bash.loot.LootError'>, <LootError: u'LOOT_ERROR_INVALID_ARGS:Given local data path "\x01" is not a valid directory.'>, None)

No clue where this x01 comes from - here is the commit:

https://github.com/wrye-bash/wrye-bash/commit/fb9b5611beb5db0033b42cc3855ff5f8fbfb9535

**Comment by WrinklyNinja** [comment]
Done as of d439d7ac524f2a7744c23a854c17784a139ad2ac, any further work can go as separate issues.
