### ISSUE TITLE
LOOT reporting SKSE outdated

### ISSUE THREAD

**Issue by SillySnowFox** [loot/loot#636]
The ingame menu reports version 1.7.3 installed, the skse website reports the current version as 1.7.3 LOOT claims my skse is outdated.

**Comment by Freso** [comment]
Could you please make an issue for this in the relevant masterlist's issue tracker? SKSE is for Skyrim, so that would be [this one](https://github.com/loot/skyrim/issues).

**Comment by SillySnowFox** [comment]
Ah, sorry I didn't realize there were different pages. I'll put it there.

**Comment by Freso** [comment]
Thanks. :) Closing as duplicate of https://github.com/loot/skyrim/issues/127
