### ISSUE TITLE
question: 64bit Loot? 

### ISSUE THREAD

**Issue by 321nick** [loot/loot#638]
i use mod organizer 2, and i am wondering, is it possible to use loot with it? i heard it does not run well with 32 bit programs, and i need to run it via mod organizer, as a shortcut, to have it detect the mods i have loaded. i heard there was a 64bit version of loot, but i cant find it. any help?

**Comment by pStyl3** [comment]
LOOT is and will be 32 bit for the foreseeable future and while MOv2 is 64 bit. it also runs 32 bit applications. If there were problems with running LOOT under MO, it would be the responsibility of the author of MO to fix those issues.

**Comment by 321nick** [comment]
thanks for replying @pStyl3 . i thought i heard somewhere that MOv2 had problems running 32bit programs, but apparently i am wrong.
