### ISSUE TITLE
Applying load order

### ISSUE THREAD

**Issue by BigBurkhart** [loot/loot#641]
After setting load order, everything seems to compile fine, but when I hit "Apply" I get this error:

Error code: 1; libloadorder failed to set the load order. Details: "C:\Users\Owner\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error

OK

How can I fix this?

**Comment by pStyl3** [comment]
The specified file plugins.txt is set to be "read only", so LOOT cannot change it's content. To fix this, rightclick on your plugins.txt > Properties > remove the tick infront of "Read Only", save.

**Comment by BigBurkhart** [comment]
Thanks. Sorry for being such a newb.
