### ISSUE TITLE
Loot don't responds at all

### ISSUE THREAD

**Issue by millhause** [loot/loot#644]
Hello.
Some months ago i had the same issue with version 1.8.x. At the time what worked for me was reverting back to version 1.7 to run loot on Skyrim. 
Now i've tried to install the new version 1.9.2 to loot mods for Fallout4 and... loot still behaves the same: Never create a LOOT folder on Appdata/local and if i try to just install the new version ontop of the old one (which already create the LOOT folder at appdata/local) it seems to remain untouched, as if it had no access to it. 
The only warning message i could find to try to illustrate the problem was a System warning box "Unable to execute file: C:/Program Files (x86)/LOOT/LOOT.exe  CreateProcess failed; code 2. The system couldn't find the specified file."
Other than that i already tried pretty much every single option to make loot run, including: 
- Deleting the LOOT folder at LocalAppData; 
- Using both installer n 7zip versions... on many different folders including C: ;
- Install the newer version on top of the old one;
- Unninstall the old one before installing the new;
- Use the 7zip file while there was a installed version (newer and older);
- Use just the 7zip file;
- Use both installer n 7zip versions with and without Admin mode;
- Install with antivirus on/off;

I'm really running out of options here =/

**Comment by WrinklyNinja** [comment]
Have you tried the snapshot build linked to at the bottom of #575?

**Comment by millhause** [comment]
Thanks WrinklyNinja! Its finally working. It have created the LOOT folder at appdata successfuly.
