### ISSUE TITLE
Failed to find my steam installed skyrim

### ISSUE THREAD

**Issue by ubronan** [loot/loot#646]
I saw this tool mentioned in the guide from Gopher.
So i was hoping this would resolve my issue with the game crashing on some mods near whiterun.
However the game is totally not detected at all.
Its the only game i have from the list so no clue if its a general problem or not.
But it totally does not find skyrim at all, even though i am playing it as i type this
The game is on steam and directing the program to the path where it is installed gave me the message incorrect game id and thats it

**Comment by WrinklyNinja** [comment]
Have you tried running the Skyrim launcher? If you have, please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by ubronan** [comment]
Duh now it did .... good grief.
Not sure why it worked after reboot and reinstall the game and indeed when i started the game launcher it popped up.
There must have been some damage to the files, going to see if i can get the mods working without crashing the game

**Comment by WrinklyNinja** [comment]
Glad you got it working, closing this.
