### ISSUE TITLE
Erro code 12

### ISSUE THREAD

**Issue by pocketsocket** [loot/loot#653]
Hi,
When trying to use Loot I run into this error:
Error code: 12; Failed to update the masterlist. Details: An error occurred while trying to clone the remote masterlist repository

I have added my debuglog, hoping you might be able to help me out?

Thanks! 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/493465/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
The error in your log is 

```
[17:33:08] [error]: Git operation failed. Error: -1; failed to send request: The operation timed out
```

Does this always happen? If so, the URL is `https://github.com/loot/skyrim.git`, can you access that in your web browser?

**Comment by pocketsocket** [comment]
It seems to be the same error every time. I am using Firefox and edge, and I can access the url no problem.

**Comment by WrinklyNinja** [comment]
Could you try [this snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.9.2-97-g4955639_dev#files)?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.

**Comment by pocketsocket** [comment]
Yes.
I apologise for not getting back to you, but life kind of came in the way.
Your responsiveness is greatly appreciated and I hope you keep up the good
work!

Best wishes,
Jonas
