### ISSUE TITLE
How to open Loot window?

### ISSUE THREAD

**Issue by jin8864** [loot/loot#654]
Hello.
I recently updated ModOrganizer from 1.2.18 to 1.3.11 and found Loot does not show the result window any longer. How do I get the Loot window? 
Thanks.

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported. Does LOOT open its window if you run it outside of MO?

**Comment by jin8864** [comment]
Oh, I see. I have not tried it yet. Then i would rather roll back. Thanks for reply.

**Comment by WrinklyNinja** [comment]
Unsupported means I don't provide support for it: it doesn't mean it doesn't work (I can run LOOT through MO myself with no issues).

**Comment by jin8864** [comment]
I just found that Loot does not work through MO. So, there must be something wrong in my system. I have rolled back to 1.2.18 and everything is fine. Will stay on 1.2.18. Anyway, thanks for great app!
