### ISSUE TITLE
Russian translation update from latest template.pot(061016)

### ISSUE THREAD

**Issue by TokcDK** [loot/loot#657]
Hi, WrinklyNinja.
Tryed several times to update loot.po using repositories from SVNTortoise but got Merged Failed. Tryed to send message to Google mail about it but no results.

Here is updated loot.po (updated from latest template from git):
[loot.zip](https://github.com/loot/loot/files/513061/loot.zip)

As I remember "First-Time Tips" window still has no strings for translation.

**Comment by Freso** [comment]
You shouldn't use SVNTortoise for submitting changes back to GitHub. GitHub provides SVN-access to its repositories, but AFAIK, those are "read only". If you want to submit changes back, you will have to use Git.
