### ISSUE TITLE
White screen when opening LOOT

### ISSUE THREAD

**Issue by TIG123** [loot/loot#661]
Was running loot fine until I installed a new anti-virus. After that loot would no longer start. After re-installing and giving exception in my anti-virus it will start but just presents with a white screen. Have tried adding the "--single-process" argument through mod organizer and still get this issue. Any help would be appreciated.
![loot](https://cloud.githubusercontent.com/assets/22738310/19227869/8ea04e22-8f02-11e6-9217-682c127c02dd.png)

**Comment by WrinklyNinja** [comment]
Does it work if you try launching LOOT not through MO?

**Comment by TIG123** [comment]
No, the exact same issue occurs

**Comment by WrinklyNinja** [comment]
Your antivirus may have quarantined something or is probably otherwise
still interfering then.

**Comment by TIG123** [comment]
I've checked my anti-virus and it hasn't removed anything LOOT related and I can't find a reason as to how else it would be interfering. Could it just be coincidental timing or do you have any other suggestions?

**Comment by WrinklyNinja** [comment]
I've never heard of LOOT white-screening on its own before, but MO and antivirus have both caused problems in the past. I'm not sure what else could be involved.

**Comment by TIG123** [comment]
I reinstalled it again and I think it's a problem with mod organizer, it managed to load fresh off the install before I tried opening it with mod organizer (none of my mods were listed though) and once I tried opening with MO the same thing is happening

**Comment by WrinklyNinja** [comment]
Try deleting your LOOT install and its `%LOCALAPPDATA%\LOOT` folder and reinstalling it.

**Comment by TIG123** [comment]
I got it to work, thank you so much for your help. I ended up having to do what you said and I had to launch it from MO first. If I tried launching it by itself and then through MO the issue would occur, thank you
