### ISSUE TITLE
About and First Time Tips dialogs cannot be fully translated

### ISSUE THREAD

**Issue by TokcDK** [loot/loot#664]
I see each time message "You have not sorted your load order this session." and cant find strings for it. 

Also cant be translated text in the window when LOOT was started in the firs time. This text:

> First-Time Tips
> This appears to be the first time you have run LOOT v0.9.2. Here are some tips to help you get started with the interface.
> 
> Click  buttons to open menus.
> As well as messages, LOOT displays plugin version numbers, CRCs and Bash Tag suggestions for addition and removal.
> CRCs are only displayed after plugins have been loaded, either by conflict filtering, or by sorting.
> Double-click a plugin in the sidebar to quickly open it in the metadata editor.
> Plugins can be drag and dropped from the sidebar into the metadata editor's "load after", "requirements" and "incompatibility" tables.
> Some features are disabled while the metadata editor is open, or while there is a sorted load order that has not been applied or discarded.
> Many interface elements have tooltips. If you don't know what something is, try hovering your mouse over it to find out. Otherwise, LOOT's documentation can be accessed through the main menu.
> LOOT is free, but if you want to show your appreciation with some money, donations may be made to WrinklyNinja (LOOT's creator and main developer) using PayPal or Bitcoin.

Also question about text in masterlist like this:

> - &patchOutSub
>   type: warn
>   content:
>   - lang: en
>     str: 'Contains unexpected (or out of order) records. A compatibility patch fixed and cleaned with TES5Edit can be obtained [here](http://www.nexusmods.com/skyrim/mods/26230).'
>   - lang: ru
>     str: 'Содержит неожиданные (или неисправные) записи. Исправленный и очищенный с помощью Tes5Edit патч можно попробовать найти [здесь](http://www.nexusmods.com/skyrim/mods/26230).'
>     - lang: es
>       str: 'Este archivo contiene entradas fuera de lugar. Un patch de compatibilidad puede ser encontrado [aquí](http://www.nexusmods.com/skyrim/mods/26230).'

Where can I find more info about this. This is like variables which can be inserted instead of some messages using in the masterlist many times. But not using?

**Comment by WrinklyNinja** [comment]
> I see each time message "You have not sorted your load order this session." and cant find strings for it.

I'll fix that.

> Also cant be translated text in the window when LOOT was started in the firs time. This text:

Yes, that's mostly untranslatable because the sentences contain HTML tags, and I'm not sure how to handle that.

> Where can I find more info about this. This is like variables which can be inserted instead of some messages using in the masterlist many times. But not using?

Apparently not. 😕

**Comment by TokcDK** [comment]
> Apparently not
Already found in the masterlist and understood how it using. Maybe need to replace some standard messages wich exist in this variables or maybe exist some problems with it and better do not need?

**Comment by WrinklyNinja** [comment]
It probably needs to replace some existing messages, yes.

**Comment by TokcDK** [comment]
About LOOT window also have no strings for localization.

**Comment by WrinklyNinja** [comment]
Yes, that's what the issue title says.
