### ISSUE TITLE
LOOT won't open.

### ISSUE THREAD

**Issue by Usernameasdasd** [loot/loot#668]
When I try to open LOOT, I get a "LOOT.exe has stopped woking" message. Tried older versions and got the same problem.

> Problem signature:
>   Problem Event Name: APPCRASH
>   Application Name:   LOOT.exe
>   Application Version:    0.9.2.0
>   Application Timestamp:  57a19bfa
>   Fault Module Name:  StackHash_e341
>   Fault Module Version:   0.0.0.0
>   Fault Module Timestamp: 00000000
>   Exception Code: 80000002
>   Exception Offset:   76d7d7d8
>   OS Version: 6.1.7601.2.1.0.256.1
>   Locale ID:  1046
>   Additional Information 1:   e341
>   Additional Information 2:   e34149193fa66d6548c8f331d771cc2c
>   Additional Information 3:   6841
>   Additional Information 4:   684179abd048bf5c6b317cbaffe6b41b
> 
> Read our privacy statement online:
>   http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
>   C:\Windows\system32\en-US\erofflps.txt

**Comment by Freso** [comment]
Please attach the LOOTDebugLog.txt and CEFDebugLog.txt as per https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html

**Comment by Usernameasdasd** [comment]
And how do I get those logs?

**Comment by WrinklyNinja** [comment]
Try the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.9.2-129-g49580f9_dev.7z), bearing in mind that it requires the [MSVC 2015 redistributable](http://download.microsoft.com/download/9/a/2/9a2a7e36-a8af-46c0-8a78-a5eb111eefe2/vc_redist.x86.exe).

**Comment by gerriet-hinrichs** [comment]
Had the same problem: LOOT did not start.
I changed the settings.yaml to enable debugging, but no debug files where generated.

Repairing my MSVC 2015 redistributable installation with the setup from your post fixed the problem for me.

**Comment by WrinklyNinja** [comment]
@Usernameasdasd Does this still happen with the v0.10.1 release?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
