### ISSUE TITLE
Masterlist syntax: `util` vs. `utility`

### ISSUE THREAD

**Issue by Freso** [loot/loot#670]
As part of our discussion for the new/updated masterlist syntax for v0.10.0, one of the things was for standardising the usage of some of the keys, like what used to be `util`. However, unlike what was originally proposed—introducing a new `util` key that would behave different from the already existing `util` key—the new `utility` essentially replaced both the old `util` and took the functionality of the new proposed `util` key.

I've been debating with myself which one looks "nicer", but in the end, I'm slightly in favour of renaming `utility` back to `util` - if nothing else, to make the two ever so slightly more compatible (which practically will pretty much just mean that diff'ing between the two will result in slightly smaller diffs).

It will require some more large-ish commits to the current v0.10 masterlist branches though, so I'm going to just leave this topic here for discussion. It should be resolved before the final v0.10.0 actually gets released though.

**Comment by WrinklyNinja** [comment]
> introducing a new util key that would behave different from the already existing util key

I can't remember, what was the different behaviour? Was this the split of `util` into `utility` and `info`?

I'm in favour of the status quo due to laziness, are smaller diffs a significant thing? I don't do much masterlist work so maybe I'm unaware of the issue.

**Comment by WrinklyNinja** [comment]
On further thought, keeping `util` would avoid any userlist breakage for users who have added dirty metadata, so that's a pro for changing it back.

**Comment by Freso** [comment]
The diff'ing is also most for keeping stuff back/forward ported between v0.8 and v0.10 branches. The smaller the diffs, the smaller the chance of porting going wrong. It should be fairly easy to do something like `sed -i 's/( *)utility:/\1util:/' ./*/masterlist.yaml` to mass-convert back to the old syntax. (Note that the `sed` command is untested, so it would likely be good to verify it before committing its results. ;) )

**Comment by WrinklyNinja** [comment]
So just to check, 6bb90c2b8acdfa19371fafbf86bc004321037dae makes the change you want, right?

**Comment by pStyl3** [comment]
Using "loot_0.9.2-139-gc27e55c_undo-syntax-change.7z" I can't properly update the masterlists for all games except FO4 and SSE.

Oblivion
> Masterlist revision 85f5c27: yaml-cpp: error at line 170, column 9: bad conversion: 'util' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.

Skyrim
> Masterlist revision 8973ecd: yaml-cpp: error at line 292, column 9: bad conversion: 'util' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.

Fallout 3
> Masterlist revision 3de4825: yaml-cpp: error at line 163, column 9: bad conversion: 'util' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.

Fallout New Vegas
> Masterlist revision b17c237: yaml-cpp: error at line 78, column 9: bad conversion: 'util' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.

**Comment by Freso** [comment]
The change hasn't been made to the masterlists yet (and probably won't be until the change has been merged to dev, or just prior to merging).

**Comment by WrinklyNinja** [comment]
OK, I'll merge this in and make the masterlist changes.
