### ISSUE TITLE
Is the latest 2 Fallout 4 official DLC support been added to alpha support in the next release?

### ISSUE THREAD

**Issue by milldogtjm** [loot/loot#671]
Sirs by any chance have the latest two dlc for the Fallout 4, been added to your alpha-support list for your next main version release for 0.10? Also on a side note when will alpha-support be added for the new Legendary edition of Skyrim, thou that may be another release after 0.10 is out.

Also can the games that Loot supports now work on a windows 8.1 x64bit, 16gb gddr5 (ram can be upgraded to 32GB), 8gb gddr4 Geforce GTX 1070 DirectX 11.2 256bit videocard? As I just got back into the PC gamming side of the community.
P.S. Can loot use the latest boss master list for Oblivion even thou that list doesn't have any metadata for those plugins?

**Comment by pStyl3** [comment]
The current official version 0.9.2 supports FO4 including all 6 official DLCs (as will the next version 0.10.0).

SSE support is scheduled for LOOT 0.10.0, so probably "soon".

Your PC specs seem more than alright and there shouldn't be a reason why the games (or LOOT) shouldn't work.

The current BOSS masterlist for Oblivion is most likely incompatible with LOOT 0.9.2 and LOOT 0.10.0, as the masterlist syntax was rewritten.

**Comment by WrinklyNinja** [comment]
What pStyl3 said, though I'll clarify that BOSS masterlists are definitely incompatible with LOOT.

**Comment by milldogtjm** [comment]
But if lists syntax was updated to what the current version will recognize, then can the latest boss masterlist work?

**Comment by WrinklyNinja** [comment]
> But if that masterlist's syntax was updated to what the current version of Loot will recognize, then could the latest boss masterlist work side by side with the metadata being the aid to the main program help to find the right order by the mods metadata and by its depentices that are in the boss lists as of now.

If the BOSS masterlist was rewritten to use LOOT syntax, it wouldn't work for BOSS any more. There's also no way to extract load order metadata from the BOSS masterlists, because it's implicit in the relative position of plugins, so there's too much noise to extract any meaningful data.

**Comment by milldogtjm** [comment]
So for now they won't work even if all we want from those lists is the dependencies for the mods we use so that the current metadata that loot is currently use will be supplemented with the dependencies for a whole mod plugin group.

**Comment by WrinklyNinja** [comment]
What?

**Comment by pStyl3** [comment]
@milldogtjm 
LOOT uses an alygorythm to sort your load order, and uses the different masterlists only as a "supplement" .. in contrary to BOSS, which sorts load order 100% by looking at the masterlist with no algorythm involved as it is the case with LOOT.

That means, that LOOT will sort your load order, even for Oblivion, out of the box mostly fine. There are people prefering BOSS over LOOT when it comes down to Oblivion, it's a matter of taste I would say. You have the options to either use BOSS or LOOT for Oblivion, but there isn't much to be done in regards to "BOSS <---> LOOT masterlist conversion".

**Comment by milldogtjm** [comment]
That clears that up, its just that its sad seeing that mhahn123's work at nexusmods will be for nothing cause BOSS doesn't get updated anymore by you guys, and the lists don't either; at least his lists get updated correctly more often than yours does.  My suggestion; may be you could get him to help you work on the new masterlists with his already sorted lists combined into yours; which in the long run would be better for you cause he can keep the lists better maintained as seen on the NexusMods since the ended support of BOSS.

**Comment by WrinklyNinja** [comment]
BOSS support hasn't ended, mhahn maintains its masterlists and deaths_soul is working on the application, so it's not "for nothing", and as I've said, it's impossible to practically combine the two masterlists any farther than has already been done.
