### ISSUE TITLE
LOOT won't start up.

### ISSUE THREAD

**Issue by MatLX** [loot/loot#672]
Hey people.

A few weeks back LOOT simply stopped working. It doesn't start up, even when I try to run it as admin.

After googling the issue, I found someone with a similar problem, and it was solved by deleting the LOOT folder from %localappdata%.

So, without giving it much thought, I deleted the folder, and it still wouldn't start up. Now I'm stuck, because I can't provide you guys with a debug log since I have no LOOT folder on %localappdata%.

A clean install doesn't solve the problem.

Any ideas?

Many thanks!

**Comment by pStyl3** [comment]
Just to clarify, you deleted your LOOT installation as well as the LOOT folder in C:\%localappdata%, installed LOOT 0.9.2 fresh, and it still doesn't work?

If that is the case, what is your operating system/mod manager/game you want to manage?

**Comment by MatLX** [comment]
I didn't actually delete the installation folder, I simple uninstalled it instead. Not sure if it makes a difference. The LOOT folder in C:\%localappdata% is definitely gone, though.

I'm running on Windows 10, using NMM and trying to manage TES: Skyrim (original one, not SE)

If it makes any difference, I used to run it on this same system and it just stopped starting up overnight. I really don't know what could have happened.

**Comment by WrinklyNinja** [comment]
It may be an antivirus thing, check that any you have isn't interfering somehow. If that's not it, try the [latest snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.9.2-135-g13b0841_dev).

**Comment by MatLX** [comment]
Yeah, that worked!

It wasn't my antivirus either, though.

I'll be sure to enable debug logging in case it happens again in the future.

Thank you very much!

**Comment by WrinklyNinja** [comment]
OK, closing this then.
