### ISSUE TITLE
Error code: -1; Invalid game ID supplied

### ISSUE THREAD

**Issue by Qwerty-Space** [loot/loot#675]
When I launched LOOT and got this error.  Reinstalling doesn't help either.

**Comment by Freso** [comment]
Can you please follow the steps outlined at https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html and upload the debug logs?

**Comment by sabre96** [comment]
same here

**Comment by pStyl3** [comment]
@sabre96 
Please do as Freso requested from @Qwerty-Space and upload the Debug logs if you have the same problem. Saying that you have the same problem but not providing any more details does unfortunately not help.

**Comment by Qwerty-Space** [comment]
I sort of fixed the problem.

I just applied the settings multiple times, exited LOOT, started it again, and repeat.  It eventually worked.

**Comment by Qwerty-Space** [comment]
@Freso I'm afraid I can't replicate the issue anymore, without reinstalling LOTO.

**Comment by sabre96** [comment]
I fixed it too by installing the latest snap

**Comment by ethanosullivan** [comment]
As stated in a previous issue (#578), the [comment](https://github.com/loot/loot/issues/578#issuecomment-220834565) made by @WrinklyNinja provides a possible solution that worked for me:

> The settings panel is displayed because LOOT can't detect any games. Try running the games' launchers to add their Registry entries, or you can put the paths to their folders in LOOT's settings panel.

**Comment by Qwerty-Space** [comment]
@ethanosullivan I think you misunderstand the problem...
I added the game correctly, but the error `Error code: -1; Invalid game ID supplied` occurs when I save it.

**Comment by ethanosullivan** [comment]
@Qwerty-Space Right, I had the same issue with a new install of Fallout 4 on my end with the same error; Despite adding the path to my game directory manually.

**Comment by WrinklyNinja** [comment]
Closing this as it seems nobody is still experiencing the issue.
