### ISSUE TITLE
Improve robustness of update checking

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#676]
Right now the masterlists' LOOT version check if the LOOT.exe version is less than some semantic version, but this version changes with each release and in fact changes between releases, so there are two issues:
1. There's a maintenance burden for changing the versions in the masterlists (now automated with lomad, so not a big deal)
2. People who download a snapshot build after a version number change but before a release don't get notified of the final release.

A better system would check the final release's commit SHA as well as checking the semantic version, so users also see the update message if the version matches but the SHA is different. Checking by SHA alone wouldn't work because more recent releases shouldn't cause the update message to display if an older masterlist version without an up-to-date version is used.

Going further, an alternative mechanism might use the GitHub API to get the SHA and tag name for the latest release, avoiding the masterlist altogether, but then that does introduce some dependency on GitHub specifically (which seems reasonable).

**Comment by WrinklyNinja** [comment]
@Freso: Any thoughts on this?

**Comment by Freso** [comment]
I like the GitHub API route myself, TBH. It has seemed silly to me for a while to depend on updating all the masterlists every time there's a release (even if it's automated). If/when GitHub eventually goes away, hopefully something else will take its place (and if nothing else, a simple, similar API could be implemented on the LOOT website).

One thing to keep in mind is that GitHub is prone to downtime from time to time, so it should handle not being able to talk to GitHub gracefully.

**Comment by WrinklyNinja** [comment]
Well, this is half done, but CEF is blocking XHR to other domains (ie. `api.github.com`), which means it doesn't work. Once I solve that I can get it to display a message in the UI, duplicating the current behaviour.

**Comment by WrinklyNinja** [comment]
Done and merged, turns out the issue was due to some overzealous font-request-blocking I'd added and totally forgotten about...
