### ISSUE TITLE
Completely broken after trying to run SSE

### ISSUE THREAD

**Issue by BekNos** [loot/loot#677]
Which doesn't even show in the list, btw... even after I made sure the newest one supported it.

I keep getting the Invalid game ID, even though I said "screw it," and did a complete uninstall. I did the right file path to how I KNOW how to do it, and even put LOOT on the same friggin' harddrive as my games.
I tell you, ever since SSE was released, LOOT and Nexus Mod Manager has broken repeatedly.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/561516/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/561517/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
> I tell you, ever since SSE was released, LOOT and Nexus Mod Manager has broken repeatedly.

And this surprises you how?

That LOOTDebugLog.txt is incomplete, it looks like it started logging after you enabled debug logging and exited the settings dialog, but I need a log from a fresh run.

**Comment by BekNos** [comment]
I don't know what you expect, I can't get it to do ANYTHING. That is the ONLY thing I can do. I boot it up, it tells me all the first time run, then when I put info in, it instantly gives me the error and then anything I click it crashes. So... There isn't anything I can do in the way to help with that.

**Comment by BekNos** [comment]
Sorry to do another post, but I want this to be shown, since this is all I can do to offer any more help:
![loot crashing](https://cloud.githubusercontent.com/assets/23166491/19855199/e2bc3f16-9f38-11e6-85f3-dc9d6ff7d04c.gif)
Also apologize the size, but it's the best quality I could get that makes stuff legible.

**Comment by WrinklyNinja** [comment]
Just launching LOOT should write to its LOOTDebugLog.txt, does it not do that? I need the debug log, I'm afraid showing what you see isn't very useful.

**Comment by BekNos** [comment]
That's just it... you told me the last one was incomplete. This one that I'm posting is from THAT run I got the gif of.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/561810/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Well, I'm not sure why LOOT isn't logging from when you initialise it, the function it starts logging from is only called when you click Apply in the settings dialog. Whatever the reason though, you're not using the right build of LOOT, because the right build would have the Special Edition listed with the other games in your debug log.

**Comment by BekNos** [comment]
*headdesks*
https://i.gyazo.com/f2bef107b5dfa40526fad1c7818f292f.png
Then WHY was that on their most current download? I'm getting the feeling you don't know what the hell is broken either.
Also, every time I run Loot? It doesn't stop. It just runs in the processes and in order for me to get you ANY of this info, I have had to go into the task manager each time and end the process.
Thus starting this ALL OVER AGAIN.

**Comment by Freso** [comment]
Who is this "they" that has what as their most recent download? LOOT 0.9.2 doesn't support Skyrim SE. LOOT 0.10.0 will be the first release with SSE support. You can find developments builds of 0.10.0 - just note that these are experimental builds and some things are likely to change from one build to the next.

**Comment by BekNos** [comment]
V0.9.2 is where the "Download" page took me, even states in the  and was the first one in the download that had SSE support in the bug fixes:
Changes Since v0.9.1
"Fixed the conflict filter not including the Unofficial Skyrim Legendary Edition Patch's plugin (and any other plugin that overrides a very large number of records) in results."
So either I have been mislead or I'm even more confused than I started out with.
As for "they", I mean the website that the Loot team runs? Is there not more than one? I don't know the team.
But thank you, Fresco, that wasn't ever stated that I saw.
Still, that doesn't help my situtation, why is it breaking on start up? Why can't I get a log? Why is it telling me my info is wrong?

**Comment by Freso** [comment]
> Fixed the conflict filter not including the Unofficial Skyrim Legendary Edition Patch's plugin (and any other plugin that overrides a very large number of records) in results.

Has little to nothing to do with SSE. This is about the "Official" Unofficial Patch that most Bethesda Gamebryo-based games have and it is for the "Legendary Edition" - the edition of Skyrim non-SE which includes all the DLCs - it is not related to SSE at all.

If you're using LOOT 0.9.2 (which *is* the latest stable release of LOOT), it doesn't support Skyrim SE yet, which is why it isn't working and why your info is wrong. Either use a recent 0.10.0 development build or wait for 0.10.0 to get released (based on [the milestone tracking](https://github.com/loot/loot/milestone/14), it isn't far off).

**Comment by BekNos** [comment]
Ah hah, thank you. I read that wrong then and it was staring me in the friggin' face all this time. 
Ok, so... I'll try that 10.0 release, and see if that solves my problem with it not reading stuff too. (maybe the install hiccupped or something.. though that is hard for me to believe since I've made sure to reinstall the installer thrice now, just in case.)

**Comment by WrinklyNinja** [comment]
There is no beta, only unstable snapshot builds that only testers should be using but everybody and their dog seems to be downloading. I'd advise patience and wait for the v0.10.0 release, which should only be a matter of days now.
