### ISSUE TITLE
Masterlist Error

### ISSUE THREAD

**Issue by Mikiniki** [loot/loot#678]
Using LOOT Version 0.10.0 (build 480f386)
Using it for Skyrim special edition.
Masterlist downloaded: 8973ecd
Masterlist dated: 2016-10-13
Error: Masterlist revision 356243e: yaml-cpp: error at line 292, column 9: bad conversion: 'utility' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.
This error has existed for 24 hours.
As I have just rebuild with Nexus Mod Manager 0.63.6 I don't get to use LOOT since it only reads the master files and no mods.
This just for your information.
Brgds Mike

**Comment by WrinklyNinja** [comment]
You're using an outdated snapshot build.
