### ISSUE TITLE
After Metata: Riftrun_HF_v_2_0.esp

### ISSUE THREAD

**Issue by Sharlikran** [loot/loot#679]
LOOT Version 0.9.2-139-gc27e55c_dev

Loot Masterlist: Skyrim SE v0.10

[Riftrun_HF_v_2_0.esp](http://www.nexusmods.com/skyrimspecialedition/mods/757/?) not loading after [Hideout_DLC_Main.esp](http://www.nexusmods.com/skyrimspecialedition/mods/742/?) despite the appropriate metadata to do so.

[LOOT Log File](http://pastebin.com/aEXVMtFs)

**Comment by WrinklyNinja** [comment]
The log file makes no mention of that metadata, and given it's always worked until now I suspect it's not a code issue. Check your syntax and that the metadata you expect is actually in the masterlist/userlist in LOOT's SkyrimSE folder.

**Comment by Sharlikran** [comment]
I added the metadata in https://github.com/loot/skyrimse/commit/ce2e1eadf6d0655d3f0eff0d516b3dc3888ac510 does it look right to you for the new v0.10 syntax?  I compared it to other v0.10 masterlists.

**Comment by Sharlikran** [comment]
It's in the masterlist.yaml file also under my users folder.

**Comment by WrinklyNinja** [comment]
Does LOOT have the latest masterlist, with the fixed syntax, or are you using the commit that you added the metadata in? If the former, can you see the metadata listed when you open the editor for `Riftrun_HF_v_2_0.esp`?

**Comment by Sharlikran** [comment]
No it is not showing that in the editor from within LOOT.  I'm gonna add it and poke around in the folder.  Do you want to me do or provide anything specific?

There wasn't a userlist.yaml until I cleared it so this is what it made.
```yaml
bash_tags:
  []
plugins:
  []
globals:
  []
```

**Comment by Sharlikran** [comment]
Okay nevermind.  I think it' just me.  There is no "plugins:" line in the masterlist.  Fiddlesticks.  It's not Travis' job to catch that, it's my job to do it right but the masterlist had the indentation it didn't catch and no 'plugins'.  If that's something you want to look at.

**Comment by WrinklyNinja** [comment]
OK, closing this and continuing in #681.
