### ISSUE TITLE
Loot crashes on start!

### ISSUE THREAD

**Issue by hitman47br** [loot/loot#683]
So I just recently got back to playing skyrimg and dicovered BOSS isnt the tool to sort mods anymore.
So as I first installed LOOT it imidiatly crashes when I try to start it.

Assinatura do problema:
  Nome do Evento de Problema:	APPCRASH
  Nome do Aplicativo:	LOOT.exe
  Versão do Aplicativo:	0.9.2.0
  Carimbo de Data/Hora do Aplicativo:	57a19bfa
  Nome do Módulo de Falhas:	ntdll.dll
  Versão do Módulo de Falhas:	6.1.7601.23539
  Carimbo de Data/Hora do Módulo de Falhas:	57c997df
  Código de Exceção:	c0000005
  Deslocamento de Exceção:	0004e6df
  Versão do sistema operacional:	6.1.7601.2.1.0.768.3
  Identificação da Localidade:	1046
  Informações Adicionais 1:	a877
  Informações Adicionais 2:	a87751724e225ffcdd7aaed29770c8da
  Informações Adicionais 3:	a436
  Informações Adicionais 4:	a436974db0058271cd8adc44b29b7079

Sorry that´s in portuguesse, but that´s basically it, and I have no clue what I can do to try to fix it.
Unistalled and Instaled it several times and it didnt work.

**Comment by WrinklyNinja** [comment]
It looks like this is a duplicate of #680, try the snapshot build linked to there.
