### ISSUE TITLE
Ability to know when FNIS-dependent mods have changed, been added, or removed.

### ISSUE THREAD

**Issue by Xevion** [loot/loot#688]
Sometimes I wake up and find this annoying crap when I start up my games.
![Stiffy Mode, Activate!](http://i.imgur.com/4AGNPj4.jpg)
It might be an obvious easy fix for some, but otherwise, a simple feature could be implemented to combat this kind of stuff before it happens, a maybe 5-20 minute timesaver.

Let us say this somehow WAS implemented, it might look somewhat like this in the end... 

1) Open up LOOT
2) A notification pops up, it reads "FNIS-Dependent mods have been (added, removed, changed).
3) You click on one of the buttons to (Ignore, Always Ignore, Open FNIS-Forgot-Your-Full-Name.exe)
3a) You click "Ignore". The rest of the session in LOOT is spent with no more notifications like this.
3b) You click "Always Ignore". Until you reset this in the settings menu or something of the sort, you will never, ever, see this notification again.
3c) You click "Open FNIS-Forgot-Your-Full-Name.exe", the .EXE opens and you can continue to generate all of your animation files and everything. 4) You close FNIS, and the process repeats next time the requirements for the notification to pop-up appear. Go back to 1.

> I'm not very smart with all of this load order and stuff, but I thought this might be a useful suggestion.
> Please don't hurt me.

**Comment by WrinklyNinja** [comment]
I don't see how this fits in with what LOOT does...

**Comment by Xevion** [comment]
Does LOOT have a strict requirement for it NOT to do anything more than what it is usually used for?
A function or something to be notified when a ESM, ESP etc. changes would be the simplified version.
When I mean change, I mean removed, added or something that would matter.

**Comment by WrinklyNinja** [comment]
No, but it's so unrelated to anything else LOOT does and is such a narrowly-focussed feature that I don't see it having a place in LOOT. It would be easier and more appropriate to create a new utility to do this checking than to extend LOOT to do it.
