### ISSUE TITLE
LOOT won't find FO4 / open from MO2

### ISSUE THREAD

**Issue by grndblitz** [loot/loot#689]
As the subject lines says, I run into an error when running LOOT from ModOrganizer 2 and LOOT itself doesn't seem to find FO4. It finds skyrim fine, and is installed outside of the program files. "MSVCP 120.dll is missing from your computer."

**Comment by Freso** [comment]
Does it work when not run via Mod Organizer?

**Comment by grndblitz** [comment]
It will run fine when ran outside of MO 2. LOOT runs fine from the mod organizer v.1.3.11 for Skyrim. My issue currently is LOOT v.10 or v.92 can't find Fallout 4. I installed in the same directory as Skyrim was (a folder outside of program files)

**Comment by grndblitz** [comment]
I went into LOOT settings and added in the install path manually for Fallout 4, LOOT can now find it. How ever it doesn't see the mods I installed in Mod Organizer version 2.0.7. I think at this point it would be best for me to delete mod organizer 2 and try nexus?

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported. If it works when you run it without MO involved, then it's not an issue with LOOT.
