### ISSUE TITLE
LOOT 0.10.0 incorrectly sorting plugins in SE

### ISSUE THREAD

**Issue by cfs3rd** [loot/loot#690]
LOOT is not correctly sorting my plugins. It is putting Open Cities as the first esp and ASLAL in the middle of the load order. SMIM is also very low which is unusual. I uninstalled v .9.2 and installed .10 using the installer.exe. After installing version .10 it would not recognize that SE was installed. I uninstalled again and used the .7z version. This one would recognize SE, but sorted my load order incorrectly, I believe.
Debug log: http://pastebin.com/T2gd1Kmt

Wrye Bash is the mod management tool I am using. Load order as sorted by LOOT;
 0  0 Skyrim.esm
 1  1 Update.esm
 2  2 Dawnguard.esm
 3  3 Hearthfires.esm
 4  4 Dragonborn.esm
 5  5 Unofficial Skyrim Special Edition Patch.esp
 6  6 UnlimitedBookshelves.esp
 7  7 ApachiiHairFemales.esm
 8  8 Lanterns Of Skyrim - All In One - Main.esm
 9  9 Realistic Lighting Overhaul - Major City Interiors.esp
10  a Open Cities Skyrim.esp
11  b Prometheus_No_snow_Under_the_roof.esp
12  c RealisticWaterTwo.esp
13  d Cutting Room Floor.esp
14  e Modern Brawl Bug Fix.esp
15  f When Vampires Attack.esp
16 10 dD - Realistic Ragdoll Force - Realistic.esp
17 11 Realistic Lighting Overhaul - Dawnguard Interiors.esp
18 12 Immersive Sounds - Compendium.esp
19 13 Realistic Lighting Overhaul - Weathers.esp
20 14 Realistic Lighting Overhaul - Dawnguard Weathers.esp
21 15 RLO - Major City Exteriors - No Guard Torches.esp
22 16 dD - Enhanced Blood Main.esp
23 17 SPTConsistentOlderPeopleSE.esp
24 18 ISC Enhanced Blood Patch.esp
25 19 FNIS.esp
26 1a LWPlayerHeadTracking.esp
27 1b Alternate Start - Live Another Life.esp
28 1c Realistic Lighting Overhaul - Major City Exteriors.esp
29 1d Point The Way.esp
30 1e Apocalypse - Magic of Skyrim.esp
31 1f Run For Your Lives.esp
32 20 Realistic Lighting Overhaul - Dungeons.esp
33 21 SMIM-SE-Merged-All.esp
34 22 SMIM-SE-FarmhouseFlickeringFix.esp
35 23 Immersive Patrols II.esp
36 24 SkyrimImprovedPuddles-DG-HF-DB.esp
37 25 LeftHandRings_1stPersonView.esp
38 26 LeftHandRings.esp
      Bashed Patch, 0.esp

Thanks for your time,
Charles

**Comment by WrinklyNinja** [comment]
In future, please file Skyrim SE sorting issues in the Skyrim SE masterlist's [issue tracker](https://github.com/loot/skyrimse/issues).

Arthmoor just submitted metadata for OCS and ASLAL, SMIM probably needs priority metadata added.

**Comment by WrinklyNinja** [comment]
I've added SMIM metadata, so this should now be resolved, can you confirm?

**Comment by cfs3rd** [comment]
Yes, the newest master list solved the issue, my load order looks like a LOOT sorted load now! For some reason my LOOT would not update the master list past the one released on 11/3. Tonight when I clicked update I got the most current master list.

Thanks!!
Charles
