### ISSUE TITLE
LOOT installer exe began pc restart BEFORE I accepted

### ISSUE THREAD

**Issue by heatblayze** [loot/loot#692]
I installed LOOT for the first time, while I waited I watched some YouTube vids. Suddenly my computer showed the "Restarting" screen which I quickly cancelled.
I switched to the LOOT setup and it was at the "To complete the setup please restart etc" screen with the "Yes, restart the computer now" option selected.

Obviously I was going to restart anyway, but I would have liked to do it in my own time.

Running Windows 8.1. LOOT version is v0.10.0

**Comment by WrinklyNinja** [comment]
Yeah, sorry about that, I didn't realise that the LOOT installer has to tell the MSVC redist installer **not** to reboot without asking when it runs. Microsoft: defaulting to data loss. 😠 

Anyway, this is fixed in d3f7cf0ae888bbafacead2d244a1c0b48c462ce6.
