### ISSUE TITLE
What have you done?!

### ISSUE THREAD

**Issue by Anonymous1993** [loot/loot#695]
Hello,

what the fuck have you done with Loot?!
It sorts the plugins completely wrong, my game looks shit now!

The list after update to 0.10:

00
Skyrim.esm
01
Update.esm
02
Dawnguard.esm
03
HearthFires.esm
04
Dragonborn.esm
05
Unofficial Skyrim Legendary Edition Patch.esp
06
ApachiiHair.esm
07
Purewaters.esp
08
EnhancedLightsandFX.esp
09
immersive roads.esp
0A
SDO Full-LOD - The Morthal Swamp Light.esp
0B
Northfires Photoreal Mountains.esp
0C
Moss - Legendary.esp
0D
Moss.esp
0E
Moss_DB.esp
0F
AOS.esp
10
dD - Enhanced Blood Main.esp
11
dD-Dragonborn-Dawnguard-EBT Patch.esp
12
AOS2_EBT Patch.esp
13
SDO Full-LOD - Waterfall Effects.esp
14
SMIM-Merged-All.esp
15
SFO - Dragonborn.esp
16
ELFXEnhancer.esp
17
Pureweather.esp
18
Pureweather_AOS2 Patch.esp
19
UFO - Ultimate Follower Overhaul.esp
1A
SDO Full-LOD - Whiterun Trundra Creeks.esp
1B
Skyrim Flora Overhaul.esp
1C
TemptressVixen.esp
1D
SDO Full-LOD - Giant Campfires.esp
1E
SkyUI.esp
1F
Chesko_WearableLantern.esp
20
dD - Realistic Ragdoll Force - Realistic.esp
21
Tembtra Thief Armor.esp
22
faster vanilla horses.esp

WTF??
Pls fix that!

regards

**Comment by pStyl3** [comment]
Please keep it civil.

Also, please explain exactly what in your opinion should have been sorted differently and why. Only because the newly sorted load order looks different doesn't mean automatically that it's "wrong" or in need of fixing.

**Comment by WrinklyNinja** [comment]
Closing and locking this issue because I won't accept that kind of behaviour towards me or any of LOOT's contributors. I've also blocked the user responsible from the LOOT organisation's pages here on GitHub, and on my personal account.

**Comment by pStyl3** [comment]
The user, "Nexusman93" has reposted his comment on SSE Nexus. This time I banned him from LOOT, in fact all my files.

**Comment by pStyl3** [comment]
Now I'm getting a PM with the same comment. This time he will get reported to Nexus moderators.
