### ISSUE TITLE
Dawnguard.esm had 6 ITM records, but LOOT didn't tell me

### ISSUE THREAD

**Issue by skwerlman** [loot/loot#696]
After intstalling today's SSE patch, I checked each esm to see if they needed to be cleaned. Dawnguard did, but LOOT did not warn me about it. (I ran LOOT before and after cleaning)

Dawnguard.esm's CRC: `1B95F26B`
After cleaning: `2C80927B`

**Comment by Sharlikran** [comment]
Differences in CRC and number of ITMs and UDRs are the result of changes in xEdit.

Indecently Wrinkly, how should users provide feedback for this kind of information.  In the Bethesda forums?

**Comment by WrinklyNinja** [comment]
> Indecently Wrinkly, how should users provide feedback for this kind of information. In the Bethesda forums?

Pull requests are best, followed by issues filed in the relevant masterlist issue tracker, followed by forum posts.
