### ISSUE TITLE
Request: Profile-Specific "Userlist"

### ISSUE THREAD

**Issue by airbreather** [loot/loot#700]
I'm writing from the perspective of Skyrim 2011, but I expect that this would apply to other games as well.

Use Case
--
I've got an application that sets up a user's entire modlist along with their Mod Organizer profiles from scratch.  At the end, it yields a batch file that can be used to run their modded Skyrim setup, as well as all the supporting tools that the user needs to manage future tweaks to their profiles, including LOOT.  I'm mainly focusing on STEP Core and STEP Extended right now.

The problem is that if a user wants to "go off the beaten path" once they're done with the automated setup, they're eventually going to want to run LOOT to sort their plugins, but the automated setup might require userlist rules that they don't have (or vice-versa, the user's own userlist rules might cause problems if incorrect).  I want to help out novice users by setting the STEP-mandated userlist rules automatically, but I don't want to overwrite a user's own `userlist.yaml` if they've got their own tweaks.  I also want to isolate the auto-setup profiles from any other manually managed profiles.

Workaround
--
It looks like I could get around this by writing a quick one-off application that uses the LOOT API directly, but that looks like an annoying amount of work for me, and I suspect that power users will very much prefer being able to run the full LOOT application to manage their own profile anyway.

Proposal
--
If LOOT accepted a command-line argument that allowed the user to specify a different `userlist.yaml` path that got used everywhere that `userlist.yaml` currently does, so that the user would get the normal LOOT interface and be able to add / edit / whatever their own rules are per-profile without affecting other profiles, that would be ideal.

edit: thought of a slightly different proposal

Proposal 2
--
Similar to the other proposal, but instead of accepting a different `userlist.yaml` file path, accepting a file path for the entire "LOOT" folder that currently goes into a user-specific AppData\Local folder and thus forces LOOT to change behavior simply based on what user is running it.

**Comment by WrinklyNinja** [comment]
This seems reasonable, but the trouble I see with it is that the user can change games in LOOT and be stuck with the same userlist. The "LOOT way" of handling profiles would probably be to define a new game in LOOT's settings, which would point to the same Skyrim install but get its own masterlist and userlist. You could then launch LOOT with the `--game=<game>` parameter to run it for that game.

The only difficulty I see with that is that there's no interface besides the UI for defining a new game, but you could just edit LOOT's settings.yaml to add it there, the format hasn't changed for many releases and I've got no plans to change it, so that should be relatively safe.

**Comment by airbreather** [comment]
A problem with that is that it has to be done once for each user, so unless I assume the MO profile is only used by a single user, it can't be "one-and-done" for the whole profile and it needs to instead be able to fix up at least `settings.yaml` for the current user on some runs and not on other runs, ideally keeping the user's own edits to that file (if any) untouched.

**Comment by WrinklyNinja** [comment]
Well, you were talking about "a user"... If you want multiple users to use the same LOOT profile, I think your second proposal (point to a different LOOT data folder) is the way to go. Your utility would then have a LOOT folder at some location accessible to multiple users, and point LOOT to it whenever it runs LOOT.

**Comment by airbreather** [comment]
> Well, you were talking about "a user"...
Yep.  I only realized the issue after considering your suggestion.

> Any suggestions for what the CLI parameter name should be?

Some thoughts, off the top of my head:

* `--profile-folder`
* `--loot-folder`
* `--override-loot-data`

**Comment by airbreather** [comment]
Grabbed the bleeding-edge version from [bintray](https://bintray.com/wrinklyninja/loot/LOOT/0.10.1-9-g769f3dd_configurable-loot-data-path).  It works for me.  Thanks!
