### ISSUE TITLE
Disables nukaworld dlc

### ISSUE THREAD

**Issue by Slategrey** [loot/loot#703]
every time I run loot 0.10.1 it disables nukaworld dlc

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Giving the actual filename of the disabled plugin would also help.

(This was also reported [here](https://forums.nexusmods.com/index.php?/topic/3527110-loot-load-order-optimisation/?p=44451595).)

**Comment by WrinklyNinja** [comment]
Others cannot replicate the issue: [pStyle](http://forums.bethsoft.com/topic/1611336-rel-loot-thread-26/?p=25264358) [Arthmoor](http://forums.bethsoft.com/topic/1611336-rel-loot-thread-26/?p=25264548).

**Comment by Aronir2004** [comment]
Unfortunately I have the same issue too. :(

**Comment by WrinklyNinja** [comment]
Do you both use NMM?

**Comment by Aronir2004** [comment]
Yes I'm using NMM. :)

**Comment by WrinklyNinja** [comment]
NMM seems to report it as disabled when it's not actually.

**Comment by WrinklyNinja** [comment]
Closing this as it seems to just be NMM reporting the wrong thing.
