### ISSUE TITLE
Disables Bethesda Master Files

### ISSUE THREAD

**Issue by decopauge123** [loot/loot#704]
Performed a clean uninstall of LOOT 0.10.0 from system before downloading and installing LOOT 0.10.1.  Ran LOOT from within Mod Organizer against TESV SE game installation that includes 14 user-applied mods.  LOOT messages stated that 3 Bethesda-supplied master files (Dawnguard.esm, Dragonborn.esm and Hearthfires.esm) had multiple ITM records and deleted references.

The reason I am posting this comment is that LOOT 0.10.1 deselected those three master files and placed them at the end of the load order.  Any time I re-ran LOOT 0.10.1 after enabling them and placing them at the top of the load order (where they belong), LOOT 0.10.1 would perform the same actions.  Performing a clean uninstall of LOOT 0.10.1 from my system, re-installing LOOT 0.10.0, and running LOOT 0.10.0 through Mod Organizer against my TESV SE game installation resulted in the 3 Bethesda master files being re-enabled and placed in the correct order at the top of my load order.

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported. In this case, Mod Organiser doesn't seem to know that it's impossible to deactivate the DLC plugins, they always load before everything apart from Skyrim.esm and Update.esm, so it's showing you nonsense.

**Comment by decopauge123** [comment]
Thank you for a quick, informative response.
