### ISSUE TITLE
0.10.1 Crashing upon initialization

### ISSUE THREAD

**Issue by JaneBuzJane** [loot/loot#706]
Hi, 

Just wanted to report a crash I'm getting. I'm using the 0.10.1 version of LOOT (trying to run FO4) and it's crashing upon initialization. This occurs whether I run it through Nexus Mod Manager (0.63.9) or through the .exe itself. 

I get different errors by running them different ways - if I don't run it through NMM, I get a "Memory Couldn't Be Written" error and crash (although that may be a hardware issue on my end). If I DO run it through NMM, I get a generic "LOOT.exe stopped working" error and crash. I ran the 0.10.0 version of LOOT - just for kicks - and it works fine with 63.9.

I started getting this crash after I updated the version of NMM from 63.8 to 63.9. Solutions I've tried: 

1. Fresh install of FO4 and NMM
2. Repaired the 2015 VC Redistributable
3. Verified game cache using Steam
4. Updated Windows/DirectX/Java/game
5. Turned off antivirus 
6. Installing LOOT (both manually and using installer) on my SSD where my Steam/game directory is located. 
7. Running in compatibility mode

I'm on Windows 7, if that helps at all, and always run programs as Admin. I would've attached the LOOTdebuglog.txt, but I don't have a settings.yaml file in my LOOT directory. 

And, of course, if this is a NMM issue - or a metadata issue - let me know and I'll send this to the correct place. 

[CEFDebugLog.txt](https://github.com/loot/loot/files/601835/CEFDebugLog.txt)

**Comment by pStyl3** [comment]
Make a backup of your C:\%LOCALAPPDATA%\LOOT folder and then delete that folder. Does the error still occur?

If no, then please recreate said folder through your backup, go into the LOOT folder and create a new textfile "newtextfile.txt". Rename that textfile to "settings.yaml" (yes, the extension must be changed to .yaml). Open that file and write

>language: en
updateMasterlist: false
enableDebugLogging: true
game: auto

Save and close. Now try to open LOOT. It should now have created both log files, so that cou could upload your LOOTDebugLog.txt.

**Comment by WrinklyNinja** [comment]
Strictly speaking, you only need to have `enableDebugLogging: true` in your settings.yaml, since defaults are assumed for missing settings.

**Comment by Kalorean** [comment]
I have the exact same error as JaneBuzz. 
Clean installation of NMM, Fallout IV as well as several tries of Loot.
[CEFDebugLog.txt](https://github.com/loot/loot/files/601983/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/601984/LOOTDebugLog.txt)

**Comment by JaneBuzJane** [comment]
For some reason, creating settings.yaml, entering/saving the text, and trying to run LOOT won't generate a debug log. I do have a [crash dump file,](https://www.dropbox.com/s/sgtsh5yrcbpialo/LOOT.exe.680.dmp?dl=0) if that will be helpful? I'll try Kalorean's fix and see if it works for me as well.

**Comment by Kalorean** [comment]
In case you are digging through your reg-file:

 x64 location - [HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Bethesda Softworks\Fallout4]
 x32 location - [HKEY_LOCAL_MACHINE\SOFTWARE\Bethesda Softworks\Fallout4]

Kalorean

**Comment by WrinklyNinja** [comment]
Does the crash reported in #708 look like the crashing either of you are experiencing? It looks a little different to me, but then I'm not experiencing any crashing...

**Comment by JaneBuzJane** [comment]
Ahh, yep, that looks like the same one! I tried Kalorean's fix but my registry seems to be in order (just in case you wanted an update re: registry paths).

**Comment by WrinklyNinja** [comment]
In that case I'll close this if favour of that issue, since it looks more familiar to me. I just had a look at your crash dump file, first time reading one of those, but I couldn't spot anything I'd find useful.
