### ISSUE TITLE
LOOT Application Error / Crash on opening

### ISSUE THREAD

**Issue by Ashton187** [loot/loot#708]
Hey all,

First off, thank you very much for the program. I personally and i'm sure many others really appreciate the work you all do.

My issue is i am completely unable to run LOOT. Soon as i load it, it'll crash.

I'm using version 10.1

This is the error box i'm getting:

![error](https://cloud.githubusercontent.com/assets/23705970/20573741/3719f6f2-b1a9-11e6-9e1c-ca15d8d5bcb9.png)

Here is my DebugLog

[CEFDebugLog.txt](https://github.com/loot/loot/files/609672/CEFDebugLog.txt)

Here is my LOOTDebugLog

[LOOTDebugLog.txt](https://github.com/loot/loot/files/609679/LOOTDebugLog.txt)

Things i have tried:

Reinstalling Fallout 4
Reinstalling LOOT + Deleting the Local LOOT folder
Checking Registry Install Directory is correct

Thanks everyone.

**Comment by WrinklyNinja** [comment]
What's in your Fallout 4 plugins.txt? I had a crash that looks similar from that error message and the logs during development, but I thought I'd fixed it...

**Comment by Ashton187** [comment]
Hi WrinklyNinja,

In my Fallout 4 Local folder i just have 

[DLCList.txt](https://github.com/loot/loot/files/609690/DLCList.txt)

I'm starting my modding with a blank slate, so i only have F4 + DLC's installed.

I have reverted back to version 10 and LOOT is loading and working absolutely fine.

**Comment by WrinklyNinja** [comment]
OK, I'll try to replicate the issue.

**Comment by WrinklyNinja** [comment]
Right, I can replicate it if the following plugins exist and no `plugins.txt` exists:

```
Fallout4.esm
DLCCoast.esm
DLCNukaWorld.esm
DLCRobot.esm
```

Now to fix it...

**Comment by Ashton187** [comment]
I'm glad you can replicate it.

**Comment by WrinklyNinja** [comment]
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-14-gcccad12_fix-startup-crash.7z).

**Comment by Ashton187** [comment]
This is what i get now. Not sure if this is what you want to see.

![loot](https://cloud.githubusercontent.com/assets/23705970/20590295/30758444-b21a-11e6-8d29-fcd52858d7fd.png)

**Comment by WrinklyNinja** [comment]
What's in your logs?

**Comment by Ashton187** [comment]
So my %appdata% Local logs are the same as the one i linked above. 

The version you provided, i extracted here: C:\Users\Myname\Downloads\loot_0.10.1-14-gcccad12_fix-startup-crash

Inside that folder there seems to be no logs at all that i can see/recognise.

**Comment by WrinklyNinja** [comment]
Please try again with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-20-g4a426f1_fix-startup-crash.7z). I'm aware there are a few styling issues with underlines, just ignore them.

**Comment by Ashton187** [comment]
Works. Thanks a lot :)
