### ISSUE TITLE
Loot crashes on v0.10.0 or later

### ISSUE THREAD

**Issue by Connage** [loot/loot#711]
When loot opens, the First Time Tips pop up, as does the Settings tab, but after I close the Settings tab LOOT.exe stops working. I tried v0.9.2 and I do not encounter the same error, however it crashes on both v0.10.0 and 0.10.1. I am using LOOT for SkyrimSE so using v0.9.2 won't really work.

**Comment by WrinklyNinja** [comment]
Could I get the [debug logs](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by Connage** [comment]
Sure thing: 
[CEFDebugLog.txt](https://github.com/loot/loot/files/614934/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/614935/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
I think this may have already been fixed, but none of the snapshot builds are currently available for download, so I'll post a link once access to them has been restored.

**Comment by Connage** [comment]
Okay great, thank you very much sir!

**Comment by WrinklyNinja** [comment]
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-29-gfba0aa5_dev.7z).

**Comment by WrinklyNinja** [comment]
Please try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-33-g2673c21_dev.7z).

**Comment by Connage** [comment]
The same issue occurs when I open this build of loot.

**Comment by Connage** [comment]
I hope you do not stress over this issue though! I am still able to play SKSE with my mods as they were sorted by Loot before I started encountering this issue! So no worries!

**Comment by belak** [comment]
I'm running into the same problem... anything I can do to help debug this?

**Comment by WrinklyNinja** [comment]
Did you try the build I linked to above?

**Comment by belak** [comment]
Yes. It also didn't work as a standalone... for whatever reason the installer seemed to work fine, but the standalone builds didn't.

**Comment by WrinklyNinja** [comment]
Try installing [this MSVC redist](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe) and see if that works.

**Comment by Raferty-FL** [comment]
I also have this issue and have reload the loot app and the MSVC, still crashes after I select Skyrim SE

**Comment by Zerhackfetzer** [comment]
I have the same problem with mod organizer, but it works fine without it. Any ideas what i could do ?

**Comment by WrinklyNinja** [comment]
@Connage @belak @Raferty-FL Are you still getting crashes when trying to use LOOT for Skyrim SE?

**Comment by Lochstock** [comment]
I'm having the same issue. I'm using v.0.10.2 via the installer and right after I hit Apply on the Setup page it crashes.  I've installed LOOT in both my mods folder and Program (x86), doesn't seem to make a difference.

**Comment by WrinklyNinja** [comment]
I think I may have fixed this crash recently, can you try with [this snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.2-42-g82bf9dd_dev_Win32.7z)?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
