### ISSUE TITLE
LOOT download problems

### ISSUE THREAD

**Issue by CasediaOBJ** [loot/loot#718]
Hello,

I recently purchased Skyrim and I am beginning to mod the game. I have found and downloaded mods that I want and now I need to fix my load order. From what I hear, LOOT is where its at. But I get errors when trying to download it from this site and on the nexus on chrome, edge and explorer. It could be a problem with my internet but I was able to download multiple things without problems the day before. I get a 0 B/s download speed on google, edge and explorer download to about 9% and stop, and when I pause and resume the downloads I get messages along the lines of  "failed" or "unable to download" "failed - Forbidden". When my downloads work for the first 4% or so I get about 23-30 Kb/s then around 5-7% I get 3-5 Kb/s than it gets to 9% and gets stuck on 0 Kb/s. I am attempting to download LOOT.Installer.exe so if i'm doing something wrong i'm pretty stupid. I also can't run Skyrim but this is because the mods are not in the correct load order.

Thanks

**Comment by CasediaOBJ** [comment]
I just spent 10 minutes typing this and I may have just solved it

**Comment by CasediaOBJ** [comment]
Still doesn't work

**Comment by WrinklyNinja** [comment]
It's something wrong on your end, nothing I can do about it.
