### ISSUE TITLE
LOOT Won't open

### ISSUE THREAD

**Issue by Faiilnix** [loot/loot#719]
Hey Guys, i have a problem, when i want to open Loot, there's an error, i searched it on Google. The only thing i had to do is to install Microsoft C++ x64 But i have it already, so i don't know what to do else.
Please help.
![error loot](https://cloud.githubusercontent.com/assets/24367363/20865063/d208487e-ba07-11e6-8776-6a33d9322829.png)

**Comment by WrinklyNinja** [comment]
You need the x86 redistributable, not the x64. This is clearly stated on
LOOT's download page.

**Comment by Faiilnix** [comment]
I got it too, i just said that on Google, they said to install the x64.

**Comment by WrinklyNinja** [comment]
Which version of the redistributable do you have installed (check in Programs and Features)?

**Comment by Faiilnix** [comment]
Where do i see it ? I don't know where it is installed

**Comment by WrinklyNinja** [comment]
Try installing [this version](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe) and see if that works.

**Comment by Faiilnix** [comment]
Thanks !! You're the best ! 
![loot](https://cloud.githubusercontent.com/assets/24367363/20866004/c18f5acc-ba21-11e6-81dd-680189b6d829.png)
Now i have to learn how to use it haha
