### ISSUE TITLE
Installer won't even launch after attempting reinstall for LOOT not launching

### ISSUE THREAD

**Issue by DocJRoberts** [loot/loot#720]
I'd been using LOOT for Oblivion prior to Skyrim SE's launch and had no issues. After getting the update that added Skyrim SE's compatibility, I decided to try modding SSE. After doing so, almost every time I'd run LOOT, the program window would launch but just be a blank white screen. The only thing that worked was to uninstall the program and reinstall it. This worked every time to get me back to using LOOT. But almost any time I'd add a new mod and need to reorder my load, I'd have to reinstall LOOT to get it to launch.

Now after this latest time of uninstalling LOOT, I can't get the installer to launch? When I double click the exe I see the process load in task manager->details but nothing opens on screen and nothing happens at all. It stays in details until I end it. I've tried with 10.1, and now the latest 10.2. I've wiped out the install directory. I'm wondering if there's something I need to do to do a true clean from the system before reinstalling? Some registry keys that may be causing problems? I can still use NMM to manually sort the load order and launch the game but I don't trust myself as much as I trust LOOT.

I can post anything needed of course. Any help is appreciated! And if this isn't the place for this and is more of a forum post, please direct me. 

QUICK EDIT: Things I've tried
-running in various compatibility modes as well as admin mode. 
-deleting the files (that I know of) entirely and redownloading the installer.exe
-waiting for a version update and trying that installer.exe
-tested various other installers in my downloads folder including TeamSpeak 3, LibreOffice, and a boot USB maker, all of which worked fine. 
-reinstalled vc_redist.x86.exe

Final Edit(?)-
Using the build posted by WrinklyNinja in "Loot crashes on v0.10.0 or later" 

https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.1-33-g2673c21_dev.7z

seems to work fine just because it's bypassing the need to install anything which is subverting the greater issue of the installer not running. This may be an issue outside of LOOT though. Figured I'd update in case anyone else did come looking. Mods of course feel free to delete and do your work XD

**Comment by WrinklyNinja** [comment]
Do you have a Registry key at `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\LOOT` (remove the `WOW64Node` if you're on a 32-bit OS)? If so, what is its `Installed Path` value?

**Comment by DocJRoberts** [comment]
I do not have a reg key there. 

And even the dev downloaded file is locking up on launch immediately now, just like the installed version was doing.

**Comment by WrinklyNinja** [comment]
Please [provide your debug logs](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by DocJRoberts** [comment]
I couldn't get the program to successfully launch so I followed the method described for that instance. And I used loot_0.10.2-0-g9eb7d26_dev\LOOT.exe, not an installed application version.


[LOOTDebugLog.txt](https://github.com/loot/loot/files/629871/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Do you have LOOT set to use a non-English language?

**Comment by DocJRoberts** [comment]
I have LOOT entirely uninstalled and cannot get the installer to reinstall it. I'm using the build posted. I don't recall it asking for a language? I wouldn't have chosen anything but English though

**Comment by DocJRoberts** [comment]
My settings.yaml shows language: en

**Comment by DocJRoberts** [comment]
I really don't know how it's potentially connected...

But I clean reinstalled my graphics drivers tonight for an unrelated issue and now the installer AND the program are working fine...

**Comment by WrinklyNinja** [comment]
Sounds like there's just something wrong with your system then, closing this.
