### ISSUE TITLE
LOOT doesn't detect Skyrim

### ISSUE THREAD

**Issue by GrantGust** [loot/loot#721]
So I just installed LOOT and tried running it. First im greeted by a text bubble with some first time tips. After that the settings appear alongside the compatible games. I guess that it searches the computer for those games, although it didn't find Skyrim for me. It's set for autodetect and i've tried changing it to search only for Skyrim. Nothing has come up yet and when I press apply the program stops working and forces me to shut it down. Am I missing something?

**Comment by WrinklyNinja** [comment]
Run the Skyrim launcher.
