### ISSUE TITLE
Can't launch loot

### ISSUE THREAD

**Issue by Bassknight** [loot/loot#726]
When I try to launch it a window pops up saying: program couldn't start beacause api-ms-win-crt-runtime-[1-1-0.dll is missing and redownloading might fix it, but I already redownloaded it twice

**Comment by WrinklyNinja** [comment]
Try installing [this MSVC redist](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe) and see if that works.

**Comment by Bassknight** [comment]
It won't let me download the file you sent me

**Comment by WrinklyNinja** [comment]
What is "it"? The link is perfectly valid though, the problem is on your end.

**Comment by Bassknight** [comment]
Yeah it was a problem on my end, but it's okay now thanks for your help
