### ISSUE TITLE
When Loot loads from Mod Organizer, I only get a white screen.

### ISSUE THREAD

**Issue by BlacksburgNick** [loot/loot#727]
Hi Everyone,

I reinstalled Skyrim, MO, and Loot today and tried to run Loot.  Doing so gave me the dreaded white screen.  I read about it in a topic on this site that was declared fixed and closed out.  It can be found here: https://github.com/loot/loot/issues/482

After I installed Loot, i ran it directly from its folder and it worked.  I then tried to Launch it through Mod Organizer.  Doing that brought up the white screen.  After that, I went back to the Loot folder and tried to run Loot directly, but now I get only the white screen running it directly.  It is as if MO somehow _breaks_ Loot now.  

My Skyrim, Loot, and MO folders are in the following locations in Windows 10:
C:\Program Files (x86)\Steam\steamapps\common\Skyrim
C:\Program Files (x86)\LOOT
C:\Program Files (x86)\Mod Organizer

I found CEFDebugLog, which contained the following:
[1209/191742:WARNING:resource_bundle.cc(329)] locale_file_path.empty() for locale 
[1209/191742:ERROR:main_delegate.cc(710)] Could not load locale pak for en-US
{{The following line is repeated 44 times}}
[1209/191742:WARNING:resource_bundle.cc(529)] locale resources are not loaded
[1209/191742:ERROR:proxy_service_factory.cc(127)] Cannot use V8 Proxy resolver in single process mode.
[1209/191742:WARNING:histograms.cc(40)] Started multiple compositor clients (Browser, Renderer) in one process. Some metrics will be disabled.

Any ideas as to how I can remedy this?

Thanks!
Nick

**Comment by BlacksburgNick** [comment]
Well, I seem to have fixed it.  On a whim, i tried running loot as administrator.  Despite not working last time i tried it, it worked this time.  It posted the following message:
_An error occurred while parsing the masterlist: yaml-cpp: error at line 201, column 13: bad conversion: 'text' key missing from 'message content' object. This probably happened because an update to LOOT changed its metadata syntax support. Try updating your masterlist to resolve the error._

I sorted the load order and the message went away.  I then used TES5edit to clean up the files, and tried loading it from MO.  It didn't work.  I tried sorting it from within loot and this time, THAT worked.  As soon as that worked, I tried running loot again from inside MO and this time, Loot DID load.  I got the same message as above, so I sorted the files and it went away.  Now Loot loads and that message no longer appears.

Victory?  Sure.  Why did it work?  Beats me.

**Comment by WrinklyNinja** [comment]
In any case, running LOOT through Mod Organiser is unsupported.

**Comment by isochronous** [comment]
Well, considering the thousands of MO users out there, maybe you could add support?

**Comment by Freso** [comment]
If LOOT works outside of MO but doesn't work when run from MO, that means that there's a bug in MO. @WrinklyNinja barely has enough time to work on LOOT as it is and AFAIK has never touched Mod Organizer's code base, so it would be a huge undertaking to fix MO's code to make LOOT work under it.

So no, we will not support LOOT-via-MO. You *should* file bug reports with MO though.

**Comment by WrinklyNinja** [comment]
> Well, considering the thousands of MO users out there, maybe you could add support?

We're talking support as an activity, not a state. The idea of adding support (the state) for MO to LOOT is meaningless, there's nothing to do, it's the wrong way around. I'm also not providing support (the activity) for MO for the reasons Freso gave.
