### ISSUE TITLE
Build 64-bit API DLL on AppVeyor

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#728]
At the request of @DuskDweller for NMM, which needs a x64 DLL as well as the x86 DLL.

AppVeyor has a `platform` configuration key, and CMake uses different generators for x86 and x64 with MSVC, so it is possible to build both DLLs on the x64 platform on separate paths and supply a custom build script, but it's simpler to use both platforms and use the appropriate generator for each.

- [x] Configure AppVeyor to run for x86 and x64 platforms, use the correct CMake generator for each, and to fail on the first failing platform.
- [x] Update the Boost install script to build x86 and x64 libraries.
- [x] Configure the AppVeyor build so that only the steps necessary for building the x64 API get run on the x64 platform.
- [x] Update the archive script to include the platform in the filename to avoid conflicts. The helpers module already includes path-based labelling, this should probably be modified to use some other detection mechanism as the separate paths aren't currently used.
- [x] Publish x64 API archives to Bintray and GitHub Releases.

**Comment by WrinklyNinja** [comment]
@TanninOne, @DuskDweller can you give the DLL in [this build archive](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot-api_0.10.2-21-g4756e5f_build-x64-api_x64.7z) a go and let me know if it's a working x64 build or not?

**Comment by TanninOne** [comment]
That link lead to a 404. I tried https://bintray.com/wrinklyninja/loot/download_file?file_path=loot-api_0.10.2-11-g5c7fc7b_build-x64-api_x64.7z instead and that one seems to work fine.
Thank you mate!

**Comment by WrinklyNinja** [comment]
Hmm, looks like the old version cleanup is being overzealous... Well, at least the build works.

**Comment by WrinklyNinja** [comment]
Done in 5c7fc7b1dcb60d02de3b69226c9ed335684f185b.

**Comment by DuskDweller** [comment]
Thanks for taking the time to sort this buddy :)
