### ISSUE TITLE
erro ao iniciar loot

### ISSUE THREAD

**Issue by Aluizx6** [loot/loot#730]
![image](https://cloud.githubusercontent.com/assets/24538117/21128225/38568d5a-c0e0-11e6-82be-74921513e01e.png)

eu já tenho a dll mas n sei o pq n que rodar o programa

![sem titulo](https://cloud.githubusercontent.com/assets/24538117/21128317/03230798-c0e1-11e6-9351-2eeaa6a161ce.png)

**Comment by WrinklyNinja** [comment]
You need to install the MSVC redistributable [](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe)
