### ISSUE TITLE
LOOT is installed but does not run

### ISSUE THREAD

**Issue by zarebalt** [loot/loot#731]
Hello,
I have made several attempts at different installs for the LOOT application and I am encountering an error:
When I attempt to run LOOT the file kicks me back an error saying it cannot start because api-ms-win-crt-runtime-|1-1-0.dll is missing from my computer.
I'm not sure what I may be missing to run the application.

**Comment by WrinklyNinja** [comment]
You need to install the [MSVC redistributable](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe)
