### ISSUE TITLE
cannot start up?

### ISSUE THREAD

**Issue by JustHereForMyLoadOrder** [loot/loot#736]
I used to use loot, and it worked perfectly. however, sense i got my new computer and attempted starting up, it gives me a system error, saying "The program can't start because api-ms-win-crt-runtime-1l-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem"
When i reinstall, it doesnt fix. any suggestions?

**Comment by WrinklyNinja** [comment]
Have you installed the MSVC redistributable that's linked to on the download page?

**Comment by KodaMoore** [comment]
I have the same problem  and I have also downloaded MSVC redistributable but the problem still persists. Any helpful suggestions?

**Comment by WrinklyNinja** [comment]
> I have the same problem and I have also downloaded MSVC redistributable but the problem still persists. Any helpful suggestions?

Did you install the x86 redistributable?

**Comment by KodaMoore** [comment]
I have downloaded the x86 redistributable and I have tried downloading LOOT both manually and with the installer and the program just doesn't want to work.

**Comment by WrinklyNinja** [comment]
`api-ms-win-crt-runtime-1l-1-0.dll` is a file installed by the MSVC redistributable, if it can't be found then it hasn't been installed correctly, and there's nothing I can do about that, because it's not my code.
