### ISSUE TITLE
LOOT creating empty system-level files when run through MO2.

### ISSUE THREAD

**Issue by CapnWhales** [loot/loot#737]
I know Mod Organizer 2 isn't officially supported, but I figured this can be a system-breaking issue so it may be worth taking a look at.

When running LOOT through MO2 on Windows 8.1, LOOT creates an empty folder at "C:\Program"; this empty folder can break any program or system utility that looks for "C:\Program~" or other similar inspecific/lazy/legacy queries that would be instead searching for the Program Files directory. In worst-case scenarios, this can cause OS hangs and system instability.

This started when I updated to version 10.2.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/673322/LOOTDebugLog.txt)

**Comment by Freso** [comment]
Does this folder get created when not running through MO2?

**Comment by WrinklyNinja** [comment]
LOOT doesn't write any directories outside the user's application data folder, so it's not creating the `C:\Program` directory.
