### ISSUE TITLE
Fix for Loot crashing

### ISSUE THREAD

**Issue by mellowfire** [loot/loot#738]
I updated Loot to the latest version and it was crashing because I didn't have MS Visuals 2015 x86 installed. Even though I have a 64 bit version of windows. Visuals wouldn't install because my .Net framework was out of date. .Net framework can be updated through windows update. But for me windows update was stuck in a "checking for updates" loop. I let it run for several days because I hadn't updated in 10 months and it was still stuck. I found a web site 
https://www.howisolve.com/checking-for-updates-stuck-solved-windows-7-sp-1-8-1-10/

that directed me to an offline windows update tool, because I was having issues with my update client.The tool is at
http://download.wsusoffline.net/

I let it install overnight and in the morning I can run Loot. The offline update tool also installed MS Visuals and updated all the other versions of it I had installed.

**Comment by WrinklyNinja** [comment]
So what's the issue?

**Comment by mellowfire** [comment]
For me there is no issue. I just thought I would post what I did to fix my computer in case someone else had a similar problem. If there was some kind of discussion thread I would have posted this there, but all I could find was an issues thread.
