### ISSUE TITLE
LOOT could not detect any installed games

### ISSUE THREAD

**Issue by iCodeLogix** [loot/loot#741]
Good morning.

I have been trying to run the latest release of LOOT ([0.10.2](https://github.com/loot/loot/releases/tag/0.10.2)) on my computer but LOOT fails to detect TES V: Skyrim and LOOT will not recognize TES V: Skyrim if I manually input the path. The odd thing is that LOOT doesn't crash when I start up the app but LOOT will crash if I attempt to do anything with the UI.
![loot_exe_has_stopped_working](https://cloud.githubusercontent.com/assets/20905159/21678882/f0e12dcc-d30e-11e6-9d1b-14e92d9a5e3d.PNG)

Here are the paths I manually tried inputting for TES V: Skyrim:
* C:\Program Files (x86)\Steam\steamapps\common\Skyrim
* C:/Program Files (x86)/Steam/steamapps/common/Skyrim
* C:\Program Files (x86)\Steam\steamapps\common\Skyrim\Data
* C:/Program Files (x86)/Steam/steamapps/common/Skyrim/Data

Before anyone asks I have installed both MSVC 2015 x86 redistributable and 7-Zip. To ensure UAC was not causing problems I tried running LOOT as administrator before uninstalling and re-installing LOOT to the root of the C:\ drive. However the problem persists.
![installed_msvc_redist](https://cloud.githubusercontent.com/assets/20905159/21679168/88050bd2-d310-11e6-8785-2c135f831b31.PNG)

I don't know if this helps but I ran an earlier version of LOOT. I believe it was release 0.9.2. It worked like a charm. I went back to that version and installed it to see if it would work after uninstalling release 0.10.2 and deleting **%LOCALAPPDATA%\LOOT** but LOOT 0.9.2 does not work anymore unfortunately. It fails to work in the same way release 0.10.2 does. I see the same issue across the board:
`[0105/055359:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak`

P.S. I'm using Windows 10 and here are my debug logs from **%LOCALAPPDATA%\LOOT**.
[CEFDebugLog.txt](https://github.com/loot/loot/files/687094/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/687095/LOOTDebugLog.txt)

I'm open to all suggestions and helping you in debugging this issue in anyway possible.
Thank you very much for your time and effort.

**Comment by iCodeLogix** [comment]
Searching around in my registry with regedit.exe I was not able to find the Install Path Registry Key:
`Software\Bethesda Softworks\Skyrim\Installed Path`

Could this be a problem?

**Comment by iCodeLogix** [comment]
Hi @WrinklyNinja.

I didn't think it was an issue with the redist because if it is required than LOOT shouldn't launch at all given if there are aqueduct checks for all required dependencies when the app is first launched. I don't really know much about C++ but I was trying to study the codebase to see if I could find the what the issue was regarding the line in CEFDebugLog.txt:
`[0105/055359:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak`

Unfortunately I wasn't able to find any code regarding that line.

When I do things on UI like "Refresh Content", "Sort", and/or "Update the Masterlist" LOOT will crash (just like in the screenshot above) which makes sense to me because like you said LOOT doesn't know how to perform any actions on a game which hasn't yet been defined.

Once I get home today I will try running the Skyrim launcher and check to see if that adds the registry key. The strange thing is, I have launched Skyrim multiple times with from the launcher. My INI files are in their respective directories.

Thanks! I'll keep you posted.

**Comment by iCodeLogix** [comment]
Hi @WrinklyNinja.

I completely uninstalled LOOT 0.10.2 from my computer, deleting the %LOCALAPPDATA%\LOOT directory, ran CCleaner, ran Skyrim launcher as per request, reinstalled LOOT 0.10.2 and it works like a charm now! Thank you so very much!

![loot_works](https://cloud.githubusercontent.com/assets/20905159/21699894/ad895e66-d36b-11e6-959f-f42d2e0bbc14.PNG)

I also like the enhancement request you opened. It would help describe the issue to the user so they would know what it is and how to remedy it. I was searching through the issues here on Github and searching for issues across the web. All the information about what helped others didn't help me at all. I really appreciate your time and effort towards this project. It really helps out modders like me who are new to the modding game. Maybe one day when I learn more about C++ I can contribute on bugfixes and enhancements.

Again thank you and Happy New Years!

**Comment by thunderpants** [comment]
Running Skyrim launcher and deleting the %LOCALAPPDATA%\LOOT  files fixed it for me

**Comment by thloer123-design** [comment]
It helped me
