### ISSUE TITLE
LOOT Error w/ Skyrim SE via MO2

### ISSUE THREAD

**Issue by RLancey3205** [loot/loot#748]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/692769/LOOTDebugLog.txt)

Hi -- I need some help. I'm using LOOT via MO2 for Skyrim SE and when I use LOOT through MO2 I get the error message: boost::filesystem::directory_iterator::construct: The filename, directory name, or volume label syntax is incorrect: "D:\Games\Steam\steamapps\common\Skyrim Special Edition\Data"
But if I use LOOT independent of MO2 it works fine however isn't sorting my MO2 mods so that's not so good. Any suggestions?

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported, because of problems like this. My only suggestion is to not use MO2.
