### ISSUE TITLE
"An error occurred while trying to clone the remote masterlist repository.: libgit2 error"

### ISSUE THREAD

**Issue by AK87991** [loot/loot#750]
As title states; I get this error whenever I try to update the masterlist for any games in LOOT (specifically only tried on Skyrim SE and Fallout 4). Used to work just fine and seems like all of a sudden I am having this problem. Tried past suggestions I dug up related to deleting Fallout 4 (for example) folder under LOOT in local appdata, running as administrator, reinstalling in different location, etc.. nothing changes :-/

Attached Debug Log for reference, CEFDebugLog also has one line which reads "ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak" if that is relevant.

Any help would be greatly appreciated.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/703025/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Are you using the latest release (0.10.3)? It doesn't look like that error message is from it.

**Comment by AK87991** [comment]
Hey, yes I am 100% certain I have the latest version 0.10.3. I know because I uninstalled, re-downloaded and reinstalled it about half a dozen times desperately hoping it would eventually work (haha). I couldn't find much info about anyone else having this issue so I'm not sure why I seem to be alone here, let me know if there is anything I can supply that would help, I attached another debug log from my decently modded Skyrim SE that shows the same issue and a picture with proof of the LOOT version.

Somewhere down the Debug log it reads the same line "An error occurred while trying to clone the remote masterlist repository.: libgit2 error"

![image](https://cloud.githubusercontent.com/assets/25089981/21943743/f720a3f0-d9d2-11e6-84b8-eb1d439c3cbf.png)

[LOOTDebugLog.txt](https://github.com/loot/loot/files/705224/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Ah, the error handling isn't working correctly then, it should be giving details instead of just `libgit2 error`...

**Comment by AK87991** [comment]
Alright well if anything changes I would certainly be happy to know. Thanks ahead of time.

**Comment by WrinklyNinja** [comment]
Could you try with [this snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.10.3-4-gef7ddca_fix-libgit2-error-logging_Win32.7z)? It probably won't fix anything, but it will log a more informative error message.

**Comment by AK87991** [comment]
Here you go... it now reads "An error occurred while trying to clone the remote masterlist repository. Details: -1; failed to send request: The operation timed out: libgit2 error"

(I'm far from an expert but could it be connection related? I tried disabling antivirus but I am running though a proxy server (college). I've never been blocked from anything else though, I'm not entirely sure.)

[LOOTDebugLog.txt](https://github.com/loot/loot/files/705820/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
It's probably due to the proxy, have you tried the steps [here](https://loot.github.io/docs/help/LOOT-FAQs.html#proxy)?

**Comment by AK87991** [comment]
Yes, I don't believe it is a socket error since nothing would suggest that (From my understanding), and I am running windows 10. And I've tried deleting the fallout 4 and skyrim folders from C:\Users\me\AppData\Local\LOOT\ to no aid. On the troubleshooting page it says to "Try deleting the .git folder in %LOCALAPPDATA%\LOOT\<game folder>\" but there have never been any .git folders in that location unless they are hidden; if I open the game folder there is nothing unless I manually insert a masterlist and tell it not to update, but I wasn't sure if it was working properly because the program still tells me no masterlist is present when I sort after manually putting the .yaml file in the corresponding game folder. If that way is actually working properly I can just do it manually until I can access the internet elsewhere to test without a proxy.

**Comment by AK87991** [comment]
On a related note, I just retried sorting with masterlist update off (using manually downloaded masterlists) and afterward on top for either game it reads "Masterlist Revision: Unknown: Git repository missing" and
"Masterlist Date: Unknown: Git repository missing" Am I missing something here...?

**Comment by WrinklyNinja** [comment]
> but there have never been any .git folders in that location unless they are hidden

The .git folder is hidden by default.

> On a related note, I just retried sorting with masterlist update off (using manually downloaded masterlists) and afterward on top for either game it reads "Masterlist Revision: Unknown: Git repository missing" and
> "Masterlist Date: Unknown: Git repository missing" Am I missing something here...?

If you're using manually downloaded masterlists, and there is no no `.git` folder, that's expected.

**Comment by EsOmEs** [comment]
I had the same issue when I tried to use LOOT through MO2. I ran LOOT once outside of MO2 and it successfully downloaded the missing git files. After that it also ran fine through MO2. Maybe that helps you...

**Comment by AK87991** [comment]
Just to update, I connected to the internet at a different location (without bull**** campus proxy server) and everything updated and worked as desired. Thanks for all the help, at least I know what was causing me the issue now.

**Comment by WrinklyNinja** [comment]
OK, closing this as I don't think there's much I can do about the proxy support.
