### ISSUE TITLE
Loot not finding modorganiser mods ....modorganiser/mods

### ISSUE THREAD

**Issue by MuchMucho** [loot/loot#751]
Seems to only find the datafolder, would be great if you manually could tell it where the mods are at as a failsafe.

Am using modorganiser version 2.0.7 if thats causing issues.

**Comment by WrinklyNinja** [comment]
Mod organiser is not supported.

**Comment by MuchMucho** [comment]
Sry to hear that modorganizer2 isn't supported since its my favorite modorganiser tool and actually also the best after my opinion.

**Comment by Freso** [comment]
The reason that MO isn't supported on LOOT's side, is that 99+% of issues have with LOOT when using MO are actually issues on MO's end that we cannot do anything about in LOOT, so they should really be reported with MO. This issue is one of the 99+%.
