### ISSUE TITLE
Crash upon launch from Mod Organizer

### ISSUE THREAD

**Issue by avandesa** [loot/loot#754]
Hello, thanks for all the work you do on this program!

The application launches fine from the desktop. However, when I attempt to launch from Mod Organizer for Skyrim, the application almost immediately crashes.

I first tried updating, and then performing a full reinstall, but the issue persisted.

I switched to MO for Fallout 4, and the application worked fine and loaded all of my mods. From there, I attempted to switch to TESV, and it worked, but none of my installed mods appeared (due to the nature of MO).

[I currently have 167 mods installed with 70 plugins.](https://modwat.ch/u/avandesa).  I was attempting to sort after installing the last five plugins on that list.  They're all from the [clutter/misc](http://wiki.step-project.com/STEP:2.2.9.2#2.K._Clutter_.26_Miscellaneous) section of the STEP guide.

Based upon the debug logs below, it appears there is something wrong with loading the styling. I doubt that it would be caused by one of the mods/plugins, but I'll go through each that I installed, deactivate them, and try again.

Thanks for you help!

Debug logs:
[CEFDebugLog.txt](https://github.com/loot/loot/files/721802/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/721803/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
If LOOT works when not running it through MO, it's a bug in MO and there's nothing we can do about it.

**Comment by avandesa** [comment]
Hello, I know you closed it, but I do have an update. The issue, I believe, isn't with launching from MO, but from a specific mod. I isolated it to [Soul Gems Differ](http://www.nexusmods.com/skyrim/mods/6335/?).  Whenever the mod is activated, even if the esp is disabled, LOOT crashes upon launch.

I know this probably isn't an issue with LOOT, but I am intrigued by the debug logs.

Thanks!
