### ISSUE TITLE
LOOT restores a maximised window to the same dimensions but not maximised

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#756]
If LOOT is maximised then closed, when it is re-launched it sets the window size to the maximised window size, but the window is not actually maximised. Going by Explorer's behaviour, if the window  is maximised when closed, it should be restored maximised and un-maximising it should restore it to its previous size and position (the un-maximise behaviour may be provided by the window system, I don't know).

**Comment by Gr3yStar** [comment]
I think we've got a regression on this with 11.0. Now, with 11.0, no matter if the window was maximized, or if you alter the window dimensions or position in any way, LOOT will return to it's default un-maximized size and position upon the very next launch.

**Comment by WrinklyNinja** [comment]
Huh, you're right. I could swear I tested this when I made the related changes...

**Comment by WrinklyNinja** [comment]
OK, so I've figured out why it's not saving window position (the callback never gets run), but there are a couple of other issues:

- The `CefWindow::Maximise()` call doesn't seem to do anything on Windows, calling Win32 `ShowWindow()` after the window is shown works though.
- If a maximised window is closed, its maximised dimensions are saved, not the pre-maximised dimensions.

**Comment by WrinklyNinja** [comment]
@Gr3yStar Can you check if [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-1-gc266985_fix-window-sizing#files) fixes the issue for you?

**Comment by Gr3yStar** [comment]
Sorry for the late response. everything is seemingly in order now. I do want to point out a minor visual bug when launching loot maximized though.
https://youtu.be/a8mLDvO_vEs
here's a video showcasing that everything works now, and it also shows the visual bug i was talking about on the first launch.

**Comment by WrinklyNinja** [comment]
Yeah, that's due to the hack I'm using to get it working, but I'll try for a better solution.

**Comment by Gr3yStar** [comment]
Alrighty. I was just flying that by you because I wasn't sure if my computer was at fault or not. Thanks again, WrinklyNinja.
