### ISSUE TITLE
Unable to download Loot 0.10.3

### ISSUE THREAD

**Issue by DatrixTHLK** [loot/loot#757]
I'm pretty sure I can download other mods from the nexus fairly easily but your installer while downloading freezes up halfway through the dl process. It then tells me the download failed.

**Comment by WrinklyNinja** [comment]
Can you download it from here on GitHub?

**Comment by BlackGTNinja** [comment]
I can download the EXE but not from the Server when Installing

![loot uninstalled](https://cloud.githubusercontent.com/assets/25482618/22509373/af56df98-e842-11e6-9bb1-b233338cb13d.jpg)

**Comment by WrinklyNinja** [comment]
Oh, right, it's trying to download the MSVC redistributable from Microsoft. The link still works for me, so there's probably something wrong with your internet connection.

**Comment by DatrixTHLK** [comment]
Yes you were correct @WrinklyNinja My wifi was being spotty in certain times and caused my download to fail. I don't have that issue anymore.
