### ISSUE TITLE
Split metadata validator code into its own repository

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#758]
The metadata validator can be reimplemented using the LOOT API, so doesn't need to live in this repository. I've created a [new repository](https://github.com/loot/metadata-validator) for it, but only Windows builds work because only Windows API binaries are uploaded here as part of releases.

- [x] Rebuild the commit tagged `0.10.3` on Travis and upload the binary Travis creates to the 0.10.3 release page.
- [x] Update the Travis config to publish LOOT API builds to GitHub.
- [x] Remove the existing metadata validator code and related config from this repository.

This was originally intended to follow from #753, but the changes made there aren't actually necessary.

**Comment by Freso** [comment]
I thought this was already done! TIL. :) (My FO4 itch is getting really strong and I am now slowly acclimatised to Barcelona. I hope to be able to pick up again somewhat!)

**Comment by WrinklyNinja** [comment]
Nope, I was lazy about it, but now it's good practice for splitting out the API.

**Comment by WrinklyNinja** [comment]
Done in 1f73c46010262abddb15db38f15be609c613f3ca.
