### ISSUE TITLE
Norton blocking loot.exe

### ISSUE THREAD

**Issue by themerson** [loot/loot#767]
Version: v0.10.3

Saying threat: Heur.AdvML.C

https://www.symantec.com/security_response/sape/

**Comment by WrinklyNinja** [comment]
I guess you have to report it to Norton as a false positive.

**Comment by Ghostwalker71** [comment]
Easiest way to sort this is to add the exe to your white list, since Norton will mark any new exe for loot as suspicious until it has gone through the process of being reported and excluded in their database. Which can take a while to complete.
