### ISSUE TITLE
Mod Organizer 2

### ISSUE THREAD

**Issue by Dragun9500** [loot/loot#768]
So I was modding Fallout 4 using Mod Organizer 2 and I was able to use LOOT to sort my plugins. But at some point randomly it stopped working, Every time I load up LOOT it only detects the base game ESM and the DLCs. I do launch LOOT through MO2. I also completely uninstalled and reinstalled both MO2 and LOOT and it still hasn't changed anything. But if I launch LOOT using the original MO with Skyrim, it loads all the mods for that, as it should. Is there something I can do to fix this issue?

**Comment by Freso** [comment]
You should report this at Mod Organizer's issue tracker. If LOOT works outside of MO2, then it's an issue with MO2 and not with LOOT, so we're not able to help with that. Sorry.
