### ISSUE TITLE
Replace yaml-cpp usage with an actual JSON library

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#770]
Communication between C++ and JavaScript is done by serialising objects as JSON, and LOOT currently uses yaml-cpp plus some replace expressions to do the serialising, re-using code that's used by the API to do this. There are JSON-specific libraries available that are more suited to this task, and although using them would mean re-implementing serialisation logic for the classes that need it, there shouldn't be much to it.

The two libraries that seem best/most popular are [nlohmann/json](https://github.com/nlohmann/json) and [RapidJSON](https://github.com/miloyip/rapidjson). I'm leaning towards the former because speed isn't a major concern (RapidJSON is ~5x faster, but I deal with relatively small amounts of data) and the syntax is very expressive.

One problem with this approach is that it means the "Copy ..." functionality will output JSON, not YAML. As the former is a subset of the latter, it's only really a style issue, but is still worth bearing in mind. This could be resolved by retaining usage of yaml-cpp for those bits of functionality, but that seems a bit like overkill, and nlohmann/json supports pretty-printing so the result is only really a different by some double quotes and curly braces.

**Comment by WrinklyNinja** [comment]
Ran into an issue with replacing yaml-cpp: it's used to read/write LOOT's settings file, so it's necessary anyway... Given this, the benefit of adding a separate JSON parser is debatable, so leaving this for now.

**Comment by Freso** [comment]
Is yaml-cpp used for masterlist parsing as well? I don't think the anchors and such are supported under JSON, so a pure-JSON parser will likely not be able to deal with the masterlists and we might need to keep yaml-cpp around anyway.

**Comment by WrinklyNinja** [comment]
yaml-cpp will still be a requirement for the LOOT API, but once the
metadata has been passed up to the application it could be re-serialised as
something else.

**Comment by WrinklyNinja** [comment]
Closing this as wontfix since the YAML parser is required for settings file I/O and useful for the metadata clipboard features, and I've got a PR for yaml-cpp that adds proper support for emitting JSON.
