### ISSUE TITLE
My LOOT doesn't order my plugins for Fallout 4

### ISSUE THREAD

**Issue by AlexBorquezIV** [loot/loot#771]
I order my mods using the loot but some day it stop ordering my mods and now I can't play my game because it start to laging because loot doesn't order my lastest mods

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
