### ISSUE TITLE
Loot won't find Skyrim

### ISSUE THREAD

**Issue by Budda523** [loot/loot#772]
Yeah, as the title says...

For the install Path I set:
E:\Games\SteamLibrary\SteamApps\common\Skyrim\Data

And for the Install Path Registry Key:
E:\Games\SteamLibrary\SteamApps\common\Skyrim

I already launched the Skyrim launcher, but LOOT still won't find Skyrim.

Has anyone any ideas? Maybe I'm still doing something wrong?

**Comment by WrinklyNinja** [comment]
The install path and registry key values should not be the same, set the registry key value to be empty and see if LOOT will then detect Skyrim.

**Comment by Budda523** [comment]
Ok, I don't know what it was. After I emptied the registry key value there was still the same error. 
Then I deleted everything in the LOOT debug location and restarted LOOT and it found Skyrim immediately.
