### ISSUE TITLE
Skyrim - Loot order feedback / bug report

### ISSUE THREAD

**Issue by Bandifighter** [loot/loot#776]
Hello there,

### **Issue:**
Just wanted to report back that when I use the load order LOOT automatically sorted for me I have the location "Little Vivec" (added by the mod "Moon and Star")  village sort of float when using Aurora Village along with Moon and Star (+ compatibility patch) due to what looks like missing/disabled ground/texture meshes on the island.
This is also noted by the author of the Moon and Star, under the file "[Aurora Village Compatibility Patch](http://www.nexusmods.com/skyrim/mods/52397/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fskyrim%2Fajax%2Fmodfiles%2F%3Fid%3D52397&pUp=1)":

> Requires MoonAndStar_MAS.esp, AuroraVillage.esp, and loading Moon and Star after Aurora Village.

### **Fix:**
To fix it I had to manually make it so that MoonandStar_MAS.esp loads after AuroraVillage.esp
Now the metadata is:
```
[spoiler][code]name: 'MoonAndStar_MAS.esp'
after:
  - 'AuroraVillage.esp'[/code][/spoiler]
```

### **To easily see what my correcting action made to my load order:**
https://www.diffchecker.com/NpscX0Wg
(left side is the load order that seemed incorrect, the right one seems to be perfect so far).

### _Load orders - before and after fix:_
**The default, incorrect load order was:**
  _0  0 Skyrim.esm
  1  1 Update.esm
  2  2 Dawnguard.esm
  3  3 HearthFires.esm
  4  4 Dragonborn.esm
  5  5 Unofficial Skyrim Legendary Edition Patch.esp
  6  6 Skyrim Project Optimization - Full Version.esm
  7  7 Falskaar.esm
  8  8 Wyrmstooth.esp
  9  9 RSkyrimChildren.esm
 10  a SkyTEST-RealisticAnimals&Predators.esm
 11  b HighResTexturePack01.esp
 12  c HighResTexturePack02.esp
 13  d HighResTexturePack03.esp
 14  e Unofficial High Resolution Patch.esp
 15  f Cutting Room Floor.esp
 16 10 SkyUI.esp
 17 11 TradeBarter.esp
 18 12 Random Vampire Attacks in Towns Disabled.esp
 19 13 When Vampires Attack.esp
 20 14 MIDFollowMeCloser.esp
 21 15 FCO - Follower Commentary Overhaul.esp
 22 16 FISS.esp
 23 17 EnhancedLightsandFX.esp
 24 18 ELFX - Exteriors.esp
 25 19 LydiaPrettyFace.esp
 26 1a DesyncBirdsOfPrey.esp
 27 1b Brighter Campfires X20.esp
 28 1c RSChildren - Complete.esp
 29 1d AHZmoreHUD.esp
 30 1e UnreadBooksGlow.esp
 31 1f AMB Glass Variants Lore.esp
 32 20 Differently Ebony.esp
 33 21 AOS.esp
 34 22 dD - Enhanced Blood Main.esp
 35 23 dD-Dragonborn-Dawnguard-EBT Patch.esp
 36 24 Hothtrooper44_Armor_Ecksstra.esp
 37 25 iWil_UselessShopOverhaul.esp
 38 26 Blues Skyrim.esp
 39 27 Comprehensive Whiterun Bug Fix 1.1.esp
 40 28 Weathered Road Signs.esp
 41 29 Ebonvale.esp
 42 2a MoonAndStar_MAS.esp
 43 2b Hothtrooper44_ArmorCompilation.esp
 44 2c Wyrmstooth - Craftable Sets.esp
 45 2d Less Falling Damage.esp
 46 2e Guard Dialogue Overhaul.esp
 47 2f BattleAftermath.esp
 48 30 BetterQuestObjectives.esp
 49 31 DFB - Random Encounters.esp
 50 32 BFT Ships and Carriages.esp
 51 33 Immersive Weapons.esp
 52 34 aMidianborn_Skyforge_Weapons.esp
 53 35 Destructible_bottles.esp
 54 36 Unique BOOZE Bottles.esp
 55 37 BrighterTorchesBiggerMagelight.esp
 56 38 BetterQuestObjectives-AMBSkyforgePatch.esp
 57 39 Chesko_LoreBasedLoadingScreens.esp
 58 3a AOS2_EBT Patch.esp
 59 3b Book Covers Skyrim.esp
 60 3c ELFXEnhancer.esp
 61 3d Vivid Weathers.esp
 62 3e IcePenguinWorldMap.esp
 63 3f CollegeDormDoors.esp
 64 40 Realistic Boat Bobbing.esp
 65 41 Vivid Weathers - AOS patch.esp
 66 42 AOS2_GDO Patch.esp
 67 43 SPTUnlimitedRingsDragonborn.esp
 68 44 SPTUnlimitedRingsDawnguard.esp
 69 45 SPTUnlimitedRings.esp
 70 46 SPTUnlimitedAmuletsDragonborn.esp
 71 47 SPTUnlimitedAmuletsDawnguard.esp
 72 48 SPTUnlimitedAmulets.esp
 73 49 Shields of Jorrvaskr by Hothtrooper44.esp
 74 4a ABT - Increased Progressive Damage (with Nord Hero Arrow) +100%.esp
 75 4b PipeSmoking.esp
 76 4c Sinking Bodies.esp
 77 4d No Dragon LODs v2 full.esp
 78 4e WondersofWeather.esp
 79 4f ImprovedHearthfireLighting.esp
 80 50 AuroraVillage.esp
 81 51 Skysan_ELFX_SMIM_Fix.esp
 82 52 Vivid Weathers - Falskaar.esp
 83 53 Vivid Weathers - Wyrmstooth.esp
 84 54 prettypotions.esp
 85 55 RUSTIC SOULGEMS - Unsorted.esp
 86 56 RealisticHumanoidMovementSpeed.esp
 87 57 BF.esp
 88 58 Animallica.esp
 89 59 Hide Those Futile Quests.esp
 90 5a SkyTweak.esp
 91 5b MoreSoundOptions.esp
 92 5c ABT - Increased Bolts Damage (Vanilla) +100%.esp
 93 5d ABT - Merchants Arrows +50%.esp
 94 5e AuroraVillage-RSChildren.esp
 95 5f Better Docks DLC's - Compatible Version.esp
 96 60 SolitudeBetterDocks.esp
 97 61 The Honored Dead.esp
 98 62 Run For Your Lives.esp
 99 63 SMIM-Merged-All.esp
100 64 OH GOD BEES.esp
101 65 DIVERSE SKYRIM.esp
102 66 Immersive Patrols II.esp
103 67 Wyrmstooth - Landmarks.esp
104 68 MoonAndStar_AuroraPatch.esp
105 69 CampNewZainab.esp
106 6a FarmhouseChimneys.esp
107 6b RiftenBetterDocks.esp
108 6c RBB - Wyrmstooth.esp
109 6d The Paarthurnax Dilemma.esp
110 6e BetterQuestObjectives-PaarDilemmaPatch.esp
111 6f BlitzConsoleCommandsMCM.esp
112 70 RSChildren - CRF Patch.esp
113 71 DawnstarBetterDocks.esp
114 72 DYNAVISION Dynamic Depth of Field.esp
115 73 Footprints.esp
116 74 FarmhouseChimneysFalskaar+Wyrmstooth.esp
117 75 ELFX - UselessShopOverhaul patch.esp
118 76 EmbersHD.esp
119 77 FarmhouseChimneysAurora+MaS.esp
120 78 FarmhouseChimneysCRF.esp
121 79 IslandFastTravel.esp
122 7a SolstheimBetterDocks.esp
123 7b AK- Boethiah Alternate.esp
124 7c NoRandomDragons.esp
125 7d Take a Leek.esp
126 7e navetsea female face preset.esp
127 7f SaturationBoost.esp
128 80 Beards.esp
129 81 Babette.esp
130 82 WyrmstothMapMarkerHotfix.esp
131 83 TheEyesOfBeauty.esp
132 84 The Eyes Of Beauty - Elves Edition.esp
133 85 WyrmstoothTravelCrashHotfix.esp
134 86 Wyrmstooth - Realistic Ownership.esp
135 87 Wyrmstooth - Dragon Lore.esp
136 88 Wyrmstooth - Typo Fix.esp
137 89 Wyrmstooth - Follower Tweaks.esp
138 8a Wyrmstooth - Radiant Encounter Tweaks.esp
139 8b No_stretching.esp
140 8c Purewaters.esp
141 8d AOS_Reduced_Reverb_Addon.esp
142 8e DynDOLOD.esp_

**The correct load order is now the following:**
  _0  0 Skyrim.esm
  1  1 Update.esm
  2  2 Dawnguard.esm
  3  3 HearthFires.esm
  4  4 Dragonborn.esm
  5  5 Unofficial Skyrim Legendary Edition Patch.esp
  6  6 Skyrim Project Optimization - Full Version.esm
  7  7 Falskaar.esm
  8  8 Wyrmstooth.esp
  9  9 RSkyrimChildren.esm
 10  a SkyTEST-RealisticAnimals&Predators.esm
 11  b HighResTexturePack01.esp
 12  c HighResTexturePack02.esp
 13  d HighResTexturePack03.esp
 14  e Unofficial High Resolution Patch.esp
 15  f Cutting Room Floor.esp
 16 10 SkyUI.esp
 17 11 TradeBarter.esp
 18 12 Random Vampire Attacks in Towns Disabled.esp
 19 13 When Vampires Attack.esp
 20 14 MIDFollowMeCloser.esp
 21 15 FCO - Follower Commentary Overhaul.esp
 22 16 FISS.esp
 23 17 EnhancedLightsandFX.esp
 24 18 ELFX - Exteriors.esp
 25 19 LydiaPrettyFace.esp
 26 1a DesyncBirdsOfPrey.esp
 27 1b Brighter Campfires X20.esp
 28 1c RSChildren - Complete.esp
 29 1d AHZmoreHUD.esp
 30 1e UnreadBooksGlow.esp
 31 1f AMB Glass Variants Lore.esp
 32 20 Differently Ebony.esp
 33 21 AOS.esp
 34 22 dD - Enhanced Blood Main.esp
 35 23 dD-Dragonborn-Dawnguard-EBT Patch.esp
 36 24 Hothtrooper44_Armor_Ecksstra.esp
 37 25 iWil_UselessShopOverhaul.esp
 38 26 Blues Skyrim.esp
 39 27 Comprehensive Whiterun Bug Fix 1.1.esp
 40 28 Weathered Road Signs.esp
 41 29 Ebonvale.esp
 42 2a Hothtrooper44_ArmorCompilation.esp
 43 2b Wyrmstooth - Craftable Sets.esp
 44 2c Less Falling Damage.esp
 45 2d Guard Dialogue Overhaul.esp
 46 2e BattleAftermath.esp
 47 2f BetterQuestObjectives.esp
 48 30 DFB - Random Encounters.esp
 49 31 BFT Ships and Carriages.esp
 50 32 Immersive Weapons.esp
 51 33 aMidianborn_Skyforge_Weapons.esp
 52 34 Destructible_bottles.esp
 53 35 Unique BOOZE Bottles.esp
 54 36 BrighterTorchesBiggerMagelight.esp
 55 37 BetterQuestObjectives-AMBSkyforgePatch.esp
 56 38 Chesko_LoreBasedLoadingScreens.esp
 57 39 AOS2_EBT Patch.esp
 58 3a Book Covers Skyrim.esp
 59 3b ELFXEnhancer.esp
 60 3c Vivid Weathers.esp
 61 3d IcePenguinWorldMap.esp
 62 3e CollegeDormDoors.esp
 63 3f Realistic Boat Bobbing.esp
 64 40 Vivid Weathers - AOS patch.esp
 65 41 AOS2_GDO Patch.esp
 66 42 SPTUnlimitedRingsDragonborn.esp
 67 43 SPTUnlimitedRingsDawnguard.esp
 68 44 SPTUnlimitedRings.esp
 69 45 SPTUnlimitedAmuletsDragonborn.esp
 70 46 SPTUnlimitedAmuletsDawnguard.esp
 71 47 SPTUnlimitedAmulets.esp
 72 48 Shields of Jorrvaskr by Hothtrooper44.esp
 73 49 ABT - Increased Progressive Damage (with Nord Hero Arrow) +100%.esp
 74 4a PipeSmoking.esp
 75 4b Sinking Bodies.esp
 76 4c No Dragon LODs v2 full.esp
 77 4d WondersofWeather.esp
 78 4e ImprovedHearthfireLighting.esp
 79 4f AuroraVillage.esp
 80 50 MoonAndStar_MAS.esp
 81 51 Skysan_ELFX_SMIM_Fix.esp
 82 52 Vivid Weathers - Falskaar.esp
 83 53 Vivid Weathers - Wyrmstooth.esp
 84 54 prettypotions.esp
 85 55 RUSTIC SOULGEMS - Unsorted.esp
 86 56 RealisticHumanoidMovementSpeed.esp
 87 57 BF.esp
 88 58 Animallica.esp
 89 59 Hide Those Futile Quests.esp
 90 5a SkyTweak.esp
 91 5b MoreSoundOptions.esp
 92 5c ABT - Increased Bolts Damage (Vanilla) +100%.esp
 93 5d ABT - Merchants Arrows +50%.esp
 94 5e AuroraVillage-RSChildren.esp
 95 5f Better Docks DLC's - Compatible Version.esp
 96 60 SolitudeBetterDocks.esp
 97 61 The Honored Dead.esp
 98 62 Run For Your Lives.esp
 99 63 SMIM-Merged-All.esp
100 64 OH GOD BEES.esp
101 65 DIVERSE SKYRIM.esp
102 66 Immersive Patrols II.esp
103 67 Wyrmstooth - Landmarks.esp
104 68 MoonAndStar_AuroraPatch.esp
105 69 CampNewZainab.esp
106 6a FarmhouseChimneys.esp
107 6b RiftenBetterDocks.esp
108 6c RBB - Wyrmstooth.esp
109 6d The Paarthurnax Dilemma.esp
110 6e BetterQuestObjectives-PaarDilemmaPatch.esp
111 6f BlitzConsoleCommandsMCM.esp
112 70 RSChildren - CRF Patch.esp
113 71 DawnstarBetterDocks.esp
114 72 DYNAVISION Dynamic Depth of Field.esp
115 73 Footprints.esp
116 74 FarmhouseChimneysFalskaar+Wyrmstooth.esp
117 75 ELFX - UselessShopOverhaul patch.esp
118 76 EmbersHD.esp
119 77 FarmhouseChimneysAurora+MaS.esp
120 78 FarmhouseChimneysCRF.esp
121 79 IslandFastTravel.esp
122 7a SolstheimBetterDocks.esp
123 7b AK- Boethiah Alternate.esp
124 7c NoRandomDragons.esp
125 7d Take a Leek.esp
126 7e navetsea female face preset.esp
127 7f SaturationBoost.esp
128 80 Beards.esp
129 81 Babette.esp
130 82 WyrmstothMapMarkerHotfix.esp
131 83 TheEyesOfBeauty.esp
132 84 The Eyes Of Beauty - Elves Edition.esp
133 85 WyrmstoothTravelCrashHotfix.esp
134 86 Wyrmstooth - Realistic Ownership.esp
135 87 Wyrmstooth - Dragon Lore.esp
136 88 Wyrmstooth - Typo Fix.esp
137 89 Wyrmstooth - Follower Tweaks.esp
138 8a Wyrmstooth - Radiant Encounter Tweaks.esp
139 8b No_stretching.esp
140 8c Purewaters.esp
141 8d AOS_Reduced_Reverb_Addon.esp
142 8e DynDOLOD.esp_

**Comment by Bandifighter** [comment]
In case any more info is needed, such as the installed version of the 3 mods in question (Moon and Star, Aurora village and the patch for the compatibility of the two) or something else just let me know and I'll attempt to provide them.

**Comment by WrinklyNinja** [comment]
Is this for the original Skyrim or SE? For future reference, the issue should have been filed in one of their issue trackers:

- https://github.com/loot/skyrim/issues
-https://github.com/loot/skyrimse/issues

**Comment by Bandifighter** [comment]
Ah, alright. My bad. It's Skyrim. Should I delete this and file one there?

**Comment by WrinklyNinja** [comment]
No, it's fine, and you can't delete issues anyway, only close them.
