### ISSUE TITLE
Unable to detect or sort plugins with Skyrim SE and a junctioned install directory.

### ISSUE THREAD

**Issue by skeevy420** [loot/loot#777]
I've discovered that Loot isn't able to always detect or sort plugins after installation when the Skyrim SE install directory has a junction to a different location.  **Luckily it is a simple fix of modifying "%LocalAppData%\LOOT\settings.yaml" and manually entering the path to where Skyrim SE is physically located and not the path of the junction** (for me it is Steam's default Skyrim SE folder).  For some reason, I wasn't able to change the install directory from within Loot, tried both as a regular user and running as administrator, but after changing it by hand, it works just fine and I haven't had a single issue since.  

For some info on my setup, I have SSE, my mods (not archives), and various mod tools installed to a 30GB ramdisk\image because I have a bunch of ram (48gb) and no SSD.  What I do is either mount the image to a dummy drive (stuff that'll increase image size) or to a ramdisk (to play), and I keep a junction that points to my image (either setup) in my steam directory.  This is a setup that I do for any game that's under 32gb of size.  I figure 14gb of ram is plenty for Windows 10 or Arch Linux and whatever game I'm running.

I apologize that I don't have any logs to go with this.  I was having this issue yesterday after a complete reinstall of SSE, my mods, and tools, and by the time I figured this out, I was just so happy it worked that I ran Loot, made a bashed patch, and started playing.  If necessary I can revert the changes to "settings.yaml" and upload any logs you'd like.

Edit: Using 0.11.0

**Comment by WrinklyNinja** [comment]
IIRC there are already tests for symlink support, but I don't think junction links are tested, I'm not really surprised it doesn't work. It should be fairly easy to replicate, I'll ask if I need logs.

**Comment by WrinklyNinja** [comment]
Actually, there are a few possible places that could be causing problems, the logs would be helpful.

**Comment by skeevy420** [comment]
Uninstalled and wiped user data.
Here's the first run after the install.
[CEFDebugLog.txt](https://github.com/loot/loot/files/1014878/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1014879/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
What about the LOOT API debug log?

**Comment by skeevy420** [comment]
Where is it located?

**Comment by skeevy420** [comment]
I'll add that I was able to use the settings menu and set the correct directory this time.  I'm really not sure why I wasn't able to on my last install.  I tried three times before manually editing the config last time.  But that doesn't change it not working by setting LOOT to use the junction directory.

**Comment by WrinklyNinja** [comment]
> Where is it located?

There should be a LOOTAPIDebugLog.txt, but you may need to turn on debug logging in LOOT's settings.

**Comment by skeevy420** [comment]
That did the trick.  Can't believe I didn't see that setting....It's right there....

Deleted settings, restarted, enabled debugging, restarted:
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1014918/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1014919/LOOTDebugLog.txt)

Changed settings to use the physical directory, restarted:
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1014924/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1014923/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Right, I think I've pinpointed the issue. The logs show that LOOT can find your data folder and the plugins in it, but then thinks they're all invalid, because libespm thinks they're invalid. Libespm thinks they're invalid because it can't parse their headers. I'm guessing that's because it memory-maps the file, and the underlying implementation can't resolve junction links correctly.

Unfortunately, there's not a lot I can do about that. Perhaps when C++17 is official (hopefully only a few months), MSVC will have implemented its filesystem library with support for junction links, and I may be able switch to that.

**Comment by WrinklyNinja** [comment]
@skeevy420: I think I've got a fix for this. Get the LOOT v0.11.0 release, and replace its loot_api.dll with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.0-5-gc78314c_fix-junction-link-support-win32.7z), and see if that works for you when the game path is set to the junction link path, not the actual path.
