### ISSUE TITLE
Syntax Error in Masterlist

### ISSUE THREAD

**Issue by Viusing** [loot/loot#779]
Masterlist revision 98a1fc7: yaml-cpp: error at line 112, column 9: bad conversion: 'utility' key missing from 'cleaning data' object. The latest masterlist revision contains a syntax error, LOOT is using the most recent valid revision instead. Syntax errors are usually minor and fixed within hours.

**Comment by WrinklyNinja** [comment]
I can't replicate this, and CI says there isn't any syntax error. Try using the latest version of LOOT if you're not already doing so. It would have been helpful if you'd provided the version you're using, and indeed the game you're getting the error for.

**Comment by Viusing** [comment]
Updating to the latest version of LOOT fixed this, for any others who had a similar error.

I was under the impression that LOOT auto updated, but it seems I got my tools mixed up.

Sorry for not replying back sooner.
