### ISSUE TITLE
Loot disables plugins for Legendary Skyrim when sorting load order for Skyrim Special Edition.

### ISSUE THREAD

**Issue by revolcane-gaming** [loot/loot#781]
I have both Old Skyrim and Special Edition loaded on the same PC. When I sort the load order for special Edition, it disables plugins for Old Skyrim. I am a game streamer and I play both for different content.

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

I can't replicate this: sorting for Skyrim SE modifies plugins.txt for it, and doesn't touch Skyrim's plugins.txt.
