### ISSUE TITLE
loot is not loading my mods. I use nmm and the game is fallout4

### ISSUE THREAD

**Issue by cade111** [loot/loot#782]
ok so before I put this in the incorrect place and now I need help. it could be something simple that I overlooked but try as I might I could not get loot to load my mods. I'm using nexus mod manager and I set loot to my fallout 4 folder. Please help me!

**Comment by WrinklyNinja** [comment]
You've just created a duplicate in the same issue tracker. Use #780 instead.

**Comment by cade111** [comment]
sorry its just you recommended i make a new one under this name
