### ISSUE TITLE
v11 is incompatible with mod organiser

### ISSUE THREAD

**Issue by afsu312** [loot/loot#784]
I'm not sure who to report this, so I'll write it here. 
As of 23rd May 2017, Mod Organizer (v1.3.11) is incompatible with LooT (v0.11.0). 
I've downloaded LooT (v0.11.0) and test run it alone. **It was working.**
Then i ran LooT through Mod Organizer (v1.3.11). All that came out was a **blank page.**
i then re-ran LooT without Mod Organiser, and all that appears was **a blank page again**.
i then re-download LooT (v0.11.0) and reinstalled LooT. 
The same thing happened again and again:
      - Re-Download, re-install, ran LooT, it worked just fine.
      - Ran LooT through MO (Mod Organiser), a blank page appears. _(even with the "--single-process" 
      argument added)_
      - Ran LooT again without MO, blank page appears.
I finally downloaded the previous version of LooT (LooT v 0.10.3). 
Everything worked fine even with MO, without even having to use the"--single-process" argument.
Sorry for the long comment. Just want to let you know that LooT(v0.11.0) is not working with Mod Organizer (v1.3.11).

**Comment by WrinklyNinja** [comment]
Mod Organiser breaks LOOT seemingly at random and has done for a long time, that's why it's unsupported (and also because MO's author no longer supports it either). There's not really anything that can be done about this.
