### ISSUE TITLE
LOOT v0.11.0 crash during Plugin sort

### ISSUE THREAD

**Issue by GarnetSan** [loot/loot#787]
I just installed Skyrim with a good handful of mods on my new PC and just as the title says, LOOT crashes while sorting my plugins. 
The rest of the aplication seems towork just fine. This isn't the first time I use LOOT for Skyrim and I've used it for FO4 as well.
DebugLogs are attached

[CEFDebugLog.txt](https://github.com/loot/loot/files/1051976/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1052014/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1052015/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Those don't seem to be the logs from when LOOT crashed.

**Comment by GarnetSan** [comment]
I just reproduced the crash again. How about these?
[CEFDebugLog.txt](https://github.com/loot/loot/files/1052957/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1052955/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1052956/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
That's better: I now see `[21:21:30.886860] [error]: Cannot read plugin file "KJ Lore Tattoos 2K.esp". Details: ios_base::failbit set: iostream stream error`. Googling for that plugin [suggests](https://forums.nexusmods.com/index.php?/topic/1337317-kj-tattoos-overlay-plugins-for-racemenu/page-33) there are issues with it, check if there's a newer or fixed version available.

Still, LOOT shouldn't outright crash, can you link me to the download page you got it from, or if it's a small (< 2MB) archive, upload it for me here?

**Comment by GarnetSan** [comment]
Sure thing, although it was the Skyrim SE Nexusmods Page: http://www.nexusmods.com/skyrimspecialedition/mods/1918/?
As far as I know that LOOT version should support regular skyrim, right?

**Comment by WrinklyNinja** [comment]
> As far as I know that LOOT version should support regular skyrim, right?

It supports the original Skyrim and the Special Edition separately. You shouldn't really be mixing plugins for one with the other, though I don't think that should have caused LOOT's crash.

**Comment by GarnetSan** [comment]
> You shouldn't really be mixing plugins for one with the other
That's not what I meant, I just downloaded it from the nexus SSE page beacause I couldn't find it in the regular Skyrim nexus page. I've worked enough with skyrim and fallout modding to know that.

I could try to disable the plugin before running loot to see if that's causing the crash or not.

**Comment by WrinklyNinja** [comment]
You'd need to move it out of your data folder entirely, ie. uninstall it. Disabling it won't stop LOOT from trying to load it.

**Comment by GarnetSan** [comment]
I know, disabling the mod just removes it from the load order. I just tried uninstalling the mod and it doesn't crash, there must be something particular about that plugin that makes LOOT stop responding. I'll post a bug report on their nexus page, although I doubt they will update the mod at this point.

**Comment by WrinklyNinja** [comment]
> Sure thing, although it was the Skyrim SE Nexusmods Page: http://www.nexusmods.com/skyrimspecialedition/mods/1918/?
> As far as I know that LOOT version should support regular skyrim, right?

I actually meant the link for the plugin that's causing LOOT to break, not the link to where you got LOOT, sorry for the ambiguous wording.

**Comment by pStyl3** [comment]
It's on the modpage you already found @WrinklyNinja , it's an optional file (the main file is alright, but the optional "lore" version is the one that's causing the problem.

If I try to open the plugin in TES5Edit 3.2, xEdit reports:  `An error occured while loading modules. Editing is disabled. Check the message log and correct the error.` and `[00:00] Background Loader: Fatal: <EAccessViolation: Access violation at address 007A2EE6 in module 'SSEEdit.exe'. Read of address 00000000>`. It then looks like [this](https://abload.de/img/untitled1uckfh.jpg).

I can click on the record `00000800` but if I click on that record `00000000` I get two further errors:
`Access violation at address 00BFF2B4 in module 'SSEEdit.exe'. Read of address 00000000.` and `Assertion failure in TES5Edit\frmViewMain.pas, line 14467`

Maybe this is interesting for @zilav aswell?

**Comment by GarnetSan** [comment]
Modpage: http://www.nexusmods.com/skyrim/mods/50032/?
Yeah, apparently the esp has been broken for a while now. Simply uninstalling fixed it for me. Weirdly enough skyrim worked just fine with the plugin.

**Comment by WrinklyNinja** [comment]
I think it's because the `QUST` group's size field has a value of `0x103`, when the actual size of the group is `0x102`. The plugin also doesn't have a `SNAM` field in its header, which I seems unusual to me, but my code allows for that. The single `QUST` record's stated size matches its actual size, and LOOT doesn't parse subrecords for anything for the `TES4` header, so I don't think there could be any other cause.

As for the crash, that's probably because there's nothing catching the exception in the thread where the plugin is loaded.

**Comment by zilav** [comment]
Resave that plugin in CK and try again.
