### ISSUE TITLE
Regression: Force overwrite LOOT's git repositories when history has changed

### ISSUE THREAD

**Issue by Freso** [loot/loot#790]
See https://github.com/loot/loot/issues/297 - I don't know if there's been a conscious decision to revert this, but I'd really like it to force updating HEAD to FETCH_HEAD again. :)

**Comment by WrinklyNinja** [comment]
It wasn't intentional...

**Comment by WrinklyNinja** [comment]
Could you describe the state of your branches in the remote and local repositories that LOOT's using? I'm going to add a test for this, and want to make sure I'm getting the situation right.

**Comment by Freso** [comment]
Well, right now they're all neatly lined up. :) Usually I use a `v0.10-local` branch (which I can edit locally on my Windows machine and push to/pull from from my laptop (thanks CIFS!)). This `v0.10-local` branch I'll happily rebase, force push or do other Very Bad Things(tm) to, until I feel the commits are ready to be pushed upstream. Anyway.

Example workflow:
  - `git checkout v0.10-local` (add a `-b` in there if the branch doesn't already exist)
  - `git fetch --all --prune`
  - `git reset --hard origin/v0.10` (makes the current HEAD of `v0.10-local` identical to https://github.com/loot/fallout4/tree/v0.10 regardless of its previous state)
  - Edit masterlist
  - `git commit -av`
  - Run LOOT and make it update masterlist from local repository
  - Realise I made a typo in commit message
  - `git commit -av --amend`
  - Run LOOT again and try to update again: get error that the masterlist couldn't be updated (because the HEAD for `v0.10-local` in LOOT's copy of the repository no longer exists in the "upstream" repository)

**Comment by WrinklyNinja** [comment]
OK, I think I've got a test replicating the issue, is the error you get something like `Git operation failed. Details: -1; Cannot delete branch 'refs/heads/master' as it is the current HEAD of the repository.: libgit2 error`?

**Comment by Freso** [comment]
Probably. 😼 I have a planned change to the FO4 masterlist in the pipeline. I'll get to it tonight or this weekend. Should I check whether I get that exact error, or should I just try and devel build and check if it works as intended now? (Or both…)

**Comment by WrinklyNinja** [comment]
Try replacing your `loot_api.dll` with [this one](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.11.0-5-gf9d0a00_fix-masterlist-update-win32.7z).

**Comment by Freso** [comment]
Works perfectly now. Thanks! :)

**Comment by Freso** [comment]
Wait, I guess you haven't merged the branch yet. I'll let you close it. 😇

**Comment by WrinklyNinja** [comment]
Oh neat, the automagical closing still works if the commit's from another repository. Hopefully it only works if you've got write access to both...
