### ISSUE TITLE
F4SE version check

### ISSUE THREAD

**Issue by jandraelune** [loot/loot#791]
Loot thinks the newest version of F4SE is not the newest.

" It appears you do not have the latest version of F4SE. Some mods may require functionality added in the latest version of F4SE to work. "

Newest version of F4SE is: Fallout 4 runtime 1.9.4 - build: 0.4.1

**Comment by Freso** [comment]
You should file this for the relevant masterlist (`fallout4`); see https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html

2nd, please double check what version of `f4se_loader.exe` you actually have in your game dir. (This can be seen if you right click on the executable, "Details…" (or something like that), and go look at one of the tabs which should have one of its key:value pairs be "Version". (I don't sit on a Windows machine right now, so I can't guide more concretely.)

I'm closing this issue, so just be sure to include the above when you open a new issue in the proper issue tracker. :)
