### ISSUE TITLE
Clicking "Sort Plugins" Causes LOOT.exe to Crash in Mod Organizer

### ISSUE THREAD

**Issue by Leer0x** [loot/loot#795]
I get the error message "Loot.exe has stopped working: A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." when running LOOT through Mod Organizer for Skyrim (version 1.3.11)
I've tried changing versions of Microsoft.NET and this hasn't fixed this problem. Re-installing LOOT does not fix this. Using version v0.10.3 of Loot does NOT cause this problem. Running Loot outside of Mod Organizer DOES work. Help?

**Comment by Freso** [comment]
> Running Loot outside of Mod Organizer DOES work.

Then it's a problem with Mod Organizer and not LOOT. We can't provide support for Mod Organizer, so you'll have to approach them for help. Sorry.
