### ISSUE TITLE
App Fail to Start

### ISSUE THREAD

**Issue by micmou** [loot/loot#798]
So it seems that LOOT refuses to even launch on my PC. Some Info, Latest Windows 10 Creators Update, Fallout 4 and all DLC, Mods installed through NMM latest version. I double click on the LOOT.exe a little loading wheel pops up for about half a second and then vanishes. I never catch the process running using Task Manager. Steps I have tried to fix. Unistall Reinstall of LOOT, Deleting LOOT APPDATA, Running in Compat mode going from Windows 8 to XP, Running as Admin. Loot is installed it D:/LOOT Same drive as my game. At first no log was being generated or settings.yaml got it to generate not that it is useful as per IRC suggestion I tried latest Dev Build to no avail.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1127236/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Did you try manually enabling debug mode as in the bottom of [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by micmou** [comment]
Yeah I attached the Debug log :P I can try an older build

**Comment by WrinklyNinja** [comment]
> Yeah I attached the Debug log :P I can try an older build

There wasn't a `LOOTAPIDebugLog.txt`?

**Comment by micmou** [comment]
Sorry for late reply but no there was not.

**Comment by micmou** [comment]
Okay it seems the issue still persists
here is a GIF with what happens when I launch the app
http://i.imgur.com/XJKU24p.gifv

Here is the DebugLog it has generated this time the other two are not being generated at all.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1134398/LOOTDebugLog.txt)

**Comment by micmou** [comment]
Okay so Loot 10.3 is running fine I believe that my issue is a clone of #786 Here are all the 10.3 logs

[CEFDebugLog.txt](https://github.com/loot/loot/files/1134406/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1134407/LOOTDebugLog.txt)

**Comment by Freso** [comment]
@micmou What Windows version are you on? If Windows 10, are using the Insider Program? What's your build number?

**Comment by micmou** [comment]
Umm one sec I have no idea lol

http://i.imgur.com/8gQ8xFR.jpg

It is 1703 15063.413

**Comment by WrinklyNinja** [comment]
> Okay so Loot 10.3 is running fine I believe that my issue is a clone of #786

I'm going to close this as a duplicate of #786 then, please post future comments in that issue thread.
