### ISSUE TITLE
Kaspersky Internet Security detects LOOT 0.11.0 as threat

### ISSUE THREAD

**Issue by rosedesavane** [loot/loot#800]
Loot v 0.11.0 is detected +++ bay KIS

**Comment by WrinklyNinja** [comment]
What does that mean?

**Comment by rosedesavane** [comment]
after installing loot 0.11.0 , KIS block it always indicating that is infected

**Comment by WrinklyNinja** [comment]
I'm guessing that KIS stands for Kaspersky Internet Security? Please don't
make me guess.

If that's correct, you need to report LOOT v0.11.0 as a false positive.

**Comment by rosedesavane** [comment]
Yes, KIS stands for Kaspersky Internet Security. Thanks for your answer .
