### ISSUE TITLE
LOOT keeps crashing whenever I try to sort plugins

### ISSUE THREAD

**Issue by thestrauch** [loot/loot#802]
Whenever I try to get LOOT to sort my Skyrim plugins, it goes through "updating and parsing masterlist" and then freezes when sorting the plugins, and eventually crashes. Stranger still, it appears this issue may have something to do with the Dragonborn DLC. Here are the texts found in my debugging files:

CEFDebugLog.txt: [0716/225909.859:ERROR:main_delegate.cc(726)] Could not load cef_extensions.pak

LOOTAPIDebugLog.txt: [22:59:16.809843] [error]: Cannot read plugin file "Dragonborn.esm". Details: ios_base::failbit set: iostream stream error

LOOTDebugLog.txt: [22:59:10.000455] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:59:10.001456] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700

Any help would be much appreciated!

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for how to enable debug logging, I need more info.

**Comment by WrinklyNinja** [comment]
Also try the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-18-gdf62b79_dev.7z).

**Comment by DemetriussXVII** [comment]
I had the same issue and I found this https://www.reddit.com/r/skyrimmods/comments/3p7sxj/loot_keeps_crashing/ 
which worked for me

**Comment by WrinklyNinja** [comment]
Can you post the settings.yaml that works for you now and the settings.yaml that v0.11.0 writes that causes you crashes?

**Comment by hesam2013** [comment]
I reinstall ver 9.2 and all back to normal.

**Comment by WrinklyNinja** [comment]
@hesam2013: Does it work with the [latest snapshot build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-27-g5566904_dev#files)?

**Comment by umisery** [comment]
I'm having the same issue as well on New Vegas, it starts to sort the load order and the crashes after a few seconds. Using the build "loot_0.11.0-32-g31af55b_dev" works, if that's any consolation. I guess I'll have to stick with that now until the fixes are incorporated into the main build.

(New Vegas - GOG, Windows 7 SP1 64bit, NMM 0.63.14, LOOT 0.11.0)

[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1221964/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1221965/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1221966/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
> Using the build "loot_0.11.0-32-g31af55b_dev" works, if that's any consolation.

In that case, closing this as fixed.

**Comment by umisery** [comment]
h

**Comment by WrinklyNinja** [comment]
That's probably because the plugin is corrupt

**Comment by umisery** [comment]
That seems to be the issue, which sucks. Thanks for the help.
