### ISSUE TITLE
Security warning from google when trying to download latest release

### ISSUE THREAD

**Issue by miltongq** [loot/loot#806]
I'm getting a security warning about phishing, from google, every time I try to download through the link: https://github.com/loot/loot/releases/download/0.11.0/LOOT.Installer.exe

**Comment by miltongq** [comment]
Browser: Google Chrome on windows 10, version 59.0.3071.115 64 bits

**Comment by miltongq** [comment]
It was probably a temporary issue, I can't reproduce it anymore.

**Comment by WrinklyNinja** [comment]
Well, if LOOT ever asks for your bank details or your email address, it's not a feature. :wink: 

I guess the URL was probably automatically blacklisted as a false positive by some automated process, then fixed, like how Kaspersky is convinced every new version of LOOT is malware...
