### ISSUE TITLE
Sorting does not disable all intended buttons

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#807]
I've updated to "loot_0.11.0-23-g922fb20_dev.7z", I noticed that once sorting did reorder the load order and I can choose between Apply and Cancel, not everything that is supposed to be disabled is actually getting disabled. For example see [here](https://abload.de/img/untitled16tzv1.jpg).

 In fact, I only see the Game Selecting dropdown and Refresh Content being disabled. Things that should also get disabled are, as far as I remember:
- Sort Plugins
- Update Masterlist

Arguebly the following ones could also be disabled:
- Redate Plugins
- Clear User Metadata
- Clear All User Metadata

Though these last three are also enabled with LOOT 0.11.0 and LOOT 0.10.3, but in my opinion they don't make much sense during this very moment where I want to Apply or Cancel my new load order.

**Comment by WrinklyNinja** [comment]
> Though these last three are also enabled with LOOT 0.11.0 and LOOT 0.10.3, but in my opinion they don't make much sense during this very moment where I want to Apply or Cancel my new load order.

They're not disabled because using them while sorting doesn't risk breaking LOOT's state like the others do. It's not really an "is this sensible" thing (and besides, someone may want to modify/clear their metadata while looking at the changes that it's made).

**Comment by WrinklyNinja** [comment]
Can you test again with [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-27-g5566904_ui-fixes#files)?

**Comment by pStyl3** [comment]
`loot_0.11.0-27-g5566904_ui-fixes.7z` has fixed this issue.
