### ISSUE TITLE
Unresponsive SOC filter

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#809]
Using "loot_0.11.0-23-g922fb20_dev.7z", the Show Only Conflicts filter seems to be unresponsive on the 1st attempt to use it. Say I want to use SOC for Plugin A .. instead of Plugin A's conflicting plugins I see an empty card list. Then I choose Plugin B to SOC with, but instead of Plugin B's conflicting plugins I see the conflicting plugins of Plugin A, And so forth.

**Comment by WrinklyNinja** [comment]
Can you test again with [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-27-g5566904_ui-fixes#files)?

**Comment by pStyl3** [comment]
`loot_0.11.0-27-g5566904_ui-fixes.7z` has fixed this issue.
