### ISSUE TITLE
Cramped columns in the metadata editor 

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#810]
Using "loot_0.11.0-23-g922fb20_dev.7z" .. are the columns in the metadata editor supposed to look like [this](https://abload.de/img/untitled2tqbt9.jpg), before a new row is opened? After that the editor looks [normal](https://abload.de/img/untitled3siawt.jpg).

**Comment by WrinklyNinja** [comment]
Can you test again with [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-27-g5566904_ui-fixes#files)?

**Comment by pStyl3** [comment]
`loot_0.11.0-27-g5566904_ui-fixes.7z` has fixed this issue.
