### ISSUE TITLE
The "Drop" part of Drag&Dropping plugins into the editor doesn't work

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#811]
Using "loot_0.11.0-23-g922fb20_dev.7z" - Drag & Dropping plugins into the editor does not seem to work. Nothing happens once I "drop" the plugins into the editor.

**Comment by WrinklyNinja** [comment]
Can you test again with [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-27-g5566904_ui-fixes#files)?

**Comment by pStyl3** [comment]
`loot_0.11.0-27-g5566904_ui-fixes.7z` has fixed this issue.
