### ISSUE TITLE
LOOT will not load any games for sorting

### ISSUE THREAD

**Issue by towman77** [loot/loot#814]
I started getting an error in the loot debug log right after the last windows 10 update. what can i do to fix this? [08:17:59.317961] [error]: Git operation failed. Details: -3; Object not found - no match for id (cb27931c7d449a129577def19237e9b894f4a9ed): libgit2 error

**Comment by WrinklyNinja** [comment]
Create a zip archive of your LOOT folder at `%LOCALAPPDATA%\LOOT` and attach it here, then delete the folder and see if that fixes your problem. It looks like one or all of your games' Git repositories were somehow corrupted.

**Comment by towman77** [comment]
yes it did fix it.
FYI: when this happened and i couldn't fix it i tried the extream. i purged
out steam, loot, and all games and mods then reinstalled all and still got
the same problem. not that savy with all this stuff but im wondering if the
download package my somehow be corrupted. just a thought.
