### ISSUE TITLE
Filters tab is not visible with dark theme

### ISSUE THREAD

**Issue by Freso** [loot/loot#815]
If using the dark theme and going to the "Filters" tab in the right-hand column, it will just show up as a white/light box. The GUI elements are still there, but everything is the same colour.

Build from commit 963c1414

**Comment by WrinklyNinja** [comment]
Ah yes, the dark theme is a bit broken now...

**Comment by WrinklyNinja** [comment]
@Freso can you confirm that [this build](https://bintray.com/wrinklyninja/loot/loot/0.11.0-30-g538883d_ui-fixes#files) fixes the issues you were seeing?

**Comment by Freso** [comment]
Yep, perfectly. 👍
