### ISSUE TITLE
Enhancement for to manually adjust load order for Skyrim

### ISSUE THREAD

**Issue by MikeMonse** [loot/loot#817]
To be able to manually adjust the load order of mods with in the program, for persons using SEEdit to modify their mods and then to be able to go back to auto to put the mods back in the correct load order! That would be very helpful! Nice Work on this program! It does solve load problems, that is for sure!

**Comment by WrinklyNinja** [comment]
I'm not interested in providing manual load order management features because there are already existing utilities (i.e. mod managers) that you can use to do that, and if you're using LOOT and SEEdit, you're probably using one already.

**Comment by Freso** [comment]
Also, you can already use "user metadata" for making local alterations to the load order sorting; see http://loot.readthedocs.io/en/stable/app/usage/editor.html
