### ISSUE TITLE
Load order failing to update

### ISSUE THREAD

**Issue by HeSoDead** [loot/loot#821]
i get this error when i try to update my games Load Order "Failed to sort plugins. Details: Cyclic interaction detected between plugins "Change Follower Outfits Redux.esp" and "Change Follower Outfits Redux -- Dawnguard.esp". Back cycle: Change Follower Outfits Redux -- Dawnguard.esp, Change Follower Outfits Redux.esp" and idea for a fix?

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
