### ISSUE TITLE
loot refuses to reconise fallout new vegas or any of its plugins when i uptated it to the newest version

### ISSUE THREAD

**Issue by CactusCoyote** [loot/loot#823]
when loot updated its self it completely broke and now refuses to see fallout Skyrim or any game, Ive installed it directly in to the games folders, the program files 86 folder the steam folder but nothing fixes loot

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
