### ISSUE TITLE
LOOT crashes when sorting any game

### ISSUE THREAD

**Issue by HamileRoo** [loot/loot#827]
Ive tried reinstalling it in different places, googling the problem and deleting the LOOT folder in %appdata%/Local but nothing has worked

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1341104/LOOTDebugLog.txt)

Heres the debug file
 plz help

**Comment by WrinklyNinja** [comment]
Have you tried using the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-40-gf1e4c4f_dev.7z)?

**Comment by HamileRoo** [comment]
How do you do that? I see no option to use it...
or am i just blind XP

**Comment by WrinklyNinja** [comment]
Can you actually access `F:\Steam\steamapps\common\Skyrim\Data\Update.esm`? It looks like an issue with filesystem permissions.

**Comment by HamileRoo** [comment]
Fixed it. I just needed to have steam Verify Integrity of Game Data and it replaced the broken files. Thanks for the help :)
