### ISSUE TITLE
Prerelease: No 'pressed' state for 'Apply' button

### ISSUE THREAD

**Issue by Silarn** [loot/loot#834]
For longer plugin lists, there is a significant delay between pressing the 'Apply' button and the completion of the plugins.txt writing.

With the prerelease, there is no 'clicked' appearance for the apply button or any other visual change to indicate that LOOT is processing.

It will eventually just finish with no other indication that it's doing anything.

**Comment by WrinklyNinja** [comment]
Which build are you running, and what do you consider significant?

**Comment by Silarn** [comment]
5-10 second delay

**Comment by Silarn** [comment]
I'm running the build that was posted: loot_0.11.0-46-g5dab82b_update-api.7z as well as my own build of the most recent commits of the update-api branch.

**Comment by WrinklyNinja** [comment]
Please supply your [debug log](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Ignore the bit about LOOTAPIDebugLog.txt, it is no longer used.

**Comment by Silarn** [comment]
I'll get this shortly...

**Comment by Silarn** [comment]
[CEFDebugLog.txt](https://github.com/loot/loot/files/1409726/CEFDebugLog.txt)
[Uploading LOOTDebugLog.txt…]()

**Comment by WrinklyNinja** [comment]
Hmm, how much time it takes to set the load order isn't currently logged. I'll add logging for that and let you know when a new build is available to try again with.

**Comment by Silarn** [comment]
I'll not that I didn't experience this delay with fo4 though the mod list isn't quite as long.

**Comment by WrinklyNinja** [comment]
The two games run exactly the same load order code, so that's surprising. How many plugins are in your FO4 load order?

**Comment by WrinklyNinja** [comment]
Can you try with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-67-gb2ef365_update-api.7z)? I've improved the performance of setting the load order (but that was ~120 ms to ~40 ms on a 1000-plugin load order, not several seconds).

**Comment by Silarn** [comment]
Sure, I'll take a look ASAP. It could be some strange conflict with MO. There are some VFS file handle issues we're looking into.

**Comment by Silarn** [comment]
I'm not sure how much it actually helps, but as you can see it's taking a long time to write the plugins.txt. I can't really say why... I hadn't experienced this issue in the past, and my FO4 load order seems to be writing much more quickly. (Both are included in this log.)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1424775/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
You mentioned MO, can you try dumping your plugins into the SSE data folder and running LOOT without MO to see if you get the same behaviour?

**Comment by Silarn** [comment]
I'll get to this as soon I can. It's definitely not just MO - as it does apply fairly quickly with FO4 / fewer mods in general. However, I can replicate this even running the last release of MO - and v0.11.0 also seems to apply quickly.

**Comment by WrinklyNinja** [comment]
You're not really comparing apples with apples though. MO has proven to be an intermittent and difficult to trigger source of problems before, so as far as I'm concerned no test involving MO is a valid test of LOOT's behaviour.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
