### ISSUE TITLE
N/A no masterlist present

### ISSUE THREAD

**Issue by Skyrimdragonborn** [loot/loot#836]
I dunno what to do. I already allowed access of loot in windows firewall, and now turned windows firewall off, turned off my anti virus. 
Error says "Oh no, something went wrong! you can check your lootdebuglog.txt (you can get to it through the main menu) for more information."

I HAVE NO IDEA WHAT TO DO WITH THIS >: 

[CEFDebugLog.txt](https://github.com/loot/loot/files/1414030/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1414031/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Well, you've done almost the right thing, but it would be best if you could enable debug logging and post the logs generated with it enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
