### ISSUE TITLE
Skyrim SE won't open! LOOT txt. files are included

### ISSUE THREAD

**Issue by OliverSkyrimReplay** [loot/loot#839]
So Skyrim SE was working fine, I had lots of mods already on and I wasn't even using LOOT (coz I had no idea load order was so important). Then I downloaded a few more mods, and left the game for a few hours, only to come back to the game no longer opening. 

To be more specific, it seems to me that on every first attempt to open Skyrim SE from Nexusmods app, the launcher loads up, but once you press "Play" on the launcher, nothing happens. Then the rest of your attempts to open from Nexusmods, absolutely nothing happens. Everytime you open the game from Steam though, again, the launcher opens, but won't go further, except it happens every time. I had a go at de-activating ALL my mods and launching Skyrim SE from Nexusmods and it worked, so it's definitely a MOD issue, I just can't figure out what exactly is causing it. 

After all that, I got LOOT and these are the warnings/errors etc. that it is giving me. Please helpppppppppppppp :( :( :( :(

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1438464/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1438465/CEFDebugLog.txt)

**Comment by pStyl3** [comment]
Which exact version of LOOT as well as Nexus Mod Manager do you use? Which Operating System do you use?

**Comment by WrinklyNinja** [comment]
```
[03:02:12.326801] [error]: Git operation failed. Details: -1; Received unexpected content-type: libgit2 error
```

Unexpected content-type suggests to me that something is intercepting the masterlist download and responding itself. Do you use a proxy?

**Comment by OliverSkyrimReplay** [comment]
I use Windows 10! Nexus Mod Manager 0.63.14 and LOOT 0.11.0

And does a VPN count?

**Comment by WrinklyNinja** [comment]
It might do, though if you're posting here from the same computer with the same connection that you're trying to run LOOT with, it's unlikely.

**Comment by OliverSkyrimReplay** [comment]
Okie, any suggestions anyone? :(

**Comment by pStyl3** [comment]
I would suggest to watch the following video:
[Skyrim Crash on Startup FIX : Part 1 (Troubleshooting your Load Order)](https://www.youtube.com/watch?v=cPwiY7NBVTM)

This video is for TES5Edit, but "xEdit" - as it is widely known - is TES4Edit, TES5Edit, SSEEdit, FO3Edit, FNVEdit and FO4Edit all in one (and thus the video applies even if your not modding classic Skyrim). For Skyrim Special Edition you will need to download the latest official version of SSEEdit, which can be found [here](https://www.nexusmods.com/skyrimspecialedition/mods/164).

You also could try one of the newer (also unofficial) snapshot builds of LOOT from [here](https://bintray.com/wrinklyninja/loot/loot#files), for example "loot_0.11.0-89-g8e2ca3a_update-api.7z".

Also, modding Bethesda games works best, if Steam/SSE/LOOT/NMM are not located in the C:\Program Files folders. If that's the case it might be worth a shot to move those to another folder not within said folder ( so e.g. C:\Games\ ).

**Comment by WrinklyNinja** [comment]
Yes, your modding problems are probably fairly unrelated to your problems using LOOT, just that LOOT could help pinpoint them if it worked...

**Comment by WrinklyNinja** [comment]
Try using the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-71-gb38ca13_dev.7z) instead, see if that works for you.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
