### ISSUE TITLE
[FO4] Loot Deactivating Plugins

### ISSUE THREAD

**Issue by KrimsonXG** [loot/loot#840]
Just earlier today I updated all my out of date FO4 mods via NMM and went to use LOOT to organize and find any errors. I used update masterlist then used the sort function when it spat out so many errors saying all my plugins weren't activated. I reactivated them via NMM and relaunched LOOT and repeated the process only to get about 10 mods deactivated again but no errors. Everytime I reactivate them in NMM and sort with LOOT the same ones get deactivated again. LOOT is also not sorting the mods load order in NMM as it normally does.

I'm using LOOT 0.11.0 (build 7976a4de) and NMM 0.63.14. I have also tried running both in Admin with the same problem.

**Comment by WrinklyNinja** [comment]
Which plugins get deactivated? Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by KrimsonXG** [comment]
The mods disabled are all the same everytime. After looking at them, it is all the mods that I updated/added minus the see through scopes Nuka World esp.

[Mods Disabled](https://pastebin.com/72Xw4kQq)

Here are the 3 files from the local folder as well.

[CEFDebugLog.txt](https://github.com/loot/loot/files/1442477/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/loot/files/1442478/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1442479/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Does [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-71-gb38ca13_dev.7z) work?

**Comment by KrimsonXG** [comment]
No, unfortunately. When I run the sort and hit apply the mods are deactivated as well. Within both versions the mods don't display a green check mark like all the other mods.

**Comment by WrinklyNinja** [comment]
Can you also post your plugins.txt after activating the plugins in NMM and after sorting with LOOT?

**Comment by KrimsonXG** [comment]
Alright, I think I found the problem. It seems to be tied to too many mods. I tried deactivating some of my other mods since the ones that were causing issues were my "new" ones and recently download/updated. Lo and behold LOOT picked up on them this time and was able to sort load order properly without deactivating mods. I guessing that there must be a LOOT setting to deactivate recent mods when reaching over a certain number. Maybe add in a message if people reach that number of mods?

Here is my plugin list anyway.
[Load Order.txt](https://github.com/loot/loot/files/1442604/Load.Order.txt)

**Comment by WrinklyNinja** [comment]
Oh, yes, you can only have up to 255 .esm/.esp plugins active, if you had
more than that it's not that LOOT was deactivating them so much as they
were never really active, and NMM was being misleading.

Adding a message sounds like a good idea but can't be done because it
happens at a lower level than LOOT itself is aware of. Really, NMM (or any
other mod manager) shouldn't let you 'activate' any plugins over that limit
in the first place.

**Comment by KrimsonXG** [comment]
I see. TBH I only tried this because I barely noticed the 10x10 pixel exclamation mark on the NMM in the corner.

Thanks for the assistance even if it was because of NMM.

**Comment by WrinklyNinja** [comment]
Closing this as it's been resolved.
