### ISSUE TITLE
tried to update Loot, got new problem (system error)

### ISSUE THREAD

**Issue by ducksause0x** [loot/loot#841]
Loot was working for me before I saw there was an update, so I tried to download it but it seemed to have frozen up during final installation. I shut down my computer after exiting the program. Now whenever I try to load up Loot, it doesn't start, only saying that the program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. I tried reinstalling multiple time, but it has the same result.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
