### ISSUE TITLE
Not opening/Event viewer shows error

### ISSUE THREAD

**Issue by SubSonix** [loot/loot#843]
LOOT v0.11.0 error. v0.10.3 works fine.

Faulting application name: LOOT.exe, version: 0.11.0.0, time stamp: 0x5916b39b
Faulting module name: ucrtbase.dll, version: 10.0.16299.15, time stamp: 0x9e3394c7
Exception code: 0xc0000409
Fault offset: 0x000933ab
Faulting process ID: 0x9bc
Faulting application start time: 0x01d3669f466374d0
Faulting application path: C:\Programs\LOOT\LOOT.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: 6648a4ee-dd62-40ab-94b6-fd7bc4793c13
Faulting package full name: 
Faulting package-relative application ID:

**Comment by WrinklyNinja** [comment]
Try the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-87-gfb7cbb6_dev.7z), see if that works for you.

**Comment by SubSonix** [comment]
That launched fine, thanks.
Just to add to my original post, It used to work fine on Win 10. I think the CU or FCU update broke it.
