### ISSUE TITLE
Loot Crash Upon Sorting Plugins

### ISSUE THREAD

**Issue by nevertah** [loot/loot#844]
I get a windows error in which it says loot.exe has stopped working when i try to sort plugins for TES5. any advice would be great.

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). Try the [latest snapshot build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.11.0-87-gfb7cbb6_dev.7z) first though, in case it's already fixed.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
