### ISSUE TITLE
install laucher won't run

### ISSUE THREAD

**Issue by helpsy** [loot/loot#845]
after downloading the loot installer i try to open the launcher to install the software but it won't open the window required to install it onto my system

**Comment by WrinklyNinja** [comment]
I can't replicate that, what OS are you on and did the v0.11.0 installer work for you?

**Comment by helpsy** [comment]
windows 10 and both worked on my old harddrive without any issues

**Comment by WrinklyNinja** [comment]
Have you checked if your antivirus has blocked the installer from running or something? Some antiviruses and other security software tend to flag every new release as malware.

**Comment by helpsy** [comment]
nope doesnt seem to be a anti virus issue or firewall issue were can i find earlier versions so i can see if they are the same

**Comment by WrinklyNinja** [comment]
[Here](https://github.com/loot/loot/releases/tag/0.11.0) is the v0.11.0 release page.

**Comment by helpsy** [comment]
ok is working now seems i needed to download that other requirement that needed to be on the system

**Comment by WrinklyNinja** [comment]
The MSVC redistributable? The installer is supposed to download that, but maybe the link changed or something so it doesn't work any more. Unfortunately that's not something I can test as I don't have a Windows machine without the dev tools installed.

**Comment by helpsy** [comment]
vc_redist.x86.exe had to download this one manually it was the only way for me to get it working i don't no why the installer didn't run but atleast thereis a work around if some one else has the same kind of issue

**Comment by vegacoyote** [comment]
If I may ask, where did you go to download vc_redist.x86.exe manually? This is the same thing my installer is getting hung up on, and the link on the latest release page is doing the same thing the installer is and timing out every time I try to download.

**Comment by WrinklyNinja** [comment]
You should be able to download it from [here](https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe), it's the same link as the installer uses though, so maybe there's some connectivity issue there for you.

**Comment by vegacoyote** [comment]
Thank you, that was it. I ended up having to save it to Dropbox via my phone, then download it to my PC from there. It's working now. :)

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
