### ISSUE TITLE
ESL-Flagged ESP with ESP masters prevents sorting

### ISSUE THREAD

**Issue by PhoenixTheSage** [loot/loot#847]
LOOT is reporting a cyclical error now that it detects ESL flags, when in fact it shouldn't, and will prevent the user from sorting their load order when it has file with the flag enabled and said file has ESP masters.

ESL-Flagged ESP's use the FE slot and merge at runtime like an ESL, but do not push ESP masters into Block 3 from Block 5 at runtime, like those with the .esl extension. This lets us benefit from the positive effect of ESL files, but currently LOOT doesn't recognize this and I assume is treating them like any other master file.

**Comment by WrinklyNinja** [comment]
What version of what game is this with? The ESL stuff has changed several times and I've gotten quite confused as to the current state of things. If only Bethesda produced patch notes... 😞 

Also, what is the positive effect of ESL-flagged ESPs?

**Comment by PhoenixTheSage** [comment]
Latest version of both I believe, but reported on FO4 1.10.40

ESL-flagged ESP's still use the FE slot and don't hit the 255 limit just like ESL extensions, but they don't shuffle the masters up to the ESM Block 3 area. If you were to use a ESL-flag and ESL extension together, and the file had a ESP master, the master could load AFTER the ESL but then get pushed to Block 3 when saving the game. 

ESL-Flagged ESP's still bypass the limit but do not shuffle their masters like they themselves are a master file, loading everything in the order on runtime as intended except for taking up the FE slot by force.

**Comment by pStyl3** [comment]
@PhoenixTheSage Where exactly do you have your information from? Can you link to a source?

**Comment by PhoenixTheSage** [comment]
https://afkmods.iguanadons.net/index.php?/topic/5079-plugin-files-and-you-esmeslesp/&
https://www.creationkit.com/fallout4/index.php?title=Data_File

**Comment by WrinklyNinja** [comment]
I'm concerned that this behaviour is something that Bethesda will patch out, as it's inconsistent with the interplay of other combinations of flags and file extensions, and goes beyond the use-case for ESLs. It seems a bit dangerous to be taking advantage of. Why not just use a regular ESP instead of hacking around with an edge case?

**Comment by PhoenixTheSage** [comment]
Not sure what you mean regarding the use-case, but I certainly hope they don't patch it out.
It'll be extremely useful for small mods and patches in the long run...unless everyone wants to continue relying on merging ESP's which is finicky a lot of the time.

**Comment by WrinklyNinja** [comment]
@PhoenixTheSage: Can you try replacing the `loot_api.dll` in your LOOT install with the one in [this archive](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.12.1-3-g6432d32_false-flagged-light-esp-win32.7z) and let me know if it works how you want?

**Comment by PhoenixTheSage** [comment]
@WrinklyNinja Nice thanks, no more cyclical error. 
Although, they have this message: https://imgur.com/a/SfYNq

**Comment by WrinklyNinja** [comment]
[This build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.1-7-g813f479_light-master-esp.7z) should get rid of those errors for light master .esp files, though you'll have to replace its `loot_api.dll` as before.

**Comment by PhoenixTheSage** [comment]
Aight, plugin warnings are gone, but when trying to apply the sort I get this: https://imgur.com/a/KuuVu

**Comment by WrinklyNinja** [comment]
Great, closing this as fixed then.
