### ISSUE TITLE
Skyrim is Windy "SkyrimIsWindy - EVT patch.esp" need to be placed before "SkyrimIsWindy.esp"

### ISSUE THREAD

**Issue by hcr99** [loot/loot#848]
ENGLISH: Skyrim is Windy "SkyrimIsWindy - EVT patch.esp" need to be placed before "SkyrimIsWindy.esp" because the trees are textured incorrectly, is the only error of loot in this mod for the moment...
-EXAMPLE Load Order:
Mods...
SkyrimIsWindy - EVT patch.esp=LO 62
SkyrimIsWindy.esp=LO 63
More moods...

sorry for my bad english

ESPAÑOL: Skyrim is Windy "SkyrimIsWindy - EVT patch.esp" necesita ser situado antes del archivo main "SkyrimIsWindy.esp" porque los arboles dan error en textura.
-EJEMPLO de oden de carga
Mods...
SkyrimIsWindy - EVT patch.esp=LO 62
SkyrimIsWindy.esp=LO 63
Más moods...

Solution are like this

![sin titulo](https://user-images.githubusercontent.com/34358120/33747527-c346179e-db80-11e7-9439-6c05d7fadad3.png)

**Comment by WrinklyNinja** [comment]
Is this for Skyrim or Skyrim SE?

**Comment by hcr99** [comment]
is skyrim legendary edition, the normal
