### ISSUE TITLE
"Forbidden"

### ISSUE THREAD

**Issue by BlakeQuiet** [loot/loot#849]
I've consulted Google but I got jack squat. (No Google is not my best friend) But whenever I attempt to Download the LOOT installer, it will first up with a Network Error then upon retrying I'm struck with "Forbidden" I'm going to need help or I'm not going to be moving forward anytime soon.

**Comment by WrinklyNinja** [comment]
I can't replicate this, the installer is hosted on GitHub (via AWS) so is pretty highly available, and has 20,000 downloads so far, there's not really anything I can do about it. Have you tried downloading the installer from [Nexus Mods](http://www.nexusmods.com/skyrimspecialedition/mods/1918/)?

**Comment by BlakeQuiet** [comment]
I'll attempt to.

**Comment by BlakeQuiet** [comment]
May I have a link?

**Comment by BlakeQuiet** [comment]
Disregard the spammy comments, I finally got my internet back. 
So every time I check, Nexus. I get the Skyrim SE LOOT
