### ISSUE TITLE
Error with Skyrim HighResTexturePack ESPs disabled

### ISSUE THREAD

**Issue by olwince** [loot/loot#855]
Version 0.12.1 (build 46956175)

In Mod Organizer 1x, with "have MO manage archives" enabled
Have HighResTexturePack0x.esp disabled/hidden

1. Run LOOT through MO
2. Parsing dialog appears
3. Settings dialog appears, close by clicking Apply or Cancel without changing anything
4. Error Message: "Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information."
5. No Plugins are displayed 
6. Debug log ends with: [error]: No plugin "HighResTexturePack01.esp" exists.

[Debug Log](https://drive.google.com/open?id=1sGDH_olmHsE4A0fJDGPxtLK5PvHxEt_s)

Runs normally by enabling HighResTexturePack ESPs in MO before running LOOT, and then disable them after closing LOOT. 

Other MO managed BSAs (dummy ESPs disabled) seem to not cause the same result. For example, LOOT runs normally with "Unofficial High Resolution Patch.esp" disabled.

**Comment by WrinklyNinja** [comment]
Running LOOT through Mod Organiser is unsupported, as

1. Mod Organiser itself is unsupported
2. Most issues reported by Mod Organiser users are caused by Mod Organiser, which I can't do anything about.

Please try to replicate your issue while running LOOT independently of Mod Organiser.

**Comment by olwince** [comment]
Understood regarding unsupported status of MO. 
 
I cannot replicate outside of MO by moving or renaming those ESPs.

**Comment by GrantSP** [comment]
Sorry but there is no inherent fault with running LOOT via MO 1.3.11.
Whilst it may be true that @Tannin, the developer of MO, is no longer maintaining it, it would be a mistake to say MO is unsupported. There is a team of developers working on the MO2 code and they are also able to give feedback about any code issues.
This however appears to be an issue on the user's side as 1000's use MO and LOOT together and don't report this behaviour.
I see you have posted on the STEP forum also, I'll continue offering suggestions there.

**Comment by WrinklyNinja** [comment]
I'll update my canned response then, I wasn't aware others had picked MO up.
