### ISSUE TITLE
Sidebar indices don't update when sorting

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#859]
Reported by pStyle [here](https://afkmods.iguanadons.net/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=171057) and replicated.

**Comment by pStyl3** [comment]
This issue also occured roughly a year ago and was tracked in #686

**Comment by WrinklyNinja** [comment]
Should be fixed in [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.1-12-gb35ad29_fix-sidebar-indices.7z).

**Comment by pStyl3** [comment]
It seems to be fixed, yes.

**Comment by WrinklyNinja** [comment]
Closing as fixed in b35ad29ffad22a84aad5b427970714f1210c6ddf then.
