### ISSUE TITLE
[Application Issue] LOOT crashes when sorting

### ISSUE THREAD

**Issue by jakegallant** [loot/loot#860]
So my Fallout 4 game crashes upon loading, no matter how I try to start it (run as administrator, start through Nexus mod manager, etc). I've attempted to rectify the issue through LOOT, and have managed to tend to every issue that causes a warning message. Though somewhere in the process of my rectifying issues with DLC deleted references and whatnot, the sorting function on LOOT Became inoperable.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1590061/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1590065/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
```
[16:34:23.424369] [error]: libloadorder failed to set the load order. Details: Access is denied. (os error 5)
[16:34:23.424369] [error]: libloadorder failed to set the load order. Details: Access is denied. (os error 5): Libloadorder error
```

Check that your plugins.txt is not read-only. Also, is LOOT actually crashing, or is sorting failing with an error dialog box?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
