### ISSUE TITLE
LOOT Install Error

### ISSUE THREAD

**Issue by abermuffin** [loot/loot#861]
I made an imgur album of the 3 error boxes I receive, in the order I receive them:
https://imgur.com/a/obPRR

When I go into Regedit, I am unable to find this specific registry file. It doesn't exist. Running install as admin makes no difference.

**Comment by WrinklyNinja** [comment]
LOOT's installer doesn't do anything unusual when creating the start menu and registry entries, it's just using the standard methods that Inno Setup provides. Whether it's a problem with Inno Setup or something going on with your PC, I can't really do anything about this issue.
