### ISSUE TITLE
Exception while executing query: std::bad_alloc

### ISSUE THREAD

**Issue by raehik** [loot/loot#862]
Running the latest Bintray Linux builds, I immediately receive an error message upon closing the initial settings screen. I'm able to set a game install directory and download a masterlist (for Oblivion in this case) and the log shows that my plugins are found, but sorting plugins gives the same `std::bad_alloc` error and it doesn't succeed.

Upon startup:

    [00:31:45.277688] [trace]: Getting masterlist metadata for: Oblivion.esm
    [00:31:45.278811] [error]: Exception while executing query: std::bad_alloc

After trying to sort plugins:

    [00:31:55.081934] [trace]: Getting and evaluating metadata for plugin Bashed Patch, 0.esp
    [00:31:55.082039] [error]: Failed to sort plugins. Details: std::bad_alloc
    [00:31:55.085569] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Failed to sort plugins. Details: see general messages for details.

I'm on Arch Linux x86_64. `libloot_api` complains about `libcurl-gnutls` missing version info but masterlist downloading works just fine, so I assume that's not the problem. Running with `./LOOT --no-sandbox --game-appdata-path=test`.

I'd test with a build from source, but I get an immediate segfault. Is there any way to uncover what this `std::bad_alloc` might be about?

  * [LOOTDebugLog.txt](https://github.com/loot/loot/files/1594894/LOOTDebugLog.txt)
  * [CEFDebugLog.txt](https://github.com/loot/loot/files/1594895/CEFDebugLog.txt) (common CEF error which seems to affect nothing)

**Comment by WrinklyNinja** [comment]
I'll test the latest build out on my Ubuntu install when I next boot into it. What happens if you try just downloading the masterlist without sorting?

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
