### ISSUE TITLE
Bad Image

### ISSUE THREAD

**Issue by RugRatRew** [loot/loot#863]
---------------------------
LOOT.exe - Bad Image
---------------------------
C:\WINDOWS\SYSTEM32\MSVCP140.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f. 

How do I fix this? I can't use to program!

**Comment by WrinklyNinja** [comment]
Try reinstalling the x86 MSVC 2015 Redistributable.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
