### ISSUE TITLE
Mod list error

### ISSUE THREAD

**Issue by jake21001** [loot/loot#864]
I have a couple of mods that recommended the loot system that required the "unofficial Skyrim legendary edition" and "better quest objectives". the loot system is telling me I don't have them installed when I have them in both the steam workshop menu and Skyrim script extender

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). I'll need your debug logs to see what's going on.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
