### ISSUE TITLE
None of the supported games were detected.

### ISSUE THREAD

**Issue by XiuLan123** [loot/loot#867]
After I move my Skyrim to C:\Skyrim loot can no longer find the game folder, I was trying to change the Install path by my own, but is not work.

**Comment by WrinklyNinja** [comment]
Could you post the contents of your `%LOCALAPPDATA%\LOOT\settings.toml`? Your [debug logs](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) would also be helpful.

**Comment by XiuLan123** [comment]
@WrinklyNinja After I uninstall Loot and use ccleaner to clean up all the settings and reinstall it works again, but still thank you!

**Comment by WrinklyNinja** [comment]
OK, closing this then.
