### ISSUE TITLE
adding fallout 4 vr support

### ISSUE THREAD

**Issue by Djones4822** [loot/loot#869]
with fallout 4 vr out for over a month and mods popping up, will loot ever be updated to incorporate the new game? 

Especially since Nexus Mod's new tool "Vortex" relies entirely on Loot to determine load order

**Comment by WrinklyNinja** [comment]
I don't see why not.

**Comment by Djones4822** [comment]
It runs identically to Fallout 4, the VR aspect seems to have been created as an addon to the existing game. Enough so that there's a system for merging the similar files resulting in a much smaller overall fileset. 

What's ended up happening is that Nexus added VR as a sub-set of Fallout4. However, a vast majority of non-f4se dependent mods work and have been in use widely. 

The game itself works with windows MR and occulus, though it's a bit of a workaround from what I understand.

**Comment by WrinklyNinja** [comment]
In which case it may just be enough to know what the game's `%LOCALAPPDATA%` folder and registry key are, and LOOT can re-use the FO4 settings for everything else.

**Comment by Djones4822** [comment]
I'll work on finding that for you tonight. 

I'm willing to be it's nearly identical to the FO4 locations as it has been with everything else in my experience.

**Comment by Djones4822** [comment]
Are we trying to update the game_settings.cpp file to include the fallout4vr info in the construction from line 40-80? 

I would assume we also need a fallout4vr masterlist as well, no?

If so, then I would assume we just need to add something like

`  } else if (Type() == GameType::fo4vr) {
    name_ = "Fallout 4 VR";
    registryKey_ = "Software\\Bethesda Softworks\\Fallout4VR\\Installed Path";
    lootFolderName_ = "Fallout4VR";
    masterFile_ = "Fallout4VR.esm";
    repositoryURL_ = "https://github.com/loot/fallout4vr.git";
  }
`
obviously adding the fallout4vr git right? 

But scanning my registry, I don't have that Software\\Bethesda Softworks\\... folders for any of my bethesda games. I only have these:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 611660
Computer\HKEY_CURRENT_USER\Software\Valve\Steam\Apps\611660
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Fallout 4 VR

My appdata is C:\Users\{user}\AppData\Local\Fallout4VR\

Is any of this helpful?

**Comment by WrinklyNinja** [comment]
> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Fallout 4 VR

That's the one I need - the `WOW6432Node` bit is a 32-bit/64-bit thing, LOOT hardcodes the 32-bit key and knows to ask for the corresponding one on 64-bit systems, which is why you couldn't find any of the hardcoded keys.

> Is any of this helpful?

Yes, I'll post a link to a build once I've made the changes with that info.

**Comment by Djones4822** [comment]
That's incredible, thank you so much! 

I know the VR community is tiny compared to the rest of the application's audience, but know that we all really appreciate it.

**Comment by WrinklyNinja** [comment]
Hmm, this will need changes all the way down to libloadorder, as it defines the games' local app data folder names, and while they can be overridden, LOOT doesn't provide a way to do so on a per-game basis...

If you launch LOOT with the `--game-appdata-path=C:\Users\{user}\AppData\Local\Fallout4VR\` parameter, it'll override the game's local app data path globally, which should be good enough to get LOOT working without any code changes, though you might also need to open the settings and add a game definition with the right registry key / path (just make sure the base game is set to Fallout 4).

Try that, see if you can then sort your FO4VR plugins.

**Comment by Djones4822** [comment]
That seemed to work, including the parameter and setting up the game worked fine using the fallout4 masterlist. Sorting also seemed to work, except for some reason my notepad isn't show the linefeeds, but opening it in notepad++ shows they're there... not sure what's going on. 

Will this work without running the `--game-appdata-path` parameter at start? 

We'll also need a seperate masterlist too, right?

**Comment by Djones4822** [comment]
> Notepad doesn't support Unix line endings, but they don't cause a problem with the game.

Sorry, I had it backwards in my head for some reason

> No, without it LOOT will use %LOCALAPPDATA%\Fallout4 when reading/writing load order, and with it LOOT will use its value for every game, so don't try using LOOT for other games with it set.

Okay, I see. So for now I've got a bat script that launches loot with that parameter specifically for fo4vr and then when I want to sort a different game I'll use the

**Comment by Djones4822** [comment]
sorry misclicked close and comment

**Comment by WrinklyNinja** [comment]
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.1-16-g2700101_fallout4vr.7z). I've removed the `--game-appdata-path` parameter and replaced it with a per-game setting. It's not in the GUI, but if you run LOOT, close it, then open up your `%LOCALAPPDATA%\LOOT\settings.toml`. Find the `[[games]]` block that matches your FO4VR install, and set its `local_path` to what you were using for `--game-appdata-path`.

**Comment by Djones4822** [comment]
Each time I open it I need to add Fallout4VR as a game again and the `settings.toml` is reset. 

1. Open new LOOT
2. Add Fallout 4 VR as a game
3. Close Loot
4. Open `settings.toml`
5. add local directory for fo4vr, fo4, fonv, sse
6. Open LOOT
7. Fo4vr is not added, settings.toml is reset back to pre-local specification

**Comment by WrinklyNinja** [comment]
I can't replicate that. I can get the `local_path` values to be emptied if I apply settings in the GUI and then close LOOT though.

**Comment by WrinklyNinja** [comment]
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.1-17-gde55b18_fallout4vr.7z).

**Comment by Djones4822** [comment]
That build is working for me now, but it's not determining the correct load order. 

For example I put "Craftable Ammo - Plus.esp" at the top "Craftable Ammo.esp" at the bottom and it's making no changes. Is that expected with this build?

**Comment by WrinklyNinja** [comment]
I expect it to behave the same way for FO4VR as it (and previous builds) does for FO4. I don't know anything about Craftable Ammo, I can't say what LOOT should or shouldn't be doing with it.

**Comment by Djones4822** [comment]
Seems to be working then, it's found the game again and preserved the settings between sessions and is managing the plugins. 

Switching between games and coming back also works.

Looks good!

**Comment by WrinklyNinja** [comment]
I'm going through adding proper support for FO4VR now, I need some more information to do so. Could you please:

- upload your `Fallout4.ccc` file (or maybe it's `Fallout4VR.ccc`) that's in your Fallout 4 VR game directory?
- post a list of the official .esp / .esm / .esl plugins that were installed with the game?

**Comment by Djones4822** [comment]
There is no .ccc file in the fallout4 directory. Looking at the fallout4.ccc file in the original directory leads me to think it's creation club content? If so, fallout4vr does not have official support for CC. Let me know if I should do anything more there. 

The list of esp/esms is simply:

- Fallout4.esm
- Fallout4VR.esm

Nothing else was included in the base installation. DLC's are compatible with mods to patch bugs, but otherwise not included - they must be copied over from the basegame's data directory.

**Comment by WrinklyNinja** [comment]
> There is no .ccc file in the Fallout4VR installation directory. Looking at the fallout4.ccc file in the original fo4 directory leads me to think it's creation club content?

Good to know, and yes, it's related to the creation club.

**Comment by Djones4822** [comment]
I'm sorry the vr esm is Fallout4_VR.esm, i've edited it above as well. My mistake.

**Comment by WrinklyNinja** [comment]
I don't think a separate masterlist is necessary, I'm setting the default to be the FO4 masterlist pretty much for the reasons @pStyl3 has given.

**Comment by WrinklyNinja** [comment]
@Djones4822 can you try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.1-20-g523e482_fallout4vr.7z) and let me know if it works or not? It adds a Fallout 4 VR game type that uses the correct game-specific data, so you don't have to edit the local_path of a Fallout 4 entry to get it recognised.

**Comment by Djones4822** [comment]
>Nexus doesn't feature the VR version as a seperate game but provides now the new VR tag as a "mod category" on Nexus. Plus, as of writing this comment, there are a total of 29 VR mods listed with this VR tag.

While true,  there are over 260 mods confirmed working from original fo4 out of around 320 that have been tested by the community. My concern as been that as mods specific for VR come out that attempt optimizations and improvements I worry that dependencies and metadata may change. I've reached out to the Nexus admins about a better way to organize compatibility with VR which may change how that all looks in the future. 

But i'm fine with all that as it is now, I doubt there will be any problems in the near-term.

The current build seems to work great. Been trying to break it and haven't run into any problems!

**Comment by pStyl3** [comment]
Have you a source for that information? What about those other 60 mods? Where they definitely not working on VR? Or was compatibility simply not prooven or untested?

**Comment by Djones4822** [comment]
https://docs.google.com/spreadsheets/d/1xz4VSYQYlGXxUEuHXdN4yF44x72nm_8EshPVkbzKcSk/edit#gid=1245599248

That's the "masterlist" of testing results so far.

**Comment by WrinklyNinja** [comment]
OK, closing this since FO4VR support is merged as of c4a0ffbb60e12f379fcaf1ab71bc2b3baf5d179c. I'll probably do a release in the next few days.

**Comment by Djones4822** [comment]
Thanks so much for working so quickly! Hopefully when SkyrimVR launches this fall we can do something similar
