### ISSUE TITLE
Loot stopped working with no changes done to MO2 or load order

### ISSUE THREAD

**Issue by Pelzdev** [loot/loot#870]
Started giving "invalid string" error and shutting down.

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by selsie** [comment]
Did you try deleting the directory and doing a fresh install of Loot? If you use the same directory as you did before, you won't even need to change things in MO

**Comment by millmill12345** [comment]
As far as I have confirmed, LOOT crashed on loading/ user metadata. Other process are no issue. This issue could not be confirmed on 12.0 ~ 12.3. This is apparently only 12.4's issue.

**Comment by WrinklyNinja** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
