### ISSUE TITLE
Loot don't want to start...

### ISSUE THREAD

**Issue by Sebatien** [loot/loot#871]
Hey man, Since the newer version of loot , my loot doesn't want to start, i tried to reinstall him in a other directory but nothing change.Can you help me please ?

Thanks you

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by WrinklyNinja** [comment]
Also, this may have the same probable cause as #873, what's your user directory?

**Comment by Sebatien** [comment]
C:\Program Files (x86)\LOOT

**Comment by WrinklyNinja** [comment]
That's your LOOT install directory, your user directory is C:/Users/someone, I'm asking what someone is for you.

Also try the build linked to at the bottom of  #873, it may fix your issue.

**Comment by Maldedo** [comment]
Hi, I'm having the same problem as Sebatien. My user folder has an ''é'' in it and the links in #873 give me a 404 error. I also saw that the command --loot-data-path=C:\LOOT could fix it but I am new to all of this and I have no idea where to put that command. Would you mind giving more explanation or a functioning link please?

Thank you for your help

**Comment by WrinklyNinja** [comment]
Whoops, I forgot those builds would be deleted. Try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.2-2-g457899a_dev.7z).

**Comment by Maldedo** [comment]
This one works, awesome! Thanks for your help and have a great day!

**Comment by WrinklyNinja** [comment]
Closing this as it's probably fixed in 0.12.3.
