### ISSUE TITLE
[FO4] Using Vortex (meh) and it's giving me set error: elements must be unique note

### ISSUE THREAD

**Issue by twist3dimages** [loot/loot#872]
![image](https://user-images.githubusercontent.com/33134502/35890449-d45b1968-0b6d-11e8-9014-3357b6b72d4b.png)

Vortex is fucking up the DLC list ordering so I'm assuming that's what this is (I'm trying to sort the UOF4 patch after NukaWorld)

![image](https://user-images.githubusercontent.com/33134502/35890488-f6e112a8-0b6d-11e8-9bd6-53e7abadac69.png)

**Comment by twist3dimages** [comment]
I realize there are other things that shouldn't be loaded before the unofficial patch but that's Vortex for ya...

**Comment by twist3dimages** [comment]
Is it possible that my DLCList.txt is messed up? 
[DLCList.txt](https://github.com/loot/loot/files/1701223/DLCList.txt)

**Comment by twist3dimages** [comment]
Also,
 I didn't realize New Calibers showed as an esm-marked esp

![image](https://user-images.githubusercontent.com/33134502/35891258-599778bc-0b71-11e8-828a-41c8e3616167.png)

**Comment by pStyl3** [comment]
Since this is related to Vortex: @TanninOne

**Comment by WrinklyNinja** [comment]
I don't know anything about Vortex or how it is using LOOT, but it looks like there's invalid metadata. The FO4 masterlist's CI isn't showing any errors, so I guess this is user metadata? If you know where it stores the metadata it passes to LOOT, posting it may be useful.

**Comment by twist3dimages** [comment]
@WrinklyNinja what would the metadata look like?

**Comment by WrinklyNinja** [comment]
It would be YAML, probably stored in a .yaml or .yml file somewhere in wherever Vortex stores its data.

**Comment by TanninOne** [comment]
First of all: apologies for the note in that screenshot about looking for help on loot.github. This note was only on during the limited release and is not in the current versions.

Vortex saves its own userlists here: C:\Users\<username>\AppData\Roaming\vortex\fallout4\userlist.yaml

I think this error has been fixed, it hasn't been reported after Vortex 0.12.7

**Comment by WrinklyNinja** [comment]
Thanks for the info 👍

**Comment by twist3dimages** [comment]
It was working fine now it's doing it again :( should I post my meta info

**Comment by twist3dimages** [comment]
Here's my .yaml file

[userlist.zip](https://github.com/loot/loot/files/1731746/userlist.zip)

**Comment by TanninOne** [comment]
There are two rules "AkaSingersWardrobe.esp after AkaSinger" and two rules "SPAWN ITEMS - VIS.esp after spawn items.esp"

Can you remove one of each rule from the vortex ui?

**Comment by twist3dimages** [comment]
Actually now that I think about it, I added those rules before Vortex became public. They aren't set in Vortex anymore and SPAWN ITEMS - VIS isn't even installed anymore. Look at the modified date.

![image](https://user-images.githubusercontent.com/33134502/36316424-471ff1d4-1308-11e8-9006-fc2c8b06a6af.png)


userlist.yaml file? Or the entire Vortex folder and reimport everything?

**Comment by twist3dimages** [comment]
I think something happened to the profile. It's marked as read-only now and the files inside were last modified 2 days ago (with plugins I don't have installed anymore).

![image](https://user-images.githubusercontent.com/33134502/36316679-ea38a118-1308-11e8-8d5d-efcc95713558.png)

**Comment by TanninOne** [comment]
It doesn't really matter, Vortex will still use the same userlist.yaml, there was no reset when it became public.

But since you don't have the esp any more, the UI won't give you a way to remove the rule. 
I'll just attach the fixed file.
[userlist.zip](https://github.com/loot/loot/files/1731933/userlist.zip)

Now for anything else, please post an issue in the  Vortex repo or through feedback, we're still in the loot repo. ;)

**Comment by twist3dimages** [comment]
THANK YOU I LOVE YOU

**Comment by twist3dimages** [comment]
I'll let you know if it works

**Comment by WrinklyNinja** [comment]
Closing this as it's been resolved.

**Comment by twist3dimages** [comment]
Still not working. If I delete everything in that file will I be fine?

**Comment by twist3dimages** [comment]
Think I'm going to try and start the import over
