### ISSUE TITLE
Freshly updated LOOT generates empty error logs

### ISSUE THREAD

**Issue by MaulMachine** [loot/loot#874]
Hello,

I was using LOOT to sort my Fallout: New Vegas plugins, and whenever I tried to update the masterlist, it spat out an error box saying to check LOOTDebugLog.  When I opened said document, it was blank.  My changes were not applied.

Thanks.

**Comment by MaulMachine** [comment]
And now it works perfectly, despite literally nothing changing.

Thanks anyway.

**Comment by WrinklyNinja** [comment]
Which version did you update from?

**Comment by MaulMachine** [comment]
1.2.   I got it working through a simple reinstall, then closing all active programs and trying again.

**Comment by WrinklyNinja** [comment]
There is no LOOT v1.2...

**Comment by MaulMachine** [comment]
It was a typo, I meant 12.2.

**Comment by WrinklyNinja** [comment]
I'm confused. 0.12.2 is the latest version of LOOT, what version of LOOT were you using before you upgraded to it?

**Comment by MaulMachine** [comment]
Okay.  I was using 0.12.0, I upgraded to 0.12.2, and after reinstalling it and closing all my other programs, I got it to work.  I did not have it running when I opened the log and found it empty.

**Comment by SuperSandro2000** [comment]
I had the same problem. Delete C:\Users\Sandro\AppData\Local\LOOT and it should work after a restart. maybe a config conversion problem.

**Comment by WrinklyNinja** [comment]
I think I've fixed this in 0.12.3, but I was unable to replicate it. If it's still happening, this can be reopened.
