### ISSUE TITLE
Could not load cef_extensions.pak

### ISSUE THREAD

**Issue by SuperSandro2000** [loot/loot#875]
When running Loot 0.12.2 if generates this error in CEFDebugLog.txt:
[0210/150706.784:ERROR:main_delegate.cc(713)] Could not load cef_extensions.pak

I don't think this has any negative impacts on my experience but maybe still worth mentioning.

**Comment by WrinklyNinja** [comment]
[It's harmless](https://loot.github.io/docs/help/LOOT-FAQs.html#cef-extensions-error)

**Comment by SuperSandro2000** [comment]
Oh my bad. Did not check the FAQ and it probably should be removed then.
