### ISSUE TITLE
Loot GameDir not empty crash

### ISSUE THREAD

**Issue by SuperSandro2000** [loot/loot#877]
`[11:19:12.514169] [error]: Exception while executing query: Git operation failed. Details: -4; 'C:\Users\Sandro\AppData\Local\LOOT\FalloutNV' exists and is not an empty directory: libgit2 error`
C:\Users\Sandro\AppData\Local\LOOT\FalloutNV is just filled with loadorder backups. Maybe Loot should clean them/ignore them and operate normal.

**Comment by WrinklyNinja** [comment]
Please post your full debug log.
