### ISSUE TITLE
Add more detail to UI error message when setting the load order fails

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#879]
It's the most commonly-reported issue, and it's always (?) been due to plugins.txt being read-only, so it seems sensible to add a "check that your plugins.txt is not read-only" bit to the UI's "Oh no, something went wrong!" message.

**Comment by SuperSandro2000** [comment]
Just as a thought. If the plugins.txt is outside of program files is it possible to remove the read only?

**Comment by WrinklyNinja** [comment]
Yes, but I don't think LOOT should be doing so on the basis that some other program probably set it for a reason, e.g. a "lock load order" feature.

**Comment by SuperSandro2000** [comment]
Maybe as an "emergency" button is the user did not use such feature and maybe the launcher set it read only by accident

**Comment by WrinklyNinja** [comment]
I'd rather not have UI elements that are just for handling a special case error, especially since there's no practical way to be sure that the reason for the write failure was due to the read-only flag on the file. I think it's much better to say "this is probably why you're having a problem" than to give the user a "fix this" button that may not work.

**Comment by WrinklyNinja** [comment]
Done in 1fdf9c8f2a84571e17e325bc45de2944bf2364fd.
