### ISSUE TITLE
Masterlist name matching?

### ISSUE THREAD

**Issue by TanninOne** [loot/loot#880]
This is not a bug report, just a question:
I've seen masterlists (i.e. skyrim) containing regular expressions for matching plugin names like this:
> name: Expanded Towns.*\.esm

However in the Fallout 3 masterlist there are entries like this:
> Xepha''s Dynamic Weather - Weather Machine (+Rain).esp

which, if interpreted as a regular expression would be illegal since the braces would represent a group and a + (repeat 1 or more time) can't be at the start of a group.

So I was wondering: How does loot handle these, does it have some logic to decide if it's an exact match or re?

**Comment by WrinklyNinja** [comment]
It's treated as regex if it contains any of `:\*?|` ([reference](https://loot-api.readthedocs.io/en/latest/metadata/data_structures/plugin.html)) as they're invalid in Windows paths.

**Comment by TanninOne** [comment]
Perfect, thank you.
