### ISSUE TITLE
The new LOOT masterlist updating is indirectly conflicting with another game I play. 

### ISSUE THREAD

**Issue by phireblast** [loot/loot#900]
Upon the masterlist updating change, I've been getting an error that prevented me from updating my masterlist and sorting my load order(something about a libgit2 error) in LOOT. After some searching, the only fix for me was to install a windows 7 update to enable TLS 1.1 and 1.2 as default secure protocols.(https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in). This fixed the issue. However, due to this update, I am now unable to launch FFXIV due to the whole change. So if I wanted to play FFXIV ever again, I would have to undo the update since I cannot find a solution to the error code that game gives on google.

Any ideas? Going back to older updates do nothing. It's either system restore to before and retain my ability to play FFXIV and not be able to sort my load order in Skyrim, or apply the update and not be able to play FFXIV.

**Comment by WrinklyNinja** [comment]
I suspect that in the process of enabling TLS 1.1 and 1.2, you disabled whatever older encryption protocol FFXIV is depending on. From that article, what values do you have from your `DefaultSecureProtocols`  and `SecureProtocols` Registry keys?

As an aside, the only thing about masterlist updating that changed was that GitHub started enforcing a TLS 1.2 requirement and in their infinite wisdom Microsoft decided that the safest encryption protocol shouldn't be enabled by default. Nothing about LOOT actually changed, it's just one of many programs caught in the middle.

**Comment by phireblast** [comment]
SecureProtocols(or at least what I could find of it): http://puu.sh/zwYoa/19086fcf8d.png

DefaultSecureProtocols: http://puu.sh/zwYks/534008c426.png

**Comment by WrinklyNinja** [comment]
Try setting `DefaultSecureProtocols` to `A80` too so that TLS 1.0 is enabled by default.

**Comment by phireblast** [comment]
That didn't work, unfortunately.

**Comment by arkayn71** [comment]
I tried installing the above update on my system and restarting and I still get the libgit2 error and it was initially crashing LOOT as well.

My temporary solution is the turn off the check for the new masterlist and manually update it until I can figure out why my system does not want to use TLS.
Looking at Regedit, it looks like that patch did nothing.

**Comment by WrinklyNinja** [comment]
> I would try that, but since my PC deleted my restore point, i'm pretty much stuck with not being able to play FFXIV until further notice. So basically, I can mess with loot again, just not under ideal conditions.

If you're on a 64-bit version of Windows 7, there are 4 Registry keys to change, did you get them all?

**Comment by phireblast** [comment]
Whoops! That's what I was missing. That fixed it. thanks.
