### ISSUE TITLE
Check that LOOT game path is a directory

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#909]
An issue was recently reported and it turned out that the user had a file named `falloutnv` in their `%LOCALAPPDATA\LOOT` folder, so LOOT wasn't trying to create a game directory and masterlist update was failing due to an invalid path. To help handle this case, check that the LOOT game path is a directory before attempting to create it, and error if not, instead of just checking if it exists.

**Comment by dubirdrs** [comment]
Ok, I removed that folder and let LOOT create a new one, then put the masterlist in there and it works through MO now.  Still have to have updates turned off, but at least the sorting works!

**Comment by pStyl3** [comment]
> It's like every time I open it through MO, it's acting like it's the first time I've opened it.

Does that behavior also occur, if you run LOOT the normal way (that is, not through MO)? Because if not, and it only occurs while running LOOT through MO, then LOOT cannot do anything about it, as that would be a issue of MO, not LOOT.

**Comment by WrinklyNinja** [comment]
Fixed in f2c712e343cb171114c2b57b0139d16df92a83a8.
