### ISSUE TITLE
Sidebar indices don't update properly on game change

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#910]
Reported by @pStyl3 [here](https://afkmods.iguanadons.net/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&do=findComment&comment=172193). I can't replicate this, but I think it might be due to the computed binding using `this.isLightMaster` instead of passing that value into the function.

**Comment by WrinklyNinja** [comment]
@pStyl3 Try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.4-34-gf3fe927_modernise-frontend.7z).

**Comment by pStyl3** [comment]
I'm currently trying to formulate exact steps to reproduce the issue. I just got [this](https://abload.de/img/untitled1b6uf3.jpg) after updating FNV's masterlist and then switching to Fallout 4 (which already had it's masterlist downloaded).

Once I can reproduce it more reliably, I will test with the new snapshot.

**Comment by pStyl3** [comment]
Alright, I think I got it now. I've tested with "loot_0.12.4-33-g3b912f8_modernise-frontend.7z" and the reproduction steps should be as follows:

- two games need to be installed, 1. SSE or FO4 and 2: one of the other (older) games
- in my case, i use SSE and FNV
- delete %localappdata%\LOOT
- make sure that FNV's plugins.txt is empty, so that those plugins will be considered inactive
(for example like [this](https://pastebin.com/raw/KTJihcHX))
- start LOOT and switch fo FNV
- update FNV's masterlist
- switch to SSE
- [Result](https://abload.de/img/untitled1gxrdb.jpg)

**Comment by pStyl3** [comment]
"loot_0.12.4-34-gf3fe927_modernise-frontend.7z" is the same, at least in this specific case.

As of now, I couldn't replicate [this](https://afkmods.iguanadons.net/index.php?/topic/5042-relz-loot-load-order-optimisation-tool/&page=15&tab=comments#comment-172193) with 0.12.4-33.

**Comment by pStyl3** [comment]
The issue at hand (disappearing indix numbers with FNV/SSE) is also present in "loot_0.12.4-0-g62ca11c_dev.7z".

**Comment by WrinklyNinja** [comment]
Ah, with those instructions I can replicate missing indices like in your result screenshot.

**Comment by WrinklyNinja** [comment]
Well, when the load order index isn't visible, it's because Polymer hasn't updated the computed binding even though the underlying data changed (and the item's name, etc. update fine). I can't see why updating the masterlist is necessary to replicate the issue, though I can't without doing so, and I also can't see why only some plugins are effected.

Double-clicking an item to open the editor fixes it, but opening the editor through a card's menu doesn't, even though neither operation changes any item's data and both affect the UI in the same way. Filtering the list also has no effect.

I'm guessing this is a Polymer bug, there could be some async operation that does the rendering that's completing a bit too fast or slow... I'll try updating the elements, hopefully that'll fix it.
