### ISSUE TITLE
exception unknown certificate check

### ISSUE THREAD

**Issue by exelworks91** [loot/loot#911]
Hello,

I've encountered a problem with LOOT. It worked like a charm up until I've installed Fallout 4 a couple of days ago and all of a sudden when I tried to download the masterlist and sort my load order it gave me an error.

The debugging log is attached.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1799822/LOOTDebugLog.txt)

I already tried uninstalling and reinstalling LOOT to no avail. I've also deleted the LOOT folder inside AppData/Local. I keep bumping into the same error.

I hope somebody can help me.

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
