### ISSUE TITLE
Blocking load of resource

### ISSUE THREAD

**Issue by bndmstrj** [loot/loot#912]
Something is blocking LOOT from updating any masterlists. I've double and triple checked the firewall permissions (I think), and am completely lost otherwise. 

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1799860/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
