### ISSUE TITLE
Error at updating masterlist LOOT

### ISSUE THREAD

**Issue by bryanaladiyat** [loot/loot#913]
hello guys, first of all sorry for my bad english, im not a native speaker.
i got this problem im hoping you can help.
 when i try to update masterlist.

> Error
> Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

this is the debug log.

> [14:46:31.279425] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
> [14:46:31.334428] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> [14:51:21.261011] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
> [14:51:21.264011] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
>     at onFailure (http://loot/ui/js/query.js:43:16

i already tried all of the solution in this thread https://github.com/loot/loot/issues/882 but nothing seems to work and it keep showing the same error.
thing i already try
-disable firewall
-allow loot 
-delete loot in appdata
-update windows 7
-run easyfix

idk if this problem occur when i reinstall windows 7 and putting back the appdata and mydocument file from the old windows but this problem never occur before at my old windows. 

thanks,

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.

**Comment by Ghostwalker71** [comment]
@WrinklyNinja I think you might need to take a closer look at this error, it doesn't appear to be the #882 error here.

**Comment by WrinklyNinja** [comment]
I don't see anything suggesting it isn't #882.
