### ISSUE TITLE
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

### ISSUE THREAD

**Issue by Sindri** [loot/loot#917]
What is wrong? I get this each time I try updating my Master List..

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1822289/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
That's loot/loot#882, see the fix that's given in that issue thread, the release notes, readme and FAQs.
