### ISSUE TITLE
Norton Antivirus is labling the program as a "Heuristic Virus"

### ISSUE THREAD

**Issue by Aaron1248** [loot/loot#920]
Hello! I use Loot for Skyrim Special Edition all the time and Norton never had problems with it before. However when the new update was issued I went to download it. When I did, Norton started have a panic attack and said that the program was listed as a Heuristic Virus. Considering this is the first time this has happened to me I was wondering if you had any ideas why it would say that. If it helps it was v0.12.5 that was having issues.

**Comment by WrinklyNinja** [comment]
This happens with various antiviruses pretty much every update, just report it as a false positive and they'll whitelist it.
