### ISSUE TITLE
Loot can't run

### ISSUE THREAD

**Issue by X-Merged** [loot/loot#922]
So here is whats happening. Whenever I try to run loot it just doesn't run. I check it in task manager and see that every time I click it, loot crashes as a background process. The only version of loot that does run is 0.10.3 and with that I am getting errors saying loot can't load anything. Here is my log I got from each time I try to launch it. 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1849923/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Did you try generating a debug log with the latest version of LOOT using the instructions at the bottom of [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by X-Merged** [comment]
In the folder there is no settings, just that log.

**Comment by WrinklyNinja** [comment]
It's not even getting that far? Create the `settings.toml` then, and put `enableDebugLogging = true` in it.

**Comment by X-Merged** [comment]
I did that but when I check in the location of the log, assuming that's where it should be, there is nothing but the new settings.toml and the old log.

**Comment by X-Merged** [comment]
It is meant to go in with the log and not the loot directory right?

**Comment by WrinklyNinja** [comment]
> It is meant to go in with the log and not the loot directory right?

Yes. If it's not overwriting the log, then it's not even getting to the point where it starts logging anything. Could you have antivirus software blocking LOOT?

**Comment by X-Merged** [comment]
I don't think so usually windows defender would give me an annoying message about how it got blocked.

**Comment by X-Merged** [comment]
Just tried disabling windows defender and still didn't help.

**Comment by X-Merged** [comment]
Huh weird, can't even run wrye bash. Only mod organizer thats working is Mod Organizer and it doesn't even really help you sort load order.

**Comment by X-Merged** [comment]
Hey I have TESV Edit, wryebash, LOOT, and Mod Organizer. Could it be that these arent letting me open on another?

**Comment by X-Merged** [comment]
I fixed the problem for now, I just had to delete the loadorder.txt. Thanks for trying to help.

**Comment by WrinklyNinja** [comment]
Do you have a backup of the loadorder.txt you could share? If there was something wrong with the file it still shouldn't ideally stop LOOT launching.

**Comment by X-Merged** [comment]
Wrye Bash actually generated the file it seems, when I launch LOOT it does not make the file.

**Comment by X-Merged** [comment]
But I will get the backup later if I can.

**Comment by X-Merged** [comment]
[loadorder.txt](https://github.com/loot/loot/files/1866502/loadorder.txt)
There it is.

**Comment by WrinklyNinja** [comment]
Ah, the file is incorrectly encoded, there's an entry for `Death Knight`s of Skyrim.esp` where the ``` is encoded as 0xB4, so the file is in Windows-1252, but it should be in UTF-8.

**Comment by WrinklyNinja** [comment]
This is fixed in the `group-metadata` branch, leaving the issue open until that's merged.

**Comment by X-Merged** [comment]
Ok

**Comment by X-Merged** [comment]
Also quick question, why does loot enable some things and disable others when sorting load order

**Comment by WrinklyNinja** [comment]
What do you see getting enabled/disabled? Aside from ensuring correctness, it shouldn't make any such changes.

**Comment by WrinklyNinja** [comment]
> Also it may have something to do with the fact that I have over 255 mods and its just doing this for skyrim.

Yes, it'll deactivate any plugins past your 255th active plugin for correctness.

**Comment by X-Merged** [comment]
So to fix this just remove the plugins that are part of a merge to another folder?

**Comment by WrinklyNinja** [comment]
> So to fix this just remove the plugins that are part of a merge to another folder?

I don't think that should be necessary, but I don't really understand what's happening. Can you give specifics?

**Comment by X-Merged** [comment]
So I have merged plugins. When I use LOOT to sort load order it allows those plugins to be enabled but it also adds some mods that are unnecessary to be loaded because they are inside the merged plugins. While this happens mods that aren't part of the merges are disabled.

**Comment by WrinklyNinja** [comment]
When I say specifics, I mean "here are the plugins that were merged, these were active, these were not, then I did the sort and it disabled these plugins".

**Comment by X-Merged** [comment]
Huh just sorted the load order and it did everything right this time. Thanks anyway though,

**Comment by X-Merged** [comment]
I know this isn't the place for suggestions but you think you could also make it in LOOT where you can enable/disable plugins? Just wondering because other than seeing where the mod loads I don't see a purpose for the search feature.

**Comment by WrinklyNinja** [comment]
Fixed and merged as of b3a6c464d60d14e0af6780d8ec691330498434f8.
