### ISSUE TITLE
LOOT Won't Launch!

### ISSUE THREAD

**Issue by thorman123** [loot/loot#923]
i know that there is another topic like this but mine is different... first of all i have reinstalled loot many times and even went as far as deleting the loot folder in appdata/local

i double click on loot and nothing.. it is in task manager with 10 MB of ram and zero cpu usage... i looked at the appdata/local/loot and the only things in there is an empty Lootdebuglog.txt and a fallout 4 folder with nothing inside of it.. i tried launching loot with administrator privileges and nothing again... it is not launching no matter what i do! what can i do to fix it?

**Comment by WrinklyNinja** [comment]
Did you try generating a debug log with the latest version of LOOT using the instructions at the bottom of [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html)?

**Comment by thorman123** [comment]
heres the log

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1869271/LOOTDebugLog.txt)

and it is still in task manager and isnt launching

**Comment by WrinklyNinja** [comment]
Does LOOT manage to create a folder at `%LOCALAPPDATA%\LOOT\Fallout4`?

**Comment by thorman123** [comment]
yes but its empty...

**Comment by WrinklyNinja** [comment]
Could you have antivirus software that's blocking/quarantining LOOT?

**Comment by thorman123** [comment]
No I have checked and even added it as an exclusion but nothing changes

**Comment by WrinklyNinja** [comment]
Hmm, I'm not sure what it would be then... LOOT's releases are all available [here](https://github.com/loot/loot/releases), can you try going back through them until one works (don't bother going back past v0.11.0 if you get that far)?

**Comment by WrinklyNinja** [comment]
> is it possible to figure out why it was not launching with msi afterburner open?

MSI afterburner says it does video recording, I've heard of some utilities that do audio/video capture can cause issues, maybe this is one of those cases. I can't really figure out any specifics though, but it's good to know in future.
