### ISSUE TITLE
Skyrim VR?

### ISSUE THREAD

**Issue by NightHammer1000** [loot/loot#924]
Any Support planned?

**Comment by WrinklyNinja** [comment]
No as I don't own any VR kit so can't figure it out myself, but see #869 for how Fallout 4 VR support got added: I'd need similar info.

**Comment by Darkaxt** [comment]
Registry:
`[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim VR]
"installed path"="C:\\Program Files (x86)\\Steam\\steamapps\\common\\SkyrimVR\\"`

AppData path: 
`C:\Users\<User>\AppData\Local\Skyrim VR`

Base plugins:
Skyrim SE + SkyrimVR.esm

**Comment by WrinklyNinja** [comment]
> Base plugins:
> Skyrim SE + SkyrimVR.esm

By "Skyrim SE", do you mean all the plugins that shipped with Skyrim SE (e.g. `Hearthfires.esm`) or `SkyrimSE.esm`, or what?

**Comment by Darkaxt** [comment]
Yes, the standard shipped plugins from the SSE version.

**Comment by mbguinta** [comment]
Seconding this request

**Comment by WrinklyNinja** [comment]
Does Skyrim VR use `.bsa` or `.ba2` archives?

Also, you should be able to use the latest LOOT release with Skyrim VR, if you add a game entry for it with `local_path` set, like:

```
[[games]]
	branch = "v0.13"
	folder = "Skyrim VR"
	repo = "https://github.com/loot/skyrimse.git"
	type = "Skyrim Special Edition"
	registry = "Software\\Bethesda Softworks\\Skyrim VR\\Installed Path"
	name = "TES V: Skyrim VR"
	local_path = "C:\\Users\\<User>\\AppData\\Local\\Skyrim VR"
	path = "C:\\Games\\Steam\\steamapps\\common\\SkyrimVR"
	master = "Skyrim.esm"
```

**Comment by Darkaxt** [comment]
I am not sure about .ba2, I can tell that it is using .bsa since most mods from SEE seems to be compatible wtih this version. Only the ones that need to use the 3rd person are problematic.

**Comment by Nyteryder17** [comment]
I just tried the above, and it loaded up my plugins file and seemed to work as you would expect.

**Comment by NightHammer1000** [comment]
Works! +1

**Comment by WrinklyNinja** [comment]
Done as of 47e51b88dd31166a96b60b5c570d59689ebadc1a.
