### ISSUE TITLE
Migrate to Bower-less, Webpack-only UI via Polymer 3

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#926]
Part 2 of #902, split off because Polymer 3 didn't ship within the expected timeframe and the other changes in that issue have been merged.

To do:

- [x] Upgrade Polymer to v3
- [ ] Upgrade official Polymer elements to their Polymer v3-compatible releases
- [ ] Upgrade ellipticaljs/paper-autocomplete to a Polymer v3-compatible release
- [x] Remove Bower usage
- [x] Replace any remaining HTML imports with ES6 module imports
- [x] Remove the `scripts/build_ui.js` script as it'll be redundant with no HTML imports
- [x] Fix the flash-of-unresolved-content introduced when launching LOOT

**Comment by WrinklyNinja** [comment]
I've started this in the `polymer-3` and because it's not possible to do an incremental upgrade, it's mostly finished and seems to work. The official Polymer elements have been upgraded to their latest v3 previews, pending proper releases.

The paper-autocomplete element hasn't got a v3-compatible version available (not even unreleased) so I'll have to check if the author is going to update it, or if I should fork the element and upgrade it for LOOT. I had a quick look and there don't appear to be alternatives.

**Comment by pStyl3** [comment]
I've tested "loot_0.12.5-30-gae0c791_polymer-3.7z", the drag-enable/disable buttons for "Enable debug logging" and "Update masterlist before sorting" are not getting displayed within the Settings menu.

**Comment by WrinklyNinja** [comment]
That seems to be caused by loading the `app.js` module in `<head>`, which was the fix for the flash of unresolved content. There's also an exception thrown: `Uncaught DOMException: Failed to construct 'CustomElement': The result must not have attributes`. That exception isn't thrown, and the toggles are visible, if `app.js` loads in `<body>`...

**Comment by WrinklyNinja** [comment]
non-preview v3 releases are now available for all the elements LOOT uses, so I can now update to them and hopefully merge this if that doesn't introduce any issues.

**Comment by WrinklyNinja** [comment]
Done as of b79c6d28e6adca91b3ea77b6717ecf3dfba17173.
