### ISSUE TITLE
LOOT v0.12.5 will not detect games and fails

### ISSUE THREAD

**Issue by Red-Can** [loot/loot#927]
Trying to install LOOT v0.12.5 using LOOT.Installer.exe or using loot_0.12.5-0-gc398b9c_dev.7z (W10 x64 Home). Neither version will find game files for Fallout 4. Error shows as "Error
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information."

Debug file shows:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1886832/LOOTDebugLog.txt)

Also when trying to close file getting error Loot.exe has stopped working, and I have to click through this error message twice to actually close it.

**Comment by WrinklyNinja** [comment]
Have you tried running the Fallout 4 launcher so its Registry entries exist?

**Comment by Red-Can** [comment]
You have found the problem. I can not find any registry entries under Bethesda Softworks, except one for Bethesda.net. Looks like I will have to reinstall Fallout 4, and run the game first.

**Comment by WrinklyNinja** [comment]
OK, that'll do it, closing this.
