### ISSUE TITLE
LOOT Running slow to the point of being unable to function + unable to update load order

### ISSUE THREAD

**Issue by EngiePlus** [loot/loot#929]
So...  I'm not positive what all information is relevant, so I'm just gonna include everything.  Not even sure what happened. I haven't touched Skyrim for a while, tried to today after installing a bunch of new mods, and have been having issues with CTD . Of course, I open up LOOT to see if I can find anything in there, but the program is experiencing some unreal kind of lack. It can take anywhere from 10 seconds to a minute for any action I make to register, scrolling is virtually impossible, and I can't seem to actually effect any changes I make as well. I noticed that I was using an old version of LOOT, so, I downloaded and installed the newest version, but the same issue persists.  Now, at least, when i try to just update the load order anyway for the sake of any progress, I get a message saying some plugins.txt may be set to read only, but it doesn't say where it's located so I can't check, nor can I still even see what is actually use the software in any other way; when I close and reload it it seems any settings or changes I attempt to make don't get saved or whatever. Ex. I keep having to set it to Skyrim when I manage to bungle through the settings and turn it off auto detect.

I'm sorry that's kind of a mish-mash of info but that's pretty much where I'm at right now. I can try to pull the debug logs but I haven't been able to turn those on let alone access the actually thing either. If I could just get the program to not run like I was using a toaster (I know it's not my system itself, I have a ton of other processes going on at the same time with no issue whether LOOT is open or not, and even with just LOOT running itself it has no difference in performance) then that would be a major fix and I could probably work my way through the rest with some effort. Thanks in advance.

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for how to enable debug logging when the UI is inaccessible (which it sounds like it is for you). It sounds like Chromium (which LOOT uses for its UI) may not like your system, so posting your specs might also be helpful.

The plugins.txt issue and your settings not getting saved sounds like separate issues, though may be related to the lag you're experiencing.

**Comment by EngiePlus** [comment]
I apologize about the delay, work got the best of me this past week.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1907425/LOOTDebugLog.txt)
Glancing through this myself I think my issue may just be I have to many god damn mods going on, although I didnt have this sort of lag several months ago when I first installed all this stuff.

Also have specs here
https://i.gyazo.com/5f1a43d47183eb297a759ab765eaa8cc.png

**Comment by WrinklyNinja** [comment]
Hmm, the timings in that debug log seem reasonable, and 114 plugins isn't a lot, it seems to be UI lag as opposed to a backend performance issue...

From your specs I'm guessing you're on a laptop, does it have anything that switches between the integrated graphics card and your 970M, e.g. for better efficiency on battery power? I've heard that sort of thing can cause display issues.

Try:
- running LOOT with the `--disable-gpu` flag, it makes the UI a bit stuttery for me, maybe it'll do something different for you
- running the [v0.12.2 release](https://github.com/loot/loot/releases/tag/0.12.2), it was the last release to include CEF debug logging, if it's also got the same performance issues maybe `CEFDebugLog.txt` will have something useful.

**Comment by WrinklyNinja** [comment]
OK, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-15-g0388f4f_update-cef.7z).

**Comment by WrinklyNinja** [comment]
> I only know very little about coding so I wasn't sure where or how to plug in the flag you mentioned.

Create a shortcut, then right-click it and select Properties. On the Shortcut tab, add `--disable-gpu` to the Target value.

**Comment by EngiePlus** [comment]
Shit, that did it! Thanks for all your help.
