### ISSUE TITLE
ERROR: Cannot read property "status" of undefined

### ISSUE THREAD

**Issue by a1798636524** [loot/loot#935]
tonight i meet a severe bug that my skyrim always ctd but my mods are same as it was before.so i seek for help from loot by MO.then i meet this severe bug.i search for issues on the github and i find a similar one.github are banned in china these days so that i use VPN .i want toknow that if it is the reason that i cannot organize my mods and meet with ctd .i will upload my debug.txt .What shuold i do? i really love skyrim and do not want to give it up!!!! 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/1934720/LOOTDebugLog.txt)
![default](https://user-images.githubusercontent.com/33086354/39085907-8d1bfcfa-45bc-11e8-8b72-d098ca0daf3e.PNG)

**Comment by a1798636524** [comment]
i change the order randomly to make sure my loot can not organize those mods anymore WHO CAN HELP ME?

**Comment by CptMcSplody** [comment]
Receiving the same error, I'm running through MO2 though, so could be an issue with that, I left a message on their discord to see if they can come up with anything. I haven't replicated it while not running through MO as I don't have a mod list set up outside MO to test properly. Is there a working link for that build?

**Comment by WrinklyNinja** [comment]
> Is there a working link for that build?

No, but just try with the [latest build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-25-ge41f579_dev.7z).

**Comment by CptMcSplody** [comment]
Can't replicate it with latest build.

**Comment by WrinklyNinja** [comment]
This was due to a bug in the github-api library LOOT's update checker was using, fixed in 304555e3297411ba72d3d33a99a77d44a83d59b3.
