### ISSUE TITLE
ERROR: Cannot read property "status" of undefined Skyrim SE

### ISSUE THREAD

**Issue by Veym** [loot/loot#939]
When trying to run Skyrim SE I run into the aforementioned error. I cannot sort nor can I update the masterlist. I am running version 0.12.5 (build c398b9c6) of Loot. I have read every other issue regarding the same problem and I am unable to resolve this.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1935113/LOOTDebugLog.txt)

What happens when I try to sort the plugins:

![cannot read](https://user-images.githubusercontent.com/38596088/39089931-f47a6a22-458e-11e8-909e-96ae5258e7e8.JPG)

What happens when I try to update the masterlist:

![update masterlist](https://user-images.githubusercontent.com/38596088/39089941-20486dca-458f-11e8-8a7b-aaeb2c8ec4ee.JPG)

**Comment by CptMcSplody** [comment]
Looks like you have the Skyrim masterlist as SSE masterlist does not have FNIS install check.
Have you verified your settings?

**Comment by Veym** [comment]
These are my settings: 

![settings](https://user-images.githubusercontent.com/38596088/39090589-06610348-45a0-11e8-96d1-0027572739e1.JPG)


Is there something incorrect?

**Comment by Veym** [comment]
This is my log file now. It appears that it can sort the plugins then fails at the end.


[LOOTDebugLog.txt](https://github.com/loot/loot/files/1935156/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
```
[20:09:07.082839] [error]: Exception while executing query: Git operation failed. Details: -1; invalid data in index - incorrect header signature: libgit2 error
[20:09:12.534435] [error]: Exception while executing query: Git operation failed. Details: -1; invalid data in index - incorrect header signature: libgit2 error
[20:09:16.018662] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: refs/remotes/origin/v0.10: libgit2 error
```

Looks like you've got a corrupted file, delete your `C:/Users/Mitchell Collins/AppData/Local/LOOT/Skyrim Special Edition/.git/` folder. Also try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-20-g9cbff7f_misc-fixes.7z), which should fix the "cannot read property" error you're getting.

**Comment by Veym** [comment]
Deleting that file worked, thank you.
