### ISSUE TITLE
SKYUI and SKSEVR error

### ISSUE THREAD

**Issue by VernMcC** [loot/loot#941]
The SKSE developers just released v2.0.7 of SKSE for VR, SKSEVR.  The file names are:
sksevr_1_3_64.dll
sksevr_loader.exe
sksevr_steam_loader.dll

I have successfully installed SkyUI on SkyrimVR and have it functioning as expected including MCM menu. When I sort my loot order, I get an alert that SkyUI requires SKSE64:

> This plugin requires "SKSE64" to be installed, but it is missing.

The sorting works, as does SkyUI.  I copied the file to skse64_loader.exe (that is the req in the master list) to stop the error, but an update to the master list to include sksevr_loader.exe should be considered.

**Comment by WrinklyNinja** [comment]
Hmm, SKSE64 requirements in the skyrimse masterlist will need to be conditional on `Skyrim VR.esm` not being present, and SKSEVR requirements added that are conditional on it being present, to give the right message for the right game. I don't think it's worth creating a separate skyrimvr masterlist when just SKSE is different.

**Comment by WrinklyNinja** [comment]
Wait a second, SkyUI doesn't say anything about SKSE VR, it just says it requires SKSE64. As such, the current message is correct, so I'm closing this as invalid.

**Comment by VernMcC** [comment]
Okay, sorry for the confusion.
