### ISSUE TITLE
Fallout 4 Setting's Issue [Solved]

### ISSUE THREAD

**Issue by FaytCloud** [loot/loot#944]
Not sure if it was only on me, but incase it wasn't here's a bug and how i fixed it

Bug = LOOT would not detect any Fallout 4 mods or plugins at all, no matter what i tried

Fix = finding the settings.toml in the local folder [ <user>\Appdata\local\LOOT ] i edited using Visual Studio Code [though i assume notepad++ and other's "Should" work] i found the fallout 4 header and under it found this;

[[games]]
	branch = "v0.10"
	folder = "Fallout4"
	repo = "https://github.com/loot/fallout4.git"
	type = "Oblivion"
	registry = "Software\\Bethesda Softworks\\Fallout4\\Installed Path"
	name = "Fallout 4"
	local_path = ""
	path = "E:\\SteamLibrary\\steamapps\\common\\Fallout 4\\"
	master = "Fallout4.esm"

the type section reads oblivion, but SHOULD read "Fallout4" once fixed and saved the problem is solved

**Comment by WrinklyNinja** [comment]
`type = "Oblivion"` isn't the default, so I don't see how this is a bug, but it's good that you've solved your issue.
