### ISSUE TITLE
Masterlist update error: The server name or address could not be resolved

### ISSUE THREAD

**Issue by C-Haros** [loot/loot#953]
When using LOOT, I couldn't update my masterlist nor sort my mods. Below is the error message from the DebugLog.

[00:02:13.206255] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

**Comment by WrinklyNinja** [comment]
Please upload your whole debug log.

**Comment by C-Haros** [comment]
[03:01:51.473230] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[03:01:52.462284] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[03:01:54.173056] [warning]: No masterlist present at C:\Users\Charon Hu\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by C-Haros** [comment]
Sorry about that. This should do it
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2052751/LOOTDebugLog.txt)

**Comment by C-Haros** [comment]
I have tried deleting everything inside the Skyrim SE folder in Loot as well as reinstalling loot. But unfortunately to no avail

**Comment by WrinklyNinja** [comment]
```
[03:01:56.353139] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The server name or address could not be resolved
: libgit2 error
```

It looks like something is blocking DNS when LOOT tries to update the masterlist, check your firewall / antivirus. Are you posting here from the same machine that LOOT runs on?

**Comment by C-Haros** [comment]
Yes I am

**Comment by C-Haros** [comment]
I also am just using Windows 10 firewall.
I tried running Loot as admin and allowing it to pass through the firewall, but it doesn't seem to do anything

**Comment by WrinklyNinja** [comment]
Can you turn on debug logging, reproduce the error, then upload that log?
Maybe there's something wrong with the URL being used, but that's not
logged at the default logging level.

**Comment by C-Haros** [comment]
Of course 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2052867/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Could you try with [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-38-g6fa927e_misc-updates.7z)? If it doesn't work, please upload its debug log.

**Comment by WrinklyNinja** [comment]
Well, that error is totally unrelated and harmless, and isn't so much fixed as hidden as LOOT no longer writes a CEF debug log...

**Comment by sr383** [comment]
I think there was a parallel, unreported error, because my bashed patch wasn't being sorted to the bottom. With the latest update, it is.

**Comment by WrinklyNinja** [comment]
Were you using an earlier plugin groups build? There were a few general issues with groups that I fixed recently.

**Comment by sr383** [comment]
I'm not sure what you mean by a "plugin groups build." (I was running the installer version downloaded from GitHub today.) I'm running MO2, and with a bit of effort, I can usually get everything working like I need it to. My new MO2 install running FO4 didn't seem to be updating the master lists, so nothing was being sorted. With your new build, the list update is happening, and the load order results are reflected in MO2.

**Comment by WrinklyNinja** [comment]
Well, that's good. Could be related to some masterlist update improvements I made.

**Comment by C-Haros** [comment]
The build didn't help for me unfortunately. So here's the debug log
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2055289/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Well, it's trying to use the right URL for the masterlist, so it's not just bad config... Do you use a proxy to connect to the internet? What gets displayed if you open up a command line window and type `nslookup github.com`?

**Comment by C-Haros** [comment]
It said:

Non-authoritative answer:
Name:    github.com
Addresses:  192.30.253.112
                   192.30.253.113

**Comment by WrinklyNinja** [comment]
So your OS is able to resolve the domain, but LOOT isn't... LOOT just uses the OS network stack though, so I don't see why it's not working unless something else is interfering. I don't think there's anything I can do about this.

**Comment by C-Haros** [comment]
That's unfortunate, Thanks for the help regardless
