### ISSUE TITLE
LOOT v0.12.5 won't detect Fallout 3

### ISSUE THREAD

**Issue by Zippomoon** [loot/loot#954]
Lunching it from the NMM FO3 (Steam - GOTY) menu and immediately dumps me in the settings menu and the setting seem to be fine.
https://pastebin.com/2P6ZCiij

**Comment by WrinklyNinja** [comment]
Have you run the game launcher to visit ensure the necessary registry entry
is created first?

**Comment by WrinklyNinja** [comment]
Looks like somthing in the git repository got corrupted, delete your `%LOCALAPPDATA%\LOOT\Fallout3\.git` folder (it may be hidden) and try again.

**Comment by Zippomoon** [comment]
That fixed it thanks!
