### ISSUE TITLE
Fallout 4 Creation Club plugin sorted out of order

### ISSUE THREAD

**Issue by Kylobek** [loot/loot#956]
I have this annoying error of ''plugins.txt read only'' thing. 

My plugins.txt is NOT read-only, I am the owner of the folder, tried running as admin, tried uninstalling/reinstalling. Slowly running out of options.

Here's the DEBUG :
[12:18:03.774754] [trace]: User has accepted sorted load order, applying it.
[12:18:03.774805] [debug]: Getting load order.
[12:18:03.777113] [info]: Setting load order.
[12:18:03.777138] [info]: 		Fallout4.esm
[12:18:03.777150] [info]: 		DLCRobot.esm
[12:18:03.777160] [info]: 		DLCworkshop01.esm
[12:18:03.777171] [info]: 		DLCCoast.esm
[12:18:03.777181] [info]: 		DLCworkshop02.esm
[12:18:03.777193] [info]: 		DLCworkshop03.esm
[12:18:03.777203] [info]: 		DLCNukaWorld.esm
[12:18:03.777213] [info]: 		ccbgsfo4016-prey.esl
[12:18:03.777223] [info]: 		ccbgsfo4038-horsearmor.esl
[12:18:03.777234] [info]: 		Unofficial Fallout 4 Patch.esp
[12:18:03.777244] [info]: 		ccgcafo4004-factionws04gun.esl
[12:18:03.777254] [info]: 		Homemaker.esm
[12:18:03.777264] [info]: 		def_inv_scrap_en.esp
[12:18:03.777274] [info]: 		Homemaker - Streetlights Use Passive Power.esp
[12:18:03.777284] [info]: 		Diamond City Enhanced.esp
[12:18:03.777332] [error]: libloadorder failed to set the load order. Details: The game's main master file must load first
[12:18:03.777399] [error]: Exception while executing query: libloadorder failed to set the load order. Details: The game's main master file must load first: Libloadorder error
[12:18:03.777789] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! This is usually because "C:\Users\Ced\AppData\Local\Fallout4\plugins.txt" is set to be read-only. If it is, unset it and try again. If it isn't, you can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:462892)
[12:18:07.517769] [info]: Opening LOOT's local appdata folder.

Thanks in advance!

**Comment by WrinklyNinja** [comment]
The error message says `This is usually` for a reason... In this case it's because there's some metadata missing. There is a file ending in .ccc, something like `Fallout4.ccc`, in your Fallout 4 install folder (one up from its Data folder), can you post the contents of that (it's just a text file, open it in notepad or whatever)?

**Comment by Kylobek** [comment]
Oh, don't worry I know it says `This is usually`, I just wanted to prevent the usual ''It's because it's read-only brah'' comment.

Here is the content of the Fallout4.ccc file.

Also thanks alot for the help!

ccBGSFO4001-PipBoy(Black).esl
ccBGSFO4002-PipBoy(Blue).esl
ccBGSFO4003-PipBoy(Camo01).esl
ccBGSFO4004-PipBoy(Camo02).esl
ccBGSFO4006-PipBoy(Chrome).esl
ccBGSFO4012-PipBoy(Red).esl
ccBGSFO4014-PipBoy(White).esl
ccBGSFO4005-BlueCamo.esl
ccBGSFO4016-Prey.esl
ccBGSFO4018-GaussRiflePrototype.esl
ccBGSFO4019-ChineseStealthArmor.esl
ccBGSFO4020-PowerArmorSkin(Black).esl
ccBGSFO4022-PowerArmorSkin(Camo01).esl
ccBGSFO4023-PowerArmorSkin(Camo02).esl
ccBGSFO4025-PowerArmorSkin(Chrome).esl
ccBGSFO4033-PowerArmorSkinWhite.esl
ccBGSFO4024-PACamo03.esl
ccBGSFO4038-HorseArmor.esl
ccBGSFO4041-DoomMarineArmor.esl
ccBGSFO4042-BFG.esl
ccBGSFO4044-HellfirePowerArmor.esl
ccFSVFO4001-ModularMilitaryBackpack.esl
ccFSVFO4002-MidCenturyModern.esl
ccFRSFO4001-HandmadeShotgun.esl
ccEEJFO4001-DecorationPack.esl
ccRZRFO4001-TunnelSnakes.esm
ccBGSFO4045-AdvArcCab.esl
ccFSVFO4003-Slocum.esl
ccGCAFO4001-FactionWS01Army.esl
ccGCAFO4002-FactionWS02ACat.esl
ccGCAFO4003-FactionWS03BOS.esl
ccGCAFO4004-FactionWS04Gun.esl
ccGCAFO4005-FactionWS05HRPink.esl
ccGCAFO4006-FactionWS06HRShark.esl
ccGCAFO4007-FactionWS07HRFlames.esl
ccGCAFO4008-FactionWS08Inst.esl
ccGCAFO4009-FactionWS09MM.esl
ccGCAFO4010-FactionWS10RR.esl
ccGCAFO4011-FactionWS11VT.esl
ccGCAFO4012-FactionAS01ACat.esl
ccGCAFO4013-FactionAS02BoS.esl
ccGCAFO4014-FactionAS03Gun.esl
ccGCAFO4015-FactionAS04HRPink.esl
ccGCAFO4016-FactionAS05HRShark.esl
ccGCAFO4017-FactionAS06Inst.esl
ccGCAFO4018-FactionAS07MM.esl
ccGCAFO4019-FactionAS08Nuk.esl
ccGCAFO4020-FactionAS09RR.esl
ccGCAFO4021-FactionAS10HRFlames.esl
ccGCAFO4022-FactionAS11VT.esl
ccGCAFO4023-FactionAS12Army.esl
ccAWNFO4001-BrandedAttire.esl
ccSWKFO4001-AstronautPowerArmor.esm
ccSWKFO4002-PipNuka.esl
ccSWKFO4003-PipQuan.esl
ccBGSFO4050-DgBColl.esl
ccBGSFO4051-DgBox.esl
ccBGSFO4052-DgDal.esl
ccBGSFO4053-DgGoldR.esl
ccBGSFO4054-DgGreatD.esl
ccBGSFO4055-DgHusk.esl
ccBGSFO4056-DgLabB.esl
ccBGSFO4057-DgLabY.esl
ccBGSFO4058-DGLabC.esl
ccBGSFO4059-DgPit.esl
ccBGSFO4060-DgRot.esl
ccBGSFO4061-DgShiInu.esl
ccBGSFO4036-TrnsDg.esl
ccRZRFO4004-PipInst.esl
ccBGSFO4062-PipPat.esl
ccRZRFO4003-PipOver.esl
ccFRSFO4002-AntimaterielRifle.esl
ccEEJFO4002-Nuka.esl
ccYGPFO4001-PipCruiser.esl
ccBGSFO4072-PipGrog.esl
ccBGSFO4073-PipMMan.esl
ccBGSFO4074-PipInspect.esl
ccBGSFO4075-PipShroud.esl
ccBGSFO4076-PipMystery.esl
ccBGSFO4071-PipArc.esl
ccBGSFO4079-PipVim.esl
ccBGSFO4078-PipReily.esl
ccBGSFO4077-PipRocket.esl
ccBGSFO4070-PipAbra.esl
ccBGSFO4008-PipGrn.esl
ccBGSFO4015-PipYell.esl
ccBGSFO4009-PipOran.esl
ccBGSFO4011-PipPurp.esl
ccBGSFO4021-PowerArmorSkinBlue.esl
ccBGSFO4027-PowerArmorSkinGreen.esl
ccBGSFO4034-PowerArmorSkinYellow.esl
ccBGSFO4028-PowerArmorSkinOrange.esl
ccBGSFO4031-PowerArmorSkinRed.esl
ccBGSFO4030-PowerArmorSkinPurple.esl
ccBGSFO4032-PowerArmorSkinTan.esl
ccBGSFO4029-PowerArmorSkinPink.esl
ccGRCFO4001-PipGreyTort.esl
ccGRCFO4002-PipGreenVim.esl
ccBGSFO4013-PipTan.esl
ccBGSFO4010-PipPnk.esl

**Comment by WrinklyNinja** [comment]
Damn, that's a big list, it'll be a pain to add metadata for all of them... I'll add an entry for `ccgcafo4004-factionws04gun.esl` and work on getting LOOT to read the `.ccc` file instead of needing metadata for all of them.

**Comment by WrinklyNinja** [comment]
OK, I've added the metadata entry, your particular case should work now, can you confirm?

**Comment by Kylobek** [comment]
Yep. Absolutely worked out. Now is this something that I can prevent in the futur? I know it sounds strange but LOOT worked fine for a while, even with Creation Club mods. Is the solution just not to add any Creation Club plugins anymore?

Thanks alot for your help btw, greatly appreciate it.

**Comment by WrinklyNinja** [comment]
It worked fine because LOOT was sorting them in positions they couldn't actually load in (because their positions are hardcoded). When you apply the load order, LOOT passes it down to libloadorder to do the actual applying, and libloadorder was just ignoring that hardcoded plugins had nonsense positions, because it couldn't actually change them anyway.

The trouble with this is that it can lead to LOOT never noticing you've already sorted your load order, because the reality doesn't match what it calculates. To help fix that I made libloadorder stricter so that it would check hardcoded plugin positions in what it was given and reject anything that's wrong, which is what is happening here.

If you want to avoid this happening again, avoid adding any more CC mods until I've updated LOOT, as the alternative is adding a huge block of very repetitive metadata to the masterlist, and keeping that up to date as more CC mods are released.

**Comment by Kylobek** [comment]
Perfect. Thanks alot for the support!

**Comment by WrinklyNinja** [comment]
@DankRafft, @AZZOS, @caliburn2003, @gdog361: Please try replacing the `loot_api.dll` in your LOOT install with [this one](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_api-0.13.4-5-gcf9f955_update-libgit2-win32.7z) and try sorting again. Let me know if it fixes your issues or not.

**Comment by DankRafft** [comment]
Yes, it does work. Thank you.

**Comment by AZZOS** [comment]
ur magic powder works gj
