### ISSUE TITLE
main.rst needs an updated image for The Main Interface

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#957]
loot/docs/app/usage/main.rst
The image still shows priorities.

**Comment by WrinklyNinja** [comment]
Damn, well, it looks like I'll have to do another release soon due to #956, so I'll make sure that gets updated before then.

**Comment by pStyl3** [comment]
https://loot.readthedocs.io/en/latest/app/usage/settings.html
Another candidate to be updated.

**Comment by WrinklyNinja** [comment]
Oh, I added that setting, didn't I...

**Comment by WrinklyNinja** [comment]
Done in 76fd93cc78d09162fdb07bd93a68cb9df6366fdc.
