### ISSUE TITLE
Grey color in Skyrim SE USSEP mod

### ISSUE THREAD

**Issue by vexz2423** [loot/loot#966]
HELP in LOOT
USSEP
C.Climate, C.Encounter, C.ImageSpace, C.Light, C.Location, C.Music, C.Name, C.Owner, C.Water, Delev, Graphics, Invent, Names, Relev, Sound, Stats
The Description of all of that is not color green... it's color grey. why is that? I see other people with those descriptions with color green but mine is color grey. HELP

**Comment by WrinklyNinja** [comment]
Hmm, I forgot to update the docs about this... Tags that are already present in the plugin's description field are now shown in grey, there's nothing wrong.
