### ISSUE TITLE
Back cycle... something, something

### ISSUE THREAD

**Issue by T0rvadaL** [loot/loot#968]
Hi, LOOT won't sort my load order after updating to the newest version :(
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2066266/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Looks similar to #963. Try using the metadata editor to put `RealisticWaterTwo - iNeed.esp` in the `Alternate Start` group.

**Comment by T0rvadaL** [comment]
Ok, i did that but it didn't work. I tried also putting realisticwatertwo - watercolor.esp in the alternate start group still didn't work. this is what i get now.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2066276/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Looks like it did work, but you hit another cycle. Also try adding DBM_MLU_Patch.esp to the group that MLU.esp is in.

**Comment by T0rvadaL** [comment]
I keep getting hit by cycles. Immersive citizens doesn't agree with anything. putting immersive citizens to default group, fixes it, but puts it way to early in the load order.

**Comment by CptMcSplody** [comment]
Could be the fact that immersive citizens group does not have anything loading after it. The load after alt start rule might also be an issue.

**Comment by T0rvadaL** [comment]
I don't even have alternate start installed :/

**Comment by T0rvadaL** [comment]
I'm currently mid play-through, and am trying to replace elfx with ele + relighting skyrim, hence why i'm running loot. Do you think deleting everything inside LOOT (in appdata) would fix it, without changing my current load order and possibly breaking my game?

**Comment by CptMcSplody** [comment]
If you have any existing user rules then it's worth trying. Make a backup first though.

**Comment by CptMcSplody** [comment]
@T0rvadaL Try moving `Immersive Citizens - AI Overhaul.esp` to Alt Start Group.
![image](https://user-images.githubusercontent.com/1944639/40890601-64f1e55c-6770-11e8-9c5d-a0a0d853aad9.png)

**Comment by T0rvadaL** [comment]
It worked! Altough it now places immersive citizens below Morrowloot ultimate, and if i remember right, when i looked through sseedit, it was better to have MLU below Immersive citizens. But that was easily fixed by adding editing "MLU.esp" metadata. Thank you, You're the man <3

**Comment by CptMcSplody** [comment]
@T0rvadaL `Immersive Citizens - AI Overhaul.esp` should be fine after `mlu.esp`. I'll double check to be sure.

**Comment by WrinklyNinja** [comment]
OK, closing this since it was fixed by #131.
