### ISSUE TITLE
Cyclic interaction detected between "RE_OCS Patch.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Requiem - Live Another Life.esp, Open Cities Skyrim.esp, RE_OCS Patch.esp, RE_OCS Patch.esp

### ISSUE THREAD

**Issue by coasunecroma** [loot/loot#970]
Cyclic interaction detected between "RE_OCS Patch.esp" and "Alternate Start - Live Another Life.esp". Back cycle: Alternate Start - Live Another Life.esp, Requiem - Live Another Life.esp, Open Cities Skyrim.esp, RE_OCS Patch.esp, RE_OCS Patch.esp

https://www.nexusmods.com/skyrim/mods/37774
https://www.nexusmods.com/skyrim/mods/9557/
https://www.nexusmods.com/skyrim/mods/8058/

**Comment by CptMcSplody** [comment]
Move `Requiem - Live Another Life.esp` & `RE_OCS Patch.esp, RE_OCS Patch.esp` to the same group as their masters.

Also please enable debug logging and provide your LOOTDebugLog

**Comment by coasunecroma** [comment]
Sorry for the belated reply, that seems to have fixed it, Thanks !

**Comment by coasunecroma** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2108584/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
@coasunecroma No worries, thanks. I'm going to leave this open until the meta data has been updated.

**Comment by CptMcSplody** [comment]
Fixed in https://github.com/loot/skyrim/pull/191/commits/d1c70b6 by splitting alt start & open cities into 2 groups.
