### ISSUE TITLE
Loot 'cyclic interaction error'

### ISSUE THREAD

**Issue by PhoenixSpyder** [loot/loot#973]
I'm trying to sort my mods for Skyrim VR but am getting this error:

Cyclic interaction detected between "Open Cities Skyrim.esp" and "Immersive Citizens - AI Overhaul.esp". Back cycle: Immersive Citizens - AI Overhaul.esp, Relationship Dialogue Overhaul.esp, RDO - AFT v1.66 Patch.esp, Open Cities Skyrim.esp

Here is my 'Lootdebuglog.txt' file

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2130159/LOOTDebugLog.txt)

Thanks

**Comment by Hairetik0s** [comment]
Usually it means that your metadata can't be satisfied (Such as A comes after B, B comes after C, but C must come after A; there's no way to sort that in a way to make that happen), so I'd check to make sure if can be sorted first.

That said, I'm trying to sort "chem redux.esp", "VIS-PatchChemRedux.esp", and "Radrose Usability Enhancements.esp" in FO4, except it claims a cyclic interaction exists when there is none. "Radrose Usability Enhancements.esp" should load after "VIS-PatchChemRedux.esp", "VIS-PatchChemRedux.esp" requires "chem redux.esp", and "chem redux.esp" has no rules. So it may be a bug in LOOT.

**Comment by PhoenixSpyder** [comment]
Thanks, for now I've made a load after rule for 'Open cities Skyrim' to load after 'Immersive citizens - AI Overhaul'. This enables me to then still sort my mods. Cheers!!

**Comment by WrinklyNinja** [comment]
@CptMcSplody Is there anything we should be adding to the Skyrim SE masterlist to handle this issue?

**Comment by CptMcSplody** [comment]
@WrinklyNinja I think this should have resolve that issue https://github.com/loot/skyrimse/commit/00bf2e1e

**Comment by CptMcSplody** [comment]
And also this https://github.com/loot/skyrimse/pull/261/commits/f8af8a72

**Comment by WrinklyNinja** [comment]
OK, closing this then.
