### ISSUE TITLE
LOOT UI is a blank white page but is still functional

### ISSUE THREAD

**Issue by GREMLINoRAGE** [loot/loot#974]
To make this as short and sweet as possible: Every time I launch LOOT I get a blank white screen. It doesn't matter how I launch it or what I launch it through. I've been through every thread I can find, tried every "solution", yet the problem persists. It worked fine a little over a month ago and now it doesn't.

**Comment by WrinklyNinja** [comment]
Unfortunately while it's a known issue and I've had it happen myself a few times, I've got no idea why it happens or how to fix it...

**Comment by muizzsiddique** [comment]
Same here. I've had it working everytime until till now.

I can't install the required MSVC redistributable because I have a different version installed but I don't have a single MSVC 2015 installed on my laptop. Even then, it worked before I thought the distributable packages were even a problem.

**Comment by GREMLINoRAGE** [comment]
Can confirm that disabling IE11 had no effect on LOOT. What I have discovered is that, despite the white screen, I can still interact with LOOT's interface. With a little guessing and a look at a working version of LOOT via YouTube, I was able to sort my load order. Will update if it sorted properly to allow stable play.

**Comment by CptMcSplody** [comment]
@GREMLINoRAGE Can you check your processes in windows when it happens? Just check that their is only one process of LOOT running, and after closing LOOT make sure there is no LOOT process left running.

**Comment by WrinklyNinja** [comment]
> @CptMcSplody None. But as I said above. It appears to be purely visual. I can still interact with LOOT to sort my load order with some very calculated clicking.

That is very strange... If you're a Chrome user, do you get this with it at all when you're browsing the web?

**Comment by GREMLINoRAGE** [comment]
@CptMcSplody I do use chrome and I've had the issue once in the past but it was a simple fix and hasn't happened since.

**Comment by Tulivu89** [comment]
I'm having the same issue. I've tried installing different versions, the above mentioned disabling IE and whatnot. I am able to click on things but haven't figured out navigating blind like the OP.

**Comment by docido** [comment]
Just had this issue updating to 0.14.4 from something much older, but with a black screen.  Had an installer for 0.14.3, so tried that and it cleared the problem up.  Just for the heck of it I reinstalled 0.14.4 and saw the problem recur.  Reinstalling 0.14.3 cleared it up again.

**Comment by Ortham** [comment]
Passing `--disable-gpu` will work around the black screen, but I've reverted the CEF update responsible, so it should be fixed again in the next release.

**Comment by HylianSteel** [comment]
Heya, Wrinkly. I experience this (Solid white screen) when I launch LOOT with --game=Skyrim Special Edition. It's been doing this for the past couple releases now. Is this considered the same thing, or should I open up a separate issue about it?

**Comment by Ortham** [comment]
Probably the same thing. Does it only happen when you launch with `--game=Skyrim Special Edition`? What happens if you remove that?

**Comment by HylianSteel** [comment]
It launches without issue if the flag is removed. LOOT has no issue launching with --game=Fallout4 though. Don’t have any other games to test other flags with.

**Comment by Ortham** [comment]
Ah, you need to pass `--game="Skyrim Special Edition"`, otherwise it's parsing it as `--game=Skyrim`, `Special` and `Edition`, and I think it's then trying to use `Special` as the path to the HTML file to load (which is a feature I added for testing, so maybe I should change that...).

**Comment by HylianSteel** [comment]
Yep, can confirm, the quotes makes the difference. It launches without issue now.

**Comment by HylianSteel** [comment]
301 459 3500

**Comment by jjurkus** [comment]
--disable-gpu worked for me on a VM. (was testing stuff)

**Comment by Ortham** [comment]
I've added this to the v0.18.0 milestone because I'm pretty sure that the issue does not exist in the Qt-based UI that is being developed in the `qt` branch and tracked by #1638.

**Comment by Ortham** [comment]
The new UI has landed as of 6daa98c0e45eddb4d5b37312302592ab4cf476c8, so closing this.
