### ISSUE TITLE
LOOT crash/close after starting

### ISSUE THREAD

**Issue by ggKismet** [loot/loot#975]
Not much to say, this happens kind of randomly and this is the first time i've done a debug log:

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2138927/LOOTDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Unfortunately that doesn't contain any useful information. Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by ggKismet** [comment]
thats weird, because it *was* ticked on when it made that log..
well trying the program again, and it doesnt seem to be crashing anymore. I havent changed anything since.. I guess ill come back to this again if it happens..

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
