### ISSUE TITLE
Cannot read property 'getElementsByClassName' of null // Fallout 4

### ISSUE THREAD

**Issue by MrMisterBean** [loot/loot#976]
I just did a clean install of Fallout 4 after experiencing some issues so I have no idea why this issue is happening. Never had any issues with Skyrim (SE) and nothing with Fallout up until this point. 
The only thing I have installed is the script extender.
I also have no knowledge of coding or anything of the sort so if this is really obvious/not an issue that's why.

**Comment by CptMcSplody** [comment]
@MrMisterBean Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by MrMisterBean** [comment]
I cleaned my master files while waiting for a response and the issue is no longer occurring..
