### ISSUE TITLE
Failed to sort plugins

### ISSUE THREAD

**Issue by EpicRage** [loot/loot#977]
when I try and sort the fo4 plugins, i get that error. tells me there is a general message, but i see nothing new on the main screen. doesnt show any plugins or anything. masterlist updates fine, but no plugins show up. i ran it outside of mo2 and it showed the base dlcs for fo4, but when i run it through mo2, it doesnt work. even run as admin.

**Comment by WrinklyNinja** [comment]
Please post your full debug log with debug logging enabled, see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by EpicRage** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2153095/LOOTDebugLog.txt)

this is the log, but it doesnt look like this gives any debug errors. i dont know much coding but whenever i see debug logs they are usually thousands of lines long, this ones only a few hundred. posted anyway, but the exact error message if you can even call it that is "failed to sort plugins: details, see general messages for details" and then nothing shows up for general messages. just  latest loot thread and  f4se is up to date.
appreciate the help

**Comment by EpicRage** [comment]
the file is there but it wont let me upload it. do i have the change the file type?

**Comment by WrinklyNinja** [comment]
Ah, you may need to rename it to end in `.txt`.

**Comment by EpicRage** [comment]
[userlist.txt](https://github.com/loot/loot/files/2154161/userlist.txt)

yeah that worked, here you go

**Comment by WrinklyNinja** [comment]
Well, that's unexpectedly empty... Can you also upload your settings.toml (you'll need to change its extension too)? You may be using an older masterlist branch for some reason.

**Comment by EpicRage** [comment]
[settings.txt](https://github.com/loot/loot/files/2161907/settings.txt)

**Comment by WrinklyNinja** [comment]
Hmm, that all looks fine too... You've tried updating the masterlist?

**Comment by EpicRage** [comment]
yeah i updated the masterlist, 0203bbb and the masterlist date is 7/3/18

**Comment by EpicRage** [comment]
it shows just the dlc as files, but no mods
![loot 1](https://user-images.githubusercontent.com/40732518/42355087-0ba5bebe-8080-11e8-9a78-563505c8e599.PNG)
![loot 2](https://user-images.githubusercontent.com/40732518/42355088-0bbf02b6-8080-11e8-8474-6a62e79ac1f1.PNG)

this is what i get when i run it outside of mo2. i dont know why it shows the pipboy, i think that one was a creationclub dlc so thats why thats there, not too sure

**Comment by WrinklyNinja** [comment]
Well, you won't see any plugins installed through MO2 if you run LOOT separately, but since you only get errors when running LOOT through MO2, there's not much I can do about it.

**Comment by EpicRage** [comment]
ok so thanks for the lazy ass solution. there has to be some reason why its not working because it used to work just fine. u asked for 3 files and you there is obviously something wrong because it doesnt work. could it be installed in the wrong area? wrong version? pretty bs solution, but i guess i have to troubleshoot this myself since its an "invalid bug" thanks

**Comment by WrinklyNinja** [comment]
If LOOT works fine on its own, then MO is causing issues and I can't do anything about that. You can try getting help from the MO developers about it, but I'd advise you learn to be less rude before doing so.
