### ISSUE TITLE
New Vegas is not shown in Game List

### ISSUE THREAD

**Issue by Wastelandmatrix** [loot/loot#979]
Hey,

Fallout 4, Skyrim SE and Fallout 3 are shown in my game list to check load order.
But Fallout new Vegas isn't. It is installed on the same harddrive as the others.
Reinstalling LOOT did not help.
Any Idea?

**Comment by WrinklyNinja** [comment]
Have you tried running NV's launcher? The Registry entry is probably missing.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
