### ISSUE TITLE
Failed to sort - Cyclic Interaction (Skyrim)

### ISSUE THREAD

**Issue by Brucien** [loot/loot#980]
Trying to add mods after STEP Guide install:

Failed to sort plugins. Details: Cyclic interaction detected between "ELE_Legendary_Lite.esp" and "STEP Extended Patch.esp". Back cycle: STEP Extended Patch.esp, Alternate Start - Live Another Life.esp, ELE_Legendary_Lite.esp

https://www.nexusmods.com/skyrim/mods/9557
https://www.nexusmods.com/skyrim/mods/11
https://www.nexusmods.com/skyrim/mods/59733

**Comment by Brucien** [comment]
Forgot to add, sorts fine w/o Alternate start.

**Comment by WrinklyNinja** [comment]
@CptMcSplody Have you had a look at this?
@Brucien Is this still a problem with the latest masterlist?

**Comment by CptMcSplody** [comment]
@WrinklyNinja It's not a LOOT issue, it was a MO2 issue, they had not upgraded the api version for the built in sort.

**Comment by CptMcSplody** [comment]
@WrinklyNinja Log with `STEP Extended Patch.esp` set to default group.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2177026/LOOTDebugLog.txt)

**Comment by Brucien** [comment]
@WrinklyNinja I've just left Alternate Start deactivated in the meantime.

Will try to get it working after work tonite, after checking grouping

**Comment by CptMcSplody** [comment]
https://github.com/loot/skyrim/pull/194/commits/39e1171

I've set `ELE_Legendary_Lite.esp` to load after `Alternate Start - Live Another Life.esp`.

**Comment by Brucien** [comment]
Just enabled Alternate Start and everything sorted fine. Thanks!

**Comment by CptMcSplody** [comment]
Okay so I think I figured out why this happened. 
`ELE_Legendary_Lite.esp` is a master of `STEP Extended Patch.esp`.
`STEP Extended Patch.esp` is in a group above default but below `ELE_Legendary_Lite.esp` group.
So if there is an unrelated mod in a group between them, it will cause a cyclic.
This is why adding a load after rule to ELE resolved it.
Moving `STEP Extended Patch.esp` to default would also work, or moving it to the same group as `ELE_Legendary_Lite.esp` or higher.
