### ISSUE TITLE
Loot cyclic interaction detected

### ISSUE THREAD

**Issue by Shiyano** [loot/loot#983]
Cyclic interaction detected between "IW_SRCEO_Patch.esp" and "MLU.esp". Back cycle: MLU.esp, ISC_MRU_patch.esp, Wildcat - Combat of Skyrim.esp, UltimateCombat.esp, Skyrim Revamped - Complete Enemy Overhaul.esp, IW_SRCEO_Patch.esp

MLU has low priority overrides, no meta data on IW_SRCEO, Ultimate Combat loads after Wildcat, Skyrim Revamped loads after Ultimate Combat, Wildcat is sorted by loot, no metadata on ISC MRU.

I tried playing Skyrim again with my set of mods from last month and didn't have this problem, now after trying to sort my mods after trying to play Skyrim again gives me this problem.

I also took out everything from MLU and just used it's loot and then took out SRCEO's loot using SSEdit if it helps.

I tried disabling all above mods and for some reason it still shows me that error.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2220407/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
@Shiyano If your moving MLU.esp to low priority overrides then you will also need to move its patches as well.

Move these to low priority overrides & any patches they have as well.

UltimateCombat.esp
Skyrim Revamped - Complete Enemy Overhaul.esp
IW_SRCEO_Patch.esp
ISC_MRU_patch.esp

**Comment by Shiyano** [comment]
Fixed it. thanks!
