### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by ianne7d** [loot/loot#984]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2251419/LOOTDebugLog.txt)

I have absolutely no clue what caused this or why, started a few weeks ago, as soon as i hit sort, it pulls up skyrim SE and only skyrim SE, even if Fallout 4 is selected.

**Comment by WrinklyNinja** [comment]
```
[19:13:27.433289] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: HEAD: libgit2 error
```

Somehow that file got corrupted, just delete your `C:/Users/Gizmo/AppData/Local/LOOT/Skyrim Special Edition/.git` folder and run the masterlist update again.

**Comment by Freso** [comment]
No reply for over a month, closing.
