### ISSUE TITLE
esplugin error code: 5

### ISSUE THREAD

**Issue by Thejiffiness** [loot/loot#985]
Something went wrong with the latest update to LOOT, this esp in question worked fine last time I played and I had not switched anything around either so this has to be a false positive. 
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2252162/LOOTDebugLog.txt)

Attached is the log. Thank you Wrinkley for your amazing work and anyone else involved.

**Comment by WrinklyNinja** [comment]
Can you provide a link to the plugin?

**Comment by pStyl3** [comment]
It's probably [this one](https://www.nexusmods.com/fallout3/mods/60).

**Comment by Thejiffiness** [comment]
pStyl3 it is, wrinkly ninja. https://www.nexusmods.com/fallout3/mods/60
