### ISSUE TITLE
No tag editing pane appears

### ISSUE THREAD

**Issue by Darklocq** [loot/loot#988]
I'm using 0.13.1.0 in Windows 10 (in a VM).  Loot seems to work fine at the basic level - downloaded master list, reported issues with particular mod, sorted the list, and applied the sort, etc.

But it will not give the bash tag editing pane (the mod-specific interface with Main, Load After, Requirements, etc.).  Double-clicking and left- or ctrl-clicking on the mod name (on either side of the main interface) does nothing.

**Comment by Darklocq** [comment]
Never mind.  I set the app to "Run this program as an administrator" (in Windows Explorer, right-click the app, pick Properties > Compatiblity).  I probably should have thought of this earlier, but will plead that I'm a Mac guy, so the vagaries of Windows do not always come to mind immediately.

It still doesn't work very reliably.  Sometimes after opening this feature once, I can't do it again and have to restart the app.

**Comment by Freso** [comment]
It really shouldn't need to run as administrator. Could you disable that again and go through the motions outlined at https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html (notably supplying debug logs)?

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Comment by Darklocq** [comment]
Sorry to have spaced this completely. I can confirm that this issue went away for me, by at least September-ish if not later in August, so this is definitely close-worthy.
