### ISSUE TITLE
LOOT plugin cards has wrong logic for showing plugins as masters

### ISSUE THREAD

**Issue by Freso** [loot/loot#990]
https://github.com/loot/loot/blob/00bda5942defbfc9ed2586a3f78c437d7c129ffc/src/gui/html/elements/loot-plugin-card.js#L194

However, ESL-tagged `.esp` files are not considered masters, even if all `.esl` files are. It should probably do a check like `this.$.isMaster.hidden = !this.data.isMaster || this.data.fileName[-4:] == '.esl' ;` (or whatever the equivalent would be).

**Comment by WrinklyNinja** [comment]
`isMaster` and `isLightMaster` both come from esplugin through loot-api, and respect file extensions as you'd expect, so the `isLightMaster` check could be dropped entirely.
