### ISSUE TITLE
Cyclic interaction detected between "SoS_ELFX+Enhancer+Weathers_Patch.esp". Back cycle: ELE_SSE.esp, SoS_ELE_Patch.esp, ELFXEnhancer.esp, SoS_ELFX+Enhancer+Weathers_Patch.esp

### ISSUE THREAD

**Issue by dalvin0531** [loot/loot#992]
Getting error once I try to sort my plug in. Trying to resolve an issue with "skse64 not running" error in game. Hoping this fix will solve issue. I'm new to all of this btw.

**Comment by WrinklyNinja** [comment]
This is almost certainly unrelated to your SKSE issue.

**Comment by CptMcSplody** [comment]
You can't have 'ELE_SSE.esp' and 'ELFXEnhancer.esp' active at the same time, both mods are doing the same thing.
