### ISSUE TITLE
Differentiate between "light" plugins and "regular" plugins in "active plugins" count

### ISSUE THREAD

**Issue by Freso** [loot/loot#994]
Currently the "active plugins" show the number of all plugins, regardless of type. For FO4 and SSE it might be helpful to show a count of both "active (full/regular) plugins" and "active light/ESL plugins" for people relying on those numbers to figure out how close they are to hitting the(ir) load order plugin limit.

**Comment by WrinklyNinja** [comment]
Good idea, though we don't currently have any GUI differences between games beyond some operations being disabled (e.g. redate plugins), so that would be new (but not necessarily very complicated).

**Comment by Ortham** [comment]
It took three and a half years, but this is done in 05b7f402c1a448119390c9c08d04d17f3b233043.
