### ISSUE TITLE
Lack of full CR LF in plugins.txt causes Skyrim VR not to load mods

### ISSUE THREAD

**Issue by confuded** [loot/loot#996]
On Windows 10 using Skyrim VR on steam and NMM. When LOOT is run it takes the plugins.txt list from the "Skyrim Special. Edition" folder in AppData where NMM creates plugins.txt, sorts the plugins and creates a new plugins.txt in the Skyrim VR folder. This new plugins.txt only has LF, while the one in the SE folder has CRLF. Without CRLF the game does not load the mods. Replacing LF with CRLF (using Notepad++) makes the game load the mods.

Funny, how the issue wal already reported #279 and declared a non issues as it was irrelevant for vanilla Skyrim it seems.

**Comment by confuded** [comment]
Uploaded to some random file service [here](https://files.fm/u/jszefrgy).

Actually, I just ran LOOT again and despite being LF only the mods still loaded.
Initially (after running Skyrim a few times, the loading mods and running LOOT) though the mods refused to be loaded unless I added CRLF instead of LF. I wonder if I add more mods and run LOOT again (i.e. with just LF) will they load...

**Comment by WrinklyNinja** [comment]
Well, if you can figure out what's happening that would be good. I don't really want to make a change without understanding the underlying problem.

**Comment by confuded** [comment]
I have this ticket open for a month in a tab on my phone but didnt have the time to touch my VR headset. I will get around to it as soon as i have time :-/.

**Comment by confuded** [comment]
Nevermind... I can't reproduce this anymore. I've added [this ](https://www.nexusmods.com/skyrimspecialedition/mods/1296/) mod for testing, but it seems not to work be it in LF or CR+LF.
Then I tried removing "Book covers" and leaving it at LF only and it detected the change.

I guess something else was preventing the game from loading mods when I initially changed from LF to LF+CR.

**Comment by WrinklyNinja** [comment]
OK, closing this then.
