### ISSUE TITLE
[Minor] [Feature Request] Allow Use Of `.dll` extension files with `inc` Key

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#997]
Currently a plug-in, `.dll` or `.exe` can be used in `req` key entries.
Where as only a plug-in can be used with the `inc` key.

Some plug-in files such as `SunDaytimeNorth_MM_default.esp` & `SunDaytimeSouth.esp` from 
[Majestic Mountains](https://www.nexusmods.com/skyrimspecialedition/mods/11052) are incompatible with ENBSeries.

As ENBSeries only uses `.dll` files in the data folder it cannot be used with the `inc` key.

Though as this is the first case I've encountered of a plug-in being incompatible with a `.dll`.
A custom message with a conditional check should be sufficient at the moment.

I'll update this issue if I encounter any more plug-in's with a `.dll` incompatibility.

**Comment by WrinklyNinja** [comment]
Classifying this as bug as it's supposed to show messages for incompatible files if they're present, unless they're plugins, in which case they also need to be active.

**Comment by WrinklyNinja** [comment]
Fixed in 5928d325f0c3b4145aecb309b787ee788677f231.
