### ISSUE TITLE
Cyclical Interaction Detected

### ISSUE THREAD

**Issue by Shenrias** [loot/loot#998]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2321807/LOOTDebugLog.txt)

I've been using LOOT for a while now and have never had a problem like this before. I did all I could to try and fix it but I've run out of options. Each time I tried to fix it the same thing came up:

Failed to sort plugins. Details: Cyclic interaction detected between "Open Cities Skyrim.esp" and "Immersive Citizens - AI Overhaul.esp". Back cycle: Immersive Citizens - AI Overhaul.esp, Requiem - Audio Overhaul for Skyrim.esp, Open Cities Skyrim.esp

Here's my Load Order:

  0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
  5  5     Unofficial Skyrim Legendary Edition Patch.esp
  6  6     SGHairPackBase.esm
  7  7     ApachiiHair.esm
  8  8     hdtHighHeel.esm
  9  9     ETaC - RESOURCES.esm
 10  a     Lanterns Of Skyrim - All In One - Main.esm
 11  b     RaceCompatibility.esm
 12  c     SexLab.esm
 13  d     SkyTEST-RealisticAnimals&Predators.esm
 14  e     ImCh.esm
 15  f     Campfire.esm
 16 10     Schlongs of Skyrim - Core.esm
 17 11     WM Flora Fixes.esp
 18 12     ImmersiveContent.esm
 19 13     RSkyrimChildren.esm
 20 14     TKChildren.esm
 21 15     ApachiiHairFemales.esm
 22 16     ApachiiHairMales.esm
 23 17     rcrnShaders.esp
 24 18     RCRNdgdb.esp
 25 19     SGHairPackAIO.esp
 26 1a     SkyUI.esp
 27 1b     Socially Alert Guards (Guard Dialogue Tweaks).esp
 28 1c     ICROL - Legendary.esp
 29 1d     datgrass .esp
 30 1e     Complete Crafting Overhaul_Remade.esp
 31 1f     Complete Alchemy & Cooking Overhaul.esp
 32 20     KS Hairdo's.esp
 33 21     LovelyHairstylesCE.esp
 34 22     Archery.esp
 35 23     CharacterMakingExtender.esp
 36 24     Dual Sheath Redux.esp
 37 25     Immersive Citizens - AI Overhaul.esp
 38 26     Immersive Citizens - OCS patch.esp
 39 27     FNIS.esp
 40 28     FNIS_PCEA2.esp
 41 29     FNISSexyMove.esp
 42 2a     MainMenu.esp
 43 2b     SOSRaceMenu.esp
 44 2c     UIExtensions.esp
 45 2d     UltimateDragons.esp
 46 2e     ETaC - Complete.esp
 47 2f     Hunterborn.esp
 48 30     B&W.esp
 49 31     IcePenguinWorldMap.esp
 50 32     ETaC & OB.esp
 51 33     RealisticNeedsandDiseases.esp
 52 34     Armor.esp
 53 35     FAMP2.esp
 54 36     Wild World.esp
 55 37     JemWM.esp
 56 38     heJemWMPatch.esp
 57 39     Hunterborn_CACO_Patch.esp
 58 3a     Sex Lab.esp
 59 3b     TheEyesOfBeauty.esp
 60 3c     CinematicFireFX.esp
 61 3d     Clouds.esp
 62 3e     HighElfSkinTones.esp
 63 3f     LindsMerEyes.esp
 64 40     Requiem.esp
 65 41     Requiem - Legendary Bugsmasher Edition.esp
 66 42     dD - Realistic Ragdoll Force - Realistic.esp
 67 43     XPMSE.esp
 68 44     Animals & Enemies.esp
 69 45     Survival.esp
 70 46     Open Cities Skyrim.esp
 71 47     Immersion.esp
 72 48     NPC & Children.esp
 73 49     M&F.esp
 74 4a     Apocalypse - The Spell Package.esp
 75 4b     RealisticRoomRental.esp
 76 4c     Character.esp
 77 4d     EnhancedCharacterEdit.esp
 78 4e     CFTO.esp
 79 4f     Requiem - WM Flora Fixes.esp
 80 50     Requiem - Standing Stone Rebalance.esp
 81 51     ELE_Legendary_Lite.esp
 82 52     SpiceOfLife - OrcLStrongholds.esp
 83 53     IP & W.esp
 84 54     PCR.esp
 85 55     Requiem for the Indifferent.esp

**Comment by CptMcSplody** [comment]
@Shenrias You'll have to enable debug logging in LOOT setting for a full log. Those short ones won't be of use. Can you also upload a copy of your userlist.yaml?

**Comment by CptMcSplody** [comment]
As a guess I'd say you added a rule to load `Immersive Citizens - AI Overhaul.esp` after `Open Cities Skyrim.esp`

**Comment by Shenrias** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/2321885/LOOTDebugLog.txt)

This is what my userlist.yaml looks like. I'm unable to copy it or anything so I just copied and pasted:

groups:
  - name: 'default'

**Comment by CptMcSplody** [comment]
```
[16:23:00.287360] [trace]: Plugin "Immersive Citizens - ELE patch.esp" belongs to group "default", setting after group plugins
[16:23:00.287378] [trace]: Plugin "Immersive Citizens - ELFXEnhancer patch.esp" belongs to group "default", setting after group plugins
[16:23:00.287392] [trace]: Plugin "Immersive Citizens - OCS patch.esp" belongs to group "default", setting after group plugins
[16:23:00.287406] [trace]: Plugin "Immersive Citizens - RRR patch.esp" belongs to group "default", setting after group plugins
```
Can you move `Immersive Citizens - OCS patch.esp` from default to the same group as the `Open Cities Skyrim.esp`

**Comment by CptMcSplody** [comment]
https://i.imgur.com/Hajr9Ic.png

**Comment by Shenrias** [comment]
Okay I did that but that didn't seem to complete fix the problem.

[LOOTDebugLog.txt](https://github.com/loot/loot/files/2321929/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
`Immersive Citizens - ELE patch.esp`
`Immersive Citizens - ELFXEnhancer patch.esp`

move both to lighting group.

FYI ELE & ELFXEnhancer are not compatible as the two mods do the same thing.

**Comment by Sharlikran** [comment]
Can you do me a favor please? I'm on my phone so I can't really tell you where all the yaml files are stored. However, you have a folder where the exe is and a folder for each masterlist. Then you have a userlist.yaml and I don't know if anything changed from the last version or not but you may have separate userlists. 

Please look for all of them and rename them. Dont try to make new ones just rename them.

Then sort with LOOT, letting it only sort with the masterlist. If you get the error then I need another favor. This is important though.

Go to the xEdit github, I'm on my phone so I can't link it. You can find links to version 3.2.45 or higher on the nexus in the sticky post.

Rename it to SSEEdit pr TES5Edit as needed depending on which skyrim it is.

Try to load all the plugins and if it also gives an error post the error from xEdit.

**Comment by Shenrias** [comment]
What should I rename them to? I've found 1 other userlist that made it to my downloads folder.

**Comment by Shenrias** [comment]
Never mind that last comment but how would I go about just sorting the masterlist? I tried sorting but I think LOOT may have tried to sort the whole list.

**Comment by Sharlikran** [comment]
Here is what I am going for. I acnt do two things. I can't install all your mods and i can't get loot to do what you want. Having a conversation in a forum of comments section limits how we communicate.

For that reason please try the steps as I have given them. I know you want loot to sort plugins and that is the goal, eventually.

So rename them to something like userlist.bak. I just want to keep them but rename them so loot can't find them.

1. Raname userlist
2. Try to sort with loot, if no error share that please. If you still get the error do step 3
3. Download a very recent version of the experimental version of xedit. This step is super important but only if step 2 fails.

If step 2 fails and you get an error load all your plugins with xedit and tell me if you get an error about editing being disabled or not. Please.

**Comment by Shenrias** [comment]
I did Step 3 and TES5Edit seemed to work just fine with my plugins but Step 2 did fail without the slightest change.

**Comment by CptMcSplody** [comment]
@Shenrias Can you try updating the master list and sorting again? I made a change to the master list.

**Comment by Sharlikran** [comment]
@CptMcSplody sorry for interjecting but please wait

**Comment by CptMcSplody** [comment]
No worries spotted an issue with sorting rules which would always cause a cyclic.

**Comment by Sharlikran** [comment]
@Shenrias There is a reason why xEdit worked and LOOT filed. xEdit has a new way to handle how it loads mods. It doesn't care about load order anymore, that idea of how you have a mod at [00] and the next one at [01] was done away with when the original author started trying to load more then 255 plugins. He discovered that it caused errors in other places because Bethesda restricts mods to work only from 00 to FE, but now with ESL files 00 to FD. LOOT may still work with the idea that all mods must have a number assigned to them in your load order and in plugins.txt.

So now make sure you follow these steps exactly.

1. Open xEdit, right click and choose select all. As shown below.

![image](https://user-images.githubusercontent.com/1912426/44634721-3cf67f80-a952-11e8-8a6b-27f388722703.png)

2. Once complete, and sorry it takes a while to build refs the first time, now once loaded I need multiple screen shots of the files. xEdit will be adding a number to the, despite what i said for clarity only. Take two screen shots if needed but I need to see your load order in xEdit now from your mod manager, LOOT, or plugins.txt. Pretty please.

![image](https://user-images.githubusercontent.com/1912426/44634736-7a5b0d00-a952-11e8-8c39-87c4f6a9b561.png)

So something like that. To get just xEdit press ALT + PRT-SCRN which will copy xEdit to the clipboard, and then CTRL + C into the comments section. You have 85 mods please show two or if needed three screen shots of all the plugins please.

**Comment by Sharlikran** [comment]
@Shenrias @CptMcSplody Opps I didn't see his message at first. I guess he found something in the masterlist. I apologize but I guess try sorting with LOOT first.

**Comment by Shenrias** [comment]
Okay so after I updated the masterlist I sorted it and it worked just fine. The problem has been completely resolved and I'm able to run LOOT without a problem. Thank you so much for solving my problem.

**Comment by CptMcSplody** [comment]
REsolved by https://github.com/loot/skyrim/commit/ad61b1498f2da44658f85b72cb89351220df8225

**Comment by Sharlikran** [comment]
Sorry @Shenrias I don't see LOOT make this error except when plugins are loading that have masters in an incorrect load order. I didn't intend to have you do anything unnecessary.  I'm glad it's working.

**Comment by Shenrias** [comment]
Don't worry about it, it's totally fine. I'm just glad to have gotten the help I needed so thanks.
