### ISSUE TITLE
Improve Cyclic Dependency Error Message

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#999]
pStyl3:
>Could the cyclic dependency error message be adjusted, so that it contains more information regarding what kind of cyclic dependency is detected?
>
>For example, let's say Plugin A has Plugin B as master through MAST record and Plugin B has Plugin A as master through MAST record aswell, this cycle would be caused directly through master dependency and not through LOOT (although LOOT detects it). Could LOOT tell this the user in some way or another?
>
>If a cycle is caused through bad user metadata, or better said, if a plugin involved in the cycle has any kind of user metadata, LOOT could tell the user that his user metadata might be the cause.
>
>Or if NONE of the plugins involved in the cycle has any user metadata, and no direct cyclic outside of LOOT's realm is detected, that reporting the issue through GitHub might be benefitial for everyone.
>
>The main goal I'm thinking off, is, to reduce the amount of confusion these error messages can potentially produce.

@CptMcSplody 
>>Failed to sort plugins. Details: Cyclic interaction detected between "Open Cities Skyrim.esp" and "Immersive Citizens - AI Overhaul.esp". Back cycle: Immersive Citizens - AI Overhaul.esp, Requiem - Audio Overhaul for Skyrim.esp, Open Cities Skyrim.esp
>>
>to
>>
>>Failed to sort plugins. 
Details: 
Cyclic interaction detected between
 "Open Cities Skyrim.esp" and "Immersive Citizens - AI Overhaul.esp". 
>>
>>Back cycle: 
Immersive Citizens - AI Overhaul.esp,
Requiem - Audio Overhaul for Skyrim.esp,
Open Cities Skyrim.esp
>>
>Even making it a bit more readable could help.

@WrinklyNinja 
>@pStyl3 LOOT can't really pick out one edge responsible for a cycle, if you've got a path that's master-masterlist req-group-records-userlist load after, you could say any one of them is responsible. I suppose the cycle checker could indicate the "strength" of the path: whether it's only due to plugin data, if there's masterlist metadata, or if there's userlist metadata. That'll need some work to implement, and needs some more discussion about how detailed/specific that information is.
@CptMcSplody changing how the cyclic error message is formatted is easy.

@Freso 
>I think just adding what levels are involved with the cyclicicity would be great (e.g., MAST/MAST, MAST/group-after,  MAST/after/userdata-group-after, …), but any further discussion should probably happen in GH issue to not get lost in the Depths of Discord.

**Comment by pStyl3** [comment]
However this will turn out, we should ideally make sure, that the error message is "user readable", at least as best as possible. It would be great if the message has more (detailed) information for LOOT masterlist maintainers, it would be even better if the user can understand the message better himself and as such, is more likely to solve his problem on his own.

**Comment by eFrysTon** [comment]
I agree that the reason for any step in the back cycle (group, user load after, masterlist load after, MAST dependency, ...) is essential

**Comment by Ortham** [comment]
Cyclic interaction error messages now look like:

> Cyclic interaction detected between "Dawnguard.esm" and "Skyrim.esm": Dawnguard.esm --[Masterlist Load After]-> Dragonborn.esm --[User Load After]-> Skyrim.esm --[Master]-> Dawnguard.esm

I don't think that's great, but I'm at a loss for how to indicate edge types better. Any ideas?

**Comment by ElminsterAU** [comment]
The direction of the arrows together with these descriptions does not make sense to me.
I read that as "dawnguard load after dragonborn", "dragonborn load after skyrim" and "skyrim has danwguard as master". Which is obviously nonsense.

**Comment by Ortham** [comment]
It's a path through the plugin graph, effectively going down the load order, and each label in the square brackets is the source of that connection, e.g. `Skyrim.esm --[Master]-> Dawnguard.esm` is saying that Dawnguard.esm will load after Skyrim.esm because the former has the latter as a master.

Obviously users shouldn't be expected to know how to interpret that correctly, but it's difficult for me to suggest better, because it makes perfect sense to me.

**Comment by pStyl3** [comment]
How about this variant:
>Cyclic interaction detected between "Dawnguard.esm" and "Skyrim.esm":
>
>Dawnguard.esm
[Masterlist Load After]
Dragonborn.esm
[User Load After]
Skyrim.esm
[Master]
Dawnguard.esm

**Comment by CptMcSplody** [comment]
Maybe keep it simple.
>Sorting error between "Dawnguard.esm" and "Skyrim.esm":
[Masterlist]
Skyrim.esm -> Dawnguard.esm -> Dragonborn.esm
[User Load After]
Dawnguard.esm -> Skyrim.esm
```

**Comment by pStyl3** [comment]
While certainly perferable for some, this might get too much to look at very quickly, A short and concise depiction of the important information is likely the best way to do this, I would say. With the plugins listed in usual "load order style" there shouldn't be any questions on how exactly the cyclic dependency message should be read (it's top to bottom as usual).

**Comment by Ortham** [comment]
OK, I've implemented the concise version, snapshot build [here](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.13.4-27-g4cd2631_update-api.7z).

**Comment by pStyl3** [comment]
The error window should be made scrollable, though.
https://abload.de/img/cyclicerror2s6d7f.png

**Comment by Ortham** [comment]
How's it with [this build](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.13.4-31-g2237d3f_update-api.7z)?

**Comment by pStyl3** [comment]
https://abload.de/img/unbenanntrmcww.png
Looks good.

**Comment by Ortham** [comment]
Done as of 0afe0c2eca9f1c582c89c359a59279dcd5c0bb8f.
